pkg/sql/compile/projection.go
pkg/sql/op/order/types.go
pkg/sql/op/relation/types.go
pkg/vm/pipeline/pipeline.go
pkg/vm/vm.go

issue #
Not Available
Not Available
Not Available

comment refactor

---

pkg/vm/engine/aoe/storage/db/shard_test.go
pkg/vm/engine/aoe/storage/metadata/v1/base.go
pkg/vm/engine/aoe/storage/metadata/v1/catalog.go
pkg/vm/engine/aoe/storage/metadata/v1/filter.go
pkg/vm/engine/aoe/storage/metadata/v1/metadata_test.go
pkg/vm/engine/aoe/storage/metadata/v1/node.go
pkg/vm/engine/aoe/storage/metadata/v1/processor.go
pkg/vm/engine/aoe/storage/metadata/v1/shard.go
pkg/vm/engine/aoe/storage/metadata/v1/table.go
pkg/vm/engine/aoe/storage/metadata/v1/types.go

issue #1039 
Not Available
Not Available
Not Available

implement metadata in-memory compaction and other updates

---

pkg/vm/engine/aoe/storage/metadata/v1/catalog.go
pkg/vm/engine/aoe/storage/metadata/v1/ctx.go
pkg/vm/engine/aoe/storage/metadata/v1/metadata_test.go
pkg/vm/engine/aoe/storage/metadata/v1/replayer.go
pkg/vm/engine/aoe/storage/metadata/v1/shard.go

issue #1023 
Not Available
Not Available
Not Available

replay shard snapshot log entry 

---

.github/workflows/build_matrixone.yml

issue #1042 
Not Available
Not Available
Not Available

[devops] Detect non-ascii characters in github action workflow

---

pkg/sql/ftree/build.go
pkg/sql/ftree/build_test.go
pkg/sql/ftree/condition.go
pkg/sql/ftree/node.go
pkg/sql/ftree/path.go
pkg/sql/ftree/relation.go
pkg/sql/ftree/tree.go
pkg/sql/ftree/types.go
pkg/sql/ftree/variable.go
pkg/sql/plan/query.go
pkg/sql/util/util.go

issue #983
Front-end code for f-tree construction
Not Available
Not Available

Add f-tree construction

---

README.md

- [x ] Documentation
issue #1067
An external user mentioned that the README lacks information about the OS MatrixOne supported. Users may get confused and waste time to set up an environment they suppose needed. Therefore, we added related info in README.
Not Available
Not Available

Added info about supported OS required by issue #1067.

---

README.md

issue #1067 
To address issue #1067, which asks for information about supported OS to be added in README.
Not Available
Not Available
Not Available

Added info about supported OS: Linux and MacOS for issue #1067

---

pkg/vm/engine/aoe/storage/metadata/v1/catalog.go
pkg/vm/engine/aoe/storage/metadata/v1/metadata_test.go
pkg/vm/engine/aoe/storage/metadata/v1/replayer.go
pkg/vm/engine/aoe/storage/metadata/v1/split.go

issue #744 
Not Available
Not Available
Not Available

replay for shard split

---

pkg/vm/driver/cube_driver.go
pkg/vm/engine/aoe/cmd/read/main.go
pkg/vm/engine/aoe/storage/db/db.go
pkg/vm/engine/aoe/storage/db/engine_test.go
pkg/vm/engine/aoe/storage/dbi/req.go
pkg/vm/engine/aoe/storage/layout/table/v1/data.go
pkg/vm/engine/aoe/storage/layout/table/v1/data_test.go
pkg/vm/engine/aoe/storage/layout/table/v1/iface/types.go
pkg/vm/engine/aoe/storage/layout/table/v1/tblk.go
pkg/vm/engine/aoe/storage/layout/table/v1/tblk_test.go
pkg/vm/engine/aoe/storage/mutation/base/types.go
pkg/vm/engine/aoe/storage/mutation/blk.go

issue #
Not Available
Not Available
Not Available

remove old get segmented index api and dependency code

---

pkg/vm/driver/cube_driver.go

issue #1080 
Not Available
Not Available
Not Available

Adjust the situation where aoe GetShardCheckpointId is 0

---

pkg/vm/engine/aoe/storage/metadata/v1/block.go
pkg/vm/engine/aoe/storage/metadata/v1/metadata_test.go
pkg/vm/engine/aoe/storage/metadata/v1/segment.go

issue #1082 
Not Available
Not Available

add idx for block metadata preparing for dataio refactor

---

pkg/vm/engine/aoe/storage/layout/dataio/blk_test.go
pkg/vm/engine/aoe/storage/layout/dataio/mockseg.go
pkg/vm/engine/aoe/storage/layout/dataio/segwriter.go
pkg/vm/engine/aoe/storage/layout/dataio/sortedseg.go
pkg/vm/engine/aoe/storage/layout/table/v1/col/part.go

issue #1063 #1082 
Not Available
Not Available
Not Available

(aoe): refactor sorted segment

---

cmd/generate-config/system_vars_def.toml
pkg/config/system_vars.go
pkg/config/system_vars_test.go
pkg/frontend/load.go
pkg/frontend/test/system_vars_config.toml

issue #1045
Not Available
Not Available
Not Available

add max entry bytes for the cube

---

pkg/sql/ftree/build.go
pkg/sql/ftree/condition.go
pkg/sql/ftree/node.go
pkg/sql/ftree/relation.go
pkg/sql/ftree/types.go
pkg/sql/plan/build_test.go
pkg/sql/plan/expr.go
pkg/sql/plan/projection.go
pkg/sql/plan/query.go
pkg/sql/plan/types.go
pkg/sql/plan/where.go

issue #983
Not Available
Not Available
Not Available

Refining the  construction of ftree

---

pkg/catalog/catalog.go
pkg/catalog/errors.go
pkg/sql/build/create.go
pkg/vm/engine/aoe/common/helper/helper.go
pkg/vm/engine/aoe/mergesort/mergesort.go
pkg/vm/engine/aoe/model.go
pkg/vm/engine/aoe/storage/adaptor/meta.go
pkg/vm/engine/aoe/storage/db/db.go
pkg/vm/engine/aoe/storage/layout/dataio/blk_test.go
pkg/vm/engine/aoe/storage/layout/dataio/blkwriter.go
pkg/vm/engine/aoe/storage/metadata/v1/schema.go
pkg/vm/metadata/types.go

issue #991
Not Available
Not Available
Not Available

Support primary key

---

pkg/vm/engine/aoe/storage/db/sched/flushmemblk.go
pkg/vm/engine/aoe/storage/metadata/v1/base.go
pkg/vm/engine/aoe/storage/metadata/v1/block.go
pkg/vm/engine/aoe/storage/metadata/v1/types.go

issue #
Not Available
Not Available
Not Available

fix occasional unit test data race error

---

pkg/sql/build/create.go
pkg/sql/build/insert.go
pkg/sql/unittest/sql_test.go

issue #1094 
code refactor for insert value range check
use number to check range but not convert to string.
Not Available
Not Available

Code Refactor for insert value range check

---

pkg/vm/engine/aoe/storage/db/db_test.go
pkg/vm/engine/aoe/storage/db/sched/scheduler.go
pkg/vm/engine/aoe/storage/db/snapshot.go
pkg/vm/engine/aoe/storage/metadata/v1/database.go

issue #170 #744 
Not Available
Not Available
Not Available

(aoe): support AOE snapshot - phase ⅠⅠ

---

pkg/vm/engine/aoe/storage/db/snapshot.go
pkg/vm/engine/aoe/storage/metadata/v1/catalog.go
pkg/vm/engine/aoe/storage/metadata/v1/snapshot.go

issue #170 #744
Not Available
Not Available
Not Available

fix data race and improve snapshot prepare load

---

pkg/vm/engine/aoe/storage/metadata/v1/base.go
pkg/vm/engine/aoe/storage/metadata/v1/block.go
pkg/vm/engine/aoe/storage/metadata/v1/catalog.go
pkg/vm/engine/aoe/storage/metadata/v1/database.go
pkg/vm/engine/aoe/storage/metadata/v1/database_test.go
pkg/vm/engine/aoe/storage/metadata/v1/metadata_test.go
pkg/vm/engine/aoe/storage/metadata/v1/replayer.go
pkg/vm/engine/aoe/storage/metadata/v1/segment.go
pkg/vm/engine/aoe/storage/metadata/v1/table.go
pkg/vm/engine/aoe/storage/metadata/v1/types.go
pkg/vm/engine/aoe/storage/wal/shard/index.go
pkg/vm/engine/aoe/storage/wal/shard/mock.go

issue #676 #1039 
Not Available
Not Available
Not Available

update for data replay and compaction 

---

pkg/vm/engine/aoe/storage/db/db_test.go
pkg/vm/engine/aoe/storage/db/open_test.go
pkg/vm/engine/aoe/storage/db/replay_test.go
pkg/vm/engine/aoe/storage/db/sched/commitblk.go
pkg/vm/engine/aoe/storage/events/meta/types_test.go
pkg/vm/engine/aoe/storage/layout/dataio/tblk.go
pkg/vm/engine/aoe/storage/layout/table/v1/data_test.go
pkg/vm/engine/aoe/storage/layout/table/v1/tblk_test.go
pkg/vm/engine/aoe/storage/metadata/v1/base.go
pkg/vm/engine/aoe/storage/metadata/v1/block.go
pkg/vm/engine/aoe/storage/metadata/v1/catalog.go
pkg/vm/engine/aoe/storage/metadata/v1/database.go
pkg/vm/engine/aoe/storage/metadata/v1/database_test.go
pkg/vm/engine/aoe/storage/metadata/v1/metadata_test.go
pkg/vm/engine/aoe/storage/metadata/v1/node.go
pkg/vm/engine/aoe/storage/metadata/v1/replayer.go
pkg/vm/engine/aoe/storage/metadata/v1/segment.go
pkg/vm/engine/aoe/storage/metadata/v1/table.go
pkg/vm/engine/aoe/storage/metadata/v1/types.go
pkg/vm/engine/aoe/storage/mutation/blk.go
pkg/vm/engine/aoe/storage/wal/shard/index.go
pkg/vm/engine/aoe/storage/wal/types.go

issue #744 #170 
1. Remove all old log index logic
2. More pretty prints for debug
3. Add version chain operations
4. More validations
Not Available
Not Available

update for log index calculation and others

---

pkg/vm/engine/aoe/storage/db/db.go
pkg/vm/engine/aoe/storage/db/db_test.go
pkg/vm/engine/aoe/storage/db/gcreqs/compaction.go
pkg/vm/engine/aoe/storage/db/gcreqs/dropdb.go
pkg/vm/engine/aoe/storage/db/open.go
pkg/vm/engine/aoe/storage/db/replay.go
pkg/vm/engine/aoe/storage/db/replay_test.go
pkg/vm/engine/aoe/storage/metadata/v1/catalog.go
pkg/vm/engine/aoe/storage/metadata/v1/database.go
pkg/vm/engine/aoe/storage/metadata/v1/database_test.go
pkg/vm/engine/aoe/storage/metadata/v1/entry.go
pkg/vm/engine/aoe/storage/metadata/v1/listener.go
pkg/vm/engine/aoe/storage/metadata/v1/metadata_test.go
pkg/vm/engine/aoe/storage/metadata/v1/processor.go
pkg/vm/engine/aoe/storage/metadata/v1/replayer.go
pkg/vm/engine/aoe/storage/metadata/v1/schema.go
pkg/vm/engine/aoe/storage/metadata/v1/split.go
pkg/vm/engine/aoe/storage/metadata/v1/table.go
pkg/vm/engine/aoe/storage/options.go
pkg/vm/engine/aoe/storage/wal/shard/manager.go
pkg/vm/engine/aoe/storage/wal/types.go

issue #1039 #744 #170 
Not Available
Not Available
Not Available

update for compaction and data replay

---

pkg/catalog/catalog.go
pkg/catalog/catalog_test.go
pkg/catalog/errors.go
pkg/sql/build/build.go
pkg/sql/build/index.go
pkg/sql/compile/compile.go
pkg/sql/compile/scope.go
pkg/sql/compile/types.go
pkg/sql/op/createIndex/create.go
pkg/sql/op/createIndex/type.go
pkg/sql/op/dropIndex/drop.go
pkg/sql/op/dropIndex/type.go
pkg/sql/unittest/sql_test.go
pkg/vm/engine/aoe/common/helper/helper.go
pkg/vm/engine/aoe/common/helper/helper_test.go
pkg/vm/engine/aoe/engine/engine_test.go
pkg/vm/engine/aoe/engine/relation.go
pkg/vm/engine/aoe/local/relation.go
pkg/vm/engine/aoe/model.go
pkg/vm/engine/aoe/storage/adaptor/meta.go
pkg/vm/engine/aoe/storage/layout/dataio/blk_test.go
pkg/vm/engine/memEngine/relation.go
pkg/vm/engine/spillEngine/relation.go
pkg/vm/engine/types.go

issue #992 
Not Available
Not Available
Not Available

Create/Drop Index Support

---

pkg/vm/engine/aoe/storage/aoedb/db.go
pkg/vm/engine/aoe/storage/db/db.go
pkg/vm/engine/aoe/storage/db/gcreqs/dropdb.go
pkg/vm/engine/aoe/storage/db/shard_test.go
pkg/vm/engine/aoe/storage/metadata/v1/database_test.go
pkg/vm/engine/aoe/storage/metadata/v1/helper.go
pkg/vm/engine/aoe/storage/metadata/v1/metadata_test.go
pkg/vm/engine/aoe/storage/metadata/v1/replayer.go
pkg/vm/engine/aoe/storage/metadata/v1/table.go
pkg/vm/engine/aoe/storage/testutils/helpers.go

issue #1039 
Not Available
Not Available
Not Available

update for gc and add more ut

---

pkg/vm/engine/aoe/engine/engine_test.go
pkg/vm/engine/aoe/engine/reader.go

issue #
Not Available
Not Available
Not Available

Update for reader and add more ut

---

pkg/vm/engine/aoe/storage/db/db.go
pkg/vm/engine/aoe/storage/db/db_test.go
pkg/vm/engine/aoe/storage/db/engine_test.go
pkg/vm/engine/aoe/storage/db/factories/mutblock.go
pkg/vm/engine/aoe/storage/db/open_test.go
pkg/vm/engine/aoe/storage/db/replay_test.go
pkg/vm/engine/aoe/storage/db/shard_test.go
pkg/vm/engine/aoe/storage/db/snapshot_test.go
pkg/vm/engine/aoe/storage/layout/base/file.go
pkg/vm/engine/aoe/storage/layout/dataio/manager.go
pkg/vm/engine/aoe/storage/layout/dataio/mockseg.go
pkg/vm/engine/aoe/storage/layout/dataio/sortedseg.go
pkg/vm/engine/aoe/storage/layout/dataio/tblk.go
pkg/vm/engine/aoe/storage/layout/dataio/unsortedseg.go
pkg/vm/engine/aoe/storage/metadata/v1/catalog.go
pkg/vm/engine/aoe/storage/metadata/v1/database.go
pkg/vm/engine/aoe/storage/metadata/v1/metadata_test.go
pkg/vm/engine/aoe/storage/metadata/v1/processor.go
pkg/vm/engine/aoe/storage/metadata/v1/replayer.go
pkg/vm/engine/aoe/storage/metadata/v1/snapshot.go
pkg/vm/engine/aoe/storage/testutils/helpers.go
pkg/vm/engine/aoe/storage/wal/shard/mock.go

issue #170 
1. Unsorted segment file manages transient block file
2. Data replay for the snapshot log entry
3. Change the shard id logic not to share shard id between databases
4. Update UT
Not Available
Not Available

update for unsorted segment file and snapshot data replay

---

pkg/vm/engine/aoe/storage/aoedb/db.go
pkg/vm/engine/aoe/storage/db/db.go
pkg/vm/engine/aoe/storage/db/db_test.go
pkg/vm/engine/aoe/storage/db/gcreqs/dropdb.go
pkg/vm/engine/aoe/storage/db/gcreqs/droptbl.go
pkg/vm/engine/aoe/storage/db/impl.go
pkg/vm/engine/aoe/storage/db/open.go
pkg/vm/engine/aoe/storage/db/replay.go
pkg/vm/engine/aoe/storage/db/replay_test.go
pkg/vm/engine/aoe/storage/db/shard_test.go
pkg/vm/engine/aoe/storage/db/snapshot_test.go
pkg/vm/engine/aoe/storage/events/memdata/createtbl.go
pkg/vm/engine/aoe/storage/layout/table/v1/data.go
pkg/vm/engine/aoe/storage/layout/table/v1/iface/types.go
pkg/vm/engine/aoe/storage/layout/table/v1/tblk.go
pkg/vm/engine/aoe/storage/memtable/v1/collection.go
pkg/vm/engine/aoe/storage/memtable/v1/manager.go
pkg/vm/engine/aoe/storage/metadata/v1/base.go
pkg/vm/engine/aoe/storage/metadata/v1/catalog.go
pkg/vm/engine/aoe/storage/metadata/v1/database.go
pkg/vm/engine/aoe/storage/metadata/v1/idempotent.go
pkg/vm/engine/aoe/storage/metadata/v1/processor.go
pkg/vm/engine/aoe/storage/metadata/v1/replayer.go
pkg/vm/engine/aoe/storage/metadata/v1/snapshot.go
pkg/vm/engine/aoe/storage/mutation/buffer/limiter.go
pkg/vm/engine/aoe/storage/testutils/config/options.go
pkg/vm/engine/aoe/storage/wal/shard/manager.go
pkg/vm/engine/aoe/storage/wal/types.go

issue #170 
Not Available
Not Available
Not Available

update for snapshot and fix some bugs

---

pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
pkg/sql/parsers/scanner/scanner.go
pkg/sql/parsers/scanner/scanner_test.go

Fix failed to select if value is "C:\Program Files(x86)"

---

pkg/vm/engine/aoe/storage/aoedb/db.go
pkg/vm/engine/aoe/storage/db/db.go
pkg/vm/engine/aoe/storage/db/impl.go
pkg/vm/engine/aoe/storage/db/replay_test.go
pkg/vm/engine/aoe/storage/layout/table/v1/data.go
pkg/vm/engine/aoe/storage/layout/table/v1/iface/types.go
pkg/vm/engine/aoe/storage/memtable/v1/collection.go
pkg/vm/engine/aoe/storage/metadata/v1/base.go
pkg/vm/engine/aoe/storage/metadata/v1/catalog.go
pkg/vm/engine/aoe/storage/metadata/v1/database.go
pkg/vm/engine/aoe/storage/metadata/v1/idempotent.go
pkg/vm/engine/aoe/storage/metadata/v1/table.go
pkg/vm/engine/aoe/storage/wal/shard/index.go

issue #170 
Not Available
Not Available
Not Available

idempotence check during replay

---

pkg/sql/compile/exec.go
pkg/sql/compile/types.go
pkg/sql/plan/build.go
pkg/sql/plan/create_database.go
pkg/sql/plan/create_index.go
pkg/sql/plan/create_table.go
pkg/sql/plan/drop_database.go
pkg/sql/plan/drop_index.go
pkg/sql/plan/drop_table.go
pkg/sql/plan/types.go
pkg/vm/engine/types.go

issue #
Not Available
Not Available
Not Available

DDL codes for build and compile

---

pkg/frontend/mysql_cmd_executor.go
pkg/sql/build/build.go
pkg/sql/build/create.go
pkg/sql/build/show.go
pkg/sql/compile/compile.go
pkg/sql/compile/scope.go
pkg/sql/compile/types.go
pkg/sql/op/showColumns/show.go
pkg/sql/op/showColumns/types.go
pkg/sql/parsers/dialect/mysql/mysql_lexer.go
pkg/sql/parsers/sqlparse.go
pkg/sql/unittest/sql_test.go
pkg/vm/engine/aoe/common/helper/helper.go
pkg/vm/engine/aoe/model.go
pkg/vm/metadata/types.go

Feature
issue #819
Like expression: support
field: support
Type: support
Null: support
Key: support primary key
default: support constant expression
Extra: support

support show columns (#819)

---

pkg/catalog/catalog.go

issue #1156 
Not Available
Not Available
Not Available

not use string type to store non-utf-8 encoded bytes

---

cmd/db-server/main.go

issue #1153 
Not Available
Not Available
Not Available

Add log information before mo-server shuts down

---

pkg/vm/driver/handler_aoe.go
pkg/vm/engine/aoe/storage/adaptor/meta.go
pkg/vm/engine/aoe/storage/db/engine_test.go
pkg/vm/engine/aoe/storage/db/replay_test.go
pkg/vm/engine/aoe/storage/db/shard_test.go
pkg/vm/engine/aoe/storage/dbi/req.go

issue #1164 
Not Available
Not Available
Not Available

Create&Drop table set the offset and size of the index

---

pkg/sql/colexec/extend/overload/and.template
pkg/sql/colexec/extend/overload/cast.template
pkg/sql/colexec/extend/overload/eq.template
pkg/sql/colexec/extend/overload/ge.template
pkg/sql/colexec/extend/overload/gt.template
pkg/sql/colexec/extend/overload/le.template
pkg/sql/colexec/extend/overload/lt.template
pkg/sql/colexec/extend/overload/minus.template
pkg/sql/colexec/extend/overload/mod.template
pkg/sql/colexec/extend/overload/mult.template
pkg/sql/colexec/extend/overload/ne.template
pkg/sql/colexec/extend/overload/or.template
pkg/sql/colexec/extend/overload/plus.template
pkg/sql/colexec/extend/overload/unaryops.template
pkg/sql/compile/exec.go
pkg/sql/compile/scope.go
pkg/sql/plan/create_index.go
pkg/sql/plan/types.go

issue #
Add run function for DDL, and delete some error code in overload template.
Not Available
Not Available

Add DDL Run Function

---

pkg/frontend/mysql_cmd_executor.go

issue #1169 
Not Available
Not Available
Not Available

fix batch.Zs misuse

---

pkg/vm/engine/aoe/engine/engine_test.go
pkg/vm/engine/aoe/engine/reader.go
pkg/vm/engine/aoe/engine/relation.go
pkg/vm/engine/aoe/engine/types.go

-  [x] Code Refactoring
issue #
Not Available
Not Available
Not Available

Adapt storage interface of factor

---

pkg/vm/engine/aoe/storage/common/filenames.go
pkg/vm/engine/aoe/storage/db/db.go
pkg/vm/engine/aoe/storage/db/db_test.go
pkg/vm/engine/aoe/storage/db/migration.go
pkg/vm/engine/aoe/storage/db/open.go
pkg/vm/engine/aoe/storage/db/snapshot.go
pkg/vm/engine/aoe/storage/db/split.go
pkg/vm/engine/aoe/storage/db/split_test.go
pkg/vm/engine/aoe/storage/metadata/v1/catalog.go
pkg/vm/engine/aoe/storage/metadata/v1/commit.go
pkg/vm/engine/aoe/storage/metadata/v1/ctx.go
pkg/vm/engine/aoe/storage/metadata/v1/metadata_test.go
pkg/vm/engine/aoe/storage/metadata/v1/snapshot.go
pkg/vm/engine/aoe/storage/metadata/v1/split.go
pkg/vm/engine/aoe/storage/metadata/v1/table.go

issue #744 
Not Available
Not Available
Not Available

aoe support database splite

---

pkg/vm/driver/handler_aoe.go

issue #1139 
Not Available
Not Available
Not Available

[STMT-DROP TABLE] call local drop table failed 14, 6, invalid data, must 8 bytes, but 17

---

pkg/container/batch/batch.go
pkg/sql/compile/exec.go
pkg/sql/compile/scope.go
pkg/sql/compile/types.go
pkg/sql/plan/build.go
pkg/sql/plan/create_table.go
pkg/sql/plan/show_columns.go
pkg/sql/plan/show_databases.go
pkg/sql/plan/show_tables.go
pkg/sql/plan/types.go
pkg/vm/engine/types.go

issue #
1.add build / compile/ exec code for show database / tables / columns
2.fix a create table bug about primary key check.
Not Available
Not Available

Migrations of show statement / fix a create table bug

---

pkg/vm/engine/aoe/storage/aoedb/v1/db.go
pkg/vm/engine/aoe/storage/aoedb/v2/db.go
pkg/vm/engine/aoe/storage/aoedb/v2/db_test.go
pkg/vm/engine/aoe/storage/aoedb/v2/replay_test.go
pkg/vm/engine/aoe/storage/aoedb/v2/snapshot_test.go
pkg/vm/engine/aoe/storage/db/db.go
pkg/vm/engine/aoe/storage/db/gcreqs/dropdb.go
pkg/vm/engine/aoe/storage/db/gcreqs/droptbl.go
pkg/vm/engine/aoe/storage/db/impl.go
pkg/vm/engine/aoe/storage/db/replay.go
pkg/vm/engine/aoe/storage/db/sched/scheduler.go
pkg/vm/engine/aoe/storage/db/snapshot.go
pkg/vm/engine/aoe/storage/layout/dataio/tblk.go
pkg/vm/engine/aoe/storage/layout/table/v1/data.go
pkg/vm/engine/aoe/storage/metadata/v1/base.go
pkg/vm/engine/aoe/storage/metadata/v1/processor.go
pkg/vm/engine/aoe/storage/metadata/v1/segment.go
pkg/vm/engine/aoe/storage/metadata/v1/snapshot.go
pkg/vm/engine/aoe/storage/sched/types.go
pkg/vm/engine/aoe/storage/wal/shard/index.go
pkg/vm/engine/aoe/storage/wal/shard/proxy.go

issue #170 
Not Available
Not Available
Not Available

bug fix and add unit test for snapshot

---

pkg/sql/compile/exec.go
pkg/sql/compile/scope.go
pkg/sql/compile/types.go
pkg/sql/plan/build.go
pkg/sql/plan/create_table.go
pkg/sql/plan/expr.go
pkg/sql/plan/insert.go
pkg/sql/plan/types.go
pkg/vm/engine/types.go

issue #
1.Migration of Insert function.
2.Migration of buildConstant function.
3.fix a bug in buildConstant.
Not Available
Not Available

Migration of Insert and some function

---

pkg/vm/engine/aoe/storage/aoedb/v2/snapshot_test.go
pkg/vm/engine/aoe/storage/db/sched/ctx.go
pkg/vm/engine/aoe/storage/db/sched/scheduler.go
pkg/vm/engine/aoe/storage/db/sched/upgradeseg.go
pkg/vm/engine/aoe/storage/db/snapshot.go
pkg/vm/engine/aoe/storage/metadata/v1/segment.go

issue #170 
Not Available
Not Available
Not Available

snapshot bug fix and add ut to cover it

---

pkg/vm/engine/aoe/storage/aoedb/v2/db.go
pkg/vm/engine/aoe/storage/aoedb/v2/db_test.go
pkg/vm/engine/aoe/storage/aoedb/v2/split_test.go
pkg/vm/engine/aoe/storage/db/gcreqs/compaction.go
pkg/vm/engine/aoe/storage/db/impl.go
pkg/vm/engine/aoe/storage/db/sched/scheduler.go
pkg/vm/engine/aoe/storage/db/sched/upgradeseg.go
pkg/vm/engine/aoe/storage/db/split.go
pkg/vm/engine/aoe/storage/metadata/v1/base.go
pkg/vm/engine/aoe/storage/metadata/v1/block.go
pkg/vm/engine/aoe/storage/metadata/v1/split.go
pkg/vm/engine/aoe/storage/metadata/v1/table.go

issue #744 
Not Available
Not Available
Not Available

bug fix for split and add ut

---

pkg/vm/engine/aoe/storage/aoedb/v2/db_test.go
pkg/vm/engine/aoe/storage/db/replay.go
pkg/vm/engine/aoe/storage/db/sched/flushidx.go
pkg/vm/engine/aoe/storage/layout/dataio/index.go
pkg/vm/engine/aoe/storage/layout/index/numbsi.go
pkg/vm/engine/aoe/storage/layout/index/seg.go
pkg/vm/engine/aoe/storage/layout/index/segzonemap.go
pkg/vm/engine/aoe/storage/layout/index/strbsi.go
pkg/vm/engine/aoe/storage/layout/index/types.go
pkg/vm/engine/aoe/storage/layout/index/zonemap.go

issue #1166 #1167 
Not Available
Not Available
Not Available

[AOE] Support Create/Drop Index for AOE - phase 2

---

pkg/vm/engine/aoe/engine/reader.go
pkg/vm/engine/aoe/engine/relation.go
pkg/vm/engine/aoe/engine/types.go

issue #1200 
Not Available
Not Available
Not Available

Fix the failed to remove block bug of Reader

---

pkg/vm/engine/aoe/engine/reader.go

issue #
Not Available
Not Available
Not Available

Remove debug info

---

pkg/sql/parsers/dialect/mysql/mysql_sql.go
pkg/sql/parsers/dialect/mysql/mysql_sql.y
pkg/sql/parsers/dialect/mysql/mysql_sql_test.go

Deal with empty string in Load statement (#1203)

---

pkg/vm/engine/aoe/storage/aoedb/v2/db.go

issue #
Not Available
Not Available
Not Available

hot bug fix for create database log index logic

---

pkg/vm/engine/aoe/engine/reader.go
pkg/vm/engine/aoe/engine/relation.go
pkg/vm/engine/aoe/engine/types.go

issue #
Not Available
Not Available
Not Available

Add Reader's read cache and Fix the bug of Reader

---

pkg/sql/plan/create_table.go
pkg/sql/plan/expr.go
pkg/sql/unittest/sql_test.go

issue #
1. add unitTest for ddl and dml
2. fix an insert bug
Not Available
Not Available

Add unitTest for sql and fix some insert bug

---

pkg/vm/engine/aoe/storage/metadata/v1/catalog.go
pkg/vm/engine/aoe/storage/metadata/v1/replayer.go
pkg/vm/engine/aoe/storage/metadata/v1/table.go

issue #1209 
Not Available
Not Available
Not Available

replay bug fix

---

pkg/vm/engine/aoe/engine/reader.go

issue #
Not Available
Not Available
Not Available

Fix the bug of repeatedly reading a block

---

pkg/container/hashtable/fixed_map.go
pkg/container/hashtable/fixed_set.go
pkg/container/hashtable/int64_hash_map.go
pkg/container/hashtable/string24_hash_map.go
pkg/container/hashtable/string32_hash_map.go
pkg/container/hashtable/string40_hash_map.go
pkg/container/hashtable/string_hash_map.go

issue #664
Not Available
Not Available
Not Available

[Hashtable] Remove deprecated mempool support

---

pkg/sql/plan/insert.go
pkg/sql/unittest/sql_test.go
pkg/vectorize/like/like.go

issue 
#1127 
#1129 
#1155 
fix an insert bug for negative default value
fix a like operator bug for `xxx%` rule
add unites for fix cases.
Not Available
Not Available

fix bugs for like operator and insert

---

pkg/vm/engine/aoe/common/util/util.go
pkg/vm/engine/aoe/storage/aoedb/v2/ctx.go
pkg/vm/engine/aoe/storage/aoedb/v2/db.go
pkg/vm/engine/aoe/storage/aoedb/v2/db_test.go
pkg/vm/engine/aoe/storage/db/sched/flushidx.go
pkg/vm/engine/aoe/storage/layout/index/seg.go

issue #1166 #1167 
Not Available
Not Available
Not Available

[AOE] Support Create/Drop Index for AOE - phase 3

---

pkg/container/hashtable/hash_amd64.s
pkg/container/hashtable/int64_hash_map.go
pkg/container/hashtable/string24_hash_map.go
pkg/container/hashtable/string32_hash_map.go
pkg/container/hashtable/string40_hash_map.go
pkg/container/hashtable/string_hash_map.go

issue #664
Not Available
Not Available
Not Available

Fix a bug in hashtable resize

---

pkg/sql/compile/transfer.go
pkg/sql/compile/transfer_test.go
pkg/sql/protocol/protocol.go
pkg/sql/protocol/protocol_test.go
pkg/sql/protocol/types.go

Pipeline serialization / deseralization (#1176)

---

pkg/vm/engine/aoe/storage/aoedb/v2/db_test.go
pkg/vm/engine/aoe/storage/layout/index/seg.go
pkg/vm/engine/aoe/storage/layout/table/v1/seg.go

issue #1166 #1167 
Not Available
go -race passed
Not Available

[AOE] Fix bug in segment index holder & add more tests for index

---

pkg/vm/engine/aoe/storage/db/blk_test.go
pkg/vm/engine/aoe/storage/db/factories/factories_test.go
pkg/vm/engine/aoe/storage/db/sched/meta_test.go
pkg/vm/engine/aoe/storage/db/sched/types_test.go
pkg/vm/engine/aoe/storage/db/seg_test.go
pkg/vm/engine/aoe/storage/layout/dataio/blk_test.go
pkg/vm/engine/aoe/storage/layout/table/v1/data.go
pkg/vm/engine/aoe/storage/layout/table/v1/data_test.go
pkg/vm/engine/aoe/storage/layout/table/v1/handle/types_test.go
pkg/vm/engine/aoe/storage/layout/table/v1/seg.go
pkg/vm/engine/aoe/storage/layout/table/v1/tblk_test.go
pkg/vm/engine/aoe/storage/logstore/rotational_test.go
pkg/vm/engine/aoe/storage/logstore/store_test.go
pkg/vm/engine/aoe/storage/metadata/v1/database_test.go
pkg/vm/engine/aoe/storage/metadata/v1/metadata_test.go
pkg/vm/engine/aoe/storage/metadata/v1/segment.go
pkg/vm/engine/aoe/storage/metadata/v1/table.go
pkg/vm/engine/aoe/storage/mutation/blk_test.go
pkg/vm/engine/aoe/storage/testutils/helpers.go

issue #
Not Available
Not Available
Not Available

update ut and some code refactor

---

pkg/vm/engine/aoe/engine/reader.go

issue #
Not Available
Not Available
Not Available

Refactor Reader.Read code

---

pkg/frontend/mysql_cmd_executor.go
pkg/frontend/routine_manager.go
pkg/frontend/util.go

issue #1205 
When the panic happens, we catch the panic and print the info under the network handler.
Not Available
Not Available

add panic protection

---

pkg/vm/engine/aoe/storage/aoedb/v2/db_test.go
pkg/vm/engine/aoe/storage/db/seg.go
pkg/vm/engine/aoe/storage/db/segment_filter.go
pkg/vm/engine/aoe/storage/layout/dataio/segwriter.go
pkg/vm/engine/aoe/storage/layout/index/seg.go
pkg/vm/engine/aoe/storage/layout/index/types.go

issue #
Not Available
Not Available
Not Available

[AOE] add index test & small fix

---

pkg/sql/compile/scope.go

issue #1245 
Not Available
Not Available
Not Available

change result column name of `show`

---

pkg/sql/compile/compile.go

issue #1245 
last PR doesn't work.
Not Available
Not Available

res result names of show tables and show databases

---

pkg/sql/parsers/dialect/mysql/Makefile
pkg/sql/parsers/dialect/postgresql/Makefile

issue #
Not Available
Not Available
Not Available

Change parser makefile to work well

---

pkg/vm/driver/aoe/storage.go
pkg/vm/engine/aoe/storage/aoedb/v1/ctx.go
pkg/vm/engine/aoe/storage/layout/dataio/segwriter.go
pkg/vm/engine/aoe/storage/wal/shard/index.go

issue #
Not Available
Not Available
Not Available

revert #1255

---

cmd/generate-config/config_template.go
cmd/generate-config/system_vars_def.toml

issue #
Not Available
Not Available
Not Available

config file verbose version

---

pkg/vm/engine/aoe/storage/metadata/v1/block.go

issue #
Not Available
Not Available
Not Available

fix snapshot data rebuild bug

---

pkg/catalog/catalog.go
pkg/sql/plan/create_table.go
pkg/vm/engine/aoe/common/helper/helper.go
pkg/vm/engine/aoe/model.go
pkg/vm/engine/types.go

issue #
Not Available
Not Available
Not Available

Add the table option of properties in catalog

---

pkg/container/vector/vector.go
pkg/sql/viewexec/untransform/types.go
pkg/sql/viewexec/untransform/untransform.go

fixes issue #1282
Not Available
Not Available
Not Available

Rewrite group-by related code in a batched manner

---

go.mod
go.sum
pkg/catalog/catalog.go
pkg/vm/driver/aoe/storage.go
pkg/vm/driver/aoe/storage_test.go
pkg/vm/driver/aoe_shard_aware.go
pkg/vm/driver/cube_driver.go

issue #
Not Available
Not Available
Not Available

Integrate CUBE new API: support snapshot

---

pkg/vm/engine/aoe/storage/db/sched/scheduler.go
pkg/vm/engine/aoe/storage/db/split.go
pkg/vm/engine/aoe/storage/event/listeners.go
pkg/vm/engine/aoe/storage/event/logging.go
pkg/vm/engine/aoe/storage/event/types.go
pkg/vm/engine/aoe/storage/options.go

issue #1291 
Not Available
Not Available
Not Available

add event listener

---

pkg/sql/plan/create_table.go
pkg/vm/engine/aoe/common/helper/helper.go

issue #
Not Available
Not Available
Not Available

update primary key

---

pkg/vm/driver/pb/rpc.pb.go
pkg/vm/engine/aoe/storage/aoedb/v1/db.go
pkg/vm/engine/aoe/storage/common/file.go
pkg/vm/engine/aoe/storage/db/seg_test.go
pkg/vm/engine/aoe/storage/layout/dataio/colpart.go
pkg/vm/engine/aoe/storage/layout/dataio/index.go
pkg/vm/engine/aoe/storage/layout/index/blk.go
pkg/vm/engine/aoe/storage/layout/index/index_test.go
pkg/vm/engine/aoe/storage/layout/index/seg.go
pkg/vm/engine/aoe/storage/layout/index/sortedseg_holder.go
pkg/vm/engine/aoe/storage/layout/index/tbl.go
pkg/vm/engine/aoe/storage/layout/index/types.go
pkg/vm/engine/aoe/storage/layout/index/unsortedseg_holder.go
pkg/vm/engine/aoe/storage/layout/table/v1/baseblk.go
pkg/vm/engine/aoe/storage/layout/table/v1/blk.go
pkg/vm/engine/aoe/storage/layout/table/v1/col/stdblk.go
pkg/vm/engine/aoe/storage/layout/table/v1/iface/types.go
pkg/vm/engine/aoe/storage/layout/table/v1/seg.go

issue #1296 
Not Available
Not Available
Not Available

[AOE] Support filters upon unclosed segment - phase 1

---

pkg/frontend/mysql_cmd_executor.go
pkg/sql/compile/exec.go
pkg/sql/compile/scope.go
pkg/sql/compile/types.go
pkg/sql/parsers/dialect/mysql/mysql_sql.go
pkg/sql/parsers/dialect/mysql/mysql_sql.y
pkg/sql/parsers/tree/show.go
pkg/sql/plan/build.go
pkg/sql/plan/show_create_table.go
pkg/sql/plan/types.go
pkg/sql/unittest/sql_test.go
pkg/vm/engine/format.go
pkg/vm/engine/types.go

issue #1297 
Not Available
Not Available
Not Available

Support the stmt of <show create table>

---

pkg/vm/engine/aoe/storage/aoedb/v1/shard_test.go
pkg/vm/engine/aoe/storage/db/split.go
pkg/vm/engine/aoe/storage/event/listeners.go
pkg/vm/engine/aoe/storage/event/logging.go
pkg/vm/engine/aoe/storage/event/types.go
pkg/vm/engine/aoe/storage/metadata/v1/database.go

issue #
Not Available
Not Available
Not Available

update event listener and related dependency

---

.github/workflows/build_matrixone_factor.yml

issue #1305 
To make sure the factor branch works well on CI/CD before merging to main.
n/a
n/a

Add new workflow for factor and disable scheduler on 1.18

---

pkg/container/nulls/nulls.go
pkg/encoding/encoding.go
pkg/vm/engine/aoe/common/codec/codec.go

issue #
Not Available
Not Available
Not Available

pick slice header fix

---

pkg/sql/viewexec/times/times.go
pkg/sql/viewexec/times/times_test.go
pkg/sql/viewexec/times/types.go

issue #1308 
Not Available
Not Available
Not Available

Add calcuteCount

---

cmd/db-server/main.go

issue #1034
This modification is verified in a docker environment with three nodes.

Reading data fails in a multi environment

---

pkg/container/hashtable/string_hash_map.go

issue #664
Not Available
Not Available
Not Available

Fix a bug in StringHashMap::Find

---

pkg/sql/viewexec/times/times.go
pkg/sql/viewexec/times/times_test.go

issue #1309 
Not Available
Not Available
Not Available

Minor refactor

---

.github/workflows/build_matrixone_factor.yml

issue #1305 
Not Available
Not Available
Not Available

Cherry pick new workflow file to factor branch from main

---

pkg/sql/viewexec/transform/transform.go
pkg/sql/viewexec/untransform/untransform.go
pkg/vm/vm.go

issue #1317
Not Available
Not Available
Not Available

Fix a bug in multi-column serialization

---

pkg/sql/viewexec/untransform/types.go
pkg/sql/viewexec/untransform/untransform.go

issue #1317
Not Available
Not Available
Not Available

Fix invalid pointer caused by hashtable resize

---

docs/rfcs/00000000-template.md
docs/rfcs/README.md

RFC template and its guideline.

Add the RFC template

---

docs/rfcs/20211210_aoe_overall_design.md

issue #1320 
Not Available
Not Available
Not Available

add aoe overall design rfc

---

go.mod

issue #
Not Available
Not Available
Not Available

Update matrixcube version

---

pkg/frontend/load.go

issue #
Not Available
Not Available
Not Available

 update load

---

pkg/sql/compile/view.go
pkg/sql/viewexec/oplus/oplus.go
pkg/sql/viewexec/oplus/types.go
pkg/sql/viewexec/plus/plus.go
pkg/sql/viewexec/plus/types.go
pkg/sql/viewexec/times/times.go
pkg/sql/viewexec/times/times_test.go
pkg/sql/viewexec/times/types.go
pkg/sql/viewexec/transform/transform.go
pkg/sql/viewexec/transform/types.go
pkg/sql/viewexec/untransform/types.go
pkg/sql/viewexec/untransform/untransform.go

issue # 987
Not Available
Not Available
Not Available

Add view logic for building indefinitely long strings

---

pkg/sql/compile/exec.go
pkg/sql/compile/scope.go
pkg/sql/compile/types.go

issue #
Not Available
Not Available
Not Available

Recover the code of <show create table>

---

go.mod
go.sum

issue #
Not Available
Not Available
Not Available

update cube version

---

cmd/generate-config/system_vars_def.toml
pkg/config/system_vars.go
pkg/config/system_vars_test.go
pkg/frontend/load.go

issue #
Not Available
Not Available
Not Available

add missing bytes limit

---

go.mod
pkg/vm/engine/aoe/storage/container/vector/stdvec_test.go
pkg/vm/engine/aoe/storage/container/vector/strvec_test.go

issue #
Not Available
Not Available
Not Available

Fix vector ut error

---

pkg/vm/engine/aoe/storage/aoedb/v1/db.go
pkg/vm/engine/aoe/storage/aoedb/v1/replay_test.go
pkg/vm/engine/aoe/storage/aoedb/v1/split_test.go
pkg/vm/engine/aoe/storage/db/impl.go
pkg/vm/engine/aoe/storage/wal/shard/manager.go
pkg/vm/engine/aoe/storage/wal/shard/proxy.go

issue #
Not Available
Not Available
Not Available

wait checkpointed in flush database

---

pkg/vm/engine/aoe/common/helper/helper_test.go
pkg/vm/engine/aoe/engine/engine_test.go
pkg/vm/engine/aoe/storage/aoedb/v1/db_test.go
pkg/vm/engine/aoe/storage/aoedb/v1/replay_test.go
pkg/vm/engine/aoe/storage/aoedb/v1/snapshot_test.go
pkg/vm/engine/aoe/storage/aoedb/v1/split_test.go
pkg/vm/engine/aoe/storage/container/vector/wrapper.go
pkg/vm/engine/aoe/storage/container/vector/wrapper_test.go
pkg/vm/engine/aoe/storage/db/blk_test.go
pkg/vm/engine/aoe/storage/db/seg.go
pkg/vm/engine/aoe/storage/db/seg_test.go
pkg/vm/engine/aoe/storage/db/segment_sparse_filter.go
pkg/vm/engine/aoe/storage/layout/table/v1/tblk_test.go
pkg/vm/engine/aoe/types.go

issue #
Not Available
Not Available
Not Available

Fix Aoe&driver ut

---

pkg/vm/engine/aoe/storage/aoedb/v1/snapshot_test.go
pkg/vm/engine/aoe/storage/db/db.go
pkg/vm/engine/aoe/storage/db/snapshot.go
pkg/vm/engine/aoe/storage/metadata/v1/catalog.go
pkg/vm/engine/aoe/storage/metadata/v1/ctx.go
pkg/vm/engine/aoe/storage/metadata/v1/entry.go
pkg/vm/engine/aoe/storage/metadata/v1/metadata_test.go
pkg/vm/engine/aoe/storage/metadata/v1/snapshot.go

issue #1354 
Not Available
Not Available
Not Available

snapshot enhancement

---

Makefile
cmd/db-server/main.go
cmd/db-server/profile.go

issue #
Not Available
Not Available
Not Available

Feature, support --version argument

---

cmd/db-server/main.go
go.mod
pkg/catalog/catalog.go
pkg/catalog/errors.go
pkg/catalog/helper.go
pkg/vm/driver/aoe/storage.go
pkg/vm/driver/helper.go
pkg/vm/driver/kv/executor.go
pkg/vm/engine/aoe/storage/aoedb/v1/db.go
pkg/vm/engine/aoe/storage/aoedb/v1/replay_test.go
pkg/vm/engine/aoe/storage/aoedb/v1/snapshot_test.go
pkg/vm/engine/aoe/storage/aoedb/v1/split_test.go
pkg/vm/engine/aoe/storage/db/db.go
pkg/vm/engine/aoe/storage/db/impl.go
pkg/vm/engine/aoe/storage/db/snapshot.go
pkg/vm/engine/aoe/storage/metadata/v1/catalog.go
pkg/vm/engine/aoe/storage/metadata/v1/ctx.go
pkg/vm/engine/aoe/storage/metadata/v1/entry.go
pkg/vm/engine/aoe/storage/metadata/v1/metadata_test.go
pkg/vm/engine/aoe/storage/metadata/v1/snapshot.go
pkg/vm/engine/aoe/storage/wal/shard/manager.go
pkg/vm/engine/aoe/storage/wal/shard/proxy.go

issue #
Not Available
Not Available
Not Available

Update main branch bug fix

---

cmd/generate-config/system_vars_def.toml

issue #
Not Available
Not Available
Not Available

Update the config parameter "block-max-rows" to 16000

---

pkg/container/vector/vector.go
pkg/sql/unittest/sql_test.go

issue #
vector.String() function will print `null` which should return directly.
this pr fix it. and unit test can be pass success.
Not Available
Not Available

fix ut TestInsertFunction

---

pkg/sql/compile/compile.go
pkg/sql/compile/types.go

issue # 1362
Not Available
Not Available
Not Available

Add InitAddress Function

---

cmd/generate-config/system_vars_def.toml
pkg/frontend/codec.go
pkg/frontend/iopackage_test.go
pkg/frontend/mysql_cmd_executor.go
pkg/frontend/mysql_protocol.go
pkg/frontend/mysql_protocol_test.go
pkg/frontend/routine.go
pkg/frontend/routine_manager.go
pkg/frontend/server.go

issue #
Not Available
Not Available
Not Available

speedup the output of the mo

---

cmd/db-server/main.go

issue # 1362
Not Available
Not Available
Not Available

add node addr

---

pkg/frontend/epochgc_test.go

issue #
Not Available
Not Available
Not Available

transplant the epochtest from the main to the factor

---

pkg/sql/ftree/build_test.go

issue #
Not Available
Not Available
Not Available

Fix TestBuild bug

---

pkg/frontend/mysql_cmd_executor_test.go

issue #
Not Available
Not Available
Not Available

comment ut

---

pkg/frontend/mysql_cmd_executor.go
pkg/frontend/mysql_protocol.go

issue #
Not Available
Not Available
Not Available

fix channel protocol

---

pkg/container/batch/batch.go
pkg/sql/colexec/splice/splice.go
pkg/sql/compile/scope.go
pkg/sql/compile/vtree.go
pkg/vm/overload.go
pkg/vm/process/types.go
pkg/vm/types.go

issue #
1.Support select without group by and aggregate functions
tips:  not support select from empty table because AOE's NewReader() interface can not return correct value at this case
2.These code will be refactored to be multi-thread-query at next time.
Not Available
Not Available

Support select * for factor (single thread)

---

pkg/frontend/mysql_cmd_executor_test.go

issue #
Not Available
Not Available
Not Available

comment ut2

---

go.mod
pkg/vm/engine/aoe/storage/aoedb/v1/snapshot_test.go

issue #
Not Available
Not Available
Not Available

Fix aoe snapshot UT

---

cmd/generate-config/system_vars_def.toml

issue #
Not Available
Not Available
Not Available

migrate the cube config from main to factor

---

pkg/vm/engine/aoe/engine/relation.go

issue #
Not Available
Not Available
Not Available

Support empty table to return to reader normally

---

pkg/container/ring/avg/avg.go
pkg/sql/colexec/restrict/restrict.go
pkg/sql/colexec/splice/splice.go
pkg/sql/compile/exec.go
pkg/sql/compile/vtree.go
pkg/sql/plan/from.go
pkg/sql/plan/where.go
pkg/vm/overload.go

issue # 1387
Not Available
Not Available
Not Available

Fix the problem of constant restrict

---

pkg/vm/engine/aoe/storage/db/impl.go
pkg/vm/engine/aoe/storage/mutation/blk.go

issue #1374 #1349 #1350 
Not Available
Not Available
Not Available

fix bug for concurrent flush tblk

---

pkg/vm/engine/aoe/storage/db/impl.go
pkg/vm/engine/aoe/storage/mutation/blk.go

issue #
Not Available
Not Available
Not Available

Fix bug for concurrent flush tblk (#1389)

---

go.mod

issue #
Update cube version to the latest which contains a critical fix. 
Not Available
Not Available

Bumped MatrixCube version

---

pkg/container/vector/vector.go
pkg/frontend/mysql_cmd_executor.go
pkg/frontend/mysql_protocol.go
pkg/sql/colexec/extend/extend.go
pkg/sql/colexec/extend/overload/types.go
pkg/sql/plan/expr.go
pkg/vm/engine/aoe/protocol/protocol.go

1. diff `div` to `/`, div means integer div.
2. add date and datetime case for vector function and protocol functions.
issue #1391 
1.now div operator are not effective, this pr fix it.
2.fix problem for select date / datetime error.
Not Available
Not Available

fix bug for: div operator, date, datetime

---

pkg/sql/compile/scope.go
pkg/sql/compile/transfer.go
pkg/sql/protocol/protocol.go
pkg/sql/protocol/types.go

issue #
Not Available
Not Available
Not Available

Serialize the new operators

---

cmd/generate-config/system_vars_def.toml

issue #
Not Available
Not Available
Not Available

change default log level

---

cmd/generate-config/system_vars_def.toml

issue #
Not Available
Not Available
Not Available

1. change default value of metric' config

---

cmd/db-server/main.go
cmd/generate-config/system_vars_def.toml

fix #1407 
Not Available
Not Available
Not Available

use structural log format

---

cmd/generate-config/system_vars_def.toml

issue #
Not Available
Not Available
Not Available

add log compaction duration for cube

---

go.mod
go.sum

issue #
Not Available
Not Available
Not Available

Bumped MatrixCube version to the latest in main

---

cmd/db-server/main.go
pkg/sql/compile/compile_test.go
pkg/sql/compile/scope.go
pkg/sql/compile/vtree.go
pkg/sql/handler/handler.go
pkg/sql/handler/recover.go
pkg/sql/handler/types.go
pkg/sql/viewexec/times/times.go

Fix #1416
Not Available
Not Available
Not Available

Add support for distributed queries

---

pkg/vm/engine/aoe/storage/db/split.go

issue #
Not Available
Not Available
Not Available

fix wrong index used for split

---

pkg/frontend/epochgc.go
pkg/frontend/load.go
pkg/frontend/mysql_cmd_executor.go
pkg/frontend/mysql_protocol.go
pkg/frontend/protocol.go
pkg/frontend/routine.go
pkg/frontend/routine_manager.go
pkg/frontend/test_stub.go

issue #
Not Available
Not Available
Not Available

1216 fix load

---

pkg/vm/engine/aoe/storage/aoedb/v1/split_test.go
pkg/vm/engine/aoe/storage/db/split.go
pkg/vm/engine/aoe/storage/metadata/v1/database.go
pkg/vm/engine/aoe/storage/metadata/v1/split.go

issue #
Not Available
Not Available
Not Available

support split on incremental database after split check

---

cmd/db-server/main.go

Fix #1436
Not Available
Not Available
Not Available

db-server: pass buffered channel to signal.Notify

---

pkg/frontend/cmd_executor.go
pkg/frontend/load.go
pkg/frontend/mysql_cmd_executor.go
pkg/frontend/mysql_protocol.go
pkg/frontend/mysql_protocol_test.go
pkg/frontend/protocol.go
pkg/frontend/routine.go
pkg/frontend/routine_manager.go
pkg/frontend/session.go

issue #
Not Available
Not Available
Not Available

restore the design of the frontend

---

pkg/container/hashtable/hash_arm64.s

issue #1440
Not Available
Not Available
Not Available

(hotfix) enable compilation on arm64

---

pkg/frontend/mysql_cmd_executor.go
pkg/sql/compile/exec.go
pkg/sql/compile/scope.go
pkg/sql/compile/types.go
pkg/sql/parsers/dialect/mysql/mysql_sql.go
pkg/sql/parsers/dialect/mysql/mysql_sql.y
pkg/sql/parsers/scanner/scanner_test.go
pkg/sql/parsers/util/util.go
pkg/sql/plan/build.go
pkg/sql/plan/show_create_database.go
pkg/sql/plan/types.go

issue #1433 
Not Available
Not Available
Not Available

[Feature]: Support sql of show create database (#1433)

---

pkg/sql/colexec/extend/overload/binary.go
pkg/sql/colexec/extend/overload/cast.template
pkg/sql/colexec/extend/overload/eq.template
pkg/sql/colexec/extend/overload/ge.template
pkg/sql/colexec/extend/overload/gt.template
pkg/sql/colexec/extend/overload/le.template
pkg/sql/colexec/extend/overload/lt.template
pkg/sql/plan/prune.go
pkg/sql/unittest/sql_test.go

issue #1429
Not Available
Not Available
Not Available

Feature: support comparison operator for date types

---

pkg/vm/engine/aoe/engine/relation.go
pkg/vm/engine/aoe/local/relation.go
pkg/vm/engine/memEngine/relation.go
pkg/vm/engine/types.go

issue #
Not Available
Not Available
Not Available

provide AOE interface for create/drop index

---

pkg/sql/plan/build.go

issue # 783
Not Available
Not Available
Not Available

Adding Missing Initialization

---

pkg/sql/colexec/extend/overload/binary.go
pkg/sql/colexec/extend/overload/cast.template
pkg/sql/colexec/extend/overload/eq.template
pkg/sql/colexec/extend/overload/ge.template
pkg/sql/colexec/extend/overload/gt.template
pkg/sql/colexec/extend/overload/le.template
pkg/sql/colexec/extend/overload/lt.template
pkg/sql/colexec/extend/overload/ne.template
pkg/sql/plan/prune.go
pkg/sql/unittest/sql_test.go

issue #1446 
Not Available
Not Available
Not Available

support comparison operator for datetime types..

---

pkg/sql/compile/scope.go
pkg/sql/plan/create_index.go
pkg/sql/plan/drop_index.go
pkg/sql/plan/types.go

issue #1430 
add semantic analyse for create and drop index
will check
column name, index name, index exist situation, BSI index or not
Not Available
Not Available

semantic analyse and create plan for create/drop index

---

cmd/db-server/main.go
cmd/generate-config/system_vars_def.toml
go.mod
go.sum

issue #1461 
Not Available
Not Available
Not Available

use advertise address

---

cmd/generate-config/system_vars_def.toml
go.mod
go.sum
pkg/builtin/binary/types.go
pkg/builtin/multi/types.go
pkg/builtin/types.go
pkg/builtin/unary/length.go
pkg/builtin/unary/types.go
pkg/sql/colexec/extend/extend.go
pkg/sql/colexec/extend/overload/unary.go
pkg/sql/compile/compile.go
pkg/sql/plan/expr.go

issue #
Not Available
Not Available
Not Available

Add builtin function example

---

pkg/sql/protocol/protocol_test.go
pkg/sql/protocol/types.go

issue #1467 
Not Available
Not Available
Not Available

Fix deserialization of transform

---

pkg/chaostesting/action.go
pkg/chaostesting/config_codec_test.go
pkg/chaostesting/execute.go
pkg/chaostesting/go.mod
pkg/chaostesting/go.sum
pkg/chaostesting/node.go
pkg/chaostesting/operator_porcupine.go
pkg/chaostesting/report.go
pkg/chaostesting/scope.go
pkg/chaostesting/testkv/actions.go
pkg/chaostesting/testkv/kv.go
pkg/chaostesting/testkv/kv_test.go
pkg/chaostesting/testkv/porcupine_test.go

updates issue #1469 , not done yet
Not Available
Not Available
Not Available

various changes to chaostesting package

---

pkg/sql/colexec/merge/merge.go
pkg/sql/colexec/splice/splice.go
pkg/sql/colexec/splice/types.go
pkg/sql/compile/exec.go
pkg/sql/compile/scope.go
pkg/sql/compile/vtree.go
pkg/sql/plan/query.go
pkg/sql/protocol/protocol.go

issue #1466
issue #465
issue #459
Not Available
Not Available
Not Available

Refactor pipeline

---

go.sum
pkg/frontend/load.go

issue #1474
Not Available
Not Available
Not Available

Add the datetime into the load

---

pkg/sql/colexec/dedup/dedup.go
pkg/sql/compile/view.go
pkg/sql/viewexec/oplus/oplus.go
pkg/sql/viewexec/plus/plus.go
pkg/sql/viewexec/times/times.go
pkg/sql/viewexec/transform/transform.go
pkg/sql/viewexec/untransform/untransform.go

issue #1476
Not Available
Not Available
Not Available

Add grouping, Join support for date and datetime

---

pkg/sql/viewexec/times/times.go

issue #664
Not Available
Not Available
Not Available

Fix a segfault introduced by #1478

---

pkg/container/ring/max/str.go
pkg/container/ring/min/str.go
pkg/sql/plan/query.go

issue #1483
Not Available
Not Available
Not Available

Fix the bug of max/min ring

---

pkg/container/hashtable/hash.go
pkg/container/hashtable/hash_amd64.s
pkg/container/hashtable/hash_arm64.s
pkg/container/hashtable/hash_test.go

issue #664
Not Available
Not Available
Not Available

Cleanup obsoleted hash functions

---

optools/image_builder/Dockerfile
optools/image_builder/entrypoint.sh

issue #1495 
Not Available
Not Available
Not Available

To build docker image

---

pkg/container/types/types.go
pkg/container/vector/vector.go

issue #1502 
1. fill basic functions in vector.go
Not Available
Not Available

fix vector's function for type Date, Datetime

---

pkg/builtin/types.go
pkg/builtin/unary/year.go
pkg/container/types/date.go
pkg/container/types/datetime.go
pkg/vectorize/year/year.go

issue #1484 
Not Available
Not Available
Not Available

add year and to year function for date and datetime types(return uint16 number indicating the year)

---

pkg/builtin/multi/round.go
pkg/builtin/types.go
pkg/sql/colexec/extend/multi.go
pkg/sql/colexec/extend/overload/multi.go
pkg/sql/compile/scope.go

issue #1497
issue #1499
Not Available
Not Available
Not Available

Add function round

---

pkg/sql/colexec/splice/splice.go

issue #1501 
Not Available
Not Available
Not Available

fix a bug may lost batch information when select *

---

pkg/vm/driver/aoe/storage.go

issue #
Not Available
Not Available
Not Available

Fix the bug that GetInitialStates gets expired metadata

---

pkg/sql/colexec/dedup/dedup.go
pkg/sql/compile/scope.go
pkg/sql/viewexec/oplus/oplus.go
pkg/sql/viewexec/plus/plus.go
pkg/sql/viewexec/times/times.go
pkg/sql/viewexec/transform/transform.go
pkg/sql/viewexec/untransform/untransform.go

issue #1524
Not Available
Not Available
Not Available

Fix the bug of date and datetime

---

pkg/sql/colexec/extend/overload/overloadGenerate.go

issue #
fix a format error may cause warn while do make build.
Not Available
Not Available

fix go fmt error in overloadGenerate.go

---

pkg/sql/compile/scope.go
pkg/sql/compile/vtree.go
pkg/sql/protocol/protocol.go
pkg/sql/viewexec/oplus/oplus.go
pkg/sql/viewexec/plus/plus.go
pkg/vm/pipeline/pipeline.go

issue # 1533
Not Available
Not Available
Not Available

Add the logic of pipeline abnormal exit

---

cmd/generate-config/config_template.go
cmd/generate-config/system_vars_def.toml
docs/en/MatrixOne/Get-Started/set-up-matrixone.md

issue #
Not Available
Not Available
Not Available

Config file verbose update(added some comments and deleted some internal and redundant parameters)

---

pkg/sql/compile/scope.go
pkg/sql/protocol/protocol.go
pkg/sql/protocol/protocol_test.go

Fix #1526 
Not Available
Not Available
Not Available

Fix serialization of ring

---

.github/workflows/build_matrixone_0.1.0.yml

issue #1540 
Not Available
Not Available
Not Available

disable v0.1.0 workflow scheduler

---

pkg/catalog/catalog.go
pkg/vm/driver/aoe/helper.go
pkg/vm/driver/aoe/storage.go
pkg/vm/driver/test/storage_test.go

issue #
Not Available
Not Available
Not Available

refine interface split

---

.github/workflows/build_matrixone_0.1.0.yml
optools/run_bvt.sh

issue #1540 
Not Available
Not Available
Not Available

disable v0.1.0 workflow scheduler (#1541)

---

cmd/generate-config/system_vars_def.toml
pkg/frontend/load.go
pkg/sql/parsers/dialect/mysql/mysql_sql.go
pkg/sql/parsers/dialect/mysql/mysql_sql.y

issue #
Not Available
Not Available
Not Available

add function writeBatchToStorage threadNum log

---

pkg/sql/compile/vtree.go
pkg/sql/protocol/types.go

issue #1530 #1533 
fix a serialization bug and delete error message when select * from empty table
Not Available
Not Available

fix a serialization bug, delete error message when select * from empty table

---

pkg/vm/driver/aoe/storage.go
pkg/vm/driver/test/storage_test.go

issue #
Not Available
Not Available
Not Available

fix interface RemoveShard

---

pkg/vm/engine/aoe/engine/database.go

issue #1554 
Not Available
Not Available
Not Available

Return err after GetSegmentIds timeout

---

pkg/frontend/mysql_cmd_executor.go
pkg/sql/parsers/dialect/mysql/mysql_sql.go
pkg/sql/parsers/dialect/mysql/mysql_sql.y
pkg/sql/parsers/tree/explain.go
pkg/sql/parsers/tree/show.go

issue #1557 
Not Available
Not Available
Not Available

Fix show columns from db.table fail

---

pkg/sql/protocol/protocol.go
pkg/sql/protocol/protocol_test.go

issue #1526 
Not Available
Not Available
Not Available

Add unit test for serialization and fix bug of ring

---

pkg/sql/compile/scope.go

issue #1563
Not Available
Not Available
Not Available

Increase the speed of convergence

---

pkg/container/types/date.go

issue #
Not Available
Not Available
Theoretically speaking, the original implementation of year function is already O(1)(four integer division operation dominates the computation time, about 200 clock cycles). 
using ssb lineorder.tbl(6million rows), Testing results shows that implement year function with lookup tables does not accelerate the execution at all.

Year function implementation with lookup tables

---

pkg/sql/protocol/protocol.go
pkg/sql/protocol/protocol_test.go
pkg/sql/protocol/types.go

issue #1515 
Not Available
Not Available
Not Available

service is offline during BVT in cluster mode

---

pkg/chaostesting/action.go
pkg/chaostesting/action_sequential.go
pkg/chaostesting/execute.go
pkg/chaostesting/go.mod
pkg/chaostesting/go.sum
pkg/chaostesting/operator.go
pkg/chaostesting/operator_porcupine.go
pkg/chaostesting/operator_save_config.go
pkg/chaostesting/report.go
pkg/chaostesting/testcube/.gitignore
pkg/chaostesting/testcube/cmd_gen_configs.go
pkg/chaostesting/testcube/cmd_run.go
pkg/chaostesting/testcube/do.go
pkg/chaostesting/testcube/main.go
pkg/chaostesting/testcube/main_action.go
pkg/chaostesting/testcube/porcupine.go
pkg/chaostesting/testcube/scope.go

issue #1469, not done yet
Not Available
Not Available
Not Available

various changes to the chaostesting package

---

pkg/vm/engine/aoe/storage/aoedb/v1/db.go
pkg/vm/engine/aoe/storage/aoedb/v1/db_test.go
pkg/vm/engine/aoe/storage/common/compare.go
pkg/vm/engine/aoe/storage/common/filenames.go
pkg/vm/engine/aoe/storage/db/replay.go
pkg/vm/engine/aoe/storage/db/sched/flushblkidx.go
pkg/vm/engine/aoe/storage/db/sched/flushseg.go
pkg/vm/engine/aoe/storage/db/sched/flushsegidx.go
pkg/vm/engine/aoe/storage/db/sched/scheduler.go
pkg/vm/engine/aoe/storage/db/segment_filter.go
pkg/vm/engine/aoe/storage/db/segment_sparse_filter.go
pkg/vm/engine/aoe/storage/db/segment_summarizer.go
pkg/vm/engine/aoe/storage/layout/dataio/blk.go
pkg/vm/engine/aoe/storage/layout/dataio/blkwriter.go
pkg/vm/engine/aoe/storage/layout/dataio/segwriter.go
pkg/vm/engine/aoe/storage/layout/dataio/unsortedseg.go
pkg/vm/engine/aoe/storage/layout/index/blk_holder.go
pkg/vm/engine/aoe/storage/layout/index/numbsi.go
pkg/vm/engine/aoe/storage/layout/index/sortedseg_holder.go
pkg/vm/engine/aoe/storage/layout/index/types.go
pkg/vm/engine/aoe/storage/layout/index/unsortedseg_holder.go
pkg/vm/engine/aoe/storage/layout/table/v1/blk.go
pkg/vm/engine/aoe/storage/layout/table/v1/data.go
pkg/vm/engine/aoe/storage/layout/table/v1/iface/types.go
pkg/vm/engine/aoe/storage/layout/table/v1/tblk.go

Fix #1296 
Not Available
Not Available
Not Available

[AOE] Support filters upon unclosed segment - end

---

pkg/vm/engine/aoe/storage/flusher/flusher.go
pkg/vm/engine/aoe/storage/flusher/flusher_test.go
pkg/vm/engine/aoe/storage/flusher/shard.go

issue #
Increase the average UT coverage of flusher from 62.90% to 93.80%
Not Available
Not Available

add flusher test

---

cmd/generate-config/config_template.go
docs/en/MatrixOne/Get-Started/set-up-matrixone.md

… in quick start
issue #
Not Available
Not Available
Not Available

delete a orphan parameter in quick start(shard-groups), fix a mistake in quick start

---

pkg/builtin/multi/round.go
pkg/builtin/multi/types.go
pkg/sql/colexec/extend/overload/init.go
pkg/vectorize/round/round.go
pkg/vectorize/round/round_test.go

issue #1566 
issue #1506
Not Available
Not Available
Not Available

feature: add round function

---

pkg/frontend/mysql_cmd_executor.go

issue #1589 
Not Available
Not Available
Not Available

[Sqlancer] show tables from database failed when do not use database

---

.github/ISSUE_TEMPLATE/10_bug_report.yml

Change issue default assignee to @m-schen

Update issue template

---

docs/en/MatrixOne/documentation_contribution_guide.md

issue #
Not Available
Not Available
Adding documentation contribution guide for external developers to partipate.

Add documentation_contribution_guide.md

---

pkg/vm/engine/aoe/storage/layout/table/v1/baseblk.go

issue #
Not Available
Not Available
Not Available

[AOE] Fix unexpected reference of block index holder

---

docs/en/MatrixOne/Get-Started/Playground.md

issue #
add Playground.md
Not Available
add ../docs/en/MatrixOne/Get-Started/Playground.md

add playground.md into docs

---

pkg/vm/engine/aoe/engine/engine_test.go
pkg/vm/engine/aoe/engine/relation.go

issue #
Not Available
Not Available
Not Available

 Implement interface Rows() and Size(string)

---

pkg/vm/engine/aoe/engine/database.go

issue #1593 
Not Available
Not Available
Not Available

Use storeId to determine whether to read data

---

pkg/vm/engine/aoe/engine/reader.go
pkg/vm/engine/aoe/engine/types.go

issue #
Not Available
Not Available
Not Available

Add read latency of the reader

---

pkg/builtin/multi/floor.go
pkg/builtin/types.go
pkg/vectorize/floor/floor.go
pkg/vectorize/floor/floor_amd64.go
pkg/vectorize/floor/floor_avx2_amd64.s
pkg/vectorize/floor/floor_test.go

issue #1566 
Not Available
Not Available
Not Available

vectorized floor function_

---

pkg/vm/engine/aoe/storage/aoedb/v1/shard_test.go
pkg/vm/engine/aoe/storage/flusher/flusher.go
pkg/vm/engine/aoe/storage/flusher/flusher_test.go

issue #
Not Available
Not Available
Not Available

fix data race

---

pkg/vm/engine/aoe/storage/db/sched/flushseg.go
pkg/vm/engine/aoe/storage/db/sched/scheduler.go
pkg/vm/engine/aoe/storage/layout/dataio/index.go
pkg/vm/engine/aoe/storage/layout/dataio/segwriter.go

issue #1614 
Not Available
Not Available
Not Available

fix physical resources not released after drop op

---

pkg/vectorize/floor/floor.go
pkg/vectorize/floor/floor_avx2_amd64.s
pkg/vectorize/round/round.go
pkg/vectorize/round/round_amd64.go
pkg/vectorize/round/round_avx2_amd64.s

issue #1566 
Not Available
Not Available
Not Available

vectorized round function

---

docs/en/MatrixOne/Overview/matrixcube/matrixcube-auto-rebalance-scheduling.md
docs/en/MatrixOne/Overview/matrixcube/matrixcube-introduction.md
docs/en/MatrixOne/Overview/matrixcube/matrixcube-proxy-routing.md
docs/en/MatrixOne/Overview/matrixcube/matrixcube-shard-splitting.md

issue #
Not Available
Not Available
Add MatrixCube introduction and design docs.
Not Available

Add MatrixCube Documentation

---

pkg/sql/plan/types.go

issue #1617
Not Available
Not Available
Not Available

Apply attribute's name pruning

---

pkg/vm/engine/aoe/engine/engine_test.go

issue #
Not Available
Not Available
Not Available

fix TestAOEEngine

---

docs/en/MatrixOne/Get-Started/Playground.md
docs/en/MatrixOne/Get-Started/Tutorial/NYC-test-with-matrixone.md
docs/en/MatrixOne/Get-Started/Tutorial/SSB-test-with-matrixone.md
docs/en/MatrixOne/Get-Started/connect-to-matrixone-server.md
docs/en/MatrixOne/Overview/NYC Test Performance.md
docs/en/MatrixOne/Overview/SSB Test Performance.md
docs/en/MatrixOne/Overview/matrixone-architecture.md
docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/load-data.md

issue #
add SSB,NYC test performance.md 
and modify some mistakes
Not Available
add SSB,NYC test performance.md 
add NYC test.md

add SSB,NYC tet performance

---

Makefile
cmd/db-server/main.go

issue #
Not Available
Not Available
Not Available

get MatrixOne version info from git tag

---

pkg/container/types/date_test.go
pkg/container/types/datetime_test.go
pkg/container/vector/vector.go
pkg/partition/partition.go
pkg/sort/sort.go
pkg/sql/colexec/dedup/dedup.go
pkg/sql/colexec/extend/overload/cast.template
pkg/sql/plan/prune.go
pkg/sql/plan/prune_test.go
pkg/sql/testutil/make.go
pkg/sql/unittest/datatype_test.go
pkg/sql/unittest/ddl_test.go
pkg/sql/unittest/dml_test.go
pkg/sql/unittest/exec_operator_test.go
pkg/sql/unittest/operator_test.go
pkg/sql/unittest/types.go
pkg/vectorize/like/like.go
pkg/vectorize/like/like_test.go
pkg/vectorize/shuffle/shuffle.go
pkg/vm/engine/memEngine/database.go
pkg/vm/engine/memEngine/kv/kv.go

1.refactor the unit-test framwork of compute-layer
2.rewrite the unit-test cases
3.fix bugs while unit-test : like operator bug, and operator bug, prune function bugs and so on.
issue #
Not Available
Not Available
Not Available

Improve the unit-test coverage of compute-layer, and fix bugs.

---

docs/en/MatrixOne/Overview/NYC Test Performance.md
docs/en/MatrixOne/Overview/SSB Test Performance.md

issue #
Modify some mistakes in docs
Not Available
Not Available

Modify some mistakes in docs

---

pkg/compare/asc/dates/compare.go
pkg/compare/asc/dates/types.go
pkg/compare/asc/datetimes/compare.go
pkg/compare/asc/datetimes/types.go
pkg/compare/compare.go
pkg/compare/desc/dates/compare.go
pkg/compare/desc/dates/types.go
pkg/compare/desc/datetimes/compare.go
pkg/compare/desc/datetimes/types.go
pkg/sql/unittest/dml_test.go
pkg/sql/unittest/exec_operator_test.go

issue #1630 
Not Available
Not Available
Not Available

add Ut for compute-layer and fix a bug in top executor

---

pkg/sql/rewrite/astrewrite.go
pkg/sql/unittest/operator_test.go

issue #1634 
Not Available
Not Available
Not Available

Feature: support IN and NOT IN operator

---

pkg/builtin/binary/types.go
pkg/builtin/multi/round.go
pkg/builtin/multi/types.go
pkg/builtin/unary/types.go

issue #
Not Available
Not Available
Not Available

add some set up code for builtin functions

---

docs/en/MatrixOne/glossary.md

issue #
Not Available
Not Available
Add glossary page: listing of terms and concepts
Not Available

Add glossary page

---

docs/en/MatrixOne/Overview/SSB Test Performance.md

issue #
Not Available
Not Available
Add recommended specification for SSB test. 
Not Available

Add recommended specification for SSB test

---

pkg/vm/engine/aoe/engine/engine_test.go
pkg/vm/engine/aoe/engine/reader.go
pkg/vm/engine/aoe/engine/relation.go
pkg/vm/engine/aoe/engine/sparse_filter.go
pkg/vm/engine/aoe/engine/store.go
pkg/vm/engine/aoe/engine/types.go

issue #1281 
Not Available
Not Available
Not Available

Engine supports zonemap index

---

docs/en/MatrixOne/Get-Started/Tutorial/add_builtin_functions.md

issue #
Not Available
Not Available
Not Available

rephrase title

---

README.md

issue #
Not Available
Not Available
Not Available

change Monolitic to Monolithic

---

Makefile

issue #1691 
Not Available
Not Available
Not Available

support cross compile

---

pkg/vm/engine/tpe/doc.go
pkg/vm/engine/tpe/orderedcodec/constants.go
pkg/vm/engine/tpe/orderedcodec/decoder.go
pkg/vm/engine/tpe/orderedcodec/decoder_test.go
pkg/vm/engine/tpe/orderedcodec/encoder.go
pkg/vm/engine/tpe/orderedcodec/encoder_test.go
pkg/vm/engine/tpe/orderedcodec/types.go
pkg/vm/engine/tpe/tuplecodec/types.go

issue #995
issue #1060 
Transactional Processing Engine
Not Available
Not Available

init transaction processing engine (TPE)

---

pkg/vm/engine/tpe/orderedcodec/constants.go
pkg/vm/engine/tpe/orderedcodec/decoder.go
pkg/vm/engine/tpe/orderedcodec/decoder_test.go
pkg/vm/engine/tpe/orderedcodec/encoder.go
pkg/vm/engine/tpe/orderedcodec/encoder_test.go
pkg/vm/engine/tpe/orderedcodec/types.go

add variable uint64 and bytes codec
issue #995
issue #1060
Not Available
Not Available
Not Available

add uint64/bytes codec

---

pkg/vm/driver/aoe/storage.go

issue #1703 
Not Available
Not Available
Not Available

Add to judge whether the segment exists in GetInitialStates

---

pkg/vm/engine/tpe/orderedcodec/decoder.go
pkg/vm/engine/tpe/orderedcodec/decoder_test.go
pkg/vm/engine/tpe/orderedcodec/encoder.go
pkg/vm/engine/tpe/orderedcodec/encoder_test.go
pkg/vm/engine/tpe/orderedcodec/types.go
pkg/vm/engine/tpe/tuplecodec/constants.go
pkg/vm/engine/tpe/tuplecodec/decoder.go
pkg/vm/engine/tpe/tuplecodec/decoder_test.go
pkg/vm/engine/tpe/tuplecodec/encoder.go
pkg/vm/engine/tpe/tuplecodec/encoder_test.go
pkg/vm/engine/tpe/tuplecodec/types.go

issue #995 
issue #1060 
Not Available
Not Available
Not Available

init primary index codec

---

pkg/chaostesting/9p.go
pkg/chaostesting/net_port.go
pkg/chaostesting/testcube/nodes.go
pkg/chaostesting/testcube/script.py

updates issue #1469 
Not Available
Not Available
Not Available

chaostesting package bug fixes

---

Makefile
cmd/db-server/main.go

issue #1712 
Not Available
Not Available
Not Available

bug fix for crossing compile

---

pkg/sql/colexec/dedup/dedup.go
pkg/sql/viewexec/transform/transform.go
pkg/sql/viewexec/untransform/untransform.go

issue #1716
Not Available
Not Available
Not Available

Add support for nullable types to hashtable

---

pkg/vm/engine/tpe/tuplecodec/decoder.go
pkg/vm/engine/tpe/tuplecodec/decoder_test.go
pkg/vm/engine/tpe/tuplecodec/encoder.go
pkg/vm/engine/tpe/tuplecodec/key.go
pkg/vm/engine/tpe/tuplecodec/key_test.go
pkg/vm/engine/tpe/tuplecodec/types.go

issue #995
issue #1060 
Not Available
Not Available
Not Available

add key range

---

docs/en/MatrixOne/Overview/NYC Test Performance.md

issue #1732 
Not Available
Not Available
In NYC Test Performance.md
-Fix a typo error

Update NYC Test Performance.md

---

pkg/sql/compile/exec.go
pkg/sql/compile/scope.go
pkg/sql/compile/vtree.go
pkg/sql/plan/from.go
pkg/sql/plan/group.go
pkg/sql/plan/select.go
pkg/sql/plan/types.go
pkg/vm/pipeline/pipeline.go
pkg/vm/vm.go

issue #
Not Available
Not Available
Not Available

add comment codes for compute layer

---

pkg/chaostesting/temp_dir.go
pkg/chaostesting/testcube/cmd_clean.go
pkg/chaostesting/testcube/do.go
pkg/chaostesting/testcube/main.go
pkg/chaostesting/testcube/nodes.go
pkg/chaostesting/testcube/script.py

updates issue #1469 
Not Available
Not Available
Not Available

various fixes to chaostesting package

---

Makefile

issue #1712 
Not Available
Not Available
Not Available

bug fix for makefile

---

docs/en/MatrixOne/Contribution-Guide/Code-Style/code-comment-style.md
docs/en/MatrixOne/Contribution-Guide/Code-Style/code-of-conduct.md
docs/en/MatrixOne/Contribution-Guide/Code-Style/commit-pr-style.md
docs/en/MatrixOne/Contribution-Guide/How-to-Contribute/contribute-code.md
docs/en/MatrixOne/Contribution-Guide/How-to-Contribute/contribute-documentation.md
docs/en/MatrixOne/Contribution-Guide/How-to-Contribute/make-a-design.md
docs/en/MatrixOne/Contribution-Guide/How-to-Contribute/preparation.md
docs/en/MatrixOne/Contribution-Guide/How-to-Contribute/report-an-issue.md
docs/en/MatrixOne/Contribution-Guide/How-to-Contribute/review-a-pull-request.md
docs/en/MatrixOne/Contribution-Guide/How-to-Contribute/types-of-contributions.md
docs/en/MatrixOne/Contribution-Guide/make-your-first-contribution.md

issue #
Not Available
Not Available
Add complete contribution guide.

Add Contribution Guide Section

---

docs/en/MatrixOne/Contribution-Guide/Code-Style/code-comment-style.md

issue #
Not Available
Not Available
Fix several words error

Fix some words error

---

pkg/vm/engine/tpe/computation/computationHandler.go
pkg/vm/engine/tpe/descriptor/types.go
pkg/vm/engine/tpe/epoch/epoch.go
pkg/vm/engine/tpe/epoch/epoch_test.go
pkg/vm/engine/tpe/tuplecodec/computationhandler.go
pkg/vm/engine/tpe/tuplecodec/computationhandler_test.go
pkg/vm/engine/tpe/tuplecodec/constants.go
pkg/vm/engine/tpe/tuplecodec/descriptorhandler.go
pkg/vm/engine/tpe/tuplecodec/memorykv.go
pkg/vm/engine/tpe/tuplecodec/memorykv_test.go

issue #1060 
issue #995 
Not Available
Not Available
Not Available

add ddl create/drop

---

pkg/vm/engine/aoe/storage/metadata/v1/block.go
pkg/vm/engine/aoe/storage/metadata/v1/database.go
pkg/vm/engine/aoe/storage/metadata/v1/segment.go
pkg/vm/engine/aoe/storage/metadata/v1/table.go

issue #
use CommitInfo.Clone() in toLogEntry
Not Available
Not Available

Fix Metadata compaction

---

pkg/vm/pipeline/pipeline.go

issue #1281
Not Available
Not Available
Not Available

Enable sparse filter

---

docs/en/MatrixOne/Reference/Customer-Functions/floor.md
docs/en/MatrixOne/Reference/Customer-Functions/length.md
docs/en/MatrixOne/Reference/Customer-Functions/round.md

issue #
Not Available
Add docs about round() function
round.md

Add docs about round() function

---

pkg/container/vector/vector.go
pkg/sql/colexec/dedup/dedup.go
pkg/sql/viewexec/transform/transform.go
pkg/sql/viewexec/untransform/untransform.go

issue #1737
Not Available
Not Available
Not Available

Fix a bug in UnionBatch for nullable type

---

pkg/container/vector/vector.go

Fixes issue #1737
Not Available
Not Available
Not Available

Fix null handling in UnionBatch

---

docs/en/MatrixOne/Overview/mysql-compatibility.md
docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/in.md

issue #
Add docs about operator 'in' and update docs about mysql compatibility
Not Available
Not Available

Add docs about operator 'in'

---

pkg/sql/parsers/dialect/mysql/mysql_sql.go
pkg/sql/parsers/dialect/mysql/mysql_sql.y
pkg/sql/parsers/dialect/mysql/mysql_sql_test.go

issue #1762
Not Available
Not Available
Not Available

[Enhancement]: Add the default type of join (#1762)

---

pkg/vm/engine/tpe/computation/computationHandler.go
pkg/vm/engine/tpe/descriptor/types.go
pkg/vm/engine/tpe/index/indexhandler.go
pkg/vm/engine/tpe/tuplecodec/computationhandler.go
pkg/vm/engine/tpe/tuplecodec/indexhandler.go
pkg/vm/engine/tpe/tuplecodec/indexhandler_test.go
pkg/vm/engine/tpe/tuplecodec/rowcolumnconverter.go
pkg/vm/engine/tpe/tuplecodec/rowcolumnconverter_test.go
pkg/vm/engine/tpe/tuplecodec/util.go

issue #1060 
issue #995 
Not Available
Not Available
Not Available

Add index read/write; update row column converter

---

pkg/frontend/protocol.go
pkg/frontend/routine.go
pkg/frontend/routine_manager.go

issue #1624
Not Available
Not Available
Not Available

fix [Bug]:buffer busy #1624

---

Makefile

issue #1759
Not Available
Not Available
Not Available

makefile opt

---

docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/select.md

issue #
Add 'select into' into docs
Not Available
Not Available

Add 'select into' into docs

---

cmd/db-server/main.go
pkg/frontend/mysql_protocol.go
pkg/sql/colexec/projection/projection.go

issue #1649  #1757 
Not Available
Not Available
Not Available

fix a projecion bug, and a version display bug

---

cmd/db-server/main.go
cmd/generate-config/system_vars_def.toml
go.mod
pkg/vm/engine/tpe/computation/computationHandler.go
pkg/vm/engine/tpe/descriptor/types.go
pkg/vm/engine/tpe/engine/database.go
pkg/vm/engine/tpe/engine/engine.go
pkg/vm/engine/tpe/engine/reader.go
pkg/vm/engine/tpe/engine/relation.go
pkg/vm/engine/tpe/engine/types.go
pkg/vm/engine/tpe/tuplecodec/computationhandler.go
pkg/vm/engine/tpe/tuplecodec/computationhandler_test.go
pkg/vm/engine/tpe/tuplecodec/indexhandler.go
pkg/vm/engine/tpe/tuplecodec/rowcolumnconverter.go
pkg/vm/engine/tpe/tuplecodec/util.go

issue #1060 
issue #995 
Not Available
Not Available
Not Available

attach the tpe to the computation engine

---

pkg/vm/pipeline/pipeline.go

issue #
Not Available
Not Available
Not Available

Fixed mo-server crash when filtering query

---

docs/en/MatrixOne/Contribution-Guide/How-to-Contribute/contribute-code.md
docs/en/MatrixOne/Contribution-Guide/How-to-Contribute/contribute-documentation.md
docs/en/MatrixOne/Contribution-Guide/How-to-Contribute/preparation.md
docs/en/MatrixOne/Contribution-Guide/How-to-Contribute/report-an-issue.md
docs/en/MatrixOne/Contribution-Guide/How-to-Contribute/review-a-pull-request.md

issue #
Not Available
Not Available
Fix several file path issues for contribution guide.

Fix several file path issue

---

docs/en/MatrixOne/Contribution-Guide/Code-Style/code-comment-style.md
docs/en/MatrixOne/Contribution-Guide/Code-Style/code-of-conduct.md
docs/en/MatrixOne/Contribution-Guide/How-to-Contribute/contribute-code.md
docs/en/MatrixOne/Contribution-Guide/How-to-Contribute/contribute-documentation.md
docs/en/MatrixOne/Contribution-Guide/How-to-Contribute/preparation.md
docs/en/MatrixOne/Contribution-Guide/How-to-Contribute/report-an-issue.md
docs/en/MatrixOne/Contribution-Guide/How-to-Contribute/review-a-pull-request.md
docs/en/MatrixOne/Contribution-Guide/How-to-Contribute/types-of-contributions.md
docs/en/MatrixOne/Contribution-Guide/make-your-first-contribution.md

issue #
Modify some grammar errors
Not Available
Not Available

Modify some grammar errors

---

pkg/sql/colexec/extend/overload/init.go
pkg/sql/colexec/extend/overload/overloadGenerate.go
pkg/sql/unittest/operator_test.go
pkg/vectorize/div/div.go

issue #1721 
Not Available
Not Available
Not Available

Implement operation semantics in issue#1721

---

pkg/vm/engine/tpe/computation/computationHandler.go
pkg/vm/engine/tpe/engine/database.go
pkg/vm/engine/tpe/engine/database_test.go
pkg/vm/engine/tpe/engine/engine.go
pkg/vm/engine/tpe/engine/engine_test.go
pkg/vm/engine/tpe/engine/relation.go
pkg/vm/engine/tpe/engine/relation_test.go
pkg/vm/engine/tpe/index/indexhandler.go
pkg/vm/engine/tpe/tuplecodec/computationhandler.go
pkg/vm/engine/tpe/tuplecodec/encoder.go
pkg/vm/engine/tpe/tuplecodec/indexhandler.go
pkg/vm/engine/tpe/tuplecodec/indexhandler_test.go
pkg/vm/engine/tpe/tuplecodec/rowcolumnconverter_test.go
pkg/vm/engine/tpe/tuplecodec/util.go

issue #1060 
issue #995 
Not Available
Not Available
Not Available

update tpe write logic

---

pkg/sql/colexec/extend/overload/init.go

issue #1786 
Not Available
Not Available
Not Available

fix a bug in overload/init.go

---

go.mod
go.sum
optools/test/config.toml
pkg/catalog/catalog_test.go
pkg/frontend/epochgc_test.go
pkg/vm/driver/aoe/storage.go
pkg/vm/driver/test/storage_test.go
pkg/vm/driver/testutil/testutil.go
pkg/vm/engine/aoe/engine/engine_test.go
pkg/vm/engine/aoe/engine/relation.go

issue #1703 
Not Available
Not Available
Not Available

Update relation when shard is unavailable

---

pkg/vm/driver/aoe/storage.go
pkg/vm/engine/aoe/engine/database.go
pkg/vm/engine/aoe/engine/relation.go
pkg/vm/engine/aoe/engine/types.go

issue #1703 
Not Available
Not Available
Not Available

Fix update relation

---

pkg/container/vector/vector.go
pkg/vm/engine/aoe/storage/container/vector/stdvec.go
pkg/vm/engine/aoe/storage/container/vector/strvec.go

issue #1790 
Not Available
Not Available
Not Available

 fix some possible misuses of reflect.SliceHeader 

---

pkg/vm/driver/aoe/storage.go

issue #
Not Available
Not Available
Not Available

Fix GetInitialStates

---

pkg/container/batch/types.go
pkg/sql/colexec/extend/overload/like.template
pkg/sql/compile/exec.go
pkg/sql/compile/scope.go
pkg/sql/compile/types.go
pkg/sql/compile/vtree.go
pkg/sql/plan/create_table.go
pkg/sql/plan/prune.go
pkg/vectorize/like/like.go
pkg/vm/engine/aoe/common/helper/helper.go
pkg/vm/engine/tpe/engine/relation.go
pkg/vm/engine/tpe/engine/relation_test.go
pkg/vm/engine/types.go

issue #
1. add some comments for compute-layer
2. show columns support show primary key
Not Available
Not Available

add some comments for compute-layer

---

.gitignore
cmd/db-server/main.go
pkg/vm/engine/tpe/descriptor/types.go
pkg/vm/engine/tpe/engine/database_test.go
pkg/vm/engine/tpe/engine/engine.go
pkg/vm/engine/tpe/engine/engine_test.go
pkg/vm/engine/tpe/engine/reader_test.go
pkg/vm/engine/tpe/engine/relation_test.go
pkg/vm/engine/tpe/engine/types.go
pkg/vm/engine/tpe/tuplecodec/computationhandler.go
pkg/vm/engine/tpe/tuplecodec/computationhandler_test.go
pkg/vm/engine/tpe/tuplecodec/cubekv.go
pkg/vm/engine/tpe/tuplecodec/cubekv_test.go
pkg/vm/engine/tpe/tuplecodec/descriptorhandler.go
pkg/vm/engine/tpe/tuplecodec/indexhandler.go
pkg/vm/engine/tpe/tuplecodec/key.go
pkg/vm/engine/tpe/tuplecodec/kv_types.go
pkg/vm/engine/tpe/tuplecodec/memorykv.go

issue #1060 
issue #995 
Not Available
Not Available
Not Available

update ddl create/drop; attach cubeDriver to tpe

---

cmd/db-server/profile.go

for debugging issue #1800 
log memory metrics periodically
Not Available
Not Available

add log-metrics-interval flag

---

go.mod
go.sum
pkg/vm/driver/aoe/storage.go
pkg/vm/engine/aoe/storage/aoedb/v1/snapshot_test.go
pkg/vm/engine/aoe/storage/metadata/v1/replayer.go
pkg/vm/engine/aoe/storage/wal/shard/manager.go
pkg/vm/engine/aoe/storage/wal/types.go

issue #1798 
Not Available
Not Available
Not Available

Fix restoreWal

---

docs/en/MatrixOne/Contribution-Guide/How-to-Contribute/contribute-code.md
docs/en/MatrixOne/Get-Started/Tutorial/SSB-test-with-matrixone.md
docs/en/MatrixOne/Reference/SQL-Reference/Aggregate-Functions/sum.md
docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/inner-join.md

issue #
Modify some errors in docs
Not Available
Not Available

Modify some errors in docs

---

pkg/sql/colexec/mergelimit/mergelimit.go

issue #1817 
Not Available
Not Available
Not Available

fix a mergeLimit operator bug

---

pkg/container/ring/max/date.go
pkg/container/ring/max/datetime.go
pkg/container/ring/max/types.go
pkg/container/ring/min/date.go
pkg/container/ring/min/datetime.go
pkg/container/ring/min/int32.go
pkg/container/ring/min/types.go
pkg/sql/viewexec/transformer/transformer.go

issue #1805 
Not Available
Not Available
Not Available

fix issue#1805, support max, min for date type

---

docs/en/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions.md

issue #
Not Available
Not Available
Add a tutorial about how to develop builtin functions.

Add built-in function development tutorial

---

pkg/frontend/epochgc.go
pkg/frontend/server.go

issue #
Not Available
Not Available
Not Available

use logutil in frontend package

---

pkg/frontend/epochgc.go

issue #
Not Available
Not Available
Not Available

fix log level

---

pkg/sql/rewrite/astrewrite.go

issue #1660
Not Available
Not Available
Not Available

fix illgeal where condition expression

---

docs/en/MatrixOne/Overview/what's-new.md
docs/en/MatrixOne/Release-Notes/v0.3.0.md

issue #
Not Available
Not Available
Add 0.3.0 release note

Add 0.3.0 release note

---

cmd/db-server/main.go
pkg/frontend/mysql_protocol.go

issue #1853 #1854 
Not Available
Not Available
Not Available

delete non-numeric characters of the version number

---

.github/workflows/docker_ci.yml

issue #
Optimeize docker build and push workflow
1. Push one nightly image every day at 10:00.pm
2. Update latest and official version image  when release is released
3. Remove pr build trigger
Not Available

Optimize  docker ci

---

.github/workflows/docker_ci.yml

issue #
Not Available
Not Available
Not Available

fix docker ci

---

pkg/builtin/multi/pi.go
pkg/builtin/types.go
pkg/vectorize/pi/pi.go
pkg/vectorize/pi/pi_test.go

issue #1821
implement pi builtin function (matrixorigin#1821)
Not Available
Not Available

implement pi builtin function (matrixorigin#1821)

---

docs/en/MatrixOne/Overview/MatrixOne-Tech-Design/matrixone-techdesign.md

issue #
Not Available
Not Available
Update technical design doc part.

Complete technical design

---

cmd/db-server/main.go
pkg/vm/engine/tpe/descriptor/types.go
pkg/vm/engine/tpe/engine/engine.go
pkg/vm/engine/tpe/engine/types.go
pkg/vm/engine/tpe/tuplecodec/computationhandler.go
pkg/vm/engine/tpe/tuplecodec/computationhandler_test.go
pkg/vm/engine/tpe/tuplecodec/constants.go
pkg/vm/engine/tpe/tuplecodec/cubekv.go
pkg/vm/engine/tpe/tuplecodec/cubekv_test.go
pkg/vm/engine/tpe/tuplecodec/descriptorhandler.go
pkg/vm/engine/tpe/tuplecodec/descriptorhandler_test.go
pkg/vm/engine/tpe/tuplecodec/epoch.go
pkg/vm/engine/tpe/tuplecodec/epoch_test.go
pkg/vm/engine/tpe/tuplecodec/indexhandler.go
pkg/vm/engine/tpe/tuplecodec/indexhandler_test.go
pkg/vm/engine/tpe/tuplecodec/kv_types.go
pkg/vm/engine/tpe/tuplecodec/memorykv.go
pkg/vm/engine/tpe/tuplecodec/memorykv_test.go

issue #1060 
issue #995 
Not Available
Not Available
Not Available

update cubeKV; promote the write efficiency;

---

.github/workflows/daily_benchmark_task.yml

issue #1767 
Not Available
Not Available
Not Available

Add daily_benchmark_task.yml

---

pkg/vm/driver/cube_driver.go
pkg/vm/driver/error/errors.go

issue #1913 
Not Available
Not Available
Not Available

Fix cubedriver.Start()

---

pkg/container/ring/types.go
pkg/container/ring/variance/variance.go
pkg/container/ring/variance/variance_test.go
pkg/sql/colexec/mergeorder/mergeorder.go
pkg/sql/plan/types.go
pkg/sql/protocol/protocol.go
pkg/sql/protocol/protocol_test.go
pkg/sql/protocol/types.go
pkg/sql/unittest/ddl_test.go
pkg/sql/viewexec/transformer/transformer.go
pkg/sql/viewexec/transformer/types.go

1. Added a sample implementation of the aggregation function
2. Fix a mergeOrder bug
3. Add comments for Ring interface
issue #
Not Available
Not Available
Not Available

Provide sample aggregate function code, Fix an operator bug.

---

docs/en/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions.md

issue #
Not Available
Not Available
Not Available

builtin function tutorial minor tuning

---

pkg/frontend/mysql_cmd_executor.go
pkg/sql/colexec/deleteTag/deleteTag.go
pkg/sql/colexec/deleteTag/types.go
pkg/sql/colexec/updateTag/types.go
pkg/sql/colexec/updateTag/updateTag.go
pkg/sql/compile/exec.go
pkg/sql/compile/scope.go
pkg/sql/compile/types.go
pkg/sql/compile/vtree.go
pkg/sql/plan/build.go
pkg/sql/plan/delete.go
pkg/sql/plan/types.go
pkg/sql/plan/update.go
pkg/sql/unittest/ddl_test.go
pkg/vm/engine/tpe/engine/relation.go
pkg/vm/engine/tpe/index/indexhandler.go
pkg/vm/engine/tpe/tuplecodec/computationhandler.go
pkg/vm/engine/tpe/tuplecodec/indexhandler.go
pkg/vm/engine/tpe/tuplecodec/indexhandler_test.go
pkg/vm/engine/tpe/tuplecodec/rowcolumnconverter.go
pkg/vm/overload.go

issue #1877 
Not Available
Not Available
Not Available

Support deletion from a single of table (#1877)

---

docs/en/MatrixOne/Contribution-Guide/Tutorial/develop_aggregate_functions.md

issue #
Not Available
Not Available
Add tutorial for developing aggregate function for MatrixOne

Add aggregate function tutorial

---

pkg/vm/engine/aoe/common/helper/helper_test.go
pkg/vm/engine/aoe/storage/layout/dataio/blk_test.go
pkg/vm/engine/aoe/storage/logstore/entry.go
pkg/vm/engine/aoe/storage/metadata/v1/metadata_test.go

issue #
Not Available
Not Available
Not Available

fix static code analysis error in aoe

---

pkg/container/ring/variance/variance.go
pkg/sql/protocol/protocol.go
pkg/sql/protocol/protocol_test.go
pkg/sql/viewexec/transformer/transformer.go

issue #
Update a typed wrong variable, makes it more understandable
Not Available
Not Available

More understandable variable name in variance sample code

---

.github/workflows/build_matrixone.yml
.github/workflows/build_matrixone_1.18.yml

issue #
Not Available
Not Available
Not Available

code formatting

---

pkg/vm/engine/memEngine/testEngine.go

issue #
Not Available
Not Available
Not Available

fix static code analysis in memEngine

---

pkg/vectorize/floor/floor_avx2_amd64.s
pkg/vectorize/round/round_avx2_amd64.s

issue #
Not Available
Not Available
Not Available

clean floor/round vectorize code

---

pkg/vm/engine/aoe/storage/metadata/v1/metadata_test.go

issue #
Not Available
Not Available
Not Available

Fix the case that WaitExpect time is not enough

---

pkg/vm/engine/aoe/storage/testutils/helpers.go

issue #
Not Available
Not Available
Not Available

Update the timeout value of WaitExpect to adapt to worse CI running platforms

---

optools/run_ut.sh

issue #
Not Available
Not Available
Not Available

Add flag -tags to SCA command

---

pkg/vm/driver/aoe/storage.go

issue #
Not Available
Not Available
Not Available

Fix RemoveShard

---

pkg/vm/engine/aoe/storage/aoedb/v1/db_test.go

Signed-off-by: asuka <312856403@qq.com>
issue #
follow-up of #1958 
Not Available
Not Available

disable more BSI related tests

---

pkg/sql/colexec/extend/overload/binary.go

issue #1914 
Not Available
Not Available
Not Available

fix issue#1914

---

pkg/vm/engine/tpe/orderedcodec/types.go
pkg/vm/engine/tpe/tuplecodec/serialize.go
pkg/vm/engine/tpe/tuplecodec/serialize_test.go

issue #1060 
issue #995
Not Available
Not Available
Not Available

add layout for the serialization

---

docs/cn/MatrixOne/Get-Started/Playground.md
docs/cn/MatrixOne/Get-Started/connect-to-matrixone-server.md
docs/cn/MatrixOne/Get-Started/install-distributed-matrixone.md
docs/cn/MatrixOne/Get-Started/install-standalone-matrixone.md

issue #
Update Chinese docs
Not Available
Not Available

Update Chinese docs

---

docs/cn/MatrixOne/Get-Started/Tutorial/SSB-test-with-matrixone.md
docs/en/MatrixOne/Get-Started/Tutorial/SSB-test-with-matrixone.md

issue #
Not Available
Not Available
Not Available

Adjust SSB document

---

docs/cn/MatrixOne/Get-Started/Tutorial/SSB-test-with-matrixone.md
docs/en/MatrixOne/Get-Started/Tutorial/SSB-test-with-matrixone.md

issue #2028 
Let the user understand better。
Not Available
Not Available

Update SSB-test-with-matrixone.md (#2028)

---

pkg/builtin/multi/ceil.go
pkg/builtin/multi/floor.go
pkg/builtin/multi/pi.go
pkg/builtin/multi/round.go
pkg/builtin/unary/ln.go

issue #
Not Available
1. Error string should not be capitalized or end with punctuation mark
2. Use camel case instead of snake case
3. Remove unnecessary comments
Not Available

Fix linter warning

---

go.sum
pkg/vm/driver/cube_driver.go
pkg/vm/driver/kv/executor.go
pkg/vm/engine/tpe/tuplecodec/cubekv.go

issue #1060 
issue #995 
Not Available
Not Available
Not Available

update cubeKV for new cube client

---

docs/en/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions.md

issue #
Not Available
Not Available
Not Available

explain boolean parameter in Fn

---

pkg/vm/engine/aoe/storage/testutils/helpers.go

issue #
Not Available
Not Available
Not Available

Update the timeout value of WaitExpect

---

go.sum
pkg/builtin/types.go
pkg/builtin/unary/tan.go
pkg/vectorize/tan/tan.go
pkg/vectorize/tan/tan_test.go

issue #1968
implement Tan builtin function
Not Available
Not Available

[MatrixCamp] add function tan

---

go.sum
pkg/builtin/types.go
pkg/builtin/unary/sin.go
pkg/vectorize/sin/sin.go
pkg/vectorize/sin/sin_test.go

issue #1966
implement Ceil builtin function
Not Available
Not Available

[MatrixCamp] add function sin

---

cmd/generate-config/system_vars_def.toml
docs/cn/MatrixOne/Get-Started/install-distributed-matrixone.md
docs/en/MatrixOne/Get-Started/install-distributed-matrixone.md
pkg/vm/engine/aoe/engine/database.go

issue #2068 
Not Available
Not Available
Not Available

Fix the bug of query data error due to split

---

pkg/vm/engine/aoe/engine/types.go
pkg/vm/engine/aoe/engine/worker.go

issue #
Not Available
Not Available
Not Available

Fixed the bug that the buffer of Zs in the reader worker was reset

---

pkg/container/ring/variance/variance.go
pkg/container/ring/variance/variance_test.go
pkg/sql/protocol/protocol.go
pkg/sql/protocol/protocol_test.go
pkg/sql/viewexec/transformer/transformer.go
pkg/sql/viewexec/transformer/types.go

issue #
refactor the variance function codes.
And it is not a sample now. It can work normally.
Not Available
Not Available

refactor aggregate function `variance`

---

cmd/db-server/main.go
cmd/generate-config/system_vars_def.toml
go.mod
go.sum
optools/test/config.toml
pkg/catalog/catalog_test.go
pkg/frontend/epochgc_test.go
pkg/vm/driver/aoe/storage.go
pkg/vm/driver/config/config.go
pkg/vm/driver/cube_driver.go
pkg/vm/driver/test/storage_test.go
pkg/vm/driver/testutil/testutil.go
pkg/vm/engine/aoe/engine/engine_test.go

issue #
Not Available
Not Available
Not Available

Independent configuration of cube engine features

---

go.mod
go.sum
pkg/vm/driver/cube_driver.go

issue #
Not Available
Not Available
Not Available

Remove config about ShardGroups

---

pkg/builtin/types.go
pkg/builtin/unary/month.go
pkg/container/types/date.go
pkg/container/types/datetime.go
pkg/vectorize/month/month.go
pkg/vectorize/month/month_test.go

Signed-off-by: RinChanNOWWW <hzy427@gmail.com>
issue #2049
Add built-in function MONTH()
Not Available
Not Available

[MatrixCamp] Add Built-in function MONTH

---

pkg/chaostesting/9p_test.go
pkg/chaostesting/fuse_test.go
pkg/chaostesting/go.mod
pkg/chaostesting/go.sum
pkg/chaostesting/testcube/config_default.go
pkg/chaostesting/testcube/config_randomize.go
pkg/chaostesting/testcube/kv.go
pkg/chaostesting/testcube/nodes.go
pkg/chaostesting/testcube/shard_state_aware.go
pkg/chaostesting/testcube/transport.go
pkg/chaostesting/util_random.go

updates issue #1469 
Not Available
Not Available
Not Available

chaostesting: update to newest cube

---

docs/en/MatrixOne/Contribution-Guide/Tutorial/develop_aggregate_functions.md

issue #
Not Available
Not Available
Update aggregate function tutorial

Update aggregate function tutorial

---

pkg/container/ring/types.go
pkg/container/ring/variance/variance.go

issue #
Not Available
Not Available
Not Available

fix a variance bug, and update the comments for ring

---

go.sum
pkg/container/ring/bitand/numeric.go
pkg/container/ring/bitand/numeric_test.go
pkg/sql/protocol/protocol.go
pkg/sql/protocol/protocol_test.go
pkg/sql/protocol/types.go
pkg/sql/viewexec/transformer/transformer.go
pkg/sql/viewexec/transformer/types.go

issue #1993
Add aggregate function bit_and
Not Available
Not Available

[MatrixCamp] Add Aggregate function bit_and

---

pkg/builtin/multi/ceil.go
pkg/builtin/multi/floor.go
pkg/builtin/multi/round.go
pkg/sql/colexec/extend/overload/multi.go
pkg/sql/colexec/extend/unary.go

issue #2142
Not Available
Not Available
Not Available

check whether a vector is constant in multiEval, unaryEval

---

pkg/logger/logger.go
pkg/logutil/api.go
pkg/partition/partition.go
pkg/vm/engine/memEngine/kv/kv.go
pkg/vm/engine/memEngine/kv/types.go

Part of issue #2140 
Not Available
Not Available
Not Available

fix static code check

---

cmd/db-server/main.go
cmd/generate-config/system_vars_def.toml
go.mod
go.sum
pkg/vm/engine/tpe/engine/database_test.go
pkg/vm/engine/tpe/engine/engine.go
pkg/vm/engine/tpe/engine/engine_test.go
pkg/vm/engine/tpe/engine/reader_test.go
pkg/vm/engine/tpe/engine/relation_test.go
pkg/vm/engine/tpe/engine/types.go
pkg/vm/engine/tpe/tuplecodec/descriptorhandler.go
pkg/vm/engine/tpe/tuplecodec/encoder.go
pkg/vm/engine/tpe/tuplecodec/indexhandler.go
pkg/vm/engine/tpe/tuplecodec/indexhandler_test.go
pkg/vm/engine/tpe/tuplecodec/rowcolumnconverter.go
pkg/vm/engine/tpe/tuplecodec/serialize.go
pkg/vm/engine/tpe/tuplecodec/serialize_test.go

issue #1060 
issue #995 
Not Available
Not Available
Not Available

update layout of the serialization

---

optools/run_ut.sh

issue #
Not Available
Not Available
Not Available

Fix make ut

---

.github/workflows/dis_test.yml

issue #
Not Available
Not Available
Not Available

fix dis test docker layer cache

---

pkg/vm/driver/kv/executor.go
pkg/vm/engine/tpe/engine/reader.go
pkg/vm/engine/tpe/engine/relation.go
pkg/vm/engine/tpe/engine/types.go
pkg/vm/engine/tpe/tuplecodec/computationhandler.go
pkg/vm/engine/tpe/tuplecodec/cubekv.go
pkg/vm/engine/tpe/tuplecodec/indexhandler.go

issue #1060 
issue #995 
Not Available
Not Available
Not Available

update parallel reader

---

pkg/vm/driver/kv/executor.go
pkg/vm/engine/tpe/engine/relation.go
pkg/vm/engine/tpe/engine/types.go
pkg/vm/engine/tpe/tuplecodec/computationhandler.go
pkg/vm/engine/tpe/tuplecodec/cubekv.go
pkg/vm/engine/tpe/tuplecodec/cubekv_test.go
pkg/vm/engine/tpe/tuplecodec/indexhandler.go
pkg/vm/engine/tpe/tuplecodec/kv_types.go

issue #1060 
issue #995 
Not Available
Not Available
Not Available

update parallel reader; add approximate statistics

---

pkg/container/ring/bitxor/bit_xor.go
pkg/container/ring/bitxor/bit_xor_test.go
pkg/container/ring/bitxor/types.go
pkg/sql/protocol/protocol.go
pkg/sql/protocol/protocol_test.go
pkg/sql/protocol/types.go
pkg/sql/viewexec/transformer/transformer.go
pkg/sql/viewexec/transformer/types.go

issue #1995 
support bit_xor agg function.
Not Available
Not Available

[MatrixCamp]  support bit_xor

---

pkg/container/ring/variance/variance.go
pkg/container/ring/variance/variance_test.go
pkg/sql/viewexec/transformer/transformer.go

issue #
Not Available
Not Available
Not Available

add type check for aggregate function `variance`

---

docs/cn/MatrixOne/Get-Started/install-standalone-matrixone.md

issue #
Add Chinese docs about MO installation
Not Available
Not Available

Add Chinese docs about MO installation

---

pkg/builtin/types.go
pkg/builtin/unary/sinh.go
pkg/vectorize/sinh/sinh.go
pkg/vectorize/sinh/sinh_test.go

issue #2094 
Add Built-in function sinh()
Not Available
Not Available

[MatrixCamp] builtin function sinh

---

Makefile

issue #
Not Available
Not Available
Not Available

Fix make static check

---

pkg/builtin/multi/rpad.go
pkg/builtin/types.go
pkg/vectorize/rpad/rpad.go
pkg/vectorize/rpad/rpad_test.go

issue #1986 
Add built-in function rpad(str,len,padstr)
Not Available
Not Available

[MatrixCamp] Add built-in function rpad

---

pkg/sql/viewexec/times/times.go

issue #1881
Not Available
Not Available
Not Available

Fix the bug of times

---

pkg/vm/engine/tpe/engine/reader.go
pkg/vm/engine/tpe/engine/relation.go
pkg/vm/engine/tpe/tuplecodec/indexhandler.go
pkg/vm/engine/tpe/tuplecodec/util.go

issue #1060 
issue #995 
Not Available
Not Available
Not Available

fix logging errors

---

pkg/sql/compile/exec.go
pkg/sql/compile/scope.go
pkg/sql/plan/expr.go

issue #2186
issue #2189
Not Available
Not Available
Not Available

Fix the bug of subquery

---

.github/workflows/contributors.yml
README.md
README_CN.md

issue #
Not Available
A yml workflow is added to automate listing contributors. 
Update readme to a better looking

Modify MatrixOne project Readme and add contributor bot workflow

---

.github/workflows/contributors.yml

issue #
Fix the github token problem for contributors fetch workflow
Not Available
Not Available

Fix contributors workflow

---

.github/workflows/contributors.yml

issue #
Not Available
Not Available
Not Available

Modify contributor bot behavior

---

pkg/sql/protocol/protocol.go
pkg/sql/protocol/protocol_test.go
pkg/sql/protocol/types.go
pkg/sql/viewexec/transformer/transformer.go
pkg/sql/viewexec/transformer/types.go

issue #2198 
Not Available
Not Available
Not Available

add serialization function for max/min's DateRing and DatetimeRing

---

pkg/vm/engine/tpe/tuplecodec/util.go

issue #1060 
issue #995 
Not Available
Not Available
Not Available

tpe: fix errors of filling the vector for char and varchar

---

pkg/sql/plan2/mock.go
pkg/sql/plan2/optimizer.go
pkg/sql/plan2/ser.go
pkg/sql/plan2/tpch/ddl.sql
pkg/sql/plan2/tpch/q1.sql
pkg/sql/plan2/tpch/q10.sql
pkg/sql/plan2/tpch/q11.sql
pkg/sql/plan2/tpch/q12.sql
pkg/sql/plan2/tpch/q13.sql
pkg/sql/plan2/tpch/q14.sql
pkg/sql/plan2/tpch/q15.sql
pkg/sql/plan2/tpch/q16.sql
pkg/sql/plan2/tpch/q17.sql
pkg/sql/plan2/tpch/q18.sql
pkg/sql/plan2/tpch/q19.sql
pkg/sql/plan2/tpch/q2.sql
pkg/sql/plan2/tpch/q20.sql
pkg/sql/plan2/tpch/q21.sql
pkg/sql/plan2/tpch/q22.sql
pkg/sql/plan2/tpch/q3.sql
pkg/sql/plan2/tpch/q4.sql
pkg/sql/plan2/tpch/q5.sql
pkg/sql/plan2/tpch/q6.sql
pkg/sql/plan2/tpch/q7.sql
pkg/sql/plan2/tpch/q8.sql
pkg/sql/plan2/tpch/q9.sql
pkg/sql/plan2/tpch/simple.sql
pkg/sql/plan2/tpch_test.go

Right now it is almost empty, but we hope to implement
the optimizer that turns the parse tree into a plan tree.
Added tpch parser test.
issue #
Not Available
Not Available
Not Available

Adding plan2 dir.

---

optools/run_ut.sh

issue #
Not Available
Not Available
Not Available

bump the ut timeout  up to 30m

---

pkg/vm/engine/aoe/storage/db/replay.go

issue #2193
Not Available
Not Available
Not Available

Fix the bug of repeated data append after mo restart

---

pkg/sql/plan2/function.go

Right now it is almost empty, but we hope to implement
the optimizer that turns the parse tree into a plan tree.
Added tpch parser test.
issue #
Not Available
Not Available
Not Available

Adding builtin functions.

---

.github/workflows/contributors.yml

issue #
Not Available
Not Available
Not Available

optimize contributors.yml, add new contribution check.

---

Makefile

issue #
Added makefile targets to install and use molint. Molint is created to help enforcing #2150 
Not Available
Not Available

Added makefile targets to install and use molint

---

cmd/db-server/main.go
pkg/vm/engine/tpe/engine/reader.go
pkg/vm/engine/tpe/engine/toolKitHandler.go
pkg/vm/engine/tpe/engine/toolKitHandler_test.go
pkg/vm/engine/tpe/tuplecodec/computationhandler.go
pkg/vm/engine/tpe/tuplecodec/indexhandler_test.go
pkg/vm/engine/tpe/tuplecodec/rowcolumnconverter.go
pkg/vm/engine/tpe/tuplecodec/rowcolumnconverter_test.go
pkg/vm/engine/tpe/tuplecodec/util.go

issue #
Not Available
Not Available
Not Available

add testcase code

---

go.mod
go.sum
pkg/vm/driver/test/storage_test.go

Fix #2192.
issue # 2192
Not Available
Not Available
Not Available

Fix build break.

---

go.mod
go.sum
pkg/sql/compile/operator.go
pkg/sql/compile/scope.go

issue #2242
Not Available
Not Available
Not Available

Fix the bug of stuck

---

docs/en/MatrixOne/Overview/MatrixOne-Tech-Design/matrixone-techdesign.md

issue #
Not Available
Not Available
Not Available

Fix AOE rfc path error

---

README_CN.md

issue #
Not Available
Not Available
Not Available

Fix the chinese readme doc path

---

optools/images/Dockerfile
optools/test/Dockerfile.bvt
optools/test/Dockerfile.mo

issue #
Not Available
Not Available
Not Available

update docker go version to 1.18

---

docs/en/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions.md

issue #2224 
Not Available
Not Available
Not Available

Refine builtin function guidance

---

cmd/db-server/main.go
cmd/generate-config/system_vars_def.toml
pkg/sql/compile/scope.go
pkg/sql/compile/transfer.go
pkg/sql/handler/recover.go
pkg/sql/protocol/types.go
pkg/vm/driver/cube_driver.go
pkg/vm/engine/tpe/engine/database.go
pkg/vm/engine/tpe/engine/engine.go
pkg/vm/engine/tpe/engine/reader.go
pkg/vm/engine/tpe/engine/reader_test.go
pkg/vm/engine/tpe/engine/relation.go
pkg/vm/engine/tpe/engine/relation_test.go
pkg/vm/engine/tpe/engine/types.go
pkg/vm/engine/tpe/tuplecodec/computationhandler.go
pkg/vm/engine/tpe/tuplecodec/cubekv.go
pkg/vm/engine/tpe/tuplecodec/cubekv_test.go
pkg/vm/engine/tpe/tuplecodec/kv_types.go
pkg/vm/engine/types.go

issue #1060 
issue #995 
Not Available
Not Available
Not Available

tpe: update reader

---

go.mod
go.sum
pkg/container/types/types.go
pkg/container/types/types_test.go
pkg/container/vector/types.go

- [x ] Test and CI
issue #
Not Available
Not Available
Not Available

Move to go 1.18, adding a toy benchmark of generics..

---

pkg/sql/compile/compile.go
pkg/sql/compile/exec.go
pkg/sql/compile/print.go
pkg/sql/compile/transfer.go
pkg/sql/compile/types.go
pkg/sql/compile/view.go
pkg/sql/viewexec/times/times.go
pkg/sql/viewexec/times/times_test.go
pkg/sql/viewexec/times/types.go

issue #2237 
Not Available
Not Available
Not Available

Add comments and test cases for times operator

---

pkg/sql/plan/expr.go
pkg/vm/engine/tpe/engine/toolKitHandler_test.go

issue #2255
Not Available
Not Available
Not Available

support load data with scientific notation

---

pkg/sql/plan2/build.go
pkg/sql/plan2/build_expr.go
pkg/sql/plan2/build_from.go
pkg/sql/plan2/build_select.go
pkg/sql/plan2/build_test.go
pkg/sql/plan2/build_util.go
pkg/sql/plan2/mock.go
pkg/sql/plan2/types.go

add join and alias support in plan2
test case in build_test.go
issue #
Not Available
Not Available
Not Available

add join and alias support in plan2

---

docs/en/MatrixOne/Develop/design-a-database.md
docs/en/MatrixOne/Develop/develop_python_application.md

issue #
Not Available
Not Available
Add a tutorial of developing a simple python stock analysis application

Add python application tutorial

---

pkg/frontend/load.go

issue #2181 
Not Available
Not Available
Not Available

support the load stream with float value in NOT-FLOAT column

---

pkg/sql/compile/scope.go
pkg/vm/engine/aoe/engine/relation.go
pkg/vm/engine/aoe/engine/sparse_filter.go
pkg/vm/engine/aoe/engine/store.go
pkg/vm/engine/aoe/engine/types.go

issue #
Not Available
Not Available
Not Available

Enable sparse

---

pkg/vm/engine/tpe/engine/toolKitHandler_test.go

issue #
Not Available
Not Available
Not Available

fix test code bug

---

.github/workflows/dis_test.yml

issue #
Not Available
Not Available
Not Available

Add console log to artifact

---

docs/en/MatrixOne/Develop/develop_python_application.md

issue #
Not Available
Not Available
Update tutorial for the new code.

Update python app demo tutorial

---

.github/workflows/build_matrixone.yml
.github/workflows/robot.yml
Makefile
optools/run_ut.sh

issue #
Not Available
Not Available
Not Available

1. Add notify robot.yml

---

pkg/sql/compile/scope.go

issue #2285 
Not Available
Not Available
Not Available

Fix the bug of zonemap

---

pkg/container/types/decimal.go

issue #
Not Available
Not Available
Not Available

refine_decimal_doc

---

docs/cn/MatrixOne/Reference/Builtin-Functions/String/substring.md
docs/en/MatrixOne/Reference/Builtin-Functions/String/substring.md

issue #
Not Available
Not Available
Not Available

Add Substring function docs

---

docs/cn/MatrixOne/Reference/Builtin-Functions/String/substring.md
docs/cn/MatrixOne/Reference/SQL-Reference/Aggregate-Functions/var.md
docs/en/MatrixOne/Reference/Builtin-Functions/String/substring.md
docs/en/MatrixOne/Reference/SQL-Reference/Aggregate-Functions/var.md
docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/inner-join.md

issue #
Not Available
Not Available
Not Available

Fix some typo issues 

---

pkg/frontend/epochgc.go
pkg/frontend/load.go
pkg/frontend/load_test.go
pkg/frontend/util.go

issue #2134 
Not Available
Not Available
Not Available

fix go race in frontend

---

docs/cn/MatrixOne/Reference/Builtin-Functions/String/substring.md
docs/cn/MatrixOne/Reference/SQL-Reference/Aggregate-Functions/var.md
docs/cn/MatrixOne/Reference/SQL-Reference/data-types.md
docs/en/MatrixOne/Reference/Builtin-Functions/String/substring.md
docs/en/MatrixOne/Reference/SQL-Reference/Aggregate-Functions/var.md
docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/inner-join.md
docs/en/MatrixOne/Reference/SQL-Reference/data-types.md

issue #
Not Available
Not Available
Not Available

Add decimal datatype docs

---

pkg/vm/engine/aoe/engine/relation.go
pkg/vm/engine/aoe/engine/store.go
pkg/vm/engine/aoe/engine/types.go

issue #2306 
Not Available
Not Available
Not Available

Fix filter date type bug

---

.github/workflows/build_matrixone.yml
pkg/vm/engine/aoe/engine/relation.go

issue #2309 
Not Available
Not Available
Not Available

Fix the bug of Instance crashed when input an incorrect date value

---

pkg/sql/plan/constant.go
pkg/sql/plan/prune.go
pkg/sql/unittest/operator_test.go

issue #2309
Not Available
Not Available
Not Available

add logic to convert const string to be date or datetime extend at prune.go

---

pkg/vm/engine/aoe/mergesort/varchar/func.go

issue #2214 
Not Available
Not Available
Not Available

Fix the bug of dealing with Null values in mergesort of varchar

---

pkg/vm/engine/aoe/storage/layout/index/blkzonemap.go

issue #2334 
Not Available
Not Available
Not Available

(aoe): small fix for zonemap unmarshal

---

cmd/generate-config/system_vars_def.toml

issue #
Not Available
Not Available
Not Available

disable aoe split in default configuration

---

pkg/sql/compile/operator.go

issue #2313
Not Available
Not Available
Not Available

Fix the bug of result of group by from subquery

---

pkg/builtin/unary/month.go
pkg/builtin/unary/weekday.go

issue #2335
Not Available
Not Available
Not Available

fix issue#2335

---

pkg/sql/plan/expr.go
pkg/sql/unittest/dml_test.go

issue #2300
Not Available
Not Available
Not Available

fix issue#2300

---

pkg/sql/viewexec/join/join.go

issue #2333
Not Available
Not Available
Not Available

Fix the bug of inner join

---

docs/rfcs/20220503_tae_design.md

issue #2360 
Not Available
Not Available
Not Available

(tae/doc): add tae design rfc

---

pkg/sql/colexec/mergeorder/mergeorder.go
pkg/sql/colexec/mergetop/mergetop.go

issue #2322
Not Available
Not Available
Not Available

Fix the bug of mergeorder

---

pkg/sql/colexec/extend/overload/cast.template

issue #2366 
Not Available
Not Available
Not Available

fix issue#2366

---

docs/cn/MatrixOne/Reference/Builtin-Functions/String/lengthUTF8.md
docs/en/MatrixOne/Reference/Builtin-Functions/String/lengthUTF8.md

issue #
Not Available
Not Available
Not Available

Add lengthUTF8 function doc

---

docs/cn/MatrixOne/Reference/Builtin-Functions/String/lengthUTF8.md
docs/cn/MatrixOne/Release-Notes/v0.4.0.md
docs/en/MatrixOne/Reference/Builtin-Functions/String/lengthUTF8.md
docs/en/MatrixOne/Release-Notes/v0.4.0.md

issue #
Not Available
Not Available
Not Available

Add 0.4.0 release note doc

---

docs/cn/MatrixOne/Get-Started/install-standalone-matrixone.md
docs/en/MatrixOne/Get-Started/install-standalone-matrixone.md

issue #
Not Available
Not Available
Not Available

Add mac binary package installation doc

---

docs/cn/MatrixOne/Get-Started/install-standalone-matrixone.md
docs/en/MatrixOne/Get-Started/install-standalone-matrixone.md

issue #
Not Available
Not Available
Not Available

ARM support is not sufficient, remove the description

---

pkg/container/types/decimal.go

issue #2297
Not Available
Not Available
Not Available

fix issue#2297

---

go.mod
pkg/rpcserver/message/message.pb.go

issue #
Remove dependency on github.com/golang/protobuf, indirect dependency is a bit tricky as etcd and other modules still depend on that. 
Not Available
Not Available

Removed dependency on github.com/golang/protobuf/proto

---

pkg/vm/driver/test/storage_test.go

issue #2422
Not Available
Not Available
Not Available

fix wrong etcd/raft import path in test

---

.github/workflows/build_matrixone.yml
Makefile

issue #
Not Available
Not Available
Not Available

Enable fmt check

---

.github/workflows/build_matrixone.yml

issue #
Not Available
Not Available
Not Available

change pr trigger type

---

pkg/sql/parsers/dialect/mysql/mysql_sql_test.go

fix #2435
Cause of problem:
Explain syntax requirements change, and the previous unit test cannot pass
Solution:
Modify the test case according to the syntax rules in explain's requirements
Not Available
Not Available
Not Available

Solve the explain unit test bug

---

pkg/vectorize/exp/exp.go
pkg/vectorize/exp/exp_test.go

issue #2125
Not Available
Not Available
Not Available

Improve compatibility for unit tests within `pkg/vectorize/exp`.

---

pkg/container/types/date.go
pkg/container/types/datetime.go

issue #2437 #2438
Not Available
Not Available
Not Available

fix issue#2438 issue#2437

---

pkg/vm/driver/aoe/storage.go

issue #2447
Not Available
Not Available
Not Available

Make unit test TestAOEEngine through;

---

pkg/sql/compile/scope.go
pkg/vm/mmu/guest/mmu.go

issue #2436 
Not Available
Not Available
Not Available

Fix the race of MergeRun and mmu

---

pkg/container/types/temestamp_test.go
pkg/container/types/timestamp.go

issue #2450 
Not Available
Not Available
Not Available

fix issue#2450

---

pkg/sql/unittest/types.go

issue #2453 
Not Available
Not Available
Not Available

fix a unit-test-tool function bug which may cause panic sometimes

---

.github/workflows/build_matrixone.yml
.github/workflows/robot.yml
optools/run_ut.sh

issue #
Not Available
Not Available
Not Available

add nightly code analysis notify

---

pkg/sql/colexec2/limit/limit.go
pkg/sql/colexec2/limit/limit_test.go
pkg/sql/colexec2/limit/types.go
pkg/sql/colexec2/mergelimit/limit.go
pkg/sql/colexec2/mergelimit/limit_test.go
pkg/sql/colexec2/mergelimit/types.go
pkg/sql/colexec2/mergeoffset/offset.go
pkg/sql/colexec2/mergeoffset/offset_test.go
pkg/sql/colexec2/mergeoffset/types.go
pkg/sql/colexec2/offset/offset.go
pkg/sql/colexec2/offset/offset_test.go
pkg/sql/colexec2/offset/types.go

issue #2372 
Not Available
Not Available
Not Available

Add limit and offset operator

---

.github/workflows/robot.yml
optools/run_ut.sh

issue #
Not Available
Not Available
Not Available

Add daily code analysis notify

---

.github/workflows/build_matrixone.yml
.github/workflows/robot.yml

issue #
Not Available
Not Available
Not Available

extend unittest timeout temporally

---

pkg/sql/plan2/build_expr.go

issue #2372 
as define in function.go.  cast function only have one argument.
so change the buildCast code。
Not Available
Not Available

fix build cast function bug

---

pkg/vm/engine/tae/catalog/segment.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/db/gc_test.go
pkg/vm/engine/tae/db/scannerop.go
pkg/vm/engine/tae/model/colview.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/tables/jobs/mergeblocks.go
pkg/vm/engine/tae/tables/node.go
pkg/vm/engine/tae/tables/updates/updateview.go
pkg/vm/engine/tae/tasks/worker/worker.go

issue #2474 #2467 
Not Available
Not Available
Not Available

temp turn off gc check for tae ut 

---

optools/run_ut.sh

issue #
Not Available
Not Available
Not Available

remove ut coverage check in ut

---

pkg/vm/engine/tae/catalog/block.go
pkg/vm/engine/tae/catalog/segment.go
pkg/vm/engine/tae/common/id.go
pkg/vm/engine/tae/db/checkpoint/units.go
pkg/vm/engine/tae/db/dispatcher.go
pkg/vm/engine/tae/db/gcop.go
pkg/vm/engine/tae/db/scannerop.go

issue #2474 
1. Fix gc bug
2. Add more debug info
Not Available
Not Available

(tae): fix gc bug and add more debug info

---

pkg/vm/engine/tae/catalog/block.go
pkg/vm/engine/tae/catalog/segment.go
pkg/vm/engine/tae/common/id.go
pkg/vm/engine/tae/db/checkpoint/units.go
pkg/vm/engine/tae/db/dispatcher.go
pkg/vm/engine/tae/db/gcop.go
pkg/vm/engine/tae/db/scannerop.go

issue #2474
Not Available
Not Available
Not Available

fix gc bug and add more debug info

---

pkg/frontend/mysql_cmd_executor.go
pkg/sql/parsers/tree/precedence.go
pkg/sql/protocol/protocol.go
pkg/vm/engine/tae/catalog/base.go
pkg/vm/engine/tae/common/interval.go
pkg/vm/engine/tae/dataio/mockio/block.go
pkg/vm/engine/tae/dataio/mockio/colblk.go
pkg/vm/engine/tae/dataio/mockio/segment.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/db/gcop.go
pkg/vm/engine/tae/db/txn_test.go
pkg/vm/engine/tae/tables/node.go
pkg/vm/engine/tae/txn/txnbase/errors.go
pkg/vm/engine/tpe/orderedcodec/types.go
pkg/vm/engine/tpe/tuplecodec/cubekv.go
pkg/vm/engine/tpe/tuplecodec/serialize.go

issue #2133
Not Available
Not Available
Not Available

Static check: commonly misspelled English words;

---

pkg/sql/colexec2/connector/connector.go
pkg/sql/colexec2/connector/connector_test.go
pkg/sql/colexec2/connector/types.go
pkg/sql/colexec2/output/output.go
pkg/sql/colexec2/output/output_test.go
pkg/sql/colexec2/output/types.go

issue #2372
Not Available
Not Available
Not Available

Add connector and output operator

---

pkg/vm/engine/memEngine/relation.go

issue #2133
Not Available
Not Available
Not Available

Static check: checks for pointers to enclosing loop variables;

---

.gitignore
pkg/builtin/types.go
pkg/builtin/unary/bin.go
pkg/vectorize/bin/bin.go
pkg/vectorize/bin/bin_test.go

issue #2110
add built-in function bin()
Not Available
Not Available

[MatrixCamp] Add built-in function bin()

---

pkg/builtin/types.go
pkg/builtin/unary/oct.go
pkg/vectorize/oct/oct.go
pkg/vectorize/oct/oct_test.go

Signed-off-by: lawrshen <191220090@smail.nju.edu.cn>
issue #2115 
Add a feature of oct() built-in function.
Not Available
Not Available

Add built-in function oct (#2115)

---

pkg/vm/engine/tae/tables/jobs/mergeblocks.go
pkg/vm/engine/tpe/descriptor/types.go
pkg/vm/engine/tpe/engine/database.go
pkg/vm/engine/tpe/tuplecodec/cubekv.go
pkg/vm/engine/tpe/tuplecodec/decoder.go
pkg/vm/engine/tpe/tuplecodec/rowcolumnconverter_test.go
pkg/vm/engine/tpe/tuplecodec/util.go

preallocated;
issue #2133
Not Available
Not Available
Not Available

Static check: slice declarations that could be preallocated

---

pkg/container/batch2/batch.go
pkg/container/batch2/types.go
pkg/container/types/types.go
pkg/sql/colexec2/aggregate/aggregate.go
pkg/sql/colexec2/aggregate/types.go
pkg/sql/colexec2/group/group.go
pkg/sql/colexec2/group/group_test.go
pkg/sql/colexec2/group/types.go

issue #2372
Not Available
Not Available
Not Available

Add group operator

---

.github/workflows/build_matrixone.yml
Makefile

issue #
Not Available
Not Available
Not Available

enable sca check

---

pkg/sql/colexec2/mergegroup/group.go
pkg/sql/colexec2/mergegroup/group_test.go
pkg/sql/colexec2/mergegroup/types.go

issue #2372
Not Available
Not Available
Not Available

Add mergegroup operator

---

pkg/vm/engine2/engine.go
pkg/vm/engine2/types.go

issue #
Not Available
Not Available
Not Available

Adding transaction snapshot to the engine interface

---

pkg/frontend/init_db.go
pkg/frontend/init_db_test.go
pkg/frontend/util.go

issue #2421 
Not Available
Not Available
Not Available

add initial data for catalog

---

pkg/sql/colexec2/connector/connector_test.go
pkg/sql/colexec2/group/group.go
pkg/sql/colexec2/group/group_test.go
pkg/sql/colexec2/join/join.go
pkg/sql/colexec2/join/join_test.go
pkg/sql/colexec2/join/types.go
pkg/sql/colexec2/limit/limit_test.go
pkg/sql/colexec2/mergegroup/group.go
pkg/sql/colexec2/mergelimit/limit_test.go
pkg/sql/colexec2/mergeoffset/offset.go
pkg/sql/colexec2/mergeorder/order_test.go
pkg/sql/colexec2/mergetop/top_test.go
pkg/sql/colexec2/offset/offset_test.go
pkg/sql/colexec2/order/order_test.go
pkg/sql/colexec2/output/output_test.go
pkg/sql/colexec2/product/product.go
pkg/sql/colexec2/product/product_test.go
pkg/sql/colexec2/product/types.go
pkg/sql/colexec2/top/top_test.go
pkg/vm/mmu/guest/mmu.go

issue #2372
Not Available
Not Available
Not Available

Add join and product operator

---

cmd/db-server/main.go
pkg/container/batch/batch.go
pkg/frontend/mysql_cmd_executor.go
pkg/rpcserver/codec.go
pkg/rpcserver/server.go
pkg/sql/colexec/connector/connector.go
pkg/sql/colexec/order/order.go
pkg/sql/colexec2/order/order.go

issue #2133
Fix some cases marked via linter [errcheck](https://github.com/kisielk/errcheck).
```bash
golangci-lint run --disable-all --max-same-issues 10000 --max-issues-per-linter 10000 -E errcheck
```
Not Available
Not Available

Static check: fix cases for `errcheck`;

---

Makefile
pkg/vm/engine/tae/dataio/segmentio/block.go
pkg/vm/engine/tae/dataio/segmentio/block_test.go
pkg/vm/engine/tae/dataio/segmentio/colblk.go
pkg/vm/engine/tae/dataio/segmentio/data.go
pkg/vm/engine/tae/dataio/segmentio/segment.go
pkg/vm/engine/tae/dataio/segmentio/segment_test.go
pkg/vm/engine/tae/dataio/segmentio/stat.go
pkg/vm/engine/tae/db/open.go
pkg/vm/engine/tae/db/tables_test.go
pkg/vm/engine/tae/layout/segment/allocator.go
pkg/vm/engine/tae/layout/segment/bitmap_allocator.go
pkg/vm/engine/tae/layout/segment/extent.go
pkg/vm/engine/tae/layout/segment/file.go
pkg/vm/engine/tae/layout/segment/inode.go
pkg/vm/engine/tae/layout/segment/log.go
pkg/vm/engine/tae/layout/segment/segment.go
pkg/vm/engine/tae/layout/segment/segment_test.go
pkg/vm/engine/tae/tables/segment.go
pkg/vm/engine/tae/tables/tables.go
pkg/vm/engine/tae/txn/txnimpl/txn_test.go

issue #
Not Available
Not Available
Not Available

Tae layout

---

pkg/container/batch2/batch.go
pkg/container/batch2/batch_test.go
pkg/container/batch2/types.go
pkg/container/ring/approxcd/approx.go
pkg/container/ring/approxcd/types.go
pkg/container/types/bytes_test.go
pkg/container/vector/vector_test.go
pkg/rpcserver/server.go
pkg/rpcserver/server_test.go
pkg/sql/colexec2/connector/connector_test.go
pkg/sql/colexec2/group/group_test.go
pkg/sql/colexec2/join/join_test.go
pkg/sql/colexec2/limit/limit_test.go
pkg/sql/colexec2/mergegroup/group_test.go
pkg/sql/colexec2/mergelimit/limit_test.go
pkg/sql/colexec2/mergeoffset/offset_test.go
pkg/sql/colexec2/mergeorder/order_test.go
pkg/sql/colexec2/mergetop/top_test.go
pkg/sql/colexec2/offset/offset_test.go
pkg/sql/colexec2/order/order_test.go
pkg/sql/colexec2/output/output_test.go
pkg/sql/colexec2/product/product_test.go
pkg/sql/colexec2/top/top_test.go
pkg/sql/compile/scope.go
pkg/sql/protocol/protocol_test.go
pkg/vm/pipeline/pipeline.go

issue #2526 
issue #2525
Not Available
Not Available
Not Available

Add batch's reference count and fix errcheck cases

---

pkg/vectorize/bin/bin_test.go

issue #2497 
Not Available
Not Available
Not Available

fix issue#2497

---

pkg/sql/parsers/goyacc/goyacc.go

issue #2524 
Not Available
Not Available
Not Available

fix cases marked by linter errcheck for goyacc

---

pkg/vm/engine/tae/catalog/catalog.go
pkg/vm/engine/tae/db/replay.go
pkg/vm/engine/tae/iface/data/block.go
pkg/vm/engine/tae/tables/appender.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/tables/updates/append.go
pkg/vm/engine/tae/tables/updates/chain_test.go
pkg/vm/engine/tae/tables/updates/cmd.go
pkg/vm/engine/tae/tables/updates/colupdate.go
pkg/vm/engine/tae/tables/updates/command_test.go
pkg/vm/engine/tae/tables/updates/delete.go
pkg/vm/engine/tae/txn/txnimpl/appendcmd.go
pkg/vm/engine/tae/txn/txnimpl/command_test.go
pkg/vm/engine/tae/txn/txnimpl/node.go
pkg/vm/engine/tae/txn/txnimpl/table.go
pkg/vm/engine/tae/wal/driver.go
pkg/vm/engine/tae/wal/types.go

issue #2495
Not Available
Not Available
Not Available

update for TAE catalog replay - phase 2

---

pkg/vm/engine/tae/catalog/catalog.go
pkg/vm/engine/tae/catalog/catalog_test.go
pkg/vm/engine/tae/catalog/checkpoint.go
pkg/vm/engine/tae/container/types.go
pkg/vm/engine/tae/db/db.go
pkg/vm/engine/tae/wal/types.go

issue #2495 
Not Available
Not Available
Not Available

update for catalog checkpoint 

---

Makefile
cmd/db-server/main.go
cmd/generate-config/system_vars_def.toml
pkg/frontend/init_db.go
pkg/frontend/init_db_test.go

issue #
Not Available
Not Available
Not Available

change init config

---

pkg/vm/engine/tae/dataio/segmentio/block.go
pkg/vm/engine/tae/dataio/segmentio/block_test.go
pkg/vm/engine/tae/dataio/segmentio/colblk.go
pkg/vm/engine/tae/dataio/segmentio/data.go
pkg/vm/engine/tae/dataio/segmentio/segment.go
pkg/vm/engine/tae/dataio/segmentio/stat.go
pkg/vm/engine/tae/layout/segment/extent.go
pkg/vm/engine/tae/layout/segment/file.go
pkg/vm/engine/tae/layout/segment/inode.go
pkg/vm/engine/tae/layout/segment/log.go
pkg/vm/engine/tae/layout/segment/segment.go
pkg/vm/engine/tae/layout/segment/segment_test.go

issue #
Not Available
Not Available
Not Available

Add compress

---

pkg/sql/compile2/compile.go
pkg/sql/compile2/exec.go
pkg/sql/compile2/types.go
pkg/vm/process2/types.go

issue #2372
Not Available
Not Available
Not Available

Add compile2

---

pkg/container/batch2/batch.go
pkg/container/vector/vector.go
pkg/sql/colexec/mergeorder/mergeorder.go
pkg/sql/colexec2/complement/complement.go
pkg/sql/colexec2/complement/complement_test.go
pkg/sql/colexec2/complement/types.go
pkg/sql/colexec2/group/group_test.go
pkg/sql/colexec2/left/join.go
pkg/sql/colexec2/left/join_test.go
pkg/sql/colexec2/left/types.go
pkg/sql/colexec2/merge/merge.go
pkg/sql/colexec2/merge/merge_test.go
pkg/sql/colexec2/merge/types.go
pkg/sql/colexec2/mergegroup/group_test.go
pkg/sql/colexec2/mergelimit/limit_test.go
pkg/sql/colexec2/mergeoffset/offset_test.go
pkg/sql/colexec2/mergeorder/order_test.go
pkg/sql/colexec2/mergetop/top_test.go
pkg/sql/colexec2/offset/offset_test.go
pkg/sql/colexec2/order/order_test.go
pkg/sql/colexec2/output/output_test.go
pkg/sql/colexec2/product/product_test.go
pkg/sql/colexec2/top/top_test.go

issue #2372
Not Available
Not Available
The use of `inthashtable` is not used here for the time being. If `inthashtable` needs to be used, then it will involve the need to align the fields of both tables to the same width so that they are correct.

Add merge, left and complement operator

---

pkg/vm/engine/tae/db/db.go
pkg/vm/engine/tae/db/scannerop.go
pkg/vm/engine/tae/iface/txnif/types.go
pkg/vm/engine/tae/moengine/engine.go
pkg/vm/engine/tae/moengine/engine_test.go
pkg/vm/engine/tae/moengine/types.go
pkg/vm/engine/tae/samples/sample3/main.go
pkg/vm/engine/tae/samples/sample4/main.go
pkg/vm/engine/tae/txn/txnbase/txnctx.go
pkg/vm/engine/tae/txn/txnbase/txnmgr.go

issue #2557 
Not Available
Not Available
Not Available

(tae): update for new engine api

---

pkg/builtin/binary/findinset.go
pkg/builtin/types.go
pkg/vectorize/findinset/findinset.go
pkg/vectorize/findinset/findinset_test.go

issue #2358 
Add add built-in string function find_in_set()
Not Available
Not Available

[MatrixCamp] Add add built-in string function find_in_set()

---

pkg/sql/compile2/exec.go
pkg/sql/compile2/scope.go
pkg/sql/compile2/types.go
pkg/vm/process2/types.go

issue #2370
Not Available
Not Available
Not Available

create database for plan2

---

pkg/vm/engine/tae/layout/segment/bitmap_allocator.go

issue #2561 
Not Available
Not Available
Not Available

Fix the bug that the last pos is not updated and the offset is abnormal

---

pkg/vm/engine/tae/catalog/database.go
pkg/vm/engine/tae/catalog/mock.go
pkg/vm/engine/tae/catalog/model.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/txn/txnimpl/store.go
pkg/vm/engine/tae/txn/txnimpl/sysblock.go
pkg/vm/engine/tae/txn/txnimpl/sysdb.go

issue #2531 
Not Available
Not Available
Not Available

(tae): update for system db -- phase 2

---

pkg/container/vector/types.go
pkg/container/vector/vector.go
pkg/sql/colexec2/expr_eval.go
pkg/sql/plan2/function/builtins_test.go
pkg/sql/plan2/function/function.go
pkg/sql/plan2/function/operators.go

issue #2563 
Not Available
Not Available
Not Available

Add eval method for plan2.Expr

---

pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
pkg/sql/parsers/scanner/scanner.go

issue #2569
Not Available
Not Available
Not Available

string should not be covert to lower case when parse string

---

pkg/vm/engine/tae/layout/segment/bitmap_allocator.go
pkg/vm/engine/tae/layout/segment/segment_test.go

issue #
Not Available
Not Available
Not Available

Add UT & Fix level0 offset

---

pkg/container/batch2/batch.go
pkg/container/batch2/batch_test.go
pkg/sql/colexec2/mergeorder/order.go
pkg/sql/colexec2/mergetop/top.go
pkg/sql/colexec2/mergetop/types.go
pkg/sql/colexec2/projection/projection.go
pkg/sql/colexec2/projection/projection_test.go
pkg/sql/colexec2/projection/types.go
pkg/sql/colexec2/top/top.go
pkg/sql/colexec2/top/types.go

issue #2372
Not Available
Not Available
Not Available

Add projection operator and remove batch's attributes reorder

---

cmd/db-server/main.go
pkg/frontend/init_db.go
pkg/frontend/load_test.go
pkg/frontend/mysql_cmd_executor.go
pkg/frontend/mysql_cmd_executor_test.go
pkg/frontend/routine.go
pkg/frontend/session.go
pkg/sql/compile/exec.go
pkg/sql/compile/types.go
pkg/sql/plan/build.go
pkg/sql/plan/types.go

* adapt frontend for tae txn
* update
issue #2421 
Not Available
Not Available
Not Available

adapt frontend for tae txn

---

pkg/sql/plan2/build_insert.go
pkg/sql/plan2/build_test.go

issue #2372 
check column length match value length in insert statement
Not Available
Not Available

check column length match value length in insert statement

---

pkg/vm/engine/tae/catalog/model.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/txn/txnimpl/sysblock.go

issue #2531 
Not Available
Not Available
Not Available

(tae): update for system db -- phase 3

---

pkg/sql/colexec2/restrict/restrict.go
pkg/sql/colexec2/restrict/types.go

issue #2372
Not Available
Not Available
Not Available

Add restrict operator

---

pkg/sql/plan2/function/function.go
pkg/sql/plan2/function/function_test.go
pkg/sql/plan2/function/init.go

issue #2329 
Not Available
Not Available
Not Available

Add type implicit convert logic for functions' arguments

---

pkg/sql/plan2/build_ddl.go
pkg/sql/plan2/build_from.go
pkg/sql/plan2/build_insert.go
pkg/sql/plan2/build_show.go
pkg/sql/plan2/build_util.go
pkg/sql/plan2/mock.go
pkg/sql/plan2/types.go

issue #2372 
Not Available
Not Available
Not Available

change CompilerContext interface

---

pkg/vm/engine/tae/catalog/block.go
pkg/vm/engine/tae/catalog/catalog.go
pkg/vm/engine/tae/catalog/database.go
pkg/vm/engine/tae/catalog/segment.go
pkg/vm/engine/tae/catalog/table.go
pkg/vm/engine/tae/container/vector/wrapper.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/iface/handle/block.go
pkg/vm/engine/tae/iface/handle/segment.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/txn/txnbase/handle.go
pkg/vm/engine/tae/txn/txnimpl/block.go
pkg/vm/engine/tae/txn/txnimpl/database.go
pkg/vm/engine/tae/txn/txnimpl/localseg.go
pkg/vm/engine/tae/txn/txnimpl/node.go
pkg/vm/engine/tae/txn/txnimpl/relation.go
pkg/vm/engine/tae/txn/txnimpl/segment.go
pkg/vm/engine/tae/txn/txnimpl/store.go
pkg/vm/engine/tae/txn/txnimpl/sysblock.go
pkg/vm/engine/tae/txn/txnimpl/sysdb.go
pkg/vm/engine/tae/txn/txnimpl/table.go
pkg/vm/engine/tae/txn/txnimpl/txn_test.go
pkg/vm/engine/tae/txn/txnimpl/txndb.go

issue #2586 
Not Available
Not Available
Not Available

fix scan txn uncommitted data and txnimpl refactor

---

pkg/vm/engine/tae/catalog/model.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/txn/txnimpl/sysblock.go

issue #2531 
Not Available
Not Available
Not Available

(tae): fix system db bug

---

pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/txn/txnimpl/index.go

issue #
Not Available
Not Available
Not Available

(tae): fix pre commit dedup bug

---

pkg/vm/engine/tae/container/compute/mock.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/db/replay_test.go
pkg/vm/engine/tae/moengine/block.go
pkg/vm/engine/tae/txn/txnimpl/localseg.go
pkg/vm/engine/tae/txn/txnimpl/txn_test.go

issue #
Not Available
Not Available
Not Available

(tae): fix bugs and apply deletes for mo engine

---

pkg/vm/engine/tae/layout/segment/file.go
pkg/vm/engine/tae/layout/segment/inode.go
pkg/vm/engine/tae/layout/segment/log.go
pkg/vm/engine/tae/layout/segment/segment.go
pkg/vm/engine/tae/layout/segment/segment_test.go

issue #
Not Available
Not Available
Not Available

Refine tae layout&Add replay

---

Makefile
pkg/frontend/mysql_cmd_executor.go
pkg/sql/plan2/build_ddl.go
pkg/sql/plan2/build_util.go
pkg/sql/plan2/function/aggregate.go
pkg/sql/plan2/function/operators.go
pkg/vm/engine/tae/catalog/base.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/db/replay.go
pkg/vm/engine/tae/txn/txnbase/txnmgr.go

2. fix few static analysis errors
issue #
Not Available
Not Available
Not Available

1. add staticcheck

---

docs/cn/MatrixOne/Get-Started/Tutorial/SSB-test-with-matrixone.md
docs/cn/MatrixOne/Get-Started/connect-to-matrixone-server.md
docs/en/MatrixOne/Contribution-Guide/How-to-Contribute/report-an-issue.md

issue #
Not Available
Not Available
Not Available

Docs optimization

---

docs/en/MatrixOne/Overview/whats-new.md

issue #
Not Available
Not Available
Not Available

Update what's new page for 0.4.0 version

---

pkg/pb/plan/plan.pb.go
pkg/sql/compile2/compile.go
pkg/sql/compile2/scope.go
pkg/sql/compile2/types.go
pkg/sql/plan2/build_util.go

issue #2370
Not Available
Not Available
Not Available

Support DDL's execution for TPCH

---

pkg/vm/engine/tae/layout/segment/allocator.go
pkg/vm/engine/tae/layout/segment/bitmap_allocator.go
pkg/vm/engine/tae/layout/segment/log.go
pkg/vm/engine/tae/layout/segment/segment_test.go

issue #
Not Available
Not Available
Not Available

Add allocator Replay

---

pkg/sql/compile2/compile.go
pkg/sql/compile2/operator.go
pkg/sql/compile2/scope.go
pkg/sql/compile2/types.go
pkg/vm/overload/overload.go
pkg/vm/overload/run.go
pkg/vm/pipeline2/pipeline.go
pkg/vm/pipeline2/types.go

issue #2372
Not Available
Not Available
Not Available

Add compile2's compile logic

---

pkg/vm/engine/tae/catalog/schema.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/db/replay_test.go
pkg/vm/engine/tae/iface/data/errors.go
pkg/vm/engine/tae/iface/handle/relation.go
pkg/vm/engine/tae/iface/txnif/types.go
pkg/vm/engine/tae/tables/appender.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/tables/node.go
pkg/vm/engine/tae/tables/updates/append.go
pkg/vm/engine/tae/tables/updates/cmd.go
pkg/vm/engine/tae/tables/updates/colupdate.go
pkg/vm/engine/tae/tables/updates/delchain.go
pkg/vm/engine/tae/tables/updates/delete.go
pkg/vm/engine/tae/tables/updates/mvcc.go
pkg/vm/engine/tae/tables/updates/updatechain.go
pkg/vm/engine/tae/txn/txnbase/handle.go
pkg/vm/engine/tae/txn/txnbase/store.go
pkg/vm/engine/tae/txn/txnbase/txn.go
pkg/vm/engine/tae/txn/txnbase/txnmgr.go
pkg/vm/engine/tae/txn/txnimpl/block.go
pkg/vm/engine/tae/txn/txnimpl/localseg.go
pkg/vm/engine/tae/txn/txnimpl/relation.go
pkg/vm/engine/tae/txn/txnimpl/store.go
pkg/vm/engine/tae/txn/txnimpl/table.go
pkg/vm/engine/tae/txn/txnimpl/txndb.go

issue #
Not Available
Not Available
Not Available

fix delete related bugs and txn code improvement

---

pkg/sql/plan2/build_expr.go
pkg/sql/plan2/build_from.go
pkg/sql/plan2/build_function.go
pkg/sql/plan2/build_select.go
pkg/sql/plan2/build_show.go
pkg/sql/plan2/build_subquery.go
pkg/sql/plan2/build_update.go
pkg/sql/plan2/build_util.go
pkg/sql/plan2/explain/explain_node.go

issue #2372
Not Available
Not Available
Not Available

Unify aggregate functions in HAVING clause

---

pkg/sql/plan2/build_show.go
pkg/sql/plan2/build_test.go
pkg/sql/plan2/mock.go

issue #2370 
1、add database name "mo_catalog" to rewrite sql.
2、add support "show create table db_name.tbl_name"
Not Available
Not Available

Change show rewrite

---

pkg/container/vector/types.go
pkg/container/vector/vector.go
pkg/sql/colexec2/expr_eval.go
pkg/sql/compile2/operator.go
pkg/sql/plan2/function/aggregate.go
pkg/sql/plan2/function/function.go
pkg/sql/plan2/function/function_id.go
pkg/sql/plan2/function/function_test.go

issue #2329 
Not Available
Not Available
Not Available

Adjust Vector and Function structure for execution of Expr_F

---

pkg/frontend/mysql_cmd_executor.go
pkg/frontend/mysql_cmd_executor_test.go
pkg/frontend/session.go
pkg/frontend/session_test.go
pkg/sql/plan2/build_function.go

issue #2421 
issue #2635 
Not Available
Not Available
Not Available

adapt frontend for tae/aoe

---

pkg/sql/colexec2/dispatch/dispatch.go
pkg/sql/colexec2/dispatch/dispatch_test.go
pkg/sql/colexec2/dispatch/types.go
pkg/sql/colexec2/limit/limit.go
pkg/sql/colexec2/offset/offset.go
pkg/sql/colexec2/order/order.go
pkg/sql/colexec2/projection/projection.go
pkg/sql/colexec2/restrict/restrict.go
pkg/sql/compile2/compile.go
pkg/sql/compile2/operator.go
pkg/sql/compile2/scope.go
pkg/sql/compile2/types.go
pkg/vm/overload/overload.go
pkg/vm/overload/run.go
pkg/vm/pipeline2/pipeline.go
pkg/vm/pipeline2/types.go

issue #2372
Not Available
Not Available
Not Available

Add dispatch operator

---

pkg/vm/engine/tae/dataio/mockio/segment.go
pkg/vm/engine/tae/dataio/segmentio/segment.go
pkg/vm/engine/tae/dataio/segmentio/segment_test.go
pkg/vm/engine/tae/iface/file/segment.go

issue #
Not Available
Not Available
Not Available

Remove replay ids

---

pkg/sql/colexec2/expr_eval.go
pkg/sql/colexec2/mergelimit/limit.go
pkg/sql/compile2/compile.go
pkg/sql/compile2/operator.go
pkg/vm/pipeline2/pipeline.go

issue #2372
Not Available
Not Available
Not Available

Fix some bug of compile and expr eval

---

cmd/generate-config/system_vars_def.toml
pkg/frontend/load.go
pkg/frontend/mysql_cmd_executor.go

issue #2421 
There is an independent transaction for a batch of data during loading data.
we just use LOAD in an autocommit transaction.
we can not use LOAD statement in Begin ... commit/rollback.
Not Available
Not Available

update load for tae

---

pkg/sql/plan2/build_expr.go
pkg/sql/plan2/build_select.go

issue #2372
Not Available
Not Available
Not Available

Add aggregate functions in SELECT/ORDER BY clause into agg node

---

pkg/sql/plan2/optimize.go
pkg/sql/plan2/rule/consant_fold.go
pkg/sql/plan2/types.go

issue #2372
Not Available
Not Available
Not Available

Add base optimizer

---

pkg/frontend/insert.go
pkg/frontend/mysql_cmd_executor.go

issue #2408 
Not Available
Not Available
Not Available

Surpport insert values

---

pkg/vm/engine/tae/container/compute/utils.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/iface/data/block.go
pkg/vm/engine/tae/iface/handle/block.go
pkg/vm/engine/tae/iface/txnif/types.go
pkg/vm/engine/tae/index/filter.go
pkg/vm/engine/tae/index/mtree.go
pkg/vm/engine/tae/index/tree.go
pkg/vm/engine/tae/index/tree_test.go
pkg/vm/engine/tae/index/types.go
pkg/vm/engine/tae/index/zonemap.go
pkg/vm/engine/tae/index/zonemap_test.go
pkg/vm/engine/tae/model/colview.go
pkg/vm/engine/tae/tables/appender.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/tables/indexwrapper/bfnode.go
pkg/vm/engine/tae/tables/indexwrapper/bfnode_test.go
pkg/vm/engine/tae/tables/indexwrapper/deletes.go
pkg/vm/engine/tae/tables/indexwrapper/immutindex.go
pkg/vm/engine/tae/tables/indexwrapper/mutindex.go
pkg/vm/engine/tae/tables/indexwrapper/types.go
pkg/vm/engine/tae/tables/indexwrapper/zmnode_test.go
pkg/vm/engine/tae/tables/indexwrapper/zonemapnode.go
pkg/vm/engine/tae/tables/node.go
pkg/vm/engine/tae/tables/updates/delchain.go
pkg/vm/engine/tae/tables/updates/delete.go
pkg/vm/engine/tae/tables/updates/mvcc.go
pkg/vm/engine/tae/txn/txnimpl/table.go

issue #
Not Available
Not Available
Not Available

update appendable block index to support multi versions

---

pkg/sql/plan2/tpch/ddl.sql

issue #2370 
Not Available
Not Available
Not Available

update tpch ddl sql

---

pkg/vm/engine/tae/container/compute/compute.go
pkg/vm/engine/tae/db/db_test.go

issue #2665 
Not Available
Not Available
Not Available

fix UpdateOffsets

---

pkg/frontend/mysql_cmd_executor.go
pkg/frontend/variables.go

* add show xxx for aoe & plan2
* add varibales
issue #2421 
issue #2386 
add show xxx for aoe & plan2 
adapt frontend for jdbc compatibility
Not Available
Not Available

adapt frontend for the show statement of plan2 on aoe and jdbc compatibility

---

pkg/sql/plan2/build_expr.go
pkg/sql/plan2/build_select.go
pkg/sql/plan2/build_test.go

issue #2372
Not Available
Not Available
Not Available

[Plan2] Handle aggregate without GROUP BY

---

pkg/sql/plan2/build_select.go

issue #2372
Not Available
Not Available
Not Available

[Plan2] Fix empty agg_list of implicit agg node

---

pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/tables/updates/delchain.go
pkg/vm/engine/tae/tables/updates/updateview.go
pkg/vm/engine/tae/txn/txnbase/txn.go

issue #2671 
Not Available
Not Available
Not Available

(tae): fix wait committing txn state bug

---

pkg/container/vector/vector.go
pkg/frontend/mysql_cmd_executor.go
pkg/sql/colexec2/expr_eval.go
pkg/sql/plan2/build_select.go
pkg/vm/process/process.go

issue #2329 #2372 
Not Available
Not Available
Not Available

Add some method for scalar vector

---

pkg/vm/engine/tae/catalog/block.go
pkg/vm/engine/tae/catalog/catalog.go
pkg/vm/engine/tae/catalog/replay.go
pkg/vm/engine/tae/catalog/segment.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/db/open.go
pkg/vm/engine/tae/db/replay.go
pkg/vm/engine/tae/db/replay_test.go
pkg/vm/engine/tae/iface/data/block.go
pkg/vm/engine/tae/iface/txnif/types.go
pkg/vm/engine/tae/logstore/store/syncbase.go
pkg/vm/engine/tae/logstore/store/vgroup.go
pkg/vm/engine/tae/tables/appender.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/tables/blocktasks.go
pkg/vm/engine/tae/tables/updates/append.go
pkg/vm/engine/tae/tables/updates/colupdate.go
pkg/vm/engine/tae/tables/updates/delchain.go
pkg/vm/engine/tae/tables/updates/delete.go
pkg/vm/engine/tae/tables/updates/mvcc.go
pkg/vm/engine/tae/tables/updates/updatechain.go
pkg/vm/engine/tae/txn/txnimpl/appendcmd.go
pkg/vm/engine/tae/txn/txnimpl/command_test.go
pkg/vm/engine/tae/txn/txnimpl/node.go
pkg/vm/engine/tae/txn/txnimpl/table.go
pkg/vm/engine/tae/wal/types.go

issue #2495
Not Available
Not Available
Not Available

update replay ut, fix bugs

---

pkg/frontend/mysql_cmd_executor.go
pkg/frontend/mysql_cmd_executor_test.go
pkg/frontend/session.go
pkg/frontend/variables.go

issue #2386
issue #2387 
Not Available
Not Available
Not Available

update variables for jdbc compatibility

---

pkg/sql/compile2/scope.go
pkg/sql/plan2/build_ddl.go
pkg/sql/plan2/build_test.go

issue #2649 
Not Available
Not Available
Not Available

drop database if exists test01; failed when using plan2 with aoe

---

pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/tables/indexwrapper/deletes.go
pkg/vm/engine/tae/tables/indexwrapper/immutindex.go
pkg/vm/engine/tae/tables/indexwrapper/mutindex.go
pkg/vm/engine/tae/tables/indexwrapper/types.go
pkg/vm/engine/tae/tables/updates/chain_test.go
pkg/vm/engine/tae/tables/updates/updateview.go
pkg/vm/engine/tae/txn/txnimpl/index.go
pkg/vm/engine/tae/txn/txnimpl/relation.go
pkg/vm/engine/tae/txn/txnimpl/table.go
pkg/vm/engine/tae/txn/txnimpl/txn_test.go
pkg/vm/engine/tae/txn/txnimpl/txndb.go

issue #2688 
SI violation scenario: (Insert row with same PK)
Not Available
Not Available

fix snapshot isolation violation

---

pkg/vm/engine/tae/logstore/store/vfile.go

issue #2687 
Not Available
Not Available
Not Available

fix logstore cache

---

pkg/vm/engine/tae/layout/segment/bitmap_allocator.go
pkg/vm/engine/tae/layout/segment/log.go
pkg/vm/engine/tae/layout/segment/segment_test.go

issue #
Not Available
Not Available
Not Available

Fix bug in bitmap allocator for large numbers of files

---

pkg/vm/engine/tae/catalog/table.go
pkg/vm/engine/tae/container/compute/compute.go
pkg/vm/engine/tae/db/db.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/iface/txnif/errors.go
pkg/vm/engine/tae/tables/appender.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/tables/updates/colupdate.go
pkg/vm/engine/tae/tables/updates/delchain.go
pkg/vm/engine/tae/tables/updates/delete.go
pkg/vm/engine/tae/tables/updates/mvcc.go
pkg/vm/engine/tae/tables/updates/updateview.go
pkg/vm/engine/tae/txn/txnbase/errors.go
pkg/vm/engine/tae/txn/txnimpl/index.go
pkg/vm/engine/tae/txn/txnimpl/relation.go
pkg/vm/engine/tae/txn/txnimpl/table.go

issue #2693 
Not Available
Not Available
Not Available

implement Rows() for TAE underlying table

---

pkg/vm/engine/tae/layout/segment/log.go
pkg/vm/engine/tae/layout/segment/segment_test.go

issue #
Not Available
Not Available
Not Available

Fix the bug that deleted files are still visible after replay

---

pkg/sql/plan2/build_from.go
pkg/sql/plan2/build_function.go
pkg/sql/plan2/build_select.go
pkg/sql/plan2/build_test.go

issue #2372 
yesterday, parser support date_add/date_sub function。 now we add support in plan2
Not Available
Not Available

support date-add/date-sub function

---

pkg/sql/colexec2/mergegroup/group.go
pkg/sql/colexec2/semi/join.go
pkg/sql/colexec2/semi/join_test.go
pkg/sql/colexec2/semi/types.go
pkg/sql/compile2/compile.go
pkg/sql/compile2/operator.go
pkg/sql/compile2/scope.go
pkg/vm/mheap/mheap.go
pkg/vm/overload/overload.go
pkg/vm/overload/types.go

issue #2372
Not Available
Not Available
Not Available

Add semi join operator

---

pkg/sql/plan2/explain/explain_test.go
pkg/sql/plan2/function/builtin/binary/power.go
pkg/sql/plan2/function/builtin/multi/floor.go
pkg/sql/plan2/function/builtin/unary/abs.go
pkg/sql/plan2/function/builtin/unary/acos.go
pkg/sql/plan2/function/buitins.go
pkg/sql/plan2/function/function_id.go
pkg/vm/process/process.go

issue #2565
According to plan2 requirements, the built-in functions are migrated. The following built-in functions are migrated this time,
they are unary function（abs，acos）, binary function(power), and multi function (floor)
Not Available
Not Available

Function to plan2

---

pkg/container/batch/batch.go
pkg/container/vector/vector.go
pkg/container/vector/vector_test.go
pkg/sql/colexec2/group/group.go
pkg/sql/colexec2/mergegroup/group.go
pkg/sql/colexec2/mergeoffset/offset.go
pkg/sql/compile2/compile.go
pkg/sql/compile2/operator.go
pkg/sql/testutil/make.go

issue #
Not Available
Not Available
Not Available

Fix the bug of offset and add order

---

pkg/frontend/insert.go
pkg/vm/engine/tae/moengine/engine_test.go
pkg/vm/engine/tae/moengine/reader.go
pkg/vm/engine/tae/moengine/relation.go
pkg/vm/engine/tae/moengine/types.go

issue #2681 #2706 
Not Available
Not Available
Not Available

Implement tae moengine Nodes

---

pkg/sql/colexec2/mergegroup/group.go
pkg/sql/colexec2/mergeorder/order.go
pkg/sql/colexec2/mergetop/top.go

issue #
Not Available
Not Available
Not Available

Fix the bug of mergeorder and mergetop

---

pkg/vm/engine/tae/moengine/reader.go
pkg/vm/engine/tae/moengine/types.go

issue #2718 
Not Available
Not Available
Not Available

Add Zs in batch

---

pkg/vm/engine/tae/catalog/catalog.go
pkg/vm/engine/tae/catalog/segment.go
pkg/vm/engine/tae/db/open.go
pkg/vm/engine/tae/db/replay_test.go
pkg/vm/engine/tae/iface/data/block.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/tables/updates/delchain.go
pkg/vm/engine/tae/tables/updates/mvcc.go

issue #
Not Available
Not Available
Not Available

replay table rows

---

pkg/sql/colexec2/expr_eval.go
pkg/sql/compile2/compile.go

issue #2372 
Not Available
Not Available
Not Available

add value-scan demo, fix an expression eval bug

---

pkg/sql/compile2/scope.go

issue #2715
Not Available
Not Available
Not Available

Fix insert bug (#2715)

---

pkg/sql/plan2/rule/consant_fold.go
pkg/sql/plan2/rule/predicate_pushdown.go

issue #2372
Not Available
Not Available
Not Available

Add predicate pushdown

---

pkg/vm/engine/tae/tables/indexwrapper/immutindex.go

issue #2733 
Not Available
Not Available
Not Available

(tae): check nil during destoring immutindex

---

pkg/vm/engine/tae/dataio/segmentio/segment.go

issue #
Not Available
Not Available
Not Available

Fix the bug that the file info expires when replay

---

pkg/sql/plan2/build_util.go

issue #2739 
Not Available
Not Available
Not Available

fix bug 2739

---

pkg/vm/engine/tae/logstore/store/appender.go
pkg/vm/engine/tae/logstore/store/replayer.go
pkg/vm/engine/tae/logstore/store/store_test.go
pkg/vm/engine/tae/logstore/store/syncbase.go

issue #2743 
Not Available
Not Available
Not Available

fix logstore bug

---

pkg/vm/engine/tae/container/vector/stdvec.go
pkg/vm/engine/tae/logstore/store/vfile.go
pkg/vm/engine/tae/txn/txnimpl/node.go

issue #2746 
Not Available
Not Available
Not Available

support timestamp in tae stdVector

---

pkg/frontend/test/engine_mock.go
pkg/sql/colexec2/deletion/deletion.go
pkg/vm/engine/aoe/engine/relation.go
pkg/vm/engine/aoe/local/relation.go
pkg/vm/engine/memEngine/relation.go
pkg/vm/engine/tae/moengine/relation.go
pkg/vm/engine/tpe/engine/relation.go
pkg/vm/engine/types.go

issue #2408 
Not Available
Not Available
Not Available

Adjust interface of engine for delete

---

pkg/sql/colexec2/expr_eval.go

issue #2372 
Not Available
Not Available
Not Available

add eval function for Expr_T

---

pkg/vm/engine/tae/logstore/store/store_test.go
pkg/vm/engine/tae/logstore/store/syncbase.go

issue #
Not Available
Not Available
Not Available

fix ut TestAddrVersion

---

pkg/frontend/load.go
pkg/frontend/load_test.go
pkg/frontend/mysql_cmd_executor.go
pkg/frontend/session.go

The problem jiangwen found. There is no issue for it.
issue #
There is one and only one txn context for one engine.Database and one engine.Relation instance.
Not Available
Not Available

fix misue of tae txn context for a single batch

---

pkg/vm/engine/tae/dataio/segmentio/segment_test.go
pkg/vm/engine/tae/layout/segment/log.go
pkg/vm/engine/tae/layout/segment/segment.go
pkg/vm/engine/tae/layout/segment/segment_test.go

issue #
Not Available
Not Available
Not Available

Update tae layout log's pagesize=512

---

pkg/sql/plan2/function/operator/cast.go
pkg/sql/plan2/function/operator/integerdiv.go
pkg/sql/plan2/function/operator/minus.go
pkg/sql/plan2/function/operator/mod.go
pkg/sql/plan2/function/operator/mult.go
pkg/sql/plan2/function/operator/unaryops.go

Most fixes are about unnecessary generics type spec.
Added uint to decimal128 cast.
issue #
Not Available
Not Available
Not Available

Fix go static check warning/errors.

---

pkg/vm/engine/tae/moengine/reader.go
pkg/vm/engine/tae/moengine/types.go

issue #
Not Available
Not Available
Not Available

Add read latency

---

pkg/sql/plan2/build_expr.go

issue #2372 
change args in case function.
1、now case function's args is (when1, then1, when2, then2, [else])
2、rewrite "case col when 1 then '1' else '2'" to "case when col=1 then '1' else '2'"
Not Available
Not Available

change args in case function

---

pkg/frontend/mysql_cmd_executor.go

To not crash server.   Fix #2764.
issue #
Not Available
Not Available
Not Available

Catch all panics in mysql_cmd_executor

---

pkg/vm/engine/tae/catalog/block.go
pkg/vm/engine/tae/catalog/catalog.go
pkg/vm/engine/tae/catalog/database.go
pkg/vm/engine/tae/catalog/schema.go
pkg/vm/engine/tae/catalog/segment.go
pkg/vm/engine/tae/catalog/table.go
pkg/vm/engine/tae/db/base_test.go
pkg/vm/engine/tae/db/compound_test.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/db/gc_test.go
pkg/vm/engine/tae/db/gcop.go
pkg/vm/engine/tae/db/helper.go
pkg/vm/engine/tae/db/hidden_test.go
pkg/vm/engine/tae/db/replay_test.go
pkg/vm/engine/tae/db/scanner.go
pkg/vm/engine/tae/db/scannerop.go
pkg/vm/engine/tae/db/scheduler.go
pkg/vm/engine/tae/db/scheduler_test.go
pkg/vm/engine/tae/db/task.go
pkg/vm/engine/tae/iface/txnif/types.go
pkg/vm/engine/tae/tables/blocktasks.go
pkg/vm/engine/tae/tables/mock.go
pkg/vm/engine/tae/testutils/config/options.go
pkg/vm/engine/tae/txn/txnbase/store.go
pkg/vm/engine/tae/txn/txnbase/txn.go
pkg/vm/engine/tae/txn/txnimpl/localseg.go
pkg/vm/engine/tae/txn/txnimpl/store.go

issue #2785 
Not Available
Not Available
Not Available

implement GC logic for drop table and database

---

pkg/sql/plan2/build_select.go
pkg/sql/plan2/build_util.go

issue #2372 
use deep copy expr in agg node
Not Available
Not Available

Deep copy expr

---

pkg/container/batch/batch.go
pkg/vm/pipeline2/pipeline.go

issue #
Not Available
Not Available
Not Available

Add cleanup for pipeline2

---

pkg/vm/engine/tae/common/compare.go
pkg/vm/engine/tae/container/compute/utils.go

issue #2799 
Not Available
Not Available
Not Available

(tae/hot fix): support decimal

---

pkg/vm/engine/tae/dataio/segmentio/segment_test.go
pkg/vm/engine/tae/layout/segment/segment.go
pkg/vm/engine/tae/layout/segment/segment_test.go

issue #
Not Available
Not Available
Not Available

Add tae layout's replay ut

---

pkg/container/types/timestamp.go
pkg/container/types/timestamp_test.go

issue #2803
Not Available
Not Available
Not Available

timestamp parser support rounding

---

pkg/vm/engine/tae/catalog/catalog.go
pkg/vm/engine/tae/catalog/table.go
pkg/vm/engine/tae/db/scanner.go

issue #2785 
issue #2783 
Right now we are skipping checkpoint on system DB and there will be user-defined tables created on system DB, which will never be checkpointed.
Not Available
Not Available

(tae): fix checkpoint bug

---

pkg/sql/plan2/build_expr.go
pkg/sql/plan2/build_select.go
pkg/sql/plan2/build_util.go

issue #2372 
Not Available
Not Available
Not Available

fix projectList bug

---

pkg/sql/colexec2/group/group.go

issue #
Not Available
Not Available
Not Available

Add missing error of group

---

pkg/vm/engine/tae/common/compare.go
pkg/vm/engine/tae/container/compute/compute.go
pkg/vm/engine/tae/container/compute/utils.go
pkg/vm/engine/tae/txn/txnimpl/index.go

issue #2819 
Not Available
Not Available
Not Available

(tae): support timestamp (part 1)

---

pkg/vm/engine/tae/mergesort/mergesort.go
pkg/vm/engine/tae/mergesort/timestamps/func.go
pkg/vm/engine/tae/mergesort/timestamps/heap.go
pkg/vm/engine/tae/mergesort/timestamps/sort.go
pkg/vm/engine/tae/mergesort/timestamps/types.go

issue #2819 
Not Available
Not Available
Not Available

support timestamp in tae mergesort

---

pkg/vm/engine/tae/dataio/segmentio/block.go

issue #
Not Available
Not Available
Not Available

Add rows for WriteIBatch

---

pkg/sql/colexec2/mergegroup/group.go
pkg/sql/compile2/compile.go
pkg/sql/plan2/function/aggregate.go

issue #
Not Available
Not Available
Not Available

Fix the bug of offset

---

pkg/sql/plan2/function/operator/unaryops.go
pkg/sql/plan2/function/operators.go

issue #2835
Slove the problem of unary minus not work
Not Available
Not Available

Slove unaryMinus bug

---

pkg/sql/plan2/function/builtin/unary/space.go
pkg/sql/plan2/function/builtin/unary/space_test.go
pkg/vectorize/space/space.go

issue #2795
Not Available
Not Available
Not Available

fix issue#2795

---

pkg/vm/engine/tae/dataio/mockio/segment.go
pkg/vm/engine/tae/dataio/segmentio/allocator.go
pkg/vm/engine/tae/dataio/segmentio/bitmap_allocator.go
pkg/vm/engine/tae/dataio/segmentio/block.go
pkg/vm/engine/tae/dataio/segmentio/colblk.go
pkg/vm/engine/tae/dataio/segmentio/data.go
pkg/vm/engine/tae/dataio/segmentio/driver.go
pkg/vm/engine/tae/dataio/segmentio/driver_test.go
pkg/vm/engine/tae/dataio/segmentio/extent.go
pkg/vm/engine/tae/dataio/segmentio/file.go
pkg/vm/engine/tae/dataio/segmentio/inode.go
pkg/vm/engine/tae/dataio/segmentio/log.go
pkg/vm/engine/tae/dataio/segmentio/segment.go
pkg/vm/engine/tae/dataio/segmentio/segment_test.go
pkg/vm/engine/tae/db/open.go

issue #
Not Available
Not Available
Not Available

Segmentio code refactor

---

pkg/vm/engine/tae/mergesort/bools/func.go
pkg/vm/engine/tae/mergesort/bools/heap.go
pkg/vm/engine/tae/mergesort/bools/sort.go
pkg/vm/engine/tae/mergesort/bools/types.go
pkg/vm/engine/tae/mergesort/mergesort.go

issue #2844 
Not Available
Not Available
Not Available

add bool for tae mergesort

---

pkg/frontend/insert.go

issue #2821
Not Available
Not Available
Not Available

Fix incorrect behavior for handling write relation errors

---

pkg/sql/compile2/compile.go

issue #
Not Available
Not Available
Not Available

Add rewrite pos for agg node

---

pkg/util/metric/dashboard/grafana8.4_mo_overview.json

issue #
Add statement latency panel, which is missing in previous dashboard
Not Available
Not Available

add statement latency panel to grafana dashboard

---

pkg/sql/plan2/function/builtin/binary/power.go
pkg/sql/plan2/function/builtin/multi/lpad.go
pkg/sql/plan2/function/builtin/multi/rpad.go
pkg/sql/plan2/function/builtin/unary/exp.go
pkg/sql/plan2/function/builtin/unary/exp_test.go
pkg/sql/plan2/function/builtin/unary/length.go
pkg/sql/plan2/function/builtin/unary/ltrim.go
pkg/sql/plan2/function/builtin/unary/reverse.go
pkg/sql/plan2/function/builtin/unary/rtrim.go
pkg/sql/plan2/function/operator/unaryops.go
pkg/vectorize/rpad/rpad.go

issue #2863
Panics related to functions appear in AOE pipeline testing, which need to be solved uniformly. The functions involved include: power, lpad, round, rpad, unary_ minus
Not Available
Not Available

Solve AOE function panic

---

pkg/sql/compile2/compile.go

issue #2653 
this pr only to support show databases/tables/columns
other show statement not finished yet
Not Available
Not Available

add support to run show databases/tables/columns

---

pkg/frontend/epochgc.go

issue #2849 
I think the persistence of epoch into cube kv storage is the most suspicious point.
So, I remove the persistence of epoch. It will not affect the correctness.
Now, whenever the leader of cluster has changed, in new leader, the epoch will increase
from the zero. It may delay some gc task of drop XXX.
Not Available
Not Available

fix epochgc stall (first try)

---

pkg/vm/engine/tae/dataio/segmentio/block.go

issue #2495 
Not Available
Not Available
Not Available

(tae): fix bug for load block

---

pkg/vm/engine/tae/db/replay.go
pkg/vm/engine/tae/db/replay_test.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/tables/node.go
pkg/vm/engine/tae/txn/txnbase/txnmgr.go

issue #2495 
Not Available
Not Available
Not Available

(tae): fix some replay bugs

---

pkg/container/ring/count/count.go
pkg/container/ring/count/types.go
pkg/sql/colexec2/aggregate/aggregate.go
pkg/sql/colexec2/aggregate/types.go
pkg/sql/colexec2/group/group.go
pkg/sql/colexec2/mergegroup/group_test.go
pkg/sql/compile2/operator.go
pkg/sql/plan2/build_expr.go
pkg/sql/plan2/build_from.go
pkg/sql/plan2/build_function.go
pkg/sql/plan2/build_subquery.go
pkg/sql/plan2/build_util.go
pkg/sql/plan2/explain/explain_expr.go
pkg/sql/plan2/function/function_id.go

issue #2324
Not Available
Not Available
Not Available

Add count(distinct)

---

pkg/sql/plan2/explain/explain_expr.go
pkg/sql/plan2/explain/explain_test.go

issue #2363
Improve the function of explain to show case when statements in plan2.
Not Available
Not Available

Add explain for case when expression

---

pkg/sql/plan2/function/builtin/unary/cos_test.go
pkg/sql/plan2/function/builtin/unary/cot_test.go
pkg/vectorize/cot/cot.go

issue #2882
Not Available
Not Available
Not Available

fix issue 2882,finish ut of cot_test and cos_test

---

pkg/sql/plan2/function/operator/plus.go

issue #2906
Not Available
Not Available
Not Available

fix issue#2906, plus result is wrong

---

pkg/frontend/mysql_cmd_executor.go
pkg/sql/testutil/testutil.go

issue #
Not Available
Not Available
Not Available

fix testutil function bugs

---

pkg/compare/asc/timestamps/compare.go
pkg/compare/asc/timestamps/compare_test.go
pkg/compare/asc/timestamps/types.go
pkg/compare/desc/timestamps/compare.go
pkg/compare/desc/timestamps/compare_test.go
pkg/compare/desc/timestamps/types.go
pkg/container/types/timestamp.go
pkg/sort/sort.go

issue #2924 
Not Available
Not Available
Not Available

fix issue#2924:Wrong order by result for TIMESTAMP

---

pkg/sql/colexec2/complement/complement.go
pkg/sql/colexec2/join/join.go
pkg/sql/colexec2/left/join.go
pkg/sql/colexec2/product/product.go
pkg/sql/colexec2/semi/join.go

issue #2372
Not Available
Not Available
Not Available

Add some check

---

pkg/sql/colexec2/restrict/restrict.go

issue #
Not Available
Not Available
Not Available

Free vector of restrict

---

pkg/vm/engine/tae/catalog/block.go
pkg/vm/engine/tae/catalog/catalog.go
pkg/vm/engine/tae/db/replay.go

issue #2495 
Not Available
Not Available
Not Available

(tae): fix replay catalog related bug

---

pkg/sql/plan2/function/builtin/binary/power_test.go
pkg/sql/plan2/function/builtin/unary/ln_test.go
pkg/sql/plan2/function/builtin/unary/log_test.go
pkg/sql/plan2/function/builtin/unary/sin_test.go

issue #2948
Not Available
Not Available
Not Available

add log/ln/power/sin ut

---

pkg/vm/engine/tae/logstore/store/store_test.go
pkg/vm/engine/tae/logstore/store/syncbase.go

issue #2956
Not Available
Not Available
Not Available

fix MergeCheckpointInfo

---

pkg/vm/engine/tae/catalog/schema.go
pkg/vm/engine/tae/db/replay_test.go

issue #
Not Available
Not Available
Not Available

Fix default value serialization bug

---

.github/workflows/ci.yml

issue #
Not Available
Not Available
Not Available

ingore colname check in some cases

---

pkg/sql/plan2/function/builtin/binary/findinset_test.go
pkg/sql/plan2/function/builtin/unary/bit_length_test.go
pkg/sql/plan2/function/builtin/unary/empty_test.go
pkg/sql/plan2/function/builtin/unary/oct.go
pkg/sql/plan2/function/builtin/unary/oct_test.go

issue #
* add unit test for empty/oct/bit_length/find_in_set
* fix oct bug
Not Available
Not Available

add string func unit test

---

pkg/frontend/load.go

issue #2921 
Not Available
Not Available
Not Available

fix int64 should not parse to float64 bug

---

pkg/container/vector/vector.go
pkg/sql/colexec2/complement/complement.go
pkg/sql/colexec2/group/group.go
pkg/sql/colexec2/join/join.go
pkg/sql/colexec2/left/join.go
pkg/sql/colexec2/mergegroup/group.go
pkg/sql/colexec2/semi/join.go

issue #
Not Available
Not Available
Not Available

Adding missing  handle for constants

---

pkg/util/metric/m_hardware.go
pkg/util/metric/m_hardware_test.go

issue #2973
Not Available
Not Available
Not Available

fix nil metric when failed to collect hardware

---

pkg/vm/engine/tae/db/replay.go

issue #2495 
Not Available
Not Available
Not Available

cleanup stale files after replay

---

cmd/generate-config/system_vars_def.toml

issue #
Not Available
Not Available
Not Available

Turn on usePlan2 and tae as default.

---

docs/cn/MatrixOne/MatrixCampEvent.md

issue #
Not Available
Not Available
Not Available

Fix some chinese typo error

---

pkg/frontend/mysql_cmd_executor.go
pkg/sql/colexec2/aggregate/aggregate.go

issue #3011 
Not Available
Not Available
Not Available

support decimal aggregation in plan2

---

pkg/hakeeper/state.go
pkg/pb/metadata/metadata.pb.go
pkg/pb/plan/plan.pb.go
proto/metadata.proto

issue #
Added the expected replica count used by HAKeeper
Not Available
Not Available

Hakeeper: add expected replica count

---

pkg/vm/engine/tae/moengine/reader.go

issue #
Not Available
Not Available
Not Available

Remove tae reader preallocated memory

---

pkg/container/vector/vector.go
pkg/sql/colexec2/group/group.go

issue #3011
Not Available
Not Available
Not Available

Add missing contant handle of group

---

pkg/vm/engine/tae/logstore/store/store_test.go

issue #
Not Available
Not Available
Not Available

fix TestMergePartialCKP

---

pkg/hakeeper/checker.go
pkg/hakeeper/rsm.go
pkg/hakeeper/state.go

issue #
Added the Checker interface that will be used by @w-zr and @cnutshell 
Not Available
Not Available

hakeeper: added the Checker interface

---

pkg/sql/plan2/function/builtin/multi/date_sub.go

issue #3040
Not Available
Not Available
Not Available

fix date_sub(NULL,INTERVAL 100000 SECOND) bug

---

pkg/pb/hakeeper/hakeeper.pb.go
proto/hakeeper.proto

issue #
Modify hakeeper.proto.
Not Available
Not Available

modify hakeeper.proto

---

pkg/container/ring/anyvalue/anyvalue.go

issue #3051
Not Available
Not Available
Not Available

Fix the bug of anyvalue

---

.github/workflows/lint_docs.yml

issue #
Not Available
Not Available
Not Available

separate sca and ut ci

---

pkg/container/vector/vector.go
pkg/sql/colexec2/complement/complement.go
pkg/sql/colexec2/expr_eval.go
pkg/sql/colexec2/join/join.go
pkg/sql/colexec2/left/join.go
pkg/sql/colexec2/loopcomplement/complement.go
pkg/sql/colexec2/loopcomplement/complement_test.go
pkg/sql/colexec2/loopcomplement/types.go
pkg/sql/colexec2/loopjoin/join.go
pkg/sql/colexec2/loopjoin/join_test.go
pkg/sql/colexec2/loopjoin/types.go
pkg/sql/colexec2/loopleft/join.go
pkg/sql/colexec2/loopleft/join_test.go
pkg/sql/colexec2/loopleft/types.go
pkg/sql/colexec2/loopsemi/join.go
pkg/sql/colexec2/loopsemi/join_test.go
pkg/sql/colexec2/loopsemi/types.go
pkg/sql/colexec2/semi/join.go

issue #
Not Available
Not Available
Not Available

Add non-euqi join operator

---

pkg/vm/overload/overload.go
pkg/vm/overload/types.go

issue #
Not Available
Not Available
Not Available

Register non-equi join operator

---

docs/en/MatrixOne/Reference/SQL-Reference/Aggregate-Functions/avg.md

issue #
Not Available
Not Available
Not Available

Update avg function contraints

---

pkg/sql/plan2/optimize.go
pkg/sql/plan2/query_builder.go
pkg/sql/plan2/utils.go

issue #2373
Not Available
Not Available
Not Available

[Plan2] Push down filter conditions

---

pkg/vm/engine/tae/dataio/segmentio/bitmap_allocator.go
pkg/vm/engine/tae/dataio/segmentio/block.go
pkg/vm/engine/tae/dataio/segmentio/colblk.go
pkg/vm/engine/tae/dataio/segmentio/data.go
pkg/vm/engine/tae/dataio/segmentio/driver.go

issue #
Not Available
Not Available
Not Available

quick solution for tae allocator to crash

---

pkg/sql/plan2/function/operator/mult.go

issue #3081
Solve the problem of floating point multiplication error reporting
Not Available
Not Available

Solve the problem of floating point multiplication error reporting

---

pkg/sql/errors/types.go
pkg/sql/plan2/base_binder.go
pkg/sql/plan2/bind_context.go
pkg/sql/plan2/build_util.go
pkg/sql/plan2/query_builder.go

issue #
Not Available
Not Available
Not Available

Friendly error msg

---

pkg/vm/engine/tae/catalog/catalog.go
pkg/vm/engine/tae/catalog/segment.go
pkg/vm/engine/tae/dataio/segmentio/block.go
pkg/vm/engine/tae/dataio/segmentio/block_test.go
pkg/vm/engine/tae/dataio/segmentio/colblk.go
pkg/vm/engine/tae/dataio/segmentio/data.go
pkg/vm/engine/tae/dataio/segmentio/driver.go
pkg/vm/engine/tae/dataio/segmentio/driver_test.go
pkg/vm/engine/tae/dataio/segmentio/file.go
pkg/vm/engine/tae/dataio/segmentio/inode.go
pkg/vm/engine/tae/dataio/segmentio/log.go
pkg/vm/engine/tae/dataio/segmentio/segment.go
pkg/vm/engine/tae/dataio/segmentio/segment_test.go
pkg/vm/engine/tae/db/replay.go
pkg/vm/engine/tae/iface/file/segment.go

issue #
Not Available
Not Available
Not Available

Driver refactor

---

pkg/hakeeper/rsm.go
pkg/logservice/rsm.go
pkg/logservice/rsm_test.go
pkg/logservice/service.go
pkg/logservice/store.go

issue #
Minor refactoring only
Not Available
Not Available

logservice: minor refactoring

---

pkg/sql/colexec2/restrict/restrict.go
pkg/sql/plan2/build_function.go
pkg/sql/plan2/function/function.go
pkg/sql/plan2/function/function_test.go
pkg/sql/plan2/query_builder.go

issue #
Change some error messages into some readable ones.
Not Available
Not Available

fix error message

---

pkg/frontend/insert.go
pkg/frontend/mysql_cmd_executor.go
pkg/sql/colexec2/update/update.go
pkg/sql/parsers/dialect/mysql/mysql_lexer.go
pkg/sql/parsers/dialect/mysql/mysql_sql.go
pkg/sql/parsers/dialect/mysql/mysql_sql.y

issue #
Not Available
Not Available
Not Available

Modify msg of err and can update to null

---

pkg/vm/engine/tae/tables/updates/colupdate.go

issue #
Not Available
Not Available
Not Available

fix ColumnUpdateNode ReadFrom

---

pkg/container/ring/anyvalue/anyvalue.go

issue #3051 
Not Available
Not Available
Not Available

fix a bug in any_value

---

pkg/sql/plan2/build_delete.go

issue #
Not Available
Not Available
Not Available

Ajust build delete plan

---

pkg/sql/plan2/base_binder.go
pkg/sql/plan2/bind_context.go
pkg/sql/plan2/build.go
pkg/sql/plan2/build_test.go
pkg/sql/plan2/flatten_subquery.go
pkg/sql/plan2/query_builder.go
pkg/sql/plan2/types.go

issue #2379
Not Available
Not Available
Not Available

[Plan2] Inline CTEs as subqueries

---

pkg/sql/plan2/base_binder.go
pkg/sql/plan2/build_test.go

issue #2372 
Not Available
Not Available
Not Available

rewrite nullif/ifnull function to case function

---

docs/en/MatrixOne/Reference/SQL-Reference/Aggregate-Functions/sum.md

issue #
Not Available
Not Available
Updating constraints of aggregate function sum()

Update sum aggreagtion function
