pkg/vm/engine/aoe/storage/db/open_test.go
pkg/vm/engine/aoe/storage/db/replay_test.go
pkg/vm/engine/aoe/storage/logstore/rotational.go
pkg/vm/engine/aoe/storage/logstore/syncbase.go
pkg/vm/engine/aoe/storage/metadata/v1/catalog.go
pkg/vm/engine/aoe/storage/metadata/v1/segment.go
pkg/vm/engine/aoe/storage/metadata/v1/table.go

issue #
Not Available
Not Available
Not Available

fix occasionally commit out of order problem

---

pkg/sql/build/expr.go
pkg/sql/tree/constant.go
pkg/sql/unittest/sql_test.go

issue #825
1.
Support operator expression for constant in INSERT.
Such as `insert into cms values (1+1/100, 'abc', 2.5 div 7)` and so on.
2.
Add rules for insert float into int / uint. 4 is ignored and 5 will accept.
1.5 -> 1,  
-1.5 -> -2, 
0.4 -> 0
Not Available
Not Available

Support more operators in INSERT CLAUSE

---

pkg/sql/build/expr.go
pkg/sql/build/prune.go
pkg/sql/build/show.go
pkg/sql/colexec/extend/overload/binary.go
pkg/sql/colexec/extend/overload/like.go
pkg/sql/compile/scope.go
pkg/sql/op/showDatabases/show.go
pkg/sql/op/showDatabases/types.go
pkg/sql/op/showTables/show.go
pkg/sql/op/showTables/types.go
pkg/sql/unittest/sql_test.go
pkg/vectorize/like/like.go

issue #979
1.Support Like Operator.
For Example:
select * from tbl where '123' like '_%'
select * from tbl where column1 like column2
select * from tbl where column1 like 'example'
select * from tbl where 'example' like column1
2.Support Like in show tables and show databases.
For Example:
show databases like 'db_'
show tables like '%qwq%'
Not Available
Not Available

support LIKE operator

---

pkg/frontend/load.go
pkg/frontend/mysql_cmd_executor.go
pkg/frontend/mysql_protocol.go
pkg/frontend/mysql_protocol_predefines.go

fix #1230 
Some colleagues complain that the load drops the data during working when the writebatch timeout happens.
Actually it is not.  The recorder counter does not include the counts from the timeout. So, it is suitable to separate out counts of timeout from the total counter.
Not Available
Not Available

Mislead writebatch timeout

---

pkg/container/types/date.go
pkg/encoding/debug_encoding.go
pkg/frontend/mysql_cmd_executor.go
pkg/frontend/mysql_protocol.go
pkg/sql/compile/scope.go
pkg/sql/ftree/build_test.go
pkg/sql/plan/create_table.go
pkg/sql/plan/expr.go
pkg/sql/plan/insert.go
pkg/sql/protocol/protocol.go
pkg/sql/unittest/sql_test.go
pkg/vm/engine/aoe/protocol/protocol.go
pkg/vm/engine/types.go

issue #827 
1. Support create table using column type 'date'
For Example:
`create table tbl (c1 date default '2021-12-02');`
2. Support insert constant value into date column, and range is from 19000101 to 99991231
constant value format can be
(1) 'yyyy-mm-dd'
(2) 'yyyymmdd'
(3) 'yy-mm-dd'
(4) 'yymmdd'
(5) INT yymmdd, yyyymmdd likes 19201003, 211202
For Example:
`insert into tbl values (201202), ('1997-02-11'), (19700315);`
3. Fix a bug while show columns from table.
Not Available
Not Available

Support Type Date (create / insert and show in frontEnd)

---

pkg/container/types/date.go
pkg/container/types/datetime.go
pkg/frontend/mysql_cmd_executor.go
pkg/frontend/mysql_protocol.go
pkg/sql/plan/create_table.go
pkg/sql/plan/expr.go
pkg/sql/plan/insert.go
pkg/sql/protocol/protocol.go
pkg/sql/unittest/sql_test.go
pkg/vm/engine/aoe/protocol/protocol.go
pkg/vm/engine/types.go

issue #827 
1.Support insert / create / select for `datetime` type.
but can not support `insert into tbl values (now());`.
supported format for datetime type:
1.'2015-10-3 12:11:10'
2.'2015-10-3'
3.12030205153444
2. use regexp to refactor ParseDate
Not Available
Not Available

Support `datetime` column type. create / insert / select

---

cmd/db-server/main.go
cmd/db-server/profile.go

issue #1322
Not Available
Not Available
**Additional documentation (e.g. design docs, usage docs, etc.):
Usages:
cpu profiling:
./db-server -cpu-profile cpuprofile system_vars_config.toml
After server shutdown, the CPU profile will be written to `cpuprofile`
allocation profiling:
./db-server -allocs-profile allocsprofile system_vars_config.toml
After server shutdown, the allocation profile will be written to `allocsprofile`
auto heap profile snapshot:
./db-server -heap-profile heap -heap-profile-threshold 1000000000 system_vars_config.toml
If heap allocates more than 1G in one second, take a heap profile and write to heap.[time].

add cpu, allocs, heap profiling flags

---

Makefile
cmd/db-server/main.go

issue #1326
pass the argument "--version" to mo-server executable to get the build info.
Not Available
Not Available
Not Available

Feature: support command line argument --version in mo-server executable

---

cmd/generate-config/system_vars_def.toml
go.mod
go.sum

issue #1445
In some situations such as in the Docker or NAT network environment, if a client cannot access service through the default client URLs listened to by service, you must manually set the advertise client URLs.  Link： [matrixcube PR](https://github.com/matrixorigin/matrixcube/pull/574)
Not Available
Not Available

[CONFIG] Support advertise rpc addresses parameters for pd

---

pkg/sql/colexec/extend/overload/binary.go
pkg/sql/colexec/extend/overload/unary.go
pkg/sql/plan/drop_index.go

issue #
1.adjust code: built-in functions do not use type-implicit-conversion
2.add a error case for drop index
Not Available
Not Available

built-in functions do not use type-implicit-conversion

---

pkg/container/types/date.go
pkg/container/types/datetime.go
pkg/sql/unittest/sql_test.go

issue #1511 
rewrite functions ParseDate and ParseDatetime
but we have more restrict requirement for value format at the same time. now can only support
Date: 1.yyyy-mm-dd 2.yyyymmdd
Datetime: 1.all Date 2. yyyy-mm-dd hh:mm:ss(.msec) 3. yyyymmddhhmmss(.msec)
in simple test to run old and new functions 100-million times. 
old parseDate functions cost 32s, parseDatetime cost 1min 30s
and new function cost 812ms, parseDatetime cost 1.4s
it is faster than olds.
Not Available
Not Available

rewrite ParseDate and ParseDatetime functions

---

pkg/vm/engine/aoe/storage/wal/shard/shard_test.go
pkg/vm/engine/aoe/storage/wal/shard/types.go

issue #
When SafeIds.Unmarshal is called, bytes are unmarshalled into local variable，not into the Ids filed in SafeIds struct
Not Available
Not Available

fix SafeIds Unmarshal

---

cmd/generate-config/system_vars_def.toml

issue #1544 
Not Available
Not Available
Not Available

update comment for system vars

---

pkg/sql/colexec/extend/overload/init.go
pkg/sql/colexec/extend/overload/minus.template
pkg/sql/colexec/extend/overload/mult.template
pkg/sql/plan/prune.go
pkg/sql/plan/prune_test.go
pkg/sql/unittest/operator_test.go
pkg/vectorize/eq/eq.go

issue #1688 
issue #1687 
equal operator has its own typecast rules in the map OperatorCastRules,
original pruneEq operation will produce incorrect answer, e.g., 2 = 2.1 will be evaluated true.

fix issue#1688, #1687, #1690

---

pkg/builtin/types.go
pkg/builtin/unary/abs.go
pkg/vectorize/abs/abs.go
pkg/vectorize/abs/abs_test.go

issue #1837
Implement built-in abs();
Not Available
Not Available
Not Available

Feature abs

---

pkg/builtin/types.go
pkg/builtin/unary/ln.go
pkg/vectorize/ln/ln.go
pkg/vectorize/ln/ln_test.go

issue #1825
implement ln(x).
1. how can I output "NULL" for users if the x <= 0?
2. what if we have a table `p1` like this:
```
+------+--------+
| id   | score  |
+------+--------+
|    1 | 1.1000 |
|    2 | 2.2000 |
|   -1 | 3.3000 |
|    4 | 4.4000 |
+------+--------+
```
and use `select ln(id) from p1;`
show it output all enties like:
```
+--------+
| ln(id) | 
+--------+
| 0.0000 |
| 0.6931 |
| NULL   |
| 1.3862 |
+--------+
ERROR 1105 (HY000): unknown error:Invalid argument for logarithm
```
But for now, it will only output:
"ERROR 1105 (HY000): unknown error: Invalid argument for logarithm"
Is there any way to fix it?

[RFC] implement ln builtin function

---

pkg/builtin/binary/power.go
pkg/builtin/types.go
pkg/sql/colexec/extend/overload/init.go
pkg/vectorize/power/power.go
pkg/vectorize/power/power_test.go

issue #1824
This PR implements built-in function power.
Suppose we have **table tb(int,int,double)**:
```SQL
mysql> select * from tb_power;
+------+------+--------+
| a    | b    | c      |
+------+------+--------+
|    2 |    2 | 3.1400 |
|    2 |   -2 | 2.7800 |
+------+------+--------+
```
When we execute _select power(a,b),power(a,c),power(c,a) from tb_power_. It will print like this:
```SQL
mysql> select power(a,b),power(a,c),power(c,a) from tb_power;
+-------------+-------------+-------------+
| power(a, b) | power(a, c) | power(c, a) |
+-------------+-------------+-------------+
|      4.0000 |      8.8152 |      9.8596 |
|      0.2500 |      6.8685 |      7.7284 | …
```

Implement built-in function power.

---

.github/workflows/docker_ci.yml

issue #
Cancel job time limit of docker build and push workflow
[Default github action usage limit](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits)
Not Available

docker build job time limit

---

pkg/sql/plan/prune.go
pkg/sql/rewrite/astrewrite.go
pkg/sql/unittest/dml_test.go

issue #1660 #1659
Cause of problem #1660:
When the where conditional expression of the select statement is a negative sign unary expression, it cannot be used as the result of logical calculation, resulting in program crash,
Solution:
Rewrite the unary expression in the where clause in the rewriting part of AST syntax tree, and modify the unary expression to unaryexpr= 0
Cause of problem #1659:
When the where conditional expression of the select statement contains multiple negative unary expressions, such as -- 1, when pruning the negative unary expression, this situation is handled, resulting in incorrect where calculation results
Solution:
When pruning the unary expression with …

Fix the problem of negative sign logical inversion

---

pkg/common/async/future.go
pkg/common/async/future_test.go

Our current driver code use callback.  In general, future
is eaiser to program and reasoning than callback.
Still using interface{} in Future instead of generics.
Test infra is on go 1.17, waiting for upgrade to go 1.18.
issue #
Not Available
Not Available
Not Available

Add future as another way to do async call.

---

Makefile

Calling recover() in non-test code will require approval first
issue #
mo-lint will be installed and invoked as a part of SCA. At this stage, it only checks whether there is any unexpected call to recover(), we can add more checks later when necessary.  
Already talked to code owns of all existing calls to recover(), resolved some of them and @nnsgmsone confirmed a few calls to recover() that is indeed required. 
Not Available
Not Available

Enable molint as a part of SCA

---

go.mod
go.sum

Removed reference to old etcd versions
issue #
#2423 didn't include a `go mod tidy` run. 
Not Available
Not Available

Removed reference to old etcd in go.mod

---

Makefile

issue #
Added go-licenses check to the static-check target. go-licenses is a tool that can check for code with forbidden licenses (such as AGPL3.0) imported by MO.  
See a list of forbidden licenses as defined by google's licenseclassifier
https://github.com/google/licenseclassifier/blob/842c0d70d7027215932deb13801890992c9ba364/license_type.go#L323
Not Available
Not Available

Added go-licenses check to the static-check target

---

cmd/db-server/debug.go
pkg/sql/colexec2/mergeoffset/offset_test.go
pkg/vm/engine/tae/samples/sample2/main.go
pkg/vm/engine/tae/samples/sample3/main.go
pkg/vm/engine/tae/tables/txnentries/mergeblockscmd.go
pkg/vm/engine/tae/txn/txnbase/helper.go

issue #2133
Fix some apparent cases marked via linter [errcheck](https://github.com/kisielk/errcheck).
```bash
golangci-lint run --disable-all --max-same-issues 10000 --max-issues-per-linter 10000 -E errcheck
```
In the current repository, there are 647 cases marked by `errcheck`:
- 388 cases within test code
- 259 cases within normal code (non-test code)
This PR fix just apparent ones.
Not Available

Static check: fix apparent cases for `errcheck`;

---

pkg/frontend/mysql_cmd_executor.go
pkg/sql/plan2/explain/explain_expr.go
pkg/sql/plan2/explain/explain_node.go
pkg/sql/plan2/explain/explain_query.go
pkg/sql/plan2/explain/explain_test.go
pkg/sql/plan2/function/operators.go

issue #2363
1. After the implementation of CompilerContext, explain needs to replace the original mock Compiler Context to support the explain operation of normal SQL
2. Note that the explain function is based on plan2, so you need to Set the 'usePlan' option to true which 
in the configuration file 'system_vars_config.toml'
Not Available
Not Available

explain support txn CompileContext

---

README_CN.md

Signed-off-by: ericsyh <ericshenyuhao@outlook.com>
issue #
Fix the dead link in README_CN. Change the link address from https://docs.matrixorigin.cn/0.3.0/MatrixOne/Overview/MatrixOne-Tech-Design/matrixone-techdesign/ to https://docs.matrixorigin.io/cn/0.3.0/MatrixOne/Overview/MatrixOne-Tech-Design/matrixone-techdesign/
Not Available
Not Available

fix(docs): Dead link in CN README

---

pkg/sql/plan2/build_function.go

issue #2372 
" date '2010-10-10' + interval 1 Hour “  will return date time。
so we cast "2010-10-10" to date time  when the unit is Hour/Minute/Second/MicroSecond/Hour_Minute.....
Not Available
Not Available

improve date function

---

pkg/frontend/session.go
pkg/frontend/session_test.go
pkg/sql/plan2/mock.go
pkg/sql/plan2/types.go

issue #2386 
In many application related to JDBC and mysql GUI administrator tools like Mysql Workbench, DBeaver, Navicat need to read system variables to make applications work well. So, mo should provide system variables adminstration mechanism.
Based on the conclusions discussed with @fengttt @ouyuanning , the resolving value of system variables will be done in the construct process of the plan2. After that, the value of system variables are constants than can not be changed again.
Not Available
Not Available

add resolveVariable

---

pkg/frontend/insert.go
pkg/sql/compile2/scope.go
pkg/sql/plan2/build_util.go
pkg/vm/engine/tae/catalog/schema.go
pkg/vm/engine/tae/moengine/engine_test.go
pkg/vm/engine/tae/moengine/helper.go

issue #2867 #2706 
Not Available
Not Available
Not Available

Support default value for tae

---

pkg/sql/plan2/build_test.go
pkg/sql/plan2/query_builder.go

issue #2969 
these sqls:
select distinct(col1) from tbl
select (col1) from tbl
select ((col1)) from tbl
will return column:  col1
Not Available
Not Available

fix bug 2969(return column name is wrong)

---

pkg/logservice/client.go
pkg/logservice/client_test.go
pkg/logservice/service.go

issue #
Use sync.Pool to avoid allocations in morpc.
Not Available
Not Available

logservice: use sync.Pool to avoid morpc allocations

---

pkg/vm/engine/tae/stl/containers/stdvec.go

issue #
The default policy is to expand vector capacity to at least 2x. and I forgot to apply this policy for `extend` operation.
Not Available
Not Available

fix vector expand bug during extend

---

pkg/hakeeper/rsm.go
pkg/hakeeper/rsm_test.go
pkg/logservice/hachecker.go
pkg/logservice/hachecker_test.go
pkg/logservice/store_test.go

issue #
k8s, hakeeper in bootstrap mode and hakeeper in running mode now all get their own id ranges, when allocating shard/replica id values, they will have to draw from their per determined id ranges.  
Not Available
Not Available

hakeeper: respect per determined id ranges

---

Makefile
cgo/Makefile

intermediate libxxx.a files are no longer kept
issue #
`make` should build the non-debug version of mo-server by default. 
Not Available
Not Available

Makefile: build production mo-server by default

---

pkg/logservice/hakeeper_client.go
pkg/logservice/hakeeper_client_test.go

issue #
Internally retry HAKeeper client requests. 
Not Available
Not Available

hakeeper: internally retry HAKeeper client requests

---

pkg/logservice/service_commands.go
pkg/logservice/service_commands_test.go
pkg/logservice/store_metadata.go
pkg/logservice/store_metadata_test.go

issue #
Zombie replicas are now handled by the dedicated KillZombie command. 
Not Available
Not Available

logservice: handle kill zombie command

---

pkg/logservice/client.go
pkg/logservice/client_test.go
pkg/logservice/config.go
pkg/logservice/config_test.go
pkg/logservice/hakeeper_client.go
pkg/logservice/hakeeper_client_test.go

issue #
always validate client config first
Not Available
Not Available

logservice: always validate client config first

---

pkg/logservice/store.go
pkg/logservice/store_test.go

issue #
When HAKeeper replica is stopped by a KillZombie command, HAKeeper ticker managed by the Log Store should be stopped as well. This avoids flooding the log with a ton of ticker failed error messages.  
Not Available
Not Available

logservice: stop hakeeper ticker on KillZombie command

---

pkg/sql/plan/build.go
pkg/sql/plan/types.go

issue #
define an interface(empty function) to get execute type from plan for test
we will finish the function later

add an empty getExecTypeFromPlan for test

---

pkg/vm/engine/tae/db/replay.go

issue #4428
Fix onReplayAppendCmd. Check whether there exists active block before load data.

fix onReplayAppendCmd

---

pkg/logservice/client.go
pkg/logservice/service_bootstrap.go
pkg/logservice/service_commands.go
pkg/logservice/store.go
pkg/logservice/store_test.go

issue #
* use constant connection timeout value which is much smaller than the LOG node heartbeat timeout. this ensures we get chance to try most specified HAKeeper nodes. 
* during bootstrap, it is possible for the HAKeeper replica to be removed by a KILL command, terminate the local bootstrap procedure when that happens. 
* always keep the ticker worker even after the HAKeeper replica is stopped.

logservice: fixed various HAKeeper client connectivity issues

---

proto/gen.sh

issue #
When the environmental variable GOPATH is not set, get its value from the output of the `go env GOPATH` command otherwise gen.sh will be using incorrect paths.

proto: fixed proto/gen.sh

---

pkg/common/morpc/backend.go
pkg/common/morpc/backend_test.go

morpc's backend will keep retrying to send failed messages, this logic does not make sense, it should be necessary to limit the retry time to the maximum reconnect time
issue #4418

morpc: fix retry frequently

---

pkg/dnservice/store.go
pkg/dnservice/store_metadata.go
pkg/dnservice/store_test.go

issue #
If any Replica exists, a deadlock will occur when DNService starts.

dnservice: fix start failed if any replica exists

---

pkg/fileservice/block_mapper.go
pkg/fileservice/block_mapper_test.go
pkg/fileservice/file_service_test.go
pkg/fileservice/local_etl_fs.go
pkg/fileservice/local_fs.go

issue #2716 
fileservice: fix DataMapper.readBlock,Read,Seek
fileservice: implement io.ReaderAt,WriterAt for BlockMapper
fileservice: use BlockMapper in LocalFS

fileservice: use BlockMapper in LocalFS

---

pkg/common/morpc/backend.go
pkg/common/morpc/backend_test.go
pkg/dnservice/store.go
pkg/logservice/client.go
pkg/logservice/client_test.go
pkg/logservice/hakeeper_client_test.go
pkg/logservice/option.go
pkg/logservice/option_test.go
pkg/logservice/service.go
pkg/logservice/service_commands_test.go
pkg/logservice/service_test.go
pkg/logservice/service_wrap.go
pkg/logservice/store_hakeeper_check_test.go
pkg/logservice/testclient.go

issue #4003
- Enable flexible `morpc` option for package `logservice`
- Extend `morpc.WithBackendFilter` in order to support network partition feature

Enable flexible `morpc` option for package `logservice`

---

.dockerignore

Signed-off-by: wanglei4687 <wanglei4687@gmail.com>
issue #
1. cago compiler with link system lib, so  ignore cgo generate files
`/usr/bin/ld` is my local Apple's linker
For example: 
```
#16 52.59 # github.com/matrixorigin/matrixone/cmd/db-server
#16 52.59 /usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
#16 52.59 /usr/bin/ld: /tmp/go-link-2126209758/000006.o: in function `_cgo_df8c56550131_Cfunc_Decimal128_Add':
#16 52.59 decimal.cgo2.c:(.text+0x71): undefined reference to `Decimal128_Add'
#16 52.59 /usr/bin/ld: /tmp/go-link-2126209758/000006.o: in function `_cgo_df8c56550131_Cfunc_Decimal128_AddDecimal64':
#16 52.59 decimal.cgo2.c:(.text+0xcd): undefined reference to `Decimal128_AddDecimal64'
#16 52.59 /usr/bin/ld: /tmp/go-link-2126209758/000006.o: in function …
```

fix: dockerignore config

---

pkg/fileservice/s3_fs_test.go
pkg/util/metric/config_test.go

issue #
This PR replaces `os.Setenv` with `t.Setenv`. Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
This saves us at least 2 lines (error check, and unsetting the env var) on every instance.
```go
func TestFoo(t *testing.T) {
// before
key := "ENV"
originalEnv := os.Getenv(key)
if err := os.Setenv(key, "new value"); err != nil {
t.Fatal(err)
}
defer func() {
if err := os.Setenv(key, originalEnv); err != nil {
t.Logf("failed to set env %s back to original value: %v", key, err)
}
}()
// after
t.Setenv(key, "new value")
}
``` …

test: use `T.Setenv` to set env vars in tests

---

pkg/cnservice/server.go
pkg/cnservice/types.go
pkg/dnservice/cfg.go
pkg/dnservice/cfg_test.go
pkg/dnservice/store.go
pkg/txn/rpc/cfg.go
pkg/txn/rpc/cfg_test.go
pkg/txn/rpc/sender.go

issue #
Support create txn sender by config. And DN and CN service can share this implementation.

txn: support create txn sender by config

---

pkg/logservice/service_test.go
pkg/logservice/store_test.go

issue #
Stop directing gossip traffics to service address as that could confuse some tests.

logservice: fixed gossip seed addresses used in tests

---

pkg/common/morpc/backend.go
pkg/common/morpc/backend_test.go

issue #
panic if deadline not set in Context. Help to quickly locate the wrong way to use Context in morpc

morpc: panic if deadline not set in Context

---

pkg/dnservice/store_rpc_handler.go
pkg/txn/service/errors.go
pkg/txn/service/service.go
pkg/txn/service/service_cn_handler.go
pkg/txn/service/service_cn_handler_test.go
pkg/txn/service/service_dn_handler.go
pkg/txn/service/service_testutil.go

issue #
return DNShardNotFound instead of panic for all rerequests send from CN

txn: return DNShardNotFound instead of panic

---

pkg/sql/plan/function/builtin/binary/typecast.go
pkg/sql/plan/function/builtin/unary/math.go
pkg/sql/plan/function/operator/cast.go
pkg/sql/plan/rule/constant_fold.go
pkg/sql/plan/utils.go
test/result/explain/explain.result

The previous implementation of cast(* as char) handles scalars in a
wrong way, thus constant folding can't be enabled on cast.
issue #

{Opt] Fix bugs in scalar handling to enable constant fold

---

pkg/sql/colexec/anti/join.go
pkg/sql/colexec/left/join.go
pkg/sql/colexec/loopanti/join.go
pkg/sql/colexec/loopleft/join.go
pkg/sql/colexec/loopsingle/join.go
pkg/sql/colexec/projection/projection.go
pkg/sql/colexec/semi/join.go
pkg/sql/colexec/single/join.go

When the right table of LEFT/SINGLE/ANTI join is empty, we should simply
move vectors from left table to output.
issue #

Reduce unnecessary non-sequential memory copies

---

cgo/Makefile

gcc build mod only allowed in C99
issue #
issue: 4867

[Enhancement]: gcc build mod only allowed in C99

---

pkg/container/vector/tools.go

issue #
vector: return nil in encodeColToByteSlice if vector.Col is nil

 vector: return nil in encodeColToByteSlice if vector.Col is nil 

---

pkg/logservice/service_test.go

issue #
Has goroutine leak in memberlist. Skip the TestGossipInSimulatedCluster first, and fix it later.

logservice: skip TestGossipInSimulatedCluster

---

pkg/taskservice/mem_task_storage.go
pkg/taskservice/task_service.go
pkg/taskservice/task_service_test.go

issue #
Support re-allocate CN for timed out tasks. The task scheduler will re-allocate the CN for timed out task to make sure the task will be executed.

taskservice: support re-allocate CN for task

---

pkg/sql/plan/function/type_check.go
test/cases/union/union.result
test/cases/union/union.sql

issue #4943 
fix bug: output is incorrect in union clause
because plan will cast int8 & float32 to float64.  but that's unnecessary

fix bug: output is incorrect in union clause

---

pkg/pb/txn/txn.go
pkg/txn/service/service_cn_handler.go

issue #
When TxnService handles Read, TxnResponse directly references the Txn of TxnRequest, causing the protobuf object to be reset when the response is sent asynchronously, and then panic

txn: fix panic when sending txn response

---

etc/cn-standalone-test.toml

issue #
set console format log, as running bvt.
it can show real newline or tab character in the message field, instead of '\n' or '\t'.
if developers want to log some formated-json, or panic stacktrace, they can benift from it.
log example 
- new (console format)
```
2022/09/23 15:09:02.943420 +0800 INFO db/db.go:115 [PrintStats][Caller=github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db.(*catalogStatsMonitor).PostExecute]:{
"CatalogStats": {
"MaxDBID": 1002,
"MaxTID": 1027,
"MaxSID": 1004,
"MaxBID": 1004
},
"TxnStats": {
"MaxTS": [
...
2022/09/23 15:10:59.183640 +0800 ERROR frontend/routine.go:123 routine execute request failed. error:internal error: panic runtime error: invalid memory address or nil pointer dereference: goroutine 145 [running]:
runtime/debug.Stack() …
```

improve: show console log in logfile, while run bvt

---

cmd/mo-service/config.go
etc/cn-standalone-test.toml
pkg/txn/clock/hlc.go

issue #
Disable hlc offset checker by default. In clock-si's algorithm, there is no correctness problem

hlc: disable hlc offset checker by default

---

pkg/vm/engine/tae/buffer/base/types.go
pkg/vm/engine/tae/buffer/buffer_test.go
pkg/vm/engine/tae/buffer/node.go
pkg/vm/engine/tae/buffer/nodemgr.go
pkg/vm/engine/tae/txn/txnimpl/node.go

issue #
1. Change the node key from common.ID to any
2. Enhancement evict related logic
Previously, a buffer node needed to be registered first. When Pinning a node, it applies a size quota and loads data. When a node is evicted, it only unloads the data and returns back its size quota. 
Now, when a hard evictable node is evicted, it will be destroyed and then removed from the buffer manager
3. Add PinByKey, TryPinByKey and Add APIs

update buffer manager

---

pkg/catalog/types.go
pkg/frontend/session.go
pkg/sql/plan/build_ddl.go
pkg/sql/plan/build_delete.go
pkg/sql/plan/build_insert.go
pkg/sql/plan/build_load.go
pkg/sql/plan/build_show.go
pkg/sql/plan/build_update.go
pkg/sql/plan/mock.go
pkg/sql/plan/query_builder.go
pkg/txn/storage/txn/account.go
pkg/txn/storage/txn/catalog.go
pkg/txn/storage/txn/catalog_handler.go
pkg/txn/storage/txn/catalog_handler_test.go
pkg/txn/storage/txn/log_tail.go
pkg/vm/engine/tae/catalog/catalog.go
pkg/vm/engine/tae/catalog/database.go
pkg/vm/engine/tae/catalog/model.go
pkg/vm/engine/tae/catalog/table.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/db/logtail.go
pkg/vm/engine/tae/db/txn_test.go
pkg/vm/engine/tae/moengine/engine_test.go
pkg/vm/engine/tae/moengine/helper.go
pkg/vm/engine/tae/moengine/sys_relation.go
pkg/vm/engine/tae/txn/txnimpl/relation.go
pkg/vm/engine/tae/txn/txnimpl/sysblock.go
pkg/vm/engine/tae/txn/txnimpl/sysdb.go

issue #5247
maintain only one catalog definition
- move column name constants from tae/catalog to pkg/catalog
- packages (except tae) will import pkg/catalog to get catalog-related constants
- modification on some ut

refactor: use pkg/catalog in other packages

---

pkg/txn/clock/hlc.go

issue #
Disable clock max offset check not work when using now() to get current timestamp.

txn: fix clock checker

---

go.mod
pkg/config/configuration.go
pkg/util/metric/config.go
pkg/util/metric/metric_test.go

issue #
- rename param `disableMetricToProm` to `enableMetricToProm`, default disable `statusPort` listening.
- modify go.mod dependence go 1.18 -> go 1.19

default disable MetricToProm (prometheus/promhttp service)

---

pkg/vm/engine/tae/common/compress.go
pkg/vm/engine/tae/common/dlnode.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/tables/evictable/bf.go
pkg/vm/engine/tae/tables/evictable/coldata.go
pkg/vm/engine/tae/tables/evictable/colmeta.go
pkg/vm/engine/tae/tables/evictable/utils.go
pkg/vm/engine/tae/tables/indexwrapper/bfnode.go
pkg/vm/engine/tae/tables/indexwrapper/bfnode_test.go
pkg/vm/engine/tae/tables/indexwrapper/meta.go
pkg/vm/engine/tae/tables/indexwrapper/zmnode_test.go
pkg/vm/engine/tae/tables/indexwrapper/zonemapnode.go
pkg/vm/engine/tae/tables/jobs/compactblk.go
pkg/vm/engine/tae/tables/jobs/helper.go
pkg/vm/engine/tae/tables/jobs/mergeblocks.go

issue #5178 
- move Compress / Decompress to common
- don't add phyaddr data to batches when compacting and merging blocks
- generating phyaddr column when loading a ColDataNode

stop flushing phyaddr column and generate when reading

---

pkg/sql/plan/base_binder.go
pkg/sql/plan/make.go
pkg/sql/plan/visit_plan_rule.go
test/cases/prepare/prepare.test
test/result/prepare/prepare.result

issue #5285 
we will cast float constant  as decimal when build plan.
so when we execute plan by using @float_var,  we cast the @float_var's value as decimal now.
that will help us to keep the precision

fix bug:  when get @float_var then cast value as decimal

---

pkg/objectio/block.go
pkg/objectio/writer.go
pkg/objectio/writer_test.go
pkg/vm/engine/tae/tables/indexwrapper/bfnode_test.go

issue https://github.com/matrixorigin/MO-Cloud/issues/59
The buffer needs to be released at the end of WriteEnd
Because the outside may hold this writer
After WriteEnd is called, no more data can be written

Release the buffer after WriteEnd is executed

---

pkg/logservice/store.go

If there are two continuous truncate request from tae without applied index advance, and the first one is in pending state, dragonboat will return requestRejected error.
This is not a error that affects the correctness of the cluster, so just change panic to error log.
issue #
Avoid panic caused by truncation worker.

Change panic to error log in truncation worker.

---

pkg/common/morpc/backend.go
pkg/common/morpc/backend_test.go

issue #
morpc will block in the read loop, if the future has been removed

morpc: fix block in read loop if future removed

---

pkg/container/vector/vector.go
pkg/sql/colexec/expr_eval.go

issue #5772  #5754
when insert into table with column's default value.  we use NewConstNull,  that method will not set vector.data, then will panic in disttae

fix bug: insert table with default value have no vector.data

---

go.mod

issue https://github.com/matrixorigin/MO-Cloud/issues/117
The root cause is that a block in the worker of the flushblock is blocked due to the infinite loop of xorfilter.PopulateBinaryFuse8, resulting in the subsequent blocks not being flushed.
Looks like xorfilter fixed this bug in https://github.com/FastFilter/xorfilter/commit/e6a74e8548ba6e1eb0672a6c741a00d7c9734243

Update xorfilter&Fix immutable not release bug

---

pkg/taskservice/task_service.go

issue #
panic if query by primary key returns more than 1 records

taskservice: panic if query by primary key != 1

---

pkg/tests/service/service_test.go

issue #
Disable multi dn tests. Currently,  system init and task service framework not work on multi-DN node

tests: disable multi dn tests

---

cmd/mo-service/config.go
cmd/mo-service/config_test.go
cmd/mo-service/main.go
pkg/cnservice/distributed_tae.go
pkg/cnservice/server.go
pkg/cnservice/server_metadata_test.go
pkg/defines/const.go
pkg/dnservice/cfg.go
pkg/dnservice/factory.go
pkg/dnservice/store.go
pkg/dnservice/store_metadata_test.go
pkg/dnservice/store_test.go
pkg/logutil/adapt_s3.go
pkg/objectio/fs.go
pkg/objectio/writer_test.go
pkg/tests/service/fileservice.go
pkg/tests/service/service.go
pkg/txn/storage/tae/storage.go
pkg/vm/engine/disttae/engine.go
pkg/vm/engine/disttae/types.go
pkg/vm/engine/tae/dataio/blockio/reader.go
pkg/vm/engine/tae/dataio/blockio/writer.go
pkg/vm/engine/tae/db/checkpoint/replay.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/db/open.go
pkg/vm/engine/tae/options/types.go
pkg/vm/engine/tae/tables/indexwrapper/bfnode_test.go
pkg/vm/engine/tae/tables/indexwrapper/zmnode_test.go
pkg/vm/engine/tae/txn/txnimpl/txn_test.go

issue #
TAE should use the main file service or temp file service explicitly. 
Main file service name is S3, temp file service name is LOCAL.
For testing purposes, instead of setting main file service name to LOCAL, just set S3's backend to disk or mem.

dnservice: get main fs and temp fs and pass to TAE explicitly

---

pkg/cnservice/tae.go
pkg/dnservice/factory.go
pkg/logservice/client.go
pkg/logservice/client_test.go
pkg/logservice/config.go
pkg/logservice/hakeeper_client.go
pkg/logservice/hakeeper_client_test.go
pkg/logservice/service.go
pkg/logservice/service_test.go
pkg/logservice/shardinfo.go

Configure it by new parameter max-message-size in log.toml.
issue #6238 
Add a new configuration for logservice to set RPC message size max-message-size, whose default value is 100M.

[feat] logservice: make RPC message max size configurable

---

pkg/frontend/mysql_cmd_executor.go
pkg/util/trace/report_statement.go

issue #
https://github.com/matrixorigin/matrixone/issues/5675
https://github.com/matrixorigin/MO-Cloud/issues/195
1. fix record missing running status statement
2. fix metric `sql_statement_total`, `sql_statement_errors` for syntax-error sql
3. fix missing txn_id query, which failed to build ExecPlan by calling `TxnComputationWrapper::Compile`

Bugfix stmt status running and record missing txn_id

---

pkg/vm/engine/disttae/reader.go

issue #6280
still have bug in main branch.   replay like:
create table t1(a int, b int, c int primary key);
select a,c from t1 where c =xx;
in this case pkidxInColIdxs = 1   but primaryIdx = 2.   
so we can not getPkValueByExpr.(expr's ColIndx = 1)

fix point read bug

---

pkg/vm/engine/disttae/reader.go

issue #
fix bug: can't get row_id's idx
sql: update t1 set a=a+1         after flush. when get row_id's idx in Read,  can not find the index.  because Name2ColIndex have no row_id column.  so we set the idx to length of Name2ColIndex.
sql: insert into t2 values (1).   if t2 have auto_increment column.  that case,  Name2ColIndex will have row_id column.
thanks @nnsgmsone @aptend

fix bug: can't get row_id's idx

---

pkg/fileservice/local_etl_fs.go
pkg/fileservice/local_etl_fs_test.go
pkg/fileservice/local_fs.go

issue #
set IsDir to true if it's a symlink to another dir

fileservice: deref symlink in LocalETLFS.List, LocalFS.List

---

pkg/frontend/mysql_cmd_executor.go
pkg/frontend/session.go

issue #https://github.com/matrixorigin/matrixone/issues/6435
move `sql_transaction_total` and `sql_transaction_errors` count action from `Session` to `TxnHandler`

bugfix: sql_transaction metric count needs in VALID txn

---

pkg/common/morpc/backend.go
pkg/common/morpc/future.go
pkg/common/morpc/future_test.go
pkg/common/morpc/server_test.go

This reverts commit fcda32551ba7076fa24b8156b5d374da253220c1.
issue #

Revert "close all futures when close the client (#6439)"

---

pkg/fileservice/get.go
pkg/fileservice/s3_fs_test.go

issue #
Users may want to add an external table specifying the endpoint and bucket but no key or secret.

fileservice: add s3-no-key to GetForETL

---

pkg/cnservice/server_heartbeat.go
pkg/cnservice/types.go
pkg/dnservice/cfg.go

issue #
`send DNShard heartbeat` to `send CNShard heartbeat` in CN.
Modify default heartbeat timeout in CN/DN to 3 seconds.

fix cn log typo

---

pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/tables/updates/chain_test.go
pkg/vm/engine/tae/tables/updates/delete.go
pkg/vm/engine/tae/txn/txnimpl/antidepend.go
pkg/vm/engine/tae/txn/txnimpl/store.go
pkg/vm/engine/tae/txn/txnimpl/table.go
pkg/vm/engine/tae/txn/txnimpl/txn_test.go
pkg/vm/engine/tae/txn/txnimpl/txndb.go

issue #6049 #6333 #6514 
1. Fix persisted appendable block dedup overkill
2. Change the txn dedup behavior before committing
3. Do not transfer deletes before committing due to snapshot isolation constraints

transfer deletes if the target block was compacted - phase 2

---

go.mod
go.sum
pkg/common/morpc/codec.go
pkg/common/morpc/codec_header.go
pkg/common/morpc/codec_test.go
pkg/frontend/server.go

issue #
Our goetty's encoder will hold some buffer internal indexes externally, and these indexes will change after buf expansion, causing the encoded data to be misaligned

morpc: fix encoding error after goetty buffer expansion

---

pkg/vm/engine/tae/dataio/blockio/read.go

issue #6352 
The rootcause is that the internal read block of tae uses mpool,since the vector of the computing layer does not support serialization and deserialization based on mpool #5937, the computing layer cannot free these data. So you need tae to free yourself

Fix the bug of BlockRead causing mpool oom

---

pkg/cnservice/types.go

issue #
Make cnservice's engine uses the appropriate default configuration

cnservice: use disttae and logservice ad default

---

pkg/vm/engine/disttae/partition.go
pkg/vm/engine/disttae/reader.go

issue #6469 
refactor for PR 6462 which to solve data race bug in NewReader.
the bug root cause:
1、we will make multi preScopes in compile.compileMinusAndIntersect/compileUnion/compileGroup for performance
2、multi compile.preScopes will make multi scope.ParallelRun call.  then we will get multi Reader which share one relation(another name is table) in one transaction.
3  in blockMergeReader.Read we will get the share relation's attribute (table.meta.modifedBlocks[i].deletes) to filter rows.
but while filter rows, we do a wrong action, we modify the attribute.  because multi readers exists and do Read in the same time,  data race happed!
after discuss with @nnsgmsone .  we think multi reader in one txn is necessary for performance. but reader modify share data is not allowed.  so i change …

refactor: solve data race bug in NewReader in another way

---

pkg/vm/engine/tae/tables/jobs/compactblk.go
pkg/vm/engine/tae/txn/txnimpl/table.go

issue #6049 
Recur transfer deletes to handle block compacted more than once

enhance rw fix to recur transfer deletes

---

pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/iface/data/block.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/tables/updates/delete.go
pkg/vm/engine/tae/txn/txnimpl/block.go
pkg/vm/engine/tae/txn/txnimpl/table.go

issue #6562 
1. dedup by maxts when preprepare.
2. prepare delete node in mergeblocks when create.
3. consume rowmask when dedup.

fix delete in merge and enable delete3

---

pkg/sql/plan/build_test.go
pkg/sql/plan/mock.go
pkg/sql/plan/mysql_compatibility.go
pkg/sql/plan/query_builder.go

This affects behavior of queries with aggregation. When sql_mode doesn't contain ONLY_FULL_GROUP_BY, which is the default before mysql 8.0, columns that doesn't appear in GROUP BY clause or aggregate function will be automatically wrapped in an any_value aggregate.
Temporarily we use sql_mode, but after #6606 is implemented, we will shift to use mysql_compatibility_mode for all mysql compatibility issues.
issue #6604

Add a mysql compatibility mode

---

go.mod
go.sum

issue #6526, #6542, https://github.com/matrixorigin/MO-Cloud/issues/235
If there are many logs need to replay when restart, it will take long time to replay logs because for every index entry, file is opened. And it causes timeout panic in tae to get logservice client as there is no leader elected before the logs are all replayed.
Replace db.getEntries() with a higher performance one in dragonboat/tan. The new one does not support multiplexed collection which is not used.
The original version almost open log file for each index entry which cause low performance.
The new version open file and keep reading log entries until we get a unavailble log entry identified by
(ies[passed].pos-offset)%blockSize != 0. And then reopen the log file from the position of latest index entry. The read …

[bug] fix bug #6526 that mo cannot restart.

---

pkg/vm/engine/disttae/txn.go
pkg/vm/engine/disttae/types.go
pkg/vm/engine/disttae/util.go
pkg/vm/engine/disttae/util_test.go
test/cases/dml/select/select.test
test/distributed/cases/dml/select/select.test
test/distributed/result/dml/select/select.result
test/result/dml/select/select.result

issue #
fix bug: computeRangeByIntPk will oom.
change the compute logic, these change will use less mem. but not support less expr.
may be we can improve this function in the future.

Fix compute range by int pk oom  for 0.6

---

CODEOWNERS
pkg/common/log/doc.go
pkg/common/log/example_log_test.go
pkg/common/log/filter.go
pkg/common/log/filter_test.go
pkg/common/log/logger.go
pkg/common/log/types.go

issue #5048 
Add log framework. Printing logs using the Log package enables the following functions:
1. Uniform logger name
2. Support search all logs by service's uuid.
3. Support search the operation logs of all related processes by process ID, e.g.
search all logs of that transaction by transaction.
4. Sampling and printing of frequently output logs.
5. One line of code to add a time consuming log to a function.
6. Support for using the mo_ctl function to control log printing.

log: add a log printing framework

---

pkg/vm/engine/tae/common/generator.go
pkg/vm/engine/tae/common/hack.go
pkg/vm/engine/tae/common/hack_test.go
pkg/vm/engine/tae/containers/vecbase.go
pkg/vm/engine/tae/containers/vecimpl.go
pkg/vm/engine/tae/containers/vector_test.go
pkg/vm/engine/tae/stl/containers/stdvec.go
pkg/vm/engine/tae/stl/containers/strvec.go
pkg/vm/engine/tae/stl/containers/vector_test.go
pkg/vm/engine/tae/stl/types.go

For better performance.
+1000x faster than the current implementation if apply many deletes to a vector
Approved by: @LeftHandCold
issue #

[cherry pick]: revisit and optimize vector deletion operation (#6704)

---

pkg/sql/compile/compile.go
pkg/sql/compile/types.go

issue #
A very simple improvement to modify the parallelism of the pipeline by cost. The current design is simple and assumes that a core needs to process at least 100w rows of data. A more systematic approach will be adopted later.

Adjust the parallelism of the pipeline according to the cost

---

pkg/hakeeper/checkers/logservice/parse.go
pkg/hakeeper/checkers/logservice/parse_test.go
pkg/vm/engine/tae/logstore/driver/logservicedriver/appender.go

When hakeeper decides to remove replicas, make sure the leader replica is the last one, which means we should remove follower replicas first.
In addition, add a slow log in appender.
issue #

[Enhancement] Optimize the checker of logservice in hakeeper.

---

pkg/fileservice/lru.go
pkg/fileservice/mem_cache.go

issue #
lru.Get(key) in memcache.Read does not initialize ObjectSize, so that the 'replace' of lru.Set only reduces size and does not add size, and finally lru memory leaks

Fix fileservice lru memory leak bug

---

pkg/vm/engine/tae/txn/txnimpl/node.go

issue #
Previously it always allocated a MaxNodeRows for any txn insertion, which was not friendly to high concurrent small transactions.

optimize for high concurrent small insert

---

pkg/logservice/message.go
pkg/vm/engine/tae/logstore/driver/logservicedriver/appender.go

issue #6745
Print a pointer to the data where the race occurred, in the event of a race, the check can analyse the relevant logs

logservice: add more debug log for logsservice

---

pkg/sql/colexec/external/external.go
pkg/sql/colexec/external/external_test.go

issue #6865 
1, use the go package **filepath** handling the complicate file path.

fix filepath

---

pkg/common/morpc/backend.go
pkg/common/morpc/backend_test.go
pkg/common/morpc/future.go
pkg/common/morpc/future_test.go

issue #6745
If context' deadline is before  write request, it maybe cause data  race

morpc: make future get after write loop handled

---

cmd/mo-service/main.go
pkg/util/trace/trace.go
pkg/util/trace/trace_test.go

issue #https://github.com/matrixorigin/matrixone/issues/7017
fix mo panic while do normally shutdown or got kill signal
- use context.Background() with timeout as shutdown context
- add ut cover trace.Shutdown() with cancled context

bugfix: shutdown trace meet error panic

---

pkg/vm/engine/tae/options/types.go

Default to 8K rows per block.  Might have something to do with both ap/tp perf and metadata cache size.
issue #

Change rows per block and blocks per seg.

---

pkg/sql/plan/base_binder.go
pkg/sql/plan/utils.go

issue #6870
when column compare constant, we should cast constant instead of column.
for char/varchar type, if the length of constant is shorter than column, we can cast constant only

[Bug]: mo's scan with predicate is slower than clickhouse #6870

---

pkg/util/export/merge.go
pkg/util/export/merge_test.go
pkg/util/export/table/table.go

issue #7040, #7218, 
simdcsv.Read may return nil buffer and nil error, while context is Done, in Mac dev.
- check nil buffer return value, even if err == nil. see more in ContentReader.ReadLine(...)
- improve all note output in merge.go

bugfix: panic issue if simdcsv.Read return nil buffer and err is nil

---

pkg/frontend/mysql_cmd_executor.go
pkg/frontend/mysql_cmd_executor_test.go
pkg/sql/plan/explain/explain_query.go
pkg/util/export/table/table.go
pkg/util/trace/buffer_pipe_test.go
pkg/util/trace/report_statement.go
pkg/util/trace/report_statement_test.go
pkg/util/trace/schema.go

issue #https://github.com/matrixorigin/matrixone/issues/6596
record query explain's global stats in table statment_info's individual column, like `statement_info.stats`
- example
```
mysql> select statement_id, statement, stats from system.statement_info where json_unquote(json_extract(exec_plan, '$.code')) = 0 limit 10\G
*************************** 1. row ***************************
statement_id: 5860eaec-8d7f-11ed-ad54-3ebf9f3960c8
statement: show tables
stats: {"statistics": {"IO": [{"name": "Disk IO", "unit": "byte", "value": 0}, {"name": "S3 IO", "unit": "byte", "value": 3619}], "Memory": [{"name": "Memory Size", "unit": "byte", "value": 66}], "Network": [{"name": "Network", "unit": "byte", "value": 0}], "Throughput": [{"name": "Input Rows", "unit": "count", "value": 68}, {"name": …
```

statemetn_info record stats json

---

pkg/fileservice/file_service_test.go
pkg/fileservice/local_etl_fs.go
pkg/fileservice/local_fs.go

fileservice: do not check IOEntry.Size when reading to the end of file in LocalFS/LocalETLFS.Read

---

pkg/fileservice/config.go
pkg/fileservice/disk_cache.go
pkg/fileservice/disk_cache_test.go
pkg/fileservice/file_service.go
pkg/fileservice/file_service_test.go
pkg/fileservice/io_entry_test.go
pkg/fileservice/local_etl_fs.go
pkg/fileservice/local_fs.go
pkg/fileservice/mem_cache.go
pkg/fileservice/mem_cache_test.go
pkg/fileservice/memory_fs.go
pkg/fileservice/path.go
pkg/fileservice/s3_fs.go
pkg/fileservice/s3_fs_test.go
pkg/fileservice/vector.go

issue #6943 
fileservice: set S3 mem cache defaultly
fileservice: rename IOEntry.ignore to done
fileservice: refactor cache process
fileservice: add disk cache configs
fileservice: use disk cache in S3
fileservice: implement DiskCache.Read

fileservice: add disk cache

---

pkg/fileservice/file_service_test.go
pkg/fileservice/io_entry.go
pkg/fileservice/io_entry_test.go
pkg/fileservice/local_etl_fs.go
pkg/fileservice/local_fs.go
pkg/fileservice/memory_fs.go
pkg/fileservice/mutable_file_service_test.go
pkg/fileservice/replaceable_file_service_test.go
pkg/fileservice/s3_fs.go
pkg/fileservice/s3_fs_test.go
pkg/frontend/query_result_test.go
pkg/sql/colexec/external/external_test.go
pkg/util/export/merge_test.go

issue #
Check context done in methods to ensure that error is returned when the context is canceled

fileservice: check context done in methods

---

pkg/vm/engine/tae/logtail/service/server.go
pkg/vm/engine/tae/logtail/service/service_test.go

issue #6894
The debug log should be under control, and we must change the default logger for `logtail server`.

Take global logger as the default logger for logtail server

---

pkg/dnservice/factory.go
pkg/txn/storage/tae/storage.go
pkg/vm/engine/tae/logtail/service/server.go
pkg/vm/engine/tae/logtail/service/service_test.go
pkg/vm/engine/tae/logtail/service/session.go
pkg/vm/engine/tae/logtail/service/session_test.go

issue #6894
The log should be under control, and we take dnservice's logger for tae engine's logtail server.

Take dnservice's logger for tae engine's logtail server

---

pkg/fileservice/file_service_bench_test.go
pkg/fileservice/s3_fs_test.go

issue #
We don't want to test the cache in S3 tests.

fileservice: disable caches in S3 tests

---

pkg/util/export/batch_processor.go

issue #https://github.com/matrixorigin/matrixone/issues/7629
fix bvt found data race issue.
- found at https://github.com/matrixorigin/matrixone/actions/runs/3890422599/jobs/6639527529
- data race
```
2023-01-11T07:02:29.6342071Z WARNING: DATA RACE
2023-01-11T07:02:29.6342271Z Write at 0x00c00007e078 by goroutine 14:
2023-01-11T07:02:29.6342414Z   ??()
2023-01-11T07:02:29.6342695Z       -:0 +0xd7b434
2023-01-11T07:02:29.6342926Z   sync/atomic.CompareAndSwapInt32()
2023-01-11T07:02:29.6343172Z       <autogenerated>:1 +0x18
2023-01-11T07:02:29.6343555Z   github.com/matrixorigin/matrixone/pkg/util/export.(*dummyBuffer).ShouldFlush()
2023-01-11T07:02:29.6344108Z       /runner/_work/matrixone/matrixone/pkg/util/export/batch_processor_test.go:107 +0x3c
2023-01-11T07:02:29.6344466Z …
```

bugfix: data trace on bufferHolder.buffer

---

pkg/common/morpc/backend.go
pkg/common/morpc/backend_test.go

issue #7678 
The stream object in morpc is reusable, but lastReceivedSeqence is not reset at reset, so the match detection of seqence does not pass, resulting in some messages being lost.

morpc: reset last received seqence in stream

---

cmd/mo-service/debug.go
cmd/mo-service/main.go
go.mod
go.sum
pkg/fileservice/disk_cache.go
pkg/fileservice/local_fs.go
pkg/fileservice/mem_cache.go
pkg/fileservice/profile.go
pkg/fileservice/profile_test.go
pkg/fileservice/s3_fs.go
pkg/fileservice/s3_fs_test.go

issue #
mo-service: add /debug/fs/ http handler
fileservice: add s3 profile point
mo-service: add file-service-profile
Usage:
method 1: start `mo-service` with `-file-service-profile <file path>`, after the program exit, the profile will be written to `<file path>`
method 2: start `mo-service` with `-debug-http :9876`, and open profile with `go tool pprof -http :9999 'http://localhost:9876/debug/fs?seconds=120'`

fileservice: add profiler

---

pkg/lockservice/lock_table.go
pkg/lockservice/service.go
pkg/lockservice/txn.go
pkg/lockservice/txn_test.go
pkg/lockservice/types.go

issue #7066 
According to our [design](https://github.com/matrixorigin/docs/blob/main/design/pessimistic_txn.md), this make locktable as a interface, and rename origin implemention to localLockTable

lockservice: make locktable as interface

---

CODEOWNERS
pkg/clusterservice/cluster.go
pkg/clusterservice/cluster_test.go
pkg/clusterservice/selector.go
pkg/clusterservice/selector_test.go
pkg/clusterservice/types.go
pkg/logservice/hakeeper_client.go
pkg/pb/metadata/metadata.go
pkg/pb/metadata/metadata.pb.go
proto/metadata.proto

issue #7066 
Abstracts the cluster information service for future caching of all cluster-level metadata for routing, fetching service metadata, etc. Clusterservice has one and only one instance on each cn and dn

Add cluster cache

---

pkg/logservice/shardinfo.go

If failover happens, logservice heartbeat cannot work anymore it cannot get HAKeeper client.
See #8154 for more details.
issue #8154
1. 这个bug只在k8s环境中才会有，因为发生在 GetShardInfo() 中
2. 以3节点为例，当logservice 的一个节点failover，旧的pod被删掉，新的pod加入集群，同时gossip也会对logservice集群做同样的操作
3. 此时，整个集群中的节点为3个，包括2个旧的和1个新的；但是logservice的副本虽然也是3个，但是都是旧的，因为logservice的副本的删除/增加是通过HAKeeper中判断各副本的心跳tick来完成
4. 但是logservice副本无法完成心跳操作，因为在获取 HAKeeper client的时候，GetShardInfo() 中会尝试比较节点和副本的状态，如果状态不一致，就返回错误了，就导致了集群心跳完全停止了
5. 解决办法是，在比较节点和副本的状态时，信息对不上的忽略，只返回匹配上的副本，通过这些副本建立HAKeeper client连接，完成心跳发送，从而完成logservice 副本的删除/增加操作。

logservice: fix bug #8154, logservice not working if failover happens.

---

pkg/vm/engine/tae/logtail/logtailer.go
pkg/vm/engine/tae/logtail/service/server.go

issue #6894
There were some interval spikes when receiving response from DN service.
We've noticed that it isn't stable when fetching incremental log tail.
This PR change the way of log tail fetching with an optimization of complexity: from `O(N*M)` to `O(D*M)`
> `N` is the number of subscribed tables
> `D` is the number of dirty tables
> `M` is the cost for log tail fetching

Improve publishment performance and stability

---

pkg/sql/plan/utils.go

issue #
check if no need to cast double column when compared to int constant
improve the performance of ssb benchmark

check if no need to cast double column when compared to int constant

---

CODEOWNERS
cmd/mo-service/config.go
pkg/fileservice/cache.go
pkg/fileservice/caching_file_service.go
pkg/fileservice/caching_file_service_test.go
pkg/fileservice/config.go
pkg/fileservice/counter.go
pkg/fileservice/disk_cache.go
pkg/fileservice/disk_cache_test.go
pkg/fileservice/example_test.go
pkg/fileservice/file_services_test.go
pkg/fileservice/local_fs.go
pkg/fileservice/local_fs_test.go
pkg/fileservice/mem_cache.go
pkg/fileservice/s3_fs.go
pkg/fileservice/s3_fs_test.go
pkg/objectio/fs.go
pkg/objectio/writer_test.go
pkg/perfcounter/context.go
pkg/perfcounter/counter.go
pkg/perfcounter/update.go
pkg/perfcounter/update_test.go
pkg/tests/service/fileservice.go
pkg/util/export/etl/csv_test.go
pkg/util/export/etl/tae_test.go
pkg/vm/engine/tae/dataio/blockio/writer_test.go
pkg/vm/engine/tae/rpc/rpc_test.go
pkg/vm/engine/tae/tables/indexwrapper/bfnode_test.go
pkg/vm/engine/tae/tables/indexwrapper/zmnode_test.go
pkg/vm/pipeline/pipeline.go

issue #
fileservice: optimize counter updating
fileservice: remove CacheStats
fileservice: make counters in context maps
fileservice: add CachingFileService.CacheCounter

fileservice: replace CacheStats with perfcounter 

---

pkg/common/morpc/server_test.go

issue #8278 
TestServerTimeoutCacheWillRemoved has too small timeout, and ci is too slow, may make test failed

morpc: fix TestServerTimeoutCacheWillRemoved

---

pkg/fileservice/s3_fs.go
pkg/fileservice/s3_fs_test.go

fileservice: use ListObjects instead of ListObjectsV2 in s3

---

pkg/fileservice/cache.go
pkg/fileservice/caching_file_service_test.go
pkg/fileservice/disk_cache.go
pkg/fileservice/disk_cache_test.go
pkg/fileservice/file_service.go
pkg/fileservice/file_service_test.go
pkg/fileservice/file_services.go
pkg/fileservice/io.go
pkg/fileservice/local_etl_fs.go
pkg/fileservice/local_fs.go
pkg/fileservice/mem_cache.go
pkg/fileservice/memory_fs.go
pkg/fileservice/s3_fs.go
pkg/fileservice/s3_fs_test.go
pkg/fileservice/sub_path.go
pkg/perfcounter/counter_logexporter.go
pkg/perfcounter/counter_set.go

issue #
fileservice: cache types renaming and sketch FileContentCache
fileservice: implement FileContentCache for DiskCache; implement Preload for S3FS
perfcounter: add disk cache get/set file content fields
fileservice: use full-data file in DiskCache.Read/Update
fileservice: more disk cache tests and bug fixes
fileservice: add disk cache file stat counter field
fileservice: refactor FileContentCache interface
fileservice: add concurrency control to DiskCache.SetFileContent

fileservice: add FileService.Preload

---

pkg/container/vector/vector_test.go
pkg/vm/engine/tae/containers/utils.go
pkg/vm/engine/tae/containers/vector_test.go
pkg/vm/engine/tae/dataio/blockio/read.go

issue #
Reusing CN vector CloneWindow, to mimic CloneMOVec() functionality.
https://github.com/matrixorigin/matrixone/commit/4322ac6b9603f76b0dac339feb3d61b0e209e8bd#r106062041

[Improvement] Replace dnVec.CloneMOVec() with cnVec.CloneWindow()

---

pkg/fileservice/disk_cache.go
pkg/fileservice/disk_cache_test.go
pkg/perfcounter/counter_set.go

issue #8723 
fileservice: ignore disk write error in disk cache; add .mofscache extension to disk cache files
fileservice: add DiskCache.collect and evict
fileservice: add DiskCache eviction

fileservice: add DiskCache eviction

---

pkg/sql/colexec/lockop/fetch.go
pkg/sql/colexec/lockop/fetch_test.go

issue #7066 
Get min and max value in lock operator, and not depend on  sort operator

lockop: get min and max value in lock op

---

pkg/fileservice/config.go
pkg/fileservice/disk_cache.go
pkg/fileservice/disk_cache_test.go
pkg/fileservice/example_test.go
pkg/fileservice/file_services_test.go
pkg/fileservice/local_fs.go
pkg/fileservice/local_fs_test.go
pkg/fileservice/mem_cache.go
pkg/fileservice/profile_test.go
pkg/fileservice/s3_fs.go
pkg/perfcounter/counter_set.go
pkg/tests/service/fileservice.go
pkg/util/export/etl/csv_test.go

issue #8723 
fileservice: add disk cache to LocalFS
fileservice: fix disk and memory cache path
fileservice: naming fixes
fileservice: use symlink in disk cache
fileservice: add disk cache eviction logs
fileservice: disable disk caches for LocalFS

fileservice: disk cache evict fixes

---

pkg/sql/plan/opt_misc.go
pkg/sql/plan/query_builder.go
pkg/sql/plan/stats.go

On top of each subquery or view, there is a PROJECT node. It's unnecessary and will interfere various optimizer rules, such as join order and aggregate push-down/pull-up. This commit removes most of that kind of PROJECT node, but some are retained to avoid intricate issues.
issue #

[Opt] Remove unnecessary PROJECT nodes from plan

---

pkg/fileservice/cache.go
pkg/fileservice/disk_cache.go
pkg/fileservice/io_entry.go
pkg/fileservice/local_fs.go
pkg/fileservice/local_fs_test.go

issue #8866 
fileservice: add LocalFS with disk cache tests
fileservice: fix DiskCache.Read
fileservice: add IOEntry.ReadFromOSFile

fileservice: use one file per IOEntry in disk cache

---

pkg/container/batch/batch.go
pkg/container/batch/batch_test.go
pkg/frontend/export.go
pkg/sql/colexec/connector/connector.go
pkg/sql/colexec/constraint_util.go
pkg/sql/colexec/dispatch/dispatch.go
pkg/sql/colexec/order/order.go
pkg/sql/colexec/projection/projection.go
pkg/sql/colexec/table_function/meta_scan.go
pkg/sql/compile/scopeRemoteRun.go
pkg/testutil/util_debug.go
pkg/vm/engine/disttae/partition_reader.go
pkg/vm/engine/disttae/reader.go
pkg/vm/engine/memoryengine/table_reader.go
pkg/vm/engine/tae/moengine/reader.go

issue #8741 
1. add some log with debug level.
2. fix a pipeline bug that will early free vector while doing the dup.

fix issue 8741 that connector operator early free the vector before dup and cause crash finally

---

pkg/config/configuration.go
pkg/util/export/batch_processor.go

issue #https://github.com/matrixorigin/matrixone/issues/8391
bug reason like https://github.com/matrixorigin/matrixone/issues/8391#issuecomment-1510974911
fix here: make  etl collect buffer cnt default: no limit.

bugfix: etl collect buffer cnt default: no limit

---

pkg/frontend/util.go
pkg/sql/plan/deepcopy.go
pkg/sql/plan/distinct_agg.go
pkg/sql/plan/having_binder.go
pkg/sql/plan/query_builder.go
pkg/sql/plan/stats.go
pkg/sql/plan/visit_plan.go

For TPCH q16 SF=10, it reduces time cost from 2.3s to 0.9s, and eliminates 4.3GB memory allocation on hashtable.
TPCH q16 SF=100 is now runnable on 32GB memory machine.
issue #9049

[Opt] Transform count distinct into 2 agg nodes

---

pkg/cnservice/server.go
pkg/cnservice/types.go
pkg/common/moerr/error.go
pkg/common/moerr/error_no_ctx.go
pkg/sql/colexec/lockop/lock_op.go
pkg/sql/colexec/lockop/lock_op_test.go
pkg/txn/client/client.go
pkg/txn/client/client_feature.go
pkg/txn/client/client_feature_test.go
pkg/txn/client/types.go

issue #7066 
In RC mode, when a conflict occurs, if the refresh expression feature is not turned on, then a transaction retry error is returned and then the entire sql needs to be re-executed here in the execution.

lockop:  return retry error if refresh expr not enabled

---

pkg/frontend/mysql_protocol.go
pkg/frontend/variables.go
pkg/proxy/client_conn.go
pkg/proxy/client_conn_test.go
pkg/proxy/conn_manager_test.go
pkg/proxy/counter_set.go
pkg/proxy/event.go
pkg/proxy/event_test.go
pkg/proxy/handler.go
pkg/proxy/handler_test.go
pkg/proxy/label_info.go
pkg/proxy/mysql_conn_buf.go
pkg/proxy/rebalancer_test.go
pkg/proxy/router.go
pkg/proxy/router_test.go
pkg/proxy/server_conn.go
pkg/proxy/server_conn_test.go
pkg/proxy/tunnel.go

Add session variable cn_label fro pipelien and keep session variables and user variables when transfer connection between CN servers.
issue #9079

[feat] proxy: add session variable for pipeline.

---

pkg/objectio/writer.go
pkg/vm/engine/tae/blockio/writer_test.go

issue #
Add offset and compressed size and original size info for Object's ColumnMeta

Add Location for Object's ColumnMeta

---

pkg/clusterservice/cluster.go
pkg/hakeeper/rsm_test.go
pkg/logservice/hakeeper_client_test.go
pkg/logservice/service_test.go
pkg/logservice/store_test.go
pkg/pb/logservice/logservice.go
pkg/pb/logservice/logservice.pb.go
pkg/pb/logservice/logservice_test.go
proto/logservice.proto

issue #9275 
修改更新 cn label 的接口行为，移除 Delete 操作，只保留 Set 操作，每次 update 时更新全量的 cn label 信息。

[refactor] hakeeper: Change the behavior of updating cn label.

---

pkg/common/hashmap/iterator.go
pkg/container/hashtable/bucket.go
pkg/container/hashtable/hash.go
pkg/container/hashtable/hash_amd64.go
pkg/container/hashtable/hash_amd64.s
pkg/container/hashtable/hash_arm64.go
pkg/container/hashtable/hash_arm64.s
pkg/container/hashtable/int64_hash_map.go
pkg/container/hashtable/string_hash_map.go

Total memory allocation in hash table reduced from 39.6GB to 25.3GB for TPCH Q18 SF=100.
issue #9380

Resize multi-block hash table in place

---

pkg/frontend/computation_wrapper.go
pkg/frontend/session.go
pkg/frontend/test/engine_mock.go
pkg/sql/compile/compile.go
pkg/sql/compile/compile_test.go
pkg/sql/compile/scope_test.go
pkg/sql/compile/types.go
pkg/vm/engine/disttae/engine.go
pkg/vm/engine/entire_engine.go
pkg/vm/engine/entire_engine_test.go
pkg/vm/engine/memoryengine/binded.go
pkg/vm/engine/memoryengine/engine.go
pkg/vm/engine/types.go

When get cn node list in compile phase, filter the nodes by cn label, which is stored in session variable "cn_label".
issue #9080

[feat] determine the range of CNs for pipeline.

---

pkg/proxy/client_conn.go
pkg/proxy/client_conn_test.go
pkg/proxy/conn_manager.go
pkg/proxy/event.go
pkg/proxy/event_test.go
pkg/proxy/handler_test.go
pkg/proxy/mysql_conn_buf.go
pkg/proxy/plugin_test.go
pkg/proxy/router.go
pkg/proxy/server_conn.go
pkg/proxy/server_conn_test.go
pkg/proxy/tunnel.go
pkg/proxy/util.go
test/distributed/cases/dml/insert/insert.result
test/distributed/cases/dml/insert/insert.test

If suspend or drop account is requested, kill all connections that belongs to this account.
issue #8167

[feat]: kill connected session if account suspended or dropped.

---

pkg/vm/engine/tae/logtail/service/client.go

issue #
The logtail client will close the stream when it encounters an error. if the stream's server is still sending messages to the stream, it will fill up the stream's channal and cause a deadlock when it closes.

fix logtail hung in close stream

---

pkg/sql/plan/explain/explain_expr.go

issue #
change the output of explain to this: Filter Cond: (lineorder.lo_discount >= 1)
instead of this:  Filter Cond: (lineorder.lo_discount >= 1.0000000000000000000000000000000000000000000000000000000000000000)

fix the output of explain

---

pkg/proxy/client_conn.go
pkg/proxy/event.go
pkg/proxy/event_test.go
pkg/proxy/ppv2.go
pkg/proxy/ppv2_test.go
pkg/proxy/server.go
pkg/proxy/tunnel.go

Send the drop account statement to backend directly instead of execute it in a new connection. And whatever its result is, trigger the kill connection operation.
issue #

[refactor] proxy: change the action of drop account.

---

test/distributed/cases/result_count/result_count.result
test/distributed/cases/result_count/result_count.sql
test/distributed/cases/sql_source_type/sql_source_type.result
test/distributed/cases/sql_source_type/sql_source_type.sql
test/distributed/cases/statement_query_type/prepare.result
test/distributed/cases/statement_query_type/prepare.sql
test/distributed/cases/statement_query_type/statement_query_type.result
test/distributed/cases/statement_query_type/statement_query_type.sql

issue #https://github.com/matrixorigin/matrixone/issues/9425
use new account to exec those case, to avoid `user dump` sql affect.
Then these case can run success in local dev, not just in CI bvt.

fix bvt case remove mo-tester exec mo_ctl records

---

pkg/vm/engine/tae/db/checkpoint/runner.go

issue #9578 
In a poor working env, it will take more than 30s to flush all data into the object storage. Here change the timeout from 30s to 90s

change the default timeout of force flush time from 30s to 90s

---

.dockerignore
.github/workflows/e2e-compose.yml
.gitignore
Makefile
etc/launch-tae-compose/compose.yaml
etc/launch-tae-compose/config/log.toml
optools/compose_bvt/Dockerfile.tester
optools/compose_bvt/compose_bvt.sh
optools/compose_bvt/entrypoint.sh

issue #
1. add 'make compose' and 'make compose-clean'  command
2. change the method of export log in e2e-cmpose.yaml by modify image entrypoint

CI: add 'make compose' and 'make compose-clean', modify e2e-compose workflow

---

pkg/vm/engine/tae/blockio/read.go

issue #
The rowid is generated by encoding and is not stored in the fileservice cache, so there is no need for blockreader to copy it

Avoid copying rowid in blockreader

---

pkg/lockservice/lock_table_local.go
pkg/lockservice/service.go

issue #
events workers started when every local lock table created, it makes goroutines leak. it must be only start one times.

fix locktable events workers leak

---

pkg/lockservice/lock_table_local.go
pkg/lockservice/lock_table_local_test.go
pkg/lockservice/service_test.go
pkg/lockservice/test_helper.go

issue #
may lost locks in below flow:
1. txn1 hold row1
2. txn2/op1 lock row1 will wait txn1 on row1
3. txn2/op2 lock row1 and row2 will add into txn2/op1's same txn list, also wait on row1
4. txn1 unlock, and txn1/op1 added lock row1
5. txn1/op2 will missing row2

fix lock multi-rows may lost if current lock found

---

pkg/lockservice/lock_table_local.go
pkg/lockservice/lock_table_local_test.go
pkg/lockservice/txn.go
pkg/lockservice/waiter.go
pkg/lockservice/waiter_test.go

issue #
Add a new status "ready" to waiter status to avoid received a invalid notify. The notify can only at blocking status.

lockservice: add ready status to waiter to avoid invalid notify

---

pkg/pb/txn/txn.go

issue #
txn may return context.DeadlineExceeded error. 
Wrap should handle this error instead of just panic.

txn.WrapError handles all types of errors

---

pkg/incrservice/cfg.go
pkg/incrservice/column_cache.go
pkg/incrservice/column_cache_test.go
pkg/incrservice/store_mem.go

issue #
For the load scenario, if the machine is good enough, there will be very many goroutines to concurrently fetch the value of the auto-increment column, which will immediately trigger the cache of the auto-increment column to be insufficient and thus go to the store to allocate a new cache, which causes the load to block all due to this allocation being slow. The idea of our optimization here is to reduce the number of allocations as much as possible, add an atomic counter, check how many concurrent requests are waiting when allocating (of course this is imprecise, but it doesn't matter), and then allocate more than one at a time.

improve auto-increment in load scene

---

pkg/common/mpool/mpool.go
pkg/vm/engine/disttae/partition_reader.go
pkg/vm/engine/disttae/txn_table.go

issue #9732
* since the current mpool detection does not take competition into account, there may be some double free missed, and eventually mo will encounter the free > alloc error
* add some missing free

Fix the bug of double free detection in mpool

---

pkg/vm/engine/disttae/reader.go

issue #9309 
1. Remove low-efficient deletes related logic
2. Pass external deletes into block read API

(disttae): some code change to blockMergeReader for deletes

---

pkg/container/nulls/nulls.go
pkg/container/vector/utils.go
pkg/container/vector/utils_test.go
pkg/vm/engine/disttae/reader.go
pkg/vm/engine/disttae/txn_table.go
pkg/vm/engine/disttae/types.go
pkg/vm/engine/disttae/util.go
pkg/vm/engine/disttae/util_test.go

issue #9309 
Support composite primary key filter when read a block, which will reduce the allocation of memory. 
in my local test, the tpcc performance will be improved by more than 100%.
TODO:
There is a partionReader, which now dominates the performance of tpcc, and it will be optimized in the next PRs

improve tpcc performance a lot by supporting composite primary key filter

---

pkg/sql/compile/scopeRemoteRunTypes.go

issue #9842
change HandleNotifyTimeout  from 60s to 120s.
not a root fix, but tpch 100g can run eks with 2cn

[Bug]: q21 of tpch_100g report 'internal error: send notify msg to dispatch operator timeout' on eks with 2*cn

---

pkg/vm/engine/disttae/engine.go
pkg/vm/engine/disttae/txn_database.go
pkg/vm/engine/disttae/txn_table.go

issue #9309 
1. Prefix scan the in-memory primary index for composite primary keys
2. Remove the internal error trace for each txn

improve tpcc performance by prefix scan

---

pkg/dnservice/factory.go
pkg/txn/storage/tae/storage.go
pkg/vm/engine/tae/db/open.go
pkg/vm/engine/tae/options/types.go
pkg/vm/engine/tae/txn/txnbase/command.go
pkg/vm/engine/tae/txn/txnimpl/cmdmgr.go
pkg/vm/engine/tae/txn/txnimpl/command_test.go
pkg/vm/engine/tae/txn/txnimpl/store.go
pkg/vm/engine/tae/txn/txnimpl/txn_test.go

issue #9647 
If there are too many cmds, the message size will be too large to send out by RPC. So split it by max-message-size in config.

[bug] dn: split commands in case it is too large for RPC message.

---

pkg/sql/plan/function/func_mo.go
test/distributed/cases/dml/show/database_statistics.result
test/distributed/cases/dml/show/database_statistics.sql

issue #8312
`mo_table_size` and `mo_table_rows` supports operations on partition table:
mo_table_size. the table size is equal to the sum of the partition tables.
mo_table_rows. the table rows is equal to the sum of the partition tables.

partition table support `mo_table_size`,`mo_table_rows`

---

pkg/vm/engine/tae/logtail/service/response.go
pkg/vm/engine/tae/logtail/service/session.go

issue #9862
If dn releases `logtail.MessageSegment` on morpc error, there would be panic from morpc side.

Fix dn crash

---

pkg/common/morpc/client.go
pkg/common/morpc/server_test.go

issue #9896
`Ping` returns error when err is not nil and the error is not `backendClosed` error

fix cn ping panic

---

pkg/vm/engine/tae/db/replay.go
pkg/vm/engine/tae/logstore/driver/logservicedriver/driver.go
pkg/vm/engine/tae/logstore/driver/logservicedriver/replay.go
pkg/vm/engine/tae/logtail/service/session.go

issue #
Update logs.
Count the number of WAL entries when replay.

print the number of WAL entries when replay

---

pkg/incrservice/allocator.go
pkg/incrservice/allocator_test.go
pkg/incrservice/column_cache.go
pkg/incrservice/column_cache_test.go
pkg/incrservice/service.go
pkg/incrservice/service_test.go
pkg/incrservice/store_mem.go
pkg/incrservice/store_sql.go
pkg/incrservice/table_cache.go
pkg/incrservice/types.go
pkg/sql/colexec/preinsert/preinsert.go

issue #9914 
Make incrservice using external txn in all ops.  And returns pretty error if table dropped

make incrservice using external txn in all ops

---

pkg/lockservice/lock_table_local.go
pkg/lockservice/lock_table_remote.go
pkg/lockservice/lock_table_remote_test.go
pkg/lockservice/log.go
pkg/lockservice/service.go
pkg/lockservice/service_remote.go
pkg/lockservice/service_test.go
pkg/lockservice/txn.go
pkg/lockservice/txn_test.go
pkg/lockservice/types.go
pkg/lockservice/waiter_events.go

issue #9909 
Let the lock operation of the same transaction spend serially. Currently, for update operations, delete and insert are parallel, once a deadlock occurs, the original design cannot meet this concurrent locking scenario

let the lock op of the same txn serially

---

pkg/txn/client/timestamp_waiter.go

issue #
In txn client's timestamp waiter.  If no notifications have been received, all new things need to wait until at least the first logtail notify.

txn: need wait  if have not received notification

---

pkg/sql/plan/opt_misc.go
pkg/sql/plan/query_builder.go

issue #
for equal join, if join conds left.a=right.b and left.a=right.c,
remove one cond and only leave left.a=right.b for hashmap build.
improve performance for tpch q9

remove redundant join condition

---

pkg/txn/client/timestamp_waiter.go

issue #9992 
Use a buffered channel of size 1 to avoid waiter no longer waiting for state and notify being blocked due to ctx cancel

fix notify applied logtail block

---

pkg/proxy/util.go

The `regexp.MatchString(pattern, str)` function performs a `regexp.Compile(pattern)` operation internally. Since we already know the regex pattern at compile time, we can use `regexp.MustCompile` to avoid compiling the same regex pattern for each function invocation.
This pull request updates the `isStmtBegin`, `isStmtCommit`, and `isStmtRollback` functions to use pre-compiled regex patterns, resulting in better performance and less memory allocations.
Sample benchmark:
```go
var (
beginPattern = fmt.Sprintf("^%s(%s)%s%s%s$",
spaceAtLeastZero, begin, spaceAtLeastZero, end, spaceAtLeastZero)
beginRegex = regexp.MustCompile(beginPattern)
)
func isStmtBegin(c []byte) bool {
matched, _ := regexp.MatchString(beginPattern, string(c))
return matched
}
func isStmtBeginNew(c []byte) bool {
return …
```

proxy: improve performance of isStmt functions

---

pkg/lockservice/rpc.go

issue #9884 
get response detail before write to avoid data race

fix data race in lock service

---

pkg/config/configuration.go
pkg/util/trace/config.go
pkg/util/trace/impl/motrace/buffer_pipe_test.go
pkg/util/trace/impl/motrace/mo_trace.go
pkg/util/trace/impl/motrace/mo_trace_test.go
pkg/util/trace/impl/motrace/schema.go
pkg/util/trace/noop_trace.go
pkg/util/trace/noop_trace_test.go
pkg/util/trace/trace.go
pkg/util/trace/type.go

issue #
modification:
1. logging span which is slow span, with config `longSpanTIme` as default threshold: 10s
- user can overwirte `longSpanTime` by passing `trace.LongTimeThreshold()` at `Tracer.Start(...)`
2. logging span which meets context Deadline, and the context is specified at the `Tracer.Start`.
3. span support add ExterFields to record more detail infos.
more examples can see `TestMOSpan_End`  in [mo_trace_test.go](https://github.com/matrixorigin/matrixone/blob/b0b671a9cbe224ee4b0a804db1bcaaba137ac3c3/pkg/util/trace/impl/motrace/mo_trace_test.go#L208)

record Span with long time threshold and context deadline condition.

---

pkg/logservice/store.go
pkg/logservice/store_hakeeper_check.go
pkg/logservice/store_hakeeper_check_test.go
pkg/logservice/store_test.go
pkg/sql/parsers/dialect/mysql/mysql_sql.go

issue #8599  #9794 
moving the task schedule from the ticker normal routine to a separate goroutine can avoid the hakeeper's health check and tick update operations being blocked by the task schedule, or the tick will be skipped and can not correctly estimate the time passing. and added some unit tests.

fix issue 8599: move task schedule to a separate goroutine

---

test/distributed/cases/result_count/result_count.result
test/distributed/cases/result_count/result_count.sql
test/distributed/cases/statement_query_type/statement_query_type.result
test/distributed/cases/statement_query_type/statement_query_type.sql

issue #
fix bvt double exec result, which is caused by pr #10061
- found in https://github.com/matrixorigin/matrixone/actions/runs/5320270900/jobs/9633817039?pr=10151

fix bvt double exec 

---

pkg/sql/plan/build_dml_util.go

issue #
Disable build hash table on left table in right join. Because maybe lost some data, and will then cause the primary key constraint to be misclassified

disable build hash table on left  in right join

---

cmd/mo-service/launch.go
go.sum

It is a horrible hack -- we call this method to force go runtime release memory back to OS, otherwise RSS is inflated.
issue #

Call debug.FreeOSMemory every minute.

---

cmd/mo-service/launch.go
go.sum

Calling FreeOSMemory in a goroutine when server starts. Try to free go runtime memory to os to curb RSS inflation.
issue #

Resubmit calling FreeOSMemory every minute.

---

pkg/vm/engine/tae/containers/pool.go
pkg/vm/engine/tae/options/options.go
pkg/vm/engine/tae/tables/mnode.go

issue #
Currently, It always set 16 workers to execute the background compaction jobs. The compaction task is an IO-and-CPU-bound job(load data, sort block, calc ndv, bloomfilter...). In a resource-limited environment, it will use up most of the hardware resources. Here we set the workers to be max(CpuNumers/4, 1).
I will temporarily disable the memtable vector pool for this pr, because the current memtable reuse has some problems, the actual observation shows that the reuse rate is very low, and the relevant resources are still pinned.

reduce the number of workers to execute compaction task

---

pkg/vm/engine/disttae/reader.go
pkg/vm/engine/disttae/txn_table.go
pkg/vm/engine/disttae/types.go

issue #9665 
1. filter uncommitted blks  by exprs when call `rangesOnePart` function .

filter uncommitted blocks by exprs  when call rangesOnePart

---

test/distributed/cases/function/table_func_metadata_scan.result
test/distributed/cases/function/table_func_metadata_scan.sql

issue #
The compressed block size will change. Remove related compressed block size check during metadata scan

remove bvt check with compressed size

---

pkg/frontend/computation_wrapper.go
pkg/frontend/test/txn_mock.go
pkg/frontend/util_test.go
pkg/sql/compile/compile.go
pkg/sql/compile/compile_test.go
pkg/sql/compile/sql_executor.go
pkg/txn/client/types.go
pkg/vm/engine/disttae/engine.go
pkg/vm/engine/disttae/types.go

issue #
In RC mode, the snapshot ts of the transaction are updated before each statement is executed. but cn treats commit as a statement as well, and obviously commit cannot update the snapshot ts. Because once dn has only incremental de-duplication turned on, it means that dn will only check for duplicate primary keys between snapshot ts and commit ts. If commit updates snapshot ts, then it means that the primary key de-duplication in the interval [last snapshot, new snapshot] neither cn nor dn will check

commit cannot update snapshot ts in rc mode

---

pkg/vm/process/process.go

* make vectorPool.getVector fetch vector from the end(#10201)
issue #10201

make vectorPool.getVector fetch vector from the end

---

pkg/sql/compile/ddl.go

issue #
fix bug for lockRows.  
for lock table in mo_catalog, we do not use primary key some times.

fix bug for lockRows

---

pkg/vm/engine/tae/logtail/service/server.go

issue #
When pushing logtail to cn, if there is a problem with the network, resulting in a failure, it may cause a leak of mpool

fix possible mpool leak when network fails

---

pkg/vm/engine/disttae/reader.go
pkg/vm/engine/disttae/types.go
pkg/vm/engine/tae/blockio/read.go

issue #9309 
In TPCC scenario, about 85% of blocks will be loaded and filtered by filter expr. Here we load the primary keys first to evaluate the filter expr and then only load other columns if the block is not filtered.
Also, we only prefetch primary keys when the filter expr is not nil.
After this PR, we can avoid mass eviction in the LRU cache.

improve tp performance in high concurrency and big data scenarios

---

pkg/sql/colexec/lockop/lock_op.go

issue #
fix bug: panic when truncate table in rc&pessimistic
repo step:
1 change cn.toml to set RC&pessimistic
2、run sql:
create database db1;
use db1;
create table t1(a int auto_increment primary key, b int);
truncate table t1;   //panic here

fix bug: panic when truncate table in rc&pessimistic

---

.github/workflows/release.yml

issue #10389 
The version of MO is determined by a git command, which gets the latest tag of repo, so we need to fetch all tags before build release binary.

[bug] the version is not correct when build binary in CI.

---

pkg/sql/plan/function/func_builtin.go
test/distributed/cases/function/func_purge_log.result
test/distributed/cases/function/func_purge_log.sql

issue #10421
fix buildin function purge_log just handle first table

fix buildin function purge_log just handle first table

---

pkg/vm/engine/tae/db/open.go

related to issue #10440
Before this pr, every minute, dn checks if the max checkpoint is finished, if so, gc logtail using the end timestamp. However, it is possible that every check will find the checkpoint is unfinished, and skip gc logtail, leading to a lot of unused logtail in memory.
In this pr,  the start ts of the max checkpoint is used to calculate the end ts of the previous checkpoint.

fix logtail lagging gc

---

pkg/sql/plan/build_ddl.go

issue #10355
fix alter stmt crash bug:
There are tons of ALTER TABLE cases that users might try. The following statements still crash MO.
ALTER TABLE t2 CHARACTER SET = utf8mb4;
ALTER TABLE t2 ROW_FORMAT = COMPRESSED;
ALTER TABLE t2 ENGINE = InnoDB;
I'm referring from this page. https://dev.mysql.com/doc/refman/8.0/en/alter-table.html

fix alter stmt crash bug

---

pkg/vm/engine/tae/logtail/service/server.go
pkg/vm/engine/tae/logtail/service/session.go

issue #
In this PR:
1. it will free all pending responses in the session after the stream is closed.
2. it will free the incoming response when there is no session. (the previous active sessions were deleted from the session manager)

fix a mpool leak after stream closed

---

pkg/sql/plan/build_dml_util.go
pkg/sql/plan/build_update.go

issue #10447 
1、如果更改的列不是pk，或者复合主键的某列。那么该更新语句跳过pk查重
2、有时候旧逻辑会跳过pk查重

skip dup check for update non pk col

---

pkg/sql/plan/build_ddl_test.go
pkg/sql/plan/build_index_util.go

issue #10515
在mysql中：索引的语法是：
ADD {INDEX | KEY} [index_name]
[index_type] (key_part,...) [index_option] ...
ADD [CONSTRAINT [symbol]] UNIQUE [INDEX | KEY]
[index_name] [index_type] (key_part,...)
[index_option] ...
key_part: {col_name [(length)] | (expr)} [ASC | DESC]
目前咱们mo的索引不支持使用表达式expr作为索引组成键，出现表达式作为索引组成键会报错，但是mo语法支持索引键排序[ASC | DESC] @heni02 @DanielZhangQD @LiSong0214 @domingozhang

Index syntax supports sorting

---

pkg/common/morpc/server.go

issue #10514
If DN encounters an error and needs to close the stream by calling Close, it will leave a busy writing loop reading the closed channel, consuming a lot of CPU. 
In this pr, cancel the context in Close method to break that loop

fix busy loop when closing client

---

pkg/dnservice/cfg.go

issue #
Now the logtail-collect-interval is configured to 2ms in dn.toml. If it is not configured, MO will use the default value 50ms (defaultLogtailCollectInterval), which will cause poor performance of MO. So it needs to be fixed.

Modify defaultLogtailCollectInterval to 2ms

---

pkg/config/configuration.go
pkg/config/configuration_test.go
pkg/frontend/mysql_cmd_executor.go
pkg/sql/plan/explain/explain_query.go
pkg/sql/plan/explain/marshal_query.go
pkg/util/trace/impl/motrace/report_statement.go

issue #
1. directly get stats from `plan.Query`, instead of from `MarshalPlan`, which is parsed from planQuery.
2. modify config `LongQueryTime` default value. 
- If config `DisableStmtAggregation == false`, `LongQueryTime` is NO less than `SelectAggrThreshold`

Improve stats calculate cost while collect statement info

---

pkg/vm/engine/disttae/reader.go
pkg/vm/engine/disttae/tools.go
pkg/vm/engine/disttae/txn_table.go
pkg/vm/engine/disttae/types.go
pkg/vm/engine/disttae/util.go
pkg/vm/engine/disttae/util_test.go
test/distributed/cases/dml/select/select.result
test/distributed/cases/dml/select/select.test

issue #10499 
1. it should not panic if eval expr of any key in composite primary keys $key = null
2. quick return if any null used in pk filter expr

fix 10499 and quick return if any null used in pk filter expr

---

pkg/lockservice/lock_table_local.go
pkg/lockservice/lock_table_local_test.go
pkg/sql/colexec/lockop/lock_op.go

issue #
Improve performance if locked with no conflict.  The lock service internally records the maximum commit timestamp for each table, and when a transaction acquires a lock, if there is no conflict, the last commit timestamp is used as the lockedTS, to avoid unnecessary waits

improve performance if locked with no conflict

---

pkg/sql/colexec/lockop/lock_op.go
pkg/vm/engine/disttae/logtailreplay/primary_key_utils.go

issue #10502 
When you realize that you have already flushed, and the commit timestamp of the flush is after the from, then you should force the return of the data change, and you don't need to check the memory value.

fix check data changed

---

pkg/txn/client/operator.go

issue #10498
* In rc mode, this logic is not needed to introduce redundant waits, and should be used to ensure that rc is correct by detecting the presence of a primary key modification and then reeval.

Remove the dealy of rc mode

---

pkg/proxy/server.go

issue #9523 
adding code to set up the service version for proxy when using cfg mode.

set service version for proxy when uses cfg mode

---

pkg/cnservice/server_heartbeat.go
pkg/cnservice/server_task.go
pkg/proxy/bootstrap.go
pkg/proxy/bootstrap_test.go
pkg/proxy/config.go
pkg/proxy/conn_manager.go
pkg/proxy/handler.go
pkg/proxy/handler_test.go
pkg/proxy/router.go
pkg/proxy/router_test.go
pkg/proxy/server.go
pkg/proxy/server_conn_test.go
pkg/proxy/sql_worker.go
pkg/proxy/sql_worker_test.go

Before, proxy get the connection information within itself, and it does not know infos in other proxy. So we need to use show processlist function to get global connection info to kill the right connection.
issue #10122

[bug] proxy: drop/suspend account does not work for multi proxies.

---

pkg/perfcounter/counter_set.go
pkg/sql/compile/compile.go
pkg/util/metric/stats/counter.go

issue #10562
clean the s3counter after get compile from pool

clean s3count after get compile from pool

---

pkg/vm/engine/disttae/logtailPushModel.go

issue #10833
1. adjust some log level of log tail push client.
2. increase timeout to 30s for table subscription. (If the state of a table does not change to 'subscribed' within 30 seconds after sending the subscribe request, an error is returned.)

increase timeout to 30s for table subscription

---

pkg/vm/engine/tae/catalog/catalog.go
pkg/vm/engine/tae/db/db_test.go

issue #10830
If it is replaying a delete node, do not replay renaming operation at the same time.

fix replay delete and rename node

---

cmd/mo-service/launch.go
cmd/mo-service/main.go
pkg/dnservice/store.go
pkg/dnservice/store_heartbeat.go
pkg/dnservice/store_test.go
pkg/hakeeper/checkers/syshealth/check.go
pkg/logservice/client_test.go
pkg/logservice/hakeeper_client_test.go
pkg/logservice/service.go
pkg/logservice/service_commands.go
pkg/logservice/service_commands_test.go
pkg/logservice/service_test.go
pkg/logservice/service_wrap.go
pkg/logservice/store_hakeeper_check_test.go
pkg/logservice/testclient.go
pkg/pb/logservice/logservice.go
pkg/pb/logservice/logservice_test.go
pkg/tests/service/dnservice.go
pkg/tests/service/logservice.go

issue #10658 #10422 #10888 
when the ha keeper found the log replicas of any shards less than half of the initial setting (num-of-log-shard-replicas), it will issue a shutdown command to log services and dn services to shut down all stores.
however, the shutdown command handler will fall into a deadlock when the log store and dn store received these commands:
heartbeat sends log store and dn store msg to ha keeper, and calls `handleCommands` to handle commands. the shutdown handler then calls service.close which will cancel all ctx and wait tasks exit. but the heartbeat task can detect the cancel signal only when handleCommands is returned.
so, when the shutdown command is generated, the log service and dn service will print these msg respectively
endlessly:
```
tasks still running in …
```

correct the behavior of handle shutdown cmd

---

pkg/common/morpc/backend.go
pkg/common/morpc/backend_test.go
pkg/common/morpc/client.go

issue #
release tcp mem when closed immediately. If wait gc task, has a 1 minutes latency.

fix morpc mem

---

pkg/frontend/test/txn_mock.go
pkg/frontend/util_test.go
pkg/sql/compile/compile.go
pkg/sql/compile/compile_test.go
pkg/txn/client/client.go
pkg/txn/client/types.go
pkg/vm/engine/disttae/types.go

issue #
Improve performance in pessimistic(rc) mode.  Pessimistic(rc)mode no need use current timestamp as txn's snapshot ts, and when the first statement is executed, we can use the snapshot of the created transaction, no need to update the snapshot.

improve performance in pessimistic mode

---

pkg/vm/engine/tae/logstore/driver/logservicedriver/driver.go

issue #10926 
when ctrl+c shut down the log service, the dn service cannot append entries to the log service, after retrying 180s, the append task will panic.
however, all append tasks are submitted to a goroutine pool to be scheduled, and the pool will catch the panic through `recover`, and do some operations specified by users.
In the previous implementation, no panic handler is specified to the pool when calling the 'ants.NewPool, so the panic` can only crash the goroutine it belongs to instead of the dn service.
after the append task crashes, some other tasks will fall into the dead wait, which expected the append task to return and do some further work.
that is why the ctrl+c cannot shut down the dn service.
the fix is to specify a panic handler.
but it still needs to wait for 180s …

add default panic handler for log append task

---

pkg/sql/colexec/lockop/lock_op.go

issue #
Since the original transaction is used to check for primary key changes, in order to ensure that the logtail of the locked TS can be seen by the transaction, a larger snapshotTS needs to be used to get a new snapshot to check for it, instead of using the lockedTS, which would have missed the commits corresponding to the lockedTS writes.

fix checks pk changed with the wrong timestamp

---

pkg/sql/plan/build_constraint_util.go
pkg/sql/plan/build_dml_util.go
pkg/sql/plan/build_insert.go
pkg/sql/plan/build_load.go
pkg/sql/plan/build_update.go

issue #10655 
1、have t1 (a int auto_increment primary key, b int, c int);
insert  into t1(b, c) values (1,1),(2,2)  will not check PK dup now.
2、have t1 (a uuid primary key, b int, c int);
insert  into t1(b, c) values ("2675a10c-31d1-11ee-be6c-f93a3353072c",1)
use PK_col = xx to improve performance in checking PK dup, not join entire table any more.
3、when insert table which have no primary key.  we do not lock the rows now.

improve performance for checking PK dup in some cases

---

pkg/common/morpc/cfg.go
pkg/common/morpc/cfg_test.go
pkg/vm/engine/tae/txn/txnbase/command.go
pkg/vm/engine/tae/txn/txnimpl/command_test.go

issue #10835 
After the prefetch fix, there still context deadline exceeded
error when commit transaction, which is caused by the message
size larger than RPC max message size.
The main fix is to change value of CmdBufReserved from 1024 to
1024 * 1024 * 10. Because the size of TxnCtx.Memo may be large
if there are too many blocks.

[bug] load data: fix the timeout bug when load 1T data.

---

pkg/vm/engine/disttae/db.go
pkg/vm/engine/disttae/engine.go
pkg/vm/engine/disttae/logtailPushModel.go
pkg/vm/engine/disttae/logtailreplay/partition.go
pkg/vm/engine/disttae/logtailreplay/partition_state.go
pkg/vm/engine/disttae/logtailreplay/partition_state_test.go
pkg/vm/engine/disttae/logtailreplay/partition_test.go

issue #
logtailreplay: add Partition.ConsumeCheckpoints
logtailreplay: add benchmark for Partiton.ConsumeCheckpoints
logtailreplay: add Partition.checkpointConsumed
disttae: ensure partition checkpoints are consumed once

logtailreplay: optimize checkpoints consumption

---

pkg/sql/plan/build_show.go
test/distributed/cases/dml/show/show3.result
test/distributed/cases/dml/show/show3.sql

issue # https://github.com/matrixorigin/MO-Cloud/issues/1028#issuecomment-1667642384
1. 调整 `show create table` 输出字符串中`cluster by`字符串的位置。
根据`create table`的语法，`cluster by` 选项是放在最后的位置。
在`show create table`也要放到最后。mo-dump会用`show create table`的结果来构造`create table` 语法。

adjust the position of `cluster by` option in the output of `show create table`

---

pkg/frontend/server.go
pkg/frontend/types.go

issue #10945
* The default 1MB rpc buffer is too large, and in tp scenarios, a high concurrency can easily lead to oom.

Modify the default rpc buffer size for mysql protocol server

---

pkg/cnservice/types.go

issue #
use cpu numbers * 4 as default max active user txns.

set default max active user transactions

---

pkg/proxy/router.go
pkg/proxy/router_test.go
pkg/proxy/server_conn.go
pkg/proxy/server_conn_test.go

issue #11162
Prevoisly, the connect() mothod in porxy only return retryable error when
the cn pod is down and could not connect to, and it is not enough. We 
add a timeout check in handshake phase to return a timeout error if the
CN server is hang.

[Enhancement]: proxy do not connect to cn if it cannot connect to.

---

pkg/frontend/cmd_executor.go
pkg/frontend/computation_wrapper.go
pkg/frontend/mysql_cmd_executor.go
pkg/frontend/mysql_cmd_executor_test.go
pkg/frontend/routine_test.go
pkg/frontend/test/types_mock.go
pkg/frontend/types.go
pkg/sql/compile/compile.go
pkg/sql/compile/compile_test.go
pkg/sql/compile/sql_executor.go
pkg/util/run_result.go

issue #
原来是在从pool get的时候clear。
会让调用方误以为Run这个函数使用之后，Compile对象还存在。但是实际上它是可能存在，也可能不存在。
因为当并发很高，其他地方快速从pool中get一个compile出来，然后进行clear的话。那么会导致前面那个调用方所拿到的compile中的数据是错误的（比如affect_rows，因为被另外一个调用方clear了)
这个重构，给Run方法增加了返回值。如果需要信息，调用方应该从返回值中拿。当Run结束后，应该认为compile对象内的所有信息已经被清空。

clean compile before put compile to pool

---

pkg/lockservice/lock_table_local.go
pkg/lockservice/lock_table_local_test.go
pkg/lockservice/txn.go
pkg/lockservice/waiter.go

issue #
1. Transaction A's waiting list is [B, C, D]. Means [B, C, D] wait A. If A closed, B will get the lock, so wait relation is changed, [C, D] wait A -> [C, D] wait B. So C, D need check deadlock with B.
2. When a transaction has not been locked for a long time, it is possible that the deadlock detection was missed, rejoin the deadlock detection queue

fix missing deadlock check

---

test/distributed/cases/pessimistic_transaction/transaction_enhance.sql

add tag 11334

---

pkg/frontend/cmd_executor.go
pkg/frontend/mysql_cmd_executor.go
pkg/frontend/mysql_protocol.go
pkg/frontend/util.go
pkg/util/export/table/table_test.go

issue #
changes:
1. correct frontend log `caller` location, like: `frontend/util.go:524` -> `frontend/mysql_cmd_executor.go:3268`
2. correct frontend `logInfo()` params, like: `logInfo(ses, msg, params)` -> `logInfo(ses, info, fmt.Sprintf(msg, params))`
3. correct frontend log fields's value: `session_id` and `statement_id`.
check log:
```
mysql> select sleep(2);
```
- new log format
```
{"level":"INFO","time":"2023/09/07 14:59:33.889767 +0800","name":"log-service.frontend","caller":"frontend/mysql_cmd_executor.go:3268","msg":"time of Exec.Run : 2.000382875s","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","session_info":"connectionId 29422|127.0.0.1:51489|{account sys:dump:moadmin -- 0:1:0}|goRoutineId 7626|1604ddce-4d4c-11ee-a647-3ebf9f3960c8","session_id":"1604ddce-4d4c-11ee-a647-3ebf9f39 …
```

Fix frontend log fromat

---

pkg/sql/colexec/connector/connector.go
pkg/sql/colexec/dispatch/dispatch.go
pkg/sql/colexec/dispatch/sendfunc.go
pkg/sql/colexec/receiver_operator.go

issue #
context done is an expected performance for pipeline, it means pipeline ends normally.
So it is no need to write logs for those situations.

remove pipeline's wrong log

---

pkg/frontend/mysql_cmd_executor.go
pkg/util/trace/impl/motrace/Aggr_test.go
pkg/util/trace/impl/motrace/buffer_pipe_test.go
pkg/util/trace/impl/motrace/report_statement.go
pkg/util/trace/impl/motrace/report_statement_test.go
pkg/util/trace/impl/motrace/statistic/stats_array.go
pkg/util/trace/impl/motrace/statistic/stats_array_test.go

issue #https://github.com/matrixorigin/matrixone/issues/11761
https://github.com/matrixorigin/MO-Cloud/issues/1004
changes:
1. Record ConnType while do `RecordStatement()` in frontend
2. Add new elem `StatsArrayIndexConnType` in statistics.StatsArray
3. Modify `StatsArray.Add()` ignore StatsArray elem.

record conn type in statement_info.stats

---

pkg/frontend/authenticate.go

issue #11747 
原先的drop account 写死了delete from mo_pubs。如果mo_pubs不存在会报错。
去掉delete from mo_pubs。只用drop table if exists 就行了。

remote delete mo_pubs

---

CODEOWNERS
pkg/common/morpc/backend.go
pkg/common/morpc/backend_test.go
pkg/common/morpc/future.go
pkg/lockservice/rpc.go
pkg/lockservice/service_remote_test.go

issue #11838
In our environment, it is possible to not sense a tcp disconnect, causing the remote lock to fail to return, resulting in a hung. we've added a heartbeat mechanism to morpc and added a read timeout to read to solve this problem.

add read timeout for lockservice remote lock

---

pkg/frontend/authenticate.go

issue #11747 
原先的drop account 写死了delete from mo_pubs。如果mo_pubs不存在会报错。
去掉delete from mo_pubs。只用drop table if exists 就行了。

fix drop account

---

pkg/fileservice/cache.go
pkg/gossip/delegate.go
pkg/gossip/dist_key_cache.go
pkg/gossip/node.go

issue #11918
Do not set items if the remote cache is not enabled. Also, add
count limit for key cache queue, to avoid large memory occupation.

[bug] distcache: limit the item count for the dist cache.

---

pkg/incrservice/column_cache.go
pkg/incrservice/column_cache_test.go

issue #11957
fix cannot allocate new cache. If create auto-incr table and insert too many records, cannot allocate new incr cache again.

fix cannot allocate new cache

---

pkg/common/morpc/backend.go
pkg/logservice/hakeeper_client_test.go

issue #11957 
Make the backend connection reconnect only when it encounters a temporary net error

make retry reset conn with temp net error

---

pkg/sql/colexec/lockop/lock_op.go
pkg/sql/compile/alter.go
pkg/sql/compile/compile.go
pkg/sql/compile/ddl.go

issue [#1409](https://github.com/matrixorigin/MO-Cloud/issues/1409)
* For the case of inserting into a table with no primary key, the original logic was to mindlessly lock the entire table, which is not correct. The logic should have been to just lock the metadata information of this table to ensure that it doesn't conflict with the alter.

Fix incorrect locking logic for inserting tables without primary keys

---

pkg/vm/engine/disttae/logtailreplay/partition_state.go
pkg/vm/engine/tae/catalog/schema.go

issue #11973 
fix the sort key missing in tables having a `cluster by` clause.
the sort key only exists in memory and is constructed when creating schema by reading checkpoint data.
the sort key will be used later in `metadata_scan` and judging if it is needed to `mergesort` columns.

 fix the sort key missing in tables having cluster by clause

---

pkg/frontend/util.go

issue #11952
refix_issue_11952, changes:
- move EndStatement after LogDebug / LogError, which still need ses.tStmt to log.

Make sure no one use ses.tStmt after EndStatement

---

pkg/frontend/mysql_cmd_executor.go

issue # 11858
Clean up executeStmt a little bit.   Removed some abuse of err, err2, txnErr, etc.   Use local if possible.
Fix a few possible code path that led to leak Start/End statement, not it is not necessarily the root cause
of #11858.

A sequence of minor rewrite to clean up executeStmt

---

pkg/config/configuration.go

issue #11944
changes:
- config frontend::lengthOfQueryPrinted default value as 1KiB
affect 2 places:
1. record in table system.statement_info, column `statement` will be truncated as 1KiB length
2. logs printed by CN, which has `statement` field
- for example:
-   2023/10/08 16:24:54.173199 +0800 ERROR log-service.frontend frontend/util.go:511 query trace status {....., "connection_id": 113711, **"statement": "uset test"**, "status": "fail", "error": ".....", "span": ....., "session_info": "connectionId 113711.....", "session_id": ".....", "statement_id": "......"}

change config frontend::lengthOfQueryPrinted default as 1KiB

---

cmd/mo-service/config.go
cmd/mo-service/debug.go
pkg/perfcounter/named.go

mo-service: set per node named perf counters; add global named perf counter
issue #11710

perfcounter: add Named

---

pkg/objectio/metav2.go
pkg/objectio/writer.go
pkg/objectio/writer_test.go
pkg/vm/engine/tae/blockio/writer.go
pkg/vm/engine/tae/db/checkpoint/option.go
pkg/vm/engine/tae/db/checkpoint/runner.go
pkg/vm/engine/tae/db/open.go
pkg/vm/engine/tae/db/test/db_test.go
pkg/vm/engine/tae/db/testutil/engine.go
pkg/vm/engine/tae/logtail/utils.go
pkg/vm/engine/tae/options/cfg.go

Limit the size of a single checkpoint file.
Because the offset of the layout is of uint32 type, a single file cannot exceed 4 G.
issue #

Limit the size of a single checkpoint file (#12095)

---

cmd/mo-dump/main.go
cmd/mo-dump/types.go

issue #10091 
mo-dump supports dumping database and table definitions only without data

feat: support mo-dump -no-data flag

---

cmd/mo-service/launch.go
pkg/logservice/client.go
pkg/logservice/hakeeper_client.go
pkg/logservice/hakeeper_client_test.go
pkg/logservice/shardinfo.go

issue #12080 
Add timeout for logservice RPC read, and add retry logic for
CN start if it encouters some error which is not context.DeadlineExceeded.

[bug] logservice: add timeout for RPC read.

---

pkg/vm/engine/tae/logtail/utils.go

issue #
CN Prefetch checkpoint will cause panic because the original checkpoint was one object, and now it may be multiple objects, but CN's Prefetch does not adapt to multiple objects.

Fix CN prefetch checkpoint

---

pkg/sql/colexec/server.go
pkg/sql/compile/scopeRemoteRunTypes.go

fix a remote run bug will cause memory leak.

---

pkg/lockservice/lock.go
pkg/lockservice/lock_table_local.go
pkg/lockservice/service_test.go
pkg/lockservice/test_helper.go
pkg/lockservice/waiter_events.go
pkg/lockservice/waiter_queue.go

issue #12015 
Fix try hold on empty lock.  If a range lock has no holders, the all waiters need to be notified.  Because these waiters may be attempting to acquire a non-conflicting row locks or range locks between the current range.  Also, the range locks needs to be removed, otherwise an Empty Lock will be left in the lock table.

fix lockservice panic with try hold on empty lock

---

pkg/vm/engine/tae/logtail/service/server.go

issue #12045 
The reason may be that send subscription takes long time and every
time "for select" choose a case, it always choose the sub channel.
And update event is never sent during slow subscription.
We add a logic that we try to send update event before send subscription
if it has not sent any update event for long time to make sure that logtail
consumer can receive timestamp advance.

[bug] logtail: CN panic due to wait latest commit ts failed

---

pkg/sql/plan/function/ctl/cmd_inspectdn.go
pkg/sql/plan/function/ctl/ctl.go
pkg/vm/engine/tae/catalog/segment.go
pkg/vm/engine/tae/catalog/table.go
pkg/vm/engine/tae/common/stats.go
pkg/vm/engine/tae/db/checkpoint/runner.go
pkg/vm/engine/tae/db/db.go
pkg/vm/engine/tae/db/merge/executor.go
pkg/vm/engine/tae/db/merge/mod.go
pkg/vm/engine/tae/db/merge/policyBasic.go
pkg/vm/engine/tae/db/merge/policyOverlap.go
pkg/vm/engine/tae/db/merge/utils.go
pkg/vm/engine/tae/db/open.go
pkg/vm/engine/tae/db/operations.go
pkg/vm/engine/tae/db/scannerop.go
pkg/vm/engine/tae/index/zm.go
pkg/vm/engine/tae/index/zm_test.go
pkg/vm/engine/tae/logtail/collector.go
pkg/vm/engine/tae/rpc/handle.go
pkg/vm/engine/tae/rpc/inspect.go
pkg/vm/engine/tae/tables/jobs/flushTableTail.go
pkg/vm/engine/tae/tables/jobs/mergeblocks.go

issue #12075
merge more blocks for once.
add `merge`, `object`, and `policy` commands to check and control merging
```bash
mysql> select mo_ctl('dn', 'inspect', 'help')\G
*************************** 1. row ***************************
mo_ctl(dn, inspect, help): 
msg: Usage:
inspect [command]
Available Commands:
catalog     show catalog
help        Help about any command
merge       manually merge objects
object      show object statistics
policy      set merge policy for table
Flags:
-h, --help   help for inspect
```

merge more blocks

---

pkg/fileservice/caching_file_service_test.go
pkg/fileservice/disk_cache.go
pkg/fileservice/disk_cache_test.go
pkg/fileservice/file_cache.go
pkg/fileservice/s3_fs.go
pkg/perfcounter/counter_set.go

issue #11569 
fileservice: add FileCache
fileservice: rename DiskCache.entryDataFilePath to pathForIOEntry
fileservice: sketch FileCache impl for DiskCache
fileservice: remove S3FS.writeDiskCacheOnWrite
fileservice: add DiskCache.writeFile
fileservice: remove FileCache.GetFile; try get full file in DiskCache.Read
fileservice: add DiskCache.SetFile tests
fileservice: write to disk file cache in S3FS.write

fileservice: write to disk cache in S3FS.Write and Read

---

pkg/container/vector/vector.go
pkg/container/vector/vector_test.go
pkg/vm/engine/tae/containers/batch.go
pkg/vm/engine/tae/containers/vector.go
pkg/vm/engine/tae/logtail/utils.go

When writing checkpoint, mo needs to split the vector into multiple small vectors according to 10,000 rows before writing. Now use the windown interface to split it, causing each small vector of 10,000 lines to reference the same Vector.area. Causes the vector's writing size to expand 10 times. fix now
Approved by: @aunjgr, @XuPeng-SH
issue #

Fix batch splitter (#12311)

---

pkg/proxy/client_conn.go
pkg/proxy/client_conn_test.go
pkg/proxy/event.go
pkg/proxy/event_test.go
pkg/proxy/server_conn_test.go

issue https://github.com/matrixorigin/MO-Cloud/issues/1563
When proxy transfer a connection to a new CN server, use statement
should be re-executed to make sure the tables could be found in session.

[bug] proxy: re-execute use statement after session is transferred.

---

pkg/common/moerr/error.go
pkg/common/moerr/error_no_ctx.go
pkg/txn/client/client.go
pkg/txn/client/timestamp_waiter.go
pkg/txn/client/timestamp_waiter_test.go
pkg/txn/client/types.go
pkg/txn/util/log.go

issue #12166 #12263 #11838
When logtail resumer occurs some kind of error, it will try to reconnect
to logtail server. Before reconnect, it aborts all running transactions.
Before rollback txns, txn client should cancel all timestamp waiters,
because there may be some transactions are trying to commit and
waiting for the new TS, but they cannot wait for any new TS as the
logtail consumer is in the status of reconnecting.

[bug] logtail: fix hang when logtail consumer reconnect.

---

pkg/util/metric/v2/dashboard/grafana_dashboard_task.go
pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
pkg/util/metric/v2/metrics.go
pkg/util/metric/v2/task.go
pkg/util/metric/v2/txn.go
pkg/vm/engine/disttae/txn_table.go
pkg/vm/engine/tae/db/merge/executor.go
pkg/vm/engine/tae/rpc/handle.go
pkg/vm/engine/tae/txn/txnbase/txnmgr.go
pkg/vm/engine/tae/txn/txnimpl/store.go

issue #12223 
add some metrics:
1. txn OnPrepareWal duration Histogram
2. txn Dequeue Preparing Duration Histogram
3. txn Dequeue Prepared Duration Histogram
4. txn Handle Commit But Before Txn.Commit Duration Histogram
5. task Merge Scheduled times Counter
6. task Merged Block count Each Schedule Counter
7. task Merged Size Each Scheduler Counter
8. txn fast loading object meta counter in oneRangePart

sync the txn and task metrics on tn side between main and 1.0-dev.

---

pkg/vm/engine/disttae/logtailPushModel.go

issue #12065
If the logtail push client is not ready, do not check the snapshot timestamp.
There is another checking logic before create a new transaction, so we do
not need to check here if it is not ready yet.

[bug] logtail: remove unnecessary panic information.

---

pkg/sql/colexec/deletion/types.go

issue #11856 
`arg.ctr.batch_size` is defined as a uint32, but it was incorrectly calculated and was smaller than the actual data size. When `arg.ctr.batch_size` reaches a certain threshold (currently set at 32MB), the data is flushed to disk. During each flush operation, the real batch size is subtracted from arg.ctr.batch_size. This subtraction causes an overflow issue, causing arg.ctr.batch_size to become excessively large. As a result, every subsequent check to determine whether data should be flushed also triggers a flush operation, even when the actual data size is not significant. This behavior leads to the creation of a large number of small files.

fix-issue-11856

---

pkg/sql/compile/ddl.go
pkg/sql/plan/build_alter_table.go
pkg/sql/plan/build_constraint_util.go
pkg/sql/plan/build_dml_util.go
pkg/sql/plan/build_insert.go
pkg/sql/plan/build_load.go
pkg/sql/plan/deepcopy.go
pkg/sql/plan/mock.go
pkg/sql/plan/query_builder.go

This PR adds proper column pruning for joins which are implicitly spawned by INSERT/UPDATE statements when foreign key exists in order to resolve memory issues.
issue #12358 matrixorigin/MO-Cloud#1531

[opt] column pruning for foreign key insert/update

---

pkg/frontend/show_account.go

When a defer statement is followed by a `time.Since`, that `time.Since` is actually not deferred but inlined. The correct usage is to wrap it in a closure.
Refer to https://pkg.go.dev/golang.org/x/tools/go/analysis/passes/defers
issue #

fix a misuse of `defer time.Since`

---

pkg/frontend/show_account.go
pkg/vm/engine/tae/logtail/storage_usage.go
pkg/vm/engine/tae/logtail/utils.go

issue #12483 
change to load specified ckp data batch when `show accounts` to avoid possible oom. 
the previous implementation is loading the whole ckp data.

change to load specified ckp data batch when `show accounts` to avoid possible oom. 

---

pkg/sql/colexec/rightsemi/join.go
pkg/sql/compile/compile.go
pkg/sql/compile/scope.go
pkg/vm/vm.go

issue #11966, #12385
* Currently there are some missing resource cleanups after recover, the pr makes up for the missing resource cleanups
* Fix a case where right join didn't handle context correctly

Fix resource cleanup issue after recover

---

pkg/sql/compile/compile.go
pkg/sql/compile/scope.go

issue #12449
should not set channel buffer size in runtime

[Bug]: After a long run, the tpch get wrong result

---

pkg/sql/compile/compile.go
pkg/sql/compile/scope.go

Reverts matrixorigin/matrixone#12586

Revert "[Bug]: After a long run, the tpch get wrong result"

---

pkg/logservice/config.go
pkg/logservice/service_bootstrap.go
pkg/logservice/service_bootstrap_test.go

issue #12437 
1. set a default value to restore file path. If the file does not exist,
do not restore.
2. do not perform repeated restore operation by checking the restore
tag file. This file is created when we do restore the first time.
3. If something wrong happens and a new restore have to be done, then
set "force" to true.

[enhancement] hakeeper: Do not perform repeated restore operation.

---

pkg/vm/engine/tae/options/options.go
pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
pkg/vm/engine/tae/tables/txnentries/mergeblocks.go

issue #
1. Do not record rowid transfer history for tables without primary key
2. Change the history retention time from 120s to 90s

do not record rowid transfer history for tables without primary key

---

pkg/vm/engine/tae/model/pages.go
pkg/vm/engine/tae/model/transfer_test.go
pkg/vm/engine/tae/tables/txnentries/compactblk.go
pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
pkg/vm/engine/tae/tables/txnentries/mergeblocks.go

issue #12660 
Record the transfer history for a short time to avoid r-w errors in BVT.

record rowid transfer history for a short time for the table without primary key

---

pkg/catalog/types.go
pkg/sql/plan/mock.go
pkg/sql/util/index_util.go

issue #1686 https://github.com/matrixorigin/MO-Cloud/issues/1686
修改 unique index 前缀名错误导致show accounts失败问题。
原因：
1，unique index 前缀名错误使得索引表被误判为cluster table。
2，普通租户的索引表被切换到sys租户取统计信息。因此出错。
索引表名称定义时只有单个下划线：
错误使用双下划线：

fix wrong unique index prefix

---

pkg/catalog/types.go
pkg/sql/util/index_util.go

issue https://github.com/matrixorigin/matrixone/issues/1686 https://github.com/matrixorigin/MO-Cloud/issues/1686
修改 unique index 前缀名错误导致show accounts失败问题。
原因：
1，unique index 前缀名错误使得索引表被误判为cluster table。
2，普通租户的索引表被切换到sys租户取统计信息。因此出错。
索引表名称定义时只有单个下划线：
错误使用双下划线：

cherry pick: fix wrong unique table name

---

pkg/fileservice/config.go
pkg/fileservice/disk_cache.go
pkg/fileservice/error.go
pkg/fileservice/path.go
pkg/fileservice/policy.go
pkg/fileservice/s3_fs.go
pkg/fileservice/s3_fs_restore.go
pkg/fileservice/s3_fs_test.go

issue #12692 
fileservice: cache IOEntry if not caching full file in S3FS disk cache
fileservice: more tests for S3FS restore
fileservice: add Config.FixMissing
fileservice: add fixMissingFlag

fileservice: add S3FS.restoreFromDiskCache

---

pkg/util/metric/v2/fileservice.go
pkg/util/metric/v2/hakeeper.go
pkg/util/metric/v2/logtail.go
pkg/util/metric/v2/morpc.go
pkg/util/metric/v2/task.go
pkg/util/metric/v2/txn.go

issue #
cherry pick update metrics precision

adjust metrics precision

---

pkg/common/moerr/error.go
pkg/common/moerr/error_no_ctx.go
pkg/txn/client/client.go
pkg/txn/client/timestamp_waiter.go
pkg/txn/client/timestamp_waiter_test.go
pkg/txn/client/types.go
pkg/txn/util/log.go

issue https://github.com/matrixorigin/MO-Cloud/issues/1733
some sequence bug results to the hang issue, fix:
1. timestamp waiter and single txn waiter share the same channel 
2. add lock for the cancel channel. If pause the timestamp waiter,
set the cancel channel to nil in timestamp waiter. If some new txns
comes, refuse its creation because the channel is nil. After rollback
all txns, resume the timestamp waiter and create a new cancel channel.

[bug] txn client: fix hang issue.

---

pkg/taskservice/mysql_task_storage.go
pkg/taskservice/task_service_cron.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/1746
Return error when trigger time does not match.
Print more info when trigger cron tasks failed.

return error when trigger times does not match

---

pkg/vm/engine/tae/catalog/table.go
pkg/vm/engine/tae/common/stats.go
pkg/vm/engine/tae/db/merge/executor.go
pkg/vm/engine/tae/db/scannerop.go
pkg/vm/engine/tae/logtail/collector.go
pkg/vm/engine/tae/rpc/inspect.go

issue #12645
add an interface to get info on the delete chain for debugging
```sh
*************************** 1. row ***************************
mo_ctl(dn, inspect, info -t db.t -b 81a6fb82-82aa-11ee-a8c2-acde48001122_0_0): 
msg: success. arg info: 272472-t 81a6fb82-82aa-11ee-a8c2-acde48001122-0-0
last_merge: (0001-01-01_00:00:00) no0 nb0 osize0B
last_flush: 0-1
persisted_ts: 0-0
delchain: DeleteChain:
1. [TXN:C:N][1:{1}][1699938229578336000-1,1699938229586875000-0]
```

add info cmd and various improvement

---

pkg/vm/engine/disttae/reader.go
test/distributed/cases/dml/delete/delete.result
test/distributed/cases/dml/delete/delete.test

issue #12797
临时移除一个统计信息。
目前大部分compile构建的source中的tableDef都是没有row_id的。
这里的统计信息的代码会默认它是包含row_id的，所以会对不上，于是panic了。
而block reader捕获到这个panic会跳过不读这个block。于是造成reader读不到数据。
复现步骤：
```
drop table if exists t7;
create table t7(a int primary key, b int unique key, c varchar(20) unique key);
insert into t7 select result, result, "a"||result from generate_series(1,2000000) g;
select count(*) from t7;
delete from t7;    // delete zero row.
select count(*) from t7;
```
先临时移除了，等明天再跟大家讨论处理方案

remove some metric

---

pkg/vm/engine/disttae/logtailreplay/primary_key_utils.go
pkg/vm/engine/disttae/logtailreplay/rows_iter_test.go
pkg/vm/engine/disttae/txn_table.go

issue https://github.com/matrixorigin/MO-Cloud/issues/1574
improve mem usage of PrimaryKeysMayBeModified
在处理 https://github.com/matrixorigin/matrixone/pull/12818  这个的时候。
在profile中看到这个方法占用时间会多一些。所以做了简单的优化。
主要是改了一下函数参数，把一个batch的数据都传进去，这样部分函数就只需要执行一次了。主要是这个
p.primaryIndex.Copy().Iter()   主要是这个一个批次只要执行一次了。
另外就是去掉了  p.rows.Copy().Iter() 的Copy()

improve mem usage of PrimaryKeysMayBeModified

---

go.mod
go.sum
pkg/frontend/routine.go
pkg/frontend/server.go
pkg/frontend/util.go
pkg/util/export/etl/db/db_holder.go

issue #1817 https://github.com/matrixorigin/MO-Cloud/issues/1817
如线下沟通，做下面的修改：
1，应用端修改
SetConnMaxLifetime 设置超时。
sqlDb.Exec(loadSQL) 用超时版本
2,goetty 修改
增加超时
msg, err := rs.Read(ReadOptions{超时时间})
3,frontend 打印新conn日志 
只打印一条。
目前goroutineid 与 session ip port 无法关联。

fix long queries that exceed 24 hours

---

pkg/vm/engine/tae/blockio/pipeline.go

Some prefetch requests do not have keys, but the reader is set, and judgment conditions need to be added.
issue #12912

Fix PrefetchFile interface:1.0-dev (#12906)

---

pkg/logservice/service_bootstrap.go
pkg/logservice/service_bootstrap_test.go

issue #12891
there is no default fileservice instance, so we need to get a fileservice
instance explicitly, otherwise, a "service not found" error will be raised.

[bug] BR: fix bug when restore data

---

pkg/sql/compile/sql_executor.go

issue #
fix build plan func not set in sql executor. If in has any conflict, need retry and found table def changed, need rebuild plan.

fix build plan func not set in sql executor

---

pkg/sql/compile/sql_executor.go

issue #
fix build plan func not set in sql executor cherry pick 1.0

fix build plan func not set in sql executor cherry pick 1.0

---

pkg/sql/compile/sql_executor.go

issue #
fix build plan func not set in sql executor, cherry pick

fix build plan func not set in sql executor to 1.1-dev

---

pkg/vm/engine/disttae/reader.go

this PR: https://github.com/matrixorigin/matrixone/pull/12896 had make all TableDef in disttae as the same. then this bug was fixed.
Approved by: @nnsgmsone
issue https://github.com/matrixorigin/matrixone/issues/12797
cherry-pick PR 12983

cherry-pick: remove unused tag logic

---

pkg/lockservice/service_remote.go
pkg/lockservice/service_remote_test.go

issue #12544 
Fix hung in remote lock if cn restart quickly, it will call remote lock on rpc io goroutine, and block all remote requests.
Assuming that we have cn0, cn1, and table1, we consider the following timing:
1. at time t0, cn0 obtains the t1 lock table, and the lock-table bind is t1-cn0-table1-version1.
2. at time t1, cn0 down.
3. at time t2, cn0 restarted, and (t2-t1) < cfg.KeepBindTimeout，so lock-table allocator will keep
the bind t1-cn0-table1-version1 valid
4. cn1 try to lock table1 and gets the binding t1-cn0-table1-version1 from allocator or local cache, then
sends a lock request to cn0.
5. cn0 receive the lock request, but the lock-table bind is t1-cn0-table1-version2, and cn0 cn0 will consider
this lock-table bind to be a remote lock table, because the serviceID(t1-cn0) != …

fix hung in remote lock if cn restart quickly to 1.1

---

pkg/lockservice/service_remote.go
pkg/lockservice/service_remote_test.go

issue #12554
Fix hung in remote lock if cn restart quickly, it will call remote lock on rpc io goroutine, and block all remote requests.
Assuming that we have cn0, cn1, and table1, we consider the following timing:
1. at time t0, cn0 obtains the t1 lock table, and the lock-table bind is t1-cn0-table1-version1.
2. at time t1, cn0 down.
3. at time t2, cn0 restarted, and (t2-t1) < cfg.KeepBindTimeout，so lock-table allocator will keep
the bind t1-cn0-table1-version1 valid
4. cn1 try to lock table1 and gets the binding t1-cn0-table1-version1 from allocator or local cache, then
sends a lock request to cn0.
5. cn0 receive the lock request, but the lock-table bind is t1-cn0-table1-version2, and cn0 cn0 will consider
this lock-table bind to be a remote lock table, because the serviceID(t1-cn0) != …

fix hung in remote lock if cn restart quickly to 1.0-dev

---

pkg/cnservice/upgrader/upgrader.go
pkg/util/internalExecutor/internal_executor.go

issue # https://github.com/matrixorigin/MO-Cloud/issues/1859
`mo_indexes` is a multi-tenant table. so the upgrade should happen for all the tenants. Previously, the upgrade was run without tenant info.

[BugFix]: Multi-Tenant upgrade logic for `mo_catalog.mo_indexes` 

---

pkg/cnservice/upgrader/upgrader.go

issue # https://github.com/matrixorigin/MO-Cloud/issues/1859
cherry-pick PR #13057 to 1.1-dev: Multi-Tenant upgrade logic for mo_catalog.mo_indexes

cherry-pick PR 13057 to 1.1-dev: [BugFix]: Multi-Tenant upgrade logic for mo_catalog.mo_indexes

---

pkg/frontend/server.go
pkg/proxy/handler.go
pkg/proxy/mysql_conn_buf.go
pkg/proxy/mysql_conn_buf_test.go

issue #1781 moc1781
1，最大数据包长度判断错误。
2，增加proxy 连接日志

cherrypick: fix max packet len (#13086)

---

pkg/proxy/rebalancer.go
pkg/proxy/rebalancer_test.go
pkg/proxy/tunnel.go

issue https://github.com/matrixorigin/MO-Cloud/issues/1834 https://github.com/matrixorigin/MO-Cloud/issues/1463
when proxy do rebalance and try to transfer some connections to
other CNs, the connections turns out to be some should not be transferred.
So we should pick up some correct connections to do the transferring.

[bug] proxy: rebalance connections to wrong cns.

---

pkg/frontend/authenticate.go
pkg/frontend/stmt_kind.go

issue #13132
1.The reason for the previous error is that the table mo_mysql_compatibility_mode is deleted first, and when the database is deleted later, the data will be deleted from this table, which results in the transaction getting stuck.
2.Changing the order of deleting tables now solves the problem

fix commit an active transaction when drop database

---

pkg/cnservice/server.go
pkg/cnservice/types.go
pkg/txn/client/client.go
pkg/txn/client/client_test.go

issue #13115 
Add a new config "normal-state-no-wait" in CN to control whether it
returns an error or waits when the txn client is in pause state.
The configuration value is false by default, which means that if the txn
client is in pause state, it will wait until it changes to nromal state. Otherwise,
just return an error.

[enhancement] txnClient: it waits until txn client is in normal state.

---

pkg/sql/colexec/lockop/lock_op.go

issue https://github.com/matrixorigin/MO-Cloud/issues/1884
make lock op can deal with const null
当update一个包含unique key表的时候。
我们会用原表left join unique key的隐藏表来找到要更新的pk。但是有时候left join的隐藏表的数据为空，这个时候 left join是把它置为 const null。
这里增加了对这种情况的处理

make lock op can deal with const null

---

pkg/sql/compile/scope.go
pkg/sql/compile/scopeRemoteRun.go
pkg/sql/plan/deepcopy.go

issue # https://github.com/matrixorigin/MO-Cloud/issues/1881
1. The panic is converted to moerror. However, this moerror is not returned to the callee, resulting in suppression of panic.
2. The internal executor returns `err = nil`, even when the pipeline panics. Introducing a logger to verify the root cause for this issue.
NOTE: I will cherry-pick this PR to master.

[BugFix]: Deep Copy missing parts + Panic suppression + Adding a debug log.

---

pkg/sql/colexec/lockop/lock_op.go

make lock op can deal with const null
当update一个包含unique key表的时候。
我们会用原表left join unique key的隐藏表来找到要更新的pk。但是有时候left join的隐藏表的数据为空，这个时候 left join是把它置为  const null。 这里增加了对这种情况的处理
Approved by: @zhangxu19830126, @m-schen
issue https://github.com/matrixorigin/MO-Cloud/issues/1884
cherry pick 13143 to 1.1-dev

make lock op can deal with const null (#13143)

---

pkg/sql/compile/scope.go
pkg/sql/compile/types.go
pkg/vm/types.go

some pipeline (with lock_op operator) cannot execute remotely.
Approved by: @nnsgmsone
issue #13119
cherry-pick the pr #13166

[cherry-pick] some pipeline cannot execute remotely (#13166)

---

etc/launch-tae-compose/config/cn-0.toml
etc/launch-tae-compose/config/cn-1.toml
etc/launch-tae-compose/config/log.toml
etc/launch-tae-compose/config/tn.toml
pkg/fileservice/aws_sdk_v1.go
pkg/fileservice/aws_sdk_v2.go
pkg/fileservice/minio_sdk.go
pkg/fileservice/object_storage_arguments.go

issue #13164 
fileservice: load custom ca files in NewAwsSDKv2
etc: add cert-files configs
fileservice: more logs
fileservice: load custom cert files in AwsSDKv1 and MinioSDK

fileservice: add ObjectStorageArguments.CertFiles

---

go.mod
go.sum
pkg/common/system/system.go
pkg/sql/plan/function/func_unary.go

issue #13170
- support getting resources in cgroup v2 environment.
- remove two functions: mo_memory("max-usage") and mo_memory("fail-count"),
as there are no data in cgroup v2.

[enhancement] system: support resource in cgroup v2.

---

pkg/vm/engine/tae/blockio/writer.go

issue #12741 
The bf of the current object is not used, but it is written and read every time to occupy memory space, so it is removed.

Remove object's bloom filter

---

pkg/frontend/authenticate.go
pkg/frontend/session.go
pkg/frontend/txn.go

… no accout in mo_account table
issue #13235
Account is created successfully from the record in statement_info but no accout in mo_account table

Resolve the issue of inconsistent create account results-1.0-dev

---

pkg/util/errutil/context.go
pkg/util/trace/config.go

issue https://github.com/matrixorigin/matrixone/issues/12491
pick From #13100
change:
1. copy Span.SpanContext if passing Error to MOCollector.
fix DATA RACE case, between
- span.Reset(), after release MOSpan after in span.End()
- span.SpanContext(), after passing Error to MOCollector. The collector will get the span's Context info, which may already reset by span.Reset().
Approved by: @zhangxu19830126

pick: fix DATA RACE

---

pkg/vm/engine/tae/catalog/segment.go

issue #13147 
w/o clone, it will always reference the whole object metadata

clone zonemap to avoid reference the whole object metadata 

---

pkg/sql/plan/function/func_mo.go

issue #13352 
fix Incorrect use of proc.ctx in the builtin func

fix Incorrect use of proc.ctx in the builtin func

---

pkg/vm/engine/tae/catalog/segment.go

w/o clone, it will always reference the whole object metadata
Approved by: @LeftHandCold
issue #13147
clone zonemap to avoid reference the whole object metadata

clone zonemap to avoid reference the whole object metadata  (#13334) to 1.0-dev

---

pkg/vm/engine/tae/catalog/segment.go

w/o clone, it will always reference the whole object metadata
Approved by: @LeftHandCold
issue #13147 
clone zonemap to avoid reference the whole object metadata

clone zonemap to avoid reference the whole object metadata  (#13334) to 1.1-dev

---

pkg/sql/plan/function/func_mo.go

fix Incorrect use of proc.ctx in the builtin func
Approved by: @m-schen
issue #13352 
fix Incorrect use of proc.ctx in the builtin func

fix Incorrect use of proc.ctx in the builtin func (#13353)

---

pkg/frontend/mysql_cmd_executor.go
pkg/frontend/session.go
pkg/frontend/txn.go

讨论见：https://github.com/matrixorigin/docs/blob/main/design/system_view.md#%E4%BC%9A%E8%AF%9D
策略调整：
1, 信息最多持续时间3秒。
一个语句执行完成，最多3秒后，相关的信息会被清空。
一个语句执行完成，如果下一条语句在3秒内开始执行，部分信息就是下一条的。
```
//例子
|---sql---|--空闲3s---|---下一个sql---|
/|\        /|\     /|\
|          |       |
|          |       |---------看到部分信息被更新，不是所有信息同时更新。
|          |
|          |-------------看不到第一个sql的信息
|
看到第一个sql的信息。
```
2. txn_id。
- 事务的生命周期可能长于sql语句。例如：begin开启事务后，执行了一些语句。但是在commit/rollback之前事务一直存在。但此时可能没有执行语句。
- commit/rollback之后，不论成果与否，事务都会结束。此时txn_id会被清空。
- 事务创建失败。txn_id也为空
issue #https://github.com/matrixorigin/MO-Cloud/issues/1932
update mo_sessions view

update mo_sessions view (#1.0-dev)

---

pkg/sql/compile/compile.go

fix bug: throw incorrect err type.
在Compile.runonce之前执行的lock metatable，应该是只有 ErrTxnNeedRetry 或者 ErrTxnNeedRetryWithDefChanged 这两种情况才表明原始表的表结构或者名字有变更。其他情况应该正常抛出异常。
Approved by: @nnsgmsone
issue https://github.com/matrixorigin/matrixone/issues/13152
fix bug: throw incorrect err type.

fix bug: throw incorrect err type (#13300)

---

pkg/frontend/variables.go

add more detail to get variable  error log
issue #13224 
add more detail to get variable  error log

add more detail to get variable  error log (#1.1-dev)

---

pkg/vm/engine/disttae/reader.go

issue #12876
since prefetch already write memcache, do not need to write again when read

do not write memcache for normal scan

---

pkg/cnservice/server.go

issue #13399 
cn service should get the global logger.

cn-service use the global log level

---

pkg/util/trace/impl/motrace/Aggr.go
pkg/util/trace/impl/motrace/report_statement.go

…ing the incorrect statementinfo (#12619)
There are data racings in the bufferpipe - aggregator step.
1.
If the statementinfo object being added to the aggregator, then statementinfo might be modified outside.
So take a clone here,
2. Free the statementinfo afterwards
Approved by: @xzxiong
issue # https://github.com/matrixorigin/matrixone/issues/12432
https://github.com/matrixorigin/matrixone/issues/10382
https://github.com/matrixorigin/matrixone/issues/10382
fit the aggregator stmt racing 
add logs for further investigation

Cherry pick stmt report racing fix

---

pkg/proxy/client_conn.go
pkg/proxy/client_conn_test.go
pkg/proxy/event.go
pkg/proxy/event_test.go
pkg/proxy/mysql_conn_buf.go
pkg/proxy/server_conn.go
pkg/proxy/server_conn_test.go
pkg/proxy/util.go
pkg/proxy/util_test.go

issue #12955
proxy cannot parse `use db` statement correctly, which
cause session info missing when proxy transfers connections.

[bug] proxy: fix mysql protocal parsing issue.

---

pkg/util/trace/impl/motrace/Aggr.go
pkg/util/trace/impl/motrace/report_statement.go

…ing the incorrect statementinfo (#12619)
There are data racings in the bufferpipe - aggregator step.
1.
If the statementinfo object being added to the aggregator, then statementinfo might be modified outside.
So take a clone here,
2. Free the statementinfo afterwards
Approved by: @xzxiong
issue # https://github.com/matrixorigin/matrixone/issues/12432
https://github.com/matrixorigin/matrixone/issues/10382
https://github.com/matrixorigin/matrixone/issues/10382
fit the aggregator stmt racing 
add logs for further investigation

1.1 cherry pick stmt racing fix

---

pkg/frontend/mysql_cmd_executor.go
pkg/sql/plan/explain/marshal_model.go
pkg/util/trace/impl/motrace/buffer_pipe_test.go
pkg/util/trace/impl/motrace/report_statement.go

remove success field from ExplainData
Approved by: @xzxiong, @badboynt1, @qingxinhome, @aunjgr
issue #13197
remove success field from ExplainData

remove success field from ExplainData (#13407)

---

pkg/vm/engine/disttae/cache/catalog.go
pkg/vm/engine/disttae/cache/types.go
test/distributed/cases/pessimistic_transaction/create_table.result
test/distributed/cases/pessimistic_transaction/create_table.sql

issue #https://github.com/matrixorigin/MO-Cloud/issues/2009
对于类似于以下场景:
```sql
begin;
create table t(a int);
alter table t add column `remark` varchar(100);
commit;
```
会出现表找不到的情况，本质原因是因为上述事务会产生以下logtail:
```
k0 = insert (t(name)+10(tableid) + 100(timestamp))
k1 = delete (t(name)+10(tableid) + 100(timestamp))
k2 = insert (t(name)+12(tableid) + 100(timestamp))
```
因为多版本k的比较代码存在如下的代码:
```go
if a.deleted && !b.deleted { //deleted item head first
return true
}
```
所以会生成k1, k2, k0类似于这样的序列，这样的情况会导致表找不到。修改为delete只比需要删除的key大来修正这个问题

Fix the wrong compare of catalog cache's mvcc

---

pkg/vm/engine/disttae/types.go

issue #12876
slow down prefetch speed to reduce memory allocation for 1.1-dev

slow down prefetch speed for 1.1-dev

---

pkg/frontend/mysql_cmd_executor.go
pkg/frontend/mysql_cmd_executor_test.go
pkg/frontend/mysql_protocol.go
pkg/frontend/resultset.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/1897
double and float 类型编码不对会导致jdbc对后面的数据读取的时候越界，所以对这两种类型的编码进行修复

fix wrong rowpackage encoding for double and float types

---

pkg/fileservice/lrucache/shard.go
pkg/fileservice/lrucache/types.go

issue #13434
* 目前的代码存在data race，导致出现这个问题的原因是内存复用导致的，主要是freeItem的时候无法保证item没有被其他地方引用，先临时增大了锁的粒度来处理这个问题。后续考虑增加一个reference count来确保可以正确释放

Fix the data race of lru

---

pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
pkg/util/metric/v2/txn.go
pkg/vm/engine/tae/db/test/util_test.go
pkg/vm/engine/tae/txn/txnbase/helper.go
pkg/vm/engine/tae/txn/txnbase/txnmgr.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/2010
cherry-pick to 1.0: #13443
cherry-pick to 1.1:  #13446
adding  some metrics and logs to inspect why situations like this occurred:
|

adding more metrics and log for onPrepareWAL

---

pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
pkg/util/metric/v2/txn.go
pkg/vm/engine/tae/db/test/util_test.go
pkg/vm/engine/tae/txn/txnbase/helper.go
pkg/vm/engine/tae/txn/txnbase/txnmgr.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/2010
adding  some metrics and logs to inspect why situations like this occurred:
|

sync to 1.0: adding more metrics and log for onPrepareWAL

---

pkg/frontend/authenticate.go
pkg/frontend/mysql_cmd_executor.go
pkg/frontend/session.go
pkg/util/trace/impl/motrace/report_statement.go
pkg/util/trace/impl/motrace/statistic/stats_array.go

issue #13384
changes:
1. reset backgroud session id as frontend query's statement id.
2. reset fronted query's txn-id if the txn-id is non-setted, by using background session txn-id
- default skip the background transaction, which DO check privileges. 
3. fix stmt reset while do free
4. improve statement aggr logic, if all aggr stmts in the same txn, not reset the txn-id. @gavinyue

Relate frontend query and background session query, v1.1

---

pkg/fileservice/object_storage_arguments.go
pkg/fileservice/object_storage_arguments_test.go

issue #13468 
do not leak credentials arguments to logs.

fileservice: strip credential arguments from logs (#13492)

---

pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
pkg/util/metric/v2/txn.go
pkg/vm/engine/tae/db/test/util_test.go
pkg/vm/engine/tae/txn/txnbase/helper.go
pkg/vm/engine/tae/txn/txnbase/txnmgr.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/2010
adding  some metrics and logs to inspect why situations like this occurred:
|

sync to 1.1: adding more metrics and log for onPrepareWAL

---

pkg/frontend/variables.go
test/distributed/cases/database/system_variables.result

…… (#12682)
MySql server default setting is 64mb
The server's default [max_allowed_packet](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_max_allowed_packet) value is 64MB
Approved by: @fengttt, @daviszhen, @heni02
issue #https://github.com/matrixorigin/matrixone/issues/12489
MySql server default setting is 64mb
The server's default [max_allowed_packet](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_max_allowed_packet) value is 64MB

Cherry pick max package size change

---

pkg/sql/util/eval_expr_util.go

fix insert blob value with '0x' begin
Approved by: @aunjgr
issue #https://github.com/matrixorigin/MO-Cloud/issues/2030
fix insert blob value with '0x' begin

fix insert blob value with '0x' begin (#1.1-dev)

---

pkg/frontend/mysql_cmd_executor.go
pkg/frontend/mysql_cmd_executor_test.go
pkg/frontend/mysql_protocol.go

double and float 类型编码不对会导致jdbc对后面的数据读取的时候越界，所以对这两种类型的编码进行修复
issue #https://github.com/matrixorigin/MO-Cloud/issues/1897
fix wrong rowpackage encoding for double and float types

fix wrong rowpackage encoding for double and float types (#1.1-dev)

---

pkg/sql/compile/compile.go

issue #13527 
add more log info when scan workload among multi CNs not balanced

add more log info when scan workload among multi CNs not balanced

---

pkg/proxy/client_conn.go
pkg/proxy/config.go
pkg/proxy/handshake.go

issue https://github.com/matrixorigin/MO-Cloud/issues/1899
make a TLS connect timeout value configurable.

[enhancement] proxy: make a timeout value configurable.

---

pkg/sql/compile/compile.go
pkg/sql/plan/build_load.go

issue #13485
for load statement, if parallel then go shuffle, else go sendToAny

[Bug]: LOAD DATA Report internal error: message body 157032805 is too large, max is 104857600

---

pkg/sql/compile/compile.go
pkg/sql/compile/sql_executor.go
pkg/sql/compile/types.go
pkg/vm/engine/disttae/txn.go
pkg/vm/engine/disttae/txn_database.go
pkg/vm/engine/disttae/types.go

issue #11917
When processing a user-entered sql, if another sql is executed using the internal executor, if a conflict occurs and retry is required in RC mode, it will be retried in the internal sql executor, resulting in the user-entered sql not being retried

fix rollback statement incorrect to 1.1

---

pkg/frontend/mysql_cmd_executor.go
pkg/frontend/mysql_cmd_executor_test.go
pkg/frontend/mysql_protocol.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/1897
Revert "fix wrong rowpackage encoding for double and float types"

Revert "fix wrong rowpackage encoding for double and float types (#1.1-dev)"

---

pkg/vm/engine/disttae/logtailreplay/partition_state.go

issue #13643 
The deletes calculation error in PartitionState caused the block to be accidentally deleted in DirtyBlocks. In the end, mergeread is not executed, and there will be two rows of the same pk.

Fix the bug of DirtyBlocks removing wrong block

---

pkg/fileservice/local_etl_fs_test.go
pkg/fileservice/local_fs.go

issue #12052 
ignore invalid symlink in local fs list.

fileservice: ignore invalid symlink in LocalFS.List and LocalETLFS

---

pkg/vm/engine/tae/catalog/segment.go
pkg/vm/engine/tae/catalog/table.go
pkg/vm/engine/tae/iface/data/block.go
pkg/vm/engine/tae/rpc/handle.go
pkg/vm/engine/tae/rpc/inspect.go
pkg/vm/engine/tae/rpc/utils.go
pkg/vm/engine/tae/tables/ablk.go
pkg/vm/engine/tae/tables/blk.go

issue #13513
- get block information at runtime
- recover panic in tn when executing mo-ctl inspect cmd

add blk info tool

---

pkg/vm/engine/tae/catalog/segment.go
pkg/vm/engine/tae/catalog/table.go
pkg/vm/engine/tae/iface/data/block.go
pkg/vm/engine/tae/rpc/handle.go
pkg/vm/engine/tae/rpc/inspect.go
pkg/vm/engine/tae/rpc/utils.go
pkg/vm/engine/tae/tables/ablk.go
pkg/vm/engine/tae/tables/blk.go

issue https://github.com/matrixorigin/matrixone/issues/13513
- get block information at runtime
- recover panic in tn when executing mo-ctl inspect cmd

add blk info tool 1.1 (#13598)

---

pkg/sql/colexec/lockop/lock_op.go
pkg/sql/colexec/lockop/lock_op_no_txn.go
pkg/sql/colexec/lockop/lock_op_test.go
pkg/sql/colexec/lockop/types.go
pkg/sql/compile/ddl.go

issue #13714
在lock meta table的时候，relation 其实已经取出来过一次了。
在这种情况下，可以传进去，避免在  hasNewVersionInRangeFunc  再通过 GetRelationById 再获取一次
所以修改了 hasNewVersionInRangeFunc 实现的参数，增加了relation的传入，其他的普通lock的话，relation传入nil，跟旧逻辑保持一致。

improve lock rows

---

pkg/sql/compile/util.go

issue # https://github.com/matrixorigin/matrixone/issues/3783
- There is a typo T_decimal128

[BugFix]: Typo in genCreateIndexTableSql

---

pkg/lockservice/lock_table_local.go
pkg/lockservice/lock_table_remote.go
pkg/lockservice/service_test.go
pkg/lockservice/txn.go
pkg/lockservice/txn_test.go

issue #13444
fix unlock with bind changed.
txn1 hold key1 on bind version 0
txn1 commit success
dn restart
txn2 hold key1 on bind version 1
txn1 unlock.

fix unlock with bind changed to 1.1

---

pkg/vm/engine/tae/catalog/catalog.go
pkg/vm/engine/tae/catalog/metamvccnode.go
pkg/vm/engine/tae/catalog/object.go
pkg/vm/engine/tae/db/test/compatibility/cases.go
pkg/vm/engine/tae/db/testutil/engine.go
pkg/vm/engine/tae/logtail/utils.go

Replay name and extent of old objects from meta location
issue #13793 
Replay name and extent for old object

Replay name and extent for old object, cherry-pick #13795

---

pkg/sql/colexec/preinsertunique/preinsertunique.go
pkg/sql/plan/build_dml_util.go

PK column of Hidden Index Table not updated when PK is a Composite Primary Key
Approved by: @m-schen, @ouyuanning
issue #13674
PK column of Hidden Index Table not updated when PK is a Composite Primary Key

handle unique index table update error (#13746)

---

.github/workflows/e2e-upgrade.yaml

CI: increase the timeout of upgrade ci for 1.1-dev

---

pkg/frontend/show_account.go
pkg/vm/engine/tae/catalog/database.go
pkg/vm/engine/tae/db/test/storage_usage_test.go
pkg/vm/engine/tae/logtail/storage_usage.go
pkg/vm/engine/tae/logtail/utils.go
pkg/vm/engine/tae/rpc/handle.go
pkg/vm/engine/tae/rpc/inspect.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/2146
1. correct the account type in the storage usage bat to uint64.
2. adding more tests to test the behavior of the usage cache.
3. one way to provide support is to transfer the usage to the right account.

fix account decode err when replay usage from old ckp

---

pkg/sql/plan/build_dml_util.go

issue #13830
fuzzy filter有些细节没有和次级索引对齐, 测load的时候发现的
下面的indexdef.Parts[1]不是fuzzy 需要的col def

[fix] : make fuzzy filter compatible with secondary indexes

---

pkg/vm/engine/tae/catalog/database.go

issue #13915
When rollback transactions of creating table, nn.Node() may be nil.

fix checkAddNameConflictLocked

---

pkg/sql/compile/compile.go
pkg/sql/compile/ddl.go
pkg/sql/compile/fuzzyCheck.go
pkg/sql/compile/runtime_filter.go
pkg/sql/compile/scope.go
pkg/sql/compile/types.go
pkg/sql/compile/util.go

issue #13908 
some error was unhandled and it may cause hung.
removed some unused codes like redundant type conversion.

[cherry-pick] pr #13909 fix some unhandled error and redundant codes

---

pkg/vm/engine/tae/catalog/database.go

issue #13915 
When rollback transactions of creating table, nn.Node() may be nil.

fix checkAddNameConflictLocked, cherry-pick #13916

---

pkg/frontend/authenticate.go
pkg/frontend/authenticate2.go
pkg/frontend/authenticate2_test.go
pkg/sql/plan/utils.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/2162
restrict mo_ctl privilege.
only can be executed by sys moadmin role.

fix mo_ctl

---

pkg/frontend/show_account.go
pkg/util/metric/v2/dashboard/grafana_dashboard_task.go
pkg/util/metric/v2/metrics.go
pkg/util/metric/v2/task.go
pkg/util/metric/v2/txn.go
pkg/vm/engine/tae/db/test/storage_usage_test.go
pkg/vm/engine/tae/logtail/storage_usage.go
pkg/vm/engine/tae/rpc/inspect.go

issue #13920
1. add sync.lock to avoid data race when cache.IsExpired().
2. split the show accounts duration metric to different phases.

sync_to_1.1: adding lock to cn storage usage cache to avoid data race 

---

pkg/lockservice/lock_table_allocator.go

issue #13789
* 在不需要更新时间的时候不应该更新时间，以免导致探活失效

[cherry-pick] #13941 Remove an incorrectly timed dropout update that invalidates a live probe

---

pkg/fileservice/aliyun_sdk.go

issue #13906 
do not set role arn from env if not oidc credential

fileservice: do not set default role arn from os env

---

pkg/lockservice/service.go
pkg/lockservice/service_test.go

issue #14008
fix panic if allocating lock table from dn failed

fix panic if allocating lock table from dn failed to 1.1

---

pkg/fileservice/disk_cache.go
pkg/fileservice/disk_cache_test.go
pkg/fileservice/fifocache/bench_test.go
pkg/fileservice/fifocache/fifo.go
pkg/fileservice/fifocache/fifo_test.go
pkg/fileservice/fifocache/queue.go
pkg/fileservice/fifocache/queue_test.go
pkg/fileservice/local_fs.go
pkg/fileservice/s3_fs.go

issue #12506 
fileservice: add fifocache package
fifocache: add get benchmarks
fifocache: naming fixes
fifocache: add Cache.capacity, used
fifocache: add Queue
fifocache: implement evict
fifocache: add Get Set mixed benchmark
fifocache: refine eviction
fifocache: refine eviction
fileservice: refine disk cache with fifo cache
fileservice: refine disk cache
fileservice: delete DiskCache.fileExists

fileservice: refine disk cache with fifo cache

---

pkg/vm/engine/tae/rpc/handle.go

issue #13983 
fix the time.Since not deferred

sync_to_1.1: defer on time.since not work

---

pkg/lockservice/service.go
pkg/lockservice/service_test.go

issue #14008
fix panic if allocating lock table from dn failed

fix panic if allocating lock table from dn failed

---

pkg/sql/colexec/server.go
pkg/sql/compile/scopeRemoteRun.go
pkg/sql/compile/scopeRemoteRunTypes.go

issue #14009 #14024 #14032
remove an error when the required process was done.

[cherry-pick] #14052 removed a context done error at the remote run stage.

---

pkg/fileservice/local_fs.go
pkg/fileservice/s3_fs.go
pkg/frontend/mysql_cmd_executor.go
pkg/util/trace/impl/motrace/statistic/stats_array.go

issue #13211 #13982
improve cpu stats by subtracting io duration

fix-cpu-stats

---

pkg/vm/engine/disttae/logtailreplay/blocks_iter.go

- [x ] BUG
issue #14114 
issue #13788 
1.  ref to https://github.com/matrixorigin/matrixone/pull/14142

fix bug relate to "invalid file path"

---

pkg/fileservice/disk_cache.go
pkg/fileservice/fifocache/fifo.go

issue #12739 
The disk cache may delete files, and also delete the cache.

fileservice: fix DiskCache.DeletePaths

---

pkg/common/morpc/client.go
pkg/common/morpc/client_test.go

issue #14149
disable auto create backend automatically in background by default

disable auto create backend automatically in background by default to 1.1

---

pkg/lockservice/service_remote.go
pkg/lockservice/service_remote_test.go
pkg/pb/lock/lock.go

issue #14241
fix bind changed not handled

fix bind changed not handled to 1.1

---

pkg/vm/engine/disttae/engine.go
pkg/vm/engine/disttae/reader.go
pkg/vm/engine/disttae/txn.go
pkg/vm/engine/disttae/txn_table.go
pkg/vm/engine/disttae/types.go

issue #https://github.com/matrixorigin/matrixone/issues/14138
there is a tiny probability that concurrent write on the map txn.blockId_tn_delete_metaLoc_batch.
this PR adds an RWMutex to protect it

sync to 1.1: adding RWMutex to avoid concurrent map write

---

pkg/logservice/store_hakeeper_check.go
pkg/logservice/store_hakeeper_check_test.go

issue #https://github.com/matrixorigin/matrixone/issues/8438
augment the `hakeeperDefaultTimeout` to avoid `TestHAKeeperCanBootstrapAndRepairShards` failed.
this change only happened when UT.

sync to 1.1: augment the hakeeperDefaultTimeout in ut to avoid TestHAKeeperCanBootstrapAndRepairShards failed

---

pkg/sql/plan/function/func_mo.go
pkg/vm/engine/disttae/cache/catalog.go
pkg/vm/engine/disttae/engine.go
pkg/vm/engine/disttae/logtailreplay/partition_state.go
pkg/vm/engine/disttae/txn_table.go
test/distributed/cases/function/table_func_metadata_scan.sql

issue #13013 #13151 
1. adding debug log to dump catalog cache  when `ExpectedEOB` for #13151 
2. avoid loading object meta when object stats are valid when `mo_table_size` and `metadata_scan`.

sync_to_1.1: avoiding load object meta when object stats are valid in `mo_table_size` and `metadata_scan`

---

pkg/sql/plan/build_dml_util.go

issue https://github.com/matrixorigin/matrixone/issues/14137 https://github.com/matrixorigin/matrixone/issues/14139
当 更新/删除 unique key和2cnd key隐藏表的时候，是用 原表 left join隐藏表 ,取出隐藏表要更新/删除的 row id。
这个时候隐藏表的数据可能是null， 于是删除的batch的这一列的值全部是null，
（但是实际删的时候，不会去读null的那个属性，而是直接用的data里的数据，而这些数据都是vector被复用之前的错误数据。
这里在delete算子前加个filter算子筛选掉null值的行

fix bug: delete incorrect rows for hidden tables

---

pkg/fileservice/aliyun_sdk.go
pkg/fileservice/aws_sdk_v2.go
pkg/fileservice/config.go
pkg/fileservice/get.go
pkg/fileservice/minio_sdk.go
pkg/fileservice/object_storage_arguments.go
pkg/fileservice/s3_fs.go
pkg/fileservice/s3_fs_test.go

fileservice: add ObjectStorageArguments.NoDefaultCredentials
issue #14113
add config to disable default credentials.

fileservice: add NoDefaultCredentialsForETL

---

pkg/frontend/mysql_cmd_executor.go
pkg/frontend/session_test.go
pkg/frontend/stmt_kind.go
pkg/frontend/txn.go
test/distributed/cases/optimistic/autocommit.result
test/distributed/cases/optimistic/autocommit_1.result
test/distributed/cases/optimistic/autocommit_1.sql
test/distributed/cases/optimistic/transaction_enhance.result
test/distributed/cases/pessimistic_transaction/isolation_2.result
test/distributed/cases/statement_query_type/statement_query_type.result

issue #https://github.com/matrixorigin/MO-Cloud/issues/2343
issue #https://github.com/matrixorigin/MO-Cloud/issues/2048
之前的设计，限制set 用在活跃事务中。原因是早期mo的bug奇多，为了避免踩坑，做了限制。
现在由于与mysql 应用的兼容性原因。尝试放开。
1，set @autocommit = ON:
从  OFF 到 ON，mo会commit事务。如果commit失败，autocommit 标志不会设置成功。

cherry-pick to main : fix setvar in the active transaction

---

pkg/frontend/export.go
pkg/frontend/mysql_cmd_executor.go
pkg/frontend/output.go

issue #https://github.com/matrixorigin/matrixone/issues/14127
原因：
业务端的代码早期是围绕aoe、tae设计的。tae的事务是SI，对于select，SI事务不会提交失败。所以只要计算引擎不出错，就先响应client了。现在是有分布式事务，commit也可能失败。那么需要在commit后，根据结果来响应不同值。
修改：
对于select,select ... into outfile，ShowXXX，Explain，ExplainAnalyze 有结果集的语句，等事务提交后，根据结果响应client。
影响：
事务commit会比较耗时，响应client会有延长时间。
进一步：
1.2会有重构的任务。会改进这块的代码。

cherry-pick:fix response of select after the commit ends

---

pkg/sql/plan/base_binder.go
pkg/sql/plan/function/function.go
pkg/sql/plan/utils.go

issue #13987
serial must be constant-folded, to allow IN filter on composed primary key

allow serial/serial_full to be constant-folded

---

pkg/sql/plan/build_constraint_util.go
pkg/sql/plan/build_insert.go

issue #13987
use IN instead of OR for cpk and fix a typo

clean up func getPkValueExpr to use IN instead of OR for cpk

---

pkg/sql/compile/compile.go
pkg/sql/plan/build_load.go

issue # https://github.com/matrixorigin/MO-Cloud/issues/2440
reading compressed file when load is in single parallel, no need to use shuffle.

dont use shuffle when load file is compressed to 1.1-dev

---

pkg/frontend/show_account.go
pkg/vm/engine/tae/catalog/dbmvccnode.go
pkg/vm/engine/tae/db/test/storage_usage_test.go
pkg/vm/engine/tae/logtail/storage_usage.go
pkg/vm/engine/tae/logtail/utils.go
pkg/vm/engine/tae/rpc/inspect.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/2439
in the old version, the sizes of a single table were stored in several vector rows, but in the new implementation, all table sizes accumulated in one row.
the new decode code ignores this difference causing some storage usage data to be counted twice.

sync to 1.1: fix the bug of storage usage double counting

---

pkg/sql/plan/function/func_binary.go

for unflushed rows in memtable, even primary key column is not sorted
issue https://github.com/matrixorigin/MO-Cloud/issues/2408
fix wrong output

don't assume input vector to be sorted in prefix_eq

---

pkg/vm/engine/tae/logtail/storage_usage.go

issue #https://github.com/matrixorigin/matrixone/issues/14456
fix the data race when ickp

sync to 1.1: fix data race when ickp

---

pkg/frontend/show_account.go
pkg/vm/engine/tae/db/operations.go
pkg/vm/engine/tae/db/operations.pb.go
pkg/vm/engine/tae/db/operations.proto
pkg/vm/engine/tae/logtail/storage_usage.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/2196
compatible backward, the old storage usage request method.
two changes in the new version:
all the RPC method codes have been changed.
unable to handle the response of the old version tn.
this fix adds a retry with the old method and handler when a not supported error occurs.

sync to 1.1: compatible backwards, the old storage usage reqeust method

---

pkg/sql/plan/build_load.go

issue #14463 
use moerr.IsMoErrCode

sql/plan: fix error checking code in checkFileExist

---

pkg/sql/plan/build_constraint_util.go
pkg/sql/plan/build_insert.go

issue #13987
use IN instead of OR for cpk and fix a typo
the special case of rowCnt == 1 is retained, otherwise the performance of tpcc will be significantly reduced.

clean up func getPkValueExpr

---

pkg/sql/plan/apply_indices.go
pkg/sql/plan/function/func_binary.go
pkg/sql/plan/function/func_prefix.go
pkg/sql/plan/function/operator_between.go

issue #12517 https://github.com/matrixorigin/MO-Cloud/issues/2408
memtable is not sorted by primary keys

don't assume input vector to be sorted in prefix_*

---

pkg/sql/plan/apply_indices.go
pkg/sql/plan/function/func_binary.go
pkg/sql/plan/function/func_prefix.go
pkg/sql/plan/function/operator_between.go

issue #12517
rows in memtable are not sorted by primary keys

cherry-pick index related commits to 1.1-dev

---

pkg/sql/plan/function/func_prefix.go

issue #14509
fix a panic caused by prefix_in on memtable

fix a panic caused by prefix_in on memtable

---

pkg/sql/plan/build_constraint_util.go
pkg/sql/plan/build_insert.go

Reverts matrixorigin/matrixone#14378

Revert "clean up func getPkValueExpr"

---

pkg/backup/tae.go
pkg/vm/engine/tae/catalog/metamvccnode.go
pkg/vm/engine/tae/containers/vector.go
pkg/vm/engine/tae/logtail/backup.go
pkg/vm/engine/tae/logtail/utils.go

The blocklist in TN1.1's metadata and checkpoint has been changed to objectlist. The Backup is not adapted. This PR solves this bug.
issue https://github.com/matrixorigin/MO-Cloud/issues/2359
The blocklist in TN1.1's metadata and checkpoint has been changed to objectlist. The Backup is not adapted. This PR solves this bug.

Backup adapt object (#14376)

---

pkg/sql/plan/apply_indices.go

issue https://github.com/matrixorigin/MO-Cloud/issues/2495
trigger index mechanism when we encounter filters like `a = ?` or `a = @some_var` on indexed column `a`

[opt] allow filters with parameter/variable to use index

---

pkg/sql/plan/function/func_prefix.go

issue #12517
vectors allocated from mempool are not zero-initialized and MUST be overwritten in function implementation.

fix wrong result caused by prefix_eq

---

pkg/sql/colexec/semi/join.go

issue #14530
semi join can skip probe if runtime filter push in_pred to probe side, but the vecs need to be adjusted according to output vecs

fix a bug of semi join when semi join can skip probe

---

pkg/vm/engine/disttae/txn_database.go
pkg/vm/engine/disttae/txn_table.go

* 因为不是所有的操作都会调用ranges，所以将更新table的wirteoffset的操作从ranges改为获取table的时候更新
Approved by: @triump2020
issue https://github.com/matrixorigin/matrixone/issues/14282
* 因为不是所有的操作都会调用ranges，所以将更新table的wirteoffset的操作从ranges改为获取table的时候更新

Move writeoffset update from Ranges to Relation (#14434)

---

pkg/sql/plan/apply_indices.go
pkg/sql/plan/runtime_filter.go

issue #14516 https://github.com/matrixorigin/MO-Cloud/issues/2495
cleanup the dummy items in BlockFilterList, and don't prevent runtime filter on small table

[opt] ensure runtime filter is deduced after applying index

---

pkg/sql/plan/explain/explain_expr.go

issue #14560
runtime filter could push a in predicate with thousands of values.
don't display all of that in explain.

[Tech Request]: don't display too long vector in explain

---

pkg/sql/plan/stats.go

issue #14559
blocknum in stats estimated too small, cause bad performance

[Bug]: [regression 2.7] internal error: send notify msg to dispatch operator timeout during tpch 1T queries and TPCH cost increaseed more than 25%

---

pkg/common/morpc/cfg.go
pkg/tnservice/cfg.go

issue #https://github.com/matrixorigin/matrixone/issues/14471
increasing the number of RPC server workers to allow higher parallel sessions.

sync to 1.1: increase the default val of the tn rpc worker

---

test/distributed/cases/join/leftjoin.result
test/distributed/cases/join/leftjoin.test

need to wait for flush complete in race mode
Approved by: @aressu1985
issue #14108
[Bug]: Incorrect explain in bvt with race enabled to 1.1-dev

[Bug]: Incorrect explain in bvt with race enabled to 1.1-dev
