- pkg/txn/client/operator.go
issue #12471
Fix txn commit error mapping.
> fix commit error mapping

- pkg/vm/engine/tae/db/scannerop.go
- pkg/vm/engine/tae/logtail/utils.go
- pkg/vm/engine/tae/mergesort/func.go
> reduce golang objects allocation during merge sort

- .github/workflows/ci.yml
- .github/workflows/e2e-compose.yml
- .github/workflows/e2e-standalone.yml
- .github/workflows/e2e_upgrade.yml
- .github/workflows/utils.yaml
> CI: modify regex for main

- pkg/txn/client/operator.go
issue #12471 
Fix txn commit error mapping.
> cherry pick fix commit error mapping

- pkg/cnservice/cnclient/client.go
issue #
restore pipeline max connections
> restore pipeline max connections

- test/distributed/cases/mo_cloud/mo_cloud.result
- test/distributed/cases/mo_cloud/mo_cloud.sql
> modify bvt case

- pkg/sql/compile/scope.go
> Remove unused code for recover

- pkg/util/metric/v2/dashboard/grafana_dashboard.go
- pkg/util/metric/v2/dashboard/grafana_dashboard_task.go
- pkg/util/metric/v2/metrics.go
- pkg/util/metric/v2/task.go
- pkg/vm/engine/disttae/reader.go
- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/tae/blockio/read.go
issue #
make task dashboard more concise
Before
After
all info can be found in one screen
> refactor task metric grafana dashboard

- optools/images/Dockerfile
> CI: change builder to 1.20.7

- pkg/util/metric/v2/dashboard/grafana_dashboard_logtail.go
- pkg/util/metric/v2/dashboard/grafana_dashboard_task.go
- pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
- pkg/util/metric/v2/metrics.go
- pkg/util/metric/v2/txn.go
- pkg/vm/engine/disttae/txn_table.go
issue #
1. adding more counter for ranges loading object meta 
2. fix some task metrics name err
> sync `metrics to ranges loading object meta` to 1.0-dev

- pkg/common/moerr/error.go
- pkg/common/moerr/error_no_ctx.go
- pkg/sql/plan/function/func_binary.go
- pkg/sql/plan/function/func_binary_test.go
issue #12513 #12514 #12516
fix convert_tz funtion
> fix convert_tz funtion

- pkg/sql/compile/compile.go
> fix using fs without shared(1.0-dev)

- test/distributed/cases/pessimistic_transaction/transaction_enhance.result
- test/distributed/cases/pessimistic_transaction/transaction_enhance.sql
issue #
https://github.com/matrixorigin/matrixone/issues/11774
> removeTag11774

- pkg/common/moerr/error.go
- pkg/common/moerr/error_no_ctx.go
- pkg/sql/plan/function/func_binary.go
- pkg/sql/plan/function/func_binary_test.go
fix convert_tz funtion
Approved by: @YANGGMM, @m-schen, @zhangxu19830126
issue #
> fix convert_tz funtion (1.0-dev)

- pkg/util/export/etl/db/db_holder.go
- pkg/util/export/etl/db/db_holder_test.go
- pkg/util/export/merge.go
Approved by: @fengttt, @xzxiong
issue #
> Skip file upload if record already existed  (#12496)

- pkg/sql/compile/compile.go
- pkg/sql/compile/scope.go
Reverts matrixorigin/matrixone#12584
> Revert "[Bug]: After a long run, the tpch get wrong result"

- pkg/frontend/mysql_protocol.go
- pkg/frontend/util.go
- pkg/frontend/util_test.go
- pkg/proxy/client_conn.go
- pkg/proxy/client_conn_test.go
- pkg/proxy/handler.go
issue #12333 
cherr-pick pr #12396
与云平台协商后，将error code1045修改为只对3种情况报错。其它情况报internal error code 1815。
password error
suspended
source address & is not authorized
> cherry-pick : update error to 1.0dev

- .github/workflows/merge-trigger-tke.yaml
> CI: change clone method

- .github/workflows/merge-trigger-tke.yml
- cmd/mo-service/main.go
- optools/images/Dockerfile
> CI: sync ci with main

- pkg/fileservice/disk_cache.go
Reverts matrixorigin/matrixone#12582
> Revert "fileservice: trigger eviction on startup; more logs; use blocks * block"

- pkg/sql/compile/compile.go
- pkg/sql/compile/scope.go
> resubmit "[Bug]: After a long run, the tpch get wrong result"

- pkg/sql/compile/compile.go
- pkg/sql/compile/scope.go
* 12385
* 11966
issue #
* Fix the error handling of channel when recovering
> Fix the error handling of channel when recovering

- pkg/txn/client/operator.go
- pkg/txn/client/operator_test.go
issue #12167 
allow multiple rollbacks of a transaction
> allow multiple rollbacks of a transaction

- pkg/fileservice/disk_cache.go
> fileservice: trigger eviction on startup; more logs

- pkg/sql/compile/compile.go
- pkg/sql/compile/scope.go
> resubmit "[Bug]: After a long run, the tpch get wrong result" 

- go.mod
- go.sum
- pkg/fileservice/aliyun_sdk.go
> fileservice: add toOSSCredentialProvider

- pkg/frontend/mysql_cmd_executor.go
> fix Incorrect logging (1.0-dev)

- pkg/vm/engine/tae/catalog/segment.go
- pkg/vm/engine/tae/db/scannerop.go
- pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
> hotfix metadata load

- pkg/fileservice/aliyun_sdk.go
> fileservice: add default aliyun credential provider

- pkg/sql/plan/shuffle_algo.go
- pkg/sql/plan/shuffle_test.go
- pkg/sql/plan/stats.go
- pkg/vm/engine/disttae/stats.go
> add null count info in stats cache

- pkg/objectio/cache.go
- pkg/vm/engine/tae/blockio/reader.go
issue #12670
Fill in the missing parts of the  #12670
> Update reader SkipFullFilePreloads policy

- pkg/vm/engine/tae/logtail/collector.go
- pkg/vm/engine/tae/rpc/inspect.go
issue #12645
add mo-ctl to intervene and debug
> add mo-ctl ignore ckp

- pkg/vm/engine/tae/containers/pool.go
- pkg/vm/engine/tae/db/open.go
> [data race]: fix data race when collect metrics

- pkg/vm/engine/tae/db/checkpoint/replay.go
issue #
fix mpool leak during replay
> fix mpool leak during replay

- pkg/vm/engine/tae/tables/base.go
issue #12686 
fix a very very weak mpool leak
> fix a very weak mpool leak

- pkg/vm/engine/tae/tables/updates/delchain.go
- pkg/vm/engine/tae/tables/updates/delete.go
issue #12686 
Close rowid2pk when gc delete node
> fix leak in delete node

- pkg/fileservice/aliyun_sdk.go
> fileservice: fix aliyun sdk error handling

- test/distributed/cases/tenant/tenant.result
- test/distributed/cases/tenant/tenant.test
issue #12689
add a show account case
> add show accounts case

- pkg/common/moerr/error.go
- pkg/common/moerr/mysql_error_define.go
- pkg/common/morpc/codec.go
- pkg/container/types/datetime.go
- pkg/container/types/datetime_test.go
- pkg/container/types/time.go
- pkg/frontend/authenticate.go
- pkg/sql/plan/build_alter_add_primarykey.go
- pkg/taskservice/types.go
- pkg/tests/service/service_test.go
- proto/gen.sh
- test/distributed/cases/auto_increment/auto_increment_columns.sql
- test/distributed/cases/ddl/alter_table_AddDrop_column.sql
- test/distributed/cases/ddl/alter_table_rename_column.sql
- test/distributed/cases/dtype/TimeToInt.result
- test/distributed/cases/dtype/datetime.result
- test/distributed/cases/dtype/text_1.result
- test/distributed/cases/expression/temporal_interval.result
- test/distributed/cases/function/func_cast.result
- test/distributed/cases/function/func_date_format.result
- test/distributed/cases/function/func_date_format_1.result
- test/distributed/cases/function/func_datetime_date_add.result
- test/distributed/cases/function/func_string_concat_ws.result
- test/distributed/cases/mo_cloud/mo_cloud.sql
- test/distributed/cases/prepare/prepare_all.result
- test/distributed/cases/zz_accesscontrol/create_role.sql
- test/distributed/cases/zz_accesscontrol/create_user.sql
fix Incorrect spelling words
Approved by: @heni02, @nnsgmsone, @ouyuanning, @zhangxu19830126, @m-schen, @qingxinhome, @aunjgr
issue #
> fix Incorrect spelling words (1.0-dev)

- pkg/vm/engine/tae/logtail/storage_usage.go
- pkg/vm/engine/tae/tables/jobs/mergeblocks.go
- pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
issue #12533
Add RLock when reading mvcc chain
> fix data race and log print

- pkg/common/mpool/mpool.go
- pkg/util/metric/mometric/metric.go
- pkg/util/metric/v2/dashboard/grafana_dashboard.go
- pkg/util/metric/v2/dashboard/grafana_dashboard_mem.go
- pkg/util/metric/v2/mem.go
- pkg/util/metric/v2/metrics.go
- pkg/vm/engine/tae/common/utils/types.go
- pkg/vm/engine/tae/db/open.go
- pkg/vm/engine/tae/model/transfer.go
> adding more metrics for mpool

- pkg/sql/plan/runtime_filter.go
This reverts commit ee84a6728b220c8659ef7aac1b92c82295ff8e30.
issue #
> Revert "enable shuffle join to block probe until build ready (#12700)"

- pkg/fileservice/disk_cache.go
> fileservice: fix disk cache file size calculation

- pkg/sql/colexec/external/external.go
- pkg/sql/compile/compile.go
- pkg/sql/plan/runtime_filter.go
issue #
this change will help TPCH performance on cold data
> [Bug]: load need to keep order in original data when writing s3 object

- pkg/util/metric/v2/fileservice.go
- pkg/util/metric/v2/hakeeper.go
- pkg/util/metric/v2/logtail.go
- pkg/util/metric/v2/morpc.go
- pkg/util/metric/v2/task.go
- pkg/util/metric/v2/txn.go
issue #
adjust metrics precision
> adjust metrics precision

- optools/mo_checkin_regression/mo_checkin_regression_tke.yaml
> modify config for observability

- pkg/lockservice/rpc.go
- pkg/lockservice/txn.go
- pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
- pkg/util/metric/v2/metrics.go
- pkg/util/metric/v2/txn.go
issue #
improve lockservice p99 latency
> improve lock service p99  latency

- pkg/lockservice/rpc.go
- pkg/lockservice/txn.go
- pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
- pkg/util/metric/v2/metrics.go
- pkg/util/metric/v2/txn.go
issue #
improve p99 lockservice latency
> Improve lock p99 cherry

- pkg/sql/plan/stats.go
Reverts matrixorigin/matrixone#12758
> Revert "optimize stats calculation for point select query with primary key "

- pkg/util/metric/v2/dashboard/grafana_dashboard_logtail.go
- pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
- pkg/util/metric/v2/logtail.go
- pkg/util/metric/v2/metrics.go
- pkg/util/metric/v2/txn.go
- pkg/vm/engine/disttae/logtail_consumer.go
- pkg/vm/engine/disttae/reader.go
issue #
Add more metrics for txn and logtail
> add more metrics for txn and logtail

- pkg/objectio/meta.go
- pkg/objectio/writer.go
- pkg/objectio/writer_test.go
- pkg/sql/plan/stats.go
- pkg/vm/engine/tae/blockio/pipeline.go
- pkg/vm/engine/tae/blockio/writer.go
- pkg/vm/engine/tae/tables/jobs/compactblk.go
- pkg/vm/engine/tae/tables/jobs/flushTableTail.go
- pkg/vm/engine/tae/tables/jobs/flushblk.go
issue #
Add block type (ablk or not) and sortkey to object meta
>  Add BlockType& SortKey to object meta

- pkg/util/metric/mometric/metric.go
> fix timer misusage

- pkg/frontend/mysql_cmd_executor.go
- pkg/frontend/mysql_cmd_executor_test.go
issue #12789 
fix cmd quit return err
> fix cmd quit return err

- pkg/util/metric/v2/dashboard/grafana_dashboard_logtail.go
- pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
- pkg/util/metric/v2/logtail.go
- pkg/util/metric/v2/metrics.go
- pkg/util/metric/v2/txn.go
- pkg/vm/engine/disttae/logtail_consumer.go
- pkg/vm/engine/disttae/reader.go
issue #
add reader logtail metrics, cherry pick
> add reader logtail metrics

- go.mod
- go.sum
- pkg/util/metric/mometric/metric.go
- pkg/util/metric/v2/dashboard/grafana_dashboard.go
- pkg/util/metric/v2/dashboard/grafana_dashboard_runtime.go
- pkg/util/metric/v2/metrics.go
issue #
Add more go runtime metrics
> add more go runtime metrics

- pkg/fileservice/disk_cache.go
- pkg/fileservice/io_lock.go
- pkg/fileservice/s3_fs.go
- pkg/fileservice/s3_fs_test.go
issue #12779 
fileservice: disk cache logging tunings
blockio: use PrefetchFile
fileservice: optimize DiskCache.writeFile
fileservice: refine S3FS.PrefetchFile tests
fileservice: add slow io lock wait warnings
> fileservice: various fixes

- go.mod
- go.sum
- pkg/txn/storage/memorystorage/memorytable/btree.go
- pkg/txn/storage/memorystorage/memorytable/btree_log.go
- pkg/vm/engine/disttae/logtailreplay/blocks_iter.go
- pkg/vm/engine/disttae/logtailreplay/rows_iter.go
> fork tidwall/btree

- pkg/fileservice/disk_cache.go
issue https://github.com/matrixorigin/MO-Cloud/issues/1420
> fileservice: do not create sub dirs for each objects

- pkg/sql/colexec/table_function/processlist.go
- pkg/sql/colexec/table_function/system_view.go
issue #12829 
if there are some labled cns, the super user cannot get nodes
in shared cn nodes when fetch sessions. so we need to add the
shared cn nodes to the result.
> [bug] processlist: super user cannot get sessions in shared cn nodes.

- pkg/txn/storage/tae/read.go
- pkg/txn/storage/tae/storage.go
- pkg/txn/storage/tae/storage_debug.go
- pkg/txn/storage/tae/write.go
> simplify some code in txn handler function

- .github/workflows/ci.yaml
- .github/workflows/e2e-compose.yaml
- .github/workflows/e2e-standalone.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/entrypoint.yaml
- .github/workflows/utils.yaml
issue # https://github.com/matrixorigin/MO-Cloud/issues/1777
change the method of running ci. Developer must relate a issue or have enough pr message in section `What this PR does / why we need it:`
> change ci run method

- .github/workflows/ci.yaml
- .github/workflows/utils.yaml
> debug some courrency error

- .github/workflows/ci.yaml
- .github/workflows/entrypoint.yaml
- .github/workflows/utils.yaml
issue #
This pr is for fix secrets setting error for ci
> CI: debug secret setting error

- .github/workflows/entrypoint.yaml
> CI: change with to secrets for ci

- pkg/fileservice/disk_cache.go
- pkg/fileservice/disk_cache_test.go
- pkg/fileservice/file_cache.go
- pkg/fileservice/file_service.go
- pkg/fileservice/file_services.go
- pkg/fileservice/io_lock.go
- pkg/fileservice/local_etl_fs.go
- pkg/fileservice/local_fs.go
- pkg/fileservice/memory_fs.go
- pkg/fileservice/s3_fs.go
- pkg/fileservice/s3_fs_test.go
- pkg/fileservice/sub_path.go
- pkg/vm/engine/tae/blockio/pipeline.go
> Update prefetchJob for blockio:1.0-dev

- pkg/sql/compile/scope.go
issue #12768
fix bug: data race in loadRun
> fix bug: data race in loadRun

- pkg/frontend/show_account.go
fix dup free vector when show accounts
issue #
> fix dup free vector when show accounts (1.0-dev)

- pkg/frontend/authenticate.go
- pkg/frontend/show_account.go
issue #
pick  https://github.com/matrixorigin/matrixone/pull/12855: 
drop account 的时候会drop 系统数据库
每次drop 数据库的时候会检查数据库是不是发布库
但是系统数据库不会成为发布库，所以检查跳过就可以了。
Approved by: @qingxinhome, @daviszhen
> fix drop account return mo_pubs mo exist (1.0-dev)

- pkg/proxy/handler_test.go
- pkg/proxy/scaling_test.go
> [bug] proxy: fix a UT

- pkg/vm/engine/tae/db/checkpoint/runner.go
- pkg/vm/engine/tae/iface/data/block.go
- pkg/vm/engine/tae/tables/ablk.go
- pkg/vm/engine/tae/tables/base.go
- pkg/vm/engine/tae/tables/blk.go
> rm unused codes

- pkg/common/morpc/backend.go
- pkg/common/morpc/backend_test.go
This reverts commit c4a90dc10ef7e39b77f1c4139cc05b8b8083ef3f.
issue #
Revert
> Revert "fix morpc ping miss handle (#12883)"

- pkg/common/morpc/backend.go
issue [#1826](https://github.com/matrixorigin/MO-Cloud/issues/1826)
add dump goroutines morpc fatal cherry
> add dump goroutines morpc fatal cherry

- pkg/vm/engine/tae/logtail/backup.go
not retained
issue #12894 #12891
> Fix the bug that backup is not retained when ablk is deleted and not trimmed.

- pkg/vm/engine/tae/blockio/pipeline.go
issue #
Some prefetch requests do not have keys, but the reader is set, and judgment conditions need to be added.
> Fix PrefetchFile interface

- pkg/vm/engine/disttae/logtailreplay/rows_iter.go
- pkg/vm/engine/disttae/logtailreplay/rows_iter_test.go
- pkg/vm/engine/disttae/reader.go
- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/disttae/types.go
This reverts commit 986cb9d89f58307ef9902d70fae71a0d63a2d29e.
issue #
revert #12905
> Revert "improve delete and update related performance (#12905)"

- pkg/frontend/mysql_cmd_executor.go
- pkg/frontend/mysql_cmd_executor_test.go
- pkg/frontend/server.go
- pkg/frontend/util.go
- pkg/util/export/etl/db/db_holder.go
issue #1817 https://github.com/matrixorigin/MO-Cloud/issues/1817
1, 去掉dbholder超时使用
有些细节还未清楚。
> fix conn close

- pkg/frontend/computation_wrapper.go
- pkg/frontend/mysql_cmd_executor.go
- pkg/sql/compile/compile.go
- pkg/sql/plan/explain/explain_query.go
- pkg/sql/plan/explain/marshal_model.go
- pkg/util/trace/impl/motrace/statistic/stats_array.go
- pkg/util/trace/impl/motrace/statistic/stats_array_test.go
> feat-improve-cu-stats

- pkg/sql/plan/opt_misc.go
issue # https://github.com/matrixorigin/MO-Cloud/issues/1838
not a root fix, only to pass this problem
> fix a bug that cause insert fail for secondary index

- pkg/logservice/service_bootstrap.go
- pkg/logservice/service_bootstrap_test.go
This reverts commit d40ff8323f513293a430426c1126deb623a849f9.
issue #12891 
revert pr for issue12891
> Revert "[bug] BR: fix bug when restore data (#12942)"

- pkg/vm/engine/tae/logtail/txn_handle.go
issue #12977
Put logtail belonging to the same table into one tabletail.
> update build response in push  1.1-dev

- pkg/vm/engine/disttae/reader.go
issue #12797
this PR: https://github.com/matrixorigin/matrixone/pull/12896
had make all TableDef in disttae as the same. then this bug was fixed.
> remove unused tag & logic

- pkg/lockservice/service_remote.go
- pkg/lockservice/service_remote_test.go
issue #12544
Fix hung in remote lock if cn restart quickly, it will call remote lock on rpc io goroutine, and block all remote requests.
Assuming that we have cn0, cn1, and table1, we consider the following timing:
1. at time t0, cn0 obtains the t1 lock table, and the lock-table bind is t1-cn0-table1-version1.
2. at time t1, cn0 down.
3. at time t2, cn0 restarted, and (t2-t1) < cfg.KeepBindTimeout，so lock-table allocator will keep
the bind t1-cn0-table1-version1 valid
4. cn1 try to lock table1 and gets the binding t1-cn0-table1-version1 from allocator or local cache, then
sends a lock request to cn0.
5. cn0 receive the lock request, but the lock-table bind is t1-cn0-table1-version2, and cn0 cn0 will consider
this lock-table bind to be a remote lock table, because the serviceID(t1-cn0) != …
> fix hung in remote lock if cn restart quickly

- pkg/vm/engine/disttae/tools.go
- pkg/vm/engine/disttae/txn.go
- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/disttae/types.go
- pkg/vm/engine/disttae/util.go
This reverts commit 6db83db3ce6a9f607738408fc3d0b3fc96b9bf8e.
issue #13018 
revert #13018
> Revert "optimize tryFastRange code (#13018)"

- .github/mergify.yml
issue #
change mergify rule. Now branches other than the main branch must be approve by sukki before they can be merged.
> CI: change mergify rule

- pkg/util/export/batch_processor.go
- pkg/util/export/batch_processor_test.go
issue #12990
changes:
- add notes show ut running status
> improve note to catch ut more running infos

- pkg/vm/engine/disttae/txn_table.go
> optimize Ranges code

- pkg/sql/plan/function/func_cast.go
- test/distributed/cases/array/array.result
- test/distributed/cases/array/array.sql
issue # https://github.com/matrixorigin/matrixone/issues/13058
Previously scalar nulls for `vecfxx` were not handled well. Fixing this issue.
> [BugFix] : Fix summation(null) issue

- pkg/sql/colexec/source/source.go
- pkg/sql/colexec/source/types.go
> fix agg hung in stream scan

- pkg/common/morpc/backend.go
issue [#1826](https://github.com/matrixorigin/MO-Cloud/issues/1826)
use buffed channel to reset conn to avoid block.
> use buffed channel to reset conn to 1.0

- pkg/frontend/query_result.go
issue #12870 
add log for save query result
> add log for save query result

- pkg/lockservice/txn.go
issue #
issue #
Fix missing reset txn hold locks
> fix missing reset hold locks to 1.0

- pkg/sql/plan/function/func_cast.go
- test/distributed/cases/array/array.result
- test/distributed/cases/array/array.sql
issue #
https://github.com/matrixorigin/matrixone/issues/13038
https://github.com/matrixorigin/matrixone/issues/13058
Cherry picking 
https://github.com/matrixorigin/matrixone/pull/13039
https://github.com/matrixorigin/matrixone/pull/13059
to 1.1-dev
> cherry-pick PR 13039 & 13059 to 1.1-dev: summation(null) issue +  Create Table with PK/UK and VECFXX BVT

- .github/mergify.yml
- .github/workflows/merge-trigger-standalone.yaml
- .github/workflows/merge-trigger-tke.yaml
issue #
sync ci from main to 1.1-dev
> CI: sync ci to 1.1-dev branch

- .github/mergify.yml
- .github/workflows/merge-trigger-standalone.yaml
- .github/workflows/merge-trigger-tke.yaml
issue #
sync ci from main to 1.0-dev
> CI: sync ci to 1.0-dev branch

- pkg/frontend/query_result.go
add log for save query result
issue #12870
> add log for save query result (1.0-dev)

- pkg/lockservice/txn.go
issue #
issue #
Fix missing reset txn hold locks
> fix missing reset hold locks to 1.1

- .github/workflows/merge-trigger-standalone.yaml
issue #
add temp sleep step in race bvt for debug
> CI: add temp sleep

- pkg/common/morpc/backend.go
issue [#1826](https://github.com/matrixorigin/MO-Cloud/issues/1826)
use buffed channel to reset conn to avoid block.
> use buffed channel to reset conn to 1.1

- .github/mergify.yml
- .github/workflows/merge-trigger-tke.yaml
issue #
modify mergify config and change timeout of tpcc
> CI: modify mergify config and change timeout of tpcc

- pkg/fileservice/file_service.go
- pkg/fileservice/local_fs.go
- pkg/fileservice/local_fs_test.go
- pkg/fileservice/s3_fs.go
issue #13109 
enables extra caches in IOVector
> fileservice: add IOVector.Caches

- pkg/frontend/server.go
- pkg/proxy/handler.go
- pkg/proxy/mysql_conn_buf.go
- pkg/proxy/mysql_conn_buf_test.go
issue #1781  moc1781
1，最大数据包长度判断错误。
2，增加proxy 连接日志
> cherrypiack: fix max packet len 

- pkg/taskservice/daemon_task_test.go
issue #13124
create a chan with buffer to avoid hang issue which is caused
by concurrency between go-routines.
> [bug] UT: TestPauseResumeDaemonTask failed

- .github/workflows/merge-trigger-standalone.yaml
issue #
remove the timeout of race job
> CI: remove job timeout

- pkg/vm/engine/tae/logtail/collector.go
- pkg/vm/engine/tae/rpc/handle.go
- pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
issue #12645 
- narrowing the check interval in the collector, and this is a workaround to fix stopped checkpoint
- add detailed debug info
> fix stopped checkpoint

- pkg/frontend/query_result.go
- pkg/sql/plan/result_scan.go
add log for save_query_result
Approved by: @ouyuanning, @qingxinhome
issue #12870 
cherry-pick
> add log for save_query_result (1.1-dev)

- .github/workflows/merge-trigger-tke.yaml
issue #
add always() to collect trace in ssb/tpch
> CI: add always() to collect trace in ssb/tpch

- pkg/incrservice/column_cache.go
issue #13203
add max retry times for allocator increment value
> add max retry times for allocate increment value

- pkg/sql/compile/scope.go
- pkg/sql/compile/scopeRemoteRun.go
issue #13119 #13204 
1. fix a remote run bug will cause error message lost.
2. removed unused codes.
> [cherry-pick] #13222 fix a remote run bug; removed unused codes.

- pkg/lockservice/waiter.go
- pkg/lockservice/waiter_events.go
> fix race in ut

- pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
- pkg/vm/engine/tae/txn/txnimpl/block.go
- pkg/vm/engine/tae/txn/txnimpl/sysblock.go
issue #12965 & #12645
fix building wrong sysblock handles
> fix wrong sysblock

- pkg/frontend/compiler_context.go
- pkg/sql/colexec/external/external.go
- pkg/sql/colexec/table_scan/table_scan.go
- pkg/sql/plan/stats.go
- pkg/util/metric/v2/txn.go
- pkg/vm/engine/disttae/stats.go
issue #13045
Locate the timeout caused by the build plan, add more metric information to locate why the build plan is so slow
> Add more metric for build plan

- pkg/sql/compile/scope.go
- pkg/sql/compile/scopeRemoteRun.go
issue #13119 #13204 
1. fix a remote run bug will cause the following pipeline closed early, and it will cause error message lost.
2. removed some unused codes.
> fix a remote run bug will suppress the error message

- pkg/sql/compile/compile.go
> fix agg function panic

- .github/workflows/merge-trigger-standalone.yaml
- .github/workflows/merge-trigger-tke.yaml
> CI: add timeout for create tenant

- pkg/incrservice/column_cache.go
issue #13203 
add max retry times for allocator increment value to 1.0
> add max retry times for allocator increment value to 1.0

- pkg/incrservice/column_cache.go
issue #13203
add max retry times for allocator increment value to 1.1
> add max retry times for allocator increment value to 1.1

- .github/workflows/merge-trigger-standalone.yaml
- .github/workflows/merge-trigger-tke.yaml
> CI: Sync ci 1.0 dev

- .github/workflows/merge-trigger-standalone.yaml
- .github/workflows/merge-trigger-tke.yaml
> CI: Sync ci to 1.1 dev

- pkg/cnservice/upgrader/upgrade_sql.go
- pkg/cnservice/upgrader/upgrader.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/1746
add upgrader for mo_task.sys_async_task.task_id
> upgrade upgrader

- pkg/sql/compile/compile.go
- pkg/sql/plan/build.go
- pkg/sql/plan/build_delete.go
- pkg/sql/plan/build_insert.go
- pkg/sql/plan/build_load.go
- pkg/sql/plan/build_replace.go
- pkg/sql/plan/build_update.go
- pkg/util/metric/v2/txn.go
- pkg/vm/engine/disttae/engine.go
issue #13045
* 增加更多的metric来定位buildplan/compile耗时过久的原因
> Add more metric for debug #13045

- pkg/sql/compile/scope.go
- pkg/sql/compile/scopeRemoteRun.go
Reverts matrixorigin/matrixone#13222
> Revert "fix a remote run bug will suppress the error message"

- pkg/sql/colexec/deletion/types.go
- pkg/sql/colexec/intersect/types.go
- pkg/sql/colexec/mergeorder/types.go
- pkg/sql/colexec/mergerecursive/types.go
- pkg/sql/colexec/minus/types.go
- pkg/sql/colexec/partition/types.go
- pkg/sql/colexec/shuffle/types.go
- pkg/sql/compile/scope.go
- pkg/sql/compile/scopeRemoteRun.go
issue #13252 #13279 
1. fix a remote run cleanup bug.
2. fix free method bugs for all operator.
> [cherry-pick] #13289 fix a remote run bug. fix bugs about clean methods of operators.

- pkg/sql/colexec/connector/types.go
- pkg/sql/colexec/dispatch/types.go
issue #13219
* 第一个问题是目前存在多线程消费同一个管道的逻辑，修正这个问题
> Fix the the bug of concurrently reading channel

- pkg/lockservice/service.go
issue #13344 
fix lock service concurrent creating lock table to 1.0
> fix lock service concurrent creating lock table to 1.0

- pkg/lockservice/service.go
issue #13344
fix lock service concurrent creating lock table to 1.1
> fix lock service concurrent creating lock table to 1.1

- pkg/cnservice/server.go
- pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
- pkg/util/metric/v2/txn.go
> add leak metrics to 1.1

- pkg/frontend/authenticate.go
- pkg/frontend/variables.go
- pkg/sql/plan/function/func_mo.go
- test/distributed/cases/table/cluster_table/cluster_table.result
- test/distributed/cases/table/cluster_table/cluster_table.sql
fix can't get cluster table in mo dev
Approved by: @m-schen, @heni02, @qingxinhome
issue #13186 
fix can't get cluster table in mo dev
> fix can't get cluster table in mo dev (1.1-dev)

- pkg/container/types/tuple.go
- pkg/vm/engine/tae/rpc/handle.go
issue #13342 
Add debug log of bmsql_district
> Add debug log of bmsql_district

- pkg/vm/engine/tae/db/checkpoint/replay.go
issue #12741 
Update the checkpoint replay read duration, which previously omitted the duration of the list directory and load meta file.
> Update checkpoint replay read duration

- pkg/lockservice/service.go
issue #13344 
fix lock service concurrent creating lock table.
> fix lock service concurrent creating lock table

- pkg/frontend/variables.go
issue #13224 
add more detail to get variable  error log
> add more detail to get variable  error log

- pkg/sql/compile/scope.go
issue # https://github.com/matrixorigin/MO-Cloud/issues/1925
determine degree of parallelism for scan in runtime
> cherry pick “determine degree of parallelism for scan in runtime”  to 1.1-dev

- pkg/objectio/funcs.go
- pkg/objectio/reader.go
- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/tae/blockio/funcs.go
- pkg/vm/engine/tae/blockio/read.go
- pkg/vm/engine/tae/db/test/db_test.go
- pkg/vm/engine/tae/tables/base.go
- pkg/vm/engine/tae/tables/utils.go
- pkg/vm/engine/tae/txn/txnimpl/table.go
issue #12876
change fileservice.policy from dynamic parameter to static parameter
> change fileservice.policy from dynamic parameter to static parameter

- pkg/vm/engine/tae/rpc/handle.go
issue https://github.com/matrixorigin/matrixone/issues/13342
Add debug log of bmsql_district
> Add debug log of bmsql_district (#13349)

- pkg/frontend/authenticate.go
- pkg/frontend/authenticate_test.go
fix stage check role
issue #12179
fix stage check role
> fix stage check role (1.0-dev)

- pkg/frontend/variables.go
add more detail to get variable  error log
issue #13224
add more detail to get variable  error log
> add more detail to get variable  error log (#1.0-dev)

- pkg/fileservice/config_test.go
- pkg/fileservice/mem_cache_test.go
- pkg/fileservice/s3_fs.go
for issue https://github.com/matrixorigin/matrixone/issues/13045
update file service changes for debugging
> fileservice: pick changes

- pkg/frontend/authenticate.go
- pkg/frontend/session.go
- pkg/frontend/txn.go
issue #13235
Account is created successfully from the record in statement_info but no accout in mo_account table
> Resolve the issue of inconsistent create account results (#13271)

- pkg/lockservice/service_remote.go
issue #13250
add orphans txn log
> add orphans txn log

- pkg/frontend/connector.go
issue # https://github.com/matrixorigin/matrixone/issues/13397
fix the bug that "create dynamic table xxx if not exists " would trigger an error now. 
Should skip the error.
> fix create dynamic table with if not exist

- pkg/lockservice/service_remote.go
issue #13250
add orphans txn log
> add orphans txn log to 1.0

- pkg/cnservice/server.go
issue #13399 
cherry-pick the pr #13400
> [cherry-pick] #13400 cn-service use the global log level

- pkg/taskservice/mem_task_storage.go
issue #12552
set value with deepcopy to avoid data race in test case
> [bug] UT: fix data race

- pkg/lockservice/service_remote.go
issue #13250 
add orphans txn log
> add orphans txn log to 1.1

- pkg/frontend/computation_wrapper.go
- pkg/frontend/mysql_cmd_executor.go
- pkg/sql/plan/build_dcl.go
- pkg/sql/plan/utils.go
- test/distributed/cases/pessimistic_transaction/prepare.result
- test/distributed/cases/pessimistic_transaction/prepare.sql
fix bug: can not retry for execute statement
Approved by: @aunjgr, @heni02, @qingxinhome
issue #13287 
fix bug: can not retry for execute statement
> fix bug: can not retry for execute statement (#13318)

- test/distributed/cases/pessimistic_transaction/unique_secondary_index.result
- test/distributed/cases/pessimistic_transaction/unique_secondary_index.sql
issue #13417
fix bvt bug: check rule is incorrect
> fix bvt bug: check rule is incorrect

- test/distributed/cases/pessimistic_transaction/unique_secondary_index.result
- test/distributed/cases/pessimistic_transaction/unique_secondary_index.sql
fix bvt bug: check rule is incorrect
Approved by: @heni02
issue #13417
fix bvt bug: check rule is incorrect
> fix bvt bug: check rule is incorrect (#13418)

- pkg/fileservice/mem_cache_test.go
- pkg/fileservice/s3_fs.go
for issue https://github.com/matrixorigin/matrixone/issues/13045
to help debugging s3 read issues.
> fileservice: fix S3FS metrics

- pkg/sql/plan/function/func_builtin.go
- pkg/sql/plan/function/func_locate.go
- pkg/sql/plan/function/func_locate_test.go
- pkg/sql/plan/function/function_id.go
- pkg/sql/plan/function/list_builtIn.go
- test/distributed/cases/function/func_locate.result
- test/distributed/cases/function/func_locate.sql
- test/distributed/cases/function/func_upper_lower.result
- test/distributed/cases/function/func_upper_lower.sql
issue #https://github.com/matrixorigin/MO-Cloud/issues/2013
support mysql system function of `locate`, `upper`, `lower`
> support system function of `locate`, `upper`, `lower`

- pkg/container/hashtable/hash_amd64.go
issue https://github.com/matrixorigin/MO-Cloud/issues/2020
To make CPU feature detection more accurate
> fix hash function determination

- .github/workflows/release.yml
- optools/sign/gon.json
> CI: Modify release

- .github/workflows/merge-trigger-standalone.yaml
- .github/workflows/release.yml
- optools/sign/gon.json
> CI: Sync ci 1.0

- pkg/proxy/config.go
- pkg/proxy/handler.go
- pkg/proxy/router.go
- pkg/proxy/router_test.go
- pkg/proxy/server_conn.go
- pkg/proxy/server_conn_test.go
issue #13465
add two config for proxy:
- ConnectTimeout: connect timeout to cn server
- AuthTimeout: handshake timeout with cn server
> [enhancement] proxy: add timeout configuration to replace hardcode.

- pkg/common/morpc/backend.go
- pkg/common/morpc/server.go
- pkg/common/morpc/types.go
- pkg/pb/pipeline/pipeline.go
- pkg/sql/compile/scopeRemoteRun.go
- pkg/sql/compile/scopeRemoteRunTypes.go
> Add debug log query

- pkg/lockservice/lock_table_local.go
- pkg/lockservice/log.go
- pkg/lockservice/rpc.go
issue #13444 
add more debug log
> add more log for lockservice

- pkg/sql/colexec/join/join.go
- pkg/sql/colexec/loopjoin/join.go
- pkg/sql/colexec/loopsemi/join.go
- pkg/sql/colexec/semi/join.go
issue #
add log when join ends early to see if this triggers bug
> add log when join ends early

- pkg/vm/engine/tae/txn/txnbase/txnmgr.go
- pkg/vm/engine/tae/txn/txnimpl/cmdmgr.go
- pkg/vm/engine/tae/txn/txnimpl/store.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/1825
add some slow log to debug unexpected slow commit
> add slow log for slow commit

- pkg/vm/engine/tae/txn/txnbase/txnmgr.go
- pkg/vm/engine/tae/txn/txnimpl/cmdmgr.go
- pkg/vm/engine/tae/txn/txnimpl/store.go
add some slow log to debug unexpected slow commit
Approved by: @LeftHandCold, @gouhongshen
issue #https://github.com/matrixorigin/MO-Cloud/issues/1825
slow log for slow commit
> add slow log for slow commit (#13479) to 1.0-dev

- .github/workflows/merge-trigger-standalone.yaml
- .github/workflows/release.yml
- optools/sign/gon.json
- pkg/sql/colexec/join/join.go
- pkg/sql/colexec/loopjoin/join.go
- pkg/sql/colexec/loopsemi/join.go
- pkg/sql/colexec/right/join.go
- pkg/sql/colexec/rightanti/join.go
- pkg/sql/colexec/rightsemi/join.go
- pkg/sql/colexec/semi/join.go
issue # https://github.com/matrixorigin/MO-Cloud/issues/2027
join can not ends early when hash table is empty. will cause error
> join can not ends early

- pkg/fileservice/memorycache/lrucache/internal/hashmap/hashmap.go
- pkg/fileservice/memorycache/lrucache/internal/hashmap/types.go
- pkg/fileservice/memorycache/lrucache/lru.go
- pkg/fileservice/memorycache/lrucache/shard.go
- pkg/fileservice/memorycache/lrucache/types.go
issue #13508
* 造成sysbench 10w性能下降的原因是因为分shard后，use和avalible这两个函数的开销变大，改成原子变量后恢复性能(1000w因为分shard会导致性能提升)
> improve the performace of lru

- .github/workflows/merge-trigger-standalone.yaml
- .github/workflows/release.yml
- optools/sign/gon.json
> CI: Sync ci 1.1

- pkg/sql/colexec/constraint_util.go
- pkg/sql/colexec/evalExpression.go
- pkg/sql/colexec/index_metadata.go
- pkg/sql/colexec/insert/insert.go
- pkg/sql/colexec/mark/join.go
- pkg/sql/colexec/preinsert/preinsert.go
- pkg/sql/colexec/s3util.go
- pkg/sql/colexec/shuffle/shuffle.go
issue #13502 
处理了部分从vector pool取出内存后部分情况下没有正确释放的问题。
> [cherry-pick] #13504 fix some mpool leak in the colexec directory

- pkg/sql/colexec/deletion/deletion.go
- pkg/sql/colexec/group/group.go
- pkg/sql/colexec/insert/insert.go
- pkg/sql/colexec/order/order.go
- pkg/sql/colexec/shuffle/shuffle.go
- pkg/sql/colexec/top/top.go
- pkg/vm/pipeline/pipeline.go
- pkg/vm/process/analyze.go
- pkg/vm/process/types.go
- pkg/vm/types.go
improve the accuracy of pipeline stats
Approved by: @m-schen, @nnsgmsone
(cherry picked from commit db37cac26c6d4ff80a57ebd22472d3767a649065)
issue #13211
improve the accuracy of pipeline stats
> refactor-pipeline-stats (#13187)

- pkg/sql/compile/compile.go
issue #13528
make sure the current CN is in the CN list.
> [bug] cn: make sure the current CN is in the CN list.

- pkg/fileservice/reuse.go
- pkg/fileservice/s3_fs.go
issue [#1807](https://github.com/matrixorigin/MO-Cloud/issues/1807)
reduce s3 trace allocate
> reduce s3 trace allocate

- pkg/sql/plan/stats.go
issue #12517 #12934
make stats estimation for IN filter more accurate
> fix stats estimation for IN filter

- optools/mo_checkin_regression/mo_checkin_regression_tke.yaml
> CI: modify tke merge run resources setting for 1.1-dev

- pkg/sql/compile/compile.go
issue #13061 #13087 
cherry pick to 1.1-dev
> cherry pick #13087 to 1.1-dev

- optools/mo_checkin_regression/mo_checkin_regression_tke.yaml
> CI: change requests.memory back to 12Gi

- pkg/vm/engine/tae/db/scannerop.go
issue https://github.com/matrixorigin/matrixone/issues/13577
stopping merging globally should not block forced merging
> fix manually merge hung 1.0 (#13588)

- pkg/partition/partition.go
- pkg/sql/colexec/order/order.go
issue #13551
fix a bug that package partition never consider the const vector.
> [cherry-pick] pr #13606 to 1.0 to fix issue #13551

- pkg/util/metric/mometric/cron_task.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/2026
pick from #13521
changes:
1. if func `CalculateStorageUsage` quit, it will cancel the ctx, which passing to the `checkNewAccountSize` goroutinue.
2. do `cleanStorageUsageMetric`, while  `CalculateStorageUsage` and `checkNewAccountSize` quit.
example log if quit
```
{"level":"INFO","time":"2023/12/15 19:05:01.935348 +0800","name":"log-service.MetricStorage","caller":"mometric/cron_task.go:119","msg":"finished","uuid":"7c4dccb4-4d3c-41f8-b482-5251dc7a41bf","error":"context deadline exceeded","span":{"trace_id":"3d514156-ac57-5f91-1a06-55637696244a","span_id":"5d688a1ee79244b7"}}
{"level":"INFO","time":"2023/12/15 19:05:01.935387 +0800","name":"log-service.MetricStorage","caller":"mometric/cron_task.go:109","msg":"clean storage …
```
> bugfix v1.1: cron task MetricStorage quit with metric's reset op. 

- pkg/frontend/test/txn_mock.go
- pkg/sql/colexec/lockop/lock_op.go
- pkg/txn/client/operator.go
- pkg/txn/client/types.go
- pkg/txn/storage/memorystorage/storage_txn_client.go
- pkg/vm/engine/entire_engine_test.go
issue #4971
support txn skip lock on special table
> support txn skip lock on special table

- pkg/incrservice/service.go
- pkg/incrservice/store_sql.go
issue #13603
* cannot continue when the old table cannot find
> Add fatal for cannot find the old table for incservice

- .github/workflows/merge-trigger-tke.yaml
> CI: increase load timeout

- .github/workflows/merge-trigger-tke.yaml
> CI: increase load timeout to 1.1-dev

- .github/workflows/merge-trigger-tke.yaml
> CI: increase load timeout to 1.0-dev

- pkg/sql/plan/runtime_filter.go
issue #13650
we should not push runtime filter on LEFT-like joins
> [fix] don't push runtime filter on LEFT/SINGLE join

- pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
- pkg/sql/parsers/dialect/mysql/scanner.go
issue #13619 
fix identifier in parser scanner
> fix identifier in parser scanner

- pkg/catalog/secondary_index_utils.go
- pkg/sql/compile/ddl_index_algo.go
- pkg/sql/plan/build_ddl.go
- pkg/sql/plan/build_dml_util.go
- pkg/sql/plan/build_vector_index_util.go
- test/distributed/cases/array/array_index.result
- test/distributed/cases/array/array_index.sql
issue # https://github.com/matrixorigin/matrixone/issues/10634
- Support of Delete, Update and Truncate in vector index.
> [Feature]: Vector Index | Phase 4 (Delete, Update, Truncate)

- pkg/sql/plan/function/function_id.go
https://github.com/matrixorigin/MO-Cloud/issues/2093
add function ucase(same as to_upper) and lcase (same as to_lower)
> add function ucase and lcase

- pkg/vm/engine/tae/db/merge/executor.go
- pkg/vm/engine/tae/db/test/db_test.go
- pkg/vm/engine/tae/db/test/hidden_test.go
- pkg/vm/engine/tae/db/test/scheduler_test.go
- pkg/vm/engine/tae/tables/jobs/compactblk.go
- pkg/vm/engine/tae/tables/jobs/flushTableTail.go
- pkg/vm/engine/tae/tables/jobs/flushblk.go
- pkg/vm/engine/tae/tables/jobs/flushdeletes.go
- pkg/vm/engine/tae/tasks/ops/base/types.go
- pkg/vm/engine/tae/tasks/ops/ops.go
- pkg/vm/engine/tae/tasks/ops/types.go
issue https://github.com/matrixorigin/matrixone/issues/13513
- add context to WaitDone
- make WaitDone be able to be called more than once
> fix flush stop 1.0

- pkg/frontend/authenticate.go
- test/distributed/cases/database/config.result
- test/distributed/cases/zz_accesscontrol/account_restricted.result
> fix incorrect version (#13500)

- pkg/vm/engine/tae/tasks/base.go
issue https://github.com/matrixorigin/matrixone/issues/13513
make task result channel non-blocking
> fix wait channel

- pkg/sql/plan/stats.go
issue #13717
Point queries based on primary keys do not need complete stats calculation process
> [Performance]: Point queries based on primary keys do not need complete stats calculation process

- pkg/sql/plan/opt_misc.go
- pkg/sql/plan/query_builder.go
- test/distributed/cases/optimizer/union.result
- test/distributed/cases/optimizer/union.test
issue #13679
rewrite effectless agg to project, and then remove this project node.
> cherry pick "[Tech Request]: optimize union statement step 2" to 1.1-dev

- pkg/vm/engine/tae/logtail/service/server.go
issue https://github.com/matrixorigin/MO-Cloud/issues/2095
fix logtail server blocked issue.
> [bug] logtail: fix logtail server blocked issue.

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/workflows/merge-trigger-tke.yaml
> CI: sync ci from main to 1.0-dev

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/workflows/merge-trigger-tke.yaml
> CI: sync ci from main to 1.1-dev

- pkg/frontend/mysql_protocol.go
- pkg/frontend/routine.go
- pkg/frontend/routine_manager.go
- pkg/frontend/session.go
- pkg/util/metric/v2/dashboard/grafana_dashboard.go
- pkg/util/metric/v2/dashboard/grafana_dashboard_frontend.go
- pkg/util/metric/v2/frontend.go
- pkg/util/metric/v2/metrics.go
issue https://github.com/matrixorigin/matrixone/issues/13337
[Enhancement] add frontend accept connection duration metric
> [Cherry-pick] pr 13719 to 1.0-dev

- pkg/sql/colexec/dispatch/dispatch.go
https://github.com/matrixorigin/MO-Cloud/issues/2040
fix a bug caused by pr 13699.
> fix a bug of pr 13699

- pkg/sql/plan/base_binder.go
- pkg/sql/plan/build_test.go
- test/distributed/cases/prepare/prepare.result
- test/distributed/cases/prepare/prepare.test
issue #https://github.com/matrixorigin/MO-Cloud/issues/2115
fix internal error when query with param
> fix internal error when query with param

- pkg/proxy/client_conn.go
- pkg/proxy/handler_test.go
- pkg/proxy/router.go
- pkg/proxy/server_conn_test.go
- pkg/proxy/util.go
issue #13618
do not show error result in kill query.
> [enhancement] proxy: do not show error result in kill query.

- pkg/sql/compile/scope.go
issue ##https://github.com/matrixorigin/MO-Cloud/issues/2121
* 原来的逻辑没有处理context，可能会导致永久性的卡住
> Fix the bug of shuffle

- pkg/sql/colexec/external/external.go
issue #13806 
maybe related to #13740 
fix an external operator bug that it never consider the error.
fix an external operator bug that it will cause mpool memory leak.
> [cherry-pick] #13818 fix external operator bugs.

- pkg/sql/plan/function/functionAgg/var_pop.go
issue #10254 
Rewrite error message when decimal overflowed during var_pop
> Rewrite error message when decimal overflowed during var_pop

- test/distributed/cases/load_data/load_data.result
- test/distributed/cases/load_data/load_data.sql
issue #13756
Add Load Data Case
> addLoadDataCase

- .github/workflows/release.yml
> CI: optimized release workflow

- .github/workflows/release.yml
> CI: optimized release workflow for 1.1-dev

- pkg/fileservice/cache.go
- pkg/fileservice/disk_cache.go
- pkg/fileservice/disk_cache_test.go
- pkg/fileservice/local_fs.go
- pkg/fileservice/mem_cache.go
- pkg/fileservice/memorycache/lrucache/lru.go
- pkg/fileservice/remote_cache.go
- pkg/fileservice/s3_fs.go
- pkg/fileservice/s3_fs_test.go
issue #13773
file contents may change, a quick fix
> fileservice: add IOVectorCache.DeletePath; add DataCache.DeletePath

- pkg/tnservice/cfg.go
- pkg/vm/engine/tae/logtail/storage_usage.go
- pkg/vm/engine/tae/logtail/utils.go
issue #12995 
the storage usage data could lost when the upgrade
> keep the storage usage from old ckp to 1.1

- pkg/frontend/mysql_protocol.go
- pkg/frontend/routine_manager.go
- pkg/frontend/session.go
issue https://github.com/matrixorigin/matrixone/issues/13337
fix: observe connection duration unit ms -> s
> fix: observe connection duration unit ms -> s

- pkg/proxy/event.go
- pkg/proxy/event_test.go
- pkg/proxy/mysql_conn_buf.go
- pkg/proxy/tunnel.go
- pkg/proxy/util.go
- pkg/proxy/util_test.go
issue #13778
add support for stmt prepare cmd.
> [enhancement] proxy: add support for stmt prepare cmd.

- pkg/sql/plan/base_binder.go
- pkg/sql/plan/function/function_id.go
- test/distributed/cases/operator/operator.result
- test/distributed/cases/operator/operator.test
* need ! operator
Approved by: @ouyuanning, @m-schen, @badboynt1, @aressu1985, @aunjgr, @heni02
issue [#2087](https://github.com/matrixorigin/MO-Cloud/issues/2087)
* we need the ! operator
> support ! operator (#13796)

- pkg/vm/engine/tae/catalog/block.go
- pkg/vm/engine/tae/catalog/catalog.go
- pkg/vm/engine/tae/catalog/command.go
- pkg/vm/engine/tae/catalog/object.go
- pkg/vm/engine/tae/db/merge/executor.go
- pkg/vm/engine/tae/db/scannerop.go
- pkg/vm/engine/tae/logtail/utils.go
- pkg/vm/engine/tae/txn/txnimpl/antidepend.go
- pkg/vm/engine/tae/txn/txnimpl/table.go
issue #12518 
avoid creating small Golang objects
> avoid creating small Golang objects 1

- .github/workflows/e2e-upgrade.yaml
> CI: increase the timeout of upgrade ci

- pkg/frontend/authenticate.go
- pkg/frontend/authenticate_test.go
issue #13813 
fix #13813 
Tested locally, also, an UT is added to avoid regression.
> bug: fixed python udf upload

- pkg/frontend/mysql_protocol.go
- pkg/frontend/routine_manager.go
- pkg/frontend/session.go
issue https://github.com/matrixorigin/matrixone/issues/13337
fix: observe connection duration unit ms -> s
> fix: observe connection duration unit ms -> s (#13819)

- pkg/frontend/authenticate.go
- pkg/frontend/authenticate_test.go
issue #13813 
fix #13813 in 1.1-dev
> [cherry-pick 1.1-dev] bug: fixed python udf upload

- .github/workflows/merge-trigger-standalone.yaml
> CI: change runner for race bvt

- .github/workflows/merge-trigger-standalone.yaml
> CI: change runner for race bvt in 1.1-dev

- pkg/sql/compile/ddl.go
issue #13853  #13615
use old table to create table and auto increment when retry.
> fix create table retry

- pkg/fileservice/aliyun_sdk.go
- pkg/fileservice/aws_sdk_v2.go
- pkg/fileservice/error.go
- pkg/fileservice/minio_sdk.go
- pkg/fileservice/object_storage_arguments.go
- pkg/fileservice/retry.go
- pkg/fileservice/s3_fs_test.go
issue #13906
fix aliyun credential error handling
Approved by: @zhangxu19830126
> fileservice: refactor aliyun credentials error handling (#13921)

- .github/workflows/merge-trigger-tke.yaml
> CI: change account for sysbench

- .github/workflows/merge-trigger-tke.yaml
> CI: change account for sysbench for 1.1-dev

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/workflows/robot.yml
> CI: change auto add milestone to 1.2.0

- .github/ISSUE_TEMPLATE/bug_report.yml
issue #
remove project from issue template because we use project workflow to automatically add item to project
>  CI: remove project from issue template

- pkg/vm/engine/disttae/route/route_test.go
issue #13943
fix a UT in route package.
> [bug] disttae: fix a UT in route package.

- pkg/proxy/client_conn.go
- pkg/proxy/event.go
- pkg/proxy/mysql_conn_buf.go
- pkg/proxy/util.go
- pkg/proxy/util_test.go
issue #13778 
fix the prepare wait condition from execute to close.
Also, add support "use db" plain text back.
> [postfix] proxy: fix the prepare wait condition from execute to close

- pkg/sql/colexec/dispatch/dispatch.go
- pkg/sql/colexec/server.go
- pkg/sql/colexec/types.go
- pkg/sql/compile/scopeRemoteRun.go
- pkg/sql/compile/scopeRemoteRunTypes.go
issue #13740 
优化了uuid-proc的map的set value / get value逻辑，删除了引用计数的逻辑，避免因特殊情况下的process永远被引用导致的内存泄漏。
> [cherry-pick] #13965 optimized the uuid-process map to avoid memory leak.

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/merge-trigger-standalone.yaml
- .github/workflows/merge-trigger-tke.yaml
- .github/workflows/release.yml
- .github/workflows/robot.yml
- .github/workflows/utils.yaml
> CI: sync ci to 1.0-dev

- pkg/vm/engine/disttae/logtailreplay/partition_state.go
issue #13970 
cherry-pick update handle object insert
> cherry-pick update handle object insert (#14018)

- pkg/objectio/cache.go
issue #12506
use fifocache in objectio
> objectio: use fifocache

- pkg/frontend/mysql_protocol.go
- pkg/frontend/routine.go
- pkg/frontend/routine_manager.go
- pkg/frontend/session.go
- pkg/util/metric/v2/frontend.go
issue https://github.com/matrixorigin/matrixone/issues/13337
add more metrics for accept connection duration
> add more metrics for accept connection duration

- pkg/vm/engine/disttae/logtailreplay/partition.go
update lazy-load to avoid unnecessary blocking
Approved by: @reusee
issue #13968 
update lazy-load to avoid unnecessary blocking
> update lazy-load to avoid unnecessary blocking -> 1.1-dev

- pkg/vm/engine/disttae/logtailreplay/blocks_iter.go
- [ x] BUG
issue #13788 
https://github.com/matrixorigin/MO-Cloud/issues/2132
1.  fix bug for file not found .
> fix bug-file-not-found

- pkg/vm/engine/disttae/logtailreplay/blocks_iter.go
Reverts matrixorigin/matrixone#14090
> Revert "fix bug for file not fuond"

- pkg/proxy/client_conn.go
- pkg/proxy/config.go
issue #13778
change default config value and sql stmt of use.
> [enhancement] proxy: change default config value and sql stmt of use.

- pkg/vm/engine/tae/options/types.go
issue #14096
Set `DefaultGlobalVersionInterval` = 1h
> update default global version interval

- pkg/frontend/mysql_cmd_executor.go
issue #14068
参看这个comment：
https://github.com/matrixorigin/matrixone/issues/14068#issuecomment-1884646969
> fix bug: should throw err when prepare multi stmt

- pkg/sql/colexec/evalExpression.go
- pkg/sql/plan/explain/explain_expr.go
- pkg/sql/plan/rule/constant_fold.go
- pkg/sql/plan/stats.go
- pkg/sql/plan/utils.go
issue #14095 matrixorigin/MO-Cloud#2262 matrixorigin/MO-Cloud#2272 matrixorigin/MO-Cloud#2273
fix various bugs related to index
> fix various bugs related to index

- pkg/vm/engine/disttae/logtailreplay/blocks_iter.go
- [ x] BUG
issue #14114 #13788 
1.  fix bug relate to "invalid file path"
2.  p.dataObjects.Get() is not thread-safe,  instead, use iter.Copy and Seek
3.  p.dataObjects.GetMut() seems that don't work , i don't know why.
> fix bug relate to invalid file path

- test/distributed/cases/join/leftjoin.result
- test/distributed/cases/join/leftjoin.test
issue #14108
need to wait for flush complete in race mode
> [Bug]: Incorrect explain in bvt with race enabled

- pkg/txn/client/operator.go
issue #13780 
fix invalid dead lock error
> fix invalid dead lock error

- test/distributed/cases/keyword/NoReservedKeyword.result
- test/distributed/cases/keyword/NoReservedKeyword.sql
issue #13728
Add no reserved keyword case
> addNoReservedKeywordCase

- pkg/vm/engine/tae/catalog/object.go
- pkg/vm/engine/tae/catalog/table.go
- pkg/vm/engine/tae/common/print.go
- pkg/vm/engine/tae/common/stats.go
- pkg/vm/engine/tae/index/zm.go
- pkg/vm/engine/tae/rpc/inspect.go
- pkg/vm/engine/tae/tables/ablk.go
issue #14129
- add options to limit output range
- add hex output format to debug zonemap print error
- remove unused codes
- refactor inspect cmds
> add page limiter for mo-ctl.object

- .github/workflows/e2e-standalone.yaml
issue # https://github.com/matrixorigin/matrixone/issues/12168
Need to fix the issue 12168, but adding some more statement in bvt test would cause timeout problem
> increaset bvt (e2e  BVT Test on Linux/x64(LAUNCH)) timeout

- pkg/lockservice/lock_table_allocator_test.go
- pkg/lockservice/lock_table_keeper.go
- pkg/lockservice/lock_table_keeper_test.go
- pkg/lockservice/lock_table_proxy_test.go
- pkg/lockservice/service.go
- pkg/lockservice/service_observability.go
- pkg/lockservice/service_remote.go
- pkg/lockservice/service_remote_test.go
- pkg/lockservice/service_test.go
issue #14146 
Fix same lock table create muti-times in handle bind changed.
> fix lock table map

- pkg/taskservice/cron_state.go
- pkg/taskservice/task_service_cron.go
issue https://github.com/matrixorigin/MO-Cloud/issues/2133
do not break when fetch cron task failed.
> do not break when fetch cron tasks error

- pkg/objectio/funcs.go
issue #12532 
The interface for load metadata adds Release
> The interface for load metadata adds Release

- pkg/vm/engine/tae/tables/jobs/flushblk.go
issue #14212
return early if sync has error
> fix flushblk error handling

- pkg/lockservice/lock_table_allocator_test.go
- pkg/lockservice/lock_table_keeper.go
- pkg/lockservice/lock_table_keeper_test.go
- pkg/lockservice/service.go
- pkg/lockservice/service_observability.go
- pkg/lockservice/service_remote.go
- pkg/lockservice/service_remote_test.go
- pkg/lockservice/service_test.go
issue #14146 
Fix same lock table create muti-times in handle bind changed.
> fix lock table map to 1.1

- pkg/vm/engine/tae/tables/jobs/flushblk.go
issue #14212
return early when sync fails
> fix flush block error handling 1.1

- pkg/vm/engine/tae/db/checkpoint/entry.go
- pkg/vm/engine/tae/db/checkpoint/runner.go
- pkg/vm/engine/tae/db/gc/diskcleaner.go
- pkg/vm/engine/tae/db/testutil/engine.go
- pkg/vm/engine/tae/logtail/utils.go
issue #14205 
fix gc bug after upgrading from 1.0 to 1.1
> pick gc fix to 1.1

- pkg/sql/plan/build_dml_util.go
- pkg/sql/plan/build_show.go
- test/distributed/cases/ddl/alter_table_add_drop_constraint.result
- test/distributed/cases/ddl/alter_table_change_column.result
- test/distributed/cases/ddl/alter_table_modify_column.result
- test/distributed/cases/ddl/alter_table_rename_column.result
- test/distributed/cases/ddl/mysql_ddl_2.result
- test/distributed/cases/ddl/mysql_ddl_2.sql
issue #14166 #14168 
When the unqiue key meet the following conditions, it is the primary key of the table.
1. There is no primary key in the table.
2. The unique key is the only unique key of the table.
3. The column of the unique key is not null by default.
> fix: desc table key error

- pkg/sql/plan/make.go
- pkg/vm/engine/disttae/util_test.go
issue #14231 
add getPkExpr unit test
> add getPkExpr unit test

- pkg/taskservice/task_service_cron.go
issue #MOC#2133
update trigger time when write in table.
> update trigger times before write to async task

- pkg/lockservice/service_remote.go
- pkg/lockservice/service_remote_test.go
- pkg/pb/lock/lock.go
issue #14241
fix bind changed not handled
> fix bind changed not handled

- pkg/sql/colexec/onduplicatekey/on_duplicate_key.go
- pkg/sql/compile/ddl.go
fix mpool leak
Approved by: @nnsgmsone, @m-schen
issue #14083 
fix mpool leak
> fix mpool leak in LockMoDatabase (#14217)

- pkg/vm/engine/disttae/engine.go
- pkg/vm/engine/disttae/txn_database.go
- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/disttae/types.go
fix mpool leak in txn.WriteBatch
Approved by: @nnsgmsone
issue #14080 
fix mpool leak in txn.WriteBatch
> fix mpool leak in txn.WriteBatch (#14220)

- pkg/vm/engine/tae/rpc/handle.go
- [x ] BUG
issue:https://github.com/matrixorigin/MO-Cloud/issues/2350
1. TN return error, instead of panic
> TN should retrun error ,instead of panic!

- pkg/taskservice/task_service_cron.go
issue #MOC#2133
Fix trigger times on main.
> fix trigger times on main

- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/disttae/util.go
- pkg/vm/engine/disttae/util_test.go
issue #11908 
improve pk filter selectivity for tp performance
> improve pk filter selectivity for tp performance

- pkg/sql/compile/compile.go
- pkg/sql/parsers/tree/update.go
- pkg/sql/plan/build_load.go
- pkg/sql/plan/utils.go
issue #13045
* 对于小文件，会存在大量的不需要的s3请求
> [Cherry-pick] For small file loads, reduce their parallelism

- pkg/clusterservice/cluster.go
- pkg/clusterservice/types.go
- pkg/lockservice/lock_table_allocator_test.go
- pkg/lockservice/rpc.go
- pkg/lockservice/rpc_test.go
- pkg/lockservice/service_remote.go
- pkg/lockservice/service_test.go
- pkg/proxy/handler_test.go
- pkg/proxy/router_test.go
- pkg/vm/engine/disttae/route/route_test.go
issue #13764
fix continue can not connect to remote in lockservice
> fix continue can not connect to remote

- pkg/sql/plan/function/func_bench_test.go
- pkg/sql/plan/function/func_binary.go
Improving the performance of the dataformat function
Approved by: @m-schen, @aunjgr
issue #https://github.com/matrixorigin/MO-Cloud/issues/2365
Improving the performance of the dataformat function
> Date format improve (#14301)

- CODEOWNERS
issue #9986 
update some code owners
> update some code owners

- pkg/util/address/address_test.go
> [bug] ut: fix a ut case.

- pkg/vm/engine/tae/db/gc/entry.go
- pkg/vm/engine/tae/db/gc/table.go
issue https://github.com/matrixorigin/MO-Cloud/issues/1415 https://github.com/matrixorigin/MO-Cloud/issues/1424
GC Adapt Object
> GC Adapt Object

- pkg/cnservice/cnclient/client.go
- pkg/sql/compile/scope.go
- pkg/sql/compile/scopeRemoteRun.go
issue #14353
* Fatal丢失了大量的信息，改成error并记录上下文信息
> Convert fatal to error for NewStream

- pkg/container/vector/utils.go
- pkg/container/vector/vector.go
- pkg/sql/colexec/evalExpression.go
- pkg/sql/colexec/fuzzyfilter/filter.go
- pkg/sql/colexec/hashbuild/build.go
- pkg/sql/plan/make.go
- pkg/sql/plan/partition_util.go
- pkg/sql/plan/rule/constant_fold.go
- pkg/sql/plan/utils.go
- pkg/vm/engine/disttae/tools.go
- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/disttae/types.go
- pkg/vm/engine/disttae/util.go
- pkg/vm/engine/disttae/util_test.go
- pkg/vm/engine/tae/index/filter.go
issue #14231 
Revert  some commits due to possible segment fault
> Revert  some commits

- pkg/container/vector/utils.go
- pkg/container/vector/vector.go
- pkg/sql/colexec/evalExpression.go
- pkg/sql/colexec/fuzzyfilter/filter.go
- pkg/sql/colexec/hashbuild/build.go
- pkg/sql/plan/make.go
- pkg/sql/plan/partition_util.go
- pkg/sql/plan/rule/constant_fold.go
- pkg/sql/plan/utils.go
- pkg/vm/engine/disttae/tools.go
- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/disttae/types.go
- pkg/vm/engine/disttae/util.go
- pkg/vm/engine/disttae/util_test.go
- pkg/vm/engine/tae/index/filter.go
Reverts matrixorigin/matrixone#14386
> Revert "Revert  some commits"

- pkg/fileservice/local_fs.go
- pkg/fileservice/s3_fs.go
- pkg/frontend/mysql_cmd_executor.go
- pkg/sql/colexec/connector/connector.go
- pkg/sql/colexec/dispatch/dispatch.go
- pkg/util/trace/impl/motrace/statistic/stats_array.go
> fix 13211(cpu stats)

- pkg/vm/engine/tae/db/test/storage_usage_test.go
- pkg/vm/engine/tae/db/testutil/engine.go
- pkg/vm/engine/tae/logtail/utils.go
issue #14399
fix visitObjectEntry
> fix visitObjectEntry

- pkg/vm/engine/tae/db/testutil/engine.go
- pkg/vm/engine/tae/logtail/utils.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/2420
fix load and collect object
> fix load and collect object

- pkg/sql/plan/utils.go
- test/distributed/cases/ddl/alter_table_rename_column.result
- test/distributed/cases/ddl/alter_table_rename_column.sql
- test/distributed/cases/dtype/enum.result
- test/distributed/cases/dtype/varchar.result
- test/distributed/cases/dtype/varchar.test
- test/distributed/cases/function/func_aggr_count.result
- test/distributed/cases/function/func_string_format.result
- test/distributed/cases/function/func_string_format.test
- test/distributed/cases/operator/row_constructor.result
issue https://github.com/matrixorigin/MO-Cloud/issues/2422
to make type-cast rules consistent
> always cast varchar to int when comparing varchar with int

- pkg/vm/engine/tae/catalog/object.go
- pkg/vm/engine/tae/logtail/utils.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/2421
check and set object stats for previous MVCC node when load.
> fix load object stats

- .github/workflows/e2e-standalone.yaml
- .github/workflows/merge-trigger-standalone.yaml
- optools/run_bvt.sh
> disable reuse check for Upgrade CI and Restart CI

- pkg/vm/engine/disttae/logtail_consumer.go
issue #14383 
when subscribe system tables failed, make it successfuly to retry.
> [bug] logtail: cannot retry when system table subscribe failed

- .github/workflows/merge-trigger-tke.yaml
> CI: modify mocluster check

- .github/workflows/merge-trigger-tke.yaml
> CI: modify mo cluster check for 1.1-dev

- pkg/sql/plan/function/func_binary.go
issue https://github.com/matrixorigin/MO-Cloud/issues/2408
fix wrong output
> don't assume input vector to be sorted in prefix_eq

- pkg/backup/tae.go
issue https://github.com/matrixorigin/MO-Cloud/issues/2450
Fix the bug of backup checkpoint metadata
> Fix the bug of backup checkpoint metadata

- pkg/sql/plan/build_dml_util.go
当 更新/删除 unique key和2cnd key隐藏表的时候，是用  原表 left join隐藏表 ,取出隐藏表要更新/删除的 row id。 这个时候隐藏表的数据可能是null， 于是删除的batch的这一列的值全部是null，
（但是实际删的时候，不会去读null的那个属性，而是直接用的data里的数据，而这些数据都是vector被复用之前的错误数据。
这里在delete算子前加个filter算子筛选掉null值的行
Approved by: @aunjgr
issue https://github.com/matrixorigin/matrixone/issues/14137 https://github.com/matrixorigin/matrixone/issues/14139
cherry pick 14248
> fix bug: delete incorrect rows for hidden tables (#14248)

- pkg/frontend/computation_wrapper.go
- pkg/frontend/show_subsriptions.go
- pkg/frontend/stmt_kind.go
- pkg/sql/parsers/dialect/mysql/mysql_lexer.go
- pkg/sql/parsers/dialect/mysql/mysql_sql.go
- pkg/sql/parsers/dialect/mysql/mysql_sql.y
- pkg/sql/parsers/tree/alter.go
- pkg/sql/parsers/tree/analyze.go
- pkg/sql/parsers/tree/connector.go
- pkg/sql/parsers/tree/deallocate.go
- pkg/sql/parsers/tree/drop.go
- pkg/sql/parsers/tree/explain.go
- pkg/sql/parsers/tree/function.go
- pkg/sql/parsers/tree/prepare.go
- pkg/sql/parsers/tree/procedure.go
- pkg/sql/parsers/tree/replace.go
- pkg/sql/parsers/tree/sequence.go
- pkg/sql/parsers/tree/stages.go
- pkg/sql/parsers/tree/truncate.go
- pkg/sql/parsers/tree/use.go
- pkg/sql/plan/build_alter_table.go
- pkg/sql/plan/build_dcl.go
- pkg/sql/plan/build_ddl.go
issue #11663
The nodes listed below all have memory reuse, the replacement of some of the nodes is not complete and needs to be continued later.
* analyze 
* deallocate 
* drop 
* explain 
* prepare 
* replace 
* truncate 
* use
> [refactor] : use reuse package to reuse some parser-nodes

- .github/workflows/merge-trigger-tke.yaml
> CI: use mo-load-data main branch for 1.1-dev

- pkg/container/vector/vector.go
- pkg/vm/engine/disttae/txn_table.go
- test/distributed/cases/pessimistic_transaction/create_table.result
- test/distributed/cases/pessimistic_transaction/create_table.sql
issue #https://github.com/matrixorigin/MO-Cloud/issues/2449
the CN workspace can only handle `INSERT` and `DELETE` operations. Other operations will be skipped,
> handle metadata update operations in explicit transactions

- pkg/vm/engine/tae/catalog/catalog.go
- pkg/vm/engine/tae/catalog/object.go
- pkg/vm/engine/tae/logtail/utils.go
issue #14477
Skip delta location MVCC node when replay object by block
> fix replayObjectByBlock

- pkg/fileservice/aliyun_sdk.go
issue #14328 
convert not found error to moerr
> fileservice: return proper error in AliyunSDK.Stat

- .github/workflows/merge-trigger-standalone.yaml
- .github/workflows/merge-trigger-tke.yaml
> CI: Use mo-load-data main branch

- pkg/sql/plan/build_load.go
- test/distributed/cases/load_data/load_data.result
issue #14463
* Check the schema before stat the file in load
> Check the schema before stat the file in load

- pkg/frontend/export.go
issue #14470
[fix] the process for enclosed by '' in mo_dump
> [fix] the process for enclosed by '' in mo_dump

- pkg/vm/engine/disttae/txn_table.go
issue https://github.com/matrixorigin/matrixone/issues/14125
https://github.com/matrixorigin/matrixone/pull/14491
append code for alter
> append code for alter

- pkg/vm/engine/disttae/txn.go
issue #14282 
*The original logic would have resulted in too many frequent s3 write
> Add more precise workspace size control

- pkg/backup/tae.go
issue # https://github.com/matrixorigin/MO-Cloud/issues/2359
optimize CopyFile to use less memory
> backup: optimize CopyFile

- pkg/vm/engine/disttae/logtailreplay/partition_state.go
- pkg/vm/engine/tae/db/test/db_test.go
- pkg/vm/engine/tae/logtail/handle.go
- pkg/vm/engine/tae/logtail/txn_handle.go
issue #13956
remove create/delete blk in table tail
> remove create/delete blk in table tail

- pkg/backup/tae.go
Fix the bug of backup checkpoint metadata
Approved by: @daviszhen, @sukki37
issue https://github.com/matrixorigin/MO-Cloud/issues/2450
Fix the bug of backup checkpoint metadata
> Fix the bug of backup checkpoint metadata (#14448)

- pkg/sql/plan/apply_indices.go
issue https://github.com/matrixorigin/MO-Cloud/issues/2495
fix the performance issue of prepared stmt
> [opt] allow filters with variable to use index

- pkg/vm/engine/disttae/txn.go
*The original logic would have resulted in too many frequent s3 write
Approved by: @triump2020
issue https://github.com/matrixorigin/matrixone/issues/14282
*The original logic would have resulted in too many frequent s3 write
> Add more precise workspace size control (#14497)

- pkg/vm/engine/tae/db/test/txn_test.go
- pkg/vm/engine/tae/txn/txnbase/txnmgr.go
issue #14579 
optimize wait wal latency in the commit critical path
> optimize wait wal latency in the commit critical path

- pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
issue #14579 
remove some time consumer during commit flush tail transaction
> remove some time consumer during commit flush tail transaction

- pkg/sql/colexec/evalExpression.go
- pkg/sql/plan/function/list_operator.go
- pkg/sql/plan/stats.go
issue # https://github.com/matrixorigin/MO-Cloud/issues/2524
support isnull and isnotnull in block filter
> support isnull and isnotnull in block filter 

- pkg/sql/colexec/evalExpression.go
- pkg/sql/plan/function/list_operator.go
- pkg/sql/plan/stats.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/2524
support isnull and isnotnull in block filter
> support isnull and isnotnull in block filter to 1.1-dev

- pkg/sql/plan/build_constraint_util.go
- pkg/sql/plan/build_dml_util.go
- pkg/sql/plan/build_insert.go
- pkg/sql/plan/build_load.go
issue #14600
Extract the code related to pkfilter so that unique key can use pk filter and make the code more readable.
> [refactor] : Extract the code related to pkfilter

- pkg/vm/engine/disttae/txn.go
- pkg/vm/engine/disttae/txn_database.go
- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/disttae/types.go
> fix writeoffset data race

- pkg/vm/engine/disttae/txn.go
- pkg/vm/engine/disttae/txn_database.go
- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/disttae/types.go
fix data race
Approved by: @fengttt, @nnsgmsone, @sukki37
(cherry picked from commit c7d673f1c1297b2d44d6c01bf88909ff5b4d1d5f)
issue #14573
fix data race
> Fix writeoffset race

- pkg/vm/engine/tae/db/gc/entry.go
issue #14639
Handle the creation and deletion of an object across checkpoints.
Otherwise, refcount > 1 will occur and the deletion will not be possible.
> Fix TestAppendAndGC

- pkg/vm/engine/disttae/stats.go
issue #14649 
fix the wrong condition which will cause updating stats
everytime when there are small amount of data and no objects are gererated.
> [bug] stats: performace is bad as the condition is wrong.

- pkg/container/types/types.go
- pkg/sql/plan/build_show.go
- test/distributed/cases/ddl/alter_table_change_column.result
- test/distributed/cases/ddl/alter_table_modify_column.result
- test/distributed/cases/ddl/mysql_ddl_3.result
- test/distributed/cases/dtype/enum.result
- test/distributed/cases/dtype/enum_2.result
- test/distributed/cases/dtype/enum_2.test
fix dump enum type error
Approved by: @nnsgmsone, @heni02, @ouyuanning
issue #https://github.com/matrixorigin/MO-Cloud/issues/2538
fix dump enum type error
> fix dump enum type error (#1.1-dev)

- pkg/sql/parsers/dialect/mysql/scanner.go
fix scanner for '#'
Approved by: @iamlinjunhong
issue #https://github.com/matrixorigin/MO-Cloud/issues/2516
fix scanner for '#'
> fix scanner for '#' (#1.1-dev)

- pkg/vm/engine/tae/db/checkpoint/runner.go
- pkg/vm/engine/tae/db/test/db_test.go
- pkg/vm/engine/tae/logtail/collector.go
issue #13147
flush and free memory more promptly
> 1.1: add flush range lag

- pkg/sql/colexec/indexjoin/join.go
- test/distributed/cases/optimizer/index.result
- test/distributed/cases/optimizer/index.test
issue #14616
fix a bug of indexjoin that it does not output columns correctly
> fix a bug of indexjoin that it does not output columns correctly

- pkg/sql/plan/rule/constant_fold.go
- pkg/sql/plan/stats.go
issue #14697
constand fold time and datetime type, and calculate stats correctly
> [Tech Request]: time and datetime type can not fold correctly

- pkg/sql/plan/rule/constant_fold.go
- pkg/sql/plan/utils.go
issue #14669
cherry-pick bug fix to 1.1-dev
> fix constant folding of literal vector with 1 item

- pkg/vm/engine/disttae/stats.go
issue #14672
fix connection timed out and r-w confict
> [bug] stats: fix connection timed out and r-w confict

- pkg/vm/engine/disttae/stats.go
issue #14672 
revert: performace is bad as the condition is wrong
> [bug] revert: performace is bad as the condition is wrong

- pkg/vm/engine/tae/tables/base.go
issue #13342
remove duplicate Next call
> 1.1: fix wrong Next call on memory deletes collecting

- pkg/vm/engine/tae/db/gc/entry.go
issue https://github.com/matrixorigin/matrixone/issues/14639
Handle the creation and deletion of an object across checkpoints.
Otherwise, refcount > 1 will occur and the deletion will not be possible.
> Fix TestAppendAndGC for 1.1

- pkg/sql/compile/compile.go
issue [#MOC2555](https://github.com/matrixorigin/MO-Cloud/issues/2555)
All memory problems that exist on 1.1-dev but not on main may be related to this.
Added back to the release of compile and its referenced objects,
> Added back to the release of compile and its referenced objects

- pkg/fileservice/aliyun_sdk.go
- pkg/fileservice/aws_sdk_v1.go
- pkg/fileservice/aws_sdk_v2.go
- pkg/fileservice/get.go
- pkg/fileservice/minio_sdk.go
- pkg/fileservice/object_storage_arguments.go
- pkg/fileservice/s3_fs_test.go
issue #14113
add more control to s3
> fileservice: add ObjectStorageArguments.NoBucketValidation (#14510)

- pkg/objectio/cache.go
- pkg/vm/engine/tae/blockio/pipeline.go
issue https://github.com/matrixorigin/MO-Cloud/issues/2573
remove some stats to improve tp performance in 1.1-dev
> remove some stats to improve tp performance in 1.1-dev

- pkg/vm/engine/tae/catalog/table.go
issue #https://github.com/matrixorigin/matrixone/issues/14706
fix data race in ApplyCommit
> fix data race in ApplyCommit , cherry-pick 14709

- pkg/vm/engine/tae/db/scheduler.go
- pkg/vm/engine/tae/options/options.go
issue #14780 
fix 14780 in 1.1-dev
> cherry pick fix 14780 (#14782) to 1.1-dev

- pkg/frontend/test/txn_mock.go
- pkg/frontend/util_test.go
- pkg/sql/compile/compile.go
- pkg/sql/compile/compile_test.go
- pkg/txn/client/types.go
- pkg/vm/engine/disttae/partition_reader.go
- pkg/vm/engine/disttae/reader.go
- pkg/vm/engine/disttae/txn.go
- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/disttae/types.go
issue #14552, #14597
unnecessary caching of write offset is the root of all evils.
> Remove writes from table

- pkg/sql/plan/runtime_filter.go
issue # https://github.com/matrixorigin/MO-Cloud/issues/2633
fix a bug that runtime filter is not pushed for 1.1
> fix a bug that runtime filter is not pushed for 1.1

- .github/workflows/merge-trigger-tke.yaml
> CI: splite prepare data and test for sysbench

- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/tae/index/zm.go
issue https://github.com/matrixorigin/MO-Cloud/issues/2573
Improve point select performance
> Improve point select performance

- pkg/sql/plan/apply_indices.go
issue # https://github.com/matrixorigin/MO-Cloud/issues/2633
fix a bug that table scan do not go index sometimes
> fix a bug that table scan do not go index sometimes

- pkg/proxy/config.go
- pkg/proxy/config_test.go
- pkg/proxy/conn_manager.go
- pkg/proxy/conn_manager_test.go
- pkg/proxy/event.go
- pkg/proxy/handler.go
- pkg/proxy/mysql_conn_buf.go
- pkg/proxy/rebalancer.go
- pkg/proxy/router_test.go
- pkg/proxy/scaling.go
- pkg/proxy/tunnel.go
- pkg/proxy/tunnel_test.go
- pkg/proxy/util.go
- pkg/util/metric/v2/dashboard/grafana_dashboard_proxy.go
- pkg/util/metric/v2/proxy.go
issue #11048 
proxy could transfer connection more proactivly
there is a new config for this feature: RebalancePolicy, default value is active.
> [enhancement] proxy: transfer connection more proactivly

- pkg/vm/engine/tae/db/replay.go
- pkg/vm/engine/tae/db/test/db_test.go
issue #14501 
fix split command, cherry-pick 14855
> fix split command, cherry-pick 14855

- pkg/util/address/address_test.go
> [bug] fix ut case

- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/disttae/util_test.go
- [x ] BUG
issue #13483 #13212  #12613 #12354 
https://github.com/matrixorigin/MO-Cloud/issues/1411
https://github.com/matrixorigin/MO-Cloud/issues/2585
1. fix bug
2. add ut
> patch for pr 14734

- pkg/vm/engine/disttae/txn_table.go
- test/distributed/cases/pessimistic_transaction/autocommit_isolation.result
- test/distributed/cases/pessimistic_transaction/autocommit_isolation.sql
issue https://github.com/matrixorigin/MO-Cloud/issues/2649
fix bug: can not show databases after drop database
bug repo:
```
create database db1;
set autocommit=0;
use db1;
drop database db1;
show databases;   //panic here
```
> fix bug: can not show databases after drop database

- pkg/vm/engine/disttae/logtailreplay/blocks_iter.go
- pkg/vm/engine/disttae/logtailreplay/partition_state.go
- pkg/vm/engine/disttae/txn_table.go
- [x ] BUG
issue #14562 #14405 
1. fix duplication error
> cherry pick dup

- pkg/catalog/catalog.go
- pkg/vm/engine/disttae/cache/catalog.go
- pkg/vm/engine/disttae/engine.go
- pkg/vm/engine/disttae/tools.go
- pkg/vm/engine/disttae/types.go
- test/distributed/cases/pessimistic_transaction/autocommit_isolation.result
fix bug: get deleted db when autocommit=0
bug repro:
```
create database db1;
set autocommit=0;
drop database db1;
show databases;  // return db list will contains db1
```
Approved by: @heni02, @nnsgmsone
issue #14878
cherry pick 14957 to 1.1-dev
> fix bug: get deleted db when autocommit=0 (#14957)

- pkg/incrservice/store_sql.go
issue #14995
retry ww conflict in optimistic mode to 1.1
> retry ww conflict in optimistic mode to 1.1

- go.mod
- pkg/sql/compile/compile.go
- pkg/sql/plan/function/ctl/cmd_txn_trace.go
- pkg/txn/trace/README.md
- pkg/txn/trace/README_CN.md
- pkg/txn/trace/filter_statement.go
- pkg/txn/trace/filter_txn.go
- pkg/txn/trace/metedata.go
- pkg/txn/trace/service.go
- pkg/txn/trace/service_statement.go
- pkg/txn/trace/service_txn_event.go
- pkg/txn/trace/types.go
issue #13245
Add statement trace.
> add statement trace

- pkg/sql/plan/apply_indices.go
- pkg/sql/plan/utils.go
issue # https://github.com/matrixorigin/MO-Cloud/issues/2695
enable block filter pushdown for in and prefix_in
> enable block filter pushdown for in and prefix_in 

- pkg/sql/compile/compile.go
- [ x] BUG
issue #14516 
1.  Improve performance
> revert pr-14867

- pkg/sql/colexec/fuzzyfilter/filter.go
- pkg/sql/colexec/hashbuild/build.go
- pkg/sql/colexec/rightsemi/join.go
issue # https://github.com/matrixorigin/MO-Cloud/issues/2618
improve cu in some cases
> improve filter cu

- pkg/txn/client/leak_checker.go
issue #[2714](https://github.com/matrixorigin/MO-Cloud/issues/2714)
we need report txn leak outside the mutex, otherwrise openTxn and closeTxn will blocked.
> make report txn leak outside the mutex

- pkg/frontend/computation_wrapper.go
issue https://github.com/matrixorigin/MO-Cloud/issues/2674
fix bug: compile time is incorrect
> fix bug: compile time is incorrect

- .github/workflows/e2e-standalone.yaml
- .github/workflows/image-build.yml
- .github/workflows/merge-trigger-standalone.yaml
- .github/workflows/merge-trigger-tke.yaml
- etc/launch-tae-compose/compose.yaml
…e and optimize mo tke regression
issue #14903
just test the time of ci with `mo_reuse_enable_checker`
> reduce CI run cost

- go.mod
- pkg/vm/engine/disttae/engine.go
issue #15049 
make the 'mo_catalog' visible to all account
> make the 'mo_catalog' visible to all account

- pkg/vm/engine/tae/tables/pnode.go
issue #15128 
Fix vector pool leak
> Fix vector pool leak

- pkg/frontend/mysql_protocol.go
- pkg/proxy/config.go
issue #15148
1. change a default value to make proxy do not transfer conn so fast.
2. fix a bug that the status in mysql response is not correct
> [bug] change a default config value to workaround a transfer bug.

- pkg/vm/engine/disttae/filter.go
- pkg/vm/engine/disttae/logtailreplay/partition_state.go
issue #https://github.com/matrixorigin/matrixone/issues/15089
adding debug log and core-dump when empty object stats are found.
> adding debug log and coredump when empty object stats is found.

- pkg/vm/engine/tae/db/test/db_test.go
issue #15171 
Will be fixed in Refactor GC codes phase 2
> Skip TestSnapshotGC

- pkg/cnservice/server_query.go
- pkg/proxy/client_conn.go
- pkg/proxy/conn_migration.go
- pkg/proxy/mysql_conn_buf.go
- pkg/proxy/router_test.go
- pkg/vm/engine/disttae/route/route.go
issue https://github.com/matrixorigin/MO-Cloud/issues/2652
1. select all cn servers includes the draining ones
2. should transfer to a different cn server, otherwise, prepare stmt cannot be found.
> [postfix] proxy: transfer connections failed

- pkg/container/types/rowid.go
- pkg/vm/engine/tae/db/merge/executor.go
- pkg/vm/engine/tae/db/scannerop.go
- pkg/vm/engine/tae/tables/pnode.go
issue https://github.com/matrixorigin/matrixone/issues/13956
fix stopped merge
> fix stopped merge

- pkg/common/morpc/server.go
issue #15127 #14147 #12564
disable close tcp connection due to heartbeat timeout to 1.1
> disable close tcp connection due to heartbeat timeout to 1.1

- cmd/mo-service/main.go
use pool to create uuid
Approved by: @ouyuanning, @zhangxu19830126
issue #15000 
use pool to create uuid
> use pool to create uuid (#1.1-dev)

- pkg/frontend/internal_executor.go
- pkg/frontend/mysql_cmd_executor.go
- pkg/frontend/mysql_protocol.go
- pkg/frontend/routine.go
- pkg/frontend/routine_manager.go
- pkg/frontend/session.go
issue https://github.com/matrixorigin/MO-Cloud/issues/2385
[Fix] session leakage
> [Fix] session leakage

- pkg/cnservice/server_query.go
- pkg/queryservice/session_manager.go
issue #15206 
[Fix] concurrent problem of sessionMgr
> [Fix] concurrent problem of sessionMgr 

- pkg/vm/engine/tae/db/merge/mod.go
issue https://github.com/matrixorigin/matrixone/issues/13956
stop merge to make more time to fix a series of problems
> temporarily stop merge

- pkg/util/metric/v2/dashboard/grafana_dashboard.go
issue https://github.com/matrixorigin/MO-Cloud/issues/2812
fix part of https://github.com/matrixorigin/MO-Cloud/issues/2812
> fix: dashboard should filter by owner and refresh on time range change

- test/distributed/cases/pessimistic_transaction/select_for_update.result
- test/distributed/cases/pessimistic_transaction/select_for_update.sql
issue #https://github.com/matrixorigin/MO-Cloud/issues/2760
add select for update case
> add select for update case

- pkg/sql/parsers/dialect/mysql/mysql_sql.go
- pkg/sql/parsers/dialect/mysql/mysql_sql.y
- pkg/sql/parsers/tree/branch.go
- pkg/sql/parsers/tree/compound.go
- pkg/sql/parsers/tree/create.go
- pkg/sql/parsers/tree/declare.go
- pkg/sql/parsers/tree/delete.go
- pkg/sql/parsers/tree/do.go
- pkg/sql/parsers/tree/execute.go
- pkg/sql/parsers/tree/function.go
- pkg/sql/parsers/tree/grant.go
- pkg/sql/parsers/tree/iteration.go
- pkg/sql/parsers/tree/kill.go
- pkg/sql/parsers/tree/lock.go
- pkg/sql/parsers/tree/mo_dump.go
- pkg/sql/parsers/tree/procedure.go
- pkg/sql/parsers/tree/replace.go
- pkg/sql/parsers/tree/reset.go
- pkg/sql/parsers/tree/revoke.go
- pkg/sql/parsers/tree/select.go
- pkg/sql/parsers/tree/select_lock.go
- pkg/sql/parsers/tree/show.go
- pkg/sql/parsers/tree/table_function.go
- pkg/sql/parsers/tree/values.go
- pkg/sql/parsers/tree/view.go
- pkg/sql/plan/base_binder.go
- pkg/sql/plan/query_builder.go
Reverts matrixorigin/matrixone#15102
> Revert "[refactor] : continue reuse memory for parser"

- pkg/vm/engine/disttae/tools.go
issue #12876
change threshold for small scan
> change threshold for small scan

- pkg/cnservice/upgrader/new_add_table.go
- pkg/util/sysview/sysview.go
…eries
issue #15189
Solving the problem of cross tenant error in information system view 'tables' queries
> Solve cross tenant system view query error

- .github/workflows/release.yml
- Makefile
issue https://github.com/matrixorigin/MO-Cloud/issues/2639
add musl build and related release job
> CI: add `musl build` and related release job

- .github/workflows/release.yml
> CI: fix 1.1 dev ci

- pkg/proxy/scaling.go
issue #
delete a log which may cause panic
> [bug] proxy: delete a log

- pkg/testutil/testengine/testdata.go
- pkg/vm/engine/memoryengine/compiler_context.go
issue https://github.com/matrixorigin/matrixone/issues/15299
fix bug: ut（compile_test.go) failed
> fix bug: ut（compile_test.go) failed 

- .github/workflows/e2e-compose.yaml
issue #
related runner image issue: https://github.com/actions/runner-images/issues/9557
> CI: upgrade docker compose to v2

- pkg/sql/colexec/join/join.go
- pkg/sql/colexec/join/types.go
- pkg/sql/colexec/left/join.go
- pkg/sql/colexec/left/types.go
- pkg/sql/colexec/right/join.go
- pkg/sql/colexec/right/types.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/2854
clean batch when hanging in join
> clean batch when hanging in join

- pkg/sql/plan/stats.go
issue #15286 
fix a bug that some filters don't push to block filter
> fix a bug that some filters don't push to block filter for 1.1-dev

- .github/workflows/e2e-compose.yaml
issue #
related runner image issue: https://github.com/actions/runner-images/issues/9557
> CI: upgrade docker compose to v2 for 1.1-dev

- pkg/common/moerr/error.go
- pkg/common/moerr/error_no_ctx.go
- pkg/common/morpc/backend.go
- pkg/lockservice/lock_table_allocator.go
- pkg/lockservice/lock_table_allocator_test.go
- pkg/lockservice/log.go
- pkg/lockservice/rpc.go
- pkg/lockservice/rpc_test.go
- pkg/lockservice/service_remote_test.go
- pkg/lockservice/service_test.go
- pkg/lockservice/test_helper.go
- pkg/lockservice/types.go
- pkg/tnservice/store.go
- pkg/txn/service/service_cn_handler_test.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/2861
1. fix keep remote lock
2. optimize lock table bind changed
> fix keep remote lock

- pkg/vm/engine/tae/common/print.go
- pkg/vm/engine/tae/rpc/inspect.go
- pkg/vm/engine/tae/tables/jobs/flushTableTail.go
- pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
- pkg/vm/engine/tae/tables/updates/delchain.go
- pkg/vm/engine/tae/tables/updates/mvcc.go
- pkg/vm/engine/tae/txn/txnimpl/table.go
issue #15298
change the transfer deletes for flush and merge transaction into 2 phases
> two phase transfer in flushing

- pkg/sql/colexec/right/join.go
issue https://github.com/matrixorigin/MO-Cloud/issues/2854
undo change of rightjoin.sendlast()(#14136)
> undo change of rightjoin.sendlast()(#14136)

- pkg/lockservice/service_remote.go
- pkg/lockservice/service_test.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/2925
fix sync lock table between cn and dn
> fix sync lock table between cn and dn

- pkg/frontend/mysql_cmd_executor.go
- pkg/frontend/query_result.go
issue [#2917](https://github.com/matrixorigin/MO-Cloud/issues/2917)
table name overwritten when show table status
> [Fix] table name be overwrited when show table status

- pkg/sql/plan/apply_indices.go
- pkg/sql/plan/runtime_filter.go
issue https://github.com/matrixorigin/MO-Cloud/issues/2939
allow filters with parameter/variable to use index, then ensure runtime filter is deduced
> cherry-pick index related commits to 1.1-dev

- pkg/lockservice/lock_table_remote.go
- pkg/lockservice/service_test.go
issue #15402 
fix handle lock table bind changed err
> fix handle lock table bind changed err

- pkg/common/morpc/codec.go
- pkg/common/morpc/codec_test.go
- pkg/common/morpc/server.go
issue #15139 
Support unknown flag in morpc, avoid panic
> support unknown flag

- pkg/sql/plan/stats.go
issue #15457
fix stats with limit
> fix stats with limit

- pkg/vm/engine/tae/db/scannerop.go
issue #15367
- avoid data race when creating & altering table
- remove some unused codes
> fix data race when creating table

- pkg/lockservice/cfg.go
issue #15485 
fix panic too large fixed slice
> fix panic too large fixed slice

- pkg/sql/colexec/group/group.go
- pkg/sql/colexec/hashbuild/build.go
- pkg/sql/colexec/mergegroup/group.go
let go schedule cpu in large ap query
Approved by: @zhangxu19830126, @aunjgr, @m-schen
Conflicts:
pkg/sql/colexec/hashbuild/build.go
issue #15139 
let go schedule cpu in large ap query
> let go schedule cpu in large ap query (#15384) to 1.1

- test/distributed/cases/ddl/create_table_as_select.result
- test/distributed/cases/ddl/create_table_as_select.sql
issue #https://github.com/matrixorigin/matrixone/issues/15491
Modify case and add case about authority
> Modify case about auth

- pkg/common/moerr/error_no_ctx.go
- pkg/common/morpc/backend.go
- pkg/lockservice/lock_table_allocator.go
- pkg/lockservice/service.go
- pkg/lockservice/service_remote.go
- pkg/lockservice/service_remote_test.go
Reverts matrixorigin/matrixone#15478
> Revert "detect CN status before remove the lock on an orphan txn"

- pkg/sql/compile/compile.go
- pkg/sql/compile/types.go
issue #15339
fix data race for compileFuzzyFilter.func1, which may cause data correctness issues
> [fix] : fix data race for compileFuzzyFilter.func1

- pkg/fileservice/local_fs.go
- pkg/fileservice/s3_fs.go
- pkg/frontend/mysql_cmd_executor.go
- pkg/util/trace/impl/motrace/statistic/stats_array.go
issue # https://github.com/matrixorigin/MO-Cloud/issues/2982
to get more info from IO-lock
> split lock time consumption （1.1）

- pkg/common/moerr/error_no_ctx.go
- pkg/common/morpc/backend.go
- pkg/lockservice/lock_table_allocator.go
- pkg/lockservice/service.go
- pkg/lockservice/service_remote.go
- pkg/lockservice/service_remote_test.go
Reverts matrixorigin/matrixone#15515
> Revert "Revert "detect CN status before remove the lock on an orphan txn""

- pkg/fileservice/disk_cache.go
- pkg/fileservice/io_lock.go
- pkg/fileservice/local_fs.go
- pkg/fileservice/mem_cache.go
- pkg/fileservice/remote_cache.go
- pkg/util/metric/v2/dashboard/grafana_dashboard_fs.go
- pkg/util/metric/v2/fileservice.go
- pkg/util/metric/v2/metrics.go
issue #15509 
fileservice: more metrics
metric: add io lock dashboard row
> fileservice: more metrics

- pkg/vm/engine/disttae/logtailreplay/partition_state.go
issue #15544
continue the loop if the object entry has existed
> fix return statement in block meta loop 1.1

- pkg/frontend/routine_manager.go
issue https://github.com/matrixorigin/MO-Cloud/issues/3033
fix concurrent map read and map write
> [bug] frontend: fix concurrent map read and map write

- pkg/proxy/mysql_conn_buf.go
- pkg/proxy/tunnel.go
- pkg/proxy/tunnel_test.go
issue https://github.com/matrixorigin/MO-Cloud/issues/3016
1. add some debug logs
2. fix a sequence issue that the server have to transfer the tunnal after the
wait group add one.
> [bug] proxy: fix a sequence issue and add debug logs

- pkg/vm/engine/tae/db/checkpoint/snapshot.go
issue #https://github.com/matrixorigin/matrixone/issues/10397
Fix ListSnapshotCheckpoint
> Fix ListSnapshotCheckpoint

- pkg/frontend/authenticate.go
issue https://github.com/matrixorigin/MO-Cloud/issues/3050
cp https://github.com/matrixorigin/matrixone/pull/15602 to 1.1
> fix: fix skipCheckPrivilege when alter password

- pkg/frontend/session.go
- pkg/proxy/conn_migration.go
issue #15571
check for the nil session
> [bug] frontend: check for the nil session

- pkg/sql/compile/compile.go
Reverts matrixorigin/matrixone#15599
> Revert "try to delay expand ranges as much as possible"

- pkg/sql/compile/scope.go
issue #14940 
fix bug: load run huang
> fix bug: load run huang

- pkg/cnservice/server_query.go
- pkg/frontend/session.go
- pkg/proxy/router.go
- pkg/proxy/server_conn.go
issue https://github.com/matrixorigin/MO-Cloud/issues/3052
add some logs
> [enhancement] add some logs

- pkg/proxy/client_conn.go
issue https://github.com/matrixorigin/MO-Cloud/issues/3052
if connection transfer failed, retry the transfer util there is no cn available.
> [bug] proxy: retry if migrate failed

- pkg/common/mpool/mpool.go
- pkg/sql/compile/scope.go
- pkg/sql/compile/scopeRemoteRun.go
- pkg/sql/compile/scopeRemoteRunTypes.go
This reverts commit 9e890ddafc4eb24e471cd65c6e73bfb1bfef58f5.
issue #15543 
貌似会导致tpch和ssb卡死，先revert.
> Revert "[cherry-pick-15603] fix issue #15543 (#15605)"

- pkg/lockservice/lock_table_local.go
- pkg/lockservice/lock_table_local_test.go
- pkg/lockservice/service.go
- pkg/lockservice/txn.go
- pkg/lockservice/waiter_events.go
issue #15608 
close first waiter invalid, and check can delete lock using old lock record.
> fix close first waiter invalid

- pkg/lockservice/lock_table_local.go
- pkg/lockservice/waiter.go
issue #15624 
fix dead lock check
> try fix dead lock

- pkg/lockservice/lock.go
- pkg/lockservice/lock_table_local.go
- pkg/lockservice/waiter_queue.go
- pkg/lockservice/waiter_queue_test.go
issue #15636 
fix double free and leak free for lockservice waiter
> fix double and leak free

- pkg/config/configuration.go
- pkg/frontend/session.go
Reverts matrixorigin/matrixone#15330
issue #15597 
Revert "cherry-pick sys variables" (#15560)
> Revert "cherry-pick sys variables" (#15560)

- pkg/common/mpool/mpool.go
- pkg/sql/colexec/connector/types.go
- pkg/sql/colexec/dispatch/sendfunc.go
- pkg/sql/colexec/dispatch/types.go
- pkg/sql/compile/scope.go
- pkg/sql/compile/scopeRemoteRun.go
- pkg/sql/compile/scopeRemoteRunTypes.go
issue #15543 
重新提交关于 issue 15543 的修复代码，同时解决了上一个提交由于close channel导致的hung住问题。
> [re-submit] fix issue#15543.

- pkg/sql/plan/base_binder.go
- test/distributed/cases/function/func_datetime_date.result
- test/distributed/cases/function/func_math_floor.result
issue #https://github.com/matrixorigin/MO-Cloud/issues/3093
fix a bug that date function converted to cast
> fix a bug that date function converted to cast

- pkg/sql/colexec/aggexec/concat.go
- pkg/sql/colexec/aggexec/types.go
https://github.com/matrixorigin/MO-Cloud/issues/3061
fix an index error will cause agg merge failed.
> fix an index error of 'group_concat' agg.

- pkg/sql/compile/compile.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/3038
when read blocks less than 200, force scan on one CN
> when read blocks less than 200, force scan on one CN

- pkg/common/moerr/error.go
- pkg/common/moerr/error_no_ctx.go
- pkg/frontend/test/txn_mock.go
- pkg/lockservice/lock_table_allocator.go
- pkg/lockservice/lock_table_allocator_test.go
- pkg/lockservice/lock_table_keeper.go
- pkg/lockservice/lock_table_keeper_test.go
- pkg/lockservice/rpc_test.go
- pkg/lockservice/service.go
- pkg/lockservice/service_remote.go
- pkg/lockservice/service_test.go
- pkg/lockservice/test_helper.go
- pkg/lockservice/txn.go
- pkg/pb/lock/lock.pb.go
- pkg/sql/colexec/lockop/lock_op.go
- pkg/txn/client/operator.go
- pkg/txn/client/types.go
- pkg/txn/storage/memorystorage/storage_txn_client.go
- pkg/vm/engine/entire_engine_test.go
- proto/lock.proto
issue #14336 
lock service rolling restart
> lock service rolling restart

- pkg/cnservice/server.go
- pkg/txn/client/client.go
- pkg/txn/client/leak_checker.go
- pkg/txn/client/leak_checker_test.go
issue #15672
fix cannot found leak txn
> fix cannot found leak txn to 1.1

- pkg/cnservice/server.go
- pkg/txn/client/client.go
- pkg/txn/client/leak_checker.go
- pkg/txn/client/leak_checker_test.go
issue #15672
fix cannot found leak txn
> fix cannot found leak txn

- pkg/frontend/mysql_cmd_executor.go
- pkg/frontend/session.go
issue #15577
fix the code that has been overwritten by another PR and some refactor.
> [postfix] fix the code that has been overwritten by another PR.

- pkg/sql/colexec/anti/types.go
- pkg/sql/colexec/evalExpression.go
- pkg/sql/colexec/external/external.go
- pkg/sql/colexec/fill/fill.go
- pkg/sql/colexec/fuzzyfilter/types.go
- pkg/sql/colexec/hashbuild/types.go
- pkg/sql/colexec/loopanti/join.go
- pkg/sql/colexec/loopsemi/join.go
- pkg/sql/colexec/loopsingle/join.go
- pkg/sql/colexec/mark/join.go
- pkg/sql/colexec/projection/projection.go
- pkg/sql/colexec/single/join.go
- pkg/sql/colexec/table_function/generate_series.go
- pkg/sql/colexec/table_function/generate_series_test.go
- pkg/sql/colexec/table_function/metadata_scan.go
- pkg/sql/colexec/table_function/types.go
- pkg/sql/colexec/table_function/unnest.go
- pkg/sql/colexec/table_function/unnest_test.go
- pkg/sql/colexec/top/types.go
- pkg/sql/plan/explain/explain_expr.go
issue #15338 #15368
fix double free in some case
> fix double free in some case

- pkg/fileservice/aliyun_sdk.go
- pkg/fileservice/aws_sdk_v1.go
- pkg/fileservice/aws_sdk_v2.go
- pkg/fileservice/error.go
- pkg/fileservice/minio_sdk.go
- pkg/fileservice/retry.go
- pkg/fileservice/retryable_reader_test.go
issue #15398
expose these functions to help retry writing.
> fileservice: expose DoWithRetry and IsRetryableError (#15689)

- pkg/sql/compile/compile.go
#15543 
may help with #15656
修改一个上下文不匹配的问题，这可能会导致发送方无法正确感知接收方是否已经结束。
> fix a context mismatched bug when join happens.

- README.md
- README_CN.md
issue #[#1030](https://github.com/matrixorigin/matrixorigin.io.cn/issues/1030)
> update readme 1.1.3

- pkg/sql/plan/function/list_builtIn.go
issue https://github.com/matrixorigin/MO-Cloud/issues/1841
support scale in function sysdate
> support scale in function sysdate

- pkg/vm/engine/tae/blockio/reader.go
- pkg/vm/engine/tae/db/gc/table.go
issue https://github.com/matrixorigin/matrixone/issues/15782
The memory referenced during the DiskGC replay is released, and invalid memory is replayed.
> Fix disk gc replay

- pkg/sql/compile/compile.go
- pkg/vm/engine/disttae/engine.go
issue #15457
fix the num of cpu for docker environment
> fix the num of cpu for docker environment

- pkg/sql/compile/compile.go
issue #15800 https://github.com/matrixorigin/MO-Cloud/issues/3113
fix panic when load data
> fix panic when load data

- pkg/lockservice/lock_table_allocator.go
- pkg/lockservice/lock_table_allocator_test.go
- pkg/lockservice/service_test.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/3153
fix leave get bind in restart cn
> fix leave get bind in restart cn

- pkg/vm/engine/disttae/logtailreplay/partition_state.go
issue #15825
Remove handle metadata delete.
> rm handle metadata delete

- pkg/backup/backup.go
- pkg/backup/backup_test.go
- pkg/backup/fs.go
- pkg/backup/tae.go
- pkg/objectio/writer.go
- pkg/vm/engine/tae/logtail/backup.go
issue https://github.com/matrixorigin/MO-Cloud/issues/2942
Add backup parallel&retry
> Add backup parallel&retry

- pkg/vm/engine/tae/tables/updates/mvcc.go
> fix dead lock

- pkg/util/address/address.go
issue https://github.com/matrixorigin/matrixone/issues/15759
use new method to check if the port is available
> [enhancement] util: use new method to check if the port is available

- pkg/vm/engine/tae/blockio/pipeline.go
- pkg/vm/engine/tae/catalog/catalog.go
- pkg/vm/engine/tae/catalog/catalogreplay.go
- pkg/vm/engine/tae/catalog/database.go
- pkg/vm/engine/tae/catalog/mock.go
- pkg/vm/engine/tae/db/open.go
- pkg/vm/engine/tae/db/test/db_test.go
- pkg/vm/engine/tae/options/options.go
- pkg/vm/engine/tae/options/types.go
- pkg/vm/engine/tae/rpc/base_test.go
- pkg/vm/engine/tae/rpc/handle.go
- pkg/vm/engine/tae/txn/txnbase/txnmgr.go
- pkg/vm/engine/tae/txn/txnimpl/store.go
issue #15909
cp pr 1b00a0843fff68a1d07f28f94baf2e20700cf957 and fb8da325f47d9050a1600dc8aa4acd4142ad2fa2
> cp catalog and options change to 1.2

- pkg/util/metric/v2/dashboard/grafana_dashboard_task.go
- pkg/vm/engine/tae/db/merge/executor.go
issue #15268
add target object size config when merge objects.
> fix index table merge too much on 1.2

- pkg/bootstrap/service.go
- pkg/bootstrap/versions/v1_2_0/cluster_upgrade_list.go
- pkg/bootstrap/versions/v1_2_0/tenant_upgrade_list.go
- pkg/frontend/authenticate.go
- pkg/frontend/predefined.go
- pkg/util/sysview/predefined.go
- pkg/util/sysview/sysview.go
issue #15756
把mo系统表和系统视图声明为全局变量，都引用自一处，降低耦合
> Predefine system table as global var (#15925)

- pkg/vm/engine/tae/tables/updates/mvcc.go
issue #15715
Fix the bug of losing deltaLoc when doing checkpoint
> Fix the bug of losing deltaLoc when doing checkpoint

- pkg/taskservice/mysql_task_storage.go
- pkg/taskservice/task_service.go
issue #16010
Add error log in taskservice when task service cannot get db.
> add error log in taskservice

- pkg/incrservice/service.go
- pkg/incrservice/table_cache.go
- pkg/incrservice/types.go
- pkg/sql/colexec/preinsert/preinsert.go
issue #15933
improve incr service  to 1.2
> improve incr service  to 1.2

- cmd/mo-service/main.go
- pkg/cnservice/server.go
issue #https://github.com/matrixorigin/matrixone/issues/15856
解决OMM时，profile过时问题。
在收到TERM和INT信号时，报错heap和goroutine profile 到etlfs。
限制：
1.不能处理KILL信号。
2.写etlfs的超时为3分钟。写heap,goroutine总共最多6分钟。
> add dump profile

- pkg/vm/engine/tae/db/db.go
issue #https://github.com/matrixorigin/matrixone/issues/13012
should re-clear the pending ckp when retry.
> sync to 1.2: fix `ForceCheckpoint` retry logic.

- pkg/vm/engine/tae/db/db.go
issue #https://github.com/matrixorigin/matrixone/issues/13012
should re-clear the pending ckp when retry.
sync to 1.2: https://github.com/matrixorigin/matrixone/pull/16030
> fix `ForceCheckpoint` retry logic.

- pkg/frontend/computation_wrapper.go
- pkg/frontend/mysql_cmd_executor.go
issue #https://github.com/matrixorigin/matrixone/issues/15982
https://github.com/matrixorigin/matrixone/issues/15975
本地sysbench 1000w 没复现出oom。
对2处潜在的stmt引用问题，做了修改。
> fix parse oom

- pkg/frontend/test/txn_mock.go
- pkg/lockservice/service_test.go
- pkg/sql/colexec/lockop/lock_op.go
- pkg/txn/client/operator.go
- pkg/txn/client/types.go
- pkg/txn/storage/memorystorage/storage_txn_client.go
- pkg/vm/engine/entire_engine_test.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/3231
retry for first lock table bind change
> retry for first lock table bind change

- optools/mo_checkin_regression/mo_checkin_regression_tke.yaml
> add leak config to mergerun cn

- optools/mo_checkin_regression/mo_checkin_regression_tke.yaml
> add leak config to mergerun cn for 1.2-dev

- pkg/vm/engine/tae/iface/data/object.go
- pkg/vm/engine/tae/tables/aobj.go
- pkg/vm/engine/tae/tables/base.go
- pkg/vm/engine/tae/tables/obj.go
- pkg/vm/engine/tae/tables/updates/mvcc.go
issue #https://github.com/matrixorigin/matrixone/issues/12107
fix test delete3, cherry-pick #16054
> fix test delete3, cherry-pick #16054

- pkg/frontend/result_row_stmt.go
- pkg/frontend/routine.go
- pkg/frontend/session.go
- pkg/frontend/txn.go
issue #https://github.com/matrixorigin/matrixone/issues/16042
1. 修改错误的迁移场景
begin，后无commit。
autocommit = 0且无begin且无commit。
这两种场景不应该有迁移。如果迁移后面会有问题。
2. 删除不必要的状态切换
ci regression : https://github.com/matrixorigin/ci-test/actions/runs/9062088432
> fix wrong txn status

- pkg/vm/engine/tae/catalog/object.go
- pkg/vm/engine/tae/tables/aobj.go
- pkg/vm/engine/tae/tables/base.go
- pkg/vm/engine/tae/tables/jobs/flushTableTail.go
- pkg/vm/engine/tae/tables/obj.go
- pkg/vm/engine/tae/tables/updates/delchain.go
issue #https://github.com/matrixorigin/matrixone/issues/15959
Not check whether object is dropped when flush deletes.
> Fix flush deletes, cherry-pick #15961

- .github/workflows/merge-trigger-standalone.yaml
- .github/workflows/merge-trigger-tke.yaml
> add trigger condition for mergerun

- .github/workflows/merge-trigger-standalone.yaml
- .github/workflows/merge-trigger-tke.yaml
> add trigger condition for mergerun for 1.2 dev

- pkg/vm/engine/disttae/merge.go
- pkg/vm/engine/tae/db/test/db_test.go
- pkg/vm/engine/tae/db/test/hidden_test.go
- pkg/vm/engine/tae/mergesort/merger.go
- pkg/vm/engine/tae/mergesort/task.go
- pkg/vm/engine/tae/tables/jobs/mergeobjects.go
- pkg/vm/engine/tae/tables/txnentries/mergeobjects.go
issue #16111
Fix del map panic when object merge creates more than one objects.
> fix del map error after merge

- pkg/sql/compile/operator.go
- test/distributed/cases/benchmark/tpch/02_LOAD/11_select_count_snapshot.result
- test/distributed/cases/benchmark/tpch/02_LOAD/11_select_count_snapshot.sql
- test/distributed/cases/benchmark/tpch/04_CLEANUP/01_DROP.result
- test/distributed/cases/benchmark/tpch/04_CLEANUP/01_DROP.sql
- test/distributed/cases/benchmark/tpch/04_CLEANUP/02_Snapshot.result
- test/distributed/cases/benchmark/tpch/04_CLEANUP/02_Snapshot.sql
- test/distributed/cases/benchmark/tpch/04_CLEANUP/03_Snapshot_tpch.result
- test/distributed/cases/benchmark/tpch/04_CLEANUP/03_Snapshot_tpch.sql
- test/distributed/cases/snapshot/snapshot_read_incremental_data.result
- test/distributed/cases/snapshot/snapshot_read_incremental_data.sql
issue #16055
fix snapshot read with addtion data
> fix snapshot read with addtion data(#1.2-dev)

- pkg/proxy/tunnel.go
issue #16042
when sequence id is rotated, there may be a wrong ok packet.
so do not allow transfer connection when sequence id is rotated.
> [bug] proxy: when sequence id is rotated, there may be a wrong ok packet

- pkg/lockservice/service_test.go
- pkg/lockservice/txn.go
issue #16121 
skip unlock remote table for remote txn
> skip unlock remote table for remote txn

- pkg/lockservice/waiter_events.go
issue #15960 
fix deadlock by log wait tool long
> fix deadlock by log wait tool long

- pkg/frontend/snapshot.go
issue https://github.com/matrixorigin/matrixone/issues/15943
fix: drop all current dbs when restore account
> [Cherry-pick] fix: drop all current dbs when restore account

- pkg/common/malloc/bench_test.go
- pkg/common/malloc/flush.go
- pkg/common/malloc/handle.go
- pkg/common/malloc/malloc.go
- pkg/common/malloc/malloc_test.go
- pkg/fileservice/memorycache/data_alloc_free.go
issue #15479 
make max class size to 4M
malloc: add clear param to Alloc
malloc: more benchmarks
> malloc: tune params

- pkg/fileservice/disk_cache.go
- pkg/fileservice/io_entry.go
- pkg/fileservice/local_etl_fs.go
- pkg/fileservice/local_fs.go
- pkg/fileservice/memory_fs.go
- pkg/fileservice/s3_fs.go
issue #15508
cache codes clean-up
> fileservice: remove LocalFS/S3FS.allocator

- pkg/lockservice/lock_table_keeper.go
- pkg/lockservice/service.go
- pkg/lockservice/service_test.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/3231
fix active table is moved when restart cn
> fix active table is moved when restart cn

- pkg/frontend/snapshot.go
issue #15971 
fix collect fkDeps with no specified dbName and tableName
> fix restore fk-table

- pkg/frontend/snapshot.go
issue #15971 
fix collect fkDeps with no specified dbName and tableName
> [Cherry-pick] fix restore fk-table

- pkg/vm/engine/tae/catalog/object.go
- pkg/vm/engine/tae/tables/aobj.go
- pkg/vm/engine/tae/tables/updates/mvcc.go
issue #16155 
Fix allAppendsCommitted, not release the lock between checking HasDropCommitted and PrepareCompact.
> fix allAppendsCommitted, cherry-pick #16167

- pkg/fileservice/disk_cache.go
- pkg/fileservice/file_service.go
- pkg/fileservice/io_entry.go
- pkg/fileservice/local_etl_fs.go
- pkg/fileservice/local_fs.go
- pkg/fileservice/memory_fs.go
- pkg/fileservice/s3_fs.go
issue #16202 
revert changes due to TPCC performance regression
> fileservice: revert changes due to TPCC performance regression

- pkg/vm/engine/disttae/util.go
issue #16197 
cleanup some usage of UnsafeStringToBytes due to reuse
> cleanup some usage of UnsafeStringToBytes due to reuse

- pkg/sql/compile/compile.go
- pkg/sql/compile/operator.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/3282
移除无用的bucket相关逻辑，强制union在单cn上运行。等以后优化支持shuffle
> fix a bug that cause wrong result in union

- pkg/sql/plan/build_insert.go
> [fix] use runtime filter for multi-row prepared insert stmt

- pkg/frontend/mysql_cmd_executor.go
- pkg/frontend/result_row_stmt.go
issue #https://github.com/matrixorigin/matrixone/issues/15190
问题原因：
explain 与 explain analyze走得不同的逻辑。
提取explain anaylze column defs 的逻辑不对。
修改方案：
为explain anaylze设置正确的column defs。
> fix query result

- pkg/sql/compile/scope.go
- test/distributed/cases/snapshot/snapshot_restore_to_table_partition.result
- test/distributed/cases/snapshot/snapshot_restore_to_table_partition.sql
fix restore partition table
Approved by: @heni02, @ouyuanning
issue #16213 
fix restore partition table
> fix restore partition table (#1.2-dev)

- pkg/cnservice/server.go
- pkg/cnservice/types.go
- pkg/txn/trace/service.go
issue #15960 
make load trace to s3 as default
> make load trace to s3 as default

- CODEOWNERS
- cmd/mo-service/config.go
- etc/launch/cn.toml
- etc/launch/log.toml
- etc/launch/tn.toml
- pkg/common/malloc/checked_deallocator.go
- pkg/common/malloc/checked_deallocator_test.go
- pkg/common/malloc/class_allocator.go
- pkg/common/malloc/config.go
- pkg/common/malloc/default.go
- pkg/common/malloc/default_test.go
- pkg/common/malloc/unsafe.go
- pkg/fileservice/memorycache/cache.go
- pkg/fileservice/memorycache/cache_test.go
- pkg/fileservice/memorycache/data_test.go
- pkg/fileservice/memorycache/rc_bytes_test.go
issue #16059 
malloc: add TestCheckedDeallocator
malloc: more logs
add code owner
> malloc: add checked deallocator

- pkg/vm/engine/tae/db/checkpoint/snapshot.go
- pkg/vm/engine/tae/db/gc/checkpoint.go
GC needs to be compatible with the earliest checkpoint
issue https://github.com/matrixorigin/MO-Cloud/issues/3312
GC needs to be compatible with the earliest checkpoint
> GC needs to be compatible with the earliest checkpoint

- pkg/vm/engine/tae/db/checkpoint/snapshot.go
- pkg/vm/engine/tae/db/gc/checkpoint.go
GC needs to be compatible with the earliest checkpoint
issue[ #3312](https://github.com/matrixorigin/MO-Cloud/issues/3312)
GC needs to be compatible with the earliest checkpoint
> GC needs to be compatible with the earliest checkpoint for 1.2

- pkg/frontend/test/engine_mock.go
- pkg/sql/colexec/shuffle/shuffle.go
- pkg/sql/colexec/shuffle/types.go
- pkg/sql/colexec/shufflebuild/build_test.go
- pkg/sql/compile/compile.go
- pkg/sql/compile/scopeRemoteRun.go
- pkg/sql/compile/scopeRemoteRunTypes.go
- pkg/sql/plan/opt_misc.go
- pkg/sql/plan/types.go
- pkg/vm/engine/disttae/engine.go
- pkg/vm/engine/disttae/types.go
- pkg/vm/engine/entire_engine.go
- pkg/vm/engine/entire_engine_test.go
- pkg/vm/engine/memoryengine/binded.go
- pkg/vm/engine/memoryengine/engine.go
- pkg/vm/engine/types.go
- pkg/vm/process/message.go
- pkg/vm/process/process.go
- test/distributed/cases/optimizer/runtimefilter.result
- test/distributed/cases/optimizer/runtimefilter.test
This reverts commit 6cbb39c511c8bee68b327c100d5114dddacd9090.
issue #16021 
Revert "[Tech Request]: refactor message on multi CN (#16308)"
> Revert "[Tech Request]: refactor message on multi CN (#16308)"

- pkg/taskservice/task_service_cron.go
issue #16053
cron task may be deleted in table when scheduling it in memory.
> fix TestRemovedCronTask panic

- test/distributed/cases/ddl/create_table_as_select.result
- test/distributed/cases/ddl/create_table_as_select.sql
issue #16300
next time the #16300 problem is captured, we can tell whether it's the global variable not taking effect or the column name being tampered.
> add a bvt case to help debugging

- pkg/taskservice/task_runner.go
- pkg/taskservice/task_runner_test.go
issue #11250 
1. Chances are that task completed but not removed.
2. Chances are that task running but not added in `running.m`.
> fix 11250 on 1.2-dev

- pkg/perfcounter/counter_set.go
- pkg/sql/compile/compile.go
- pkg/sql/compile/fuzzyCheck.go
- pkg/sql/compile/reuse.go
- pkg/vm/process/analyze.go
issue #14940 
Add reset method for Compile
> Add reset method for Compile

- pkg/common/malloc/config.go
- pkg/common/malloc/default.go
> malloc: fix initialization race

- pkg/pb/status/status.pb.go
issue #16007
add some recover logs. After issue resolved, remote them.
> add some recover logs

- pkg/lockservice/lock_table_local.go
- pkg/lockservice/service_test.go
issue #16309
fix does not unlock deadlock txn
> fix does not unlock deadlock txn

- pkg/fileservice/io_entry.go
- pkg/fileservice/local_fs.go
- pkg/fileservice/s3_fs.go
- pkg/util/metric/v2/dashboard/grafana_dashboard_fs.go
- pkg/util/metric/v2/fileservice.go
- pkg/util/metric/v2/metrics.go
> fileservice: more metrics for Read

- test/distributed/cases/snapshot/nonsys_restore_view_to_nonsys_account.result
- test/distributed/cases/snapshot/nonsys_restore_view_to_nonsys_account.sql
- test/distributed/cases/snapshot/sys_restore_view_to_newnonsys_account.result
- test/distributed/cases/snapshot/sys_restore_view_to_newnonsys_account.sql
- test/distributed/cases/snapshot/sys_restore_view_to_nonsys_account.result
- test/distributed/cases/snapshot/sys_restore_view_to_nonsys_account.sql
- test/distributed/cases/snapshot/sys_restore_view_to_sys_account.result
- test/distributed/cases/snapshot/sys_restore_view_to_sys_account.sql
issue ##https://github.com/matrixorigin/matrixone/issues/16371
https://github.com/matrixorigin/matrixone/issues/16311
https://github.com/matrixorigin/matrixone/issues/16306
https://github.com/matrixorigin/matrixone/issues/16297
rm tag 16311 16306 16297
> rm tag 16311 16306 16297(1.2-dev)

- pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
- pkg/util/metric/v2/metrics.go
- pkg/util/metric/v2/txn.go
- pkg/vm/engine/disttae/filter.go
- pkg/vm/engine/disttae/reader.go
- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/disttae/types.go
- pkg/vm/engine/disttae/util.go
- pkg/vm/engine/disttae/util_test.go
This reverts commit e4c504a606585cb373a5bb7c452e804469716610.
issue #https://github.com/matrixorigin/matrixone/issues/16379
revert to avoid oom
> Revert "remove the old fast ranges and update metrics. (#16350)"

- pkg/frontend/snapshot.go
- pkg/sql/plan/build_show_util.go
issue https://github.com/matrixorigin/matrixone/issues/16372
fix get fk table failed when doing restoration
> fix get fk table failed when doing restoration

- pkg/vm/engine/tae/containers/utils.go
- pkg/vm/engine/tae/containers/vector.go
issue https://github.com/matrixorigin/MO-Cloud/issues/3305
Fix GetByteSlice out range
> Fix GetByteSlice out range for 1.2

- .github/mergify.yml
issue #
___
Tests
___
- Updated the Mergify configuration to ensure the commit message template correctly parses and includes the relevant section of the PR body.
- Modified the `commit_message_template` to use `body.split("___\n\n### **PR Type**")[0]` for extracting the "What this PR does / why we need it" section.
___
<tr>
<td>
<details>
<summary><strong>mergify.yml</strong><dd><code>Update commit message template in Mergify configuration</code>&nbsp; &nbsp; </dd></summary>
<hr>
<li>Updated the commit message template to correctly parse the PR body.<br> <li> Modified the <code>commit_message_template</code> to use …
> CI: update mergify config to get correct commit message for 1.2-dev

- .github/mergify.yml
issue #
___
Tests
___
- Updated the Mergify configuration to improve the extraction of PR descriptions for commit messages.
- Modified the `commit_message_template` to use a new method for extracting the PR description before the "PR Type" section.
___
<tr>
<td>
<details>
<summary><strong>mergify.yml</strong><dd><code>Update commit message template in Mergify configuration</code>&nbsp; &nbsp; </dd></summary>
<hr>
<li>Modified the <code>commit_message_template</code> to use a new method for <br>extracting the PR description.<br> <li> Replaced the <code>body | get_section</code> method with <code>body.split("___\n\n### …
> CI: update mergify config to get correct commit message

- pkg/sql/compile/compile.go
issue #16542
对于优化器打上tp标签的query，确保任何情况下都一定是单并发的pipeline。
优化output算子，tp场景下，可以直接连接到最后一个scope上，而不需要通过connector->merge来进行连接。
___
Enhancement
___
- Introduced a new `getEngineNode` function to centralize the creation of `engine.Node` objects, reducing code duplication.
- Replaced direct instantiations of `engine.Node` with calls to the new `getEngineNode` function.
- Modified the `compileSteps` function to handle `ExecTypeTP` by directly using the last scope instead of merging.
- Adjusted the `generateCPUNumber` function to return 1 for `ExecTypeTP`, ensuring single-threaded execution.
___
<tr>
<td>
<details> …
> [Tech Request]: optimize pipeline for tp query

- test/distributed/cases/snapshot/sys_restore_pubsub_to_sys_account.result
- test/distributed/cases/snapshot/sys_restore_pubsub_to_sys_account.sql
issue ##https://github.com/matrixorigin/matrixone/issues/11492
add case for restore pub_sub
___
Tests
___
- Added new test cases for restoring accounts from snapshots and handling publications.
- Included SQL commands to create, drop, and manipulate accounts, databases, tables, snapshots, and publications.
- Added various scenarios to test the integrity and consistency of database states after restoration.
- Verified the handling of publications and subscriptions between different accounts.
___
<tr>
<td>
<details>
<summary><strong>sys_restore_pubsub_to_sys_account.result</strong><dd><code>Add test cases for restoring accounts and handling …
> add case for restore pub_sub

- pkg/frontend/util.go
issue #16613 
fix convert string to timestamp
___
Bug fix
___
- Added type checking and conversion logic for `string` to `timestamp` in `convertRowsIntoBatch` function.
- Implemented error handling for unsupported types during conversion.
- Used `types.ParseTimestamp` to handle string to timestamp conversion.
___
<tr>
<td>
<details>
<summary><strong>util.go</strong><dd><code>Fix string to timestamp conversion with error handling</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pkg/frontend/util.go
<li>Added type checking for <code>string</code> to <code>timestamp</code> conversion.<br> <li> Implemented error handling for invalid type conversion.<br> <li> Used …
> fix convert string to timestamp

- pkg/frontend/util.go
issue #16662 
handle null in convertRowsIntoBatch
___
Bug fix
___
- Added handling for null values in the `convertRowsIntoBatch` function to prevent errors when encountering nulls.
- Introduced the `nulls` package to manage null values within vectors.
- Updated type-specific cases (e.g., `T_varchar`, `T_int16`, `T_int32`, etc.) to check for null values and mark them using the `nsp.Add` method.
- Ensured that null values are set in the vector after processing each column by calling `bat.Vecs[colIdx].SetNulls(nsp)`.
___
<tr>
<td>
<details>
<summary><strong>util.go</strong><dd><code>Handle null values in `convertRowsIntoBatch` function</code>&nbsp; &nbsp; …
> [Cherry-pick] handle null in convertRowsIntoBatch

- pkg/frontend/snapshot.go
- test/distributed/cases/snapshot/snapshot_restore_publication.result
- test/distributed/cases/snapshot/snapshot_restore_publication.sql
fix restore pub db
Approved by: @daviszhen, @heni02
issue #https://github.com/matrixorigin/matrixone/issues/16597
fix restore pub db
> fix restore pub db (#1.2-dev)

- pkg/sql/compile/compile.go
issue #16542 
optimize limit operator in pipeline for tp query, don't need toplimit
> optimize limit operator in pipeline for tp query

- test/distributed/cases/save_query_result/save_query_result.result
- test/distributed/cases/save_query_result/save_query_result.sql
issue #16613 
Add issue 16613 cases
___
Bug fix, Tests
___
- Added new test cases to address issue #16613.
- Included SQL commands to create and drop an account, database, table, and publication.
- Added commands to insert data into a table and show publications and subscriptions.
- Included cleanup commands to drop the publication, database, and account.
___
<tr>
<td>
<details>
<summary><strong>save_query_result.result</strong><dd><code>Add test cases for issue 16613 in save_query_result.result</code></dd></summary>
<hr>
test/distributed/cases/save_query_result/save_query_result.result
<li>Added SQL commands to create and drop an account, database, table, and …
> Add issue 16613 cases

- go.mod
- go.sum
- pkg/fileservice/aliyun_sdk.go
- pkg/fileservice/aws_sdk_v1.go
- pkg/fileservice/aws_sdk_v2.go
- pkg/fileservice/http_client.go
- pkg/fileservice/minio_sdk.go
issue #16651 #16618
cherry-pick HTTP client and DNS resolver changes
> cherry-pick http client and dns changes to 1.2-dev 

- pkg/sql/compile/scopeRemoteRunTypes.go
issue #16542 
fix a bug that cause ap performance regression on multi cn
> fix a bug that cause ap performance regression on multi cn

- pkg/util/metric/v2/dashboard/grafana_dashboard_runtime.go
issue #16745 
refine go runtime metrics dashboard
> dashboard: refactor runtime dashboard

- pkg/frontend/authenticate.go
- pkg/frontend/snapshot.go
- pkg/frontend/util.go
issue #16098
handle ctrl+c failed to cancel during restore data
> Handle Cancel Restore Statement Fail

- pkg/frontend/util.go
- pkg/sql/plan/alter_partition_util.go
- pkg/sql/plan/build.go
- pkg/sql/plan/build_dcl.go
- pkg/sql/plan/build_ddl.go
- pkg/sql/plan/build_delete.go
- pkg/sql/plan/build_insert.go
- pkg/sql/plan/build_load.go
- pkg/sql/plan/build_update.go
- pkg/sql/plan/partition_test.go
- pkg/sql/plan/query_builder.go
- pkg/sql/plan/query_builder_test.go
- pkg/sql/plan/stats.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/3404
skip stats for create view to 1.2-dev
> skip stats for create view to 1.2-dev

- CODEOWNERS
issue #16654
add XuPeng-SH as vector owner
> add a code owner for vector

- CODEOWNERS
issue #16654 
add a code owner for vector
> add a code owner for 1.2

- pkg/fileservice/s3_fs.go
- pkg/util/metric/v2/dashboard/grafana_dashboard_fs.go
- pkg/util/metric/v2/fileservice.go
issue #15509 
add metrics for io.ReadAll
> fileservice: tune metrics dashboard

- test/distributed/cases/function/func_hex_unhex.result
- test/distributed/cases/function/func_hex_unhex.sql
rm tag 16710
issue #https://github.com/matrixorigin/matrixone/issues/16710
rm tag 16710
> rm tag 16710(1.2-dev)

- test/distributed/cases/snapshot/sys_restore_to_nonsys_account.sql
add tag 16709
issue #https://github.com/matrixorigin/matrixone/issues/16709
add tag 16709
> add tag 16709(1.2-dev)

- pkg/sql/plan/external.go
issue #16841 
workaround for external stats for result scan
> fix stats for result scan

- pkg/fileservice/disk_cache.go
issue #16899 
more info for disk cache error logs
> fileservice: refine disk cache error handling codes

- pkg/sql/plan/build_show_util.go
- test/distributed/cases/comment/comment.result
- test/distributed/cases/comment/comment.sql
fix show create table
Approved by: @heni02, @badboynt1
issue #https://github.com/matrixorigin/MO-Cloud/issues/3470
fix show create table
> fix show create table  (#1.2-dev)

- pkg/fileservice/http_client.go
issue # https://github.com/matrixorigin/MO-Cloud/issues/3480
increase timeouts.
> fileservice: tune http read write timeout

- test/distributed/cases/comment/comment.result
- test/distributed/cases/comment/comment.sql
- test/distributed/cases/snapshot/snapshot_restore_view.result
- test/distributed/cases/snapshot/snapshot_restore_view.sql
add bvt test
Approved by: @heni02
issue #https://github.com/matrixorigin/MO-Cloud/issues/3470
add bvt test
> add bvt test (#1.2-dev)

- pkg/container/vector/reuse.go
- pkg/container/vector/vector.go
- pkg/sql/colexec/anti/types.go
- pkg/sql/colexec/evalExpression.go
- pkg/sql/colexec/join/types.go
- pkg/sql/colexec/left/types.go
- pkg/sql/colexec/loopanti/types.go
- pkg/sql/colexec/loopsemi/types.go
- pkg/sql/colexec/table_scan/table_scan.go
- pkg/sql/colexec/table_scan/types.go
- pkg/sql/plan/rule/constant_fold.go
- pkg/sql/plan/utils.go
- pkg/vm/engine/disttae/logtailreplay/partition_state.go
- pkg/vm/engine/disttae/reader.go
- pkg/vm/engine/disttae/util.go
- pkg/vm/engine/tae/blockio/read.go
- pkg/vm/engine/tae/logtail/handle.go
- pkg/vm/process/process.go
issue https://github.com/matrixorigin/MO-Cloud/issues/3372
清理了一部分没有被及时回收的vector，那样会导致mpool统计的问题，也会影响vector这个结构体的复用。
目前依然存在没有被正确free的情况，只是不太好查了。
> make sure vector will be free

- pkg/container/vector/reuse.go
- pkg/container/vector/vector.go
- pkg/sql/colexec/anti/types.go
- pkg/sql/colexec/evalExpression.go
- pkg/sql/colexec/join/types.go
- pkg/sql/colexec/left/types.go
- pkg/sql/colexec/loopanti/types.go
- pkg/sql/colexec/loopsemi/types.go
- pkg/sql/colexec/table_scan/table_scan.go
- pkg/sql/colexec/table_scan/types.go
- pkg/sql/plan/rule/constant_fold.go
- pkg/sql/plan/utils.go
- pkg/vm/engine/disttae/logtailreplay/partition_state.go
- pkg/vm/engine/disttae/reader.go
- pkg/vm/engine/disttae/util.go
- pkg/vm/engine/tae/blockio/read.go
- pkg/vm/engine/tae/logtail/handle.go
- pkg/vm/process/process.go
This reverts commit 2e1afe342f8ce4b9b724c654d075bc4e5596d46b.
issue [#3372](https://github.com/matrixorigin/MO-Cloud/issues/3372)
This reverts commit 2e1afe342f8ce4b9b724c654d075bc4e5596d46b.
> Revert "make sure vector will be free (#16955)"

- pkg/vm/engine/tae/catalog/schema.go
- pkg/vm/engine/tae/db/gc/types.go
- pkg/vm/engine/tae/db/test/db_test.go
- pkg/vm/engine/tae/logtail/snapshot.go
issue https://github.com/matrixorigin/matrixone/issues/16967
Fix Rebuild snapshot's table meta
> Fix Rebuild snapshot's table meta for main

- pkg/txn/client/client.go
issue #16716
retry to get latest ts, but do not fatal if waiter is paused when wait for the ts.
> [bug] txn: do not fatal if waiter is paused when wait for the ts.

- pkg/vm/engine/tae/logstore/driver/logservicedriver/truncate.go
issue #16987
comsume ErrInvalidTruncateLsn
___
Bug fix
___
- Added logging at the start of the truncate process to improve traceability.
- Introduced handling for `ErrInvalidTruncateLsn` by verifying if the LSN is already truncated, preventing unnecessary retries.
- Enhanced logging messages to include LSN details during retry attempts and upon successful truncation.
___
<tr>
<td>
<details>
<summary><strong>truncate.go</strong><dd><code>Enhance truncate process with error handling and logging</code>&nbsp; </dd></summary>
<hr>
pkg/vm/engine/tae/logstore/driver/logservicedriver/truncate.go
<li>Added logging for the start of the truncate process.<br> <li> …
> fix truncate

- pkg/sql/compile/scope.go
issue #14940 
之前一个重构引起的merge run问题，就不单独开issue了
> bug fix: load s3 panic

- pkg/lockservice/service.go
- pkg/pb/lock/lock.go
issue [#3530](https://github.com/matrixorigin/MO-Cloud/issues/3530)
add more log for debug fatal
> add more log

- pkg/logservice/service_bootstrap.go
> logservice: fix memory leak

- pkg/objectio/funcs.go
issue #17022 
copy to avoid memory leak
> objectio: copy to avoid memory leak

- pkg/cnservice/server.go
- pkg/incrservice/service.go
- pkg/incrservice/store_sql.go
- pkg/incrservice/types.go
- pkg/util/executor/types.go
issue #16982 
retry allocate if orphan txn
> retry allocate if orphan txn

- pkg/common/morpc/client.go
- pkg/proxy/handler.go
- pkg/proxy/server.go
- pkg/proxy/tunnel.go
issue #16574
clean some errors log
> [enhancement] proxy: clean some logs

- pkg/vm/engine/disttae/db.go
- [x ] BUG
issue #17012 
1. fix snapshot-read bug.
> fix snapshot-read bug

- pkg/fileservice/disk_cache.go
- pkg/fileservice/event_logger.go
- pkg/fileservice/event_logger_test.go
- pkg/fileservice/io_entry.go
- pkg/fileservice/local_etl_fs.go
- pkg/fileservice/local_fs.go
- pkg/fileservice/memory_fs.go
- pkg/fileservice/s3_fs.go
issue #16661 
log details of slow S3.Read
> fileservice: add event logger and log slow S3.Read

- pkg/cnservice/server.go
- pkg/sql/colexec/server.go
- pkg/sql/colexec/types.go
- pkg/sql/compile/remoterunServer.go
https://github.com/matrixorigin/MO-Cloud/issues/3542
1. 这行代码的逻辑目前并不重要，但是由于无法正常感知到网络断开，会有问题，因此暂时删除。
在main分支上将恢复这段逻辑。
2. 调整了一个日志的日志等级。
3. 调整了一个map的结构。
___
___
- Changed log level from Error to Info in `pkg/cnservice/server.go` for better log management.
- Removed unnecessary code in `pkg/sql/compile/remoterunServer.go` that waits for the connection context to be done, preventing potential memory leaks.
- Added comments in `pkg/sql/compile/remoterunServer.go` explaining the removal and future optimization plans.
___
<tr>
<td>
<details>
<summary><strong>server.go</strong><dd><code>Adjust log level for pipeline message error …
> remove an unnecessary code, modify a log level.

- pkg/vm/engine/disttae/txn_table.go
- test/distributed/cases/publication_subscription/pub_sub_improvment.result
- test/distributed/cases/publication_subscription/pub_sub_improvment.sql
issue #https://github.com/matrixorigin/matrixone/issues/17024
adding a log to observe txnTable.Size().
> adding log debug size()

- pkg/lockservice/cfg.go
issue #16438 
Adjust timeout for orphan transactions.
> adjust timeout for orphan transactions

- pkg/container/vector/vector.go
- pkg/vm/engine/disttae/filter.go
- pkg/vm/engine/disttae/util.go
- pkg/vm/engine/disttae/util_test.go
- test/distributed/cases/disttae_filters/ranges_filters/ranges_filters.result
- test/distributed/cases/disttae_filters/ranges_filters/ranges_filters.sql
issue #https://github.com/matrixorigin/matrixone/issues/16976
fix ranges bug of more than 2 augments in or expression.
> sync to 1.2: change all filter related "or" expr from binary function to multi function

- pkg/common/morpc/backend.go
- pkg/common/system/system.go
issue #16438 
add system busy monitor
> add system busy monitor

- pkg/sql/plan/build_constraint_util.go
- pkg/sql/plan/stats.go
issue #16846 
fix stats bug for fuzzy filter
> fix stats bug for fuzzy filter

- pkg/vm/engine/disttae/stats.go
issue #17039
add timer to check if the first logtail of table has been received,
to return from the wait function.
> [bug] stats: fix the leak of goroutine

- pkg/sql/colexec/restrict/restrict.go
- pkg/sql/colexec/restrict/types.go
- pkg/sql/compile/scope.go
- pkg/sql/plan/function/list_builtIn.go
- pkg/sql/plan/rule/constant_fold.go
- pkg/sql/plan/utils.go
- test/distributed/cases/optimizer/index.result
- test/distributed/cases/optimizer/index.test
issue https://github.com/matrixorigin/MO-Cloud/issues/3570
Revert 17050
> Revert "fix bug: can not constant fold some expr (#16979) (#17050)"

- pkg/fileservice/aws_sdk_v2.go
- pkg/fileservice/event_logger.go
- pkg/fileservice/s3_fs.go
issue #16661 
more logs for slow I/O
> fileservice: more slow logs

- .github/mergify.yml
- CODEOWNERS
issue #
add a global code owner
___
Tests, Configuration changes
___
- Updated Mergify rules to remove specific reviewer `sukki37` from approval conditions and automatic reviewer requests.
- Added `fengttt` as a global code owner in the CODEOWNERS file.
___
<tr>
<td>
<details>
<summary><strong>mergify.yml</strong><dd><code>Update Mergify rules to remove specific reviewer requirements.</code></dd></summary>
<hr>
<li>Removed specific reviewer <code>sukki37</code> from approval conditions.<br> <li> Removed automatic reviewer request for <code>sukki37</code>.<br>
</details>
</td>
<td><a …
> add global codeowner for pull request review

- .github/mergify.yml
- CODEOWNERS
issue #
___
Enhancement, Configuration changes
___
- Removed configuration for `release-1.1` queue rules and pull request rules in `.github/mergify.yml`.
- Updated `approved-reviews-by` conditions for `main` and `1.2-dev` branches in `.github/mergify.yml`.
- Added automatic reviewer request rules for `main` and `1.2-dev` branches in `.github/mergify.yml`.
- Removed global code owner `@fengttt` from `CODEOWNERS` file.
___
<tr>
<td>
<details>
<summary><strong>mergify.yml</strong><dd><code>Update Mergify configuration for queue rules and reviewers</code></dd></summary>
<hr>
<li>Removed configuration for <code>release-1.1</code> …
> CI: modify mergify config and remove global codeowner

- pkg/frontend/authenticate.go
- pkg/frontend/compiler_context.go
- pkg/util/metric/v2/dashboard/grafana_dashboard_frontend.go
- pkg/util/metric/v2/frontend.go
- pkg/util/metric/v2/metrics.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/3127
https://github.com/matrixorigin/MO-Cloud/issues/3478
1,在resolve的各个环节加监控
2,在create account的各个环节加监控
> add metric

- pkg/util/status/logtail_client.go
- pkg/vm/engine/disttae/logtail_consumer.go
- pkg/vm/engine/disttae/logtail_consumer_test.go
- [x ] BUG
issue #16948 #16938  #16577  #16421  #15844  #14890 #14880  #14405  #14160  #16701 #15843 
1. Pls ref to https://github.com/matrixorigin/matrixone/pull/17005
> Cherry pick fix[ ww/dup/datalost] bugs when unsubscribe table

- .github/mergify.yml
issue #
___
Tests, Other
___
- Removed the condition in `.github/mergify.yml` that required approval from `fengttt` for merging into the `main` branch.
- Deleted the rule in `.github/mergify.yml` that auto-requested reviews from `fengttt` for PRs targeting the `main` branch.
___
<tr>
<td>
<details>
<summary><strong>mergify.yml</strong><dd><code>Remove Mergify auto-request reviewer and approval condition for main </code><br><code>branch</code></dd></summary>
<hr>
<li>Removed the condition to require approval from <code>fengttt</code> for merging <br>into <code>main</code>.<br> <li> Deleted the rule to auto-request reviews …
> CI: remove mergify requested reviewer for main

- pkg/sql/plan/build_constraint_util.go
- pkg/sql/plan/build_dml_util.go
- pkg/sql/plan/explain/explain_query.go
issue #https://github.com/matrixorigin/matrixone/issues/16375
继续优化insert into select的内存开销
> continue opt issue-16375

- pkg/fileservice/error.go
- pkg/fileservice/retry.go
issue #17168 
more retryable errors
> fileservice: make TLS handshake timeout retryable error

- pkg/vm/engine/tae/index/tree.go
issue #16942 
Remove the above memory overhead.
___
Enhancement
___
- Removed the `IndexMVCCChain` struct and its methods to reduce memory overhead.
- Introduced a new `Positions` type to replace `IndexMVCCChain`.
- Updated `simpleARTMap` methods (`Insert`, `BatchInsert`, `Search`, `String`) to use the new `Positions` type.
___
<tr>
<td>
<details>
<summary><strong>tree.go</strong><dd><code>Refactor memory table to reduce overhead by using Positions type.</code></dd></summary>
<hr>
pkg/vm/engine/tae/index/tree.go
<li>Removed <code>IndexMVCCChain</code> struct and associated methods.<br> <li> Introduced <code>Positions</code> type as a replacement.<br> …
> save some memory in memory table

- pkg/sql/colexec/receiver_operator.go
- pkg/sql/colexec/right/join.go
- pkg/sql/colexec/right/types.go
- pkg/sql/colexec/rightanti/join.go
- pkg/sql/colexec/rightanti/types.go
- pkg/sql/colexec/rightsemi/join.go
- pkg/sql/colexec/rightsemi/types.go
issue https://github.com/matrixorigin/MO-Cloud/issues/3338
Cherry-pick #17038 and #17107 to main
___
___
- Added a new function `ReceiveBitmapFromChannel` in `receiver_operator.go` to handle bitmap reception with context handling.
- Improved bitmap handling logic in `sendLast` function across multiple join implementations (right join, right anti join, right semi join).
- Simplified the `Free` function in `types.go` files to handle channels correctly and avoid potential deadlocks.
___
<tr>
<td>
<details>
<summary><strong>receiver_operator.go</strong><dd><code>Add `ReceiveBitmapFromChannel` function for bitmap …
> Cherry-pick #17038 and #17107 to main

- pkg/sql/plan/apply_indices.go
issue #17093 
cherry pick stats related fix to 1.2-dev
> cherry pick to 1.2-dev '[Bug]: random points qps in daily regression degrade from 20000+ to 7…'

- pkg/common/malloc/c_allocator.go
- pkg/common/malloc/checked_allocator.go
- pkg/common/malloc/closure_deallocator.go
- pkg/common/malloc/config.go
- pkg/common/malloc/default.go
- pkg/common/malloc/fixed_size_mmap_allocator.go
- pkg/common/malloc/fixed_size_sync_pool_allocator.go
- pkg/common/malloc/leaks_tracker.go
- pkg/common/malloc/leaks_tracking_allocator.go
- pkg/common/malloc/managed_allocator.go
- pkg/common/malloc/metrics_allocator.go
- pkg/common/malloc/metrics_allocator_test.go
- pkg/common/malloc/profile_allocator.go
- pkg/common/malloc/size_bounded_allocator.go
- pkg/common/malloc/stacktrace.go
- pkg/fileservice/cache.go
- pkg/fileservice/io_entry.go
- pkg/fileservice/malloc.go
- pkg/fileservice/mem_cache.go
- pkg/util/metric/v2/dashboard/grafana_dashboard_mem.go
- pkg/util/metric/v2/mem.go
- pkg/util/metric/v2/metrics.go
issue #17174 #17178
refine malloc package
> malloc: various refinements

- pkg/sql/colexec/filter/filter.go
- pkg/sql/compile/compile.go
- pkg/sql/plan/base_binder.go
- pkg/sql/plan/build_insert.go
- pkg/sql/plan/build_util.go
- pkg/sql/plan/opt_misc.go
- pkg/sql/plan/partition_list.go
- pkg/sql/plan/query_builder.go
- pkg/sql/plan/stats.go
- pkg/sql/plan/utils.go
- test/distributed/cases/optimizer/like.result
issue #17185 
fix a bug that cause wrong stats in tpch
> fix a bug that cause wrong stats in tpch

- pkg/objectio/cache.go
Reverts matrixorigin/matrixone#17187
> Revert "change metadata cache size and policy"

- pkg/common/morpc/backend.go
- pkg/frontend/computation_wrapper.go
- pkg/sql/colexec/types.go
- pkg/sql/compile/compile.go
- pkg/sql/compile/compileService.go
- pkg/sql/compile/compileService_test.go
- pkg/sql/compile/compile_test.go
- pkg/sql/compile/remoterunServer.go
- pkg/sql/compile/scope_test.go
- pkg/sql/compile/sql_executor.go
- pkg/sql/compile/types.go
- pkg/txn/client/client.go
- pkg/txn/client/client_test.go
- pkg/txn/service/service.go
https://github.com/matrixorigin/MO-Cloud/issues/3512
1. support CompileService to manage the runningCompile.
2. modify the function `AbortAllRunningTxn`.
> 1.2 support compile service

- pkg/fileservice/cache.go
- pkg/fileservice/io_merger.go
- pkg/fileservice/local_fs.go
- pkg/fileservice/s3_fs.go
issue #17231 
fileservice: optimize io merging
fileservice: return early if all done in Read
> fileservice: optimize io merging

- pkg/objectio/cache.go
- pkg/objectio/funcs.go
issue https://github.com/matrixorigin/MO-Cloud/issues/3656
Add CoreDump when CachedData is nil
> Add CoreDump when CachedData is nil

- pkg/fileservice/io_entry.go
- pkg/fileservice/local_etl_fs.go
- pkg/fileservice/local_fs.go
- pkg/fileservice/memorycache/data.go
- pkg/fileservice/memorycache/data_test.go
issue # https://github.com/matrixorigin/MO-Cloud/issues/3656
do not allow nil Data
> memorycache: do not allow nil Data

- pkg/lockservice/lock_table_allocator.go
- pkg/lockservice/lock_table_allocator_test.go
- pkg/lockservice/log.go
- pkg/lockservice/service_remote_test.go
- pkg/lockservice/service_test.go
- pkg/lockservice/types.go
- pkg/txn/client/operator_test.go
issue #17225 
fix unlock fatal when tn restart
> fix unlock fatal when tn restart

- pkg/sql/compile/compile.go
- pkg/sql/plan/apply_indices.go
- pkg/sql/plan/base_binder.go
- pkg/sql/plan/build_insert.go
- pkg/sql/plan/build_util.go
- pkg/sql/plan/opt_misc.go
- pkg/sql/plan/partition_list.go
- pkg/sql/plan/query_builder.go
- pkg/sql/plan/stats.go
- pkg/sql/plan/utils.go
- test/distributed/cases/optimizer/like.result
issue #17227 
cherry-pick stats related fix into 1.2-dev
> cherry-pick stats related fix into 1.2-dev

- pkg/sql/compile/compile.go
shuffle join的结果scope需要先merge，避免导致broadcast join出现重复build的情况。 调整了compile时计算并发度的算法，与运行时保持一致
Approved by: @m-schen
Conflicts:
pkg/sql/compile/compile.go
issue # https://github.com/matrixorigin/MO-Cloud/issues/3194
cp 17265 into 1.2-dev
> cp 17265 into 1.2-dev

- test/distributed/cases/function/func_make_date.sql
issue #https://github.com/matrixorigin/MO-Cloud/issues/3626
fix bvt test
> fix bvt test

- test/distributed/cases/function/func_make_date.sql
issue #https://github.com/matrixorigin/MO-Cloud/issues/3626
fix bvt test
> fix bvt test(#1.2-dev)

- pkg/sql/compile/compile.go
- pkg/sql/plan/shuffle.go
issue #17293 
fix a bug that cause wrong parallelism for tpch
> fix a bug that cause wrong parallelism for tpch

- pkg/sql/compile/compile.go
- pkg/sql/plan/shuffle.go
Conflicts:
pkg/sql/compile/compile.go
issue #17293 
cherry-pick to 1.2-dev 'fix a bug that cause wrong parallelism for tpch'
> cherry-pick to 1.2-dev 'fix a bug that cause wrong parallelism for tpch'

- pkg/vm/engine/tae/txn/txnimpl/table.go
- [x ] BUG
issue #16938 
1. Fix dup/ww/data corruption bug caused by DN transfering deletes.
> Cherry-pick-fix-bugs[Dup/WW/Data-corruption]

- pkg/sql/compile/compile.go
- pkg/sql/plan/shuffle.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/3194
cherry-pick to 1.2-dev 'fix a bug that cause tpch performance regression '
> cherry-pick to 1.2-dev 'fix a bug that cause tpch performance regression '

- pkg/lockservice/service_test.go
- pkg/sql/colexec/lockop/lock_op.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/3681 #https://github.com/matrixorigin/MO-Cloud/issues/3654
retry lock when cn down
> retry lock when cn down

- pkg/frontend/authenticate_test.go
- pkg/frontend/mysql_cmd_executor.go
- pkg/frontend/query_result_test.go
- pkg/frontend/variables.go
- test/distributed/cases/system_variable/lower_case_table_names.result
- test/distributed/cases/system_variable/lower_case_table_names.sql
issue [#3655](https://github.com/matrixorigin/MO-Cloud/issues/3655)
fix set global var do not work cross cns
> [Cherry-pick] Fix set global var do not work cross cns

- pkg/fileservice/aws_sdk_v2.go
- pkg/fileservice/event_logger.go
- pkg/fileservice/event_logger_test.go
- pkg/fileservice/io_entry.go
- pkg/fileservice/s3_fs.go
- pkg/fileservice/string.go
issue #17213 
optimize performance of LogEvent
> fileservice: intern strings in slow event logger

- pkg/vm/engine/tae/db/dbutils/mem.go
- pkg/vm/engine/tae/tables/updates/mvcc.go
issue #17314
fix data race when get deltaLoc.
remove some log.
> fix data race when get deltaloc on 1.2-dev

- pkg/vm/engine/disttae/stats.go
issue #17001
reduce the parallel goroutines to update stats
> [enhancement] stats: reduce the parallel goroutines to update stats

- pkg/vm/engine/disttae/stats.go
issue #17365
When force to trigger the stats update, which will hang when the channel
is full, we should unlock first because another goroutine which fetches
items from the channel holds the lock.
> [bug] stats: fix hang issue

- pkg/lockservice/lock_table_keeper.go
- pkg/lockservice/service_test.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/3693
fix cannot restart lockservice
> fix cannot restart lockservice

- pkg/bootstrap/upgrade.go
- pkg/bootstrap/versions/v1_2_2/log.go
- pkg/bootstrap/versions/v1_2_2/upgrade.go
issue https://github.com/matrixorigin/MO-Cloud/issues/3711
Expansion 1.2.2 upgrade package, used to record version upgrade trajectory
> Expansion 1.2.2 Upgrade Package

- pkg/lockservice/lock_table_allocator.go
- pkg/lockservice/log.go
issue #16982 
add clean commit state log
> add clean commit state log

- pkg/sql/plan/build.go
- pkg/sql/plan/opt_misc.go
- pkg/sql/plan/stats.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/3678
cp to 1.2-dev "don't calculate stats for limit 0 query"
> cp to 1.2-dev "don't calculate stats for limit 0 query"

- pkg/proxy/client_conn.go
- pkg/proxy/error.go
issue #17392 
remove error logs caused by hearteabt of LB.
> [enhancement] proxy: remove error logs caused by hearteabt of LB.

- pkg/cnservice/distributed_tae.go
- pkg/cnservice/types.go
- pkg/vm/engine/disttae/engine.go
- pkg/vm/engine/disttae/stats.go
issue https://github.com/matrixorigin/MO-Cloud/issues/3678
add factor to update worker number.
> [enhancement] stats: add factor to update worker number.

- pkg/vm/engine/disttae/stats.go
issue https://github.com/matrixorigin/MO-Cloud/issues/3678
do not update the same key at the same time.
> [enhancement] stats: do not update the same key at the same time.

- pkg/common/morpc/backend.go
- pkg/common/morpc/backend_test.go
issue #17419 
Fix stopped state changed to stopping, and cause do close more times
> fix change morpc backend state to 1.2

- pkg/util/metric/v2/dashboard/grafana_dashboard_fs.go
- pkg/util/metric/v2/metrics.go
issue #16552 
fix typo and register counter
> metric: fix typo and register fsWriteCounter

- pkg/fileservice/aws_sdk_v2.go
- pkg/fileservice/cache.go
- pkg/fileservice/event_logger.go
- pkg/fileservice/event_logger_test.go
- pkg/fileservice/http_client.go
- pkg/fileservice/io_entry.go
- pkg/fileservice/io_merger.go
- pkg/fileservice/local_fs.go
- pkg/fileservice/object_storage_arguments.go
- pkg/fileservice/object_storage_semaphore.go
- pkg/fileservice/s3_fs.go
- pkg/fileservice/string.go
issue #17213 #17231 #16661 #17329
cherry-pick some changes
> cherry-pick some fileservice changes from main branch

- pkg/vm/engine/tae/db/gc/checkpoint.go
- pkg/vm/engine/tae/db/test/db_test.go
- pkg/vm/engine/tae/logtail/snapshot.go
issue https://github.com/matrixorigin/matrixone/issues/17241 https://github.com/matrixorigin/matrixone/issues/17443
Fix TestSnapshotMeta data race&failed
> Fix TestSnapshotMeta data race&failed

- pkg/sql/compile/compile.go
https://github.com/matrixorigin/MO-Cloud/issues/3721
remove an info-level log that prints the complete SQL in certain situations.
> remove an info-level log.

- pkg/vm/engine/tae/db/gc/checkpoint.go
- pkg/vm/engine/tae/db/test/db_test.go
- pkg/vm/engine/tae/logtail/snapshot.go
issue https://github.com/matrixorigin/matrixone/issues/17241 https://github.com/matrixorigin/matrixone/issues/17443
Fix TestSnapshotMeta data race&failed for 1.2
> Fix TestSnapshotMeta data race&failed for 1.2

- pkg/sql/compile/compile.go
https://github.com/matrixorigin/MO-Cloud/issues/3721
remove an info-level log that prints the complete SQL in certain situations.
> [pick to main] remove an info-level log.

- pkg/vm/engine/tae/db/merge/mod.go
- pkg/vm/engine/tae/db/merge/policyBasic.go
- pkg/vm/engine/tae/db/scannerop.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/3718
Always sort object in ascending order during merge.
> sort objects in ascending order

- pkg/vm/engine/tae/db/merge/policyBasic.go
issue https://github.com/matrixorigin/MO-Cloud/issues/3691
check memory usage first when considering popping
> Fix merge mem contro 1.2

- pkg/frontend/mysql_cmd_executor.go
- pkg/frontend/session.go
- pkg/sql/colexec/connector/connector.go
- pkg/sql/colexec/dispatch/dispatch.go
- pkg/sql/compile/compile.go
- pkg/sql/compile/compileService.go
- pkg/sql/compile/reuse.go
- pkg/sql/compile/scope.go
This reverts commit cb8ee611d6e14c515dc67319714304bbdd45fa05.
issue #14940 
This reverts commit cb8ee611d6e14c515dc67319714304bbdd45fa05.
> Revert "Refactor prepare to reuse Compile (#17428)"

- pkg/container/vector/functionTools.go
- pkg/container/vector/tools.go
- pkg/container/vector/vector.go
- pkg/container/vector/vector_test.go
- pkg/sql/compile/remoterunServer.go
- pkg/vm/process/process_codec.go
issue #17484 
delete some Set methods
> vector: add NewVecWithData; remove Vector.SetData,SetArea; un-expose SetColFromData
