pkg/frontend/compiler_context.go
pkg/frontend/mysql_cmd_executor_test.go
pkg/frontend/routine_test.go
pkg/frontend/session_test.go
pkg/frontend/test/engine_mock.go
pkg/frontend/test/types_mock.go
pkg/vm/engine/disttae/txn_table.go
pkg/vm/engine/memoryengine/table.go
pkg/vm/engine/types.go

issue #https://github.com/matrixorigin/matrixone/issues/14614
the copy or not of table def should decided by users, this PR provides an interface for copy-on-write.

sync to 1.1: an interface for copy-on-write of table def

---

pkg/vm/engine/tae/common/print.go
pkg/vm/engine/tae/tables/jobs/flushTableTail.go
pkg/vm/engine/tae/tables/jobs/flushblk.go
pkg/vm/engine/tae/tables/jobs/flushdeletes.go
pkg/vm/engine/tae/txn/txnimpl/table.go

issue #14576
- skip the async flush task if the root task encounters an error

check nil vector before flushing blk & print w-w detail in pessimistic mode

---

pkg/vm/engine/disttae/logtailreplay/partition_state.go

issue #12820
use a larger degree to reduce node allocations

logtailreplay: tune btree degree to lower allocations

---

pkg/container/vector/vector.go
pkg/sql/plan/rule/constant_fold.go
pkg/sql/plan/utils.go
test/distributed/cases/dml/select/select.result
test/distributed/cases/dml/select/select.test

fix bug: get incorrect result for "in" expr  in some case.
bug case:
```sql
drop table if exists t1;
create table t1(a int primary key, b int);
insert into t1 values (1,1),(2,2),(3,3);
select mo_ctl('dn', 'flush', 'select.t1');
select * from t1 where a in (3,3,3,2,1);
-- here, we should get 3 rows. but 5 rows now
```
Approved by: @badboynt1, @XuPeng-SH, @nnsgmsone, @heni02, @aunjgr
issue https://github.com/matrixorigin/MO-Cloud/issues/2533
cherry pick 14602 to 1.0

fix bug: get incorrect result for "in" expr  in some case (#14602)

---

pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
pkg/util/metric/v2/txn.go
pkg/vm/engine/tae/db/test/txn_test.go
pkg/vm/engine/tae/iface/txnif/consts.go
pkg/vm/engine/tae/iface/txnif/types.go
pkg/vm/engine/tae/logstore/driver/logservicedriver/appender.go
pkg/vm/engine/tae/txn/txnbase/impl.go
pkg/vm/engine/tae/txn/txnbase/store.go
pkg/vm/engine/tae/txn/txnbase/txn.go
pkg/vm/engine/tae/txn/txnbase/txnmgr.go
pkg/vm/engine/tae/txn/txnimpl/store.go

issue #https://github.com/matrixorigin/matrixone/issues/13987
adding detailed phased trace in the TN commit routine helps us catch the time killer when TN commits.

sync to 1.1: adding detailed phased trace in the TN commit routine helps us catch the time killer when TN commits.

---

pkg/vm/engine/tae/common/print.go
pkg/vm/engine/tae/tables/jobs/flushTableTail.go
pkg/vm/engine/tae/tables/jobs/flushblk.go
pkg/vm/engine/tae/tables/jobs/flushdeletes.go
pkg/vm/engine/tae/txn/txnimpl/table.go

issue #14576 
- skip the async flush task if the root task encounters an error

1.1: check nil vector before flushing blk & print w-w detail in pessimistic mode

---

pkg/vm/engine/tae/db/db.go
pkg/vm/engine/tae/db/task.go
pkg/vm/engine/tae/db/test/tables_test.go
pkg/vm/engine/tae/rpc/rpc_test.go
pkg/vm/engine/tae/txn/txnbase/txnmgr.go

issue #https://github.com/matrixorigin/matrixone/issues/14680
this PR replaced StartTxnWithLatestTS with StartTxn, some optimization, comes soon, depending on this.

sync to 1.1: clean all usage of the StartTxnWithLastestTs

---

pkg/vm/engine/tae/db/db.go
pkg/vm/engine/tae/db/task.go
pkg/vm/engine/tae/db/test/tables_test.go
pkg/vm/engine/tae/rpc/rpc_test.go
pkg/vm/engine/tae/txn/txnbase/txnmgr.go

issue #https://github.com/matrixorigin/matrixone/issues/14680
Revert "clean all usage of the StartTxnWithLastestTs"

Revert the replace `StartTxnWithLatestTS` with `StartTxn`

---

pkg/sql/colexec/fuzzyfilter/types.go

free a vector that missed before
Approved by: @m-schen, @fengttt
issue #14081
free a vector that missed before

Fix memory leak caused by fuzzyfilter

---

pkg/sql/plan/function/func_prefix.go

issue #https://github.com/matrixorigin/matrixone/issues/14778
see the issue for more details

sync to 1.1: fix the logic err in PrefixIn when vector unsorted

---

pkg/logservice/service_bootstrap.go

issue #12891 https://github.com/matrixorigin/MO-Cloud/issues/2625
there is no default fileservice instance, so we need to get a fileservice instance explicitly, otherwise, a "service not found" error will be raised.

[bug] BR: fix bug when restore data 

---

pkg/bootstrap/bootstrap.go
pkg/sql/plan/function/ctl/cmd_task.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/2628
modify mo_task primary key type to bigint.

modify mo_task primary key type to bigint in 1.1

---

pkg/sql/plan/build_insert.go

issue #14521
The previous code didn't take into account the out-of-order case such as 
```sql
create table t(a int, b varchar, c varchar, primary key(c, a));
explain insert into t (b, c, a) values("b", "c", 1);
```
now fix it

[fix] : fix #14521

---

pkg/vm/engine/disttae/engine.go

issue #14086 
free packer memory

disttae: call packer.FreeMem in pool reset function

---

pkg/util/trace/impl/motrace/report_statement.go

issue #https://github.com/matrixorigin/matrixone/issues/14926
changes
1. disable cu metric collection, avoid error `internal error: panic counter cannot decrease in value`

disable cu metric for Regression Test

---

pkg/cnservice/upgrader/new_add_table.go
pkg/util/metric/m_register.go
pkg/util/metric/m_sql.go
pkg/util/trace/impl/motrace/report_statement.go
test/distributed/cases/dml/show/database_statistics.result
test/distributed/cases/mo_cloud/mo_cloud.result
test/distributed/cases/tenant/tenant.result

issue # https://github.com/matrixorigin/matrixone/issues/12904
add a metric about statement_duration which could come up with query_latency

cherrypick to 1.1-dev: add statement latency metric

---

pkg/sql/plan/build_constraint_util.go
pkg/sql/plan/build_dml_util.go
pkg/sql/plan/build_insert.go
pkg/sql/plan/build_load.go

…ion if there will be no conflict.
issue: https://github.com/matrixorigin/MO-Cloud/issues/2567
For auto incr unique key, no deduplication detection is performed if there is definitely no conflict.

[Improvement] : For auto incr unique key, remove deduplication detection if there will be no conflict

---

pkg/cnservice/upgrader/new_add_column.go
pkg/cnservice/upgrader/upgrader.go

issue #https://github.com/matrixorigin/matrixone/issues/14846
Previously system tenant had access to all the column names of "mo_catalog.mo_indexes" via "INFORMATION_SCHEMA.COLUMNS".
```sql
mysql> SELECT COLUMN_NAME, COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA ="mo_catalog" AND TABLE_NAME ="mo_indexes" GROUP BY COLUMN_NAME;
+------------------+----------+
| column_name      | count(*) |
+------------------+----------+
| __mo_cpkey_col   |       35 |
| column_name      |       35 |
| comment          |       35 |
| database_id      |       35 |
| hidden           |       35 |
| id               |       35 |
| index_table_name |       35 |
| is_visible       |       35 |
| name             |       35 |
| options          |       35 |
| ordinal_position |       35 |
| …
```

[BugFix]: Upgrade Not getting applied to System Tenant

---

pkg/frontend/test/txn_mock.go
pkg/lockservice/lock_table_keeper.go
pkg/lockservice/log.go
pkg/sql/colexec/lockop/lock_op.go
pkg/txn/client/operator.go
pkg/txn/client/types.go
pkg/txn/storage/memorystorage/storage_txn_client.go
pkg/vm/engine/entire_engine_test.go

issue #[matrixorigin/MO-Cloud/issues/20](https://github.com/matrixorigin/MO-Cloud/issues/2602)
fix lock not found or changed in new txn

fix lock not found or changed in new txn

---

pkg/sql/util/util.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/2693
changes:
1. mark table `sysetem_metrics.sql_statement_cu` as `LoggingTable`.

bugfix 1.1: account access table in `system_metrics` db need redirect to sys

---

pkg/vm/engine/tae/catalog/block.go
pkg/vm/engine/tae/catalog/catalog.go
pkg/vm/engine/tae/catalog/database.go
pkg/vm/engine/tae/catalog/object.go
pkg/vm/engine/tae/catalog/table.go
pkg/vm/engine/tae/db/checkpoint/runner.go
pkg/vm/engine/tae/db/merge/executor.go
pkg/vm/engine/tae/db/merge/policyBasic.go
pkg/vm/engine/tae/db/merge/policyOverlap.go
pkg/vm/engine/tae/db/scannerop.go
pkg/vm/engine/tae/db/testutil/engine.go
pkg/vm/engine/tae/logtail/collector.go
pkg/vm/engine/tae/logtail/handle.go
pkg/vm/engine/tae/logtail/utils.go
pkg/vm/engine/tae/rpc/inspect.go
pkg/vm/engine/tae/rpc/rpc_test.go
pkg/vm/engine/tae/tables/blk.go
pkg/vm/engine/tae/tables/object.go
pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
pkg/vm/engine/tae/tables/txnentries/mergeobjects.go
pkg/vm/engine/tae/txn/txnimpl/database.go
pkg/vm/engine/tae/txn/txnimpl/relation.go
pkg/vm/engine/tae/txn/txnimpl/sysblock.go
pkg/vm/engine/tae/txn/txnimpl/table_space.go

issue #https://github.com/matrixorigin/matrixone/issues/14974
has concurrent read-write on `TableEntry.schema.Name`
Add an interface to let users choose to lock or not when using `TableEntry.schema.Name`.

adding sync interface for GetLatestSchema

---

pkg/frontend/routine_manager.go

issue #14939 
Fix: delete nil routine

[Cherry-pick] fix delete nil routine (#14951)

---

pkg/frontend/txn_test.go
pkg/frontend/util_test.go
pkg/sql/compile/compile.go
pkg/sql/compile/compile_test.go
pkg/txn/client/types.go
pkg/vm/engine/disttae/txn.go
pkg/vm/engine/disttae/txn_table.go
pkg/vm/engine/disttae/types.go

- [x ] BUG
issue #14895 #14880 #14562 #14405 #13541 #14548 #13872 
1. fix dup reported by CN and ww reported by DN.

cherry pick fix-dup-ww-3

---

pkg/sql/colexec/anti/join.go
pkg/sql/colexec/anti/types.go
pkg/sql/colexec/external/external.go
pkg/sql/colexec/external/types.go
pkg/sql/colexec/indexbuild/build.go
pkg/sql/colexec/join/join.go
pkg/sql/colexec/join/types.go
pkg/sql/colexec/left/join.go
pkg/sql/colexec/left/types.go
pkg/sql/colexec/mark/join.go
pkg/sql/colexec/mark/types.go
pkg/sql/colexec/projection/projection.go
pkg/sql/colexec/projection/types.go
pkg/sql/colexec/right/join.go
pkg/sql/colexec/right/types.go
pkg/sql/colexec/rightanti/join.go
pkg/sql/colexec/rightanti/types.go
pkg/sql/colexec/rightsemi/join.go
pkg/sql/colexec/rightsemi/types.go
pkg/sql/colexec/semi/join.go
pkg/sql/colexec/semi/types.go
pkg/sql/colexec/single/join.go
pkg/sql/colexec/single/types.go
pkg/sql/colexec/table_scan/table_scan.go
pkg/sql/colexec/table_scan/types.go

issue https://github.com/matrixorigin/MO-Cloud/issues/2351
现在table_scan算子在计算内存占用的时候，是使用累计的方式。
修改为取单次batch的最高值的方式计算内存占用

use max memory size of Operator to compute CU

---

pkg/config/configuration.go
pkg/frontend/cmd_executor.go
pkg/frontend/mysql_cmd_executor.go
pkg/frontend/status_stmt.go
pkg/util/trace/impl/motrace/config.go
pkg/util/trace/impl/motrace/report_statement.go
pkg/util/trace/impl/motrace/trace.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/2734, https://github.com/matrixorigin/MO-Cloud/issues/2726
changes:
1. move StatmentCounter above StatementDurationCounter, corrent the acount & query_type `metric/sql_statement_total` count
2. disable tcp packet estimate in network traffic stats.
- New config item
```diff
[observability]
+ tcpPacket = false   // false: disable tcp packet estimate in network traffic stats
```

fix metric, stats in 1.1

---

pkg/sql/plan/build_constraint_util.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/2765
dml的plan都是手写的，没有过优化器计算, fuzzy filter复用runtime filter的逻辑有误。最简单的改发是让scan限定在单并发

[fix] : prevent table scan for fuzzy filter from running on multiple CNs to fix moc2765

---

pkg/vm/engine/disttae/txn.go
pkg/vm/engine/disttae/txn_table.go

- [x ] BUG
issue #14552 
1.fix bug for halloween

Fix halloween

---

pkg/fileservice/aliyun_sdk.go
pkg/fileservice/aws_sdk_v2.go
pkg/fileservice/minio_sdk.go
pkg/fileservice/object_storage_arguments.go

issue #15154 
refine no credentials rules.

fileservice: add ObjectStorageArguments.shouldLoadDefaultCredentials

---

pkg/common/mpool/mpool.go
pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
pkg/util/metric/v2/txn.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/2578 https://github.com/matrixorigin/matrixone/issues/14843
ZYWL-insert benchmarking on 129 shows that nearly 30%/100% CPU usage is spent on metrics within `MPool.Free`

remove metrics in `mpool.Free` and `mpool.Alloc`

---

pkg/vm/engine/tae/db/scheduler.go
pkg/vm/engine/tae/db/test/db_test.go
pkg/vm/engine/tae/db/test/replay_test.go
pkg/vm/engine/tae/db/test/scheduler_test.go
pkg/vm/engine/tae/db/testutil/engine.go
pkg/vm/engine/tae/rpc/base_test.go
pkg/vm/engine/tae/tasks/scheduler.go
pkg/vm/engine/tae/txn/txnbase/txnmgr.go

issue #14579 
not to lock when create and delete a txn during commit

not to lock when create and delete a txn during commit

---

pkg/sql/plan/function/func_prefix.go

issue https://github.com/matrixorigin/MO-Cloud/issues/2811
vectors allocated from mempool are not zero-initialized and MUST be overwritten in function implementation.

fix wrong result caused by prefix_eq (cherry-pick to 1.1-dev)

---

pkg/cnservice/server_query.go
pkg/queryservice/session_manager.go

issue #15206 
[Fix] concurrent problem of sessionMgr

[Fix] concurrent problem of sessionMgr

---

pkg/sql/plan/explain/explain_node.go
pkg/sql/plan/runtime_filter.go

issue #15196
if joined columns are the prefix of primary key, we should set MatchPrefix
flag on RuntimeFilterSpec

[fix] let runtime filter use prefix match if necessary

---

pkg/sql/plan/build_alter_add_column.go
pkg/sql/plan/build_alter_table.go
test/distributed/cases/ddl/alter_table_change_column.result
test/distributed/cases/ddl/alter_table_modify_column.result
test/distributed/cases/dtype/enum.result

fix alter table add enum col
Approved by: @ouyuanning, @heni02
issue #15176 #15177
fix alter table add enum col

fix alter table add enum col (#1.1-dev)

---

pkg/frontend/session.go
pkg/util/export/etl/db/db_holder.go
pkg/util/trace/impl/motrace/config.go
pkg/util/trace/impl/motrace/trace.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/2848
changes:
1. set the `session.requestLabel` while do `AuthenticateUser`.
- Then cn can use it as LabelSelector in `Compile::getCNList` to select the dedicated CN set
> TIPs: directly access CN without proxy, those labels setting within username have been ignored.

MOLogger conn run with cn-labelSelector while do Compile

---

pkg/tnservice/factory.go

This reverts commit 6920986641050527e79339993501e57a3e4b813a.
issue #https://github.com/matrixorigin/matrixone/issues/15288
see the issue for more detail

Revert "unlimited the RPC msg body size (#15250)"

---

pkg/container/bytejson/bytejson.go

issue #14909 
fix json_extract

fix json_extract(#1.1-dev)

---

pkg/lockservice/service_remote.go
pkg/lockservice/service_test.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/2925
fix sync lock table between cn and dn

fix sync lock table between cn and dn

---

test/distributed/cases/dml/insert/insert_ignore.result
test/distributed/cases/dml/insert/insert_ignore.sql

issue #11224 
add insert ignore cases

Insert ignore

---

pkg/frontend/mysql_cmd_executor.go
pkg/frontend/query_result.go

issue [#2917](https://github.com/matrixorigin/MO-Cloud/issues/2917)
table name overwritten when show table status

[Fix] table name overwritten when show table status

---

pkg/vm/engine/tae/blockio/write_index.go

issue #15288 #14151
The hash function has been replaced and the assembly hash function is no longer used.

Fix segment falut bug for hyperloglog

---

pkg/sql/plan/stats.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/2946
1.1版本的stats计算不够准确，导致经常有该下推block filter的时候没有下推。
对于所有这类问题，在1.1里总是下推。从1.2版本开始计算更加准确，应该可以彻底解决问题

always try to push block filter for 1.1

---

pkg/frontend/authenticate.go
pkg/frontend/authenticate_test.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/2932
non-sys tenant should not support cluster level backup

non-sys tenant should not support cluster level backup

---

pkg/cnservice/upgrader/upgrader.go

issue #15386
Adjust system table `mo_indexes` Upgrade Order

Adjust mo_indexes Upgrade Order

---

pkg/cnservice/upgrader/new_add_table.go
pkg/cnservice/upgrader/upgrader.go
pkg/cnservice/upgrader/upgrader_util.go
pkg/frontend/internal_executor.go
pkg/stream/connector/connector_test.go
pkg/util/internalExecutor/internal_executor.go
pkg/util/metric/mometric/metric_collector_test.go
pkg/util/sysview/sysview.go
pkg/util/trace/impl/motrace/example/main.go
pkg/util/trace/impl/motrace/schema_test.go

issue #15423
处理processlist系统视图升级后定义错误问题

Handle system view Processlist Not Available issue

---

pkg/sql/plan/build_dml_util.go

change left join to right join and push down runtime filter
Approved by: @ouyuanning, @aunjgr
issue # https://github.com/matrixorigin/MO-Cloud/issues/2939
cherry pick "optimize plan for update with secondary index column (#14856)" to 1.1

cherry pick "optimize plan for update with secondary index column (#14856)" to 1.1

---

test/distributed/cases/function/func_purge_log.result
test/distributed/cases/function/func_purge_log.sql
test/distributed/cases/table/system_table_cases.sql

issue #15455
changes:
1. get the newest `collecttime` as target time to check result.

fix bvt/purge_log 

---

pkg/sql/plan/function/list_builtIn.go
test/distributed/cases/expression/temporal_interval.result
test/distributed/cases/expression/temporal_interval.sql

fix date_add with param input
Approved by: @heni02, @m-schen
issue #15081 
fix date_add with param input

fix date_add with param input (#1.1-dev)

---

test/distributed/cases/function/func_purge_log.result
test/distributed/cases/function/func_purge_log.sql
test/distributed/cases/table/system_table_cases.sql

changes:
1. get the newest `collecttime` as target time to check result.
Approved by: @heni02
issue #15455
fix bvt/purge_log

fix bvt/purge_log  (#1.1-dev)

---

pkg/catalog/types.go
pkg/vm/engine/tae/catalog/database.go
pkg/vm/engine/tae/db/test/storage_usage_test.go

issue https://github.com/matrixorigin/MO-Cloud/issues/2995
fix hang issue and reserve some table IDs.

[bug] tae: fix hang issue and reserve some table IDs.

---

pkg/config/configuration.go
pkg/frontend/session.go

Reverts matrixorigin/matrixone#15330

Revert "cherry-pick sys variables"

---

pkg/sql/plan/apply_indices.go
pkg/sql/plan/apply_indices_vector.go
pkg/sql/plan/utils.go

issue #15196
Current filter implementation in Reader uses ColRef.Name to locate the physical column.

[fix] add complete ColRef-to-Name mapping for index tables

---

pkg/common/mpool/mpool.go
pkg/sql/compile/scope.go
pkg/sql/compile/scopeRemoteRun.go
pkg/sql/compile/scopeRemoteRunTypes.go

issue #15543 
fix the order of mpool destroy.
fix a bug that will cause pipelines still running for a moment after query return.

[cherry-pick-15603] fix issue #15543

---

test/distributed/cases/function/func_purge_log.result
test/distributed/cases/function/func_purge_log.sql

issue #https://github.com/matrixorigin/matrixone/issues/15455
changes:
1. correct target time to check result, by using `date_sub`.

fix bvt with correct datetime

---

test/distributed/cases/function/func_purge_log.result
test/distributed/cases/function/func_purge_log.sql

issue #https://github.com/matrixorigin/matrixone/issues/15455
ref: https://github.com/matrixorigin/matrixone/pull/15593
changes:
1. correct target time to check result, by using date_sub.

fix bvt with correct datetime in 1.1

---

pkg/sql/plan/shuffle.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/3038
由于自增列在某些情况下会跳过很多值，导致分布不均匀。
1.1里没有对不均匀数据的处理逻辑，因此回导致负载在多cn上分布不均匀。1.2里已经解决了这个问题。
现在改成在1.1里，对自增列默认走hash shuffle，避免负载不均匀的问题

fix a bug that cause workload unbalance in 1.1

---

pkg/cnservice/types.go
pkg/config/configuration.go
pkg/lockservice/cfg.go
pkg/sql/plan/build_constraint_util.go
pkg/sql/plan/build_delete.go
pkg/sql/plan/build_dml_util.go
pkg/sql/plan/build_insert.go
pkg/sql/plan/build_update.go
pkg/sql/plan/build_util.go
pkg/sql/plan/query_builder.go

sql like `insert into A select * from B`, will try to lock the value in `B`. When the number of these locks is too much, it will lead to bugs reflected in the issue. In the context of range locks being temporarily unavailable, use table lock to replace point lock
Approved by: @ouyuanning, @daviszhen, @zhangxu19830126
issue https://github.com/matrixorigin/MO-Cloud/issues/3039 https://github.com/matrixorigin/MO-Cloud/issues/3006
replace point locks with table lock in some cases

[cherry-pick] :  fix issue moc3006 and moc3039 (#15578)

---

pkg/sql/colexec/lockop/fetch.go

issue https://github.com/matrixorigin/MO-Cloud/issues/3067
let lock op can handle varbinary

[fix] : let lock op can handle varbinary

---

pkg/container/types/rowid.go
pkg/vm/engine/tae/rpc/inspect.go

issue #15696
1. prettify output of short block id, making merge and flush easier to trace.
2. provide `objprune` cmd to dn inspect command group to prune objects
example:
```sh
mysql> select mo_ctl('dn', 'inspect', 'objprune -t tpch_1g.orders -d 1h')\G
*************************** 1. row ***************************
mo_ctl(dn, inspect, objprune -t tpch_1g.orders -d 1h): 
msg: parse err: invalid input: pruning objects within 24h is not supported
1 row in set (0.00 sec)
mysql> select mo_ctl('dn', 'inspect', 'objprune -t tpch_1g.orders -d 25h')\G
*************************** 1. row ***************************
mo_ctl(dn, inspect, objprune -t tpch_1g.orders -d 1h): 
msg: success. arg prune: table 282730-orders, 1h0m0s ago, cacheLen 1
total: 12, stale: 12, selected: 11, minR: 124741, maxR: 125871, …
```

add object prune command

---

pkg/catalog/types.go
pkg/util/export/table/table.go
pkg/util/trace/impl/motrace/schema.go
pkg/vm/engine/disttae/merge.go
pkg/vm/engine/disttae/txn_table.go
pkg/vm/engine/tae/db/checkpoint/runner.go
pkg/vm/engine/tae/db/open.go
pkg/vm/engine/tae/mergesort/merger.go
pkg/vm/engine/tae/mergesort/task.go
pkg/vm/engine/tae/rpc/handle.go
pkg/vm/engine/tae/tables/jobs/flushTableTail.go
pkg/vm/engine/tae/tables/jobs/mergeobjects.go
pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
pkg/vm/engine/tae/tables/txnentries/mergeobjects.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/3069
- fix transfer panic
- table comment `[mo_no_del_hint]` will skip transfer, which saves memory usage.
- mark `statement_info` & `rawlog` as `[mo_no_del_hint]`

fix panic in cn merge & support avoiding transfer by changing table comment

---

pkg/frontend/migrate.go
pkg/frontend/migrate_test.go
pkg/frontend/routine.go
pkg/proxy/tunnel.go

issue #15761
create migration controller to control the migration and session:
1. wait migration finished before close the routine.
2. check routine if closed before do the migration.

[bug] migrate: if the session is closed, skip migration

---

pkg/util/export/etl/db/db_holder.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/3166
changes:
1. GetSQLWriterDBAddressFunc return nil if SetSQLWriterDBAddressFunc not set.

bugfix: GetSQLWriterDBAddressFunc if not set, return nil

---

pkg/container/vector/functionTool_test.go
pkg/container/vector/functionTools.go
pkg/sql/colexec/aggexec/aggResult.go
pkg/sql/colexec/external/external.go

issue #15669 
聚合函数，表达式计算过程中对于vector.PreExtend方法使用有误，导致额外分配了多余的内存。

fix wrong usage of vector.PreExtend

---

pkg/vm/engine/disttae/logtail_consumer.go
pkg/vm/engine/disttae/logtailreplay/partition.go

issue # https://github.com/matrixorigin/MO-Cloud/issues/3114
GetTableById is too slow, cache its results.

disttae: cache result of GetTableById in PartitionState

---

pkg/vm/engine/tae/blockio/pipeline.go
pkg/vm/engine/tae/db/open.go
pkg/vm/engine/tae/options/options.go
pkg/vm/engine/tae/options/types.go
pkg/vm/engine/tae/rpc/base_test.go
pkg/vm/engine/tae/rpc/handle.go
pkg/vm/engine/tae/txn/txnbase/txnmgr.go

issue #15909
the output of config string will be like:
```
{"level":"INFO","time":"2024/05/08 17:59:37.438673 +0800","caller":"db/open.go:93","msg":"open-tae","operation":"Config","toml":"MaxMessageSize = 9223372036854775807\nTransferTableTTL = \"1m30s\"\nIncrementalDedup = true\nIsStandalone = true\nLogStoreT = \"logservice\"\n\n[storage-cfg]\n  block-max-rows = 8192\n  object-max-blocks = 256\n\n[checkpoint-cfg]\n  flush-inerterval = \"1m0s\"\n  checkpoint-min-count = 100\n  scan-interval = \"5s\"\n  checkpoint-incremental-interval = \"1m0s\"\n  checkpoint-global-interval = 40\n  overall-flush-mem-control = 1073741824\n  ForceUpdateGlobalInterval = false\n  GlobalVersionInterval = \"1h0m0s\"\n  GCCheckpointInterval = \"1m0s\"\n  DisableGCCheckpoint = false\n  ReservedWALEntryCount = …
```

Print tn config when opening and replace numCPU with procs

---

test/distributed/cases/log/query_version.result
test/distributed/cases/log/query_version.sql
test/distributed/cases/result_count/result_count.result
test/distributed/cases/result_count/result_count.sql
test/distributed/cases/sql_source_type/sql_source_type.result
test/distributed/cases/sql_source_type/sql_source_type.sql
test/distributed/cases/zz_statement_query_type/query_version.result
test/distributed/cases/zz_statement_query_type/query_version.sql
test/distributed/cases/zz_statement_query_type/sql_source_type.result
test/distributed/cases/zz_statement_query_type/sql_source_type.sql

issue #14836
ref #15914
changes:
1. move op `check statement_info result` to the end of bvt.

fix Bvt case in issue 14836 in 1.2

---

pkg/config/configuration.go
pkg/frontend/mysql_cmd_executor.go
pkg/frontend/test/types_mock.go
pkg/util/errutil/context.go
pkg/util/export/batch_processor.go
pkg/util/export/batch_processor_test.go
pkg/util/trace/impl/motrace/buffer_pipe_test.go
pkg/util/trace/impl/motrace/config.go
pkg/util/trace/impl/motrace/report_statement.go
pkg/util/trace/impl/motrace/trace.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/3225
ref: #15955
changes:
1. add new config `observability:disableError` default: false. 
2. bugfix: if NoReportFromContext(ctx), ignore error log output and collection.

Support mo_logger disable ErrorCollection in 1.2

---

pkg/sql/plan/utils.go

issue #16009
change type of prefix_in's second argument from T_tuple to T_varchar

fix argument type of prefix_in

---

pkg/taskservice/mysql_task_storage.go
pkg/taskservice/task_service.go

issue #16010
Add error log in taskservice when task service cannot get db on 1.2-dev.

add error log in taskservice

---

pkg/common/malloc/flush.go
pkg/common/malloc/handle.go
pkg/common/malloc/malloc.go

issue #15479
malloc: refine cache size calculation
malloc: remove AllocTyped
malloc: remove eviction
malloc: add shard alloc and free statistics
malloc: flush cached objects when idle

malloc: optimizations

---

pkg/frontend/computation_wrapper.go
pkg/frontend/mysql_cmd_executor.go

update
issue #https://github.com/matrixorigin/matrixone/issues/15982
https://github.com/matrixorigin/matrixone/issues/15975
本地sysbench 1000w 没复现出oom。
对2处潜在的stmt引用问题，做了修改。

fix parse oom

---

pkg/cnservice/cnclient/client.go
pkg/sql/compile/scope.go
pkg/sql/compile/scopeRemoteRunTypes.go

This reverts commit 2576dbd7fd963ca4ad0d6fac707f7e6371a44312.
issue #12652
Revert "[Bug]: pipeline client max connections is too large (#15713)"

Revert "[Bug]: pipeline client max connections is too large (#15713)"

---

pkg/vm/engine/disttae/db.go
pkg/vm/engine/disttae/engine.go
pkg/vm/engine/disttae/logtailreplay/partition.go
pkg/vm/engine/disttae/txn.go
pkg/vm/engine/disttae/txn_table.go
pkg/vm/engine/disttae/types.go
test/distributed/cases/snapshot/snapshot.sql
test/distributed/cases/snapshot/snapshot_read.sql
test/distributed/cases/snapshot/snapshot_read_1.sql
test/distributed/cases/snapshot/snapshot_read_2.sql
test/distributed/cases/snapshot/snapshot_read_3.sql
test/distributed/cases/snapshot/snapshot_restore_account_level.sql
test/distributed/cases/snapshot/snapshot_restore_database_level.sql
test/distributed/cases/snapshot/snapshot_restore_table_level.sql

issue #14784 
Fix bug for snapshot-read

Fix bug for snapshot-read(1.2-dev)

---

pkg/common/malloc/flush.go
pkg/common/malloc/handle.go
pkg/common/malloc/malloc.go

issue #15479 
malloc: refine cache size calculation
malloc: remove AllocTyped
malloc: remove eviction
malloc: add shard alloc and free statistics
malloc: flush cached objects when idle

malloc: optimizations (#16037)

---

pkg/fileservice/file_service_test.go
pkg/fileservice/local_etl_fs.go
pkg/fileservice/local_fs.go

issue #15751
ignore not found error when deleting files.

fileservice: ignore not found error in FileService.Delete

---

pkg/proxy/tunnel.go

issue #16042
when sequence id is rotated, there may be a wrong ok packet.
so do not allow transfer connection when sequence id is rotated.

[bug] proxy: when sequence id is rotated, there may be a wrong ok packet

---

pkg/lockservice/service_test.go
pkg/lockservice/txn.go

issue #16121 
skip unlock remote table for remote txn

skip unlock remote table for remote txn

---

pkg/lockservice/waiter_events.go

issue #15960 
fix deadlock by log wait tool long

fix deadlock by log wait tool long

---

pkg/frontend/snapshot.go
test/distributed/cases/snapshot/snapshot_restore_table_with_fk.result
test/distributed/cases/snapshot/snapshot_restore_table_with_fk.sql

issue #15653 #15971 
- build foreign key dependency graph from mo_foreign_keys table
- restore tables with foreign keys in order of dependency graph topological sorting

support restore table with foreign keys

---

pkg/lockservice/lock_table_local.go

issue #15921 #15815 #15757
fix lock waiter leak

fix lock waiter leak

---

pkg/sql/plan/base_binder.go
pkg/sql/plan/rule/constant_fold.go
pkg/sql/plan/utils.go

issue #15648
MO has no INTERVAL type. INTERVAL expressions are rewritten to date_add/date_sub. Standalone INTERVAL expressions should report error.

report error for standalone INTERVAL expression

---

cmd/mo-service/config.go
cmd/mo-service/main.go
pkg/common/malloc/allocator_bench_test.go
pkg/common/malloc/c_allocator_test.go
pkg/common/malloc/config.go
pkg/common/malloc/default_test.go
pkg/fileservice/bytes.go
pkg/fileservice/cache.go
pkg/fileservice/file_service.go
pkg/fileservice/io_entry.go
pkg/fileservice/io_vector.go
pkg/fileservice/local_etl_fs.go
pkg/fileservice/local_fs.go
pkg/fileservice/malloc.go
pkg/fileservice/mem_cache.go
pkg/fileservice/memorycache/cache.go
pkg/fileservice/memorycache/cache_test.go
pkg/fileservice/remote_cache.go
pkg/fileservice/remote_cache_test.go
pkg/fileservice/s3_fs.go
pkg/objectio/funcs.go

issue #15566
https://github.com/matrixorigin/MO-Cloud/issues/3253
https://github.com/matrixorigin/matrixone/issues/16291
fileservice: refactor bytesAllocator to reuse memory
objectio: remove ReleaseIOEntry
fileservice: add global malloc.Allocator
fileservice: allocate bytes in malloc allocator in LocalFS
fileservice: allocate from global allocator in IOEntry.ReadFromOSFile
malloc: add checked deallocator
malloc: add TestCheckedDeallocator
malloc: more logs
mo-service: fix malloc.SetDefaultConfig
fileservice: delay initialization of allocators
malloc: refine benchmarks

fileservice: reuse more memory

---

pkg/vm/engine/tae/db/merge/executor.go

issue #13881 
Fix data race in TestDedup2

fix TestDedup2, cherry-pick #16301

---

pkg/sql/colexec/deletion/types.go
pkg/sql/colexec/insert/types.go
pkg/sql/colexec/mergedelete/types.go
pkg/sql/compile/compile.go
pkg/sql/plan/build_dml_util.go

issue #16168
mergeDelete on hidden table should not update affect Rows

[fix] : mergeDelete on hidden table should not update affect Rows

---

pkg/fileservice/error.go

issue #15307 
retry on i/o timeout

fileservice: add i/o timeout as retryable error

---

cmd/mo-service/debug.go
pkg/cnservice/server.go

issue #https://github.com/matrixorigin/matrixone/issues/15982
定时profile存在的问题：
系统压力大时，profile保存不了。
可能的原因：
开启新routine取profile，再流式写入fileservice。在mo压力大时，新goroutine可能得不到调度，而导致profile取不出来。
在mo压力大时，也有可能取从go系统取profile本身取不出来。
改进定时profile
1.将原先proile流式写入改为同步写入。
不再开启新routine。
同时，profile要先保存到buf,再将buf写入fileservice。
2.对profile文件gzip压缩。profile名称带后缀gz。
解压方法
```
gzip -d xxx.gz
```
3. 测试结果。
在mo没什么压力的情况下。保存heap和goroutine，大概要50ms。
在mo跑sysbench 1000w 1000线程时。保存heap和goroutine，大概要2.5s。
heap文件压缩率为50%左右。goroutine文件压缩率更高。profile文件整体<= 500KB。
4. 用法
mo-service启动时增加参数。 -profile-interval "10s"
会在mo-data/etl/profile中每隔10s保存heap和goroutine。
例如：
```
./mo-service -profile-interval "10s" -debug-http 127.0.0.1:6060 -launch etc/launch/launch.toml > log.txt
```
启动成功后会有下面的效果
``` …
```

update save profile

---

pkg/vm/engine/tae/catalog/database.go
pkg/vm/engine/tae/db/test/db_test.go

issue #16282
Fix rollback create table.
When rollback, the last MVCC node has already removed. Remove related name list node with table.FullName.

fix rollback create table

---

pkg/frontend/mysql_cmd_executor.go
pkg/frontend/util.go

issue #https://github.com/matrixorigin/matrixone/issues/16393
在query trace status的日志中增加txnId

add txn id

---

test/distributed/cases/ddl/secondary_index_create.result
test/distributed/cases/ddl/secondary_index_create.sql

issue # https://github.com/matrixorigin/matrixone/issues/16427
Replace 
```sql
select name, type, column_name from mo_catalog.mo_indexes mi where mi.column_name ="name" or mi.column_name="__mo_alias_id";
```
To
```sql
select name, type, column_name from mo_catalog.mo_indexes mi where name="idx5";
```
to match the set of other queries in that BVT file.

[BugFix]: Fix failed BVT query in Secondary Index

---

pkg/vm/engine/tae/txn/txnimpl/table_space.go

issue #15848
Not set object created by CN as 1PC node

fix 15848, cherry-pick #16435

---

pkg/fileservice/fifocache/queue.go

issue https://github.com/matrixorigin/matrixone/issues/16443
When the cache evicts, although the values in cache's shards are deleted, 
there are still references in queue1, so fix.
___
Bug fix
___
- Fixed an issue in the FIFO cache eviction process where dequeued values were not reset, causing lingering references in the queue.
- Ensured that the dequeued value is set to its zero value after removal.
___
<tr>
<td>
<details>
<summary><strong>queue.go</strong><dd><code>Fix lingering references in FIFO cache eviction</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pkg/fileservice/fifocache/queue.go
<li>Reset the …

Fix fifocache evict

---

pkg/vm/engine/disttae/filter.go
pkg/vm/engine/disttae/txn_table.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/3321
use ctx instead of proc.ctx for rangesOnePart
___
Bug fix
___
- Added `ctx context.Context` parameter to several functions and methods in `filter.go` and `txn_table.go`.
- Replaced usage of `proc.Ctx` with the new `ctx` parameter to ensure proper context handling.
- Updated function and method calls to include the new `ctx` parameter.
___
<tr>
<td>
<details>
<summary><strong>filter.go</strong><dd><code>Add context parameter to filter functions and replace proc.Ctx usage</code></dd></summary>
<hr>
pkg/vm/engine/disttae/filter.go
<li>Added <code>ctx context.Context</code> parameter to …

[cherry-pick-16445] : use ctx instead of proc.ctx for rangesOnePart

---

pkg/vm/engine/disttae/txn.go
pkg/vm/engine/disttae/types.go

- [x ] BUG
issue #16278  #16220 #11815 
https://github.com/matrixorigin/MO-Cloud/issues/3235
1. fix r-w conflict : CN help TN to transfer deletes hosted in memory when txn on CN commits.
___
Bug fix
___
- Enhanced `transferDeletesLocked` function to handle commit logic, including updating and resetting snapshot timestamps.
- Added timing control to ensure snapshot updates occur only after a specified duration.
- Modified `Transaction` struct to include a `start` field for timing purposes.
- Updated `handleRCSnapshot` function to call `transferDeletesLocked` with the `commit` parameter.
___
<tr>
<td>
<details>
<summary><strong>txn.go</strong><dd><code>Enhance …

Fix-RW-Conflict

---

pkg/vm/engine/disttae/filter.go
pkg/vm/engine/disttae/txn_table.go

issue #https://github.com/matrixorigin/matrixone/issues/16463
making the dirty blocks collect lazily.
___
Enhancement
___
- Added `highSelectivityHint` parameter to various functions to optimize block filtering.
- Modified `CompileFilterExprs` and `CompileFilterExpr` to handle high selectivity hints for better performance.
- Updated `TryFastFilterBlocks` and `ExecuteBlockFilter` to collect dirty blocks lazily, improving efficiency.
- Adjusted logic in `rangesOnePart` to conditionally collect dirty blocks, ensuring they are only collected when necessary.
___
<tr>
<td>
<details>
<summary><strong>filter.go</strong><dd><code>Optimize block filtering with …

making collect dirty blocks lazily.

---

pkg/vm/engine/disttae/engine.go

issue #16273
add log to track 16273
___
Bug fix
___
- Added detailed error logging in the `Delete` function of `engine.go` to track issues related to database deletion failures.
- Included stack trace and transaction metadata in the logs when the database name contains "sysbench_db".
___
<tr>
<td>
<details>
<summary><strong>engine.go</strong><dd><code>Add detailed error logging in `Delete` function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pkg/vm/engine/disttae/engine.go
<li>Added import for <code>stack</code> package.<br> <li> Modified <code>Delete</code> function to include error logging.<br> <li> …

[cherry-pick-16424] : add log to track 16273

---

pkg/bootstrap/service_upgrade.go
pkg/bootstrap/upgrade.go
pkg/sql/parsers/tree/stmt.go

issue #16339
issue #https://github.com/matrixorigin/MO-Cloud/issues/3314
Support upgrading to skip Genesis version functionality
___
Enhancement
___
- Enhanced the upgrade framework initialization process to include logging for the founder version.
- Modified the upgrade process to use the founder version handle for creating framework dependencies.
- Added a new function `getFounderVersionHandle` to retrieve the original version handle.
- Added `StmtKind` method for `ShowAccountUpgrade` node in SQL parser.
___
<tr>
<td>
<details>
<summary><strong>service_upgrade.go</strong><dd><code>Enhance upgrade framework initialization and logging.</code>&nbsp; …

Support upgrading to skip Genesis version functionality-1.2-dev

---

pkg/vm/engine/disttae/filter.go

issue #https://github.com/matrixorigin/matrixone/issues/16463
skip collecting dirty blks only when `=`, or in and prefix_in a small set.
___
Enhancement
___
- Improved the performance of composite index selection by modifying the logic for setting `highSelectivityHint`.
- Changed the condition for `highSelectivityHint` to use logical OR instead of AND in some cases.
- Updated the handling of primary keys (`isPK`) and sorted keys to optimize performance.
- Adjusted the condition for `highSelectivityHint` to consider vector length for better efficiency.
___
<tr>
<td>
<details>
<summary><strong>filter.go</strong><dd><code>Improve filter expression …

fix collecting dirty block lazily.

---

pkg/sql/plan/function/func_mo.go
pkg/vm/engine/tae/rpc/handle_debug.go

issue #https://github.com/matrixorigin/matrixone/issues/16419
skip collecting `mo_tables, mo_databases, mo_columns` and cluster tables for non-sys when `mo_table_size, mo_table_rows and show accounts`.
___
___
- Added `specialTableFilterForNonSys` function to filter out `mo_tables`, `mo_databases`, `mo_columns`, and cluster tables for non-sys accounts.
- Removed unnecessary account switching logic for cluster tables in `MoTableRows` and `MoTableSize` functions.
- Replaced context `ctx` with `foolCtx` for database operations to ensure proper context handling.
- Simplified logic for handling partitioned tables in `MoTableRows`.
- Commented out the gathering of special table sizes in `HandleStorageUsage` to prevent incorrect size calculations.
- Disabled handling of …

skip collecting `mo_tables, mo_databases, mo_columns` and cluster tables for non-sys.

---

pkg/vm/engine/tae/db/dbutils/mem.go
pkg/vm/engine/tae/rpc/inspect.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/3199
add -f option to execute pruning without ack
___
Enhancement
___
- Added a `force` flag to the `objectPruneArg` struct and the corresponding command to allow forced pruning without acknowledgment.
- Adjusted the log chunk size from 200KB to 150KB in the `PrintMemStats` function for better memory stats logging.
- Refactored the `executePrune` method to accept a list of objects as a parameter instead of using a task cache.
- Improved the formatting of response payloads to handle multiple lines more gracefully.
___
<tr>
<td>
<details>
<summary><strong>mem.go</strong><dd><code>Adjust log chunk size …

add hidden force option for objprune 1.2

---

pkg/sql/plan/function/func_mo.go
pkg/vm/engine/tae/rpc/handle_debug.go

issue #https://github.com/matrixorigin/matrixone/issues/16419
skip collecting `mo_tables, mo_databases, mo_columns` and cluster tables for non-sys when `mo_table_size, mo_table_rows and show accounts`.
___
___
- Added a new function `specialTableFilterForNonSys` to filter special tables (`mo_tables`, `mo_databases`, `mo_columns`) and cluster tables for non-sys accounts.
- Removed the old logic that switched accounts for cluster tables, simplifying the context handling.
- Updated the `MoTableRows` and `MoTableSize` functions to use the new filtering logic and consistent context variable `foolCtx`.
- Disabled the gathering of special table sizes and handling of not ready new accounts in the `HandleStorageUsage` function.
___
<table><thead><tr><th></th><th …

sync to 1.2: skip collecting `mo_tables, mo_databases, mo_columns` and cluster tables for non-sys.

---

pkg/fileservice/file_service.go
pkg/fileservice/io_entry.go
pkg/fileservice/io_vector.go
pkg/fileservice/local_fs.go

issue #16379 
deallocate when error
___
Bug fix
___
- Added `releaseData` function to `IOEntry` struct and removed `releaseFuncs` slice.
- Implemented `prepareData` function in `IOEntry` to handle data allocation and deallocation with error handling.
- Updated `ReadFromOSFile` method to use `prepareData` for better error handling.
- Modified `Release` method in `IOVector` to use `releaseData` instead of `releaseFuncs`.
- Updated `read` method in `LocalFS` to use `prepareData` for error handling, removing manual allocation and deallocation logic.
___
<tr>
<td>
<details>
<summary><strong>file_service.go</strong><dd><code>Add releaseData function and remove …

fileservice: add IOVector.prepareData

---

test/distributed/cases/result_count/result_count.result
test/distributed/cases/result_count/result_count.sql
test/distributed/cases/zz_statement_query_type/result_count.result
test/distributed/cases/zz_statement_query_type/result_count.sql

issue #https://github.com/matrixorigin/matrixone/issues/14836, https://github.com/matrixorigin/matrixone/issues/16530
changes:
1. use hint `/*cloud_user*/` mark query DO NOT aggr.

chore: make sure no aggr in bvt result_count

---

test/distributed/cases/result_count/result_count.result
test/distributed/cases/result_count/result_count.sql
test/distributed/cases/zz_statement_query_type/result_count.result
test/distributed/cases/zz_statement_query_type/result_count.sql

issue #https://github.com/matrixorigin/matrixone/issues/14836, https://github.com/matrixorigin/matrixone/issues/16530
ref: https://github.com/matrixorigin/matrixone/pull/16534
changes:
- use hint `/*cloud_user*/` mark query DO NOT aggr.
___
Bug fix, Tests
___
- Added `/* cloud_user */` hint to `insert into t1` statements to prevent aggregation.
- Updated select statement limit from 50 to 52 in `result_count.result` and `result_count.sql`.
- Added comments and additional insert statements to ensure no aggregation in test cases.
___
<tr>
<td>
<details>
<summary><strong>result_count.result</strong><dd><code>Add hint to prevent aggregation in …

chore: make sure no aggr in bvt result_count in 1.2

---

pkg/sql/compile/compile.go
pkg/sql/compile/scope.go
pkg/vm/engine/disttae/engine.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/3374
remove log print from automaxprocs to 1.2-dev
___
Bug fix
___
- Added initialization for `maxprocs` with a no-op logger in multiple files to suppress log output.
- Removed unused import for `automaxprocs` in multiple files.
___
<tr>
<td>
<details>
<summary><strong>compile.go</strong><dd><code>Suppress `maxprocs` log output and clean up imports.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pkg/sql/compile/compile.go
<li>Added initialization for <code>maxprocs</code> with a no-op logger to suppress log <br>output.<br> <li> Removed unused import for <code>automaxprocs</code>.<br> …

remove log print from automaxprocs to 1.2-dev

---

pkg/common/malloc/malloc.go

issue # https://github.com/matrixorigin/MO-Cloud/issues/3369
less verbose logging
___
Enhancement
___
- Adjusted the log level from `Info` to `Debug` in `pkg/common/malloc/malloc.go` to reduce verbosity in logging.
___
<tr>
<td>
<details>
<summary><strong>malloc.go</strong><dd><code>Adjust log level from `Info` to `Debug` in malloc.go</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pkg/common/malloc/malloc.go
- Changed log level from `Info` to `Debug` for less verbose logging.
</details>
</td>
<td><a href="https://github.com/matrixorigin/matrixone/pull/16509/files#diff-8ebe656ce70c2a3b3da3f939376001a41c49d57f6ccfdf2ba486a300f5451ace">+1/-1</ …

malloc: fix log level

---

pkg/sql/compile/compile.go
pkg/sql/compile/scope.go
pkg/vm/engine/disttae/engine.go

Reverts matrixorigin/matrixone#16547
___
enhancement
___
- Removed the initialization of `maxprocs` with a custom logger in multiple files.
- Adjusted imports to include `automaxprocs` without initialization.
___
<tr>
<td>
<details>
<summary><strong>compile.go</strong><dd><code>Remove `maxprocs` initialization and adjust imports.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pkg/sql/compile/compile.go
<li>Removed the initialization of <code>maxprocs</code> with a custom logger.<br> <li> Added an import for <code>automaxprocs</code> without initialization.<br>
</details>
</td>
<td><a …

Revert "remove log print from automaxprocs to 1.2-dev"

---

pkg/lockservice/service_test.go

issue #15757 
fix lock service ut
___
Bug fix, Tests
___
- Reduced timeout durations from seconds to milliseconds to speed up test execution.
- Replaced `time.Sleep` calls with loops that check conditions to improve test reliability.
- Added additional assertions to ensure the lock service functions correctly under various conditions.
___
<tr>
<td>
<details>
<summary><strong>service_test.go</strong><dd><code>Improve reliability and speed of lock service unit tests</code>&nbsp; </dd></summary>
<hr>
pkg/lockservice/service_test.go
<li>Reduced timeout durations to milliseconds for faster test execution.<br> <li> Replaced sleep calls with loops checking conditions …

fix lock service ut

---

pkg/vm/engine/disttae/filter.go
pkg/vm/engine/disttae/txn_table.go

issue #https://github.com/matrixorigin/matrixone/issues/16463
making the dirty blocks collect lazily.
___
___
- Added `highSelectivityHint` parameter to several functions to improve filtering performance.
- Modified `CompileFilterExprs` and `CompileFilterExpr` to handle `highSelectivityHint`.
- Updated `TryFastFilterBlocks` and `ExecuteBlockFilter` to use `highSelectivityHint`.
- Changed `dirtyBlocks` from a map to a pointer to a map for lazy collection.
- Modified `rangesOnePart` in `txn_table.go` to collect dirty blocks lazily.
___
<tr>
<td>
<details>
<summary><strong>filter.go</strong><dd><code>Improve filter performance with high …

sync to 1.2: making collect dirty blocks lazily

---

pkg/shardservice/runtime.go
pkg/shardservice/service.go
pkg/shardservice/service_read.go
pkg/util/metric/v2/dashboard/grafana_dashboard.go
pkg/util/metric/v2/dashboard/grafana_dashboard_sharding.go
pkg/util/metric/v2/sharding.go

issue #16438 
add sharding metrics
___
___
- Added Prometheus metrics for various shard operations including AddReplica, DeleteReplica, and DeleteAllReplica.
- Integrated metrics into shard service operations to track replica counts and read operations.
- Created a new Grafana dashboard to visualize sharding metrics including replica counts, operations, and reads.
- Defined new Prometheus counters and gauges for tracking sharding metrics.
___
<tr>
<td>
<details>
<summary><strong>runtime.go</strong><dd><code>Add metrics counters for shard operations.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

add sharding metrics

---

pkg/common/morpc/server.go

issue #16141 
fix data race
___
Bug fix
___
- Added a new `disconnectedC` channel to the `clientSession` struct to handle disconnections more gracefully.
- Modified the `fetch` function within `startWriteLoop` to return a boolean indicating if the session should be closed, improving control flow.
- Updated the `startWriteLoop` method to check the new `disconnectedC` channel and handle the boolean return value from `fetch`, ensuring proper session closure.
- Introduced a `disconnected` method to the `clientSession` struct to signal when a session is disconnected, preventing potential data races.
___
<tr>
<td>
<details> …

fix data race

---

pkg/fileservice/local_fs.go
pkg/fileservice/s3_fs.go
pkg/util/metric/v2/dashboard/grafana_dashboard_fs.go
pkg/util/metric/v2/fileservice.go
pkg/util/metric/v2/metrics.go

issue #15509
refactor old metrics
___
Enhancement
___
- Refactored metric observation in `LocalFS` and `S3FS` to use new consolidated metric names.
- Updated Grafana dashboard to merge read and write duration rows and use new metric names.
- Consolidated read and write duration metrics into a single histogram in `fileservice.go`.
- Registered new consolidated read/write duration metric and removed old individual metrics in `metrics.go`.
___
<tr>
<td>
<details>
<summary><strong>local_fs.go</strong><dd><code>Refactor metric observation in LocalFS operations</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

fileservice: refactor read write duration metrics

---

.dockerignore
.gitignore
Makefile
etc/launch-tae-compose/compose.yaml
go.mod
optools/bvt_ut/Dockerfile
optools/compose_bvt/Dockerfile.tester
optools/compose_bvt/compose_bvt.sh
optools/compose_bvt/entrypoint.sh
optools/images/Dockerfile
optools/utilities.sh

issue # https://github.com/matrixorigin/MO-Cloud/issues/3413
1. bump go version from 1.21.5 to 1.22.3
2. fix `make compose` to make it work
3. `make ut` will read `UT_WORKDIR` env variable to store report, it will be `$HOME` if `UT_WORKDIR` is empty
___
___
- Bumped Go version from 1.21.5 to 1.22.3.
- Fixed and optimized Docker Compose BVT script.
- Improved MySQL readiness check and updated paths in entrypoint script.
- Added support for `UT_WORKDIR` environment variable.
- Updated `.dockerignore` to exclude scratch directories.
- Changed default `COMPOSE_LAUNCH` profile and added additional cleanup commands in Makefile.
- Removed version declaration from Docker Compose file.
- Updated base images in Dockerfiles to use Go 1.22.3.
___
<table><thead><tr><th></th><th …

bump go to 1.22.3, fix make compose and optimize ut script for 1.2-dev

---

pkg/vm/engine/disttae/txn_table.go
test/distributed/cases/function/mo_ctl/mo_ctl_merge.result
test/distributed/cases/function/mo_ctl/mo_ctl_merge.test

issue #11891 #15807
support some policy parameters.
___
Bug fix, Tests
___
- Enhanced the `MergeObjects` function to support additional merge policy parameters by introducing the `applyMergePolicy` function.
- Added `cutBetween` utility function to extract parameters from policy names.
- Updated test cases to include `sleep(1)` statements after merge operations to ensure proper timing.
- Added new test cases to validate the `overlap` merge policy with parameters.
___
<tr>
<td>
<details>
<summary><strong>txn_table.go</strong><dd><code>Implement merge policy parameter handling in txnTable</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

Support merge policy parameter 1.2 dev

---

pkg/vm/engine/tae/tables/jobs/flushTableTail.go
pkg/vm/engine/tae/tables/updates/mvcc.go

issue #16630
- reduce the size of tombstone files
___
___
- Added deduplication logic to avoid processing duplicate objects in `NewFlushTableTailTask`.
- Introduced delta statistics collection for the `bmsql_stock` schema, including logging of tombstone collection time and location distribution.
- Enhanced `GetLatestDeltaloc` method in `ObjectMVCCHandle` to include safety checks for `deltaloc` and its latest node.
___
<tr>
<td>
<details>
<summary><strong>flushTableTail.go</strong><dd><code>Deduplicate objects and add delta statistics in flushTableTailTask</code></dd></summary>
<hr>
pkg/vm/engine/tae/tables/jobs/flushTableTail.go …

remove duplicates in object list for flushing

---

pkg/frontend/util.go

issue #16662 
handle null in convertRowsIntoBatch
___
Bug fix
___
This PR addresses issue #16662 by handling null values in the `convertRowsIntoBatch` function:
- Added the `nulls` package to manage null values.
- Updated the `convertRowsIntoBatch` function to check for null values in each column type.
- Added null values to a nulls bitmap for each vector.
- Set the nulls bitmap for each vector in the batch to ensure proper handling of null values.
___
<tr>
<td>
<details>
<summary><strong>util.go</strong><dd><code>Handle null values in `convertRowsIntoBatch` function.</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pkg/frontend/util.go
<li>Added handling for …

handle null in convertRowsIntoBatch

---

pkg/frontend/types.go
pkg/frontend/variables.go

issue #16686 
Fix enumtype system variable check
___
Bug fix
___
- Fixed the logic for checking system variable definitions in `SetGlobalSysVar`.
- Improved error handling for session scope and read-only variables.
- Refactored the variable conversion process in `SetGlobalSysVar`.
- Corrected the range check in `SystemVariableEnumType.Convert` method.
___
<tr>
<td>
<details>
<summary><strong>types.go</strong><dd><code>Fix and refactor global system variable checks and conversions.</code></dd></summary>
<hr>
pkg/frontend/types.go
<li>Fixed the logic for checking system variable definitions.<br> <li> Improved error handling for session scope and read-only …

Fix enumtype system variable check

---

pkg/sql/plan/apply_indices.go
pkg/sql/plan/base_binder.go
pkg/sql/plan/build_constraint_util.go
pkg/sql/plan/build_dml_util.go
pkg/sql/plan/build_insert.go
pkg/sql/plan/expr_opt.go
pkg/sql/plan/function/func_get_admin.go
pkg/sql/plan/function/list_operator.go
pkg/sql/plan/make.go
pkg/sql/plan/partition_list.go
pkg/sql/plan/query_builder.go
pkg/sql/plan/rule/constant_fold.go
pkg/sql/plan/runtime_filter.go
pkg/sql/plan/stats.go
pkg/sql/plan/utils.go
pkg/vm/engine/disttae/util.go
pkg/vm/engine/disttae/util_test.go

issue #16146
(a,b,c) are composite keys
a=? and b in (?,?...) ==> __mo_cpkey_col prefix_in (?,?...) a=? and b = ? and c in (?,?...) ==> __mo_cpkey_col in (?,?...)
___
___
- Enhanced expression handling and function binding in various parts of the SQL planner.
- Improved handling of `in` and `not_in` functions to safely cast expressions.
- Fixed typos in function names.
- Updated type assignments to use specific types instead of `T_tuple`.
- Added constant folding for partition expressions.
- Improved selectivity estimation for `in` and `prefix_in` functions.
- Updated test cases to reflect changes in type assignment.
___
</strong></td><td><details><summary>13 …

[opt] merge filters on composite primary keys in plan (1.2-dev)

---

pkg/frontend/types.go
pkg/frontend/variables.go

issue #16686 
Fix enumtype system variable check
___
Bug fix
___
- Refactored the `SetGlobalSysVar` function in `pkg/frontend/types.go` to improve readability and error handling.
- Fixed the boundary check in `SystemVariableEnumType.Convert` method in `pkg/frontend/variables.go`.
___
<tr>
<td>
<details>
<summary><strong>types.go</strong><dd><code>Refactor and improve error handling in `SetGlobalSysVar` function</code></dd></summary>
<hr>
pkg/frontend/types.go
<li>Refactored the <code>SetGlobalSysVar</code> function to improve readability and <br>error handling.<br> <li> Changed the variable <code>sv</code> to <code>def</code> for clarity.<br> <li> Added …

Fix enumtype system variable check 

---

test/distributed/cases/save_query_result/save_query_result.result
test/distributed/cases/save_query_result/save_query_result.sql

issue #16613 
add issue 16613 cases
___
Bug fix, Tests
___
- Added SQL commands to create and drop an account.
- Added SQL commands to create, use, and drop a database.
- Added SQL commands to create a table and insert values.
- Added SQL commands to create, show, and drop publications and subscriptions.
___
<tr>
<td>
<details>
<summary><strong>save_query_result.result</strong><dd><code>Add SQL commands for account, database, and publication management.</code></dd></summary>
<hr>
test/distributed/cases/save_query_result/save_query_result.result
<li>Added SQL commands to create and drop an account.<br> <li> Added SQL commands to create, use, and drop a …

add issue 16613 cases

---

pkg/common/malloc/chain_deallocator.go
pkg/common/malloc/checked_deallocator_test.go
pkg/common/malloc/class_allocator.go
pkg/common/malloc/config.go
pkg/common/malloc/default.go
pkg/common/malloc/func_deallocator.go
pkg/common/malloc/metrics_allocator.go
pkg/common/malloc/metrics_allocator_test.go
pkg/common/malloc/profile_allocator.go
pkg/common/malloc/profile_allocator_test.go
pkg/common/malloc/profiler.go
pkg/common/malloc/profiler_test.go
pkg/common/malloc/utils.go
pkg/fileservice/file_service_test.go
pkg/fileservice/local_fs_test.go

issue #16667 
malloc: refactor config
malloc: add chainDeallocator, FuncDeallocator; optimize metrics allocator
malloc: optimize metrics allocator
malloc: enable metrics default

malloc: add profiler

---

cmd/mo-service/launch.go
go.mod
pkg/logservice/hakeeper_client.go

issue https://github.com/matrixorigin/MO-Cloud/issues/3450
fix timeout mechanism when TN service startup:
5m timeout for total wait and 5s timeout for each request.
___
___
- Fixed the timeout mechanism when starting the TN service by implementing a retry mechanism with a 5-second timeout for each request and a total timeout of 5 minutes.
- Improved error handling in the `startService` function by returning the actual error instead of `nil`.
- Enhanced the robustness of the `newHAKeeperClient` function in `hakeeper_client.go`.
- Updated dependencies in the `go.mod` file by adding `github.com/google/pprof` as a direct dependency and removing a duplicate indirect dependency.
___ …

[bug] launch: fix timeout mechanism when TN service startup

---

pkg/fileservice/local_fs.go

issue #16747 
fix fd leak in LocalFS.read

fileservice: fix fd leak in LocalFS.read

---

pkg/sql/plan/apply_indices_master.go
pkg/sql/plan/runtime_filter.go

issue # https://github.com/matrixorigin/matrixone/issues/14876
Remove unnecessary projects from Master Index.
```sql
mysql> explain analyze SELECT tbl.a100  FROM tbl  WHERE tbl.a75 = 'I2nJ0RqIQu';
+---------------------------------------------------------------------------------------------------------------------------------------------------------+
| AP QUERY PLAN ON MULTICN(10 core)                                                                                                                       |
+---------------------------------------------------------------------------------------------------------------------------------------------------------+
| Project …
```

[BugFix]: Remove unnecessary projections in master index

---

pkg/vm/engine/disttae/db.go
pkg/vm/engine/disttae/txn_database.go
pkg/vm/engine/disttae/txn_table.go

- [ x] BUG
issue #16620 
1. fix bug for snapshot read
___
Bug fix
___
- Added a check to update logtail before reusing the latest partition in `getOrCreateSnapPart` method.
- Removed debug logging for specific test conditions in `txnDatabase.Relation` method.
- Refactored partition state retrieval to use `getPartitionState` method and removed snapshot operation checks in `txnTable`.
- Simplified the `NewReader` method signature in `txnTable`.
___
<tr>
<td>
<details>
<summary><strong>db.go</strong><dd><code>Add logtail update and reuse latest partition if possible</code></dd></summary>
<hr>
pkg/vm/engine/disttae/db.go
<li>Added a check to update logtail …

Cherry-pick-for-snapshot-read-bug

---

pkg/sql/plan/base_binder.go
pkg/sql/plan/expr_opt.go
pkg/sql/plan/rule/constant_fold.go
pkg/sql/plan/utils.go
pkg/sql/plan/visit_plan_rule.go

issue #16730
don't convert IN expression to OR list in prepared statement
___
Enhancement
___
- Enhanced expression binding and type checking logic by modifying `checkNoNeedCast` function calls and adjusting case handling for the `like` operator.
- Improved merging filters on composite keys with added checks for multi-part primary keys.
- Enhanced constant folding for expression lists by avoiding folding non-literal expressions.
- Improved type checking utility functions to handle `plan.Expr` and added checks for numeric types.
- Added handling for `Expr_List` in various expression rules to ensure proper processing.
___
<tr>
<td>
<details> …

[opt] retain IN expression in prepared stmt (cp to 1.2-dev)

---

pkg/vm/engine/disttae/util.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/3461
workaround for get col type panic when construct block reader filter.

sync to 1.2: workaround for get col type panic when construct block reader filter.

---

pkg/sql/plan/build_insert.go

issue #16540
when prepare from on duplicate key statement. we can not rewrite it to replace
___
___
- Added `isPrepareStmt` parameter to the `getRewriteToReplaceStmt` function to handle prepared statements correctly.
- Modified `buildInsert` function to pass the `isPrepareStmt` parameter to `getRewriteToReplaceStmt`.
- Updated `getRewriteToReplaceStmt` to avoid rewriting to replace statement if `isPrepareStmt` is true.
___
<tr>
<td>
<details>
<summary><strong>build_insert.go</strong><dd><code>Fix and enhance duplicate key handling in prepared statements</code></dd></summary>
<hr>
pkg/sql/plan/build_insert.go
<li>Added …

do not rewrite on duplicate key stmt to replace for prepare

---

test/distributed/cases/system/system.result
test/distributed/cases/system/system.sql

add case for query from information_schema.files
issue #https://github.com/matrixorigin/MO-Cloud/issues/3302
add case for query from information_schema.files
___
Tests
___
- Added a new test case to query `information_schema.files` and verified that it returns an empty set.
- Included a SQL query to select from `information_schema.files` with a limit of 1.
___
<tr>
<td>
<details>
<summary><strong>system.result</strong><dd><code>Add test case for querying information_schema.files</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
test/distributed/cases/system/system.result
<li>Added a new test case to query …

add case for issue3302(1.2-dev).

---

pkg/vm/engine/tae/catalog/object.go
pkg/vm/engine/tae/tables/aobj.go
pkg/vm/engine/tae/tables/obj.go

issue #16812 
add debug log
___
___
- Added methods `CheckPrintPrepareCompact` and `PrintPrepareCompactDebugLog` to `ObjectEntry` for logging debug information related to compact operations.
- Enhanced `PrepareCompact` methods in `aobject` and `object` to include debug logging.
- Introduced a boolean flag `hasPrintedPrepareComapct` to track if the debug log has already been printed.
___
<tr>
<td>
<details>
<summary><strong>object.go</strong><dd><code>Add debug logging for compact operations in ObjectEntry</code>&nbsp; &nbsp; </dd></summary>
<hr>
pkg/vm/engine/tae/catalog/object.go
<li>Added <code>CheckPrintPrepareCompact</code> …

add deug log

---

pkg/sql/colexec/external/parquet_test.go
pkg/sql/colexec/table_function/generate_series.go
pkg/sql/colexec/table_function/metadata_scan.go
pkg/sql/compile/fuzzyCheck.go
pkg/sql/compile/operator.go

issue https://github.com/matrixorigin/matrixone/issues/16235
change some UnsafeGetStringAt to GetStringAt
___
Enhancement
___
- Replaced `UnsafeGetStringAt` with `GetStringAt` in multiple files to improve safety and consistency.
- Updated test assertions in `parquet_test.go`.
- Modified `resetGenerateSeriesState` function in `generate_series.go`.
- Updated `metadataScan` and `handleDatasource` functions in `metadata_scan.go`.
- Changed `vectorToString` function in `fuzzyCheck.go`.
- Updated `constructWindow` and `constructGroup` functions in `operator.go`.
___
<tr>
<td>
<details>
<summary><strong>parquet_test.go</strong><dd><code>Replace …

change some UnsafeGetStringAt to GetStringAt

---

pkg/vm/engine/disttae/filter.go
pkg/vm/engine/disttae/util.go

issue #https://github.com/matrixorigin/matrixone/issues/16816
const fold val expr lazily

sync to 1.2: fix sysbench random points ranges slow

---

pkg/clusterservice/cluster.go

issue #16480 
add lock for refresh() to protect cn services.
___
Bug fix
___
- Added a mutex (`mu`) to the `cluster` struct to prevent data races.
- Locked the `refresh` method using the mutex to ensure thread safety.
- Added comments to explain the necessity of the lock in the `refresh` method.
___
<tr>
<td>
<details>
<summary><strong>cluster.go</strong><dd><code>Add mutex to cluster struct and lock refresh method</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pkg/clusterservice/cluster.go
<li>Added a mutex (<code>mu</code>) to the <code>cluster</code> struct.<br> <li> Locked the <code>refresh</code> method to prevent data races.<br> …

[bug] clusterservice: add lock for refresh() to protect cn services.

---

pkg/sql/colexec/aggexec/exec_test.go

issue #16825 #16835 #16838 
修复一个vector重复调用free的问题，由于vector的指针池子是全局的，会导致同一个vector被多人持有，发生意想不到的错误。
___
Bug fix
___
- Fixed a bug in `TestMultiAggFuncExec1` that caused vectors to be freed twice.
- Ensured that vectors are not shared across multiple inputs by creating separate instances.
- Modified the test setup to prevent unexpected errors due to shared vector pointers.
___
<tr>
<td>
<details>
<summary><strong>exec_test.go</strong><dd><code>Fix vector double free issue in unit tests</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pkg/sql/colexec/aggexec/exec_test.go
<li>Fixed …

fix a ut bug will cause vector free twice

---

pkg/lockservice/lock_table_allocator.go
pkg/lockservice/lock_table_allocator_test.go
pkg/lockservice/rpc_test.go

issue #16732 
fix validate timeout lock table
___
Bug fix, Tests
___
- Fixed the validation logic in `checkInvalidBinds` method to properly handle retry errors and only disable binds when necessary.
- Added a new test `TestRetryValidateService` to ensure the retry logic for service validation works correctly.
___
<tr>
<td>
<details>
<summary><strong>lock_table_allocator.go</strong><dd><code>Fix validation logic for lock table binds</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pkg/lockservice/lock_table_allocator.go
<li>Added a check to continue loop if …

fix validate timeout lock table

---

pkg/frontend/mysql_protocol.go
pkg/frontend/util.go

issue #https://github.com/matrixorigin/matrixone/issues/16844
changes:
1. check if protocal is quit, skip CalculateOutTrafficBytes op.
- if NOT quit, logs the unexpected case.

fix: check protocol quit before CalculateOutTrafficBytes

---

pkg/sql/colexec/evalExpression.go

issue #14989
fix out of range
___
Bug fix
___
- Fixed out-of-range errors in `EvalIff` and `EvalCase` functions by ensuring loops iterate within the correct bounds.
- Replaced range-based loops with index-based loops for better control.
- Added variable `rowCount` to store the row count and use it for array initializations and loop bounds.
___
<tr>
<td>
<details>
<summary><strong>evalExpression.go</strong><dd><code>Fix out-of-range errors in `EvalIff` and `EvalCase` functions</code></dd></summary>
<hr>
pkg/sql/colexec/evalExpression.go
<li>Fixed out-of-range errors by ensuring loops iterate within the correct <br>bounds.<br> <li> Replaced range-based loops …

Fix panic: out of range in EvalExpression.go

---

pkg/vm/engine/tae/catalog/object.go
pkg/vm/engine/tae/tables/aobj.go

issue #16812 
update debug log, print appendnodes
___
Bug fix
___
- Enhanced the `PrepareCompact` method with additional debug logging.
- Added checks for `PrepareCompactLocked` and corresponding debug logs.
- Introduced a flag `HasPrintedPrepareComapct` to ensure specific logs are printed only once.
___
<tr>
<td>
<details>
<summary><strong>aobj.go</strong><dd><code>Enhanced debug logging in `PrepareCompact` method.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pkg/vm/engine/tae/tables/aobj.go
<li>Added debug logging for <code>PrepareCompact</code> method.<br> <li> Introduced checks and logging for …

update debug log, print appendnodes

---

pkg/common/moerr/error_no_ctx.go
pkg/frontend/mysql_cmd_executor.go
pkg/frontend/types.go
pkg/frontend/util.go
pkg/logutil/fields.go
pkg/vm/engine/disttae/logtailreplay/blocks_iter.go
pkg/vm/engine/disttae/txn_table.go

issue #16883 
print more detailed info
___
___
- Enhanced `NewTxnStaleNoCtx` function to accept a message string for better error context.
- Added `makeCompactTxnInfo` function to format transaction info and updated related transaction ID handling.
- Replaced `SetStaticTxnId` and `GetStaticTxnId` with `SetStaticTxnInfo` and `GetStaticTxnInfo` in session handling.
- Improved error logging to use transaction info instead of transaction ID.
- Added `TxnInfoField` for logging transaction info.
- Enhanced `NewObjectsIter` to include detailed error message.
- Added error logging with transaction details in `Ranges` and `MergeObjects` functions in transaction table.
___ …

Update txn print

---

pkg/common/malloc/allocator.go
pkg/common/malloc/allocator_bench_test.go
pkg/common/malloc/allocator_test.go
pkg/common/malloc/c_allocator.go
pkg/common/malloc/checked_deallocator_test.go
pkg/common/malloc/class_allocator.go
pkg/common/malloc/config.go
pkg/common/malloc/default.go
pkg/common/malloc/default_test.go
pkg/common/malloc/fuzz_test.go
pkg/common/malloc/metrics_allocator.go
pkg/common/malloc/profile_allocator.go
pkg/common/malloc/profile_allocator_test.go
pkg/common/malloc/profiler.go
pkg/common/malloc/profiler_test.go
pkg/common/malloc/pure_go_class_allocator.go
pkg/common/malloc/sharded_allocator.go
pkg/common/malloc/sharded_counter.go
pkg/common/malloc/sharded_counter_test.go
pkg/common/malloc/size_bounded_allocator.go
pkg/common/malloc/size_bounded_allocator_test.go
pkg/fileservice/bytes.go
pkg/fileservice/io_entry.go
pkg/fileservice/malloc.go
pkg/fileservice/memorycache/cache_test.go
pkg/fileservice/memorycache/data.go
pkg/fileservice/memorycache/data_test.go

issue #16667 
more optimizations for malloc profile
performance comparison
```
goos: linux
goarch: amd64
pkg: github.com/matrixorigin/matrixone/pkg/common/malloc
cpu: AMD Ryzen 9 7900 12-Core Processor             
│      b1      │                  b2                   │
│    sec/op    │    sec/op     vs base                 │
DefaultAllocator/allocate:_n_64-24        222.0n ± ∞ ¹   120.1n ± ∞ ¹        ~ (p=1.000 n=1) ²
DefaultAllocator/parallel:_n_64-24        30.90n ± ∞ ¹   29.84n ± ∞ ¹        ~ (p=1.000 n=1) ²
DefaultAllocator/allocate:_n_4096-24      256.1n ± ∞ ¹   139.8n ± ∞ ¹        ~ (p=1.000 n=1) ²
DefaultAllocator/parallel:_n_4096-24      34.70n ± ∞ ¹   32.21n ± ∞ ¹        ~ (p=1.000 n=1) ²
DefaultAllocator/allocate:_n_2097152-24   400.2n ± ∞ ¹   254.6n ± ∞ ¹        ~ (p=1.000 …
```

malloc: various changes and optimizations

---

pkg/container/vector/search.go
pkg/frontend/test/engine_mock.go
pkg/sql/compile/scope.go
pkg/vm/engine/disttae/engine.go
pkg/vm/engine/disttae/logtailreplay/rows_iter.go
pkg/vm/engine/disttae/reader.go
pkg/vm/engine/disttae/tools.go
pkg/vm/engine/disttae/txn_table.go
pkg/vm/engine/disttae/types.go
pkg/vm/engine/disttae/util.go
pkg/vm/engine/disttae/util_test.go
pkg/vm/engine/entire_engine.go
pkg/vm/engine/entire_engine_test.go
pkg/vm/engine/memoryengine/binded.go
pkg/vm/engine/memoryengine/engine.go
pkg/vm/engine/tae/blockio/read.go
pkg/vm/engine/tae/logtail/snapshot.go
pkg/vm/engine/types.go

issue #https://github.com/matrixorigin/matrixone/issues/16654
1. Compiling the expression once to generate the in-memory and block reader filters.
2. Supporting: in, prefix_in, eq, prefix_eq, between, prefix_between, >, >=, <, <=.

sync to 1.2: refactor in memory reader filter and simplify reader filters. 

---

pkg/tests/service/dnservice.go
pkg/tests/service/options.go
pkg/tnservice/cfg.go
pkg/tnservice/factory.go
pkg/tnservice/service_ports_test.go
pkg/util/metric/v2/dashboard/grafana_dashboard_logtail.go
pkg/util/metric/v2/logtail.go
pkg/util/metric/v2/metrics.go
pkg/vm/engine/disttae/logtail_consumer.go
pkg/vm/engine/tae/logtail/service/merger.go
pkg/vm/engine/tae/logtail/service/merger_test.go
pkg/vm/engine/tae/logtail/service/response.go
pkg/vm/engine/tae/logtail/service/server.go
pkg/vm/engine/tae/logtail/service/session.go
pkg/vm/engine/tae/logtail/txn_handle.go
pkg/vm/engine/tae/options/cfg.go
pkg/vm/engine/tae/options/cfg_test.go

issue #13724 
A table subscription takes long time if the table has much data
which need flushed, and it will block the logtail update of other
tables because they work in the same goroutine.
So we put the table subscription into a independent goroutine,
thus the logtails of other tables could be pushed to cn servers
without being blocked. And when the first phase of pulling table
data finishes, put it into the same goroutine with pushing-job,
and pull the data again for the second phase. At last, send the
whole data that are merged together to cn servers.
After the PR, the table subscription will not block pushing-jobs.
There are 50 parallel pulling jobs at the same time at most by
defalt to avoid OOM and other risks.

[enhancement] logtail: make table subscription async

---

pkg/vm/engine/tae/common/stats.go
pkg/vm/engine/tae/tables/base.go
pkg/vm/engine/tae/tables/jobs/flushTableTail.go
pkg/vm/engine/tae/tables/jobs/flushdeletes.go
pkg/vm/engine/tae/tables/jobs/flushobj.go
pkg/vm/engine/tae/tables/jobs/mergeobjects.go
pkg/vm/engine/tae/tables/utils.go

issue #16716
add logs to diagnose slow flush task
___
___
- Added `DeletesCollectRecorder` and `DeletesCollectBoard` structs for recording and aggregating delete collection metrics.
- Integrated context-based recording for delete collection metrics in base object methods.
- Added detailed timing and logging for various phases of the flush table tail task, including slow flush detection.
- Enhanced logging for slow flush detection in flush deletes and flush object tasks.
- Added timing and logging for the merge objects task, including slow merge detection.
- Integrated delete collection metrics recording in utility functions.
___
<tr> …

trace slow flush

---

pkg/sql/plan/build_load.go
test/distributed/cases/load_data/load_data.result
test/distributed/cases/load_data/load_data.sql

fix load data columnlist bug
Approved by: @aunjgr, @heni02, @ouyuanning, @iamlinjunhong
issue #16152
fix bug : Columns cannot correspond when use load data inline
___
Bug fix, Tests
___
- Fixed a bug where columns could not correspond correctly when using load data inline.
- Updated `buildLoad` and `getProjectNode` functions to ensure proper column mapping and indexing.
- Added new test cases to verify the fix for inline data loading with specified column list.
___
<tr>
<td>
<details>
<summary><strong>build_load.go</strong><dd><code>Fix column mapping and indexing in load data functionality</code></dd></summary>
<hr>
pkg/sql/plan/build_load.go
<li>Fixed …

load columnlist 

---

pkg/vm/engine/tae/common/stats.go
pkg/vm/engine/tae/tables/jobs/flushTableTail.go
pkg/vm/engine/tae/tables/utils.go

issue #16716
Cache the decompressed batch when reading a deltaloc file over 10 times in a flush table task.
___
___
- Added a caching mechanism for delete collection to improve performance.
- Adjusted timing constants for slow flush tasks to better diagnose issues.
- Enhanced logging details for better traceability of slow flush tasks.
- Removed unused `LoadAfter` fields and related logic.
___
<tr>
<td>
<details>
<summary><strong>stats.go</strong><dd><code>Add caching mechanism and remove unused fields.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pkg/vm/engine/tae/common/stats.go …

fix slow flush 1.2

---

pkg/sql/plan/build_load.go
test/distributed/cases/load_data/load_data.result
test/distributed/cases/load_data/load_data.sql
test/distributed/resources/load_data/test_columnlist_01.csv

issue #https://github.com/matrixorigin/MO-Cloud/issues/3522
fix load data infill with columnist error
___
Bug fix, Tests
___
- Fixed a bug in the `buildLoad` function where `ColumnList` was not handled correctly.
- Updated the `getProjectNode` function to accept `columnList` as a parameter and modified its logic accordingly.
- Added new test cases in `load_data.result` to verify the correct loading of data with a column list.
- Included corresponding SQL commands in `load_data.sql` to test the new functionality.
___
<tr>
<td>
<details>
<summary><strong>build_load.go</strong><dd><code>Fix <code>ColumnList</code> handling in <code>buildLoad</code> and …

fix: load data infile with columnlist error

---

pkg/vm/engine/tae/options/options.go

issue #16942 
change transfer page ttl from 90s to 60s
___
Enhancement
___
- Changed the `TransferTableTTL` default value from 90 seconds to 60 seconds in the `FillDefaults` function.
- This change addresses issue #16942.
___
<tr>
<td>
<details>
<summary><strong>options.go</strong><dd><code>Update TransferTableTTL default value to 60 seconds</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pkg/vm/engine/tae/options/options.go
<li>Changed the <code>TransferTableTTL</code> default value from 90 seconds to 60 <br>seconds.<br>
</details>
</td>
<td><a href="https://github.com/matrixorigin/matrixone/pull/16952/files#diff-7a129eb095032535e945 …

change transfer page ttl from 90s to 60s

---

pkg/common/moerr/error_no_ctx.go
pkg/frontend/mysql_cmd_executor.go
pkg/frontend/types.go
pkg/frontend/util.go
pkg/logutil/fields.go
pkg/vm/engine/disttae/logtailreplay/blocks_iter.go
pkg/vm/engine/disttae/txn_table.go
pkg/vm/engine/tae/options/options.go

issue #16883 #16942
pick 16952 and 16894 to main
___
___
- Modified `NewTxnStaleNoCtx` function to accept a message string parameter.
- Enhanced transaction info logging in MySQL command executor by adding `makeCompactTxnInfo` function.
- Replaced static transaction ID with transaction info string in frontend types.
- Updated error logging to use transaction info instead of transaction ID.
- Added `TxnInfoField` function for logging transaction info.
- Included message in `TxnStale` error in `NewObjectsIter`.
- Added error logging with transaction debug string in `Ranges` and `MergeObjects`.
- Changed transfer table TTL from 90 seconds to 60 seconds.
___ …

pick 16952 and 16894 to main

---

pkg/lockservice/lock_table_allocator.go
pkg/lockservice/rpc_test.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/3490 #https://github.com/matrixorigin/MO-Cloud/issues/3530
#https://github.com/matrixorigin/MO-Cloud/issues/3521 #https://github.com/matrixorigin/MO-Cloud/issues/3512
fix check invalid binds
___
Bug fix, Tests
___
- Added a nil check before calling `isRetryError` in the `checkInvalidBinds` method to prevent potential errors.
- Updated `TestRetryValidateService` to include a nil check before calling `isRetryError`.
- Added a new test `TestValidateService` to validate service responses and ensure correct behavior.
___
<tr>
<td>
<details>
<summary><strong>lock_table_allocator.go</strong><dd><code>Add nil …

fix check invalid binds

---

pkg/sql/colexec/table_scan/table_scan.go
pkg/sql/colexec/table_scan/types.go

issue #14940 
这个原来是因为有时reader返回的数据量较小，使得可以上范围锁的变成上点锁。容易造成点锁数量较大时加的。
现在一个是没有范围锁了，另外当点锁太大会转表锁，这部分逻辑应该没有必要存在了，徒增复杂度。

remove tmp buf from table_scan

---

pkg/txn/client/client.go

issue #16716
retry to get latest ts, but do not fatal if waiter is paused when wait for the ts.

[bug] txn: do not fatal if waiter is paused when wait for the ts.

---

pkg/vm/engine/tae/logstore/driver/logservicedriver/truncate.go

issue #16987
comsume ErrInvalidTruncateLsn
___
Bug fix
___
- Added logging to indicate the start of the truncate process.
- Introduced error handling for `ErrInvalidTruncateLsn` using `moerr.IsMoErrCode`.
- Implemented retry logic for the truncate operation with additional logging for retries.
- Enhanced final log message to confirm successful truncation.
___
<tr>
<td>
<details>
<summary><strong>truncate.go</strong><dd><code>Enhance truncate log service with error handling and logging</code></dd></summary>
<hr>
pkg/vm/engine/tae/logstore/driver/logservicedriver/truncate.go
<li>Added logging for the start of the truncate process.<br> <li> Added error handling …

fix truncate

---

pkg/common/morpc/mock_morpc/types_mock.go
pkg/common/morpc/server.go
pkg/common/morpc/types.go
pkg/sql/compile/remoterunServer.go
pkg/txn/rpc/server_test.go
pkg/vm/engine/tae/logtail/service/session_test.go

https://github.com/matrixorigin/MO-Cloud/issues/3542
https://github.com/matrixorigin/MO-Cloud/issues/2788
https://github.com/matrixorigin/MO-Cloud/issues/3281
fix a bug that the TCP context was incorrectly used as a STREAM context during the remote run, 
this will cause an inability to properly determine whether the stream had been disconnected.
___
Bug fix
___
- Added `SessionCtx` method to `clientSession` and `ClientSession` interface to retrieve the session context.
- Replaced incorrect usage of `ctx` with `connectionCtx` and `messageCtx` in `remoterunServer.go`.
- Updated `messageReceiverOnServer` struct and related functions to properly handle connection and message contexts.
___ …

fix incorrect use of connection ctx during remote run.

---

pkg/lockservice/lock_table_local.go
pkg/lockservice/service.go

issue [#3530](https://github.com/matrixorigin/MO-Cloud/issues/3530)
add log to debug lock table create multi times
___
Bug fix
___
- Added logging to debug lock table creation in `localLockTable` and `service` components.
- Included current and new lock table pointers in log output for better debugging.
- Added logging for lock table removal to track when tables are deleted.
___
<tr>
<td>
<details>
<summary><strong>lock_table_local.go</strong><dd><code>Add logging for lock table creation in local lock table</code>&nbsp; &nbsp; </dd></summary>
<hr>
pkg/lockservice/lock_table_local.go
<li>Added logging to debug lock table creation.<br> <li> Included current …

add log to debug lock table create multi times

---

pkg/sql/compile/remoterunClient.go
pkg/sql/compile/remoterunServer.go
pkg/sql/compile/scope.go

https://github.com/matrixorigin/matrixone/issues/17015
https://github.com/matrixorigin/MO-Cloud/issues/3542
https://github.com/matrixorigin/MO-Cloud/issues/2788
修改了一个远端执行的context没有指定deadline导致的错误。
___
Bug fix
___
- Introduced a `MaxRpcTime` constant to set a default RPC timeout if none is specified.
- Updated the `newMessageSenderOnClient` function to use `MaxRpcTime` for context timeout.
- Modified the `newCompile` function to ensure the message context has a deadline and return an error if it does not.
- Updated `handlePipelineMessage` to handle errors from `newCompile`.
- Changed the context used in `sendNotifyMessage` to `sender.ctx` to ensure consistency.
___ …

fix a bug that cause the remote-run context lost a deadline

---

pkg/sql/colexec/external/types.go

#16725
issue #
fix external_scan free panic when MO Checkin Regression On TKE
___
Bug fix
___
- Fixed a panic issue in the `Free` method of `pkg/sql/colexec/external/types.go` by reordering the operations.
- Ensured allocation analysis is performed before setting `arg.ctr` to nil.
___
<tr>
<td>
<details>
<summary><strong>types.go</strong><dd><code>Fix panic in `Free` method by reordering operations</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pkg/sql/colexec/external/types.go
<li>Fixed the order of operations in the <code>Free</code> method to prevent panic.<br> <li> Moved the allocation analysis to occur before setting …

fix: external free

---

pkg/sql/compile/remoterunClient.go
pkg/sql/compile/remoterunServer.go

issue #16741
https://github.com/matrixorigin/MO-Cloud/issues/2788
返回值里没有将connection正确返回，导致无法被关闭。

fix a remoterun bug never close connection.

---

pkg/vm/engine/disttae/logtailreplay/partition_state.go

- [ x] BUG
issue #16942 
1.  The entries in PartitionState.primaryIndex  are not deleted in some case, leads to memory leak.

Fix memory leak for partition state

---

pkg/fileservice/aws_sdk_v2.go

issue #17094 
retry will be done in the fileservice package

fileservice: use noop retryer in aws sdk

---

pkg/sql/colexec/fuzzyfilter/filter.go
pkg/sql/colexec/fuzzyfilter/types.go
pkg/sql/compile/compile.go

issue #17075
prepare for the subsequent TP performance improvement
___
Enhancement
___
- Added a callback function execution after setting the row count in the fuzzy filter process.
- Introduced a new `Callback` function field in the `Argument` struct to handle batch processing.
- Replaced the output operator with a callback function in the fuzzy filter compilation process, simplifying the code.
- Simplified struct initialization syntax in the MySQL parser for better readability.
___
<tr>
<td>
<details>
<summary><strong>filter.go</strong><dd><code>Add callback execution after setting row count in fuzzy filter</code></dd></summary>
<hr> …

[opt] : remove output operator after fuzzy filter

---

pkg/frontend/mysql_cmd_executor.go

issue https://github.com/matrixorigin/MO-Cloud/issues/3553
fix get role name of mo_catalog.database/tables/columns in `show table status`

fix get role name of sys tables

---

pkg/sql/colexec/insert/types.go
pkg/sql/colexec/mergedelete/types.go
pkg/sql/compile/compile.go
pkg/sql/plan/build_dml_util.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/3575#issuecomment-2185753388
make delete rowCount right

[cherry-pick-16310] : mergeDelete on hidden table should not update affactRows

---

pkg/sql/colexec/right/types.go
pkg/sql/colexec/rightanti/types.go
pkg/sql/colexec/rightsemi/types.go

issue https://github.com/matrixorigin/MO-Cloud/issues/3338
Do not read from channel in Free()
___
Bug fix
___
- Simplified the condition for sending to the channel in the `Free` method across multiple files.
- Removed unnecessary channel reads for merger cases to prevent hanging.
___
<tr>
<td>
<details>
<summary><strong>types.go</strong><dd><code>Simplify channel handling logic in `Free` method.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pkg/sql/colexec/right/types.go
<li>Simplified the condition for sending to the channel in the <code>Free</code> <br>method.<br> <li> Removed unnecessary channel reads for merger …

Fix rightjoin.Free hung

---

pkg/frontend/authenticate.go
pkg/frontend/authenticate_test.go
pkg/frontend/back_exec.go
pkg/frontend/server.go
pkg/frontend/session.go
pkg/frontend/show_account_test.go
pkg/frontend/txn.go

issue #https://github.com/matrixorigin/matrixone/issues/15577
https://github.com/matrixorigin/matrixone/issues/15629
https://github.com/matrixorigin/matrixone/issues/15675
1，解决data race
session取tenantInfo
tennantInfo内部都加了mutex.
全局变量globalAicm，globalRtMgr用原子变量包装。
2，ut 时序问题
打开client连接加了重试3次。会出现server 没启动成功，client就开始连接的情况。
将关闭client连接移动到 server 关闭之后。避免server还在发数据，client连接就断开的错误。

cherrypick: fix ut failed about race

---

pkg/vm/engine/tae/db/gc/checkpoint.go

global checkpoint needs to be consumed
issue https://github.com/matrixorigin/matrixone/issues/15782 #15824
When the global checkpoint on which it depends is GCed, 
the latest global checkpoint needs to be consumed

Init snapshot table must consume a global checkpoint

---

pkg/vm/engine/tae/tables/jobs/flushTableTail.go

issue #15564
fix memory leak in flushAObjsForSnapshot when error occurs.

fix memory leak in flushAObjsForSnapshot

---

pkg/lockservice/lock_table_allocator.go
pkg/lockservice/lock_table_keeper.go
pkg/lockservice/log.go
pkg/lockservice/service.go
pkg/lockservice/service_test.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/3516 #https://github.com/matrixorigin/MO-Cloud/issues/3537
fix can restart cn when tn crash
___
Bug fix, Tests
___
- Improved logging and status handling in `lock_table_allocator.go` by adding service status details and new logging functions.
- Added error logging for abnormal lock service status in `lock_table_keeper.go`.
- Introduced new logging functions and enhanced existing ones in `log.go` to include service ID and status.
- Enhanced logging in service status management in `service.go`.
- Added new tests in `service_test.go` to verify the service restart behavior related to issue #3537.
___ …

fix can restart cn when tn crash

---

pkg/vm/engine/tae/db/merge/executor.go
pkg/vm/engine/tae/db/scannerop.go

issue #16942
To avoid transfer pages to occupy too much memory. The limit is set concerning available memory for the TN process, to be specific:
- for 200+GB memory, take 10%
- for 100+GB, 15%
- for 40+GB, 20%
___
Enhancement
___
- Added a new `transPageLimit` field to the `MergeExecutor` struct to control the memory usage for transfer pages.
- Implemented logic in `MergeExecutor` to set `transPageLimit` based on available memory thresholds.
- Introduced a `TransferPageSizeLimit` method in `MergeExecutor` to retrieve the transfer page size limit.
- Updated `MergeTaskBuilder` to include a `skipForTransPageLimit` field and logic to skip merge scanning if the transfer page size exceeds the limit.
- Removed unused concurrency control fields (`suspend` and `suspendCnt`) from …

Set transfer page limit 1.2

---

pkg/vm/engine/disttae/txn_table.go

- [x ] BUG
issue #16948  #16938 #16577  #16421 #15844  #14890 #14880 #14405 #14160 #16701 #15843 
1.  Fix  dup/ww when `rangesOnePart `goes slow path, since lost deletes.

Fix ww/dup- caused by lost deletes  in rangesOnePart

---

pkg/vm/engine/disttae/txn_table.go
test/distributed/cases/mo_cloud/mo_cloud.result

issue #https://github.com/matrixorigin/matrixone/issues/17024
之前统计 partition state 里面的 rows 时，使用的是 row.Batch 的地址昨晚去重的手段，绝大多数情况下没有问题，但一条记录也可能会重复推到 CN，不属于同一个 logtail, 自然也不属于同一个 batch，所以就做不到去重的目的。现在使用 rowid 去重。

sync to 1.2: fix `Size()` duplicate counting rows size.

---

pkg/container/types/decimal.go
test/distributed/cases/dtype/decimal.result
test/distributed/cases/dtype/decimal.test

issue #16869
Return error when cast empty string to Decimal
___
Bug fix
___
- Added error handling for empty string inputs in various decimal parsing functions to prevent invalid conversions.
- Functions `Parse64`, `ParseDecimal64`, `ParseDecimal64FromByte`, `Parse128`, `ParseDecimal128`, and `ParseDecimal128FromByte` now return an error when the input string is empty.
___
<tr>
<td>
<details>
<summary><strong>decimal.go</strong><dd><code>Add error handling for empty string inputs in decimal parsing </code><br><code>functions</code></dd></summary>
<hr>
pkg/container/types/decimal.go
<li>Added error handling for empty string inputs in various decimal …

Return error when cast empty string to Decimal

---

pkg/sql/colexec/evalExpression.go
pkg/sql/plan/expr_opt.go
pkg/sql/plan/stats.go

issue #16976
some current code doesn't properly handle logical expression with more than 2 arguments
___
___
- Fixed handling of `AND` and `OR` expressions with more than 2 arguments in `evalExpression.go`.
- Enhanced merging of filters to support `IN` operator and improved handling of composite key filters in `expr_opt.go`.
- Fixed selectivity estimation for `AND` and `OR` expressions with more than 2 arguments in `stats.go`.
___
<tr>
<td>
<details>
<summary><strong>evalExpression.go</strong><dd><code>Fix handling of multi-argument AND/OR expressions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

fix stats for OR expression with more than 2 arguments

---

pkg/objectio/cache.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/3526
Change metadata cache size:
Change the max size for a host with a high memory capacity from 2g to 4g.
Change the metadata cache policy:
Read from disk cache -> Read from memory cache
___
Enhancement
___
- Increased metadata cache size for hosts with high memory capacity from 2GB to 4GB.
- Adjusted cache size thresholds to better utilize available memory.
- Changed metadata cache policy to prioritize reading from memory cache over disk cache.
___
<tr>
<td>
<details>
<summary><strong>cache.go</strong><dd><code>Update metadata cache size and policy</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

change metadata cache size and policy

---

pkg/vm/engine/disttae/logtail_consumer.go

- [x ] BUG
issue #
https://github.com/matrixorigin/MO-Cloud/issues/3538
1. Remove the redundant `requestLock ` to avoid dead lock,  since the [PR ](https://github.com/matrixorigin/matrixone/pull/17005)  guarantees the serializability of subscribing and unsubscribing a table by state machine.

Fix dead lock 

---

pkg/common/moerr/error.go
pkg/common/moerr/error_no_ctx.go
pkg/objectio/writer.go
pkg/vm/engine/disttae/merge.go
pkg/vm/engine/tae/mergesort/merger.go
pkg/vm/engine/tae/mergesort/reshaper.go
pkg/vm/engine/tae/mergesort/task.go
pkg/vm/engine/tae/tables/jobs/mergeobjects.go

issue #17188
objectIO write add object size limit.
If the compressed data exceeds 3G, an error of limited writing is returned

Fix force merge big data bug&objectIO add object size limit

---

pkg/sql/plan/apply_indices.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/3194
fix a bug that should not use index when right child's selectivity is too high

fix a bug that should not use index when right child's selectivity is too high

---

pkg/sql/plan/build_insert.go
pkg/sql/plan/function/func_prefix.go
pkg/sql/plan/function/list_builtIn.go

issue #16964
PrefixCompare doesn't satisfy transitivity of order. For a = '0', b = '0-catalog', c = '0-mysql', we have PrefixCompare(a, b) < 0, PrefixCompare(b, c) < 0, but PrefixCompare(a, c) = 0. If '0' and '0-catalog' co-exists in the second parameter, we remove the latter one.

[fix] remove unnecessary values from the second parameter of prefix_in (cp #17111 to 1.2)

---

pkg/proxy/client_conn.go

issue https://github.com/matrixorigin/matrixone/issues/16824
fix the connection ID when send request to cn server. A new connection
ID should be used when send kill query SQL, but not a used one.

[bug] proxy: fix the connection id when send request to cn server.

---

pkg/sql/plan/apply_indices.go
pkg/sql/plan/base_binder.go
pkg/sql/plan/stats.go
pkg/sql/plan/utils.go

issue #17292 
在prepare语句下，between and会错误的退化成> and <
另外由于动态参数无法准确预估stats，导致执行计划不优。
假定存在动态参数时，between的过滤度总是比较高的

fix bugs for between function in prepare mode

---

pkg/sql/compile/remoterunServer.go
pkg/vm/process/process.go

https://github.com/matrixorigin/MO-Cloud/issues/3512
https://github.com/matrixorigin/matrixone/issues/17226
修复了一个没有给process的cancel方法赋值，以及cancel方法与传入的ctx不对应导致的pipeline无法被正常杀死的问题。

[pick to 1.2] fix a bug that process's cancel not match to its context

---

pkg/sql/compile/remoterunServer.go
pkg/vm/process/process.go
pkg/vm/process/types.go

https://github.com/matrixorigin/MO-Cloud/issues/3512
https://github.com/matrixorigin/matrixone/issues/17226
修复了一个没有给process的cancel方法赋值，以及cancel方法与传入的ctx不对应导致的pipeline无法被正常杀死的问题。

fix a bug that process's cancel not match to its context

---

pkg/vm/engine/disttae/engine.go
pkg/vm/engine/disttae/stats.go

issue https://github.com/matrixorigin/MO-Cloud/issues/3656
When removing the PartitionState, you need to remove the tid in globalStats.
When re-subscribing, globalStats will wait for the PartitionState to be consumed before updating the object state.

Fix Location's Extend is 0 when call UpdateTableStats for 1.2

---

pkg/vm/engine/disttae/txn_table.go
pkg/vm/engine/disttae/types.go

issue #14518 
log some slow ranges expr
log some exprs
___
Enhancement
___
- Introduced `traceFilterExprInterval` to manage logging intervals for filter expressions.
- Added logic in `Ranges` method to conditionally log filter expressions based on the length of ranges.
- Implemented logging for filter expressions in `NewReader` method when `enableLogFilterExpr` is set.
- Added `enableLogFilterExpr` atomic boolean to `txnTable` struct to control logging behavior.
___
<tr>
<td>
<details>
<summary><strong>txn_table.go</strong><dd><code>Add conditional logging for filter expressions based on range length</code></dd></summary>
<hr> …

log some filter exprs

---

pkg/sql/compile/compile.go

issue #17350 
the clear method of the Compile structure ,which will be called after query done, should not modify the internal properties of the proc, because this attribute is directly passed in from the outside. When a query fails and a retry occurs, this attribute will still be used.

fix Compile clear() method bug.

---

pkg/sql/compile/compile.go

issue #17350 
the clear method of the Compile structure ,which will be called after query done, should not modify the internal properties of the proc, because this attribute is directly passed in from the outside. When a query fails and a retry occurs, this attribute will still be used.

[pick to main] fix Compile clear() bug.

---

pkg/sql/compile/compile.go
pkg/sql/compile/remoterunServer.go
pkg/vm/process/process.go

issue #17358 
These two pr will cause :
1、the sysbench test hung 
2、lots of orphan transaction during stability test on distributed mode
3、mo hung during stability test on distributed mode
___
Bug fix
___
- Reverted changes to the `reset` method in the `Compile` class to avoid setting `proc.Ctx` to `nil`.
- Reverted changes to the `newCompile` method in the `messageReceiverOnServer` class to restore `proc.Ctx` assignment.
- Reverted context handling changes in the `New` method of the `Process` class to use the original context handling.
___
<tr>
<td>
<details>
<summary><strong>compile.go</strong><dd><code>Revert changes to `reset` method in `Compile` …

Revert "fix Compile clear() method bug and [pick to 1.2] fix a bug that process's cancel not match to its context "

---

pkg/vm/engine/disttae/stats.go

issue #17365 
When force to trigger the stats update, which will hang when the channel
is full, we should unlock first because another goroutine which fetches
items from the channel holds the lock.

[bug] stats: fix hang issue

---

pkg/sql/plan/utils.go
pkg/vm/engine/disttae/txn_table.go
pkg/vm/engine/disttae/types.go
pkg/vm/engine/tae/rpc/utils.go

issue #14518 
optimize expr print and reduce filter expr prints
___
Enhancement
___
- Added handling for vector expressions in the `doFormatExpr` function in `pkg/sql/plan/utils.go`.
- Introduced a new atomic variable `traceFilterExprInterval2` in `pkg/vm/engine/disttae/txn_table.go`.
- Modified the `Ranges` function to optimize filter expression logging based on new conditions.
___
<tr>
<td>
<details>
<summary><strong>utils.go</strong><dd><code>Add handling for vector expressions in `doFormatExpr`</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pkg/sql/plan/utils.go
<li>Added a new case for <code>Expr_Vec</code> in the <code>doFormatExpr</code> …

add filter expr log and optimize expr print

---

pkg/sql/plan/build_dml_util.go

issue https://github.com/matrixorigin/matrixone/issues/16493
Before 16493 is resolved, it is risky to cancel deduplication

[fix] : still check dup even if the value is generated by incrservice

---

pkg/pb/statsinfo/shuffle.go
pkg/sql/plan/shuffle_test.go
pkg/sql/plan/stats.go

issue # https://github.com/matrixorigin/MO-Cloud/issues/3678
release unused memory in shuffleRange

cp to 1.2-dev "release unused memory in shuffleRange"

---

pkg/sql/compile/compile.go
pkg/sql/compile/debugTools.go
pkg/sql/compile/operator.go
pkg/sql/compile/remoterun.go
pkg/sql/compile/remoterunClient.go
pkg/sql/compile/remoterun_test.go
pkg/sql/compile/scope.go
pkg/sql/compile/scope_test.go
pkg/sql/compile/types.go
pkg/vm/pipeline/pipeline.go
pkg/vm/pipeline/types.go
pkg/vm/types.go
pkg/vm/vm.go

issue #https://github.com/matrixorigin/matrixone/issues/16727
make scope.Instructions as tree, not array any more

fix: scope.instruction as tree

---

pkg/fileservice/s3_fs.go

issue #17396 
fileservice: set finalizer on read closer to avoid potential leaks

fileservice: set finalizer on read closer to avoid potential leaks

---

pkg/sql/plan/apply_indices.go

issue https://github.com/matrixorigin/MO-Cloud/issues/3713
When main table has both filters and limit, we can't move limit to index table

[fix] don't push LIMIT clause to index table if main table has filters

---

pkg/vm/engine/tae/db/merge/executor.go
pkg/vm/engine/tae/db/merge/policyBasic.go

issue https://github.com/matrixorigin/matrixone/issues/17416
- using process memory to do control merge tasks, expecting better behavior in container
___
Enhancement
___
- Introduced process memory usage tracking using the `gopsutil` library to improve memory management for merge tasks.
- Replaced the `memSpare` variable with `memLimit` and `memUsing` to better reflect the new memory management strategy.
- Updated the logic for calculating memory limits, considering both container memory limits and host memory.
- Enhanced logging to include new memory metrics such as process memory limit and usage.
___
<tr>
<td>
<details> …

using process memory usage for background task memory throttle 1.2

---

pkg/fileservice/disk_cache.go
pkg/fileservice/disk_cache_test.go
pkg/fileservice/local_fs.go
pkg/fileservice/s3_fs.go

issue # https://github.com/matrixorigin/MO-Cloud/issues/3694
allow loading file infos asynchronously in disk cache

 fileservice: load disk cache file infos in parallel and asynchronously 

---

pkg/container/vector/vector.go
pkg/sql/colexec/semi/join.go
pkg/vm/engine/tae/blockio/read.go

issue # https://github.com/matrixorigin/matrixone/issues/16124
Reduce `mpool.Grow()` calls in `SEMI Join` and `TableScan` operators.
QPS of Vector Index KNN queries improved from 25 to 78 (5 concurrent clients)
Previous Profile
New Profile
___
Bug fix
___
- Added `PreExtendArea` function to the vector package to optimize memory pool and area expansion.
- Modified the SEMI Join operator to use `PreExtendArea` for better memory management.
- Updated `BlockReadInner` function to call `PreExtendArea` before performing union operations.
___
<tr>
<td>
<details>
<summary><strong>vector.go</strong><dd><code>Add `PreExtendArea` function to vector for memory …

[BugFix]: Reduce mp.Grow2 in SEMI Join and TableScan Operator

---

pkg/shardservice/service_read_test.go

issue #16683 
The rebalance schedules shards between service nodes randomly. The test cannot assume that shard1 is in service1

fix TestReadWithSpecialShard

---

pkg/sql/colexec/filter/filter.go

issue #https://github.com/matrixorigin/matrixone/issues/16994
when filter expo is nil, return children call's result in advance

improvement when filter expr is nil

---

pkg/fileservice/bytes.go
pkg/fileservice/io_entry.go
pkg/fileservice/local_fs.go
pkg/fileservice/memorycache/data.go
pkg/fileservice/object_storage_metrics.go
pkg/fileservice/s3_fs.go
pkg/util/metric/v2/dashboard/grafana_dashboard_fs.go
pkg/util/metric/v2/fileservice.go
pkg/util/metric/v2/metrics.go

issue #17504 
replace existing write metrics with general metrics for all object storage operations.
fileservice: add metrics for object storage
fileservice: remove fsMallocLiveObjects, duplicated with malloc metrics
fileservice: add FSReadLocalCounter

fileservice, metric: various optimizations

---

pkg/sql/compile/scope.go
pkg/vm/process/process.go
pkg/vm/process/types.go

issue #16542 
remove useless data structure from proc, for furthur refactoring of proc and merge operator

remove useless data structure from proc

---

pkg/cnservice/server_heartbeat.go
pkg/cnservice/server_task.go
pkg/proxy/bootstrap.go
pkg/proxy/bootstrap_test.go
pkg/proxy/client_conn.go
pkg/proxy/config.go
pkg/proxy/conn_manager.go
pkg/proxy/handler.go
pkg/proxy/handler_test.go
pkg/proxy/router.go
pkg/proxy/router_test.go
pkg/proxy/server.go
pkg/proxy/server_conn_test.go
pkg/proxy/sql_worker.go
pkg/proxy/sql_worker_test.go

issue #16824
proxy get connection ids from backend servers rather than from conn manager

[bug] proxy: proxy get connection ids from backend servers

---

test/distributed/cases/function/table_func_metadata_scan.result
test/distributed/cases/function/table_func_metadata_scan.sql

issue # https://github.com/matrixorigin/MO-Cloud/issues/3777
sleep(1) before using metadata_scan to let results stable in table_func_metadata_scan.sql

fix: add sleep before using metadata_scan to let results stable in bvt

---

pkg/sql/compile/compile.go
pkg/sql/plan/shuffle.go

This reverts commit ea1f0db3d5999a28e0a1db352b90caeae6b3db62.
issue #https://github.com/matrixorigin/MO-Cloud/issues/3819 https://github.com/matrixorigin/matrixone/issues/17782
先revert引入问题的pr，再继续调查

Revert "fix unnecessary merge scope in broadcast join (#17778)"

---

pkg/container/types/packer.go
pkg/container/types/packer_test.go

issue # https://github.com/matrixorigin/MO-Cloud/issues/3815
Some packers may be used after Close. Make them work.

container/types: make empty Packer valid for use

---

optools/mo_checkin_regression/mo_checkin_regression_tke.yaml

issue #
Proxy module is not enabled in the MergeRun 1.2-dev before. This time, we need to add related content of the proxy module to use the proxy module in the MergeRun 1.2-dev.

Add proxy configurations for 1.2-dev

---

pkg/util/trace/impl/motrace/buffer_content.go
pkg/util/trace/impl/motrace/buffer_content_test.go

issue #https://github.com/matrixorigin/matrixone/issues/17893
1. add ut `TestContentBuffer_isEmpty` to fix empty buffer case.

bugfix: panic if ContentBuffer is empty.

---

optools/mo_checkin_regression/mo_checkin_regression_tke.yaml

Set content about the proxy module to use the proxy module in `MergeRun` process
issue #
Proxy module is not enabled in the `MergeRun` process before. This time, we need to add related content of the proxy module to use the proxy module in the `MergeRun` process.
___
___
- Added proxy configuration to the `mo_checkin_regression_tke.yaml` file to enable the proxy module in the `MergeRun` process.
- Configured nodeSelector and overlay settings specific to the proxy.
- Set resource requests and limits for the proxy.
- Enabled export to Prometheus for the proxy module.
___
<tr>
<td>
<details> …

Add proxy configurations

---

pkg/sql/compile/compile.go
pkg/sql/compile/debugTools.go

issue # https://github.com/matrixorigin/matrixone/issues/17905 https://github.com/matrixorigin/matrixone/issues/17915
当broadcast join的probe节点，所有pipeline都在remote CN上时，会有个bug导致build端节点丢失。
先fix这个导致build端丢失的bug。
另外还fix一个会导致external scan全部在remote CN上的bug

fix a bug that cause build scopes lost in broadcast join

---

pkg/sql/colexec/evalProjection.go
pkg/sql/colexec/join/join.go
pkg/sql/colexec/join/join_test.go
pkg/sql/colexec/join/types.go
pkg/vm/message/joinMapMsg.go

issue #
___
Enhancement
___
- Refactored `InnerJoin` struct to use a container struct instead of a pointer.
- Optimized initialization in the `Prepare` method to avoid redundant allocations.
- Updated `Call` and `build` methods to use a pointer to the container for consistency.
- Improved memory management in `Reset` and `Free` methods by cleaning up resources more effectively.
- Enhanced `cleanBatch` method to ensure proper batch cleanup.
___
<tr>
<td>
<details>
<summary><strong>join.go</strong><dd><code>Refactor InnerJoin methods for optimized initialization and pointer </code><br><code>usage</code></dd></summary>
<hr>
pkg/sql/colexec/join/join.go …

refactor Innerjoin

---

pkg/proxy/tunnel.go
pkg/proxy/tunnel_test.go
pkg/proxy/util.go

issue https://github.com/matrixorigin/matrixone/issues/17688
don't change txn status if it is error packet

[proxy] enhancement: don't change txn status if it is error packet

---

pkg/common/malloc/checked_allocator.go
pkg/common/malloc/closure_deallocator.go
pkg/common/malloc/config.go
pkg/common/malloc/stacktrace.go
pkg/common/malloc/stacktrace_test.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/3775 https://github.com/matrixorigin/MO-Cloud/issues/3882
stacktrace info in malloc package is using too much memory, reduce.

malloc: reduce memory usages of stacktrace

---

pkg/sql/compile/scope.go

issue #https://github.com/matrixorigin/matrixone/issues/18097
在改scope.instructions改为tree的commit的时候，修改newParallelScope函数，复制n条pipeline的时候，如果是dispatch和Connector，Output算子，不复制这个op， 接下来也不删除pipeline的最后一个op（之前是复制整个pipeline，然后删除最后一个op）， 这个issue insert pipeline 最上层op是insert， 所以insert op复制了，但是并没有删除最后一个op， 导致issue里面后台跑的insert into select到表里面的数据多了一份，走了两次insert write

fix: insert newParallelScope

---

pkg/sql/plan/stats.go

issue #https://github.com/matrixorigin/matrixone/issues/17991
修复计算runtime filter stats中的一处错误，会导致tp query会认定为ap query

fix a bug that cause wrong stats for runtime filter

---

pkg/embed/cluster_test.go

issue #18002 
enable ut TestMultiClusterCanWork and TestBaseClusterCanWorkWithNewCluster

enable ut TestMultiClusterCanWork and TestBaseClusterCanWorkWithNewCluster

---

pkg/container/vector/vector.go

issue #[(https://github.com/matrixorigin/matrixone/issues/18088)](https://github.com/matrixorigin/matrixone/issues/18088)
the `Intersection2Vector` may index out of range when merge reader filter.

fix filter Intersection2Vector

---

optools/mo_checkin_regression/mo_checkin_regression_tke.yaml

issue #
set CN max-active txn to 100.
In the CI environment, sometimes TPCC and mixed sysbench start to run at the same time. the default max-active txn is too small that it will take almost 10 mins before it starts to run.

Update checkin max-active to 100

---

pkg/shardservice/service_test.go

issue #17011
Fix ut. Make cn1 and cn2 shared committed tables. Avoid check table deleted checker triggered.

fix TestShardCanBeAllocatedToMultiCN

---

pkg/sql/plan/build_load.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/3924
buildload里面当文件大小比较小，设置parallel为false的代码，这段逻辑有两处一样的代码，所以在之前一个commit，就删掉了一处，删错了位置，因为原本删除的地方紧接着会marshal，encode这个字段，由于删除了，导致有种情况，encode的parallel为true，实际接下来buildload里面按照parallel为false处理的

fix: buildload

---

pkg/sql/compile/compile.go

issue #16542 
isEnd property is used for analyze. should not affect pipelines. remove this logic.

isEnd property should not affect pipelines

---

pkg/common/mpool/mpool.go

issue #18240 https://github.com/matrixorigin/MO-Cloud/issues/3928
At present, the problems of the mpool framework itself can lead to meaningless oom situations.

[fix] : remove meaningless panic of mpool.Alloc

---

pkg/fileservice/disk_cache.go
pkg/fileservice/s3_fs_test.go

issue # https://github.com/matrixorigin/matrixone/issues/18388 
more eviction

fileservice: do disk cache eviction after loading and before writing file

---

pkg/vm/engine/tae/db/gc/table.go

issue https://github.com/matrixorigin/matrixone/issues/18429
When the table is dropped, creatests is greater than snapshot ts and the objects of dropts will be incorrectly GCed

Fix snapshot refers

---

pkg/frontend/routine_manager.go

issue #18487 
fix delete routine log
在 KillRoutineConnections的地方已经kill connection了，如果后面deleteRoutine 的时候再获取connectionid就会panic
___
Bug fix
___
- Removed the logging of connection ID in the `deleteRoutine` function to prevent errors when the connection has already been killed.
- This change addresses issue #18487 by ensuring that accessing the connection ID after it has been killed does not cause errors.
___
<tr>
<td>
<details>
<summary><strong>routine_manager.go</strong><dd><code>Remove logging of connection ID in deleteRoutine</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pkg/frontend/routine_manager.go
<li>Removed …

fix delete routine log

---

pkg/frontend/authenticate.go
pkg/frontend/routine_manager.go

issue #18499 #18475
fix drop account error
drop account if not exists will post drop sys account request and add sys account to kill queue
___
Bug fix
___
- Fixed a bug in `doDropAccount` by adding a check to return an error if the account does not exist.
- Added a condition in `postDropSuspendAccount` to return an error if the account ID is zero.
- Removed unnecessary logging in `deleteRoutine` method of `AccountRoutineManager`.
___
<tr>
<td>
<details>
<summary><strong>authenticate.go</strong><dd><code>Add error checks in account drop logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

fix drop account error

---

pkg/fileservice/object_storage_semaphore.go

issue #17001 #17793 
acquire semaphore when doing List and Write to limit concurrent connections
___
Bug fix
___
- Added semaphore acquisition and release in the `List` method to limit concurrent connections and prevent potential blocking issues.
- Added semaphore acquisition and release in the `Write` method to ensure consistent handling of concurrent operations.
- These changes address issues #17001 and #17793 by ensuring that semaphore control is applied to operations that may block for a long time.
___
<tr>
<td>
<details>
<summary><strong>object_storage_semaphore.go</strong><dd><code>Add semaphore control to List and Write methods</code>&nbsp; &nbsp; …

fileservice: also acquire semaphore in List and Write

---

pkg/fileservice/local_fs.go
pkg/fileservice/s3_fs.go
pkg/frontend/mysql_cmd_executor.go
pkg/util/trace/impl/motrace/statistic/stats_array.go

issue https://github.com/matrixorigin/matrixone/issues/14926
fix IOAccessTimeConsumption Statistics Duplicate
___
Bug fix
___
- Fixed the duplication issue in IOAccessTimeConsumption statistics by relocating the recording logic in `local_fs.go` and `s3_fs.go`.
- Added comments to clarify the recording of diskIO and networkIO resources.
- Corrected the format of warning messages in `mysql_cmd_executor.go` for negative CPU calculations.
- Removed unused methods related to cache IO merger time consumption in `stats_array.go` and simplified the IO merger time consumption calculation.
___
<tr>
<td>
<details>
<summary><strong>local_fs.go</strong><dd><code>Fix and …

Io access time consumptionissue 1.2 dev

---

pkg/fileservice/io.go
pkg/fileservice/object_storage_semaphore.go
pkg/fileservice/s3_fs.go

issue https://github.com/matrixorigin/matrixone/issues/17001 https://github.com/matrixorigin/matrixone/issues/17793
fix object storage semaphore
___
___
- Added a new `readerFunc` type that implements the `io.Reader` interface to improve code modularity.
- Enhanced the `objectStorageSemaphore` to safely release resources using `sync.OnceFunc`, ensuring release on errors and closure.
- Increased the default concurrency limit for S3FS from 100 to 1024, allowing more concurrent operations.
___
<tr>
<td>
<details>
<summary><strong>io.go</strong><dd><code>Add `readerFunc` type implementing `io.Reader`</code>&nbsp; &nbsp; &nbsp; &nbsp; …

fileservice: fix object storage semaphore

---

pkg/util/trace/impl/motrace/report_statement.go
pkg/util/trace/impl/motrace/report_statement_test.go
test/distributed/cases/statement_query_type/aggr_error_stmt.result
test/distributed/cases/statement_query_type/aggr_error_stmt.sql
test/distributed/cases/zz_statement_query_type/aggr_error_stmt.result
test/distributed/cases/zz_statement_query_type/aggr_error_stmt.sql

Aggr statements with same error msg and keep the error msg info #18537
issue #https://github.com/matrixorigin/MO-Cloud/issues/4005
ref pr : #18537
changes:
- aggr erorr statement filter with same error msg.
___
___
- Enhanced error handling by retaining error messages in statement aggregation.
- Added a new `Error` field in the `Key` struct to include error messages.
- Implemented a function to convert error objects to strings for consistent key generation.
- Introduced comprehensive tests to verify the handling of error messages in statement keys.
- Added SQL test cases and expected results to validate the aggregation of error statements.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td>< …

Aggr statements with same error msg to keep error msg in 1.2-dev

---

pkg/proxy/tunnel.go
pkg/proxy/util.go
pkg/proxy/util_test.go

issue https://github.com/matrixorigin/MO-Cloud/issues/4022
there is no response from server after client send a COM_STMT_CLOSE cmd,
which will cause the session cannot be transferred forever. So ignore the
send time when client send a COM_STMT_CLOSE cmd.
___
Bug fix, Tests
___
- Fixed a bug where sessions did not transfer after a `COM_STMT_CLOSE` command by ignoring the send time for such commands.
- Introduced a buffer variable `tempBuf` to improve buffer handling.
- Added utility functions `isEmptyPacket` and `isDeallocatePacket` to identify packet types.
- Updated logic to conditionally set `lastCmdTime` based on packet type.
- Added unit tests for the new utility functions to ensure correct packet type identification.
___ …

[bug] proxy: session does not transfer after COM_STMT_CLOSE.

---

pkg/vm/engine/tae/db/test/db_test.go
pkg/vm/engine/tae/tables/base.go
pkg/vm/engine/tae/tables/jobs/flushTableTail.go

issue #15918
- Remove the panic check inside CheckFlushTaskRetry and collectDelsAndTransfer. It's safe to retry this task.
___
Bug fix
___
- Removed panic checks in `CheckFlushTaskRetry` and replaced them with safe return statements.
- Adjusted logic in `NewFlushTableTailTask` to handle non-appendable objects without panicking.
- Replaced panic with an error return in `collectDelsAndTransfer` to handle missing transfer mappings gracefully.
___
<tr>
<td>
<details>
<summary><strong>base.go</strong><dd><code>Remove panic checks in CheckFlushTaskRetry method</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

fix panic in ut

---

pkg/common/hashmap/inthashmap.go
pkg/common/hashmap/strhashmap.go
pkg/common/malloc/config.go
pkg/common/malloc/inuse_tracking_allocator.go
pkg/common/malloc/inuse_tracking_allocator_test.go
pkg/container/hashtable/int64_hash_map.go
pkg/container/hashtable/malloc.go
pkg/container/hashtable/malloc_test.go
pkg/container/hashtable/string_hash_map.go

issue #18150 
to ensure the hashtable is not allocating excessive memory.
___
___
- Added `HashmapSoftLimit` and `HashmapHardLimit` to the memory configuration to control memory usage.
- Introduced `InuseTrackingAllocator` to track and manage memory allocations with callbacks.
- Integrated memory limit checks in the hashtable allocator, including logging and panic mechanisms.
- Added unit, benchmark, and fuzz tests for the new allocator to ensure reliability and performance.
___
<tr>
<td>
<details>
<summary><strong>config.go</strong><dd><code>Add memory limit configurations for hashmaps</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

hashtable: add memory limit checks

---

pkg/vm/engine/disttae/db.go
pkg/vm/engine/disttae/stats.go
pkg/vm/engine/disttae/stats_test.go

issue https://github.com/matrixorigin/MO-Cloud/issues/4045
clear the tables in global stats when logtail re-connect.
___
Bug fix, Tests
___
- Added a `clearTables` method in `GlobalStats` to clear the tables in the map.
- Integrated the `clearTables` method into the engine initialization process to ensure tables are cleared in global stats when logtail reconnects.
- Added a unit test to verify the functionality of the `clearTables` method.
___
<tr>
<td>
<details>
<summary><strong>db.go</strong><dd><code>Clear tables in global stats during engine initialization</code></dd></summary>
<hr>
pkg/vm/engine/disttae/db.go
<li>Added a call to clear all tables in …

[bug] logtail: clear the tables in global stats when logtail re-connect

---

pkg/catalog/types.go
pkg/vm/engine/disttae/db.go
pkg/vm/engine/disttae/logtail.go
pkg/vm/engine/disttae/logtail_consumer.go
pkg/vm/engine/disttae/logtail_consumer_test.go

issue #18632 
The system must complete the catalog cache replay before it can process the push logtail for the three tables.
___
Bug fix, Tests
___
- Added a new function `IsSystemTable` to identify system tables by their ID.
- Enhanced the `setPushClientStatus` function to manage signaling for readiness and closing the signal channel when not ready.
- Implemented `tryWaitThreeTablesReplayReady` to handle the readiness check for logtail replay.
- Introduced a signal channel in `syncLogTailTimestamp` to notify when the log tail client is ready.
- Added a test `TestWait` to verify the behavior of the readiness function.
___
<tr>
<td>
<details> …

fix replay incomplete data to catalog cache

---

cmd/mo-service/config.go
pkg/fileservice/cache.go
pkg/fileservice/local_fs.go
pkg/fileservice/remote_cache_test.go
pkg/fileservice/s3_fs.go
pkg/fileservice/s3_fs_test.go

issue #18688 
fileservice: do not set default memory and disk config in setDefaults
___
___
- Removed default settings for memory and disk cache capacities to prevent unintended configurations.
- Introduced specific cache configurations for different file service names, enhancing flexibility and control.
- Improved conditional logic for initializing memory and disk caches across various file services.
- Updated tests to include explicit memory and disk capacity settings, ensuring accurate test conditions.
___
<tr>
<td>
<details>
<summary><strong>config.go</strong><dd><code>Refactor file service default cache …

mo-service: fix default cache configs

---

pkg/objectio/cache.go
pkg/objectio/constructors.go
pkg/objectio/funcs.go
pkg/objectio/meta_entry.go
pkg/objectio/types.go
pkg/vm/engine/disttae/datasource.go
pkg/vm/engine/disttae/tombstones.go
pkg/vm/engine/tae/blockio/read.go
pkg/vm/engine/tae/logtail/backup.go
pkg/vm/engine/tae/logtail/snapshot.go

issue #18432 
Prev:
Now:
___
enhancement
___
- Optimized metadata cache access by using the `MustObjectMeta` function, reducing heap allocations.
- Introduced the `MustObjectMeta` function for safer and more efficient metadata handling, with validation checks.
- Defined a new `ObjectMeta` type with methods for accessing and manipulating metadata, replacing the previous interface.
- Removed the `ObjectMeta` interface definition, simplifying the code structure.
___
<tr>
<td>
<details>
<summary><strong>cache.go</strong><dd><code>Optimize metadata cache access by using MustObjectMeta</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pkg/objectio/cache.go …

avoid metadata cache access heap allocation

---

pkg/util/metric/v2/dashboard/grafana_dashboard_logtail.go
pkg/util/metric/v2/logtail.go
pkg/util/metric/v2/metrics.go
pkg/vm/engine/tae/logtail/mgr.go
pkg/vm/engine/tae/logtail/reader.go
pkg/vm/engine/tae/logtail/table.go
pkg/vm/engine/tae/options/types.go

issue https://github.com/matrixorigin/MO-Cloud/issues/3925
Add summary to speed up scanning txn during pull logtail
___
enhancement
___
- Added a `skipFn` function in `reader.go` to filter blocks based on the presence of summaries, optimizing the scanning process during logtail operations.
- Enhanced the `summary` struct in `table.go` by introducing a `tids` map to track table IDs, improving the efficiency of transaction block summaries.
- Updated the `DefaultLogtailTxnPageSize` in `types.go` from 100 to 256 to accommodate larger transaction pages.
___
<tr>
<td>
<details>
<summary><strong>reader.go</strong><dd><code>Add block filtering logic in logtail …

add summary for txnBlock(1.2-dev only)

---

pkg/sql/plan/build_dml_util.go
test/distributed/cases/dml/select/select.result
test/distributed/cases/dml/select/select.test

bug fix: unique key/secondary key get incorrect value
Approved by: @heni02, @badboynt1, @aunjgr
issue https://github.com/matrixorigin/MO-Cloud/issues/4059
bug fix: unique key/secondary key get incorrect value
___
Bug fix, Tests
___
- Fixed a bug where unique and secondary keys were getting incorrect values by simplifying the logic for computing primary key positions.
- Removed unnecessary map creation and redundant loops to improve code efficiency.
- Added new test cases to verify the correctness of queries involving composite primary keys.
___
<tr>
<td>
<details>
<summary><strong>build_dml_util.go</strong><dd><code>Simplify primary key position computation …

bug fix: unique key/secondary key get incorrect value (#18711)

---

pkg/bootstrap/versions/upgrade_strategy.go
pkg/bootstrap/versions/upgrade_tenant_task.go
pkg/bootstrap/versions/version.go
pkg/bootstrap/versions/version_upgrade.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/4067
Method for reading query results during upgrade modification
Change from `UnsafeStringAt()` to call `GetStringAt()`
___
Bug fix
___
- Replaced `UnsafeGetStringAt` with `GetStringAt` across multiple files for safer string retrieval.
- Improved safety in handling query results during upgrade modifications.
- Addressed issue #4067 by ensuring safer string operations in various functions.
___
<tr>
<td>
<details>
<summary><strong>upgrade_strategy.go</strong><dd><code>Replace Unsafe String Retrieval with Safe Method</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

Method for reading query results during upgrade modification

---

pkg/sql/plan/message.go

issue #17367 
support order by limit optimization for non-sorted columns
___
enhancement
___
- Removed a condition in the `handleMessgaeFromTopToScan` function that checked the sort order of a column, optimizing the order by limit for non-sorted columns.
- Simplified the logic for processing messages in the query plan, potentially improving performance.
___
<tr>
<td>
<details>
<summary><strong>message.go</strong><dd><code>Optimize order by limit for non-sorted columns</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pkg/sql/plan/message.go
<li>Removed a condition that checks the sort order of a column …

support order by limit optimization for non-sorted columns

---

pkg/sql/colexec/deletion/types.go

issue # https://github.com/matrixorigin/MO-Cloud/issues/4050
update delete flushThreshold
___
Bug fix
___
- Updated the `flushThreshold` value in `pkg/sql/colexec/deletion/types.go` from 32 MB to 5 MB to address a bug.
- This change is necessary to fix issue #4050 in the MO-Cloud repository.
___
<tr>
<td>
<details>
<summary><strong>types.go</strong><dd><code>Update `flushThreshold` value in deletion types</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pkg/sql/colexec/deletion/types.go
- Updated the `flushThreshold` value from 32 MB to 5 MB.
</details>
</td>
<td><a …

update delete flushThreshold

---

pkg/vm/engine/tae/catalog/object.go
pkg/vm/engine/tae/catalog/table.go
pkg/vm/engine/tae/db/dbutils/runtime.go
pkg/vm/engine/tae/db/merge/scheduler.go
pkg/vm/engine/tae/db/open.go
pkg/vm/engine/tae/db/test/db_test.go
pkg/vm/engine/tae/options/options.go
pkg/vm/engine/tae/options/types.go
pkg/vm/engine/tae/rpc/handle.go
pkg/vm/engine/tae/rpc/handle_2pc.go
pkg/vm/engine/tae/tables/jobs/mergeobjects.go
pkg/vm/engine/tae/tables/txnentries/mergeobjects.go

issue #18286
- If a large delete txn occurs, attempt to stop merging on this table to prevent intensive delete transfer
- Fix a rollback bug leading to duplicate ObjectEntry
___
enhancement
___
- Introduced `LockMergeService` to manage table locks, preventing merge operations during intensive delete transactions.
- Added methods to lock and unlock tables, with a pruning mechanism for stale locks.
- Integrated locking mechanism into various components to control merge operations based on lock status.
- Implemented logic to lock tables during bulk delete operations and release locks after transaction commits.
- Added configuration constants for bulk tombstone transaction threshold and lock merge prune interval.
___ …

add lockmerge to prevent intensive transfer

---

pkg/sql/colexec/hashbuild/build.go
pkg/sql/colexec/hashbuild/types.go
test/distributed/cases/dml/delete/delete.result
test/distributed/cases/dml/delete/delete.test

issue #https://github.com/matrixorigin/MO-Cloud/issues/4049
cp to 1.2-dev 'fix a bug that cause hashmap data wrong'
___
Bug fix, Tests
___
- Fixed a bug in the hashmap data handling by introducing a `needDupVec` flag to manage vector duplication when evaluating join conditions.
- Enhanced the `container` struct to include logic for freeing duplicated vectors, ensuring proper memory management.
- Added new test cases to verify the delete operation on a newly created table `t3`, ensuring the correctness of the delete functionality.
___
<tr>
<td>
<details>
<summary><strong>build.go</strong><dd><code>Fix hashmap data issue by handling vector …

cp to 1.2-dev 'fix a bug that cause hashmap data wrong'

---

cmd/mo-service/debug.go
pkg/common/malloc/default.go

issue #18096
pprof: dump malloc profile
___
Enhancement
___
- Added functionality to dump malloc profiles in the `cmd/mo-service/debug.go` file.
- Introduced a new function `saveMallocProfile` to handle the dumping of malloc profiles.
- Integrated the malloc profile dumping process into the existing `saveProfiles` function.
- Implemented `WriteProfileData` function in `pkg/common/malloc/default.go` to facilitate writing malloc profile data.
___
<tr>
<td>
<details>
<summary><strong>debug.go</strong><dd><code>Add malloc profile dumping functionality</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

[tech] pprof: dump malloc profile

---

pkg/vm/engine/tae/logtail/mgr.go
pkg/vm/engine/tae/logtail/reader.go
pkg/vm/engine/tae/logtail/table.go
pkg/vm/engine/tae/options/types.go

issue https://github.com/matrixorigin/MO-Cloud/issues/3925
Add summary to speed up scanning txn during pulling logtail
___
enhancement
___
- Enhanced the logging in the `GCByTS` function to include the count of remaining blocks after garbage collection.
- Optimized the `GetDirtyByTable` method by adding a skip function to avoid processing blocks without relevant table IDs.
- Introduced a `tids` map in the `summary` struct to track table IDs, and updated the `trySumary` method to populate this map.
- Increased the default transaction page size from 100 to 256 to improve performance.
___
<tr>
<td>
<details>
<summary><strong>mgr.go</strong><dd><code>Improve …

add summary for txnBlock

---

pkg/sql/colexec/aggexec/concat.go

https://github.com/matrixorigin/MO-Cloud/issues/4084
移除了group_concat每行结果不能超过1024的限制
___
Bug fix
___
- Removed the 1024-byte length limit for each row content in the `group_concat` function, allowing for longer concatenated strings.
- Simplified the code by removing unnecessary checks related to the previous length limit.
___
<tr>
<td>
<details>
<summary><strong>concat.go</strong><dd><code>Remove length limit for group_concat results</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pkg/sql/colexec/aggexec/concat.go
<li>Removed the 1024-byte length limit for <code>group_concat</code> …

remove the 1024bytes limit for group_concat result.

---

pkg/incrservice/column_cache.go
pkg/txn/client/operator.go
pkg/txn/client/operator_test.go

issue [#4083](https://github.com/matrixorigin/MO-Cloud/issues/4083)
add support rollback running txn
___
___
- Simplified the `close` method in `column_cache.go` by removing the locking mechanism and returning `nil`.
- Introduced a `runningSQL` atomic boolean in `operator.go` to track the execution state of SQL transactions.
- Enhanced `Commit` and `Rollback` methods to prevent operations if SQL is currently running.
- Updated `EnterRunSql` and `ExitRunSql` methods to modify the `runningSQL` state.
- Added comprehensive tests in `operator_test.go` to verify the new behavior of transaction operators, including checks for running SQL, lock skipping, and lock table presence.
___ …

add support rollback running txn to 1.2

---

pkg/proxy/tunnel.go
pkg/proxy/tunnel_test.go
pkg/proxy/util.go
pkg/proxy/util_test.go

issue https://github.com/matrixorigin/mo-cloud/issues/4088
In the case of "load data local infile" statement, client sends the
first packet, then server sends response, which is "0xFB + filename",
after that, client sends content of filename and an empty packet, at
last, server sends OK packet. The sequence ID of this OK packet is not
1, and will cause the session cannot be transferred after this stmt finished.
So, the solution is: when server sends 0xFB and the sequence ID of
next packet is 3 bigger than last one, the next packet MUST be an
OK packet, and the transfer is allowed.
___
Bug fix, Tests
___
- Fixed a bug where session transfer was not possible after executing "load data local infile" due to incorrect sequence ID handling.
- Introduced a new logic to determine when a session …

[bug] proxy: session cannot be transferred after load data local infile

---

pkg/vm/engine/tae/logstore/driver/logservicedriver/info.go
pkg/vm/engine/tae/logstore/driver/logservicedriver/truncate.go
pkg/vm/engine/tae/logstore/store/checkpoint.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/4098
1. fix range checkpoint
2. add log
___
___
- Improved synchronization and LSN management in `driverInfo` by adjusting mutex usage and adding removal of log service LSN range.
- Enhanced logging and added detailed metrics for the truncation process in `LogServiceDriver`, including loop count and duration.
- Added logging with timing metrics for checkpoint operations in `StoreImpl`, improving visibility into checkpoint and truncation processes.
- Improved logging format across modified files using `zap` for better clarity and consistency.
___
<tr>
<td>
<details> …

fix range checkpoint

---

pkg/vm/engine/tae/txn/txnimpl/base_table.go
pkg/vm/engine/tae/txn/txnimpl/table.go

issue #18432 
improve incremental dedup
___
Enhancement
___
- Introduced `snapshotTS` to optimize deduplication logic in `base_table.go` and `table.go`.
- Added conditions to skip processing of objects deleted before `snapshotTS`.
- Refactored deduplication checks to use `snapshotTS` for improved efficiency.
___
<tr>
<td>
<details>
<summary><strong>base_table.go</strong><dd><code>Optimize deduplication logic with snapshot timestamp</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pkg/vm/engine/tae/txn/txnimpl/base_table.go
<li>Introduced <code>snapshotTS</code> to optimize deduplication logic.<br> <li> Added condition to skip processing of …

Improve incremental dedup 2

---

pkg/sql/compile/compile.go
pkg/sql/compile/scope.go
pkg/sql/compile/types.go
pkg/vm/engine/disttae/tools.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/4107
make query with limit run in single parallel
___
enhancement
___
- Introduced a `hasLimit` flag in the `Source` struct to optimize query execution when `OrderBy` or `Limit` is present.
- Modified the `DetermineRuntimeDOP` function to adjust CPU usage based on the presence of query limits.
- Updated the logic for distributing blocks to block readers to handle single reader scenarios more effectively.
___
<tr>
<td>
<details>
<summary><strong>compile.go</strong><dd><code>Add `hasLimit` flag for query optimization</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

make query with limit run in single parallel

---

pkg/lockservice/lock_table_allocator.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/4056
fix using too much memory to store orphan txns
___
___
- Removed the `disconnectAt` mechanism and replaced it with an `inactiveService` map to better manage inactive services.
- Enhanced logging to provide more detailed information about service state changes and retry attempts.
- Improved the logic for cleaning up commit states and handling inactive services, reducing memory usage.
- Fixed potential issues with retry logic when checking if a service is alive.
___
<tr>
<td>
<details>
<summary><strong>lock_table_allocator.go</strong><dd><code>Optimize memory usage and enhance …

fix using too much memory to store orphan txns

---

etc/launch-dynamic-cn/cn.toml.base
etc/launch-dynamic-with-proxy/cn.toml.base
etc/launch-multi-cn/cn1.toml
etc/launch-multi-cn/cn2.toml
etc/launch-tae-compose/config/cn-0.toml
etc/launch-tae-compose/config/cn-1.toml
etc/launch-with-proxy/cn1.toml
etc/launch-with-proxy/cn2.toml
etc/launch-with-python-udf-server/cn.toml
etc/launch/cn.toml
pkg/config/configuration.go

issue #18877
set default value of kek
___
Enhancement
___
- Set a default value for `KeyEncryptionKey` in the `SetDefaultValues` function of `FrontendParameters` if it is not already set.
- Removed hardcoded `key-encryption-key` from various configuration files to ensure the default value is used.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>1 files</summary><table>
<tr>
<td>
<details>
<summary><strong>configuration.go</strong><dd><code>Set default value for KeyEncryptionKey in configuration</code>&nbsp; &nbsp; </dd></summary>
<hr>
pkg/config/configuration.go
<li>Set a default value for <code>KeyEncryptionKey</code> if it is not already set.<br>
</details>
</td>
<td><a …

set default value of kek

---

pkg/common/malloc/profiler.go

issue #18896 
refine malloc profiles and tests

malloc: refinements

---

pkg/sql/colexec/aggexec/aggResult.go
pkg/sql/colexec/aggexec/concat.go

issue #17518 
https://github.com/matrixorigin/MO-Cloud/issues/4092
修复了一个agg的bytes结果进行append时会覆写到其他group结果的bug.
修复了group_concat进行merge时没有更新null值位图的错误。
___
Bug fix
___
- Fixed a bug in `aggFuncBytesResult` where returning the source pointer directly could cause memory contamination.
- Enhanced the `groupConcatExec` to correctly handle empty groups during merging and simplified error handling.
- Removed unnecessary parameter usage in several methods to improve code clarity.
___
<tr>
<td>
<details>
<summary><strong>aggResult.go</strong><dd><code>Fix memory contamination in aggFuncBytesResult</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

[pick to 1.2] fix Agg bug will cause memory contamination.

---

pkg/taskservice/mysql_task_storage.go
pkg/taskservice/mysql_task_storage_test.go
pkg/taskservice/task_service_holder_test.go

issue #18472
check error_msg is valid before converting it to string.

check msgOption is Valid before convert it to msg

---

pkg/sql/plan/build_test.go
pkg/sql/plan/visit_plan.go
pkg/sql/plan/visit_plan_rule.go
test/distributed/cases/pessimistic_transaction/prepare.result
test/distributed/cases/pessimistic_transaction/prepare.sql

Fix bug: prepare for on duplicate key can not get Parameter
Approved by: @heni02, @badboynt1
issue #18957
Fix bug: prepare for on duplicate key can not get Parameter

Fix bug: prepare for on duplicate key can not get Parameter (#18995)

---

pkg/container/batch/batch.go
pkg/objectio/const.go
pkg/objectio/constructors.go
pkg/objectio/versions.go
pkg/vm/engine/disttae/datasource.go
pkg/vm/engine/disttae/reader.go
pkg/vm/engine/disttae/txn_table.go
pkg/vm/engine/disttae/types.go
pkg/vm/engine/tae/blockio/funcs.go
pkg/vm/engine/tae/blockio/read.go
pkg/vm/engine/tae/db/test/db_test.go

issue #18432 
hack column data unmarshal from cache to avoid heap allocation

hack column data unmarshal from cache to avoid heap allocation

---

optools/mo_checkin_regression/mo_checkin_regression_tke.yaml

issue #
This yaml is compatible with the current operator version, but cannot be collected using conntrack. The operator needs to be upgraded to support it. It will be fine after this PR https://github.com/matrixorigin/ops/pull/328
___
enhancement, tests
___
- Enhanced the YAML configuration by adding `initContainers` to install necessary packages like `iptables` and `conntrack`.
- Introduced security capabilities `NET_ADMIN` and `SYS_ADMIN` to the `initContainers` for better network management.
- Updated the `mainContainerSecurityContext` to include additional capabilities `NET_ADMIN` and `NET_RAW`.
- Added a `semanticVersion` field to specify the version as `1.3.0`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong> …

CI: add capabilities to cn pod and init conntrack collect

---

optools/mo_checkin_regression/mo_checkin_regression_tke.yaml

issue #
This yaml is compatible with the current operator version, but cannot be collected using conntrack. The operator needs to be upgraded to support it. It will be fine after this PR https://github.com/matrixorigin/ops/pull/328
___
tests, enhancement
___
- Added an `initContainers` section to the YAML configuration to enable conntrack, which includes installing `iptables` and `conntrack`.
- Configured security context capabilities for the init container to allow network administration tasks.
- Updated the main container's security context to include additional capabilities (`NET_ADMIN` and `NET_RAW`) necessary for the changes.
___
<tr>
<td>
<details> …

CI: modify mo-checkin yaml for  1.2-dev

---

pkg/sql/colexec/join_util.go

issue #19054 
optimize memory allocation in hash build operator by preallocate buffer

optimize memory allocation in hash build operator by preallocate buffer

---

test/distributed/cases/zz_statement_query_type/aggr_error_stmt.result
test/distributed/cases/zz_statement_query_type/aggr_error_stmt.sql

issue # https://github.com/matrixorigin/matrixone/issues/18793
ref: https://github.com/matrixorigin/matrixone/pull/18796
fix bvt: sum(aggr_count) need consider aggr_count eq 0

fix bvt: sum(aggr_count) need consider aggr_count eq 0 in 1.2-dev

---

pkg/sql/colexec/aggexec/aggResult.go

issue #19054 
move vector in agg  operator from go heap to offheap

move vectors from go heap to offheap

---

pkg/container/pSpool/copy.go

issue #19054 
move vectors in spool from go heap to offheap

move vectors in spool from go heap to offheap

---

pkg/pb/statsinfo/shuffle.go

This reverts commit 9e65c7d99c93c180b32c9f6a69888212a872117d.
issue #https://github.com/matrixorigin/MO-Cloud/issues/4196
Revert "fix shufflerange miss strvalue (#19083)"

Revert "fix shufflerange miss strvalue (#19083)"

---

pkg/logservice/client_test.go
pkg/logservice/service.go
pkg/logservice/service_commands_test.go
pkg/logservice/service_test.go
pkg/logservice/test_utils.go

issue #19129
add retry if ut failed as port is inuse

[enhancement] logservice: add retry if ut failed as port is inuse

---

pkg/logservice/service_commands_test.go
pkg/logservice/store.go
pkg/logservice/store_hakeeper_check_test.go
pkg/logservice/store_metadata_test.go
pkg/logservice/store_test.go

issue #19180 
add retry if port is inuse for store instance

[enhancement] logservice: add retry if port is inuse for store instance

---

pkg/container/vector/vector.go
pkg/container/vector/vector_test.go
pkg/sql/plan/function/list_operator.go
test/distributed/cases/dml/select/select.result
test/distributed/cases/dml/select/select.test

fix bug: SortAndCompact get incorrect value
Approved by: @aunjgr, @aressu1985, @m-schen
issue https://github.com/matrixorigin/MO-Cloud/issues/4215
fix bug: SortAndCompact get incorrect value

fix bug: SortAndCompact get incorrect value (#19056)

---

pkg/frontend/server.go
pkg/proxy/client_conn.go
pkg/proxy/client_conn_test.go
pkg/proxy/event_test.go
pkg/proxy/handler_test.go
pkg/proxy/rebalancer_test.go
pkg/proxy/router_test.go
pkg/proxy/server.go
pkg/proxy/server_conn.go
pkg/proxy/server_conn_test.go

issue #https://github.com/matrixorigin/matrixone/issues/19269
https://github.com/matrixorigin/matrixone/issues/18673
https://github.com/matrixorigin/matrixone/issues/18671
问题：proxy 启动失败
原因：proxy service 变量初始化失败。之前跑ci regression时，失败了。但是网页下载没有mo日志。错误认为时资源不足的问题。
修改：按照逻辑每个serviceid 都会至多初始化一次变量。

fix proxy new connection failed

---

test/distributed/cases/zz_statement_query_type/aggr_error_stmt.result
test/distributed/cases/zz_statement_query_type/aggr_error_stmt.sql

issue #https://github.com/matrixorigin/matrixone/issues/19287
1. stable the bvt run result, by ignoring the aggr-merged statement column

fix bvt: remove 'group by statement', caused by merged-record statement column

---

test/distributed/cases/function/builtin.result
test/distributed/cases/function/builtin.sql

issue #https://github.com/matrixorigin/MO-Cloud/issues/4223
the behaviour of mo_table_size, rows not change, remove the redundant bvt case

remove redundant mo_table_size, rows bvt case

---

pkg/frontend/mysql_cmd_executor.go

issue # https://github.com/matrixorigin/matrixone/issues/19368
binary execute 上次重构后，不重新build，execute.stmt放的是prepareStmt, 本issue，在executeStmt里面拿ExecLocation拿的是prepare stmt的，本issue prepare是alterccount的，拿到的是EXEC_IN_FRONTEND，本来execute语句应该是EXEC_IN_ENGINE，导致走了EXEC_IN_FRONTEND的流程

fix: binary execute bug

---

pkg/frontend/mysql_cmd_executor.go
pkg/frontend/util.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/4254
ref: https://github.com/matrixorigin/matrixone/pull/19369
1. log the query's statement and error info, while panic-catch at `ExecRequest` func.

Fix panic cause miss stmt info and log in 1.2

---

pkg/sql/colexec/external/external.go
pkg/sql/colexec/external/types.go
pkg/sql/plan/build_load.go
pkg/sql/util/csvparser/csv_parser.go
pkg/sql/util/csvparser/csv_parser_test.go

issue # https://github.com/matrixorigin/matrixone/issues/18807
scancsvfile,里面每次最多读8092行，下面再读，复用上次的record row

scancsvfile memory reuse

---

pkg/incrservice/store_sql.go
pkg/pb/txn/txn_option.go
pkg/txn/client/client.go
pkg/txn/client/client_test.go
pkg/txn/client/operator.go
pkg/util/executor/options.go

issue #19394
Fix hung.  Consider the following timing:
1. logtail paused
2. cancel all active pipelines
3. reset logtail state to normal
When a pipeline in 2 is executing and a new transaction is opened in another goroutine to do something (e.g., update the cache of a auto-increment), the new transaction is blocked until the logtail state returns to normal. This creates a circular wait.

make txn do not wait in incrservice while the logtail is paused 

---

pkg/incrservice/store_sql.go
pkg/pb/txn/txn_option.go
pkg/txn/client/client.go
pkg/txn/client/client_test.go
pkg/txn/client/operator.go
pkg/util/executor/options.go

issue #19394 
Fix hung. Consider the following timing:
logtail paused
cancel all active pipelines
reset logtail state to normal
When a pipeline in 2 is executing and a new transaction is opened in another goroutine to do something (e.g., update the cache of a auto-increment), the new transaction is blocked until the logtail state returns to normal. This creates a circular wait.

make txn do not wait in incrservice while the logtail is paused to 1.2

---

pkg/taskservice/mysql_task_storage_test.go

issue #https://github.com/matrixorigin/matrixone/issues/19445
fix TestDaemonTaskInSqlMock FAIL in Matrixone Utils CI  ut-test
___
Bug fix
___
- Fixed a bug in the `TestDaemonTaskInSqlMock` test by adding error handling for the `storage.Close()` operation.
- Ensured that the test properly checks for errors when closing the storage to prevent test failures.
___
<tr>
<td>
<details>
<summary><strong>mysql_task_storage_test.go</strong><dd><code>Add error handling for storage closure in test</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pkg/taskservice/mysql_task_storage_test.go
<li>Added a check to ensure …

fix TestDaemonTaskInSqlMock FAIL

---

pkg/vm/engine/tae/db/test/db_test.go

issue #19248
extend timeout for global checkpoint execution

Fix globalCheckpoint5 timeout

---

pkg/sql/util/csvparser/csv_parser.go
pkg/sql/util/csvparser/csv_parser_test.go

issue # https://github.com/matrixorigin/matrixone/issues/18807
去掉csvparse readRecord函数返回值导致的内存消耗

refactor: reduce memory use in csvparse readReocrd

---

pkg/fileservice/object_storage_arguments.go
pkg/fileservice/object_storage_arguments_test.go

issue #19488 
try to extract region from endpoint if not provided

fileservice: try to extract region from endpoint in QCloud SDK

---

pkg/sql/plan/visit_plan_rule.go
test/distributed/cases/prepare/prepare.result
test/distributed/cases/prepare/prepare.test

issue # https://github.com/matrixorigin/matrixone/issues/19512
execute insert的时候也需要检查prepare plan的table有没有发生变化

fix: execute insert panic after change table

---

pkg/sql/compile/compile.go

issue #19524
Delay opening the three tables until the Run phase to avoid inconsistent partition states, which may temporarily result in missing data.

fix deleteTable panic due to incosistent partition states

---

pkg/sql/plan/utils.go

issue #19678 
Reverts matrixorigin/matrixone#19666

Revert "not fold prepare parameter twice"

---

pkg/vm/engine/disttae/engine.go
pkg/vm/engine/disttae/logtail_consumer.go
pkg/vm/engine/disttae/logtail_consumer_test.go
pkg/vm/engine/disttae/stats.go
pkg/vm/engine/disttae/stats_test.go

issue #19653
do not unsubscribe table before it finished waited, otherwise,
it will never stop waiting for the table's first logtail as it is subscribed.

[bug] logtail/stats: do not unsubscribe table before it finished waited

---

pkg/lockservice/rpc.go

issue #19762
Fix lockservice dead lock with txn . Use separate goroutines handle getActiveTxns

fix lockservice dead lock with txn

---

etc/launch-tae-compose/config/cn-0.toml
etc/launch-tae-compose/config/cn-1.toml
etc/launch-tae-compose/config/log.toml
etc/launch-tae-compose/config/tn.toml
optools/images/Dockerfile

issue #19856
reduce the upper limit of hard disk cache to avoid insufficient disk space of minio

CI: reduce disk cache for 2.0-dev

---

pkg/common/mpool/mpool.go
pkg/common/mpool/mpool_test.go

issue #18862
Invalid alloc size is a bad error message.  Message changed to "memory allocation exceed limit with requested size.."

[Bug]: use load_file() function to load stage data, mo report 'ERROR 20101 (HY000): internal error: Invalid alloc size 7775731712

---

pkg/catalog/types.go
pkg/vm/engine/disttae/engine.go
pkg/vm/engine/disttae/local_disttae_datasource.go
pkg/vm/engine/disttae/logtailreplay/partition_state.go
pkg/vm/engine/disttae/txn_database.go
pkg/vm/engine/disttae/util.go
pkg/vm/engine/engine_util/datasource.go
pkg/vm/engine/tae/logtail/backup.go
pkg/vm/engine/test/disttae_engine_test.go
pkg/vm/engine/types.go

issue #15431 #19787
- open the three tables like a normal table, sharing the benefits of cache in a txn

refactor: remove openSysTable 2.0

---

pkg/sql/plan/function/list_builtIn.go
pkg/sql/plan/utils.go
test/distributed/cases/optimizer/pushdown.result
test/distributed/cases/optimizer/pushdown.test

…(#19922)
support pushdown cast expression to block filters for date time type
Approved by: @m-schen, @heni02, @ouyuanning
issue #https://github.com/matrixorigin/MO-Cloud/issues/2761
cherry pick 'support pushdown cast expression to block filters for date time type'

cherry pick 'support pushdown cast expression to block filters for date time type'

---

pkg/frontend/authenticate.go
pkg/frontend/authenticate_test.go
pkg/frontend/back_exec.go
pkg/frontend/compiler_context.go
pkg/frontend/mysql_buffer.go
pkg/frontend/mysql_cmd_executor.go
pkg/frontend/mysql_cmd_executor_test.go
pkg/frontend/mysql_protocol.go
pkg/frontend/mysql_protocol_test.go
pkg/frontend/publication_subscription.go
pkg/frontend/query_result_test.go
pkg/frontend/session.go
pkg/frontend/test/Makefile
pkg/frontend/txn.go
pkg/frontend/txn_test.go
pkg/frontend/types.go
pkg/frontend/variables.go

issue #https://github.com/matrixorigin/matrixone/issues/19589
https://github.com/matrixorigin/matrixone/issues/18601
https://github.com/matrixorigin/matrixone/issues/19764
1, 处理rollback,commit,new txn,IncrStatementID,RollbackLastStatement的接口panic
2, 复用txnop的对象。每个前台session只创建一次。
3,
原因：parseStmtExecute可能返回error了。导致prepareStmt为nil. 从prepareStmt取值放到了err判断之前。
修改：从prepareStmt取值放到了err判断之后。
4,
-  修改recover捕获后，err被吞了。
-  修改lint的recover加错的白名单。
5, 改进 后台sql的执行。

cherry-pick: couple of updates

---

pkg/sql/colexec/external/external.go
pkg/sql/colexec/external/external_test.go

issue # https://github.com/matrixorigin/matrixone/issues/20002
load data local infile, 导入一个不存在的压缩文件，在external算子里面直接返回EOF导致panic

fix: load data local infile with compress file which does not exists

---

pkg/sql/plan/function/func_unary.go
pkg/sql/plan/function/function_id.go
pkg/sql/plan/function/list_builtIn.go
test/distributed/cases/function/func_crc32.result
test/distributed/cases/function/func_crc32.sql

https://github.com/matrixorigin/matrixone/issues/20121
支持crc32函数，参数为字符串类型，返回值为uint32。
该函数不支持参数的自动隐式类型转换。

Support Crc32(string-type) function.

---

pkg/sql/plan/bind_insert.go
pkg/sql/plan/build.go
pkg/sql/plan/opt_misc.go
pkg/sql/plan/types.go
pkg/sql/plan/utils_test.go

issue #15768 
add a hint in optimizer to skip dedup
set session optimizer_hints="skipDedup=1";

add a hint in optimizer to skip dedup

---

pkg/sql/plan/bind_delete.go
pkg/sql/plan/build_util.go

issue #20066 
fix bug: wrong lock type in some case。
因为旧的DML一个lock_op只有一个target，新的dml可能会有很多个，当主表是要上表锁的时候，unique key表也应该上表锁，上行锁的话会影响性能

fix bug: wrong lock type in some case

---

pkg/fileservice/http_client.go
pkg/fileservice/http_client_test.go

issue #20129 
set global HTTP default client to avoid excessive connections

fileservice: set global default http client

---

pkg/sql/compile/pub_sub.go
pkg/sql/compile/pub_sub_test.go

issue #20161
fix: skip all system dbs when update pub table list

fix: skip all system dbs when update pub table list

---

pkg/frontend/back_exec.go
pkg/frontend/session.go
pkg/frontend/txn.go
pkg/frontend/types.go

issue #https://github.com/matrixorigin/matrixone/issues/20076
对于max active = 1的测试情况。
原因：用户登录验证时的事务被判定成了非 user txn事务。导致新用户还能登录上，出了一些奇怪的情况。
修改：用户登录验证时的事务改为user txn事务。受max active 的限制。

enable login max-active limit

---

pkg/common/system/system.go
pkg/common/system/system_test.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/4486
cherry-pick: https://github.com/matrixorigin/matrixone/pull/20365
fix calling system.SetGoMaxProcs(0), should store the return value of `runtime.GOMAXPROCS(n)`

fix system.SetGoMaxProcs(0) case in 2.0-dev

---

pkg/common/system/system.go
pkg/common/system/system_test.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/4486
fix calling system.SetGoMaxProcs(0), should store the return value of `runtime.GOMAXPROCS(n)`

fix system.SetGoMaxProcs(0) case

---

pkg/sql/plan/function/func_builtin.go
pkg/util/trace/impl/motrace/cu.go
pkg/util/trace/impl/motrace/cu_bench_test.go
test/distributed/cases/log/query_cu.result
test/distributed/cases/log/query_cu.sql

issue #https://github.com/matrixorigin/MO-Cloud/issues/4510
cherry-pick https://github.com/matrixorigin/matrixone/pull/20420
fix s3ioinput as float64 value while do cu calculation.

Fix cuio calculated result as float64 val 

---

pkg/frontend/routine_manager.go
pkg/frontend/routine_manager_test.go

update
issue #https://github.com/matrixorigin/matrixone/issues/20390
修改panic. 前面的ut中启动的RM,但是UT 退出后。后台线程没退出。

fix ut panic

---

pkg/vm/engine/disttae/local_disttae_datasource.go
pkg/vm/engine/tae/blockio/utils.go

issue #https://github.com/matrixorigin/matrixone/issues/20443
quick return if has no tombstone in `WorkspaceS3FlushedDeletes`.

to 2.0: quick return if has no tombstone in `WorkspaceS3FlushedDeletes`

---

pkg/sql/compile/compile.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/4471
limit the dop of dedup join max to ncpu

limit the dop of dedup join max to ncpu

---

README.md
README_CN.md

issue #[601](https://github.com/matrixorigin/matrixorigin.io/issues/601)
___
Documentation
___
- Updated the architecture diagram image URLs in both English and Chinese README files.
- Ensures that the documentation reflects the latest architecture diagram for better clarity and accuracy.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Update architecture diagram image URL</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
README.md
- Updated the architecture diagram image source URL.
</details>
</td>
<td><a …

Update architecture diagram

---

pkg/vm/engine/disttae/local_disttae_datasource.go
pkg/vm/engine/tae/blockio/utils.go

issue #https://github.com/matrixorigin/matrixone/issues/20443
quick return if has no tombstone in `WorkspaceS3FlushedDeletes`

quick return if has no tombstone in WorkspaceS3FlushedDeletes

---

pkg/vm/engine/disttae/local_disttae_datasource.go
pkg/vm/engine/disttae/logtailreplay/partition_state.go
pkg/vm/engine/engine_util/pk_filter_mem.go
pkg/vm/engine/engine_util/reader.go

issue #https://github.com/matrixorigin/matrixone/issues/18603
1.  if pk Equal is found in Inmem rows, skip all blocks
2. if pk Equal is found in one blk, skip all the following blocks.

optimization of the reader Equal filter.

---

cgo/lib.go

issue #20422 
some older version c compilers' default c standard is not c99 or newer, fix the CFLAGS to make them work.

cgo: fix CFLAGS to support older c compiler

---

pkg/frontend/authenticate.go
pkg/frontend/authenticate_test.go
pkg/frontend/publication_subscription.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/4563
原因：并发的drop account 导致的死锁。
修改：在查询mo_account表（sys租户）时，用`select ... for update`。这个避免多个drop account 并发执行的问题。
潜在的问题：锁住mo_account表，会阻塞创建/更新租户、创建/alter/drop/show发布订阅。这些业务也会查mo_account表。

fix txn deadlock during drop account

---

pkg/fileservice/minio_sdk.go
pkg/fileservice/minio_sdk_test.go
pkg/fileservice/object_storage_arguments.go
pkg/fileservice/object_storage_arguments_test.go
pkg/fileservice/qcloud_sdk.go
pkg/fileservice/utils.go
pkg/fileservice/utils_test.go

issue # https://github.com/matrixorigin/MO-Cloud/issues/4561
do not load credentials from env vars if provided in arguments.

fileservice: in minio and qcloud sdk, do not load credentials from env vars if provided in arguments

---

pkg/vm/engine/test/change_handle_test.go
pkg/vm/engine/test/mo_table_stats_test.go
pkg/vm/engine/test/reader_test.go
pkg/vm/engine/test/testutil/disttae_engine.go
pkg/vm/engine/test/testutil/tae_engine.go
pkg/vm/engine/test/testutil/types.go
pkg/vm/engine/test/testutil/util.go
pkg/vm/engine/test/workspace_test.go

issue #https://github.com/matrixorigin/matrixone/issues/20603
clean temporary files when disttae.test UTs are complete.

clean temporary files when `disttae.test` UTs are complete.

---

pkg/cnservice/distributed_tae.go
pkg/cnservice/server_task.go
pkg/frontend/server.go
pkg/predefine/predefine.go
pkg/vm/engine/disttae/mo_table_stats.go
pkg/vm/engine/disttae/types.go
pkg/vm/engine/test/testutil/disttae_engine.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/4590
1. A new task meta-record cannot be inserted into the task table when the table already exists.

fix init mo_table_stats cron task meta.

---

pkg/vm/engine/disttae/txn_table.go
pkg/vm/engine/engine_util/reader.go
pkg/vm/engine/tae/db/db.go
pkg/vm/engine/tae/db/open.go

issue #20535 
more detailed log

small code refactor

---

pkg/vm/engine/disttae/txn.go
pkg/vm/engine/disttae/types.go

issue #20663
Immediately free the batch that has been flushed when workspace dump

optimize workspace dump memory usage

---

pkg/vm/engine/tae/txn/txnimpl/store.go
pkg/vm/engine/tae/txn/txnimpl/table.go
pkg/vm/engine/tae/txn/txnimpl/txndb.go

Add debug log for 2.0.1 

---

pkg/vm/engine/tae/db/checkpoint/replay.go
pkg/vm/engine/tae/db/db.go
pkg/vm/engine/tae/db/open.go
pkg/vm/engine/tae/db/replay.go
pkg/vm/engine/tae/logstore/driver/batchstoredriver/store.go
pkg/vm/engine/tae/logstore/driver/logservicedriver/driver.go
pkg/vm/engine/tae/rpc/handle.go
pkg/vm/engine/tae/tables/aobj.go
pkg/vm/engine/tae/txn/txnimpl/store.go
pkg/vm/engine/tae/txn/txnimpl/txndb.go

issue #20247 
improve debug info

Improve debug info

---

pkg/cnservice/server_query.go
pkg/frontend/show_account.go
pkg/frontend/test/engine_mock.go
pkg/vm/engine/disttae/engine.go
pkg/vm/engine/disttae/logtail_consumer.go
pkg/vm/engine/disttae/mo_table_stats.go
pkg/vm/engine/disttae/stats.go
pkg/vm/engine/disttae/stats_test.go
pkg/vm/engine/disttae/types.go
pkg/vm/engine/entire_engine.go
pkg/vm/engine/entire_engine_test.go
pkg/vm/engine/memoryengine/binded.go
pkg/vm/engine/memoryengine/engine.go
pkg/vm/engine/test/change_handle_test.go
pkg/vm/engine/test/disttae_engine_test.go
pkg/vm/engine/test/mo_table_stats_test.go
pkg/vm/engine/test/reader_test.go
pkg/vm/engine/test/testutil/disttae_engine.go
pkg/vm/engine/test/testutil/logtailserver.go
pkg/vm/engine/test/testutil/tae_engine.go
pkg/vm/engine/test/testutil/util.go
pkg/vm/engine/test/workspace_test.go
pkg/vm/engine/types.go

issue #20577 
add some logs and UT for stats

[improvement] stats: add some logs and UT

---

pkg/txn/storage/tae/storage.go
pkg/vm/engine/tae/common/retry.go
pkg/vm/engine/tae/db/checkpoint/flusher.go
pkg/vm/engine/tae/db/checkpoint/flusher_test.go
pkg/vm/engine/tae/db/checkpoint/option.go
pkg/vm/engine/tae/db/checkpoint/runner.go
pkg/vm/engine/tae/db/checkpoint/testutils.go
pkg/vm/engine/tae/db/checkpoint/types.go
pkg/vm/engine/tae/db/controller.go
pkg/vm/engine/tae/db/db.go
pkg/vm/engine/tae/db/open.go
pkg/vm/engine/tae/db/test/db_test.go
pkg/vm/engine/tae/db/test/replay_test.go
pkg/vm/engine/tae/db/testutil/engine.go
pkg/vm/engine/tae/logtail/handle.go
pkg/vm/engine/tae/rpc/handle.go
pkg/vm/engine/test/disttae_engine_test.go
pkg/vm/engine/test/testutil/logtailserver.go

issue #20554 
manual control flusher

refactor tn migration 6

---

pkg/frontend/mysql_cmd_executor.go
pkg/frontend/mysql_cmd_executor_test.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/4635
fix get role name of mo admin role in non-sys account

[Cherry-pick] fix get role name of mo admin role in non-sys account

---

pkg/clusterservice/cluster.go
pkg/clusterservice/cluster_test.go

issue #20787 
make sure there is at least one TN in the service.

[improvement] clusterservice: at least one tn in the service.

---

pkg/frontend/variables.go

issue #20845
revert maximum value of max_allowed_packet to 1G

revert maximum value of max_allowed_packet to 1G

---

pkg/vm/engine/tae/db/checkpoint/testutils.go

issue #20535 
fix force global checkpoint implementation

fix force global checkpoint

---

pkg/lockservice/cfg.go

issue #19750 
make sure the default lock timeout is large enough to reduce sensitivity to 2.0

make sure the default lock timeout is large enough to reduce sensitivity to 2.0

---

pkg/lockservice/cfg.go

issue #19750 
make sure the default lock timeout is large enough to reduce sensitivity

make sure the default lock timeout is large enough to reduce sensitivity

---

pkg/frontend/variables.go
pkg/sql/plan/build_dml_util.go
pkg/sql/plan/mock.go
test/distributed/cases/prepare/prepare.result
test/distributed/cases/prepare/prepare.test

issue # https://github.com/matrixorigin/matrixone/issues/20864
增加session级别配置项delete_opt_to_truncate控制是否要对delete from table； 优化成truncate, 默认为true， 即优化成trucate， 通过set session delete_opt_to_truncate = 0；关闭该优化

add session system var delete_opt_to_truncate

---

pkg/lockservice/lock_table_allocator.go
pkg/lockservice/lock_table_remote.go
pkg/lockservice/lock_table_remote_test.go

issue #20747 #20839
fix remote lock EOF and OOM when lock table bind

fix remote lock EOF and OOM when lock table bind

---

pkg/vm/engine/disttae/logtail_consumer.go
pkg/vm/engine/tae/logtail/service/session.go

issue #20898
remote "set ready" in init method, otherwise, there will be some
subscriptions before system tables are subscribed.

[bug] logtail: remove "set ready" in init method

---

pkg/logservice/config.go
pkg/logservice/truncation.go
pkg/logservice/truncation_test.go

issue https://github.com/matrixorigin/MO-Cloud/issues/4704
modify the default interval of truncate hakeeper logs.

[improvement] modify the default interval of truncate hakeeper logs.

---

pkg/sql/plan/apply_indices.go
pkg/sql/plan/stats.go
test/distributed/cases/optimizer/index.result
test/distributed/cases/optimizer/index.test

issue #20992 
optimize stats when table not flushed yet

optimize stats when table not flushed yet

---

pkg/bootstrap/versions/v2_0_2/cluster_upgrade_list.go
pkg/common/pubsub/types.go
pkg/frontend/authenticate.go
pkg/frontend/authenticate_test.go
pkg/frontend/predefined.go
pkg/frontend/publication_subscription.go
pkg/frontend/publication_subscription_test.go
pkg/frontend/snapshot.go
test/distributed/cases/foreign_key/fk_show_columns.result
test/distributed/cases/publication_subscription/pub_sub3.result
test/distributed/cases/publication_subscription/pub_sub3.sql
test/distributed/cases/snapshot/cluster_level_snapshot_restore_cluster.sql
test/distributed/cases/snapshot/cluster_level_snapshot_restore_pubsub.result
test/distributed/cases/snapshot/cluster_level_snapshot_restore_pubsub.sql
test/distributed/cases/snapshot/sys_restore_pubsub_to_sys_account.result
test/distributed/cases/snapshot/sys_restore_pubsub_to_sys_account.sql

issue #20728
add columns to mo_pubs/subs

[Cherry-pick] add columns to mo_pubs/subs

---

pkg/frontend/session.go
pkg/frontend/session_test.go

issue [migrate session skip error when db is dropped](https://github.com/matrixorigin/MO-Cloud/issues/4724)
migrate session skip error when db is dropped

[bug] proxy: migrate session skip error when db is dropped

---

pkg/sql/plan/build_ddl.go
pkg/sql/plan/build_ddl_test.go

issue #21131
use full db.table path in insert stmt

[Cherry-pick] use full db.table path in insert stmt

---

pkg/util/export/etl/db/db_holder.go
pkg/util/export/etl/db/db_holder_test.go
pkg/util/export/merge.go
pkg/util/metric/v2/trace.go

issue # https://github.com/matrixorigin/MO-Cloud/issues/4730
parent pr
- https://github.com/matrixorigin/matrixone/pull/21132
Add `account=?` filter-condition combined with `request_at=?` filter-condition.
-  base on statement_info's cluster-by key is `(account, request_at)`.

chore: add account filter-condition to speedup etlmerge check-exist 

---

pkg/vm/engine/disttae/mo_table_stats.go

issue #https://github.com/matrixorigin/matrixone/issues/21083 https://github.com/matrixorigin/matrixone/issues/21106
fix partition state pinned by mo table stats.

fix partition state pinned by mo table stats and adding some metrics.

---

pkg/vm/engine/disttae/stats.go
pkg/vm/engine/disttae/stats_test.go
pkg/vm/engine/disttae/txn_table.go

issue #20577 #21174 #21227
in some case, some tables' subscription request fails and
it will wait for the notification forever. these waiting occupy
all the update stats goroutines which cause the real getting
stats request hang.

[bug] stats: fix hang issue when get stats

---

pkg/vm/engine/disttae/logtailreplay/change_handle.go
pkg/vm/engine/disttae/logtailreplay/partition_state.go
pkg/vm/engine/disttae/logtailreplay/partition_state_test.go
pkg/vm/engine/disttae/logtailreplay/rows_iter.go
pkg/vm/engine/disttae/logtailreplay/types.go
pkg/vm/engine/disttae/mo_table_stats.go

issue #https://github.com/matrixorigin/matrixone/issues/21083 https://github.com/matrixorigin/matrixone/issues/21106
reduce the memory consumption by storing points in the partition state.

to 2.0: reduce the memory consumption by using pointer as btree item in the partition state

---

pkg/vm/engine/disttae/cache/types.go
pkg/vm/engine/disttae/mo_table_stats.go

issue #https://github.com/matrixorigin/matrixone/issues/21213
skip to subscribe to the deleted table when calculating the mo table stats. 
for the deleted tables:
1. should not subscribe
2. even subscribed, should failed
However, in the current implementation, the mo table stats task may subscribe to a deleted table and succeed, which may cause some other bugs. So, it tries to skip to subscribe to a deleted table.

to 2.0: skip to subscribe to the deleted table when calculating the mo table stats.

---

pkg/common/malloc/default.go

This reverts commit 2f6f3d78a02e726f76e67594fc9973551c5b3bff.
- [x ] BUG
issue https://github.com/matrixorigin/MO-Cloud/issues/4753
revert 2f6f3d78a02e726f76e67594fc9973551c5b3bff

Revert "malloc: default to malloc (#21211)"

---

pkg/vm/engine/disttae/mo_table_stats.go
pkg/vm/engine/disttae/txn_table.go
pkg/vm/engine/disttae/types.go

issue #https://github.com/matrixorigin/matrixone/issues/21213
if no notify, global stats will wait forever.

to 2.0: notify global stats when subscribed table.

---

pkg/vm/engine/disttae/mo_table_stats.go
pkg/vm/engine/tae/rpc/handle_debug.go

issue #https://github.com/matrixorigin/matrixone/issues/21213
1. beta task could panic
2. release ckp data

fix mo_table_stats task panic and release mpool.

---

pkg/common/fulltext/fulltext.go
pkg/common/fulltext/fulltext_test.go
test/distributed/cases/fulltext/fulltext.result
test/distributed/cases/fulltext/fulltext.sql

issue #21217
Invalid search string converted to empty pattern to panic
e.g. search string '+[[[' in natural language mode. After tokenization, it become empty pattern that cause panic.

bug fix: Invalid search string converted to empty pattern to panic

---

pkg/util/export/etl/db/db_holder.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/4786
mo_logger SHOULD use server side max_allowed_packet config

bugfix: adjust mo_logger use server side max_allowed_packet config

---

pkg/util/export/etl/db/db_holder.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/4786
main pr: https://github.com/matrixorigin/matrixone/pull/21317
mo_logger SHOULD use server side max_allowed_packet config

bugfix: adjust mo_logger use server side max_allowed_packet config in 2.0

---

pkg/sql/plan/bind_delete.go
pkg/sql/plan/build.go
pkg/sql/plan/build_test.go

issue # https://github.com/matrixorigin/matrixone/issues/20864
if delete can't rewrite to truncate table, use bind_delete make new plan

if delete can't rewrite to truncate table, use bind_delete make new plan

---

pkg/sql/plan/bind_insert.go
pkg/sql/plan/bind_replace.go
pkg/sql/plan/build.go
test/distributed/cases/dml/replace/replace.result
test/distributed/cases/dml/replace/replace.test

issue #20387
implement REPLACE plan standalone, instead of rewriting to DELETE and INSERT

implement REPLACE stmt in new DML plan

---

pkg/sql/compile/lock_meta.go

issue # https://github.com/matrixorigin/matrixone/issues/21364
fix problem that bat is not initialization  causing panic when l.lockTableVec is not nil in dolck function

fix: doLock panic

---

pkg/common/malloc/config.go
pkg/common/malloc/fixed_size_mmap_allocator.go
pkg/common/malloc/fixed_size_mmap_allocator_test.go
pkg/common/malloc/mmap_darwin.go
pkg/common/malloc/mmap_linux.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/4753
replaced channel-based buffering with a slab allocator in fixed_size_mmap_allocator.go
reduces mmap syscalls by reusing slabs and batching object allocations.

malloc: refactor mmap allocator

---

pkg/sql/compile/compile.go
pkg/sql/compile/scope.go
pkg/vm/engine/disttae/txn_table.go

issue # https://github.com/matrixorigin/matrixone/issues/21237
compileTableScanDataSource using relation reset interface

refactor: compileTableScanDataSource relation reset

---

pkg/container/vector/functionTool_test.go
pkg/container/vector/type_check_no_race.go
pkg/container/vector/type_check_race.go
pkg/container/vector/utils.go
pkg/container/vector/vector.go
pkg/sql/colexec/multi_update/insert_test.go
pkg/sql/colexec/table_function/fulltext_test.go
pkg/sql/colexec/table_function/fulltext_tokenize_test.go

issue #21384 
to expose type mismatch bug

vector: always check types in *NoTypeCheck functions if race tag is set

---

optools/images/Dockerfile

issue #21453
failed to build linux arm64 image with golang-1.23.0-bookworm base image.  Change the base image with ubuntu:22.04 which is the same as the docker image OS.

bug fix arm64 build docker failed

---

pkg/container/batch/compact_batchs.go
pkg/container/batch/compact_batchs_test.go
pkg/sql/colexec/shuffleV2/shuffle.go
pkg/sql/colexec/shuffleV2/shufflepool.go
pkg/sql/colexec/shuffleV2/types.go

issue #21414
Split batchs for shuffleV2
目前会存在当消费较慢，桶又相对集中的情况下。不停append到一个桶里（而桶只是一个batch），从而造成这个batch过大，超过2G的阈值。
这里是把桶的batch从一个batch修改为一个batch数组。避免单个batch过大，顺便重构了下执行逻辑。
从21414的case看，出bug的SQL性能基本一样，跑4-5次看结果还略快了一点。但不一定有普遍意义。

Split batchs for shuffleV2

---

.github/mergify.yml

issue #
change auto merge required reviewer for non-main branch

change auto merge required reviewer for non-main branch

---

test/distributed/cases/function/func_wasm.result
test/distributed/cases/function/func_wasm.sql

issue #21439
comment out try to get  non-exist wasm file.  Different exception from open source library caught by MO.  Maybe library updated.

different exception when getting non-exist wasm file

---

pkg/vm/engine/disttae/mo_table_stats.go
pkg/vm/engine/disttae/mo_table_stats_test.go

issue #https://github.com/matrixorigin/matrixone/issues/21537
improve the performance of cleaning up the deleted table stats from the stats table.
multiple OR conditions SQL statement to IN condition statement.

to 2.1: improve the performance of cleaning up the deleted table stats from the stats table.

---

pkg/lockservice/lock_table_remote.go
pkg/lockservice/lock_table_remote_test.go
pkg/lockservice/service_test.go

issue #21758
retry when remote lock i/o timeout

retry when remote lock i/o timeout

---

pkg/partition/partition.go
test/distributed/cases/dtype/uuid.result
test/distributed/cases/dtype/uuid.sql

issue https://github.com/matrixorigin/MO-Cloud/issues/5275
fix bug: panic in order by uuid column

fix bug: panic in order by uuid column

---

pkg/fileservice/s3_fs.go

This reverts commit 8c6233beb905741329a36840cea4c38f184cf8cc.
issue #21394
revert the change

Revert "[Subtask]: 对象分配优化：fileservice.newEventLogger #21394 (#21805)"

---

cmd/mo-service/config.go
pkg/embed/config.go
pkg/fileservice/cache.go
pkg/fileservice/cache_test.go
pkg/fileservice/disk_cache.go
pkg/fileservice/disk_cache_test.go
pkg/fileservice/fifocache/bench2_test.go
pkg/fileservice/fifocache/bench_test.go
pkg/fileservice/fifocache/data_cache.go
pkg/fileservice/fifocache/data_cache_test.go
pkg/fileservice/fifocache/fifo.go
pkg/fileservice/fifocache/fifo_test.go
pkg/fileservice/fifocache/ghost.go
pkg/fileservice/fifocache/queue.go
pkg/fileservice/fifocache/shardmap.go
pkg/fileservice/local_fs.go
pkg/fileservice/local_fs_test.go
pkg/fileservice/mem_cache.go
pkg/fileservice/mem_cache_test.go
pkg/fileservice/memory_fs_test.go
pkg/fileservice/s3_fs.go
pkg/objectio/cache.go

issue #21654 #21589 #15191
1. add ghost fifo to s3fifo cache as stated in the paper.
2.  clean up shard map to avoid race conditions with items under different locks (shards locks and queue lock).
3. each item has its own mutex to protect postFunc() and its data and improve the concurrency.
4. all queues have their own mutex to improve concurrency.
5. replace VERY SLOW CompareAndSwap() with mutex to protect CacheItem for increment and decrement the frequency.
introduce disable-s3fifo in config.

s3fifo add ghost fifo for 2.1-dev

---

pkg/container/types/rowid.go
pkg/vm/engine/disttae/transfer.go
pkg/vm/engine/disttae/txn.go
pkg/vm/engine/readutil/datasource.go
pkg/vm/engine/readutil/datasource_test.go

issue #https://github.com/matrixorigin/matrixone/issues/21748
This fixed the CDC duplicated entry issue caused by in-memory transfer tombstones, which wrote the unsorted rowids into the workspace.

fix the cdc duplicated entry issue caused by in-memory transfer tombstones.

---

pkg/fileservice/disk_cache_callbacks.go
pkg/fileservice/disk_cache_test.go

issue #21810 
make DiskCacheCallbacks a context.Context to eliminate usages of context.WithValue

fileservice: make DiskCacheCallbacks a context.Context to eliminate usages of context.WithValue

---

pkg/sql/colexec/external/external_test.go

issue #18855 
colexec/external: ensure symlink is valid in TestReadDirSymlink

colexec/external: ensure symlink is valid in TestReadDirSymlink

---

pkg/sql/plan/opt_misc.go
pkg/sql/plan/query_builder.go

issue https://github.com/matrixorigin/MO-Cloud/issues/5330
to avoid hung on DML query when fulltext index exists

force SINK_SCAN to run on single CN

---

pkg/sql/plan/apply_indices_fulltext.go
test/distributed/cases/fulltext/fulltext.result
test/distributed/cases/fulltext/fulltext_bm25.result
test/distributed/cases/fulltext/fulltext_bm25.sql

issue #22064
fullltext index disable pushdown limit so that result is always predictable.
fullltext index disable pushdown limit so that result is always predictable.
https://github.com/matrixorigin/MO-Cloud/issues/5779

disable pushdown limit for 2.2-dev

---

pkg/sql/colexec/aggexec/aggContext.go
pkg/sql/colexec/aggexec/aggFrame_test.go
pkg/sql/colexec/aggexec/aggMethod.go
pkg/sql/colexec/aggexec/approx_count.go
pkg/sql/colexec/aggexec/concat.go
pkg/sql/colexec/aggexec/count.go
pkg/sql/colexec/aggexec/distinct.go
pkg/sql/colexec/aggexec/fromBytesRetBytes.go
pkg/sql/colexec/aggexec/fromBytesRetFixed.go
pkg/sql/colexec/aggexec/fromFixedRetBytes.go
pkg/sql/colexec/aggexec/fromFixedRetFixed.go
pkg/sql/colexec/aggexec/median.go
pkg/sql/colexec/aggexec/median_test.go
pkg/sql/colexec/aggexec/result.go
pkg/sql/colexec/aggexec/result_test.go
pkg/sql/colexec/aggexec/tool.go
pkg/sql/colexec/aggexec/types.go
pkg/sql/colexec/aggexec/window.go
pkg/sql/plan/function/agg/avg.go
pkg/sql/plan/function/agg/avg_tw_cache.go
pkg/sql/plan/function/agg/avg_tw_result.go
pkg/sql/plan/function/agg/bitmap.go
pkg/sql/plan/function/agg/size_test.go
pkg/sql/plan/function/agg/sum.go
pkg/sql/plan/function/agg/var_pop.go

issue #3433
add AggFuncExec.Size to estimate the memory consumption of aggregation states.

colexec/aggexec: add AggFuncExec.Size

---

pkg/sql/plan/function/func_binary.go
pkg/sql/plan/function/func_binary_test.go
pkg/sql/plan/function/function_id.go
pkg/sql/plan/function/function_id_test.go
pkg/sql/plan/function/list_builtIn.go
test/distributed/cases/function/func_string_strcmp.result
test/distributed/cases/function/func_string_strcmp.test

issue https://github.com/matrixorigin/matrixone/issues/15359
support `select strcmp(xxx, xxx);`

support strcmp

---

pkg/sql/colexec/aggexec/aggFrame_test.go
pkg/sql/colexec/aggexec/concat.go
pkg/sql/colexec/aggexec/count.go
pkg/sql/colexec/aggexec/distinct.go
pkg/sql/colexec/aggexec/median_test.go
pkg/sql/colexec/aggexec/register.go
pkg/sql/colexec/aggexec/serialize.go
pkg/sql/colexec/aggexec/types.go
pkg/sql/colexec/aggexec/window.go

issue #3433
Make aggregate states with distinctHash marshal/unmarshal-able.
Export special agg ids to allow use in tests.

colexec/aggexec: implement marshal/unmarshal for distinctHash; export special agg ids

---

pkg/sql/colexec/rightdedupjoin/join.go

issue #22226
fix right join dedup memory leak
___
Bug fix
___
- Remove vector nullification to fix memory leak
- Prevent premature cleanup of batch vectors
___
```mermaid
flowchart LR
A["probe function"] --> B["create result batch"]
B --> C["assign vectors to result"]
C --> D["removed: bat.Vecs[rp.Pos] = nil"]
D --> E["fixed memory leak"]
```
<tr>
<td>
<details>
<summary><strong>join.go</strong><dd><code>Remove vector nullification in probe function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pkg/sql/colexec/rightdedupjoin/join.go …

fix right join dedup memory leak

---

pkg/objectio/ioutil/sinker.go
pkg/sql/colexec/deletion/types.go
pkg/sql/colexec/insert/insert.go
pkg/sql/colexec/multi_update/s3writer_delegate.go
pkg/sql/colexec/rightdedupjoin/join.go
pkg/sql/colexec/s3util.go
pkg/sql/colexec/s3util_test.go
pkg/vm/engine/disttae/local_disttae_datasource_test.go
pkg/vm/engine/disttae/table_meta_reader.go
pkg/vm/engine/disttae/txn.go
pkg/vm/engine/disttae/txn_table.go
pkg/vm/engine/readutil/datasource_test.go
pkg/vm/engine/readutil/tombstone_data_test.go
pkg/vm/engine/test/reader_test.go
pkg/vm/engine/test/workspace_test.go

issue #22226 #22280
Pick 22284 22293 to 3.0-dev
___
___
- Fix right join dedup memory leak issue
- Optimize S3 writer with memory threshold configuration
- Refactor S3 writer API to support configurable memory thresholds
- Remove unnecessary batch cloning and improve memory management
___
```mermaid
flowchart LR
A["Right Join Dedup"] -- "fix memory leak" --> B["Memory Management"]
C["S3 Writer"] -- "add memory threshold" --> D["Configurable Thresholds"]
C -- "refactor API" --> E["Simplified Interface"]
D --> F["Performance Optimization"]
E --> F
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>8 …

Pick 22284 22293 to 3.0-dev

---

pkg/lockservice/cfg.go
pkg/sql/colexec/shuffle/shuffle.go
pkg/sql/compile/compile.go
pkg/sql/plan/explain/explain_node.go
pkg/sql/plan/shuffle.go
test/distributed/cases/ddl/secondary_index_insert.result
test/distributed/cases/ddl/secondary_index_insert.sql

issue #22274
1. use shuffle V1 instead of shuffle V2 if probe/build side has merge operator
2. display shuffle info for table_scan in explain
3. decrease defaultMaxLockRowCount from 1M to 20k
___
___
- Fix shuffle join V2 compatibility with merge operators
- Display shuffle information in table scan explain output
- Reduce default lock row count from 1M to 200K
- Add test coverage for secondary index operations
___
```mermaid
flowchart LR
A["Shuffle Join V2"] -- "check merge operators" --> B["Use Shuffle V1"]
C["Table Scan"] -- "add shuffle info" --> D["Enhanced Explain Output"]
E["Lock Service"] -- "reduce count" --> F["200K Row Limit"]
``` …

fix shuffle join (cp #22282)

---

pkg/vm/engine/tae/db/test/db_test.go
pkg/vm/engine/tae/iface/txnif/types.go
pkg/vm/engine/tae/txn/txnbase/store.go
pkg/vm/engine/tae/txn/txnimpl/database.go
pkg/vm/engine/tae/txn/txnimpl/relation.go
pkg/vm/engine/tae/txn/txnimpl/store.go
pkg/vm/engine/tae/txn/txnimpl/txn.go
pkg/vm/engine/tae/txn/txnimpl/txndb.go

Avoid writing write intent into the TN state machine in offline mode.
Approved by: @jiangxinmeng1
issue #22307 
Fix 22307 pick to 3.0
___
Bug fix
___
- Add write operation validation for offline transactions
- Prevent write operations in offline/readonly transaction mode
- Add comprehensive test coverage for offline transaction restrictions
- Fix error handling for write operations in offline state
___
```mermaid
flowchart LR
A["Offline Transaction"] --> B["WantWrite Check"]
B --> C["Write Operation"]
C --> D["Error if Offline"]
B --> E["Read Operation"]
E --> F["Allow if Offline"]
```
<tr>
<td>
<details> …

Fix 22307 pick to 3.0

---

pkg/frontend/mysql_cmd_executor.go
pkg/frontend/result_row_stmt.go
pkg/sql/compile/alter.go
pkg/sql/compile/analyze_module.go
pkg/sql/compile/analyze_module_test.go
pkg/sql/compile/debugTools.go
pkg/sql/compile/scope.go
pkg/sql/plan/build_alter_table.go
pkg/util/trace/impl/motrace/statistic/stats_array.go

issue https://github.com/matrixorigin/matrixone/issues/22302
- Use the database name in the query first and then try the name in the compile struct
- Fix some typos
- Refactor explain phyplan a little bit
___
___
- Fix 'db not selected' error in ALTER TABLE operations
- Refactor EXPLAIN physical plan code consolidation
- Fix typos and improve string formatting consistency
- Remove duplicate code in explain analyze handling
___
```mermaid
flowchart LR
A["ALTER TABLE"] --> B["Database Name Fix"]
C["EXPLAIN Analyze"] --> D["Code Consolidation"]
E["String Formatting"] --> F["fmt.Fprintf Usage"]
B --> G["Fixed Operations"]
D --> G
F --> G
``` …

fix 'db not selected' error in alter table

---

pkg/vm/engine/tae/db/checkpoint/flusher.go

issue https://github.com/matrixorigin/MO-Cloud/issues/6068
- Process appendable objects in controlled chunks to maintain stable memory usage.
- A chunk means 400 appendable data objects
___
Enhancement
___
- Process appendable objects in controlled chunks of 400 items
- Maintain stable memory usage during flush operations
- Handle tombstone metadata as monolithic chunk in first iteration
- Add logging for chunk processing progress
___
```mermaid
flowchart LR
A["Original Objects"] --> B["Split into Chunks (400 items)"]
B --> C["Process First Chunk + Tombstones"]
C --> D["Process Remaining Chunks"]
D --> E["Stable Memory Usage"]
``` …

flushing objects in chunks 3.0

---

pkg/sql/plan/function/ctl/ctl.go
test/distributed/cases/function/mo_ctl/mo_ctl_merge.result
test/distributed/cases/function/mo_ctl/mo_ctl_merge.test

issue #https://github.com/matrixorigin/matrixone/issues/21941
mo_ctl advancing the transaction snapshot may result in unexpected behavior,
So we restrict these executions within an explicit transaction.
___
Bug fix
___
- Restrict MO_CTL flush/merge/checkpoint execution within explicit transactions
- Add `ByBegin()` method to TxnOperator interface
- Implement transaction state checking for control operations
- Add test cases for transaction restriction validation
___
```mermaid
flowchart LR
A["TxnOperator Interface"] --> B["Add ByBegin() method"]
B --> C["Implement in all operators"]
C --> D["MO_CTL function check"]
D --> E["Block flush/merge/checkpoint in transactions"]
E --> F["Add test validation"]
``` …

to 3.0: restrict MO_CTL execution of cn merge within explicit transactions

---

pkg/common/malloc/inuse_tracking_allocator.go
pkg/common/malloc/inuse_tracking_allocator_test.go
pkg/container/hashtable/hash_test.go
pkg/container/hashtable/int64_hash_map.go
pkg/container/hashtable/malloc.go
pkg/container/hashtable/string_hash_map.go
pkg/container/hashtable/util_test.go

issue #22239 
container/hashtable: use longer than 16 bytes keys in tests
malloc: call upstream deallocator if error in InuseTrackingAllocator.Allocate
container/hashtable: re-implement WriteTo/UnmarshalFrom with iter and insert
___
___
- Fix memory allocator error handling and cleanup
- Refactor hashtable serialization using iterators
- Improve test coverage with longer keys
- Update error handling in tracking allocator
___
```mermaid
flowchart LR
A["InuseTrackingAllocator"] --> B["Error Handling"]
B --> C["Upstream Deallocator"]
D["Hashtable WriteTo/UnmarshalFrom"] --> E["Iterator-based Serialization"]
E --> F["Simplified Format"]
G["Test Improvements"] --> H["Longer Keys"]
H --> I["Better Error Testing"]
``` …

container/hashtable: use longer than 16 bytes keys in tests

---

pkg/frontend/pitr.go
pkg/objectio/ioutil/funcs.go
pkg/vm/engine/disttae/local_disttae_datasource.go
pkg/vm/engine/disttae/mo_table_stats.go
pkg/vm/engine/disttae/table_meta_reader.go
test/distributed/cases/snapshot/clone/clone_appendable_obj.result
test/distributed/cases/snapshot/clone/clone_appendable_obj.sql

issue https://github.com/matrixorigin/matrixone/issues/22342 https://github.com/matrixorigin/matrixone/issues/22338
1. Fix the appendable tombstone object clone logic.
2. Fix privilege control when restoring.
___
Bug fix
___
- Fix appendable tombstone object clone logic for PITR restoration
- Add primary key column reading support in tombstone operations
- Implement proper snapshot filtering for appendable objects
- Add clone level context for privilege control during restoration
___
```mermaid
flowchart LR
A["PITR Restore"] --> B["Clone Level Context"]
C["ReadDeletes Function"] --> D["PK Column Support"]
E["TableMetaReader"] --> F["Tombstone Filtering"]
F --> G["Snapshot Validation"]
B --> H["Privilege Control"]
``` …

to 3.0: Fix the appendable tombstone object clone logic.

---

pkg/sql/colexec/join/join.go
pkg/sql/colexec/join/types.go
pkg/sql/colexec/left/join.go
pkg/sql/colexec/left/types.go

issue #22327
pick 22351 to 3.0-dev
___
Enhancement
___
- Refactor join operations to produce results in chunks of 8192 rows
- Implement state machine for probe method with three states
- Optimize memory usage and prevent OOM in large joins
- Consolidate join batch handling for better performance
___
```mermaid
flowchart LR
A["Input Batch"] --> B["State Machine"]
B --> C["NextBatch State"]
B --> D["BatchRow State"] 
B --> E["SelsForOneRow State"]
C --> F["Find Hash Results"]
D --> G["Process Single Row"]
E --> H["Handle Multiple Matches"]
F --> D
G --> I["8192 Row Chunks"]
H --> I
I --> J["Output Result"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td> …

pick Left/Inner join produces better chunks (#22351) to 3.0-dev

---

pkg/frontend/cdc_exector.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/6173
fix context deadline not set
___
Bug fix
___
- Add context timeout to CDC table handling
- Set 5-minute deadline for transaction operations
- Prevent indefinite blocking in CDC executor
___
```mermaid
flowchart LR
A["CDC Task Executor"] --> B["handleNewTables()"]
B --> C["Add 5min timeout"]
C --> D["Transaction Operations"]
```
<tr>
<td>
<details>
<summary><strong>cdc_exector.go</strong><dd><code>Add context timeout for CDC operations</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

fix context deadline not set

---

pkg/cdc/table_scanner.go
pkg/cdc/table_scanner_test.go
pkg/frontend/cdc_exector.go
pkg/objectio/injects.go

issue #https://github.com/matrixorigin/MO-Cloud/issues/6142
串行做scanTable()，防止s.Mp被覆盖
___
Bug fix
___
- Changed CDC table scanning from concurrent to sequential execution
- Prevents race condition where `s.Mp` field gets overwritten
- Moved goroutine execution from scanning to callback processing
___
```mermaid
flowchart LR
A["scanTableLoop()"] --> B["scanAndProcess()"]
B --> C["scanTable()"]
C --> D["processCallback()"]
B -.-> E["Sequential Execution"]
D -.-> F["Async Callback"]
```
<tr>
<td>
<details>
<summary><strong>table_scanner.go</strong><dd><code>Serialize table scanning to prevent race …

fix cdc table scanner

---

pkg/cdc/sinker.go
pkg/cdc/types.go
pkg/cdc/util.go
pkg/frontend/cdc_exector.go
pkg/vm/engine/test/cdc_sinker_test.go

issue #22386
fix cdc sinker and handle new table
___
Bug fix
___
- Add `Reset()` method to CDC sink interface
- Fix transaction cleanup in MySQL sink operations
- Add timeout handling for table definition retrieval
- Remove redundant timeout context in CDC executor
___
```mermaid
flowchart LR
A["CDC Sink Interface"] --> B["Add Reset() method"]
C["MySQL Sink"] --> D["Fix transaction cleanup"]
E["Table Definition"] --> F["Add 5-minute timeout"]
G["CDC Executor"] --> H["Remove redundant timeout"]
```
<tr>
<td>
<details>
<summary><strong>sinker.go</strong><dd><code>Add Reset method and fix transaction …

fix cdc sinker and handle new table

---

pkg/vectorindex/hnsw/build.go

issue #21506 
reduce insert batch to prevent create hnsw index from oom
___
Bug fix
___
- Reduce HNSW index insert batch size from 10,000 to 2,000
- Prevent out-of-memory errors during index creation
___
```mermaid
flowchart LR
A["Large batch size (10,000)"] -- "reduce to" --> B["Smaller batch size (2,000)"]
B --> C["Prevent OOM during HNSW index creation"]
```
<tr>
<td>
<details>
<summary><strong>build.go</strong><dd><code>Reduce insert batch size constant</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

reduce insert batch to prevent create hnsw index from oom

---

pkg/vm/engine/tae/logtail/snapshot.go

issue https://github.com/matrixorigin/matrixone/issues/22483
Fix iscp bvt crashed
___
Bug fix
___
- Remove unnecessary timestamp parsing causing crashes
- Simplify null check logic in ISCP processing
___
```mermaid
flowchart LR
A["ISCP processor"] --> B["Check dropAtList null"]
B --> C["Return early if not null"]
C --> D["Continue processing watermark"]
```
<tr>
<td>
<details>
<summary><strong>snapshot.go</strong><dd><code>Simplify ISCP processor null check logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary> …

Fix iscp bvt crashed

---

pkg/vm/engine/tae/logtail/snapshot.go

issue https://github.com/matrixorigin/matrixone/issues/22486
Fix iscp data race
___
Bug fix
___
- Fix data race in ISCP and PITR operations
- Add clone method for thread-safe access
- Replace direct field access with cloned instances
___
```mermaid
flowchart LR
A["SnapshotMeta"] --> B["RLock/RUnlock"]
B --> C["Clone specialTableInfo"]
C --> D["Process with cloned data"]
```
<tr>
<td>
<details>
<summary><strong>snapshot.go</strong><dd><code>Add thread-safe cloning for snapshot operations</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

Fix iscp data race

---

pkg/lockservice/lock_table_local.go
pkg/lockservice/service_test.go
pkg/lockservice/txn.go

issue #21711 
fix leak of waiter
___
Bug fix
___
- Fix memory leak of waiter objects in lock service
- Add proper cleanup for old waiters when lock acquisition fails
- Add test case to verify waiter leak prevention
- Add test hook for transaction lock addition error simulation
___
```mermaid
flowchart LR
A["Lock Acquisition"] --> B["Error Occurs"]
B --> C["Old Waiter Cleanup"]
C --> D["Prevent Memory Leak"]
E["Test Hook"] --> F["Error Simulation"]
F --> G["Leak Detection Test"]
```
<tr>
<td>
<details>
<summary><strong>lock_table_local.go</strong><dd><code>Add waiter cleanup in error handling</code>&nbsp; …

fix leak of waiter

---

pkg/cdc/sinker.go
pkg/cdc/sinker_test.go
pkg/sql/plan/build_show_util.go

build create sql with table define
Approved by: @ouyuanning, @ck89119, @aunjgr
issue #22207 
update create sql
___
Bug fix
___
- Replace string manipulation with proper SQL construction for CREATE TABLE
- Add cluster table validation and error handling
- Fix import path from pb/plan to sql/plan
- Add comprehensive test coverage for table creation scenarios
___
```mermaid
flowchart LR
A["String Manipulation"] --> B["Table Definition"]
B --> C["SQL Construction"]
C --> D["Validation"]
D --> E["Error Handling"]
```
<tr>
<td>
<details>
<summary><strong>sinker.go</strong><dd><code>Replace manual SQL …

update create sql

---

pkg/sql/colexec/external/types.go
pkg/sql/parsers/tree/update.go
pkg/sql/plan/bind_load.go
test/distributed/cases/load_data/load_data.result
test/distributed/cases/load_data/load_data.sql

issue #https://github.com/matrixorigin/matrixone/issues/22565
Align the default field separators for the export table and load data.
___
Bug fix
___
- Standardized default field separators across export and load operations
- Replaced hardcoded separators with centralized constants
- Added comprehensive test for export-load roundtrip functionality
___
```mermaid
flowchart LR
A["Hardcoded separators"] --> B["Centralized constants"]
B --> C["External parser"]
B --> D["Load data binding"]
C --> E["Consistent behavior"]
D --> E
```
<tr>
<td>
<details>
<summary><strong>update.go</strong><dd><code>Define …

Align the default field separators for the export table and load data.
