matrixorigin/matrixone

test/distributed/cases/function/func_wasm.sql
issue #17492
add bvt tag for wasm
___
Tests
___
- Added `@bvt` tags to the WASM test cases in `func_wasm.sql`.
- Included issue reference `#17492` in the `@bvt` tag for better traceability.
___
<tr>
<td>
<details>
<summary><strong>func_wasm.sql</strong><dd><code>Add `@bvt` tags for WASM test cases</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
test/distributed/cases/function/func_wasm.sql
<li>Added <code>@bvt</code> tags for test cases related to WebAssembly (WASM).<br> <li> Included issue reference <code>#17492</code> in the …
=> add bvt tag for wasm

pkg/sql/compile/compile.go, pkg/sql/compile/operator.go, pkg/sql/compile/remoterun.go, pkg/sql/compile/remoterunClient.go, pkg/sql/compile/scope.go, pkg/sql/compile/scope_test.go, pkg/vm/types.go, pkg/vm/vm.go
issue # https://github.com/matrixorigin/matrixone/issues/17486
remove Instruction struct
=> [refactor] remove instruction struct

pkg/frontend/server.go
issue #17499
fix mo start panic
=> fix arm start mo panic

test/distributed/cases/snapshot/cluster_level_snapshot_restore_pubsub.result, test/distributed/cases/snapshot/cluster_level_snapshot_restore_pubsub.sql
issue #https://github.com/matrixorigin/matrixone/issues/17308
rm tag 17308
=> rm tag 17308

pkg/vm/engine/tae/catalog/catalog.go, pkg/vm/engine/tae/catalog/check_metadata.go, pkg/vm/engine/tae/db/db.go, pkg/vm/engine/tae/db/test/db_test.go, pkg/vm/engine/tae/logtail/utils.go, pkg/vm/engine/tae/rpc/handle_debug.go, pkg/vm/engine/tae/tables/updates/mvcc.go
issue #17506
Fix visit tombstone, use latest version in VisitTombstone()
=> Fix visit tombstone

pkg/vm/engine/disttae/txn.go, pkg/vm/engine/disttae/txn_table.go
- [ x] BUG
issue #17476 
1. Fix bugs for sharding table.
=> Fix restore panic

test/distributed/cases/snapshot/cluster_level_snapshot_restore_system_table_to_sys_account.sql
issue #https://github.com/matrixorigin/matrixone/issues/17509
add tag 17509
=> add tag 17509

pkg/sql/compile/compile.go, pkg/vm/engine/disttae/stats.go, pkg/vm/engine/disttae/txn_table.go
issue https://github.com/matrixorigin/matrixone/issues/17524
cp #17535 #17526
=> Cp 1.2.2 hotfix

pkg/fileservice/disk_cache_test.go
issue #17531 
fix missing Release in tests
=> fileservice: fix missing free in tests

pkg/frontend/mysql_cmd_executor.go, pkg/frontend/session.go, pkg/sql/compile/compile.go, pkg/sql/compile/compileService.go, pkg/sql/compile/reuse.go, pkg/sql/compile/scope.go
This reverts commit 6f87f97f949629e0689f8b0e0f95df161e29d426.
issue #14940 
This reverts commit 6f87f97f949629e0689f8b0e0f95df161e29d426.
=> Revert "Refactor prepare to reuse Compile (#17516)"

pkg/objectio/funcs.go
issue #12518 
avoid some runtime.growSlice
=> small memory opt

pkg/sql/plan/function/ctl/cmd_disk_cleaner.go, pkg/vm/engine/tae/db/db.go, pkg/vm/engine/tae/db/gc/v1/check.go, pkg/vm/engine/tae/db/gc/v1/checkpoint.go, pkg/vm/engine/tae/db/gc/v1/delete.go, pkg/vm/engine/tae/db/gc/v1/diskcleaner.go, pkg/vm/engine/tae/db/gc/v1/table.go, pkg/vm/engine/tae/db/gc/v1/types.go, pkg/vm/engine/tae/db/open.go, pkg/vm/engine/tae/db/test/db_test.go, pkg/vm/engine/tae/db/testutil/engine.go, pkg/vm/engine/tae/rpc/handle_debug.go
issue https://github.com/matrixorigin/matrixone/issues/11804
rename gc to gc/v1
=> rename gc to gc/v1

pkg/frontend/types.go, pkg/util/metric/v2/dashboard/grafana_dashboard_mem.go, pkg/util/metric/v2/mem.go
issue #17593 
add metrics for frontend session allocator
=> frontend: add metrics for session allocator

optools/mo_checkin_regression/mo_checkin_regression_tke.yaml, test/distributed/cases/function/func_wasm.sql
=> CI: use configmap to store proxy env

cmd/mo-service/main.go
issue https://github.com/matrixorigin/MO-Cloud/issues/3752
do not panic when shutdown service, instead, print the erorr into log
=> [enhancement] main: do not panic when shutdown service

pkg/util/metric/v2/metrics.go, pkg/util/metric/v2/stats.go, pkg/vm/engine/disttae/stats.go
issue #17606
add metrics for stats trigger updating
=> [enhancement] stats: add metrics for stats trigger updating

pkg/sql/colexec/filter/types.go, pkg/sql/compile/compile.go, pkg/sql/compile/scope.go
issue #14940 
prepare重构的部分代码，确认安全后先提交
=> Refactor prepare to reuse Compile part 1

pkg/vm/engine/disttae/db.go, pkg/vm/engine/disttae/logtail_consumer.go, pkg/vm/engine/disttae/logtail_consumer_test.go, pkg/vm/engine/disttae/logtailreplay/partition.go, pkg/vm/engine/disttae/partition_reader.go, pkg/vm/engine/disttae/txn_table.go
- [ x] BUG
issue #17597 #17006  #14880 #14160 
1. Fix panic 
2. Fix bugs when unsubscribing table constantly.
=> Cherry pick

go.mod, go.sum
issue #17626
converted pointer straddles multiple allocations
=> [bug] checkptr: converted pointer straddles multiple allocations

pkg/common/reuse/sync_pool_based.go
issue [#3194](https://github.com/matrixorigin/MO-Cloud/issues/3194)
adjust reuse leak check
=> adjust reuse leak check

pkg/vm/engine/disttae/stats.go, pkg/vm/engine/disttae/stats_test.go
issue https://github.com/matrixorigin/MO-Cloud/issues/3678
limit the frequency of stats update trigger
=> [enhancement] limit the frequency of stats update trigger

pkg/incrservice/store_sql.go
issue #16982 
fix update incr record returns invalid affected rows
=> fix update incr record returns invalid affected rows

pkg/sql/colexec/external/external.go, pkg/sql/colexec/external/external_test.go, pkg/sql/colexec/external/types.go, pkg/sql/compile/compile.go, pkg/sql/compile/operator.go, test/distributed/cases/load_data/load_data.result, test/distributed/cases/load_data/load_data.sql
issue # https://github.com/matrixorigin/matrixone/issues/15110 https://github.com/matrixorigin/matrixone/issues/17639
Data interpretation is nonrestrictive if LOCAL modifier is specified or sql_mode is nonrestrictive
=> fix: modify load data check for load data local mode

pkg/cnservice/server_query.go, pkg/frontend/authenticate.go, pkg/frontend/routine_manager.go
issue #15202
add log for alter account suspend
=> add log for alter account suspend

pkg/sql/compile/compile.go
issue #16542 
remove unnecessary receiver in join build scope
=> remove unnecessary receiver in join build scope

test/distributed/cases/snapshot/sys_restore_system_table_to_sys_account.sql
=> add bvt tag

pkg/container/types/packer.go, pkg/container/types/packer_test.go
=> container/types: optimize Packer

pkg/vm/engine/tae/tables/txnentries/flushTableTail.go, pkg/vm/engine/tae/tables/txnentries/mergeobjects.go
issue #17744
fix transfer page bornts race
___
Bug fix
___
- Fixed race condition in `addTransferPages` method by moving the `AddPage` call after setting the timestamp in `flushTableTail.go`.
- Fixed race condition in `prepareTransferPage` method by moving the `AddPage` call after setting the timestamp in `mergeobjects.go`.
___
<tr>
<td>
<details>
<summary><strong>flushTableTail.go</strong><dd><code>Fix race condition in `addTransferPages` method</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
<li>Moved the <code>AddPage</code> call to ensure pages are added …
=> fix transfer page bornts race

pkg/vm/engine/tae/catalog/object.go, pkg/vm/engine/tae/db/test/db_test.go, pkg/vm/engine/tae/tables/aobj.go, pkg/vm/engine/tae/tables/jobs/flushTableTail.go, pkg/vm/engine/tae/txn/txnbase/mvccnode.go
issue #15918
add debug log in unit test
=> add ut log for possible uncommitted append node

pkg/frontend/mysql_cmd_executor.go, pkg/util/metric/v2/dashboard/grafana_dashboard_frontend.go, pkg/util/metric/v2/frontend.go, pkg/util/metric/v2/metrics.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/3816
增加sql 长度监控项。用于定位问题。
=> add sql length metric

pkg/common/reuse/sync_pool_based.go
adjust reuse leak check
Approved by: @reusee
issue #https://github.com/matrixorigin/MO-Cloud/issues/3769
cp to 1.2-dev 'adjust reuse leak check (#17669)'
=> cp to 1.2-dev 'adjust reuse leak check (#17669)'

pkg/vm/engine/tae/catalog/schema.go, pkg/vm/engine/tae/db/test/db_test.go, pkg/vm/engine/tae/logtail/snapshot.go
issue https://github.com/matrixorigin/MO-Cloud/issues/3840
Sometimes the schema of the mo_snapshots table may be modified manually, and gc needs to check this situation.
=> Add snapshot schema check

pkg/sql/colexec/evalExpression.go, pkg/sql/colexec/evalExpressionReset.go, pkg/sql/compile/compileService.go, pkg/vm/process/types.go
issue #17749 
支持expression的ResetForNextQuery()方法，
后续还有许多内容需要优化。
=> support `reset` method for evaluate expression without opt.

pkg/vm/engine/disttae/txn_table.go
issue #17807
need more tests with further changes
=> Revert remove false positive branch in PrimaryKeysMayBeModified 

pkg/sql/colexec/evalExpression.go, pkg/sql/colexec/evalExpressionReset.go, pkg/sql/colexec/evalExpression_test.go
issue #17749 
常量折叠代码移动到eval()过程
=> move constant folding for function expression from New() to Eval()

pkg/sql/colexec/evalExpression.go, pkg/sql/colexec/evalExpression_test.go
=> add ut for expression's reset

pkg/sql/colexec/evalExpression.go, pkg/sql/colexec/evalExpression_test.go
=> fix EvalExpressionOnce bug cause return empty vector.

pkg/sql/colexec/receiver_operator.go, pkg/sql/colexec/types.go, pkg/sql/compile/compile.go, pkg/vm/process/types.go
issue #17909 
[Tech Request]: reduce unnecessary channel in broadcast joins
=> [Tech Request]: reduce unnecessary channel in broadcast joins

pkg/sql/colexec/evalProjection.go, pkg/sql/colexec/limit/limit.go, pkg/sql/colexec/limit/limit_test.go, pkg/sql/colexec/limit/types.go, pkg/sql/colexec/projection/projection_test.go, pkg/sql/colexec/projection/types.go
=> Add some examples

pkg/container/bytejson/types.go, pkg/sort/sort.go, test/distributed/cases/function/func_json_extract_order.result, test/distributed/cases/function/func_json_extract_order.sql
issue #https://github.com/matrixorigin/MO-Cloud/issues/3828
fix order by json type
=> fix order by json type(#1.2-dev)

optools/mo_checkin_regression/mo_checkin_regression_tke.yaml
=> CI: fix proxy nodeselector error

pkg/sql/colexec/value_scan/types.go, pkg/sql/colexec/value_scan/value_scan.go, pkg/sql/colexec/value_scan/value_scan_test.go
issue #
暂时还没有把Scope.Run前构造batchs的代码移到value_scan。如果时间来得及再在后面移进来，那样应该会可以更好服用batchs的内存
=> refactor value scan

pkg/sql/colexec/preinsertsecondaryindex/preinsertsecondaryindex.go, pkg/sql/colexec/preinsertsecondaryindex/preinsertsecondaryindex_test.go, pkg/sql/colexec/preinsertsecondaryindex/types.go, pkg/sql/colexec/preinsertunique/preinsertunique.go, pkg/sql/colexec/preinsertunique/preinsertunique_test.go, pkg/sql/colexec/preinsertunique/types.go, pkg/sql/util/index_util.go
=> refactor: preinsertunique

pkg/sql/colexec/indexjoin/join.go, pkg/sql/colexec/indexjoin/types.go
=> fix indexjoin

pkg/frontend/mysql_cmd_executor.go, test/distributed/cases/dml/show/show4.result, test/distributed/cases/dml/show/show4.sql
issue #https://github.com/matrixorigin/MO-Cloud/issues/3862
collect table statistics for Ordinary and Materialized
=> [Cherry-pick] collect table statistics for Ordinary and Materialized

pkg/sql/colexec/onduplicatekey/on_duplicate_key.go, pkg/sql/colexec/onduplicatekey/on_duplicate_key_test.go, pkg/sql/colexec/onduplicatekey/types.go, pkg/sql/compile/operator.go
issue #
只处理了比较明确的外层部分的内存复用。中间计算过程中的有点麻烦，这里先不做处理。等龙冉的重写吧
=> Refactor on duplicate key for mem reuse

CODEOWNERS, pkg/sql/colexec/indexbuild/build.go, pkg/sql/colexec/indexbuild/types.go
=> refactor index_build operator

pkg/frontend/back_exec.go, pkg/frontend/mysql_cmd_executor.go, pkg/frontend/session.go, pkg/frontend/types.go, pkg/sql/parsers/dialect/mysql/mysql_lexer.go, pkg/sql/parsers/dialect/mysql/scanner.go
issue #17955
Reuse parser/lexer.
=> Cache a mysql parser in session.

pkg/sql/plan/query_builder.go, test/distributed/cases/pessimistic_transaction/select_for_update.result, test/distributed/cases/pessimistic_transaction/select_for_update.sql
issue #17946
Fix bug: prepare for update with limit clause get error
=> Fix bug: prepare for update with limit clause get error

pkg/frontend/back_exec.go, pkg/frontend/mysql_cmd_executor.go, pkg/frontend/txn.go
issue #https://github.com/matrixorigin/matrixone/issues/17977
问题：一个请求中，有多个语句。当第一个语句为begin时，下一条语句会提交事务。
原因：begin语句时，设置的option，执行完后没有立即清理。导致下一条语句执行时，创建了新事务。
修改：option每次复位。
=> fix txn opt

pkg/common/reuse/checker.go, pkg/common/reuse/factory.go, pkg/common/reuse/mpool_based.go, pkg/common/reuse/pool_test.go, pkg/common/reuse/sync_pool_based.go, pkg/common/reuse/types.go
issue #18055 
to allow defining TypeName on pointer receiver
=> reuse: make ReusableObject pointer type

pkg/sql/colexec/mock_util.go, pkg/sql/colexec/timewin/timewin.go, pkg/sql/colexec/timewin/timewin_test.go, pkg/sql/colexec/timewin/types.go
=> refactor operator of time window

pkg/sql/colexec/left/join.go, pkg/sql/colexec/left/join_test.go, pkg/sql/colexec/left/types.go
=> Refactor LeftJoin

pkg/sql/colexec/loopanti/join.go, pkg/sql/colexec/loopanti/join_test.go, pkg/sql/colexec/loopanti/types.go
=> Refactor LoopAnti

pkg/sql/colexec/insert/insert.go, pkg/sql/colexec/insert/insert_test.go, pkg/sql/colexec/insert/types.go, pkg/sql/colexec/s3util.go
=> Refactor insert for mem reused

pkg/sql/colexec/anti/join.go, pkg/sql/colexec/anti/join_test.go, pkg/sql/colexec/anti/types.go, pkg/sql/colexec/join/join.go
=> Refactor AntiJoin

pkg/sql/colexec/external/external.go, pkg/sql/colexec/external/external_test.go, pkg/sql/colexec/external/parquet.go, pkg/sql/colexec/external/types.go
=> refactor: external

pkg/sql/colexec/top/top.go, pkg/sql/colexec/top/top_test.go, pkg/sql/colexec/top/types.go
=> colexec/top: refactor

pkg/sql/colexec/order/order.go, pkg/sql/colexec/order/order_test.go, pkg/sql/colexec/order/types.go
issue #
Refactor order for mem reused
=> Refactor order for mem reused

pkg/sql/colexec/mergeorder/order.go, pkg/sql/colexec/mergeorder/order_test.go, pkg/sql/colexec/mergeorder/types.go
=> Refactor mergeorder for mem reused

pkg/vm/engine/disttae/logtail_consumer.go
issue https://github.com/matrixorigin/MO-Cloud/issues/3841
pause the client if error occurrs
=> [bug] logtail: pause the client if error occurrs

pkg/sql/colexec/lockop/lock_op.go
issue #18082 
ctx deadline should not retry lock
=> ctx deadline should not retry lock

pkg/sql/colexec/table_function/processlist.go
issue #17687
show sessions not only on normal cns, but also on draining cns.
=> [enhancement] processlist: show sessions on draining cns

pkg/sql/colexec/loopanti/join.go, pkg/sql/colexec/loopleft/join.go, pkg/sql/colexec/loopleft/join_test.go, pkg/sql/colexec/loopleft/types.go
=> Refactor LoopLeft

pkg/sql/colexec/loopjoin/join.go, pkg/sql/colexec/loopjoin/join_test.go, pkg/sql/colexec/loopjoin/types.go
=> Refactor LoopJoin

pkg/sql/colexec/anti/join_test.go, pkg/sql/colexec/join/join_test.go, pkg/sql/colexec/left/join_test.go, pkg/sql/colexec/loopanti/join_test.go, pkg/sql/colexec/loopjoin/join_test.go, pkg/sql/colexec/loopleft/join_test.go
=> Fix Join UT

pkg/sql/colexec/loopsingle/join.go, pkg/sql/colexec/loopsingle/types.go
=> Refactor LoopSingle

pkg/sql/colexec/loopsemi/join.go, pkg/sql/colexec/loopsemi/types.go
=> Refactor LoopSemi

pkg/sql/colexec/mergedelete/mergedelete.go, pkg/sql/colexec/mergedelete/mergedelete_test.go, pkg/sql/colexec/mergedelete/types.go
issue #
并没有专门优化内存复用。只是修正了一个batch没有free的问题。要想更好复用，需要给batch和encodeBatch增加些方法才行。
=> Refactor mergedelete for mem reused

pkg/sql/colexec/mergeblock/mergeblock.go, pkg/sql/colexec/mergeblock/mergeblock_test.go, pkg/sql/colexec/mergeblock/types.go
issue #
只是修复了现有代码中的reset可能不完全的问题。
要想更好的复用，需要对UnmarshalBinary和Relation.write做一些调整才行。这个另外安排PR处理吧
=> Refactor mergeblock for mem reused

pkg/sql/colexec/constraint_util.go, pkg/sql/colexec/deletion/deletion.go, pkg/sql/colexec/deletion/deletion_test.go, pkg/sql/colexec/deletion/types.go
issue #
只处理了普通表的普通delete的内存复用
1、写s3的部分，还要再向罗飞请教后再优化
2、对于partition表的，后面可能辛苦喜亮继续优化
=> refactor deletion for mem reused

pkg/frontend/snapshot.go, pkg/sql/plan/build_dml_util.go, pkg/sql/plan/build_insert.go, pkg/sql/plan/query_builder.go, pkg/sql/plan/stats.go, pkg/sql/plan/types.go
issue https://github.com/matrixorigin/matrixone/issues/16099 https://github.com/matrixorigin/matrixone/issues/16638 https://github.com/matrixorigin/matrixone/issues/16138
fix restore related issues
=> [cherry-pick-17773] : fix restore related issues

pkg/sql/colexec/product/product.go, pkg/sql/colexec/product/types.go, pkg/sql/colexec/productl2/product_l2.go, pkg/sql/colexec/productl2/types.go
=> refactor product and product_L2

pkg/sql/colexec/right/join.go, pkg/sql/colexec/right/types.go, pkg/sql/colexec/rightanti/join.go, pkg/sql/colexec/rightanti/types.go, pkg/sql/colexec/rightsemi/join.go, pkg/sql/colexec/rightsemi/types.go
=> Refactor right(semi/anti) join

pkg/sql/colexec/intersect/intersect.go, pkg/sql/colexec/intersect/intersect_test.go, pkg/sql/colexec/intersect/types.go, pkg/sql/colexec/intersectall/intersectall.go, pkg/sql/colexec/intersectall/intersectall_test.go, pkg/sql/colexec/intersectall/types.go, pkg/sql/colexec/lockop/lock_op.go, pkg/sql/colexec/lockop/lock_op_test.go, pkg/sql/colexec/lockop/types.go, pkg/sql/colexec/minus/minus.go, pkg/sql/colexec/minus/minus_test.go, pkg/sql/colexec/minus/types.go
=> Refactor minus/intersetct(all)/lockop

pkg/container/batch/batch.go, pkg/sql/colexec/filter/filter.go, pkg/sql/colexec/filter/filter_test.go, pkg/sql/colexec/filter/types.go, pkg/sql/colexec/unionall/types.go
issue #
refactor filter operator and unionall operator
=> refacctor fiter and unionall operator

pkg/sql/colexec/product/product.go, pkg/sql/colexec/product/product_test.go, pkg/sql/colexec/productl2/product_l2.go, pkg/sql/colexec/right/join.go, pkg/sql/colexec/right/join_test.go, pkg/sql/colexec/rightanti/join_test.go, pkg/sql/colexec/rightsemi/join_test.go
=> Add Some Join UT

pkg/sql/colexec/mergetop/top_test.go, pkg/sql/colexec/top/top.go, pkg/sql/colexec/top/top_test.go
=> top: fix tests

pkg/sql/colexec/external/external_test.go
=> fix: external test

pkg/common/mpool/alloc.go, pkg/common/mpool/mpool.go, pkg/sql/colexec/mergetop/top.go, pkg/sql/colexec/mergetop/top_test.go
=> fix mergetop

pkg/sql/util/index_util.go
=> fix: TestBuildUniqueKeyBatch

pkg/common/mpool/alloc_tracing.go
=> mpool: fixes

pkg/frontend/types.go, pkg/sql/colexec/connector/connector.go, pkg/sql/colexec/constraint_util.go, pkg/sql/colexec/deletion/types.go, pkg/sql/colexec/dispatch/dispatch.go, pkg/sql/colexec/merge/merge.go, pkg/sql/colexec/projection/projection.go, pkg/sql/colexec/projection/types.go, pkg/sql/colexec/s3util.go, pkg/sql/colexec/shufflebuild/build.go, pkg/sql/compile/compile.go, pkg/sql/compile/scope.go, pkg/vm/pipeline/types.go
=> fix some bug & add some test logic

pkg/sql/colexec/preinsert/preinsert.go
=> bug fixed and make brach can start

pkg/sql/colexec/hashbuild/build.go, pkg/sql/colexec/loopsemi/join.go, pkg/sql/colexec/mergeblock/mergeblock_test.go, pkg/sql/colexec/output/types.go, pkg/sql/colexec/shufflebuild/build.go, pkg/sql/colexec/top/top.go
=> Fix bug to make branch can start

pkg/sql/colexec/group/types.go, pkg/sql/colexec/window/types.go, pkg/sql/colexec/window/window.go, pkg/sql/colexec/window/window_test.go
=> refactor operator of window func

pkg/sql/colexec/fill/fill.go, pkg/sql/colexec/fill/fill_test.go, pkg/sql/colexec/fill/types.go
issue #
refactor operator of fill
=> refactor operator of fill

pkg/common/bloomfilter/bloomfilter.go, pkg/common/bloomfilter/bloomfilter_test.go, pkg/common/bloomfilter/types.go, pkg/container/nulls/nulls.go, pkg/sql/colexec/fuzzyfilter/filter.go, pkg/sql/colexec/fuzzyfilter/filter_test.go, pkg/sql/colexec/fuzzyfilter/types.go
=> refactor fuzzy memory usage

pkg/sql/colexec/mark/join.go, pkg/sql/colexec/mark/join_test.go, pkg/sql/colexec/mark/types.go
=> Refactor MarkJoin

pkg/proxy/server_conn.go, pkg/proxy/tunnel.go, pkg/proxy/tunnel_test.go
issue #17757
fix memory leak when transfer connections.
=> [bug] proxy: fix memory leak when transfer connections.

pkg/sql/colexec/loopjoin/types.go, pkg/sql/colexec/loopleft/types.go, pkg/sql/colexec/loopmark/join.go, pkg/sql/colexec/loopmark/join_test.go, pkg/sql/colexec/loopmark/types.go
=> Refactor LoopMark

pkg/logservice/store_hakeeper_check.go
issue https://github.com/matrixorigin/MO-Cloud/issues/3901
if add commands operation fails occasionally, the cluster will never
startup. so add retry for this operation and 1 minute timeout.
=> [bug] bootstrap: add retry when failed to add schedule cmds in bootstrap

pkg/sql/colexec/fill/fill.go, pkg/sql/colexec/filter/filter_test.go, pkg/sql/colexec/filter/types.go, pkg/sql/colexec/indexjoin/join.go, pkg/sql/colexec/lockop/lock_op.go, pkg/sql/colexec/merge/merge.go, pkg/sql/colexec/mergetop/top.go, pkg/sql/colexec/output/types.go, pkg/sql/colexec/projection/projection.go, pkg/sql/colexec/source/source.go, pkg/sql/compile/scope.go
=> fix some bug for refactor branch

pkg/vm/engine/disttae/transfer.go
issue #11471 
disable want detail during cn transfer tombstones and remove some unused code
=> disable want detail during cn transfer tombstones

pkg/sql/colexec/mergecte/mergecte.go, pkg/sql/colexec/mergecte/mergecte_test.go, pkg/sql/colexec/mergecte/types.go, pkg/sql/compile/compile.go
=> refactor mergecte

pkg/common/pubsub/utils.go, pkg/common/pubsub/utils_test.go, pkg/frontend/authenticate.go, pkg/frontend/publication_subscription.go
issue #16188 
change multiple single sqls to a big batched one
=> Improve perf for pub/sub's crud

pkg/sql/compile/compile.go
issue # https://github.com/matrixorigin/MO-Cloud/issues/3904
fix bug in union scopes
=> fix bug in union scopes

pkg/sql/compile/compile.go, pkg/sql/compile/scope.go
issue #16542
build hashbuild operator in compile time for single parallel join
=> build hashbuild operator in compile time for single parallel join

cmd/mo-service/config.go, etc/launch-with-python-udf-server/python-udf-server.toml
issue #18159 
make launch-udf work
=> fix: fixed UUID for python-udf-server

pkg/vm/engine/disttae/transfer.go, pkg/vm/engine/tae/common/print.go, pkg/vm/engine/types.go
issue #11471 
apply in-memory committed tombstones during transfer
=> fix transfer deletes

pkg/frontend/snapshot.go
issue #17402
fix restore cluster table
=> fix restore cluster table

pkg/sql/colexec/connector/types.go, pkg/sql/colexec/dispatch/types.go, pkg/sql/colexec/merge/types.go
=> fix some bug

pkg/sql/colexec/deletion/deletion.go, pkg/sql/colexec/insert/insert.go, pkg/sql/colexec/order/order.go, pkg/sql/colexec/top/top.go, pkg/sql/compile/compile.go, pkg/sql/compile/operator.go, pkg/sql/compile/remoterun.go, pkg/sql/compile/scope.go
=> Buf fix for insert delete

pkg/sql/compile/compile.go
issue #16542 
reduce pipelines in value_scan
=> reduce pipelines in value_scan

pkg/sql/colexec/connector/connector.go, pkg/sql/colexec/merge/merge.go, pkg/sql/colexec/mergeblock/mergeblock.go, pkg/sql/colexec/mergeblock/types.go, pkg/sql/colexec/mergedelete/mergedelete.go, pkg/sql/colexec/mergedelete/types.go
=> fix bug: count(*) & affectRows incorrect

pkg/sql/colexec/deletion/deletion.go, pkg/sql/colexec/deletion/types.go, pkg/sql/colexec/insert/insert.go, pkg/sql/colexec/insert/types.go, pkg/sql/colexec/mergetop/top.go, pkg/sql/colexec/offset/offset.go, pkg/sql/colexec/preinsert/preinsert.go, pkg/sql/colexec/product/product.go, pkg/sql/plan/function/list_builtIn.go
=> fix bug error

pkg/sql/colexec/group/group.go, pkg/sql/colexec/group/group_test.go, pkg/sql/colexec/group/reset.go, pkg/sql/colexec/group/types.go, pkg/sql/compile/operator.go, pkg/sql/compile/remoterun.go, pkg/sql/compile/scope.go
=> Implement Reset() for Group Operator and do codes clean up.

pkg/frontend/mysql_cmd_executor.go
issue #https://github.com/matrixorigin/matrixone/issues/14926
negative cpu log too much, ture it as debug log
=> negative cpu log too much, ture it as debug log

pkg/frontend/test/engine_mock.go, pkg/sql/compile/compile.go, pkg/vm/engine/disttae/tombstones.go, pkg/vm/engine/types.go
issue #11471 
fix tombstone data
=> fix tombstone data

pkg/sql/colexec/group/types.go, pkg/sql/colexec/preinsert/preinsert.go, pkg/sql/colexec/preinsert/types.go, pkg/sql/colexec/shuffle/shuffle.go, test/distributed/cases/function/func_regular_substr.result
=> make more bvt pass

pkg/shardservice/storage_mo.go, pkg/util/status/logtail_client.go, pkg/vm/engine/disttae/logtail_consumer.go, pkg/vm/engine/disttae/logtail_consumer_test.go
issue #16471 
Integrated sharding and logtail
=> make sharding support logtail

pkg/sql/colexec/shuffle/shuffle.go
=> fix shuffle

pkg/sql/colexec/mergeorder/types.go
=> mergeorder do not reset status

pkg/vm/engine/disttae/pk_filter_mem.go, pkg/vm/engine/disttae/transfer.go, pkg/vm/engine/test/disttae_engine_test.go
issue https://github.com/matrixorigin/matrixone/issues/11471
fix a transfer error and add ut to ensure everything goes well
=> fix transfer deletes and add ut

pkg/embed/cluster_test.go, pkg/embed/operator.go, pkg/embed/types.go
issue #16471 
add more cluster test case
=> add more cluster test case

pkg/sql/colexec/mergegroup/group.go
=> remove an redundant codes.

pkg/container/batch/batch.go, pkg/sql/colexec/table_function/current_account.go, pkg/sql/colexec/table_function/generate_series.go, pkg/sql/colexec/table_function/generate_series_test.go, pkg/sql/colexec/table_function/meta_scan.go, pkg/sql/colexec/table_function/metadata_scan.go, pkg/sql/colexec/table_function/processlist.go, pkg/sql/colexec/table_function/system_view.go, pkg/sql/colexec/table_function/system_view_test.go, pkg/sql/colexec/table_function/table_function.go, pkg/sql/colexec/table_function/table_function_test.go, pkg/sql/colexec/table_function/types.go, pkg/sql/colexec/table_function/unnest.go, pkg/sql/colexec/table_function/unnest_test.go
This is a relatively large refactor.   Old table function impl is
broken.   Restructure the code.
issue #
Refactor table function code.   It is way worse than I expected, so I ends up rewrite some code.    I will be amazed if this thing works at all, but good part is that this should not block real work in pipeline refactoring.   The code need to be redone, period.
=> Pipeline Refactor: table function

pkg/sql/colexec/table_function/current_account.go, pkg/sql/colexec/table_function/generate_series.go, pkg/sql/colexec/table_function/meta_scan.go, pkg/sql/colexec/table_function/metadata_scan.go, pkg/sql/colexec/table_function/processlist.go, pkg/sql/colexec/table_function/types.go, pkg/sql/colexec/table_function/unnest_test.go, test/distributed/cases/function/table_func_generate_series.result
=> fix table function bug. make bvt pass

pkg/frontend/back_exec.go
issue #https://github.com/matrixorigin/matrixone/issues/17742
backses结束时，rollback其创建的事务。通常事务都提交了。如果有泄露，rollback 会结束事务。
=> add rollback txn

pkg/frontend/snapshot.go, test/distributed/cases/snapshot/restore_sub_db.result, test/distributed/cases/snapshot/restore_sub_db.sql
issue #18023 
Support restore sub in 1.2-dev
=> Support restore sub in 1.2-dev

pkg/sql/colexec/connector/connector.go, pkg/sql/colexec/dispatch/dispatch.go, pkg/sql/colexec/filter/filter.go, pkg/sql/colexec/merge/merge.go, pkg/sql/colexec/merge/types.go, pkg/sql/colexec/preinsertsecondaryindex/types.go, pkg/sql/colexec/preinsertunique/types.go, pkg/sql/util/index_util.go
=> Improve tpcc performance

pkg/sql/colexec/dispatch/dispatch.go, pkg/sql/colexec/merge/merge.go
=> bug dispatch & merge bug

pkg/sql/colexec/connector/connector.go
=> fix bvt(window.sql) panic

pkg/sql/colexec/evalExpressionReset.go, pkg/sql/colexec/filter/filter_test.go, pkg/sql/colexec/filter/types.go, pkg/sql/colexec/merge/merge.go, pkg/sql/colexec/merge/merge_test.go, pkg/sql/colexec/mergegroup/reset.go, pkg/sql/colexec/table_function/table_function.go, pkg/vm/engine/test/reader_test.go
=> Fix some CI error

pkg/sql/colexec/connector/connector.go, pkg/sql/colexec/merge/merge.go
=> use dup for merge

pkg/sql/colexec/dispatch/dispatch.go
=> fix ci error

pkg/vm/engine/test/reader_test.go
=> fix ut bug

pkg/sql/colexec/constraint_util.go, pkg/sql/colexec/dispatch/dispatch.go, pkg/sql/colexec/evalExpression.go, pkg/sql/colexec/external/parquet_test.go, pkg/sql/colexec/group/group.go, pkg/sql/colexec/index_metadata.go, pkg/sql/colexec/mergecte/mergecte.go, pkg/sql/colexec/mergegroup/reset.go, pkg/sql/colexec/s3util.go, pkg/sql/colexec/sample/poolData.go, pkg/sql/colexec/sample/sample.go, pkg/sql/colexec/sample/samplePool.go, pkg/sql/colexec/sample/sample_test.go, pkg/sql/plan/build_ddl.go, pkg/vm/engine/disttae/txn.go
=> Clean come code

pkg/sql/colexec/connector/connector.go, pkg/sql/colexec/dispatch/dispatch.go, pkg/sql/colexec/dispatch/sendfunc.go, pkg/sql/colexec/merge/merge.go, pkg/sql/colexec/merge/types.go, pkg/sql/colexec/window/types.go
=> Improve performance

pkg/container/nulls/nulls.go
issue #11471 
optimize nulls.Null merge
=> optimize nulls.Null merge

test/distributed/cases/stage/stage.result, test/distributed/cases/stage/stage.sql
issue #17820
comment out the failed cases in bvt test in distributed environment
___
Bug fix
___
- Updated the `stage.result` file to reflect new timestamps and stage IDs for stage creation entries.
- Commented out non-functional SQL test cases in `stage.sql` related to counting entries in stages.
- Removed test case results from `stage.result` that were not working in a distributed environment.
___
<tr>
<td>
<details>
<summary><strong>stage.result</strong><dd><code>Update stage result entries and remove test case results</code>&nbsp; </dd></summary>
<hr>
test/distributed/cases/stage/stage.result
<li>Updated timestamps for stage creation entries.<br> <li> …
=> comment out not working test cases in distributed env

pkg/fileservice/s3_fs.go
issue # https://github.com/matrixorigin/MO-Cloud/issues/3834
to help debugging.
=> fileservice: panic if S3FS.Write return io.EOF

pkg/frontend/snapshot.go, test/distributed/cases/snapshot/restore_fk.result, test/distributed/cases/snapshot/restore_fk.sql, test/distributed/cases/snapshot/restore_fk_master_not_exists.result, test/distributed/cases/snapshot/restore_fk_master_not_exists.sql, test/distributed/cases/snapshot/restore_fk_referenced_db.result, test/distributed/cases/snapshot/restore_fk_referenced_db.sql, test/distributed/cases/snapshot/restore_fk_restore_master_table.result, test/distributed/cases/snapshot/restore_fk_restore_master_table.sql, test/distributed/cases/snapshot/snapshot_restore_to_table_fk_2.result, test/distributed/cases/snapshot/snapshot_restore_to_table_fk_2.sql, test/distributed/cases/snapshot/sys_restore_view_to_newnonsys_account.result
issue #18218
refactor restore fk on 1.2-dev
=> refactor restore fk on 1.2-dev

pkg/objectio/cache.go
issue #[17850 ](https://github.com/matrixorigin/MO-Cloud/issues/3526)
change fs cache
=> change fs cache

test/distributed/cases/snapshot/restore_fk_table.result, test/distributed/cases/snapshot/restore_fk_table.sql, test/distributed/cases/snapshot/sys_restore_to_nonsys_account.sql
add case for restoring fk table
issue #https://github.com/matrixorigin/matrixone/issues/18218
add case for restoring fk table
=> add restore fk table case

pkg/container/hashtable/int64_hash_map.go, pkg/container/hashtable/string_hash_map.go
issue #18150 
the dup function is never called, remove this
=> remove unused code in hashmap

pkg/sql/compile/compile.go
- [x ] BUG
issue #17318 
1. Fix bug.
=> [#17318]CherryPick-fix bug for snapshot read

pkg/sql/colexec/offset/offset.go, test/distributed/cases/dml/select/limit.result, test/distributed/cases/dml/select/limit.sql
issue https://github.com/matrixorigin/MO-Cloud/issues/3944
fix bug: offset not work
=> fix bug: offset operator not work

pkg/proxy/client_conn.go, pkg/proxy/client_conn_test.go, pkg/proxy/conn_cache_test.go, pkg/proxy/conn_migration_test.go, pkg/proxy/event.go, pkg/proxy/event_test.go, pkg/proxy/handler_test.go, pkg/proxy/plugin_test.go, pkg/proxy/router.go, pkg/proxy/util.go, pkg/proxy/util_test.go
issue #18299
proxy broadcast upgrade statement to all cns
=> [feature] proxy: broadcast upgrade statement to all cns

pkg/logservice/store_test.go, pkg/vm/engine/tae/db/test/db_test.go, pkg/vm/engine/tae/iface/txnif/consts.go, pkg/vm/engine/tae/txn/txnimpl/base_table.go, pkg/vm/engine/tae/txn/txnimpl/table.go
issue #11804
Update dedup policy
=> Update dedup policy

pkg/fileservice/disk_cache.go, pkg/fileservice/disk_cache_test.go
issue # https://github.com/matrixorigin/MO-Cloud/issues/3918
disk cache fixes
=> fileservice: disk cache fixes

pkg/sql/colexec/offset/offset.go, test/distributed/cases/dml/select/limit.result, test/distributed/cases/dml/select/limit.sql
issue https://github.com/matrixorigin/MO-Cloud/issues/3944
移除了之前处理order算子问题事忘记删掉的几行查错时的代码
=> fix bug: offset get incorrect result

pkg/container/types/decimal.go, pkg/sql/plan/base_binder.go, pkg/sql/plan/function/func_binary.go, test/distributed/cases/function/func_math_ceil.result, test/distributed/cases/function/func_math_ceil.test, test/distributed/cases/function/func_math_floor.result, test/distributed/cases/function/func_math_floor.test, test/distributed/cases/function/func_math_round.result, test/distributed/cases/function/func_math_round.test
issue https://github.com/matrixorigin/MO-Cloud/issues/3955
Fix Floor/Ceil/Round Decimal (1.2-dev)
=> Fix Floor/Ceil/Round Decimal (1.2-dev)

pkg/vm/engine/tae/catalog/schema.go, pkg/vm/engine/test/disttae_engine_test.go, pkg/vm/engine/test/partition_state_test.go, pkg/vm/engine/test/reader_test.go, pkg/vm/engine/test/testutil/tae_engine.go, pkg/vm/engine/test/testutil/util.go
issue #18432 
add some utils for testing the reader
=> add some disttae testing utils

pkg/fileservice/object_storage_semaphore.go
issue #17001 
should hold the semaphore during the Read, otherwise it will not limit the I/O concurrency to S3.
=> fileservice: release semaphore after reader close in objectStorageSemaphore.Read

pkg/lockservice/lock_table_local.go, pkg/lockservice/waiter.go, pkg/lockservice/waiter_events.go
issue #13221 
fix ut TestManyRangeLockInManyGoroutines data race
=> fix ut TestManyRangeLockInManyGoroutines data race

pkg/embed/cluster_test.go, pkg/tests/shard/replica_test.go
issue #16471
skip restart cn test case
___
tests
___
- Skipped the `TestRestartCN` test case in `pkg/embed/cluster_test.go` by adding `t.SkipNow()`.
- Skipped the `TestReplicaBalance` test case in `pkg/tests/shard/replica_test.go` by adding `t.SkipNow()`.
- These changes prevent the specified test cases from running, likely for debugging or temporary exclusion purposes.
___
<tr>
<td>
<details>
<summary><strong>cluster_test.go</strong><dd><code>Skip the `TestRestartCN` test case</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary> …
=> skip restart cn test case

pkg/common/malloc/checked_allocator.go, pkg/common/malloc/config.go, pkg/common/malloc/inuse_tracking_allocator.go, pkg/common/malloc/leaks_tracking_allocator.go, pkg/common/malloc/managed_allocator.go, pkg/common/malloc/managed_allocator_test.go, pkg/common/malloc/metrics_allocator.go, pkg/common/malloc/profile_allocator.go, pkg/common/malloc/profiler.go, pkg/common/malloc/random_allocator.go, pkg/common/malloc/read_only_allocator.go, pkg/common/malloc/sharded_allocator.go, pkg/common/malloc/size_bounded_allocator.go, pkg/frontend/types.go
issue #18701 
malloc: make decorator types generic
malloc: add cacheline padding to ShardedAllocator
___
Enhancement
___
- Implemented generics for various allocator types, including `CheckedAllocator`, `InuseTrackingAllocator`, `LeaksTrackingAllocator`, `ManagedAllocator`, `MetricsAllocator`, `ProfileAllocator`, `RandomAllocator`, `ReadOnlyAllocator`, `ShardedAllocator`, and `SizeBoundedAllocator`.
- Refactored `Profiler` to improve type safety and performance by removing unsafe operations and optimizing stack handling.
- Added cacheline padding to `ShardedAllocator` to enhance performance.
- Updated tests to accommodate changes in `ManagedAllocator`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><detail …
=> malloc: optimize profiler

pkg/vm/engine/tae/txn/txnbase/txnmgr.go
issue #17866
fix not get txn.
___
Bug fix
___
- Fixed a bug in the `GetOrCreateTxnWithMeta` function where it failed to retrieve an existing transaction from the `IDMap`.
- Added logic to correctly assign the transaction if it already exists, preventing unnecessary creation of a new transaction.
___
<tr>
<td>
<details>
<summary><strong>txnmgr.go</strong><dd><code>Fix transaction retrieval logic in `GetOrCreateTxnWithMeta`</code></dd></summary>
<hr>
pkg/vm/engine/tae/txn/txnbase/txnmgr.go
<li>Fixed logic to retrieve an existing transaction from <code>IDMap</code>.<br> <li> Added code to assign the transaction if it exists.<br>
</details>
</td>
<td><a …
=> fix GetOrCreateTxnWithMeta not get txn error

pkg/vm/engine/test/change_handle_test.go
issue #18629 
skip TestChangesHandle3 and fix it later
___
Bug fix
___
- Skipped the `TestChangesHandle3` unit test in `pkg/vm/engine/test/change_handle_test.go` to prevent test failures.
- Added a comment to indicate that the test requires fixing in the future.
___
<tr>
<td>
<details>
<summary><strong>change_handle_test.go</strong><dd><code>Skip and mark `TestChangesHandle3` for future fixing</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pkg/vm/engine/test/change_handle_test.go
<li>Skipped the <code>TestChangesHandle3</code> unit test.<br> <li> Added a comment indicating the test needs fixing.<br>
</details>
</td>
<td><a …
=> skip TestChangesHandle3

pkg/vm/engine/disttae/stats.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4124
fix ndv calculation to make it more accurate
=> cp to 1.2-dev 'fix ndv calculation to make it more accurate'

pkg/vm/engine/disttae/stats.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4124
fix ndv calculation to make it more accurate
=> fix ndv calculation to make it more accurate

pkg/sql/plan/function/func_builtin_json.go, test/distributed/cases/function/func_json_extract.result, test/distributed/cases/function/func_json_extract.test
issue #https://github.com/matrixorigin/MO-Cloud/issues/4066
fix json extract function
=> fix json extract function(#1.2 hotfix)

pkg/sql/plan/agg_pushdown_pullup.go, pkg/sql/plan/runtime_filter.go
fix the condition for runtime filters, try to push runtime filters in more cases. fix some comment
Approved by: @aunjgr
issue #https://github.com/matrixorigin/MO-Cloud/issues/4108#issuecomment-2360241441
cp to 1.2-dev 'fix the condition for runtime filters (#18496)'
=> cp to 1.2-dev 'fix the condition for runtime filters (#18496)'

pkg/frontend/util.go
issue #18894
fix connection string parsing
=> fix connection string parsing

pkg/frontend/mysql_cmd_executor.go, test/distributed/cases/pessimistic_transaction/prepare.result, test/distributed/cases/pessimistic_transaction/prepare.sql
issue https://github.com/matrixorigin/matrixone/issues/18957
Fix bug: get params index error when retry prepare insert stmt
=> Fix bug: get params index error when retry prepare insert stmt

pkg/util/metric/v2/dashboard/grafana_dashboard_mem.go, pkg/util/metric/v2/metrics.go
issue #17593  
update memory dashboard
=> metric: update memory dashboard

pkg/sql/plan/apply_indices.go, pkg/sql/plan/utils.go
issue #17718 
code refactoring of index in optimizer
=> code refactoring of index in optimizer

pkg/vm/engine/tae/db/open.go, pkg/vm/engine/tae/db/test/db_test.go, pkg/vm/engine/tae/db/test/storage_usage_test.go, pkg/vm/engine/tae/db/testutil/engine.go, pkg/vm/engine/tae/iface/handle/relation.go, pkg/vm/engine/tae/iface/txnif/types.go, pkg/vm/engine/tae/rpc/handle.go, pkg/vm/engine/tae/tables/functions.go, pkg/vm/engine/tae/txn/txnbase/handle.go, pkg/vm/engine/tae/txn/txnbase/store.go, pkg/vm/engine/tae/txn/txnimpl/base_table.go, pkg/vm/engine/tae/txn/txnimpl/relation.go, pkg/vm/engine/tae/txn/txnimpl/store.go, pkg/vm/engine/tae/txn/txnimpl/table.go, pkg/vm/engine/tae/txn/txnimpl/table_space.go, pkg/vm/engine/tae/txn/txnimpl/txndb.go
=> fix tn transfer s3 tombstone

pkg/sql/plan/build_test.go, pkg/sql/plan/visit_plan.go, pkg/sql/plan/visit_plan_rule.go, test/distributed/cases/pessimistic_transaction/prepare.result, test/distributed/cases/pessimistic_transaction/prepare.sql
issue #18957
Fix bug: prepare for on duplicate key can not get Parameter
=> Fix bug: prepare for on duplicate key can not get Parameter

pkg/common/malloc/metrics_allocator.go, pkg/common/malloc/sharded_counter.go, pkg/common/mpool/alloc.go, pkg/common/mpool/mpool.go, pkg/common/mpool/mpool_test.go, pkg/common/reuse/mpool_based.go, pkg/container/batch/batch.go, pkg/container/batch/types.go, pkg/container/types/bytes.go, pkg/container/vector/tools.go, pkg/container/vector/vector.go, pkg/vm/engine/tae/containers/utils.go
issue #17151 
allow allocate off-heap Vector and Batch
=> batch: add NewOffHeap, NewOffHeapWithSize; vector: add NewOffHeapVecWithType, NewOffHeapVec

pkg/sql/plan/apply_indices.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4174
fix a bug in index
=> fix a bug in index

pkg/queryservice/query_service.go
issue https://github.com/matrixorigin/MO-Cloud/issues/3823 https://github.com/matrixorigin/matrixone/issues/16417 https://github.com/matrixorigin/MO-Cloud/issues/4085
remove temp context timeout
=> [enhancement] query service: remove temp context timeout

test/distributed/cases/dml/insert/insert_duplicate.result, test/distributed/cases/dml/insert/insert_duplicate.sql
issue #18710 
add on duplicate update cases
___
Bug fix, Tests
___
- Added new test cases to handle duplicate key updates in the `serial_numbers` table.
- Created the `serial_numbers` table with a unique constraint on `biz_type` and `namespace`.
- Implemented `ON DUPLICATE KEY UPDATE` logic to increment the `sn` field.
- Verified the correct handling of duplicate entries through SQL queries.
___
<tr>
<td>
<details>
<summary><strong>insert_duplicate.result</strong><dd><code>Add test cases for handling duplicate key updates</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
test/distributed/cases/dml/insert/insert_duplicate.result …
=> add on duplicate update cases

README.md, README_CN.md
issue #[1131](https://github.com/matrixorigin/matrixorigin.io.cn/issues/1131)
___
Documentation
___
- Updated the version number in the documentation from v1.2.1 to v24.1.2.4.
- Modified all relevant URLs in both English and Chinese README files to point to the new version's documentation.
- Adjusted branch version references in deployment instructions to reflect the new version.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Update documentation links and version references to v24.1.2.4</code></dd></summary>
<hr>
README.md
<li>Updated version number from v1.2.1 to v24.1.2.4 in documentation <br>links.<br> <li> Modified URLs to …
=> change version from v1.2.1 to v24.1.2.4

pkg/lockservice/lock_table_allocator.go, pkg/lockservice/service_test.go
issue #18922 
can retry to obtain active txns
=> can retry to obtain active txns

pkg/vm/engine/disttae/logtailreplay/change_handle.go, pkg/vm/engine/test/change_handle_test.go
issue #18879
skip transfer tombstone in change handle
=> skip transfer tombstone in change handle

pkg/container/batch/batch.go, pkg/sql/colexec/mergedelete/mergedelete.go, pkg/sql/compile/remoterun.go, pkg/sql/compile/remoterunClient.go, pkg/vm/engine/disttae/engine_test.go, pkg/vm/process/process.go
issue #17151 
move more memory to off-heap to reduce GC cost.
=> move more memory to off-heap

pkg/lockservice/service_test.go
issue #16739 
fix TestReLockInRollingRestartCN
=> fix TestReLockInRollingRestartCN

pkg/pb/statsinfo/shuffle.go
issue #11905
fix shufflerange miss strvalue
=> fix shufflerange miss strvalue

pkg/sql/compile/analyze_module.go, pkg/sql/compile/compile.go, pkg/util/trace/impl/motrace/statistic/stats_array.go, pkg/vm/process/operator_analyzer.go
issue https://github.com/matrixorigin/matrixone/issues/18620
Supplement the compilation of query statistics information
=> Supplement the compilation of query statistics information

pkg/sql/plan/associative_law.go, pkg/sql/plan/opt_misc.go, pkg/sql/plan/stats.go
issue https://github.com/matrixorigin/MO-Cloud/issues/4183
Fix ColRef Error(1.2-dev)
=> Fix ColRef Error(1.2-dev)

pkg/container/vector/vector.go
issue #19101 
fix wrong argument.
=> vector: fix wrongly passed offHeap argument

pkg/frontend/pitr.go, pkg/frontend/pitr_test.go
issue #19070
fix pitr restore valid start time
=> fix pitr restore valid start time

go.mod, test/distributed/cases/ddl/create_retention_table.result, test/distributed/cases/ddl/create_retention_table.sql
issue #18886
prolong sleep time during retention bvt test
=> prolong sleep time

pkg/sql/colexec/shuffle/shuffle.go
issue #19054 
allocate sels only when needed
=> optimize memory allocation in shuffle operator

pkg/proxy/client_conn.go
issue #19124
do not need to close client in each connection.
=> [bug] proxy: do not need to close client in each connection.

pkg/common/malloc/default.go, pkg/common/malloc/default_test.go, pkg/common/malloc/managed_allocator.go, pkg/common/malloc/managed_allocator_test.go, pkg/common/mpool/malloc.go, pkg/container/hashtable/malloc.go, pkg/fileservice/malloc.go, pkg/frontend/types.go, pkg/util/metric/v2/dashboard/grafana_dashboard_mem.go, pkg/util/metric/v2/mem.go, pkg/util/metric/v2/metrics.go
issue #18636 
add hashmap and mpool metrics
=> metric: add hashmap and mpool metrics

pkg/sql/plan/build_dml_util.go
issue #19120
refactor build_dml_util.go and cleanup the code. 
Move the index related code to functions.
___
enhancement
___
- Refactored the `build_dml_util.go` file to improve code organization and readability by modularizing index handling.
- Introduced new functions to handle delete and insert operations for regular, master, and multi-table indexes.
- Removed redundant and lengthy inline code by moving logic into separate functions.
- Enhanced error handling for unsupported index algorithms.
___
<tr>
<td>
<details>
<summary><strong>build_dml_util.go</strong><dd><code>Refactor and modularize index handling in DML operations</code>&nbsp; </dd></summary> …
=> refactoring build_dml_util.go

pkg/catalog/types.go, pkg/objectio/const.go, pkg/sql/colexec/aggexec/aggResult.go, pkg/vm/engine/disttae/local_disttae_datasource.go, pkg/vm/engine/disttae/local_disttae_datasource_test.go, pkg/vm/engine/disttae/transfer_util.go, pkg/vm/engine/engine_util/container_util.go, pkg/vm/engine/engine_util/reader.go, pkg/vm/engine/engine_util/reader_util.go, pkg/vm/engine/engine_util/sinker.go, pkg/vm/engine/engine_util/tombstone_data_test.go, pkg/vm/engine/tae/blockio/read.go, pkg/vm/engine/tae/blockio/utils_test.go, pkg/vm/engine/tae/blockio/writer.go, pkg/vm/engine/tae/blockio/writer_test.go, pkg/vm/engine/tae/catalog/model.go, pkg/vm/engine/tae/db/test/db_test.go, pkg/vm/engine/test/reader_test.go, pkg/vm/engine/test/sinker_test.go
issue #18631 
refactor read related code for physical address column
=> refactor read related code for physical address column

pkg/sql/plan/shuffle.go, pkg/sql/plan/shuffle_test.go
issue #9747 
set upper limit of degree of parallelism for shuffle plan
=> set upper limit of degree of parallelism for shuffle plan 

pkg/vm/engine/tae/db/merge/policyOverlap.go, pkg/vm/engine/tae/index/zm.go, pkg/vm/engine/tae/index/zm_test.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4145
Consider truncation of zm in determining whether two ZMs intersect
=> fix zm compare method in processing zm-based merge

pkg/cdc/reader.go, pkg/cdc/reader_test.go, pkg/cdc/sinker.go, pkg/cdc/sinker_test.go, pkg/cdc/types.go, pkg/cdc/types_test.go, pkg/util/metric/v2/dashboard/grafana_dashboard_frontend.go, pkg/util/metric/v2/frontend.go, pkg/util/metric/v2/metrics.go
issue #18908 #19009
add metric && simplify sinker
=> add metric && simplify sinker

pkg/datasync/syncer_test.go, pkg/frontend/pitr.go, pkg/frontend/pitr_test.go
issue #19173 
add error condition for pitr restore
=> add error condition for pitr restore

pkg/sql/colexec/anti/join.go, pkg/sql/colexec/anti/types.go, pkg/sql/colexec/semi/join.go, pkg/sql/colexec/semi/types.go
issue #19054 
reuse eligible in semi and anti join
=> reuse eligible in semi and anti join

pkg/common/malloc/profiler.go
issue #19188 
fix memory leak in malloc profiler
=> malloc: optimize profiler to avoid memory leak

pkg/frontend/publication_subscription.go, pkg/frontend/publication_subscription_test.go
=> fix show subs

pkg/tnservice/factory.go
issue https://github.com/matrixorigin/matrixone/issues/19183
fix TN to HAKeeper connection when using discovery-address
=> fix: fixed tn hakeeper client config

pkg/embed/cluster.go, pkg/embed/cluster_test.go
issue #19133 
isolate embed multi cluster by file based cluster id.
=> isolate embed multi cluster by file based cluster id

pkg/datasync/consumer.go, pkg/datasync/consumer_test.go, pkg/datasync/entry.go, pkg/datasync/entry_test.go, pkg/datasync/log_client_test.go, pkg/datasync/producer.go, pkg/datasync/syncer.go, pkg/logservice/client_test.go, pkg/logservice/rsm.go, pkg/logservice/rsm_test.go, pkg/logservice/store_test.go
issue #19268
add log for the syncing files
=> add log for the syncing files

pkg/shardservice/service.go, pkg/shardservice/service_test.go
issue #19319 
fix get replica panic on disabled shardservice
=> fix get replica panic on disabled shardservice

pkg/proxy/client_conn_test.go, pkg/proxy/event_test.go, pkg/proxy/router_test.go, pkg/proxy/server_conn.go, pkg/proxy/server_conn_test.go
issue #19302 #19289 #19323
release resources in UT
=> [bug] release resources in UT

pkg/common/malloc/profile_allocator.go, pkg/common/malloc/profiler.go, pkg/common/malloc/profiler_test.go
issue #19188 
refactor profiler
=> malloc: refactor Profiler

pkg/container/vector/vector.go, pkg/container/vector/vector_test.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4253
Intersection2Vector has corn cases not covered.
=> sync to main: fix Intersection2Vector panic

pkg/lockservice/rpc_test.go, pkg/lockservice/service_remote_test.go, pkg/lockservice/service_test.go
issue #https://github.com/matrixorigin/matrixone/issues/19082
extend timeout period for lockservice ut
=> extend timeout period for lockservice ut

pkg/cdc/reader.go, pkg/cdc/reader_test.go
issue #19387
fix recognize stale read
=> fix recognize stale read

pkg/sql/plan/opt_misc.go
issue #19405 
Optimize Hash On Primary Key
=> Optimize Hash On Primary Key

pkg/objectio/const.go, pkg/vm/engine/disttae/local_disttae_datasource.go, pkg/vm/engine/disttae/tools.go, pkg/vm/engine/disttae/transfer.go, pkg/vm/engine/disttae/txn.go, pkg/vm/engine/disttae/txn_table.go, pkg/vm/engine/disttae/txn_table_sharding_handle.go, pkg/vm/engine/engine_util/reader.go
issue #18432 
1. avoid heap allocation
2. code refactor
=> optimize reader 

pkg/sql/compile/compile.go
issue #https://github.com/matrixorigin/matrixone/issues/19409
all scopes should update the txn offset, or the reader will receive a 0 txnOffset,
that cause a dml statement can not see the previous statements' operations.
=> update the scopes `txnOffset` when reuse compile.

pkg/common/malloc/profile_allocator.go, pkg/common/malloc/profiler.go, pkg/common/malloc/profiler_test.go
issue #19188
fix bug in profiler counter
=> malloc: make profiler counters monotonic

pkg/frontend/pitr.go
issue #19426 
fix restore error info
=> fix restore error info

pkg/sql/colexec/apply/apply.go, pkg/sql/colexec/apply/types.go
issue #10060 #19437
fix apply panic
=> fix apply panic

pkg/taskservice/task_service_cron.go
issue #19112
remove some unnecessary logs.
=> remove some log in task service

pkg/sql/compile/compile.go, test/distributed/cases/snapshot/restore_pub_sub.result, test/distributed/cases/snapshot/restore_pub_sub.sql
add case for restoring pub-sub
issue #https://github.com/matrixorigin/matrixone/issues/19325
add case for restoring pub-sub
=> add case for restoring pub-sub.

pkg/vm/engine/disttae/local_disttae_datasource.go
- [x ] BUG
issue #19072 
1. Fix bug.
=> [#19072]Fix bug

pkg/frontend/query_result.go, pkg/frontend/util.go, pkg/sql/colexec/evalExpression.go, pkg/sql/colexec/evalExpressionOpt.go, pkg/sql/colexec/evalExpression_test.go, pkg/sql/colexec/hashbuild/build.go, pkg/sql/colexec/onduplicatekey/on_duplicate_key.go, pkg/sql/compile/compile.go, pkg/sql/compile/operator.go, pkg/sql/plan/external.go, pkg/sql/plan/partition_prune.go, pkg/sql/plan/partition_util.go, pkg/sql/plan/result_scan.go, pkg/sql/plan/rule/constant_fold.go, pkg/sql/plan/utils.go
issue #19146 
使用4个意义更明确的函数来替代EvalExpressionOnce.
=> remove EvalExpressionOnce and do code clean.

pkg/sql/colexec/filter/filter.go
issue #19054 
optimize shrink batch in filter operator
=> optimize shrink batch in filter operator

pkg/common/malloc/class_allocator.go, pkg/common/malloc/fixed_size_allocator.go, pkg/common/malloc/fixed_size_mmap_allocator.go, pkg/common/malloc/fixed_size_sync_pool_allocator.go, pkg/common/malloc/mmap_darwin.go, pkg/common/malloc/mmap_linux.go
issue #19451
optimize to zero less.
=> malloc: optimize zeroing

pkg/sql/compile/compile.go, pkg/sql/plan/stats.go
issue #19470 
tune down degree of parallelism for prepared statement
=> tune down degree of parallelism for prepared statement

pkg/container/vector/vector.go, pkg/container/vector/vector_test.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4253
see the details in the issue
=> sync to 1.2: fix intersection2Vector panic

pkg/fileservice/bytes.go, pkg/fileservice/caching_file_service_test.go, pkg/fileservice/example_test.go, pkg/fileservice/file_service.go, pkg/fileservice/file_service_test.go, pkg/fileservice/io_entry.go, pkg/fileservice/local_fs.go, pkg/fileservice/mem_cache_test.go, pkg/fileservice/s3_fs.go, pkg/objectio/constructors.go, pkg/objectio/funcs.go
issue #19458 
less memory clearing
=> fileservice, objectio: less memory clearing

pkg/cdc/sinker.go, pkg/cdc/sinker_test.go
issue #18908
left reserved space in sqlBuf
=> left reserved space in sqlBuf

pkg/frontend/compiler_context.go
issue #19384 
change update frequency for stats
=> change update frequency for stats

go.mod, go.sum, pkg/fileservice/disk_cache_test.go, pkg/fileservice/file_service_bench_test.go, pkg/fileservice/file_service_test.go, pkg/fileservice/memory_fs_test.go, pkg/fileservice/object_storage_test.go, pkg/fileservice/qcloud_sdk.go, pkg/fileservice/qcloud_sdk_test.go, pkg/fileservice/s3_fs.go
issue #19488 
replace minio SDK with QCloud SDK on COS
=> fileservice: add QCloudSDK

pkg/tests/shard/partition_based_test.go, pkg/vm/engine/disttae/txn_table_sharding.go
issue #19202
fix lost read at param
=> fix lost read at param

cmd/mo-service/debug_connections.go, cmd/mo-service/debug_connections_test.go
issue #17001 
improve conntrack to help debugging.
=> mo-service: group conntrack stats by host port

pkg/cdc/reader.go, pkg/cnservice/distributed_tae.go, pkg/cnservice/server_task.go, pkg/cnservice/types.go, pkg/frontend/cdc.go, pkg/frontend/cdc_test.go, pkg/util/metric/v2/dashboard/grafana_dashboard_frontend.go, pkg/util/metric/v2/frontend.go, pkg/util/metric/v2/metrics.go
issue #19009
use independent mpool for cdc tasks
=> use independent mpool for cdc tasks

pkg/cdc/reader.go, pkg/cdc/reader_test.go, pkg/cdc/util.go
issue #19013
add enter/exit running sql
=> add enter/exit running sql

pkg/vm/engine/tae/catalog/catalogreplay.go
issue #18903 https://github.com/matrixorigin/MO-Cloud/issues/4300
- fix the sort column of mo-tables and mo-columns
=> fix replay catalog sort column

pkg/proxy/router.go
issue https://github.com/matrixorigin/MO-Cloud/issues/4231
close the connection with right method if there are some errors.
=> [bug] proxy: close the connection with right method.

pkg/logservice/service_commands.go, pkg/logservice/service_commands_test.go, pkg/util/metric/v2/logservice.go, pkg/util/metric/v2/metrics.go
issue #19617
This reverts commit ab0cdb8e24943f249b7cc3713cc50b02deba0f75,
which cause tpcc performance lower.
=> Revert "[enhancement] add metric for logservice health; fix a UT (#19540)"

pkg/sql/compile/compile.go
issue #19608 
恢复了一行和retry相关的代码
=> restore a code about retryable error

pkg/util/fault/fault.go, pkg/vm/engine/tae/catalog/types.go, pkg/vm/engine/tae/containers/batch.go, pkg/vm/engine/tae/rpc/handle.go, pkg/vm/engine/tae/txn/txnimpl/table.go
Reverts matrixorigin/matrixone#19543
=> Revert "refactor txnTable.DeleteByPhyAddrKeys"

pkg/sql/plan/deepcopy.go
issue https://github.com/matrixorigin/MO-Cloud/issues/3275
Resolve the issue of missing deepCopy
=> Resolve the issue of missing deepCopy

pkg/sql/plan/build_alter_change_column.go, pkg/sql/plan/build_alter_modify_column.go, test/distributed/cases/ddl/alter_table_change_column.result, test/distributed/cases/ddl/alter_table_change_column.sql, test/distributed/cases/ddl/alter_table_modify_column.result
issue https://github.com/matrixorigin/MO-Cloud/issues/4320
Resolve the issue of column null property setting errors when changing tables
=> Fix alter table column null property 1.2 dev

pkg/container/vector/functionTools.go, pkg/sql/colexec/evalExpression.go, pkg/sql/plan/function/baseTemplate.go, pkg/vm/process/process_spoolr.go
issue #11683 #19146 
try to reuse the FunctionParameterWrapper.
fix a spool bug will write a panic log incorrelty.
=> [cherry-pick-#19660] optimize the pointer allocation for built-in function.

pkg/vm/engine/disttae/logtail_consumer.go, pkg/vm/engine/disttae/logtailreplay/partition.go
- [x ] BUG
issue #19649 #19664 #19408 
1.  Cherry-pick 2.0-dev
=> [#19649, #19664, #19408]Fix bugs

pkg/sql/colexec/hashbuild/types.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4274
fix vector free panic
=> fix vector free panic(1.2.3-tmp-shulian)

pkg/sql/plan/build_alter_change_column.go, pkg/sql/plan/build_alter_modify_column.go, test/distributed/cases/ddl/alter_table_change_column.result, test/distributed/cases/ddl/alter_table_change_column.sql, test/distributed/cases/ddl/alter_table_modify_column.result
issue https://github.com/matrixorigin/MO-Cloud/issues/4320
Resolve the issue of column null property setting errors when changing tables
=> Fix alter table column null property-shulian

pkg/defines/type.go, pkg/sql/compile/compile.go, pkg/sql/compile/ddl.go, pkg/sql/compile/sql_executor.go, pkg/sql/compile/util.go, pkg/sql/plan/build_ddl.go, pkg/sql/plan/build_dml_util.go, pkg/util/executor/options.go, pkg/util/executor/types.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4091
fix drop database without lock table
=> fix drop database without lock table

pkg/sql/plan/runtime_filter.go, pkg/sql/plan/shuffle.go
issue #19669 
fix a bug in shuffle which cause panic
=> cp to 2.0 'fix a bug in shuffle which cause panic'

pkg/objectio/injects.go, pkg/vm/engine/disttae/local_disttae_datasource.go, pkg/vm/engine/disttae/local_disttae_datasource_test.go, pkg/vm/engine/tae/logtail/snapshot.go
issue #19357
- lower log print threshold
- check rowid of insert batch
=> adjust debug log

pkg/container/types/decimal.go, pkg/container/types/decimal_test.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4269
fix decimal panic
=> fix decimal panic(1.2.3-shulian)

pkg/sql/compile/sql_executor.go, pkg/vm/engine/disttae/local_disttae_datasource.go, pkg/vm/engine/disttae/local_disttae_datasource_test.go
issue #19357 
- remove debug log
- fix batch split flow in filterInMemUnCommittedInserts
=> Fix missing workspace data in restore process

.github/workflows/entrypoint.yaml, .github/workflows/image-build.yml, .github/workflows/merge-trigger-standalone.yaml, .github/workflows/merge-trigger-tke.yaml, .github/workflows/release.yml, .github/workflows/robot.yml
issue #
use CI-release/2.0-dev for mo 2.0-dev
___
Tests
___
- Updated all GitHub Actions workflow references from the `main` branch to the `release/2.0-dev` branch.
- Affected workflows include CI checks, image builds, merge triggers, releases, and robot automation.
- Ensures consistency with the `release/2.0-dev` branch for CI/CD processes.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>entrypoint.yaml</strong><dd><code>Update CI workflow references to release/2.0-dev branch</code>&nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/entrypoint.yaml
<li>Updated CI workflow references from <code>main</code> to <code>release/2.0-dev</code>.<br> <li> …
=> uses CI release/2.0-dev for 2.0-dev

pkg/sql/compile/sql_executor.go, pkg/vm/engine/disttae/local_disttae_datasource.go, pkg/vm/engine/disttae/local_disttae_datasource_test.go
issue #19357 
- remove debug log
- fix batch split flow in filterInMemUnCommittedInserts
=> Fix missing workspace data in restore process - main

pkg/vm/engine/tae/db/test/db_test.go
issue https://github.com/matrixorigin/matrixone/issues/19667
Fix TestGlobalCheckpoint5 timeout
=> Fix TestGlobalCheckpoint5 timeout

pkg/common/malloc/fixed_size_mmap_allocator.go, pkg/common/malloc/fixed_size_mmap_allocator_test.go, pkg/common/malloc/managed_allocator_test.go, pkg/common/mpool/mpool.go
issue #19758 
ignore munmap error in mpool deallocation.
=> malloc: add IgnoreMunmapError

pkg/vm/engine/disttae/cache/catalog.go, pkg/vm/engine/disttae/txn_table.go, pkg/vm/engine/disttae/txn_table_sharding.go, pkg/vm/engine/disttae/txn_table_test.go
issue #19247
return retry error if snapshot ts is smaller than ts of catalog.
before retry, update snapshot ts to catalog start ts.
=> [bug] return retry error if snapshot ts is smaller than ts of catalog

pkg/cdc/reader.go, pkg/cdc/reader_test.go, pkg/cdc/sinker.go, pkg/cdc/sinker_test.go, pkg/cdc/types.go, pkg/frontend/cdc.go
issue #19771 
Improve cdc send sql performance
=> Improve cdc send sql performance

pkg/util/metric/mometric/cron_task.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4362
fetch the target column from corrent resultset
=> fix: fetch result from correct resultset 2.0-dev

pkg/txn/client/operator.go, pkg/txn/client/operator_test.go
issue #19789 
fix txn status invalid if commit failed or commit a readonly txn
=> fix txn status invalid to 2.0

pkg/vm/engine/disttae/logtail_consumer.go
issue https://github.com/matrixorigin/MO-Cloud/issues/4369 https://github.com/matrixorigin/MO-Cloud/issues/4372
if the dn restarts too frequently, the unbuffered channel maybe
stuck as the reconnect in in progress, so change the channel
to buffered one.
=> [bug] logtail client: change the channel to buffered one

pkg/backup/backup_test.go, pkg/vm/engine/tae/db/test/db_test.go
issue https://github.com/matrixorigin/matrixone/issues/19813
Fix TestAppendAndGC2
=> Fix TestAppendAndGC2

pkg/proxy/tunnel_test.go
issue #19858 
fix UT, which should add locks
=> [bug] proxy: fix UT

pkg/sql/colexec/mergecte/mergecte.go, pkg/sql/colexec/mergecte/types.go, pkg/sql/plan/function/function_id.go, pkg/sql/plan/function/list_builtIn.go, pkg/sql/plan/query_builder.go, pkg/sql/plan/tools.go, test/distributed/cases/recursive_cte/recursive_cte.result, test/distributed/cases/recursive_cte/recursive_cte.sql
issue #https://github.com/matrixorigin/MO-Cloud/issues/4357
fix nested recursive cte
=> fix nested recursive cte

test/distributed/cases/log/show_table.sql, test/distributed/cases/mo_cloud/mo_cloud.sql
issue #19912
ignore bvt case for https://github.com/matrixorigin/matrixone/pull/19916
=> ignore bvt case 2.0-dev

pkg/sql/colexec/multi_update/s3writer.go, pkg/sql/compile/compile.go
issue #19890 
fix bug: sysbench delete pk will flush s3
=> fix bug: sysbench delete pk will flush s3

test/distributed/cases/optimizer/runtimefilter.test
issue #19733 https://github.com/matrixorigin/MO-Cloud/issues/4380
the runtime/block filter inconsistency is tracked by specific issue
=> tag EXPLAIN bvt case

pkg/sql/plan/bind_insert.go
issue https://github.com/matrixorigin/MO-Cloud/issues/2229
DEDUP_JOIN is a blocking operator. It collects all rows from building side. We postpone the composition of secondary index columns, which are not involved in de-duplication or locking, to mitigate memory issue.
=> [plan] postpone composition of secondary index columns

pkg/vm/engine/tae/db/merge/utils.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4343
set estimateMemUsagePerRow to 30
=> set estimateMemUsagePerRow to 30

pkg/backup/backup_test.go, pkg/vm/engine/tae/db/gc/v3/checkpoint.go, pkg/vm/engine/tae/logtail/storage_usage.go
issue https://github.com/matrixorigin/matrixone/issues/19808
Fix TestBackupData2 for 2.0
=> Fix TestBackupData2 for 2.0

pkg/sql/plan/build_show.go, test/distributed/cases/array/array_index.result, test/distributed/cases/array/array_index.sql
issue #https://github.com/matrixorigin/MO-Cloud/issues/4398
fix show index panic
=> fix show index panic(#2.0-dev)

pkg/backup/backup_test.go, pkg/vm/engine/tae/db/gc/v3/checkpoint.go, pkg/vm/engine/tae/logtail/storage_usage.go
issue https://github.com/matrixorigin/matrixone/issues/19808
Fix TestBackupData2
=> Fix TestBackupData2

pkg/sql/plan/apply_indices.go, test/distributed/cases/optimizer/explain_index.result
issue #https://github.com/matrixorigin/MO-Cloud/issues/4358
optimize index only scan in some cases
=> optimize index only scan in some cases

pkg/sql/plan/build_load.go, test/distributed/cases/load_data/load_data.result, test/distributed/cases/load_data/load_data.sql
issue # https://github.com/matrixorigin/matrixone/issues/19981
cherry-pick
load data local解析compress和format等之前在compile阶段做的，之前一次compileextern重构把这里改出的问题，修改该bug并增加bvt用例覆盖
=> fix: load data local format bug

pkg/frontend/authenticate_test.go, pkg/frontend/back_exec.go, pkg/frontend/session.go, pkg/frontend/session_test.go, pkg/frontend/txn_test.go, pkg/frontend/types.go, pkg/frontend/util.go, pkg/frontend/util_test.go
issue #https://github.com/matrixorigin/matrixone/issues/18601
后台会话复用txnop
=> reuse txnop

pkg/vm/engine/disttae/transfer.go, pkg/vm/engine/disttae/transfer_util.go, pkg/vm/engine/disttae/txn_table.go
issue #https://github.com/matrixorigin/matrixone/issues/19979
see the issue for more details.
=> fix a lot of tombstone objects missing when CN transfer.

pkg/frontend/password_management.go, pkg/frontend/password_management_test.go, test/distributed/cases/zz_accesscontrol/password_management/password_reuse.result, test/distributed/cases/zz_accesscontrol/password_management/password_reuse.sql
issue #https://github.com/matrixorigin/MO-Cloud/issues/4248
fix password reuse interval
=> fix password reuse interval（2.0-dev)

pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go, pkg/util/metric/v2/txn.go, pkg/vm/engine/disttae/txn_table.go
issue https://github.com/matrixorigin/matrixone/issues/19876
add counter metric to PKPersistedBetween
=> add PKPersistedBetween metric

test/distributed/cases/dml/insert/insert_ignore.sql
issue #15365 
remove issue tag 15365
=> remove issue tag 15365

pkg/proxy/client_conn.go, pkg/proxy/conn_cache.go, pkg/proxy/conn_cache_test.go, pkg/proxy/handler.go, pkg/proxy/server_conn.go, pkg/proxy/server_conn_test.go, pkg/proxy/tunnel.go
issue #20022
fix the bug which cause MO hang: do not close the connection if it is cached.
=> [bug] proxy: fix bug that may cause mo hang

pkg/sql/colexec/multi_update/s3writer.go, test/distributed/cases/dml/insert/not_null_check.result, test/distributed/cases/dml/insert/not_null_check.sql
issue #20081
fix bug: sort index incorrect in udpate s3
=> fix bug: sort index incorrect in udpate s3

pkg/frontend/authenticate_test.go, pkg/frontend/back_exec.go, pkg/frontend/cdc_test.go, pkg/frontend/computation_wrapper.go, pkg/frontend/internal_executor.go, pkg/frontend/logservice_test.go, pkg/frontend/mysql_cmd_executor.go, pkg/frontend/mysql_cmd_executor_test.go, pkg/frontend/pitr.go, pkg/frontend/pitr_test.go, pkg/frontend/routine_test.go, pkg/frontend/self_handle.go, pkg/frontend/session.go, pkg/frontend/snapshot.go, pkg/frontend/test/types_mock.go, pkg/frontend/types.go, pkg/perfcounter/context.go, pkg/perfcounter/update.go, pkg/sql/compile/compile2.go, pkg/sql/compile/sql_executor.go, test/distributed/cases/snapshot/snapshot_restore_account_level.result, test/distributed/cases/snapshot/snapshot_restore_account_level.sql
issue https://github.com/matrixorigin/MO-Cloud/issues/3917
The restore snapshot and restore pitr statements support CU resource statistics
=> restore statement CU resource statistics-2.0-dev

pkg/vm/engine/tae/logstore/driver/logservicedriver/clientpool.go
issue #20093 
GC log record larger than 1M
=> GC large record

go.mod, go.sum, pkg/cdc/reader.go, pkg/cdc/sinker.go, pkg/cdc/sinker_test.go, pkg/cdc/types.go, pkg/cdc/util.go
issue #19625
use customized driver
=> [Cherry-pick] use customized driver

pkg/sql/plan/build_constraint_util.go, pkg/sql/plan/build_insert.go, pkg/sql/plan/utils.go, test/distributed/cases/ddl/hash_key_partition.result, test/distributed/cases/ddl/hash_key_partition.sql, test/distributed/cases/dml/insert/insert_duplicate.result, test/distributed/cases/dml/insert/insert_duplicate.sql, test/distributed/cases/dml/insert/on_duplicate_key.result, test/distributed/cases/dml/insert/on_duplicate_key.sql, test/distributed/cases/pessimistic_transaction/atomicity.result, test/distributed/cases/pessimistic_transaction/atomicity.sql
issue https://github.com/matrixorigin/MO-Cloud/issues/4423
return error when on duplicate key update pk/uk
=> return error when on duplicate key update pk/uk

pkg/frontend/pitr.go, pkg/frontend/pitr_test.go, pkg/frontend/snapshot.go, test/distributed/cases/snapshot/restote_sub.result, test/distributed/cases/snapshot/restote_sub.sql
issue #https://github.com/matrixorigin/MO-Cloud/issues/4417
fix restore sub database
=> fix restore sub database

pkg/sql/plan/runtime_filter.go
issue #20092 
fix a bug in runtime filter for fulltext index
=> fix a bug in runtime filter for fulltext index

pkg/sql/plan/function/list_builtIn.go, pkg/sql/plan/stats.go, pkg/sql/plan/utils.go, test/distributed/cases/optimizer/explain_index.result
… (#20111)
serial functions should not be pushed down on zonemap
Approved by: @m-schen, @aunjgr, @aressu1985
issue #20109 
serial functions should not be pushed down on zonemap
=> [Tech Request]: serial functions should not be pushed down on zonemap

pkg/sql/plan/build_constraint_util.go, pkg/sql/plan/build_insert.go, pkg/sql/plan/utils.go, test/distributed/cases/ddl/hash_key_partition.result, test/distributed/cases/ddl/hash_key_partition.sql, test/distributed/cases/dml/insert/insert_duplicate.result, test/distributed/cases/dml/insert/insert_duplicate.sql, test/distributed/cases/dml/insert/on_duplicate_key.result, test/distributed/cases/dml/insert/on_duplicate_key.sql, test/distributed/cases/pessimistic_transaction/atomicity.result, test/distributed/cases/pessimistic_transaction/atomicity.sql
return error when on duplicate key update pk/uk
Approved by: @aunjgr, @heni02
issue https://github.com/matrixorigin/MO-Cloud/issues/4423
return error when on duplicate key update pk/uk
=> return error when on duplicate key update pk/uk (#20108)

pkg/frontend/pitr.go, pkg/frontend/pitr_test.go, pkg/frontend/snapshot.go, test/distributed/cases/snapshot/snapshot_restote_cluster_table.result, test/distributed/cases/snapshot/snapshot_restote_cluster_table.sql
issue #https://github.com/matrixorigin/MO-Cloud/issues/4417
optimize restore system table
=> optimize restore system table(#2.0-dev)

go.mod, go.sum, pkg/common/malloc/checked_allocator.go, pkg/proxy/tunnel.go
issue #https://github.com/matrixorigin/matrixone/issues/20089
定位proxy panic问题。
1, 在 proxy的日志里面带上运行的goroutineid。tunnel和pipe 的goroutine是不同的。
2, 在malloc中记录分配内存的goroutineid.
=> add goroutine id in log

pkg/frontend/pitr.go, pkg/frontend/snapshot.go, pkg/frontend/types.go, test/distributed/cases/snapshot/snapshot_restore_keyword.result, test/distributed/cases/snapshot/snapshot_restore_keyword.sql
issue #20144 
fix restore table or database with keyword
=> fix restore table or database with keyword(#2.0-dev)

pkg/sql/colexec/multi_update/s3writer.go, test/distributed/cases/dml/insert/not_null_check.result, test/distributed/cases/dml/insert/not_null_check.sql
issue https://github.com/matrixorigin/MO-Cloud/issues/4442
fix bug: not skip null rows for clusterBy
=> fix bug: not skip null rows for clusterBy

pkg/frontend/routine.go, pkg/frontend/util.go
issue #https://github.com/matrixorigin/matrixone/issues/20089
issue #https://github.com/matrixorigin/matrixone/issues/20090
1, 更改高效的取goid函数。
2，lastMeta记录回滚后的事务信息。避免混淆
=> change goid function

pkg/sql/plan/opt_misc.go, pkg/sql/plan/stats.go
issue #20168 
make prefix_in and prefix_eq always the first filter
=> make prefix_in and prefix_eq always the first filter

pkg/sql/colexec/multi_update/s3writer.go
issue https://github.com/matrixorigin/MO-Cloud/issues/4443
fix bug: incorrect threshold
=> fix bug: incorrect threshold

go.mod, pkg/bootstrap/versions/upgrade_strategy.go, pkg/bootstrap/versions/utils.go, pkg/bootstrap/versions/utils_test.go, pkg/bootstrap/versions/v2_0_0/pubsub.go, pkg/bootstrap/versions/v2_0_0/pubsub_test.go, pkg/bootstrap/versions/v2_0_1/pubsub.go, pkg/bootstrap/versions/v2_0_1/pubsub_test.go, pkg/common/pubsub/utils.go, pkg/common/pubsub/utils_test.go
issue #20161
check mo_pubs's existence before migrate
=> check mo_pubs's existence before migrate

go.mod, pkg/cnservice/server.go, pkg/frontend/test/engine_mock.go, pkg/shardservice/types.go, pkg/sql/colexec/preinsert/preinsert.go, pkg/vm/engine/disttae/logtailreplay/blocks_iter.go, pkg/vm/engine/disttae/logtailreplay/partition_state.go, pkg/vm/engine/disttae/logtailreplay/partition_state_test.go, pkg/vm/engine/disttae/logtailreplay/types.go, pkg/vm/engine/disttae/txn_table.go, pkg/vm/engine/disttae/txn_table_sharding.go, pkg/vm/engine/disttae/txn_table_sharding_handle.go, pkg/vm/engine/memoryengine/table.go, pkg/vm/engine/test/reader_test.go, pkg/vm/engine/types.go
issue #19876
- Check tombstone files when answering PKPersistedBetween
=> fix concurrent deletes dup - main

pkg/sql/compile/compile.go, pkg/sql/compile/compile_test.go, pkg/sql/compile/scope.go, pkg/sql/plan/shuffle.go
issue #20202
fix workload unbalance for multicn
=> [Tech Request]: fix workload unbalance for multicn

pkg/sql/compile/ddl.go, test/distributed/cases/pessimistic_transaction/drop_table_truncate.sql
issue #14633 
modify truncate as type of ddl
=> modify truncate as type of ddl

pkg/sql/plan/function/type_check.go, test/distributed/cases/array/array.result, test/distributed/cases/array/array.sql
issue #20181 
fix prepare vector parameter
=> fix prepare vector parameter(2.0dev)

pkg/cnservice/server.go, pkg/frontend/test/engine_mock.go, pkg/shardservice/types.go, pkg/sql/colexec/preinsert/preinsert.go, pkg/vm/engine/disttae/logtailreplay/blocks_iter.go, pkg/vm/engine/disttae/logtailreplay/partition_state.go, pkg/vm/engine/disttae/logtailreplay/partition_state_test.go, pkg/vm/engine/disttae/logtailreplay/types.go, pkg/vm/engine/disttae/txn_table.go, pkg/vm/engine/disttae/txn_table_sharding.go, pkg/vm/engine/disttae/txn_table_sharding_handle.go, pkg/vm/engine/memoryengine/table.go, pkg/vm/engine/test/reader_test.go, pkg/vm/engine/types.go
issue #19876
- Check tombstone files when answering PKPersistedBetween
=> fix concurrent deletes dup

test/distributed/cases/function/func_crc32.result, test/distributed/cases/function/func_crc32.sql
add case for function crc32()(2.0-dev)
issue #https://github.com/matrixorigin/matrixone/issues/20121
add case for function crc32()(2.0-dev)
=> add case for function crc32()(2.0-dev)

pkg/common/system/system.go
issue #20217 
fix bug: incorrect cpu num in container
=> fix bug: incorrect cpu num in container

pkg/sql/colexec/external/external.go
issue #11081
Add input statistics for external operators
=> Add input statistics for external operators

pkg/sql/plan/build_alter_modify_column.go, test/distributed/cases/ddl/alter_table_change_column.result, test/distributed/cases/ddl/alter_table_modify_column.result, test/distributed/cases/ddl/alter_table_modify_column.sql
issue #https://github.com/matrixorigin/matrixone/issues/19872
Improve compatibility error report of alter table cold type
=> Alter table improve type compatibility error-2.0 dev

pkg/vm/engine/disttae/logtail_consumer.go, pkg/vm/engine/disttae/logtail_consumer_test.go
issue #20200
check the tn store number before use it.
=> [bug] logtail consumer: check the tn store number

.github/workflows/entrypoint.yaml
add secrets about tencent for matrixone-utils-ci
issue #
add secrets about tencent for matrixone-utils-ci
___
enhancement, configuration changes
___
- Added new secrets `TENCENT_AK` and `TENCENT_SK` to the GitHub Actions workflow configuration.
- These changes enable integration with Tencent services for the CI process.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>entrypoint.yaml</strong><dd><code>Add Tencent secrets to GitHub Actions workflow</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/entrypoint.yaml
<li>Added new secrets <code>TENCENT_AK</code> and …
=> add secrets about tencent for matrixone-utils-ci

pkg/cnservice/server.go, pkg/cnservice/types.go, pkg/sql/compile/compile2.go, pkg/sql/compile/compileService.go, pkg/sql/compile/remoterunServer.go, pkg/tests/issues/issue_test.go, pkg/txn/client/client.go, pkg/txn/client/client_test.go, pkg/txn/client/operator.go, pkg/util/executor/options.go, pkg/vm/engine/disttae/logtail_consumer.go
Reverts matrixorigin/matrixone#20254
=> Revert "speed up abort all active txn to 2.0"

pkg/cnservice/server.go, pkg/cnservice/types.go, pkg/sql/compile/compile2.go, pkg/sql/compile/compileService.go, pkg/sql/compile/remoterunServer.go, pkg/tests/issues/issue_test.go, pkg/txn/client/client.go, pkg/txn/client/client_test.go, pkg/txn/client/operator.go, pkg/util/executor/options.go, pkg/vm/engine/disttae/logtail_consumer.go
This reverts commit 94f6175e081b8759b4411044cc569859f054515a.
issue [#4436](https://github.com/matrixorigin/MO-Cloud/issues/4436)
Revert "speed up abort all active txn (#20253)"
=> Revert "speed up abort all active txn (#20253)"

pkg/sql/plan/utils.go
issue #20329 
[Bug]: invalid argument function prefix_in, bad value [INT INT]
=> [Bug]: invalid argument function prefix_in, bad value [INT INT]

pkg/sql/plan/function/ctl/cmd_addfaultpoint.go, pkg/sql/plan/function/ctl/cmd_addfaultpoint_test.go, pkg/util/fault/fault.go
issue #20280
support show fault injection status
=> support fault injection status

pkg/lockservice/lock_table_local.go
issue #19920
to figure out why TestLockNeedUpgrade failed
=> [cherry-pick-20065] : add logger for lock merged

pkg/vm/engine/tae/rpc/handle.go
issue https://github.com/matrixorigin/matrixone/issues/20326
Add w-w debug log
=> Add w-w debug log

pkg/vm/engine/tae/common/print.go, pkg/vm/engine/tae/db/test/db_test.go
issue #20355 
fix vector print panic
=> fix vector print panic

pkg/vm/engine/tae/common/print.go, pkg/vm/engine/tae/db/test/db_test.go
issue #20355 
fix vector print
=> fix vector print

pkg/vm/engine/tae/db/test/db_test.go, pkg/vm/engine/tae/tables/base.go, pkg/vm/engine/tae/tables/functions.go
issue #20326
Fix dedup. Fix get origin commit ts, use data row offset instead of tombstone physical row offset
=> fix dedup, fix ww

pkg/fileservice/disk_cache.go, pkg/fileservice/fifocache/bench_test.go, pkg/fileservice/fifocache/data_cache.go, pkg/fileservice/fifocache/fifo.go, pkg/fileservice/fifocache/fifo_test.go, pkg/objectio/cache.go
issue #20364 
This reverts commit dd576d34779ca3fee6fc0c47a9b5e808dd22b600.
=> Revert "fifocache: make queue1 size configurable (#20298)"

pkg/frontend/back_exec.go, pkg/frontend/util.go, pkg/util/trace/impl/motrace/report_statement.go
issue # https://github.com/matrixorigin/MO-Cloud/issues/4500
fix `execute` query mark as `internal_sql`
=> fix sql_source_type error setting as internal_sql in 2.0

pkg/frontend/test/engine_mock.go, pkg/testutil/testengine/testengine_test.go, pkg/vm/engine/disttae/txn_database.go, pkg/vm/engine/disttae/txn_table_sharding_handle.go, pkg/vm/engine/memoryengine/database.go, pkg/vm/engine/test/disttae_engine_test.go, pkg/vm/engine/types.go
issue #19206
issue https://github.com/matrixorigin/matrixone/issues/20194
- Add RelationExists to prevent too many logs like table not found
=> Add RelationExists interface to txnDatabase

pkg/sql/plan/function/func_builtin.go, pkg/sql/plan/function/func_builtin_serial.go
issue https://github.com/matrixorigin/MO-Cloud/issues/4471
improve mem reuse for serial&serial_full
=> improve mem reuse for serial&serial_full

pkg/sql/plan/apply_indices.go
issue #20388 
fix a bug which cause panic when there is fulltext index
=> fix a bug which cause panic when there is fulltext index

pkg/sql/plan/stats.go
issue #20299 
adjust the stats for L2 join to get more dop
=> adjust the stats for L2 join to get more dop

pkg/sql/colexec/lockop/lock_op.go, pkg/sql/plan/opt_misc.go, pkg/sql/plan/query_builder.go, pkg/sql/plan/utils.go, test/distributed/cases/pessimistic_transaction/select_for_update.sql
issue #20410 
do not lock table if lock no rows
=> do not lock table if lock no rows

pkg/sql/compile/compile2.go
- [x ] BUG
issue #20384 #20325 
1.Fix bug
=> [#20384, 20325]cherry-pick-Fix-snapshot-read-bug 

pkg/sql/plan/order_binder.go, test/distributed/cases/dml/select/order_by_clause.result, test/distributed/cases/dml/select/order_by_clause.sql
issue https://github.com/matrixorigin/MO-Cloud/issues/4508
Resolve the issue of referencing duplicate columns in SELECTList using the OrderBy clause
=> Resolve duplicate column references in OrderBy clause-2.0 dev

test/distributed/cases/security/password.result, test/distributed/cases/security/password.sql
issue #
https://github.com/matrixorigin/MO-Cloud/issues/4247
https://github.com/matrixorigin/MO-Cloud/issues/4248
test
___
Tests
___
- Updated test cases for password validation and connection control settings.
- Corrected expected outcomes for password creation failures.
- Adjusted session management and removed redundant checks in test scripts.
- Added comments to clarify specific test cases and issues.
___
<tr>
<td>
<details>
<summary><strong>password.result</strong><dd><code>Update password and connection control test results</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
test/distributed/cases/security/password.result
<li>Corrected …
=> Security bvt case

pkg/lockservice/lock_table_local.go, pkg/lockservice/service_test.go
=> fix waiter leak

pkg/txn/client/client.go, pkg/txn/client/client_test.go
issue #20468 
fix txn wait active queue leak
=> fix txn wait active queue leak to 2.0

pkg/txn/client/client.go, pkg/txn/client/client_test.go
issue #20468 
fix wait active queue leak
=> fix wait active queue leak

pkg/frontend/cdc.go, pkg/frontend/cdc_test.go, pkg/taskservice/daemon_task.go
issue #19626 #19575
quit cdc Start func when pause
=> [Cherry-pick] quit cdc Start func when pause

pkg/catalog/tuplesParse.go, pkg/catalog/tuplesParse_test.go, pkg/vm/engine/tae/common/linklist_test.go, pkg/vm/engine/tae/common/print.go, pkg/vm/engine/tae/rpc/handle.go, pkg/vm/engine/tae/rpc/handle_test.go
issue https://github.com/matrixorigin/MO-Cloud/issues/4525
- TN won't panic when parsing EntryList
=> remove panic in parsing txn entries

etc/launch/log.toml, pkg/config/configuration.go, pkg/config/configuration_test.go, pkg/util/trace/impl/motrace/buffer_pipe_test.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4524
fix the configuration `SetDefaultValues` logic, allow the price = 0
=> chore: cu price allows 0

pkg/frontend/authenticate_test.go, pkg/frontend/back_exec.go, pkg/frontend/pitr.go, pkg/frontend/pitr_test.go, pkg/frontend/snapshot.go, pkg/frontend/test/types_mock.go, pkg/frontend/types.go, test/distributed/cases/snapshot/snapshot_restore_lower_case_table_names.result, test/distributed/cases/snapshot/snapshot_restore_lower_case_table_names.sql
issue #20484 
add backSes Exec lower_case_table_names
=> add backSes Exec lower_case_table_names(#2.0-dev)

pkg/catalog/tuplesParse.go, pkg/catalog/tuplesParse_test.go, pkg/vm/engine/tae/common/linklist_test.go, pkg/vm/engine/tae/common/print.go, pkg/vm/engine/tae/rpc/handle.go, pkg/vm/engine/tae/rpc/handle_test.go
issue https://github.com/matrixorigin/MO-Cloud/issues/4525
- TN won't panic when parsing EntryList
=> remove panic in parsing txn entries - main

test/distributed/cases/optimizer/shuffle.result, test/distributed/cases/optimizer/shuffle.test
issue #20450 
reduce memory consumption in bvt shuffle test
=> reduce memory consumption in bvt shuffle test

pkg/sql/plan/bind_update.go, test/distributed/cases/dml/insert/not_null_check.result, test/distributed/cases/dml/insert/not_null_check.sql
issue #20504 
fix bug: update secondary key panic
=> fix bug: update secondary key panic

pkg/vm/engine/tae/tables/jobs/flushTableTail.go, pkg/vm/engine/tae/tables/jobs/flushobj.go
issue #20512
Do not return error if waited.
=> fix wait done reporting error on 2.0-dev

pkg/sql/plan/query_builder.go, test/distributed/cases/system_variable/lower_case_table_names.result, test/distributed/cases/system_variable/lower_case_table_names.sql
issue #20522
fix lower_case_table_names in view definition
=> fix lower_case_table_names in view definition

pkg/common/morpc/backend.go, pkg/common/morpc/backend_test.go
issue [#4331](https://github.com/matrixorigin/MO-Cloud/issues/4331)
fix busy loop in morpc if send queue is full to 2.0
=> fix busy loop in morpc if send queue is full to 2.0

pkg/cdc/reader.go, pkg/cdc/sinker.go, pkg/cdc/types.go, pkg/sql/plan/query_builder.go, test/distributed/cases/system_variable/lower_case_table_names.result, test/distributed/cases/system_variable/lower_case_table_names.sql
issue #20522 #20507
- fix double close atomic batch
- fix lower_case_table_names in view definition
=> [Cherry-pick] fix lower in view && fix double close atomic batch

pkg/common/moerr/error.go, pkg/common/moerr/error_no_ctx.go, pkg/vm/engine/tae/db/controller.go, pkg/vm/engine/tae/db/db.go, pkg/vm/engine/tae/db/open.go, pkg/vm/engine/tae/db/test/db_test.go, pkg/vm/engine/tae/txn/txnbase/txnmgr.go, pkg/vm/engine/tae/txn/txnbase/types.go
issue #20537 #20535 
refactor for the future tn migration
=> refactor for the future tn migration 2

pkg/vm/engine/tae/rpc/handle.go
issue https://github.com/matrixorigin/MO-Cloud/issues/4567
- TN gest txn database handle by ID to prevent inconsistent data
=> fix checking database id in creating table

pkg/sql/plan/apply_indices.go, pkg/sql/plan/stats.go
issue #20572 
make index scan always tp
=> to 2.0 "make index scan always tp"

pkg/frontend/back_exec.go, pkg/frontend/mysql_cmd_executor.go, pkg/frontend/session.go, pkg/sql/plan/function/func_mo.go, test/distributed/cases/publication_subscription/pub_sub.result, test/distributed/cases/publication_subscription/pub_sub4.result, test/distributed/cases/publication_subscription/pub_sub4.sql, test/distributed/cases/publication_subscription/pub_sub_improvement.result, test/distributed/cases/tenant/pub_sub2.result, test/distributed/cases/tenant/pub_sub3.result
issue #18718 #https://github.com/matrixorigin/MO-Cloud/issues/2920
use mo_table_rows/size in `show table status`
=> [Cherry-pick] use mo_table_rows/size in `show table status`

pkg/frontend/mysql_cmd_executor.go, test/distributed/cases/publication_subscription/pub_sub4.result, test/distributed/cases/publication_subscription/pub_sub4.sql
issue #20596 
fix show table status of an empty db
=> fix show table status of an empty db

pkg/sql/compile/scope.go, pkg/vm/engine/disttae/engine.go, pkg/vm/engine/entire_engine.go, pkg/vm/engine/entire_engine_test.go, pkg/vm/engine/memoryengine/binded.go, pkg/vm/engine/memoryengine/engine.go, pkg/vm/engine/types.go
This reverts commit bbf546629d1e37713f55131be702f99d8b8c36fd.
issue #15598 
Revert "remove unnecessary logics after delay expand ranges (#20573)"
=> Revert "remove unnecessary logics after delay expand ranges (#20573)"

pkg/frontend/mysql_cmd_executor.go, pkg/frontend/mysql_cmd_executor_test.go, pkg/frontend/txn.go, pkg/util/fault/fault.go, pkg/util/fault/fault_test.go
issue #https://github.com/matrixorigin/matrixone/issues/20597
1, 修改用moerr 触发panic时，会吞掉error的问题
2, 修改fault panic选项
=> fix eating err

pkg/frontend/mysql_cmd_executor.go, pkg/frontend/mysql_cmd_executor_test.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4567
在run panic时，捕获panic，转成error。回滚事务。
=> recover run panic

pkg/sql/plan/utils.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/2393
make in predicate null rejecting
=> make in predicate null rejecting

pkg/frontend/test/engine_mock.go, pkg/objectio/injects.go, pkg/vm/engine/disttae/change_handle.go, pkg/vm/engine/disttae/engine.go, pkg/vm/engine/disttae/stats.go, pkg/vm/engine/disttae/transfer.go, pkg/vm/engine/disttae/txn_table.go, pkg/vm/engine/engine_util/exec_util.go, pkg/vm/engine/entire_engine.go, pkg/vm/engine/entire_engine_test.go, pkg/vm/engine/memoryengine/binded.go, pkg/vm/engine/memoryengine/engine.go, pkg/vm/engine/test/reader_test.go, pkg/vm/engine/types.go
issue #20647 
prefetch table meta for slow ranges
=> prefetch table meta for slow ranges

pkg/frontend/mysql_cmd_executor.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4586
use force_update policy in `show table status`
=> use force_update policy in `show table status`

pkg/objectio/injects.go, pkg/vm/engine/disttae/engine.go, pkg/vm/engine/disttae/txn.go, pkg/vm/engine/disttae/txn_table.go, pkg/vm/engine/disttae/types.go, pkg/vm/engine/engine_util/reader.go, pkg/vm/engine/test/reader_test.go, pkg/vm/engine/test/testutil/disttae_engine.go, pkg/vm/engine/test/testutil/util.go, pkg/vm/engine/test/workspace_test.go
issue #20646
* 修改非commit时workspace dump的threshold
=> Optimize workspace dump

pkg/txn/client/client.go
issue [#4595](https://github.com/matrixorigin/MO-Cloud/issues/4595)
fix hung due to deadlock.
=> fix hung due to deadlock to 2.0

pkg/bootstrap/versions/v2_0_1/pubsub.go, pkg/bootstrap/versions/v2_0_1/pubsub_test.go
issue #20672
delete unsubscribed account in mo_subs
=> delete unsubscribed account in mo_subs

pkg/frontend/pitr.go, pkg/frontend/pitr_test.go, pkg/frontend/snapshot.go, test/distributed/cases/snapshot/snapshot_restore_lower_case_2.result, test/distributed/cases/snapshot/snapshot_restore_lower_case_2.sql
issue #20544 
fix restore view with lower case table names equals to 0
=> fix restore view with lower case table names equals to 0(#2.0-dev)

pkg/txn/client/client.go
issue [#4595](https://github.com/matrixorigin/MO-Cloud/issues/4595)
fix hung due to deadlock.
=> fix hung due to deadlock

pkg/bootstrap/versions/v2_0_1/pubsub.go, pkg/bootstrap/versions/v2_0_1/pubsub_test.go
issue #20672
delete unsubscribed account in mo_subs
=> [Cherry-pick] fix delete unsubscribed account in mo_subs

pkg/common/malloc/allocator_test.go, pkg/common/malloc/metrics_allocator.go
issue #20688
make malloc tests run faster
=> malloc: tune tests to run faster

pkg/sql/plan/function/fault/fault_test.go, pkg/util/fault/fault_test.go
issue #20665 #20657 #20690
fix Test_CanTransferCnFaultInject and TestCanTransferQuery and Test_panic
=> fix ut in fault injection

pkg/frontend/mysql_cmd_executor.go, test/distributed/cases/dml/show/show4.sql, test/distributed/cases/publication_subscription/pub_sub.sql, test/distributed/cases/publication_subscription/pub_sub4.sql, test/distributed/cases/publication_subscription/pub_sub_improvement.sql, test/distributed/cases/tenant/pub_sub2.sql, test/distributed/cases/tenant/pub_sub3.sql
issue #https://github.com/matrixorigin/MO-Cloud/issues/4586
- use force_update policy in `show table status`
- use `values` stmt instead of `union all` to improve performance
=> [Cherry-pick]fix show table status

pkg/util/fault/fault.go
issue #20690
add logs in fault enable and disable
=> add logs in fault enable and disable

pkg/sql/plan/explain/explain_expr.go, pkg/sql/plan/expr_opt.go, test/distributed/cases/optimizer/blockfilter.result, test/distributed/cases/optimizer/blockfilter.test
optimize filters on composite columns
Approved by: @heni02, @ouyuanning, @aunjgr
issue #20694 
cp to 2.0 "[Tech Request]: optimize filters on composite columns (#20695)"
=> cp to 2.0 "[Tech Request]: optimize filters on composite columns (#20695)"

pkg/sql/plan/function/func_compare.go, test/distributed/cases/expression/case_when.result, test/distributed/cases/expression/case_when.sql
issue #https://github.com/matrixorigin/MO-Cloud/issues/4607
fix a bug for case when expression
=> fix a bug for case when expression

pkg/sql/plan/runtime_filter.go
issue #20526 
cp to 2.0 "optimize stats for runtime filters when table not flushed"
=> cp to 2.0 "optimize stats for runtime filters when table not flushed"

pkg/common/moerr/error.go, pkg/common/moerr/error_no_ctx.go, pkg/common/morpc/server.go, pkg/tests/issues/issue_test.go, pkg/txn/client/client.go, pkg/txn/client/timestamp_waiter.go, pkg/txn/client/timestamp_waiter_test.go, pkg/txn/client/types.go, pkg/txn/rpc/sender.go, pkg/txn/rpc/sender_test.go, pkg/vm/engine/disttae/engine.go, pkg/vm/engine/disttae/logtail_consumer.go, pkg/vm/engine/disttae/logtail_consumer_test.go, pkg/vm/engine/disttae/txn_table.go
issue https://github.com/matrixorigin/MO-Cloud/issues/4436
1. do not abort txns when logtail reconnect.
2. add some retry operations when commit txn
=> [improvement] logtail: do not abort txns when reconnect. 

pkg/logservice/service_bootstrap.go, pkg/logservice/service_bootstrap_test.go
issue #20044
add some logs to investigate issues
=> [improvement] logservice: add some logs

pkg/sql/plan/expr_opt.go, pkg/sql/plan/opt_misc.go
issue #20742 
fix stats when merge filters on composite key
=> fix stats when merge filters on composite key

pkg/frontend/test/engine_mock.go, pkg/vm/engine/disttae/local_disttae_datasource.go, pkg/vm/engine/disttae/local_disttae_datasource_test.go, pkg/vm/engine/engine_util/datasource.go, pkg/vm/engine/engine_util/pk_filter_mem.go, pkg/vm/engine/engine_util/pk_filter_mem_test.go, pkg/vm/engine/engine_util/reader.go, pkg/vm/engine/engine_util/tombstone_data.go, pkg/vm/engine/engine_util/tombstone_data_test.go, pkg/vm/engine/tae/logtail/backup.go, pkg/vm/engine/types.go
issue #https://github.com/matrixorigin/matrixone/issues/20528
apply reader pk filter on workspace entry.
1. =, >, < , >=, <=, between, in
=> to 2.0: apply reader pk filter on workspace entry.

pkg/vm/engine/tae/db/db.go, pkg/vm/engine/tae/db/open.go, pkg/vm/engine/tae/db/test/db_test.go, pkg/vm/engine/tae/db/testutil/engine.go, pkg/vm/engine/tae/txn/txnbase/txnmgr.go
issue #20535 
Support open with replay mode
=> Refactor tn migration 4

pkg/taskservice/task_runner.go, pkg/taskservice/task_service_cron.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4639
fix concurrency limit
=> fix task concurrency control

pkg/util/address/address.go, pkg/util/address/address_test.go, pkg/vm/engine/disttae/db.go, pkg/vm/engine/disttae/engine.go, pkg/vm/engine/disttae/logtail.go, pkg/vm/engine/disttae/logtail_consumer.go, pkg/vm/engine/disttae/logtail_consumer_test.go, pkg/vm/engine/disttae/mo_table_stats.go, pkg/vm/engine/disttae/types.go, pkg/vm/engine/tae/logtail/service/server.go
issue #19840
some refactor and add UTs
=> [improvement] logtail: some refactor and add UTs

pkg/vm/engine/disttae/mo_table_stats.go
issue #https://github.com/matrixorigin/matrixone/issues/20762
fix tables under mo_catalog stats not update.
=> fix tables under mo_catalog stats not update.

pkg/frontend/compiler_context.go, pkg/frontend/session_test.go, pkg/sql/compile/sql_executor_context.go, pkg/sql/plan/apply_indices.go, pkg/sql/plan/apply_indices_master.go, pkg/sql/plan/apply_indices_vector.go, pkg/sql/plan/bind_delete.go, pkg/sql/plan/bind_insert.go, pkg/sql/plan/bind_update.go, pkg/sql/plan/build_delete.go, pkg/sql/plan/build_dml_util.go, pkg/sql/plan/build_util.go, pkg/sql/plan/mock.go, pkg/sql/plan/opt_misc.go, pkg/sql/plan/types.go, pkg/sql/plan/types_mock.go, pkg/sql/plan/utils.go, pkg/sql/plan/utils_test.go, pkg/vm/engine/memoryengine/compiler_context.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4596
Fix panic caused by resolve index table in subscription
=> Fix panic caused by resolve index table in subscription

pkg/container/batch/compact_batchs.go, pkg/sql/colexec/multi_update/s3writer.go, pkg/sql/colexec/multi_update/s3writer_util.go
remove some logic from multi_update
issue #20778 
remove some logic from multi_update (#20788)
=> remove some logic from multi_update (#20788)

pkg/frontend/mysql_protocol.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4648
原因：从profile上看，字符串转slice花费的时间多。
修改：unsafe的字符串转换slice函数。
=> refine string

pkg/backup/backup_test.go, pkg/vm/engine/tae/catalog/catalogreplay.go, pkg/vm/engine/tae/logtail/backup.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4652
1. update txn node in ReWriteCheckpointAndBlockFromKey
2. update txn node in replay
=> fix ReWriteCheckpointAndBlockFromKey

pkg/sql/colexec/loopjoin/join.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4656
fix a bug that cause panic on loop join
=> fix a bug that cause panic on loop join

pkg/vm/engine/tae/mergesort/task.go
issue #11891
fix MERGE-START log
=> fix merge start log

pkg/cdc/util.go, pkg/frontend/cdc.go, pkg/frontend/cdc_test.go, pkg/frontend/pitr.go, pkg/frontend/pitr_test.go
issue #18445
Revert check pitr in cdc
=> Revert check pitr in cdc

pkg/vm/engine/tae/catalog/basemvccnode.go, pkg/vm/engine/tae/catalog/catalogreplay.go, pkg/vm/engine/tae/catalog/metamvccnode.go, pkg/vm/engine/tae/db/checkpoint/replay.go, pkg/vm/engine/tae/db/open.go, pkg/vm/engine/tae/db/test/db_test.go, pkg/vm/engine/tae/logtail/utils.go, pkg/vm/engine/tae/txn/txnbase/mvccnode.go
issue #20740
Optimize replay, replay checkpoint with 10 workers
=> optimize replay

pkg/vm/engine/tae/db/merge/policyOverlap.go, pkg/vm/engine/tae/db/merge/utils.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4665
Fix Merge OOM
=> fix 2.0-dev merge oom

pkg/vm/engine/tae/db/checkpoint/entry.go, pkg/vm/engine/tae/db/checkpoint/flusher.go, pkg/vm/engine/tae/db/checkpoint/runner.go, pkg/vm/engine/tae/db/checkpoint/runner_test.go, pkg/vm/engine/tae/db/checkpoint/store.go, pkg/vm/engine/tae/db/checkpoint/testutils.go, pkg/vm/engine/tae/db/checkpoint/types.go, pkg/vm/engine/tae/db/db.go, pkg/vm/engine/tae/db/dbutils/error.go, pkg/vm/engine/tae/db/test/catalog_test.go, pkg/vm/engine/tae/db/test/db_test.go, pkg/vm/engine/tae/db/test/replay_test.go, pkg/vm/engine/tae/db/testutil/engine.go
issue #20535 
refactor ickp implementation phase 1
=> refactor ickp impl phase 1

pkg/logservice/truncation.go
issue #20853
add truncate log in logservice
=> [improvement] logservice: add truncate log

pkg/vm/engine/engine_util/tombstone_data_test.go, pkg/vm/engine/tae/tasks/job.go
issue https://github.com/matrixorigin/matrixone/issues/20815
Fix data race for ParallelJobScheduler 2.0
=> Fix data race for ParallelJobScheduler 2.0

pkg/hakeeper/task/task_scheduler.go, pkg/hakeeper/task/task_scheduler_test.go, pkg/logservice/store_hakeeper_check_test.go, pkg/taskservice/task_runner_test.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4639 #20859
If CN's heartbeat expired, fail all tasks running on it.
=> fail expired task

pkg/vm/engine/disttae/txn.go, pkg/vm/engine/test/disttae_engine_test.go
issue #20853
修复了workspace 超过10M的大事务不刷盘的问题
=> fix big txn dump

pkg/sql/plan/apply_indices.go, pkg/sql/plan/apply_indices_master.go, pkg/sql/plan/build_dml_util.go, test/distributed/cases/optimizer/index.result, test/distributed/cases/optimizer/index.test
fix opt bug: not ResolveAlias for sk
Approved by: @badboynt1, @heni02
issue https://github.com/matrixorigin/MO-Cloud/issues/4677
fix opt bug: not ResolveAlias for sk (#20903)
=> fix opt bug: not ResolveAlias for sk (#20903)

pkg/sql/parsers/dialect/mysql/mysql_sql_test.go, pkg/sql/parsers/tree/table_name.go, pkg/sql/plan/query_builder.go, pkg/sql/plan/utils.go, pkg/sql/plan/utils_test.go, test/distributed/cases/snapshot/create_table_as_select_as_of_timestamp.result, test/distributed/cases/snapshot/create_table_as_select_as_of_timestamp.sql
issue #20780 
support create table as of timestamp
=> support create table as of timestamp

pkg/vm/engine/tae/db/checkpoint/executor.go, pkg/vm/engine/tae/db/checkpoint/replay.go, pkg/vm/engine/tae/db/checkpoint/runner.go, pkg/vm/engine/tae/db/checkpoint/runner_test.go, pkg/vm/engine/tae/db/checkpoint/store.go, pkg/vm/engine/tae/db/checkpoint/testutils.go, pkg/vm/engine/tae/db/checkpoint/types.go, pkg/vm/engine/tae/db/test/db_test.go
issue #20535 
refactor gckp and fix some potential bug
=> refactor gckp and fix some potential bug

pkg/sql/plan/apply_indices.go, test/distributed/cases/optimizer/index.result, test/distributed/cases/optimizer/index.test, test/distributed/cases/optimizer/like.result
issue #https://github.com/matrixorigin/MO-Cloud/issues/4677
fix a bug in apply index
=> fix a bug in apply index

pkg/sql/compile/compile.go, test/distributed/cases/optimizer/index.result, test/distributed/cases/optimizer/index.test
issue https://github.com/matrixorigin/MO-Cloud/issues/4673
Fix bug: eng is nil in multiupdate
=> Fix bug: eng is nil in multiupdate

pkg/datasync/consumer_test.go
issue #20957
fix ut TestCompleteData
=> [bug] datasync: fix ut TestCompleteData

pkg/bootstrap/service_test.go, pkg/frontend/test/txn_mock.go, pkg/frontend/txn_test.go, pkg/incrservice/store_sql_test.go, pkg/sql/colexec/lockop/lock_op.go, pkg/txn/client/operator.go, pkg/txn/client/types.go, pkg/txn/storage/memorystorage/storage_txn_client.go, pkg/vm/engine/entire_engine_test.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4676
enable retry when first lock table
=> enable retry when first lock table

pkg/sql/plan/apply_indices.go
issue #20992 
optimize stats when table not flushed yet step II
=> optimize stats when table not flushed yet step II

pkg/lockservice/lock_table_keeper.go
issue #21011 
add debug log to lock service heartbeat
=> add debug log to lock service heartbeat to 2.0

pkg/objectio/injects.go, pkg/vm/engine/tae/db/checkpoint/executor.go, pkg/vm/engine/tae/db/checkpoint/replay.go, pkg/vm/engine/tae/db/test/db_test.go, pkg/vm/engine/tae/logtail/handle.go
issue #21010 
incremental checkpoint metadata may not contains the latest global checkpoint
=> fix checkpoint replay

test/distributed/cases/function/func_make_date.sql
- [X ] Test and CI
issue #21024
add bvt tag for issue 21024
___
Tests
___
- Added @bvt test tags around the leap year test case using MAKEDATE() function
- Tags reference issue #21024
- No functional changes to the test logic itself
___
<tr>
<td>
<details>
<summary><strong>func_make_date.sql</strong><dd><code>Add BVT tags for leap year test case</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
test/distributed/cases/function/func_make_date.sql
<li>Added @bvt tags around leap year test case to mark it for issue #21024
</details>
</td> …
=> add bvt tag for issue #21024

pkg/vm/engine/tae/db/checkpoint/runner_test.go, pkg/vm/engine/tae/db/checkpoint/store.go
issue #21009
Fix collectckpinrange
=> Fix collectckpinrange

pkg/logservice/service_commands.go
issue https://github.com/matrixorigin/MO-Cloud/issues/4098
fix context timeout for heartbeat
=> [bug] logservice: fix context timeout for heartbeat

pkg/vm/engine/disttae/engine.go, pkg/vm/engine/disttae/txn.go, pkg/vm/engine/disttae/types.go
issue https://github.com/matrixorigin/MO-Cloud/issues/4702
fix unexpected behavior in rollbacking database operation
=> fix rollback database ddl 2.0

pkg/vm/engine/tae/db/checkpoint/store.go, test/distributed/cases/function/func_datetime_utc_timestamp.result
issue #21009 
Fix collectckpinrange
=> Fix collect ckps in range

test/distributed/cases/function/func_datetime_utc_timestamp.result, test/distributed/cases/function/func_datetime_utc_timestamp.test
issue #21048
The test case design is unreasonable; let’s remove it for now.
=> ignore base test cases

pkg/vm/engine/tae/rpc/inspect.go, pkg/vm/engine/tae/rpc/tool.go, pkg/vm/engine/tae/rpc/tool_test.go
issue [moc#3209](https://github.com/matrixorigin/MO-Cloud/issues/3209)
手动gc工具，使用文档：https://github.com/matrixorigin/docs/blob/main/tech-notes/dnservice/gc_tool.md
=> feat: mo gc tool

pkg/vm/engine/tae/db/merge/policyOverlap.go, pkg/vm/engine/tae/db/merge/utils.go
=> stop cn merge

pkg/vm/engine/tae/db/merge/utils.go, pkg/vm/engine/tae/db/merge/utils_test.go, pkg/vm/engine/tae/db/test/db_test.go, pkg/vm/engine/tae/tables/jobs/mergeobjects.go
issue #21005
- avoid blocking merge in certain scenarios
- provide a more conservative estimate of merge memory consumption
=> fix dn crash 2.0

pkg/lockservice/log.go, pkg/lockservice/orphan_txn_test.go, pkg/lockservice/service.go
issue #21063 
fix isValidRemoteTxn
=> fix isValidRemoteTxn

pkg/frontend/internal_executor.go, pkg/frontend/mysql_protocol.go, pkg/frontend/query_result.go, pkg/frontend/routine.go, pkg/frontend/routine_manager.go, pkg/frontend/session.go
issue #https://github.com/matrixorigin/matrixone/issues/12390
关掉一些不必要的INFO LOG，减少日志量
=> disable logs

pkg/sql/plan/function/func_prefix.go, pkg/sql/plan/function/func_prefix_test.go
issue #20940 
fix bug: prefix_xx get incorrect result
=> fix bug: prefix_xx get incorrect result

pkg/container/vector/search.go, pkg/vm/engine/engine_util/filter_test.go, pkg/vm/engine/engine_util/pk_filter.go, test/distributed/cases/optimizer/blockfilter.result, test/distributed/cases/optimizer/blockfilter.test
issue https://github.com/matrixorigin/MO-Cloud/issues/4723
Fix bug: incorrect pk filter for string column
=> Fix bug: incorrect pk filter for string column

pkg/objectio/injects.go, pkg/sql/compile/alter.go, pkg/sql/compile/ddl.go, pkg/sql/compile/sql_executor.go, pkg/util/executor/options.go, pkg/util/executor/types.go, pkg/vm/engine/disttae/engine.go, pkg/vm/engine/disttae/logtail_consumer.go, pkg/vm/engine/disttae/txn_database.go, pkg/vm/engine/disttae/txn_table.go, pkg/vm/engine/disttae/txn_table_test.go, pkg/vm/engine/test/disttae_engine_test.go, test/distributed/cases/pessimistic_transaction/ddl_atomicity.result, test/distributed/cases/pessimistic_transaction/ddl_atomicity.sql
issue #20801
- remove the txnNeedRetry error in isCreatedInTxn
- check EOB before converting errors into BadDB to prevent the pipeline from missing retry error
- more log
=> fix need retry in engine

pkg/vm/engine/tae/db/replay.go, pkg/vm/engine/tae/db/test/db_test.go, pkg/vm/engine/tae/logstore/driver/batchstoredriver/batchstore_test.go, pkg/vm/engine/tae/logstore/driver/logservicedriver/driver_test.go, pkg/vm/engine/tae/logstore/driver/logservicedriver/entry.go, pkg/vm/engine/tae/logstore/driver/logservicedriver/replay.go, pkg/vm/engine/tae/logstore/driver/logservicedriver/replay_test.go, pkg/vm/engine/tae/logstore/driver/type.go, pkg/vm/engine/tae/logstore/samples/replay/main.go, pkg/vm/engine/tae/logstore/store/replay.go, pkg/vm/engine/tae/logstore/store/type.go, pkg/vm/engine/tae/wal/driver.go
issue #20575
check ckp lsn when skip driver entry
=> Fix skip entry in replay 

pkg/container/vector/search.go, pkg/vm/engine/engine_util/filter_test.go, pkg/vm/engine/engine_util/pk_filter.go, test/distributed/cases/optimizer/blockfilter.result, test/distributed/cases/optimizer/blockfilter.test
Fix bug: incorrect pk filter for string column
Approved by: @XuPeng-SH, @gouhongshen, @heni02
issue https://github.com/matrixorigin/MO-Cloud/issues/4723
Fix bug: incorrect pk filter for string column
=> Fix bug: incorrect pk filter for string column (#21085)

pkg/vm/engine/tae/db/replay.go, pkg/vm/engine/tae/db/test/db_test.go, pkg/vm/engine/tae/logstore/driver/batchstoredriver/batchstore_test.go, pkg/vm/engine/tae/logstore/driver/logservicedriver/driver.go, pkg/vm/engine/tae/logstore/driver/logservicedriver/driver_test.go, pkg/vm/engine/tae/logstore/driver/logservicedriver/entry.go, pkg/vm/engine/tae/logstore/driver/logservicedriver/replay.go, pkg/vm/engine/tae/logstore/driver/logservicedriver/replay_test.go, pkg/vm/engine/tae/logstore/driver/type.go, pkg/vm/engine/tae/logstore/samples/replay/main.go, pkg/vm/engine/tae/logstore/store/replay.go, pkg/vm/engine/tae/logstore/store/type.go, pkg/vm/engine/tae/wal/driver.go
issue #20575
check ckp lsn when skip driver entry
=> Fix skip entry in replay

pkg/vm/engine/tae/logstore/driver/logservicedriver/entry.go, pkg/vm/engine/tae/logstore/driver/logservicedriver/replay.go, pkg/vm/engine/tae/logstore/driver/logservicedriver/replay_test.go
=> fix replay

pkg/vm/engine/tae/logtail/reader.go, pkg/vm/engine/tae/logtail/table.go, pkg/vm/engine/tae/logtail/table_test.go, pkg/vm/engine/tae/rpc/handle_debug.go
issue #https://github.com/matrixorigin/matrixone/issues/20762
skip the TS check when `getChangedTableList`.
=> skip the TS check when `getChangedTableList`.

pkg/vm/engine/disttae/db.go, pkg/vm/engine/disttae/logtail_consumer.go, pkg/vm/engine/disttae/logtail_consumer_test.go, pkg/vm/engine/disttae/stats_test.go, pkg/vm/engine/disttae/txn_table.go, pkg/vm/engine/disttae/txn_table_test.go, pkg/vm/engine/disttae/types.go
issue https://github.com/matrixorigin/MO-Cloud/issues/4506
- prevent data race on cache
=> fix incomplete cache 2.0

pkg/objectio/injects.go, pkg/sql/compile/alter.go, pkg/sql/compile/ddl.go, pkg/sql/compile/sql_executor.go, pkg/util/executor/options.go, pkg/util/executor/types.go, pkg/vm/engine/disttae/cache/catalog.go, pkg/vm/engine/disttae/cache/types.go, pkg/vm/engine/disttae/engine.go, pkg/vm/engine/disttae/logtail_consumer.go, pkg/vm/engine/disttae/txn_database.go, pkg/vm/engine/disttae/txn_table.go, pkg/vm/engine/disttae/txn_table_test.go, pkg/vm/engine/test/disttae_engine_test.go, test/distributed/cases/pessimistic_transaction/ddl_atomicity.result, test/distributed/cases/pessimistic_transaction/ddl_atomicity.sql
issue #20801
- Given 8d91524f1, now revert https://github.com/matrixorigin/matrixone/commit/0fc3b8d66279f5d6e4ec43c614b5c88bc9d530b2. 
- remove the txnNeedRetry error in isCreatedInTxn
- check EOB before converting errors into BadDB to prevent the pipeline from missing retry error
more log
=> fix need retry in engine 2.0

pkg/sql/colexec/dedupjoin/join.go, test/distributed/cases/dml/insert/on_duplicate_key.result, test/distributed/cases/dml/insert/on_duplicate_key.sql
issue #20645 
fix bug: recall NewExpressionExecutor in prepare
=> fix bug: recall NewExpressionExecutor in prepare

pkg/frontend/authenticate_test.go, pkg/frontend/publication_subscription.go, pkg/frontend/publication_subscription_test.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4725
check col existence of mo_pubs/subs
=> [Cherry-pick] check col existence of mo_pubs/subs

pkg/vm/engine/disttae/txn.go, pkg/vm/engine/disttae/txn_database.go, pkg/vm/engine/disttae/txn_table.go, pkg/vm/engine/disttae/types.go
issue #20801 https://github.com/matrixorigin/MO-Cloud/issues/4733
- provide a better impl for isCreatedInTxn check
=> fix createdInTxn impl 2.0

pkg/vm/engine/disttae/txn.go
- [ x] BUG
issue #21049 
1.Fix bug.
=> [#21049] Fix-bug-cherry-pick

pkg/sql/compile/scope.go, pkg/vm/engine/disttae/txn_table.go, pkg/vm/engine/disttae/txn_table_sharding.go, test/distributed/cases/optimizer/shuffle.result, test/distributed/cases/optimizer/shuffle.test
issue #https://github.com/matrixorigin/MO-Cloud/issues/4738
optimize readers when there is false filter
=> optimize readers when there is false filter 

pkg/bootstrap/service_upgrade.go
issue https://github.com/matrixorigin/MO-Cloud/issues/4741
When incrementally upgrading, if the schema version has reached the final version, mark and return it
=> If the schema version has reached the final version, mark and return

pkg/vm/engine/disttae/mo_table_stats.go
issue #https://github.com/matrixorigin/matrixone/issues/21083 https://github.com/matrixorigin/matrixone/issues/21106
fix partition state pinned by mo table stats.
=> to 2.0: fix partition state pinned by mo table stats and adding some metrics.

pkg/vm/engine/tae/catalog/catalogreplay.go, pkg/vm/engine/tae/catalog/schema.go, pkg/vm/engine/tae/db/checkpoint/replay.go, pkg/vm/engine/tae/tables/table_scan.go
issue #21160 
improve catalog replay
=> improve catalog

pkg/bootstrap/custom_upgrade.go, pkg/bootstrap/service_upgrade.go, pkg/bootstrap/service_upgrade_tenant.go, pkg/bootstrap/upgrade.go, pkg/bootstrap/versions/upgrade_strategy.go, pkg/bootstrap/versions/upgrade_tenant_task.go, pkg/bootstrap/versions/version.go, pkg/bootstrap/versions/version_upgrade.go
issue https://github.com/matrixorigin/MO-Cloud/issues/4741
Resolve the issue of transaction leakage when upgrading using TxnExecutor
=> Change the upgraded panic error to fatal

pkg/objectio/injects.go, pkg/vm/engine/disttae/logtail_consumer.go, pkg/vm/engine/tae/logtail/service/client.go, test/distributed/cases/dml/checkpoint/connectlogtail.result, test/distributed/cases/dml/checkpoint/connectlogtail.test
issue #20801 #21162
-Resolve inconsistencies in pausing and resuming logtail consumers.
=> fix disorder in reconnecting logtail 2.0

pkg/util/metric/v2/metrics.go, pkg/util/metric/v2/stats.go, pkg/vm/engine/disttae/stats.go, pkg/vm/engine/disttae/stats_test.go
issue #21052 #20577 #21174
add some metrics and watcher.
=> [improvement] stats: add some metrics and watcher.

pkg/bootstrap/service_upgrade.go
issue https://github.com/matrixorigin/MO-Cloud/issues/4741
restore upgrade tenant Code
=> restore upgrade tenant Code 

pkg/bootstrap/service_upgrade.go
issue https://github.com/matrixorigin/MO-Cloud/issues/4741
restore upgrade tenant Code
=> restore upgrade tenant Code

pkg/sql/compile/compile.go, pkg/sql/plan/stats.go, test/distributed/cases/optimizer/shuffle.result, test/distributed/cases/optimizer/shuffle.test
issue #20560 
adjust dop of shuffle plan for future refactoring
=> adjust dop of shuffle plan for future refactoring

pkg/proxy/conn_manager.go
issue https://github.com/matrixorigin/MO-cloud/issues/4741
add logs when connect/disconnect
=> [improvement] proxy: add logs when connect/disconnect

pkg/cdc/sinker.go
issue #21181
prune incomplete sql before send
=> prune incomplete sql before send

pkg/vm/engine/tae/db/test/db_test.go, pkg/vm/engine/tae/tables/jobs/flushTableTail.go, pkg/vm/engine/tae/tasks/poolhandler.go
issue #21195
- fix the panic check in flushing tombstones and allow it to throw an error
- do not block closing db if tasks panic
=> fix TestReplay8

pkg/vm/engine/disttae/local_disttae_datasource.go, pkg/vm/engine/disttae/txn.go, pkg/vm/engine/disttae/txn_table.go
- [x ] BUG
issue #21179 
1.Fix bug
=> [CherryPick]Fix bug for 21179

pkg/lockservice/service_remote.go, pkg/lockservice/service_remote_test.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4750 #https://github.com/matrixorigin/MO-Cloud/issues/4748
fix unlock when version of bind changed
=> fix unlock when version of bind changed

pkg/container/types/enum.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4749
fix enum type parse stage
=> fix enum type parse stage(#2.0-dev)

pkg/container/types/enum.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4749
fix enum type parse stage
=> fix enum type parse stage

pkg/common/malloc/default.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4753
default to C.malloc
=> malloc: default to malloc

Makefile
issue #21220
support "make GOBUILD_OPT=-cover" to allow build with coverage test.
=> support GOBUILD_OPT pass to Makefile

pkg/vm/engine/disttae/mo_table_stats.go, pkg/vm/engine/tae/rpc/handle_debug.go
issue #https://github.com/matrixorigin/matrixone/issues/21213
fix the err missing when `GetChangedTableList`.
=> fix the err missing when `GetChangedTableList`.

pkg/vm/engine/tae/db/test/db_test.go, pkg/vm/engine/tae/tables/jobs/flushTableTail.go, pkg/vm/engine/tae/tasks/poolhandler.go
issue #21195
- fix the panic check in flushing tombstones and allow it to throw an error
- do not block closing db if tasks panic
=> fix TestReplay8 2.0

pkg/container/vector/vector.go, pkg/vm/engine/tae/catalog/catalogreplay.go, pkg/vm/engine/tae/catalog/schema.go
issue #21225
- Copy bytes to target fields
=> fix data copy in replaying from checkpoint

pkg/common/malloc/c_allocator.go, pkg/common/malloc/utils.go
issue #21226 
reduce peak memory usage.
=> malloc: tune glibc malloc

pkg/vm/engine/tae/tables/utils.go
issue https://github.com/matrixorigin/matrixone/issues/21246
Fix Transient VPool leak
=> Fix Transient VPool leak

pkg/sql/plan/shuffle.go, pkg/sql/plan/shuffle_test.go
issue #20560 
fix a bug for shuffle dop
=> fix a bug for shuffle dop

pkg/common/malloc/c_allocator.go, pkg/common/malloc/c_allocator_darwin.go, pkg/common/malloc/c_allocator_linux.go, pkg/common/malloc/c_allocator_test.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4753
fix build in macos
=> malloc: fix macos build

pkg/sql/colexec/table_function/table_function.go, pkg/sql/colexec/table_function/types.go, pkg/sql/compile/compile.go, pkg/sql/plan/current_account.go, pkg/sql/plan/fulltext.go, pkg/sql/plan/generate_series.go, pkg/sql/plan/meta_scan.go, pkg/sql/plan/metadata_scan.go, pkg/sql/plan/plugin.go, pkg/sql/plan/processlist.go, pkg/sql/plan/pushdown.go, pkg/sql/plan/query_builder.go, pkg/sql/plan/stage.go, pkg/sql/plan/system_view.go, pkg/sql/plan/unnest.go, test/distributed/cases/fulltext/fulltext.result
issue # https://github.com/matrixorigin/matrixone/issues/12873
make table_function as source class operator
=> refactor: make table_function as source class operator

pkg/sql/colexec/mock_util.go, pkg/sql/colexec/partition/partition.go, pkg/sql/colexec/partition/partition_test.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4769
fix operator of partition
=> fix operator of partition

pkg/txn/client/client.go, pkg/txn/client/client_test.go, pkg/txn/client/operator.go
issue [4771](https://github.com/matrixorigin/MO-Cloud/issues/4771)
fix txn client deadlock 2.0
=> fix txn client deadlock 2.0

pkg/frontend/export.go, pkg/frontend/export_test.go, test/distributed/cases/array/array.result, test/distributed/cases/array/array.sql
issue #https://github.com/matrixorigin/MO-Cloud/issues/4765
support dump for vecf32 and vecf64
=> support dump for vecf32 and vecf64(#2.0-dev)

pkg/common/moerr/error.go, pkg/pb/lock/lock.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4768
add log of stack for retry lock
=> add log of stack for retry lock

pkg/vm/engine/tae/db/test/db_test.go, pkg/vm/engine/tae/logtail/snapshot.go
issue https://github.com/matrixorigin/matrixone/issues/21292
Fix pitrtid is not unique and panic
=> Fix pitrtid is not unique and panic

pkg/fileservice/aliyun_sdk.go, pkg/fileservice/aws_sdk_v2.go, pkg/fileservice/disk_object_storage.go, pkg/fileservice/error.go, pkg/fileservice/minio_sdk.go, pkg/fileservice/qcloud_sdk.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4778
add more logs
=> fileservice: more logs for debugging EOF in Write

pkg/vm/engine/tae/blockio/utils.go
issue https://github.com/matrixorigin/matrixone/issues/21305
Fix the bug that onBlockSelectedFn does not return error
=> Fix the bug that onBlockSelectedFn does not return error

pkg/common/moerr/error.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4768
restore moerr code
=> restore moerr code

pkg/partitionservice/service_hash.go, pkg/partitionservice/service_range.go, pkg/partitionservice/service_range_test.go, pkg/sql/parsers/tree/format.go, pkg/tests/partition/create_hash_test.go, pkg/tests/partition/create_range_test.go, pkg/tests/partition/partition_test.go
issue #16438 
support range columns partition
=> support range columns partition

pkg/common/morpc/backend_test.go
issue #20610
fix TestCannotBusyLoopIfWriteCIsFull failed
=> fix TestCannotBusyLoopIfWriteCIsFull failed  to 2.0

pkg/common/morpc/backend_test.go
issue #20610
fix TestCannotBusyLoopIfWriteCIsFull failed
=> fix TestCannotBusyLoopIfWriteCIsFull failed

pkg/sql/colexec/multi_update/s3writer.go
issue #21294
Change flush s3 threshold for local run
=> Change flush s3 threshold for local run

pkg/lockservice/cfg.go, pkg/lockservice/service_remote.go, pkg/lockservice/service_test.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4748
cleam remote txn when stop cn
=> cleam remote txn when stop cn

test/distributed/cases/dml/checkpoint/connectlogtail.result, test/distributed/cases/dml/checkpoint/connectlogtail.test
issue https://github.com/matrixorigin/matrixone/issues/21320
- avoid blocking all tests
=> lower possibility of failure in receiving logtail

test/distributed/cases/dml/checkpoint/connectlogtail.result, test/distributed/cases/dml/checkpoint/connectlogtail.test
issue https://github.com/matrixorigin/matrixone/issues/21320
- avoid blocking all tests
=> lower possibility of failure in receiving logtail 2.0

pkg/partitionservice/service.go, pkg/partitionservice/service_test.go
issue #16438 
add partition metadata cache
=> add partition metadata cache

pkg/sql/colexec/top/types.go, pkg/sql/colexec/top/types_test.go
fix top container reset
Approved by: @ouyuanning
issue https://github.com/matrixorigin/matrixone/issues/21148
fix top container reset
=> fix top container reset (#21208)

pkg/sql/colexec/lockop/lock_op.go
issue # https://github.com/matrixorigin/matrixone/issues/21153
make sure not null value for lock_op.lockRows
=> refactor: make sure not null value for lock_op.lockRows

pkg/sql/compile/compile.go
issue #https://github.com/matrixorigin/matrixone/issues/21277
add load log
=> add load log

pkg/sql/colexec/top/types.go, test/distributed/cases/prepare/prepare.result, test/distributed/cases/prepare/prepare.test
issue #21337
Fix bug: double free in Top Operator
=> Fix bug: double free in Top Operator

pkg/txn/client/leak_checker.go
issue [#4812](https://github.com/matrixorigin/MO-Cloud/issues/4812)
fix leak check hung
=> fix leak check hung

pkg/txn/client/leak_checker.go
issue [#4812](https://github.com/matrixorigin/MO-Cloud/issues/4812)
fix leak check hung
=> fix leak check hung to 2.0

pkg/common/malloc/c_allocator_linux_musl.go
issue #21343 
some glibc specific functions is not supported by the musl libc.
=> malloc: fix musl build

pkg/vm/engine/disttae/util.go, pkg/vm/engine/disttae/util_test.go
issue https://github.com/matrixorigin/MO-Cloud/issues/4825
add ut and fix logs
=> add ut and fix logs

pkg/cdc/types.go, pkg/frontend/cdc.go, pkg/frontend/cdc_test.go
=> fix check pitr

pkg/sql/compile/ddl.go
issue #21352 
fix bug: panic when drop table
=> fix bug: panic when drop table

pkg/sql/colexec/lockop/lock_op.go
issue # https://github.com/matrixorigin/matrixone/issues/21237
use relation reset interface for reusing relation
=> refactor: use relation reset interface for reusing relation

pkg/common/mpool/mpool.go
issue #21369 
change threshold of realloc
=> change threshold of realloc

pkg/sql/colexec/deletion/deletion.go, pkg/sql/colexec/deletion/deletion_test.go, pkg/sql/colexec/deletion/types.go, pkg/sql/colexec/insert/insert.go, pkg/sql/colexec/insert/insert_test.go, pkg/sql/colexec/insert/types.go
issue #https://github.com/matrixorigin/matrixone/issues/21237
insert/deletion op using relation reset interface
=> refactor: insert/deletion op using relation reset interface

pkg/vm/engine/disttae/txn_database.go, pkg/vm/engine/disttae/util.go, pkg/vm/engine/test/disttae_engine_test.go
issue https://github.com/matrixorigin/MO-Cloud/issues/4823
- Include error handling to avoid panic.
=> add txn status check

pkg/sql/plan/build_dml_util.go
issue #21384 
fix bug : incorrect lock index
=> fix bug : incorrect lock index

CODEOWNERS
=> Update code owners.

pkg/objectio/cache.go
issue https://github.com/matrixorigin/matrixone/issues/21391
Reduce the frequent calls to the String() method of objectName
=>  Reduce the frequent calls to the String() method of objectName

pkg/vm/engine/tae/db/merge/policyOverlap.go, pkg/vm/engine/tae/db/merge/policy_test.go
issue #[MOC-5026](https://github.com/matrixorigin/MO-Cloud/issues/5026)
fix memory limitation did not work
=> fix memory limitation

pkg/cdc/sinker.go, pkg/cdc/sinker_test.go
issue #21387 
rewrite sql when cdc sink to mo
=> cdc sink to mo rewrite sql

pkg/vm/engine/tae/db/cronjobs.go
issue #https://github.com/matrixorigin/matrixone/issues/21438
fix the merge schedule interval.
=> fix the merge schedule interval.

pkg/vm/engine/tae/catalog/table.go, pkg/vm/engine/tae/db/merge/policyCompact.go, pkg/vm/engine/tae/db/merge/policyGroup.go, pkg/vm/engine/tae/db/merge/policyOverlap.go, pkg/vm/engine/tae/db/merge/policyTombstone.go, pkg/vm/engine/tae/db/merge/policy_test.go, pkg/vm/engine/tae/db/merge/scheduler.go, pkg/vm/engine/tae/db/merge/scheduler_test.go, pkg/vm/engine/tae/db/merge/utils.go, pkg/vm/engine/tae/db/test/db_test.go, pkg/vm/engine/tae/mergesort/task.go
issue https://github.com/matrixorigin/MO-Cloud/issues/4979
fix small objects merge policy
=> Fix various merge issues

pkg/sql/compile/analyze_module.go, pkg/sql/compile/compile.go, pkg/sql/compile/compile2.go, pkg/sql/compile/types.go
issue #https://github.com/matrixorigin/matrixone/issues/21235
AnalyzeExecPlan reduce CPU usage in Prepare mode
=> refactor: AnalyzeExecPlan reduce CPU usage in Prepare mode

pkg/vm/engine/tae/db/merge/policyOverlap.go
issue https://github.com/matrixorigin/MO-Cloud/issues/4979
- Disregard small batch zm overlap; otherwise, TPCC performance will deteriorate.
=> mitigate zm merge

pkg/sql/colexec/evalExpression.go, pkg/sql/colexec/evalExpressionReset.go
issue #21485 
make ParamExprEvaluator can resuse the memory
=> make ParamExprEvaluator can resuse the memory

pkg/fileservice/get.go, pkg/fileservice/hdfs.go, pkg/fileservice/hdfs_test.go, pkg/fileservice/object_storage_arguments.go, pkg/fileservice/s3_fs.go
issue #20574 
do not make dir and check permission of root path if not required.
=> fileservice: various HDFS fixes

pkg/vm/engine/disttae/txn.go
issue #https://github.com/matrixorigin/matrixone/issues/21383
Fast fix for exceeding the object size limit. This is a simple fix to unblock the test; I will refactor it later.
=> Fast fix for exceeding the object size limit.

pkg/bootstrap/upgrade.go, pkg/bootstrap/versions/v2_1_0/cluster_upgrade_list.go, pkg/bootstrap/versions/v2_1_0/log.go, pkg/bootstrap/versions/v2_1_0/tenant_upgrade_list.go, pkg/bootstrap/versions/v2_1_0/upgrade.go, pkg/bootstrap/versions/v2_1_0/upgrade_test.go
issue #21513 
add new upgrade entry
=> add new upgrade entry

pkg/sql/colexec/shuffle/shuffle.go, pkg/sql/colexec/shuffle/shuffle_test.go, pkg/sql/colexec/shuffle/shufflepool.go, pkg/sql/colexec/shuffle/types.go, pkg/sql/colexec/shuffleV2/shuffle_test.go, pkg/sql/colexec/shuffleV2/shufflepool.go
issue #21414
split batches for shuffle operator
=> split batches for shuffle operator

pkg/sql/compile/sql_executor_context.go
issue #21414 
fix bug: can not get stats cache in txn Executor
=> fix bug: can not get stats cache in txn Executor

test/distributed/cases/prepare/prepare.test
issue # https://github.com/matrixorigin/matrixone/issues/21511
fix  bvt in prepare.test
=> fix: bvt in prepare.test

pkg/objectio/ioutil/writer.go, pkg/objectio/writer.go, pkg/vm/engine/tae/catalog/table.go, pkg/vm/engine/tae/catalog/table_test.go, pkg/vm/engine/tae/db/merge/policyCompact.go, pkg/vm/engine/tae/db/merge/policyGroup.go, pkg/vm/engine/tae/db/merge/policyOverlap.go, pkg/vm/engine/tae/db/merge/policyTombstone.go, pkg/vm/engine/tae/db/merge/policy_test.go, pkg/vm/engine/tae/db/merge/scheduler.go, pkg/vm/engine/tae/db/merge/scheduler_test.go, pkg/vm/engine/tae/db/merge/utils.go, pkg/vm/engine/tae/db/merge/utils_test.go, pkg/vm/engine/tae/db/test/db_test.go, pkg/vm/engine/tae/mergesort/merger.go, pkg/vm/engine/tae/mergesort/reshaper.go, pkg/vm/engine/tae/mergesort/task.go, pkg/vm/engine/tae/mergesort/types.go, pkg/vm/engine/tae/mergesort/types_test.go
issue https://github.com/matrixorigin/MO-Cloud/issues/4979
1. Combine a group of small objects if no overlapping objects are selected. 
3. Use a more accurate estimation of the bytes written when executing the merge task.
=> sync verfied 2.0 merge changes to 2.1

.github/mergify.yml
issue #
modify mergify config to adapt 2.1-dev
=> modify mergify config to adapt 2.1-dev

pkg/vm/engine/disttae/mo_table_stats.go, pkg/vm/engine/disttae/mo_table_stats_test.go
issue #https://github.com/matrixorigin/matrixone/issues/21537
improve the performance of cleaning up the deleted table stats from the stats table.
multiple OR conditions SQL statement to IN condition statement.
=> improve the performance of cleaning up the deleted table stats from the stats table.

test/distributed/cases/prepare/prepare.result, test/distributed/cases/prepare/prepare.test
issue # https://github.com/matrixorigin/matrixone/issues/21511
ignore some test in prepare.test
=> fix: ignore some test in prepare.test

pkg/common/malloc/fixed_size_mmap_allocator.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/4753
fix VSS leaks in malloc allocator
=> malloc: fix VSS leaks

pkg/vm/engine/tae/db/gc/v3/checkpoint.go, pkg/vm/engine/tae/db/gc/v3/merge.go
issue https://github.com/matrixorigin/MO-Cloud/issues/5081
Fixed GC merge checkpoint memory leak
=> Fixed GC merge checkpoint memory leak

pkg/vm/engine/ckputil/meta.go, pkg/vm/engine/tae/logtail/ckp_reader.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/5081
fix read ckp meta
=> fix ckp meta

pkg/sql/compile/analyze_module.go, pkg/sql/compile/analyze_module_test.go, pkg/sql/compile/compile2.go
issue # https://github.com/matrixorigin/matrixone/issues/21501
AnalyzeExecPlan bug which cause sysbench10w update panic
=> fix: AnalyzeExecPlan bug which cause sysbench10w update panic

pkg/cdc/sinker.go, pkg/cdc/sinker_test.go, pkg/vm/engine/disttae/logtailreplay/change_handle.go, pkg/vm/engine/test/change_handle_test.go
issue #21565 
update cdc sinker
flush sql buf for each batch
fix quick next
=> update cdc sinker and changes handle

pkg/vm/engine/disttae/txn.go
issue # https://github.com/matrixorigin/matrixone/issues/21677#issuecomment-2791590377
Filter out the deletes object when merging deletes in the workspace.
=> to 2.1: filter out the deletes object when merging deletes in the workspace.

pkg/vm/engine/disttae/txn.go
issue #21565 
sort sel before shrinkBatchWithRowids
=> fix mergeTxnWorkspaceLocked

pkg/sql/plan/agg_pushdown_pullup.go, test/distributed/cases/optimizer/pushdown.result, test/distributed/cases/optimizer/pushdown.test
issue https://github.com/matrixorigin/MO-Cloud/issues/5186
fix bug: agg push down panic
=> fix bug: agg push down panic

test/distributed/cases/dml/replace/replace_workspace.result, test/distributed/cases/dml/replace/replace_workspace.sql
issue #https://github.com/matrixorigin/matrixone/issues/21565
BVT cases for the replace statements in the workspace.
=> BVT cases for the replace statements in the workspace.

pkg/vm/engine/tae/catalog/table_test.go, pkg/vm/engine/tae/db/test/db_test.go, pkg/vm/engine/tae/testutils/config/options.go, pkg/vm/engine/tae/testutils/config/options_test.go
issue #21716
fix TestAppend2, not GC
=> fix TestAppend2

pkg/vm/engine/tae/db/checkpoint/executor.go, pkg/vm/engine/tae/db/checkpoint/ickp_exec.go, pkg/vm/engine/tae/logtail/ckp_writer.go
=> fix ExportStats

pkg/vm/engine/tae/db/test/db_test.go
issue https://github.com/matrixorigin/matrixone/issues/21722
cherry-pick fixed pr from 2.1
=> Fix TestCkpLeak (#21572)

pkg/vm/engine/disttae/txn.go, pkg/vm/engine/disttae/txn_table.go, pkg/vm/engine/disttae/types.go, pkg/vm/engine/tae/blockio/read.go, pkg/vm/engine/test/mo_table_stats_test.go, test/distributed/cases/dml/delete/delete_workspace.result, test/distributed/cases/dml/delete/delete_workspace.sql
issue #https://github.com/matrixorigin/matrixone/issues/21726
Fix the compaction of objects by deletion when merging the TXN workspace.
=> fix the compaction of objects by deletion when merging the TXN workspace.

pkg/common/mpool/mpool.go, pkg/vm/engine/tae/mergesort/merger.go
issue #21730
- Write buffer immediately if oversized
- Add cap limit when calcNewCap
=> fix merge alloc

pkg/sql/plan/build_dml_util.go
issue https://github.com/matrixorigin/mo-cloud/issues/5199
to resolve OOM issue
=> [opt] improve join order and enable runtime filter for fulltext UPDATE

pkg/vm/engine/readutil/expr_util.go
issue #https://github.com/matrixorigin/matrixone/issues/21739
Fix the full table scan issue when `where sortKey = ''`.
```
create table t (a varchar primary key);
explain analyze select * from t where a = ''; (empty string)
```
=> Fix the block filter not work when `where sortKey = ''`.

pkg/common/mpool/mpool.go, pkg/vm/engine/tae/mergesort/merger.go
issue #21730
- Write buffer immediately if oversized
- Add cap limit when calcNewCap
=> Fix merge alloc 2.1

pkg/sql/plan/expr_opt.go, pkg/sql/plan/stats.go, pkg/sql/plan/utils.go, test/distributed/cases/optimizer/blockfilter.result
issue https://github.com/matrixorigin/MO-Cloud/issues/5097
to speed up range queries on statement_info
=> [opt] convert BETWEEN filter to PREFIX_BETWEEN on composite keys

pkg/vm/engine/disttae/txn_table.go
issue #https://github.com/matrixorigin/matrixone/issues/21748
Fix the duplicated entry issue caused by merging the deletion on the uncommitted objects with unsorted offsets
=> fix the duplicated entry issue caused by merging deletion on the uncommitted objects.

pkg/vm/engine/disttae/local_disttae_datasource.go, pkg/vm/engine/readutil/datasource.go
issue #https://github.com/matrixorigin/matrixone/issues/21565 https://github.com/matrixorigin/matrixone/issues/21713
1. using the bitmap store the row id offsets.
2. improve the GetTombstones performance.
=> small updates for the workspace.

pkg/vm/engine/tae/db/test/db_test.go
issue https://github.com/matrixorigin/matrixone/issues/21606
Fix TestPitrMeta
=> Fix TestPitrMeta

pkg/common/morpc/client.go, pkg/common/morpc/server.go
issue #12259
reduce goetty log output, only keep fatal log
=> reduce goetty log output

test/distributed/cases/ddl/create_table_as_select.result, test/distributed/cases/ddl/create_table_as_select.sql
issue #14475
remove bvt tag 14475
=> [ci] remove bvt tag 14475

pkg/sql/plan/build_ddl.go
issue #20578
Add comments for Master and Regular index.
=> [Refactoring]: Add comment on functions like buildFulltextIndexTable

pkg/vm/engine/tae/db/checkpoint/flusher.go, pkg/vm/engine/tae/db/merge/utils.go, pkg/vm/engine/tae/db/test/db_test.go, pkg/vm/engine/tae/db/test/tables_test.go, pkg/vm/engine/tae/iface/txnif/memo.go, pkg/vm/engine/tae/logtail/collector.go, pkg/vm/engine/tae/logtail/reader.go, pkg/vm/engine/tae/model/tree.go, pkg/vm/engine/tae/model/tree_test.go, pkg/vm/engine/tae/rpc/handle_debug.go, pkg/vm/engine/tae/tables/table_scan.go, pkg/vm/engine/tae/txn/txnbase/command.go, pkg/vm/engine/tae/txn/txnbase/store.go, pkg/vm/engine/test/disttae_engine_test.go
issue #https://github.com/matrixorigin/matrixone/issues/19475
Remove object count & tombstone count
=> Remove some fileds to simplify dirty tree 

pkg/vm/engine/tae/db/checkpoint/replay.go, pkg/vm/engine/tae/db/gc/v3/checkpoint.go, pkg/vm/engine/tae/db/gc/v3/exec_v1.go, pkg/vm/engine/tae/logtail/snapshot.go
issue https://github.com/matrixorigin/matrixone/issues/21788
Remove GC's panic(), use Warn log instead: GC-PANIC
=> Remove GC's panic(), use Warn log instead: GC-PANIC

pkg/objectio/constructors.go, pkg/objectio/ioutil/loadfuncs.go
issue https://github.com/matrixorigin/matrixone/issues/21838
Add LoadColumnsData error log
=> Add LoadColumnsData error log

pkg/lockservice/service_observability_test.go, pkg/lockservice/service_remote_test.go
issue #21853 
fix TestLockWithBindIsStale, TestIterLocks
=> fix TestLockWithBindIsStale, TestIterLocks

pkg/common/moerr/error.go, pkg/vm/engine/tae/db/merge/executor.go, pkg/vm/engine/tae/db/scheduler.go
issue https://github.com/matrixorigin/matrixone/issues/21847
fix data race
=> fix data race 2.2

pkg/vm/engine/tae/logstore/driver/logservicedriver/replay_test.go
issue #21869 
fix Test_Replayer11
=> fix Test_Replayer11

pkg/sql/plan/join_order.go
issue https://github.com/matrixorigin/MO-Cloud/issues/5345
ensure that index table is on probe side and runtime filter is pushed down
=> fix join order for DML plan

pkg/sql/plan/opt_misc.go, pkg/sql/plan/query_builder.go
issue https://github.com/matrixorigin/MO-Cloud/issues/5330
to avoid hung on DML query
=> force SINK_SCAN to run on single CN

pkg/objectio/mergeutil/tyeps_test.go, pkg/objectio/mergeutil/types.go, pkg/vm/engine/disttae/logtail_consumer_test.go, pkg/vm/engine/disttae/transfer.go, pkg/vm/engine/disttae/txn.go
issue #https://github.com/matrixorigin/matrixone/issues/21887 https://github.com/matrixorigin/matrixone/issues/21908
Fix the duplicate entry in the CDC test.
=> fix the duplicate entry in the CDC test.

pkg/vm/engine/tae/db/gc/v3/merge.go
issue https://github.com/matrixorigin/MO-Cloud/issues/5490
Fix version bug of cpt file 2.2
=> Fix version bug of cpt file 2.2

pkg/vm/engine/tae/db/gc/v3/merge.go
issue https://github.com/matrixorigin/MO-Cloud/issues/5490
Fix version bug of cpt file
=> Fix version bug of cpt file main

pkg/vm/engine/tae/db/gc/v3/merge.go
issue https://github.com/matrixorigin/MO-Cloud/issues/5490
Fix version bug of cpt file
=> Fix version bug of cpt file

pkg/vm/engine/disttae/transfer.go, pkg/vm/engine/disttae/transfer_util.go, pkg/vm/engine/disttae/txn.go, pkg/vm/engine/disttae/txn_table.go
issue #https://github.com/matrixorigin/matrixone/issues/21887
fix tombstone object missing after the CN transfer
=> to 2.2: fix tombstone object missing after the CN transfer

pkg/vm/engine/disttae/transfer.go, pkg/vm/engine/disttae/transfer_util.go, pkg/vm/engine/disttae/txn.go, pkg/vm/engine/disttae/txn_table.go
issue #https://github.com/matrixorigin/matrixone/issues/21887
Fix tombstone objects missing after the CN transfer
=> fix tombstone objects missing after the CN transfer

pkg/vm/engine/tae/db/merge/scheduler.go, pkg/vm/engine/tae/db/merge/scheduler_test.go, pkg/vm/engine/tae/rpc/inspectMerge.go
issue https://github.com/matrixorigin/matrixone/issues/6955
https://github.com/matrixorigin/matrixone/issues/21933
- Tweak the trigger mechanism of the tombstone vacuum check
- Add a backup policy for the tombstone vacuum check
=> fix tombstone vacuum check

optools/images/Dockerfile, optools/images/README.md
issue https://github.com/matrixorigin/MO-Cloud/issues/5495
Sometimes, the network between the runner and the apt software repository is very poor, which will cause packaging failure. We need to package all dependent software into the base image.
=> CI: modify dockerfile

pkg/lockservice/lock_table_allocator.go, pkg/lockservice/lock_table_allocator_test.go, pkg/lockservice/lock_table_keeper.go, pkg/lockservice/service.go, pkg/lockservice/service_test.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/5543 #21907 
fix txn unlock fatal
=> fix txn unlock fatal

pkg/partitionservice/service.go, pkg/sql/plan/build_show_util.go, pkg/tests/partition/create_hash_test.go
issue #16471 
show create partition table
=> show create partition table

pkg/vm/engine/tae/rpc/handle.go
issue https://github.com/matrixorigin/MO-Cloud/issues/5805
- Add a defer function to ensure the txn is rollbacked when an error occurs
=> fix error checking in rpc handler

pkg/container/vector/search.go, pkg/vm/engine/readutil/filter_test.go, pkg/vm/engine/readutil/pk_filter.go, pkg/vm/engine/readutil/pk_filter_mem.go, pkg/vm/engine/readutil/pk_filter_mem_test.go
issue #https://github.com/matrixorigin/matrixone/issues/21923
fix transfer tombstone failed when drop pitr bvt.
=> fix transfer tombstone failed when drop pitr bvt.

pkg/vm/engine/tae/db/gc/v3/checkpoint.go
issue https://github.com/matrixorigin/matrixone/issues/22131
Fix replay mpool leak
=> Fix replay mpool leak

pkg/taskservice/mysql_task_storage.go, pkg/taskservice/mysql_task_storage_test.go, pkg/taskservice/task_service_holder_test.go
issue #21848 
return err when commit fail
=> fix add cdc task

pkg/cdc/sinker_test.go, pkg/cdc/util.go, pkg/common/moerr/error.go, pkg/common/moerr/error_no_ctx.go, pkg/frontend/cdc_test.go
issue #22203 https://github.com/matrixorigin/MO-Cloud/issues/5954
Fix cdc json 2.2
=> Fix cdc json 2.2

go.mod, go.sum, pkg/sql/colexec/external/external_test.go
colexec/external: log file system events in TestReadDirSymlink
issue #22009
Log for potential unexpected file deletion during the test.
=> colexec/external: log file system events in TestReadDirSymlink

pkg/vm/engine/tae/db/gc/v3/cleaner_test.go, pkg/vm/engine/tae/db/gc/v3/diskcleaner.go
issue https://github.com/matrixorigin/matrixone/issues/21982
Remove try gc during replay
=> Remove try gc during replay

pkg/cdc/reader.go
issue https://github.com/matrixorigin/matrixone/issues/22211
cdc sync will do once immediately no matter of the frequency
=> for 2.2: cdc sync timing

pkg/tnservice/cfg.go, pkg/tnservice/factory.go, pkg/vm/engine/tae/db/cronjobs.go, pkg/vm/engine/tae/db/test/db_test.go, pkg/vm/engine/tae/options/cfg.go, pkg/vm/engine/tae/options/options.go, pkg/vm/engine/tae/options/types.go, pkg/vm/engine/tae/testutils/config/options.go
issue https://github.com/matrixorigin/matrixone/issues/20436
Add GCInMemoryTTL config for GC Catalog
=> Add GCInMemoryTTL config for GC Catalog

pkg/vm/engine/tae/options/options.go, pkg/vm/engine/tae/options/types.go
issue https://github.com/matrixorigin/matrixone/issues/21980
Add DefaultGlobalVersionInterval config
=> Add DefaultGlobalVersionInterval config

pkg/tests/issues/issue_test.go
issue #https://github.com/matrixorigin/matrixone/issues/20659
adding more err msg for UT `TestIssue19551`
=> adding more err msg for UT `TestIssue19551`

pkg/vm/engine/tae/db/checkpoint/executor.go, pkg/vm/engine/tae/db/test/db_test.go
issue #22256 
fix Test_CheckpointChaos3
=> fix Test_CheckpointChaos3

pkg/sql/parsers/dialect/mysql/mysql_sql_test.go, pkg/sql/parsers/tree/types.go
issue #16471 
fix string bigint(20) unsigned
=> fix string bigint(20) unsigned

pkg/sql/plan/function/list_builtIn.go, pkg/sql/plan/utils.go, test/distributed/cases/fulltext/fulltext.result, test/distributed/cases/fulltext/fulltext.sql
issue #https://github.com/matrixorigin/MO-Cloud/issues/6023
fix union all select fulltext
=> fix union all select fulltext

cmd/mo-service/debug_test.go, pkg/fileservice/file_service_test.go, pkg/fileservice/local_etl_fs.go, pkg/fileservice/local_fs.go, pkg/fileservice/memory_fs.go, pkg/fileservice/reader_writer_file_service.go
issue #3433
add fileservice NewWriter/NewReader for streaming file operations.
=> fileservice: add FileService.NewReader/NewWriter

pkg/container/batch/batch.go, pkg/objectio/bitmap.go, pkg/objectio/ioutil/sinker.go, pkg/objectio/ioutil/sinker_test.go, pkg/objectio/mergeutil/types.go, pkg/sql/colexec/deletion/types.go, pkg/sql/colexec/insert/insert.go, pkg/sql/colexec/insert/types.go, pkg/sql/colexec/multi_update/s3writer_delegate.go, pkg/sql/colexec/s3util.go, pkg/sql/colexec/s3util_test.go, pkg/vm/engine/disttae/local_disttae_datasource_test.go, pkg/vm/engine/disttae/table_meta_reader.go, pkg/vm/engine/disttae/transfer_util.go, pkg/vm/engine/disttae/txn.go, pkg/vm/engine/disttae/txn_table.go, pkg/vm/engine/readutil/datasource_test.go, pkg/vm/engine/readutil/tombstone_data_test.go, pkg/vm/engine/tae/containers/utils.go, pkg/vm/engine/tae/containers/utils_test.go, pkg/vm/engine/tae/db/gc/v3/exec_v1.go, pkg/vm/engine/tae/db/gc/v3/util.go, pkg/vm/engine/tae/db/gc/v3/window_test.go, pkg/vm/engine/test/reader_test.go, pkg/vm/engine/test/workspace_test.go
issue #22280 
Optimize s3writer
=> Optimize s3writer

test/distributed/cases/dml/select/select.result, test/distributed/cases/dml/select/select.test
issue #18667 
add bvt cases
___
Tests
___
- Add test cases for bigint unsigned arithmetic operations
- Test edge cases with maximum bigint unsigned values
- Verify WHERE clause behavior with arithmetic expressions
___
```mermaid
flowchart LR
A["Test File"] --> B["Add bigint unsigned table"]
B --> C["Insert max values"]
C --> D["Test arithmetic WHERE clauses"]
```
<tr>
<td>
<details>
<summary><strong>select.test</strong><dd><code>Add bigint unsigned arithmetic test cases</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> add cases issue 18667

pkg/sql/plan/build_show_util.go, pkg/tests/partition/create_hash_test.go
issue #16471 
fix show linear partition
___
Bug fix
___
- Add support for linear hash and linear key partition methods in SHOW CREATE TABLE
- Fix missing partition method display for linear partitioning types
- Add test case for linear hash partition table creation
___
```mermaid
flowchart LR
A["ConstructCreateTableSQL"] --> B["Add LinearHash case"]
A --> C["Add LinearKey case"]
B --> D["Display 'linear hash'"]
C --> E["Display 'linear key'"]
F["Test Suite"] --> G["Add linear hash test case"]
```
<tr>
<td>
<details>
<summary><strong>build_show_util.go</strong><dd><code>Add linear partition method …
=> fix show linear partition

pkg/frontend/clone.go, pkg/frontend/pitr.go, pkg/frontend/snapshot.go, pkg/sql/parsers/tree/clone.go, pkg/sql/plan/build_table_clone.go, test/distributed/cases/snapshot/clone/clone_privilege.result, test/distributed/cases/snapshot/clone/clone_privilege.sql
issue #https://github.com/matrixorigin/matrixone/issues/22301
```
1. 普通租户不能 clone 任一系统 db/table
如 mo_task, mo_catalog, system, mysql, system_mertric, information_schema, mo_debug
这个操作等同于在系统 db 下面创建表，为了和 create table 权限保持一致
2. sys租户和普通租户都不能 clone 数据到系统 db
不能将其他 table clone 到 系统 db 下
3. 普通租户不能 clone cluster table
cluster table 会聚合很多租户的数据，普通租户可以用 select 查看属于自己的数据。
如果允许 clone，那么 clone 就需要过滤 table 的数据，无法优化，与 select 功能无异。(rawlog, statement_info...)
4. 普通租户可以 clone 已经订阅的 db/table
==> 只有 sys 租户才能
1. clone 系统表
sys 租户和普通租户都不能
1. clone 数据到系统 db 下面
```
___
Enhancement
___
- Add privilege restrictions for clone operations on system databases
- Prevent non-sys accounts from cloning system databases/tables
- Block all accounts from cloning data into system databases
- Add comprehensive test coverage for …
=> some simple restrictions on clone privilege.

go.mod, go.sum, pkg/container/types/array.go, pkg/container/types/array_str_test.go, pkg/container/types/array_test.go, pkg/monlp/llm/llm.go, pkg/monlp/llm/mockllm.go, pkg/monlp/llm/mockllm_test.go, pkg/monlp/llm/ollama.go, pkg/monlp/llm/ollama_test.go, pkg/sql/colexec/table_function/parsejsonl.go, pkg/sql/plan/function/func_builtin_llm.go, pkg/sql/plan/function/function_id.go, pkg/sql/plan/function/function_id_test.go, pkg/sql/plan/function/list_builtIn.go, test/distributed/cases/function/func_llm.result, test/distributed/cases/function/func_llm.sql
issue #22299
Add llm_chat and llm_embedding as function so that it can be called in sql, outside of stored procedure.
___
Enhancement
___
- Add `llm_chat` and `llm_embedding` SQL functions
- Implement embedding support in LLM clients
- Fix generic type inference in array utilities
- Fix column mapping in JSON parsing
___
```mermaid
flowchart LR
A["SQL Functions"] --> B["LLM Client Interface"]
B --> C["Mock Client"]
B --> D["Ollama Client"]
C --> E["CreateEmbedding"]
D --> E
F["Array Utils"] --> G["Type Inference Fix"]
H["JSON Parser"] --> I["Column Mapping Fix"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>6 files</summary><table> …
=> Add llm_chat and llm_embedding function.

pkg/sql/colexec/fuzzyfilter/filter.go, pkg/vm/engine/disttae/txn_table.go, pkg/vm/engine/tae/db/merge/scheduler.go, test/distributed/cases/dml/replace/replace.result, test/distributed/cases/dml/replace/replace.test
issue #22340 
fix fuzzy filter
___
Bug fix
___
- Fix error handling in fuzzy filter runtime operations
- Replace deprecated `UnionMulti` with `UnionBatch` method
- Improve logging format consistency in merge scheduler
- Add test case for vector index replace operations
___
```mermaid
flowchart LR
A["FuzzyFilter.Call()"] --> B["appendPassToRuntimeFilter()"]
B --> C["Error Handling Added"]
D["UnionMulti()"] --> E["UnionBatch()"]
F["Logging Messages"] --> G["Consistent Format"]
H["Test Cases"] --> I["Vector Index Replace"]
```
<tr>
<td>
<details>
<summary><strong>filter.go</strong><dd><code>Fix error …
=> Fix fuzzyfilter 3.0

pkg/frontend/cdc_exector.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/6173
fix context deadline not set
___
Bug fix
___
- Add context timeout to prevent indefinite blocking
- Set 5-minute deadline for CDC table handling operations
___
```mermaid
flowchart LR
A["Context Creation"] --> B["Add 5min Timeout"] --> C["CDC Operations"]
```
<tr>
<td>
<details>
<summary><strong>cdc_exector.go</strong><dd><code>Add context timeout for CDC operations</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> fix context deadline not set

pkg/cdc/table_scanner.go, pkg/cdc/table_scanner_test.go, pkg/frontend/cdc_exector.go, pkg/objectio/injects.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/6142
fix cdc scanner
___
Bug fix
___
- Fix CDC table scanner timing and concurrency issues
- Add context timeout to prevent hanging operations
- Improve test coverage with injection mechanisms
- Add configurable scan intervals for testing
___
```mermaid
flowchart LR
A["CDC Scanner"] --> B["Configurable Timing"]
A --> C["Context Timeout"]
B --> D["Fast/Normal Intervals"]
C --> E["5 minute timeout"]
A --> F["Concurrency Fix"]
F --> G["Async callback execution"]
```
<tr>
<td>
<details>
<summary><strong>table_scanner.go</strong><dd><code>Fix scanner …
=> fix cdc scanner

pkg/sql/compile/analyze_module.go, pkg/sql/models/phy_plan.go, pkg/vm/process/operator_analyzer.go
issue #22286
display stats for each operator in EXPLAIN PHYPLAN ANALYZE
___
Enhancement
___
- Improve operator statistics tracking in EXPLAIN PHYPLAN ANALYZE
- Add IsFirst/IsLast flags to PhyOperator model
- Refine input/output row and size aggregation logic
- Remove conditional checks in operator analyzer methods
___
```mermaid
flowchart LR
A["Operator Analyzer"] --> B["PhyOperator Model"]
B --> C["Statistics Aggregation"]
C --> D["EXPLAIN PHYPLAN Output"]
B -- "IsFirst/IsLast flags" --> C
```
<tr>
<td>
<details>
<summary><strong>analyze_module.go</strong><dd><code>Refine statistics aggregation with …
=> display stats for each operator in EXPLAIN PHYPLAN ANALYZE

pkg/sql/colexec/mergetop/top.go, pkg/sql/colexec/top/top.go
issue https://github.com/matrixorigin/matrixone/issues/22374
- Replace UnionOne with UnionBatch to improve performance
- Allocate off-heap memory for a large limit value (over 10000)
=> optimize top operator's batch processing 3.0

test/distributed/cases/snapshot/clone/clone.result, test/distributed/cases/snapshot/clone/clone.sql
fix bvt
issue #https://github.com/matrixorigin/matrixone/issues/22398
fix bvt
=> fix clone bvt

pkg/sql/colexec/mergetop/top.go, pkg/sql/colexec/top/top.go
issue https://github.com/matrixorigin/matrixone/issues/22374
- Replace UnionOne with UnionBatch to improve performance
- Allocate off-heap memory for a large limit value (over 10000)
=> optimize top operator's batch processing

pkg/fulltext/fixedbytepool.go, pkg/objectio/injects.go, pkg/sql/colexec/anti/join.go, pkg/vm/engine/disttae/logtail_consumer.go, pkg/vm/engine/disttae/txn_table.go, test/distributed/cases/snapshot/clone/table_clone.result, test/distributed/cases/snapshot/clone/table_clone.sql
issue https://github.com/matrixorigin/matrixone/issues/22400
Report an error when the subscription table fails.
=> to 3.0: report the error when the subscription table fails.

pkg/vm/engine/disttae/logtail_consumer.go, pkg/vm/engine/disttae/txn_table.go
issue #https://github.com/matrixorigin/matrixone/issues/22409
Try snapshot read if the subscription does not exist.
=> Try snapshot read if the subscription does not exist.

pkg/vm/engine/disttae/logtail_consumer.go, pkg/vm/engine/disttae/txn_table.go
issue #https://github.com/matrixorigin/matrixone/issues/22409
Try snapshot read if the subscription does not exist.
=> to 3.0: Try snapshot read if the subscription does not exist.

pkg/cnservice/server.go, pkg/cnservice/server_task.go, pkg/config/configuration.go, pkg/frontend/back_exec.go, pkg/frontend/cdc_dao.go, pkg/frontend/cdc_handle.go, pkg/frontend/connector.go, pkg/frontend/connector_test.go, pkg/frontend/session.go, pkg/frontend/show_account.go, pkg/frontend/task.go, pkg/frontend/task_test.go
issue #22440 
fix data race for taskservice
=> fix data race for taskservice

pkg/vm/engine/disttae/txn.go, pkg/vm/engine/disttae/txn_test.go, pkg/vm/engine/disttae/types.go
issue #22452 
fix OLTP performance degradation
=> fix oltp performance degradation

pkg/sql/plan/build_dml_util.go
issue https://github.com/matrixorigin/MO-Cloud/issues/6325
genNewTag -> genNewMsgTag
___
Bug fix
___
- Fix runtime filter message tag generation method call
___
```mermaid
flowchart LR
A["genNewTag()"] -- "replaced with" --> B["genNewMsgTag()"]
```
<tr>
<td>
<details>
<summary><strong>build_dml_util.go</strong><dd><code>Fix runtime filter tag method call</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pkg/sql/plan/build_dml_util.go
<ul><li>Replace …
=> fix runtime filter message tag

pkg/iscp/iteration.go, pkg/iscp/watermark_updater.go, pkg/vm/engine/test/change_handle_test.go
issue #22525
add RenameSrcTable
rm pitr
___
Enhancement
___
- Remove `pitr_name` parameter from ISCP job registration functions
- Add `RenameSrcTable` function for updating table names in ISCP jobs
- Update all test cases to use simplified job registration API
- Implement table renaming functionality with job spec updates
___
```mermaid
flowchart LR
A["RegisterJob API"] -- "remove pitr_name param" --> B["Simplified Registration"]
C["RenameSrcTable Function"] -- "updates job specs" --> D["Table Name Changes"]
E["Test Cases"] -- "updated calls" --> B
C -- "queries mo_iscp_log" --> F["Job Spec Updates"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><tab …
=> iscp update table name

pkg/vectorindex/hnsw/search.go, pkg/vectorindex/ivfflat/search.go
issue https://github.com/matrixorigin/MO-Cloud/issues/6365
change the L2sq distance score to L2 distance score only when Limit N result
___
Bug fix
___
- Convert L2 squared distance to L2 distance in search results
- Apply square root transformation for L2sq and L2Distance metrics
- Fix distance calculation in HNSW and IVFFlat vector indexes
___
```mermaid
flowchart LR
A["Search Results"] --> B["Check Metric Type"]
B --> C["L2sq/L2Distance?"]
C -->|Yes| D["Apply sqrt()"]
C -->|No| E["Keep Original Distance"]
D --> F["Return L2 Distance"]
E --> F
```
<tr>
<td>
<details> …
=> change result score from l2sq to l2

pkg/cdc/sinker.go, pkg/cdc/sinker_test.go, pkg/sql/plan/build_show_util.go
issue #22207
build create sql with table define
___
Bug fix
___
- Fix CDC create table SQL generation using table definition
- Replace string manipulation with proper SQL construction
- Handle cluster table validation and context checks
- Update import path from pb/plan to sql/plan
___
```mermaid
flowchart LR
A["String manipulation"] --> B["Table definition"]
B --> C["ConstructCreateTableSQL"]
C --> D["Proper SQL generation"]
E["pb/plan import"] --> F["sql/plan import"]
```
<tr>
<td>
<details>
<summary><strong>sinker.go</strong><dd><code>Replace string manipulation with table definition SQL …
=> update create sql

pkg/vectorindex/hnsw/search.go, pkg/vectorindex/ivfflat/search.go
issue https://github.com/matrixorigin/MO-Cloud/issues/6365
2.2 dev convert l2sq score tp l2 score for hnsw and ivfflat index
___
Bug fix
___
- Convert L2 squared distance to L2 distance in vector search results
- Apply square root transformation for HNSW and IVFFlat indexes
- Fix distance calculation for L2 metric type
___
```mermaid
flowchart LR
A["Search Results"] --> B["Check Metric Type"]
B --> C["L2sq/L2Distance?"]
C -->|Yes| D["Apply sqrt()"]
C -->|No| E["Keep Original Distance"]
D --> F["Return Corrected Distance"]
E --> F
```
<tr>
<td>
<details>
<summary><strong>search.go</strong><dd><code>Add L2 …
=> 2.2 dev convert l2sq score tp l2 score for hnsw and ivfflat index
