matrixorigin/matrixone

- pkg/container/vector/vector.go
- pkg/sql/compile2/compile.go
- pkg/sql/compile2/compile_test.go
- pkg/sql/compile2/operator.go
- pkg/vm/engine/memEngine/engine.go
- pkg/vm/engine/memEngine/kv/kv.go
- pkg/vm/engine/memEngine/kv/types.go
- pkg/vm/engine/memEngine/relation.go
- pkg/vm/engine/memEngine/types.go
issue #
Not Available
Not Available
Not Available
> Add non-equi join compile

- pkg/frontend/mysql_cmd_executor.go
- pkg/frontend/session.go
issue #2653
Not Available
Not Available
Not Available
> support show create table in plan2 and tae

- pkg/vm/process/process.go
issue #
Not Available
Not Available
Not Available
> Fix the size of vector's data

- pkg/sql/parsers/tree/expr.go
issue #3134 
Not Available
Not Available
Not Available
> fix bug #3134: result column name is inaccurate

- pkg/util/metric/batch_collector.go
- pkg/util/metric/dashboard/grafana8.4_mo_overview.json
- pkg/util/metric/m_hardware.go
- pkg/util/metric/m_hardware_test.go
- pkg/util/metric/m_process.go
- pkg/util/metric/m_process_test.go
- pkg/util/metric/m_register.go
- pkg/util/metric/metric.go
- pkg/util/metric/metric_test.go
issue #
1. rewrite processCollector using gopsutil package, support more metrics on macOS and remove some unused tables
2. refactor batchCollector to reduce redundant codes
3. init metric tables via describe instead of metricFamily, this approach is more efficient
4. update sql in Grafana, avoid query error
Not Available
Not Available
> refactor metric process collector and update dashboard

- pkg/vm/engine/tae/dataio/segmentio/bitmap_allocator.go
- pkg/vm/engine/tae/dataio/segmentio/driver.go
- pkg/vm/engine/tae/dataio/segmentio/driver_test.go
- pkg/vm/engine/tae/txn/txnimpl/sysblock.go
issue #
Not Available
Not Available
Not Available
> Fix bitmap bug

- pkg/vm/engine/tae/catalog/mock.go
- pkg/vm/engine/tae/catalog/schema.go
- pkg/vm/engine/tae/db/base_test.go
- pkg/vm/engine/tae/db/db_test.go
- pkg/vm/engine/tae/iface/handle/database.go
- pkg/vm/engine/tae/txn/txnimpl/database.go
- pkg/vm/engine/tae/txn/txnimpl/sysdb.go
issue #3152 
Not Available
Not Available
Not Available
> (tae): implement a simple table truncate solution 

- pkg/sql/colexec2/expr_eval.go
- pkg/vm/pipeline2/pipeline.go
issue #
Not Available
Not Available
Not Available
> Fix the bug of expr eval

- pkg/sql/plan2/query_builder.go
issue #3081 
Not Available
Not Available
Not Available
> fix 3081: col_pos is inaccurate in SEMI Join Node

- pkg/vm/engine/tae/dataio/segmentio/block.go
issue #
Not Available
Not Available
Not Available
> Fix the bug of segmentio loadupdates

- pkg/sql/plan2/base_binder.go
- pkg/sql/plan2/explain/explain_node.go
- pkg/sql/plan2/query_builder.go
- pkg/sql/plan2/utils.go
issue #2372
Not Available
Not Available
Not Available
> [Plan2] Apply distributive law to disjunctions

- pkg/sql/plan2/function/operator/eq.go
- pkg/sql/plan2/function/operator/ge.go
- pkg/sql/plan2/function/operator/gt.go
- pkg/sql/plan2/function/operator/le.go
- pkg/sql/plan2/function/operator/lt.go
- pkg/sql/plan2/function/operator/ne.go
issue #3164 
Not Available
Not Available
Not Available
> fix col compare with null bug in where expression

- pkg/container/ring/min/str.go
- pkg/sql/colexec2/aggregate/aggregate.go
issue #3193 
Not Available
Not Available
Not Available
> fix a bug in min(varchar)

- pkg/vm/engine/tae/db/replay.go
- pkg/vm/engine/tae/logstore/entry/base.go
- pkg/vm/engine/tae/logstore/store/replayer.go
- pkg/vm/engine/tae/logstore/store/store.go
- pkg/vm/engine/tae/logstore/store/store_test.go
- pkg/vm/engine/tae/logstore/store/vinfo.go
- pkg/vm/engine/tae/txn/txnimpl/node.go
- pkg/vm/engine/tae/wal/driver.go
issue #
Not Available
Not Available
Not Available
> free logstore entries

- pkg/sql/plan2/function/operator/cast.go
- pkg/vectorize/typecast/typecast.go
Signed-off-by: wuqinxuan <wuqinxuan33@gmail.com>
issue #
add precision for cast timestamp as varchar
Not Available
Not Available
> add precision arg for cast ts as varchar

- pkg/container/ring/anyvalue/anyvalue.go
- pkg/container/ring/avg/decimal.go
- pkg/container/ring/max/decimal128.go
- pkg/container/ring/max/decimal64.go
- pkg/container/ring/min/decimal128.go
- pkg/container/ring/min/decimal64.go
- pkg/container/ring/sum/decimal128.go
- pkg/container/ring/sum/decimal64.go
- pkg/container/vector/vector.go
- pkg/sql/colexec2/expr_eval.go
- pkg/sql/compile2/operator.go
issue #3214 
and new bug in #3195 
Not Available
thanks @nnsgmsone 
Not Available
> Fix the bug of expr eval in null

- pkg/sql/plan2/base_binder.go
- pkg/sql/plan2/bind_context.go
- pkg/sql/plan2/flatten_subquery.go
- pkg/sql/plan2/optimize.go
- pkg/sql/plan2/projection_binder.go
- pkg/sql/plan2/query_builder.go
- pkg/sql/plan2/types.go
- pkg/sql/plan2/utils.go
issue #
Not Available
Not Available
Not Available
> [Plan2] Modify error messages

- pkg/sql/colexec2/complement/complement.go
- pkg/sql/colexec2/join/join.go
- pkg/sql/colexec2/left/join.go
- pkg/sql/colexec2/semi/join.go
- pkg/sql/plan2/query_builder.go
issue #3215 
Not Available
Not Available
Not Available
> rewrite right join to left join

- pkg/sql/plan2/function/function.go
issue #
Not Available
Not Available
Not Available
> remove a wrong type-convert-rule

- pkg/sql/plan2/function/operator/isnotnull.go
- pkg/sql/plan2/function/operator/isnull.go
Signed-off-by: wuqinxuan <wuqinxuan33@gmail.com>
issue #
improve isnull/isnotnull scalar
Not Available
Not Available
> improve isnull/isnotnull scalar

- pkg/sql/plan2/tpch/q7.sql
issue #
The first query of q7 is actually the duplicate of q6.
Not Available
Not Available
> Remove duplicate tpch q6

- pkg/frontend/load.go
- pkg/frontend/mysql_cmd_executor.go
issue #3216 
Not Available
Not Available
Not Available
> Fix load auto commit #3216

- pkg/sql/plan2/base_binder.go
- pkg/sql/plan2/bind_context.go
- pkg/sql/plan2/build_test.go
- pkg/sql/plan2/query_builder.go
- pkg/sql/plan2/utils.go
Fixes issue #3176
Not Available
Not Available
Not Available
> [Plan2] Make binder more robust

- pkg/sql/plan2/function/operator/gt.go
issue #3164 
Not Available
Not Available
Not Available
> delete println sentence

- pkg/frontend/mysql_cmd_executor.go
issue #3299 
Not Available
in mysql_cmd_executor.go:
It will execute sql like "select 1 from tbl" directly and then return response to client。without buildPlan。
I remove that code.
Not Available
> Fix bug 3299: remove unnecessary if branch

- pkg/container/vector/vector.go
- pkg/sql/colexec2/left/join.go
- pkg/sql/colexec2/loopleft/join.go
- pkg/sql/colexec2/loopleft/types.go
issue #3305
Not Available
Not Available
Not Available
> Fix the bug of outer join

- pkg/sql/plan2/query_builder.go
- pkg/sql/plan2/utils.go
issue #3305
Not Available
Not Available
Not Available
> [Plan2] Pushdown filter to right side of LEFT join only if it rejects null

- pkg/sql/plan2/function/operator/unaryops.go
- pkg/sql/plan2/function/operator/unaryops_test.go
- pkg/sql/plan2/function/operators.go
- pkg/sql/testutil/testutil.go
- pkg/vectorize/neg/neg.go
- pkg/vectorize/neg/neg_test.go
issue #
Not Available
Not Available
Not Available
> add unaryMinus for decimal type

- test/cases/expression/cte.sql
- test/result/expression/cte.result
issue #3299 
Not Available
Not Available
Not Available
> fix 3299. change case result

- test/cases/function/func_datetime_utc_timestamp.test
- test/cases/function/func_string_reverse.test
- test/cases/function/func_string_rtrim_ltrim.test
- test/result/function/func_string_reverse.result
- test/result/function/func_string_rtrim_ltrim.result
issue #3187 #3329
Not Available
Not Available
Not Available
> Add #3329 and #3187 test cases

- test/cases/function/func_cast.test
- test/result/function/func_cast.result
issue #3363 
Not Available
when use new test case. we get  actual result:
Operator '<' with parameters [VARCHAR DATETIME] will be implemented in future version.
just like #3254 
Not Available
> fix 3363.  change test case and reset issue number

- pkg/sql/plan2/build_util.go
- test/cases/dml/show/show.test
issue #3350 
Not Available
Not Available
Not Available
> fix 3350; get plan.type(char) from mysql type is not correct

- .github/ISSUE_TEMPLATE/10_bug_report.yml
- .github/ISSUE_TEMPLATE/documentation.yml
- .github/ISSUE_TEMPLATE/enhancement.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/general_question.yml
- .github/ISSUE_TEMPLATE/performance_question.yml
- .github/ISSUE_TEMPLATE/refactoring_request.yml
issue #
issue template modify
Not Available
Not Available
> issue template modify

- test/cases/operator/is_operator.sql
issue #3305
Not Available
Not Available
Not Available
> Untag #3305

- test/cases/function/func_datetime_date_add.test
issue #3176
Not Available
The error message becomes `Operator '-' with parameters [DATETIME DATETIME] will be implemented in future version.` after applying #3205. I assume it's now belong to #3291.
Not Available
> Retag #3176

- pkg/sql/plan2/function/builtin/unary/acos.go
- pkg/sql/plan2/function/builtin/unary/acos_test.go
- pkg/sql/plan2/function/builtin/unary/atan.go
- pkg/sql/plan2/function/builtin/unary/atan_test.go
- pkg/sql/plan2/function/builtin/unary/cos.go
- pkg/sql/plan2/function/builtin/unary/cos_test.go
- pkg/sql/plan2/function/builtin/unary/cot.go
- pkg/sql/plan2/function/builtin/unary/cot_test.go
- pkg/sql/plan2/function/builtin/unary/exp.go
- pkg/sql/plan2/function/builtin/unary/exp_test.go
- pkg/sql/plan2/function/builtin/unary/ln.go
- pkg/sql/plan2/function/builtin/unary/ln_test.go
- pkg/sql/plan2/function/builtin/unary/log.go
- pkg/sql/plan2/function/builtin/unary/log_test.go
- pkg/sql/plan2/function/builtin/unary/sin.go
- pkg/sql/plan2/function/builtin/unary/sin_test.go
- pkg/sql/plan2/function/builtin/unary/sinh_test.go
- pkg/sql/plan2/function/builtin/unary/space.go
- pkg/sql/plan2/function/builtin/unary/tan_test.go
- pkg/vectorize/cot/cot.go
- pkg/vectorize/cot/cot_test.go
- test/cases/function/builtin.sql
- test/cases/function/func_math.sql
- test/cases/function/func_math_trig.test
- test/result/function/builtin.result
- test/result/function/func_math.result
- test/result/function/func_math_trig.result
We have a very strange cot.
Fix warnings.
issue #3133
Bug Fix
Not Available
Not Available
> Fix cot, bvt issue 3133.

- pkg/container/types/datetime.go
- pkg/container/types/decimal.go
- pkg/sql/parsers/tree/expr.go
- pkg/sql/plan2/base_binder.go
- test/cases/function/func_string_rtrim_ltrim.test
- test/cases/function/func_substr.sql
- test/result/function/func_string_rtrim_ltrim.result
- test/result/function/func_substr.result
issue #3248 #3243 
Not Available
Not Available
Not Available
> fix #3248: throw the error which not support the & operator

- pkg/sql/plan2/query_builder.go
issue #3324
Not Available
Not Available
Not Available
> Don't pushdown SEMI/ANTI join conditions to right side

- pkg/sql/colexec2/loopjoin/join.go
- pkg/sql/colexec2/loopleft/join.go
- pkg/sql/compile2/operator.go
- pkg/sql/plan2/query_builder.go
issue #3324
Not Available
Not Available
Not Available
> Fix the bug of compile join

- test/cases/expression/cte.sql
- test/result/expression/cte.result
issue #3302
Not Available
Not Available
Not Available
> fix the result for issue#3302

- pkg/vm/engine/tae/moengine/relation.go
- pkg/vm/engine/tae/moengine/utils.go
issue #
Not Available
Not Available
Not Available
> Fix util MOToVectorTmp

- pkg/builtin/multi/rpad.go
- pkg/sql/plan2/function/builtin/multi/lpad.go
- pkg/sql/plan2/function/builtin/multi/lpad_test.go
- pkg/sql/plan2/function/builtin/multi/rpad.go
- pkg/vectorize/rpad/rpad.go
- pkg/vectorize/rpad/rpad_test.go
- test/cases/dtype/char.test
- test/cases/dtype/varchar.test
- test/cases/function/func_string_lpad_rpad.test
issue #3372
issue #3255
issue #3157
Not Available
Not Available
Not Available
> fix cases of concat_ws, lpad and rpad

- pkg/vm/engine/tae/dataio/segmentio/bitmap_allocator.go
- pkg/vm/engine/tae/dataio/segmentio/driver_test.go
issue #3519 
Not Available
Not Available
Not Available
> Fix the bug of tae driver allocator

- pkg/sql/plan2/build_update.go
- pkg/sql/plan2/make.go
issue #3491 
Not Available
Not Available
Not Available
> null in vector should be col's type instead of Type_any

- pkg/sql/plan2/function/operator/eq.go
- pkg/sql/plan2/function/operators.go
issue #2565 
Not Available
Not Available
Not Available
> add equal function for decimal128

- pkg/sql/plan2/query_builder.go
issue #3262
Not Available
Not Available
Not Available
> [Opt] Don't pushdown SEMI/ANTI join with non-equi condition

- pkg/sql/colexec2/complement/complement.go
- pkg/sql/colexec2/complement/types.go
…ting that the semantics of anti is no longer the same as the marked up anti.
issue #3320
Not Available
Not Available
Not Available
> Modify the semantics of anti to handle null to support subqueries

- test/cases/function/func_if.test
issue #3391 
Not Available
Not Available
Not Available
> fix issue about if func

- pkg/vm/engine/tae/moengine/database.go
- pkg/vm/engine/tae/moengine/engine_test.go
- pkg/vm/engine/tae/moengine/relation.go
- pkg/vm/engine/tae/moengine/sys_relation.go
- pkg/vm/engine/tae/moengine/txn_relation.go
- pkg/vm/engine/tae/moengine/types.go
issue #3543 
Not Available
Not Available
Not Available
> Add system relation in moengine

- pkg/common/morpc/backend.go
- pkg/common/morpc/backend_test.go
- pkg/common/morpc/client.go
- pkg/common/morpc/server.go
- pkg/common/morpc/server_test.go
issue #
Not Available
Not Available
Not Available
> morpc: fix data race

- pkg/common/morpc/server.go
- pkg/common/morpc/server_test.go
issue #
Not Available
Not Available
Not Available
> morpc: fix server BatchSendSize option not work

- pkg/common/morpc/backend.go
- pkg/common/morpc/client.go
- pkg/common/morpc/server.go
- pkg/common/stopper/stopper.go
- pkg/common/stopper/stopper_test.go
issue #
Not Available
Not Available
Not Available
> Rename stopper package name

- pkg/common/morpc/backend_test.go
issue #
Not Available
Not Available
Not Available
> morpc: fix TestSendWithAlreadyContextDone

- pkg/frontend/load.go
issue #3592 
Not Available
Not Available
Not Available
> delete println debug sentence

- pkg/sql/plan2/function/operator/cast.go
- test/cases/function/func_datetime_utc_timestamp.test
issue #3590 
Not Available
Not Available
Not Available
> fix issue about timestamp

- pkg/container/types/date.go
- pkg/sql/plan2/base_binder.go
- pkg/sql/plan2/function/builtin/unary/date.go
- pkg/sql/plan2/function/buitins.go
- pkg/vectorize/date/date.go
issue #3143 
Not Available
Not Available
Not Available
> support DATE can get datetime format string as arg

- .github/mergify.yml
Auto update the PR once other PR is merged.
Not Available
Not Available
> auto merge policy for mergify

- go.mod
- go.sum
issue #
Bumped dragonboat version to resolve the missing peer address issue. 
Not Available
Not Available
> deps: bumped dragonboat version

- .github/mergify.yml
Disable auto update of mergify
Not Available
Not Available
> remove:auto merge policy for mergify

- pkg/frontend/insert.go
- pkg/frontend/mysql_cmd_executor.go
- pkg/sql/plan2/function/operators.go
That code get slipped into main, then reverted, but later
I made a mistake merge 12206482.
Revert.
issue #
Not Available
Not Available
Not Available
> This checkin reverts #3637 related code.

- .github/workflows/ci.yml
issue #
Not Available
Not Available
Not Available
> fix ci uploading error when bvt failed

- .github/workflows/ci.yml
issue #3650 
Not Available
Not Available
Not Available
> setting timezone

- pkg/sql/plan2/build.go
- pkg/sql/plan2/build_update.go
- pkg/sql/plan2/query_builder.go
- pkg/sql/plan2/utils.go
issue #3262
Not Available
Not Available
Not Available
> [Opt] Join order: avoid cross product

- test/cases/subquery/subquery-with-exists.sql
issue #3311
Not Available
Not Available
Not Available
> Untag #3311

- pkg/common/morpc/backend.go
- pkg/common/morpc/backend_test.go
issue #
Not Available
Not Available
Not Available
> morpc: fix reconnect unstable

- test/cases/subquery/subquery-with-in.sql
issue #3323
Not Available
Not Available
Not Available
> Retag #3323 -> #3307

- pkg/sql/plan2/function/operator/cast.go
- test/cases/function/func_cast.test
- test/result/dml/select/select.result
- test/result/dtype/bigint.result
- test/result/dtype/date.result
- test/result/dtype/tinyint.result
- test/result/function/func_aggr_avg.result
- test/result/function/func_aggr_bitwise.result
- test/result/function/func_cast.result
issue #3247
Not Available
Not Available
Not Available
> Refactor and remove issue #3247 mark in test case

- test/cases/subquery/subquery-with-exists.sql
- test/result/subquery/subquery-with-exists.result
issue #3310
Not Available
Not Available
Not Available
> Retag #3310 -> #3307

- test/cases/subquery/subquery-with-any.sql
- test/cases/subquery/subquery-with-in.sql
issue #3309
Not Available
Not Available
Not Available
> Triage #3309 to #3308 and #3312

- pkg/sql/colexec2/loopcomplement/complement.go
issue #
Not Available
Not Available
Not Available
> remove pointless log

- pkg/logservice/store.go
issue #
Use pkg/common/stopper instead of an external package.
Not Available
Not Available
> logservice: use pkg/common/stopper

- test/cases/dtype/char.test
- test/cases/dtype/varchar.test
- test/result/dtype/char.result
- test/result/dtype/varchar.result
issue #
Not Available
Not Available
Not Available
> Adjust cases of char and varchar to fix #3678

- test/cases/dtype/timestamp.test
issue #3676
Not Available
Not Available
Not Available
> fix issue#3676

- pkg/sql/compile2/compile.go
issue #
Not Available
Not Available
Not Available
> special handing of single column anti join

- pkg/frontend/mysql_cmd_executor.go
issue #3721 
Not Available
Not Available
Not Available
> fix the bug which outfile tag is always true after into outfile

- test/cases/dtype/float.test
- test/cases/function/func_substr.sql
issue #3165，#3367
Not Available
Not Available
Not Available
> remove 3165,3367 tag

- pkg/sql/plan2/explain/column_prune_test.go
- pkg/sql/plan2/explain/explain_test.go
issue #3238
Add unit test for column pruning
Not Available
Not Available
> Add Unit Test for Column prune 

- pkg/sql/plan2/build_util.go
issue #1843
Not Available
Not Available
Not Available
> fix a bug of function convertValueIntoBool

- pkg/sql/parsers/tree/constant.go
issue #3746 
Not Available
Not Available
Not Available
> fix 3746 : confusing column name of char_length

- pkg/frontend/init_db.go
issue #3708 
Not Available
Not Available
Not Available
> fix the bug which mo-server can not start without delete the store file

- pkg/vm/engine/tae/catalog/database.go
- pkg/vm/engine/tae/catalog/table.go
- pkg/vm/engine/tae/db/db_test.go
- pkg/vm/engine/tae/logstore/store/file.go
- pkg/vm/engine/tae/logstore/store/replayer.go
- pkg/vm/engine/tae/logstore/store/store_test.go
- pkg/vm/engine/tae/logstore/store/syncbase.go
- pkg/vm/engine/tae/txn/txnimpl/store.go
- pkg/vm/engine/tae/txn/txnimpl/table.go
- pkg/vm/engine/tae/txn/txnimpl/txndb.go
issue #3725 
Not Available
Not Available
Not Available
> fix logstore replay

- pkg/vm/engine/tae/containers/alloc/alloc.go
- pkg/vm/engine/tae/containers/alloc/alloc_32bit.go
- pkg/vm/engine/tae/containers/alloc/alloc_64bit.go
- pkg/vm/engine/tae/containers/alloc/alloc_nocgo.go
- pkg/vm/engine/tae/containers/types.go
issue #
Implement a cgo allocator as a backend optional allocator for container
Not Available
Not Available
> add cgo allocator for container

- .github/workflows/issue_to_project.yml
issue #
implement auto add issue to project
Not Available
Not Available
> auto add issue to project

- pkg/frontend/insert.go
- pkg/sql/plan2/build_util.go
issue #3732 
Not Available
Not Available
Not Available
> Fix panic when inserting an error data type value

- CONTRIBUTING.md
Signed-off-by: wanglei4687 <wanglei4687@gmail.com>
issue #
Not Available
Not Available
Not Available
> doc(CONTRIBUTING): update CONTRIBUTING.md

- .github/ISSUE_TEMPLATE/10_bug_report.yml
- .github/workflows/robot.yml
issue #
Not Available
Not Available
Not Available
> coverage calculate rule and issue template update

- pkg/container/types/datetime.go
- pkg/container/types/datetime_test.go
issue #3362
Not Available
Not Available
Not Available
> fix wrong format datetime error message abnormal

- pkg/container/bitmap/bitmap.go
- pkg/container/bitmap/bitmap_test.go
- pkg/container/bitmap/types.go
issue #
Not Available
Not Available
Not Available
> fix bitmap bugs

- pkg/sql/colexec/agg/count/count.go
- pkg/sql/colexec/agg/count/types.go
- pkg/sql/colexec/agg/types.go
issue #
Not Available
Not Available
Not Available
> update the comments about aggregate function structure

- pkg/sql/plan2/mock.go
- pkg/sql/plan2/query_builder.go
issue #3262
Not Available
Not Available
Not Available
> [Opt] Leverage number of table rows in join order

- pkg/hakeeper/bootstrap/bootstrap.go
- pkg/hakeeper/bootstrap/bootstrap_test.go
issue #3814
Add len(dnStore) check
Not Available
Not Available
> fix issue #3814

- pkg/logservice/client.go
- pkg/logservice/client_test.go
issue #
Added godoc comments for Log Service client. 
Not Available
Not Available
> logservice: added godoc comments for client

- pkg/logservice/commands_test.go
- pkg/logservice/service_test.go
issue #
Fixed a few tests that relate to how replicas are started in Log Service.
Not Available
Not Available
> logservice: fixed tests relate to service start replicas

- pkg/common/moerr/error.go
- pkg/txn/service/types.go
- pkg/txn/storage/types.go
issue #
Not Available
Not Available
Not Available
> txn: add txn service and txn storage types

- pkg/pb/txn/txn.go
- pkg/pb/txn/txn.pb.go
- pkg/txn/client/operator.go
- pkg/txn/client/operator_test.go
- pkg/txn/storage/mem/kv_tree.go
- pkg/txn/storage/mem/kv_tree_test.go
- pkg/txn/storage/mem/kv_txn_storage.go
- pkg/txn/storage/mem/kv_txn_storage_test.go
- pkg/txn/storage/mem/log.go
- pkg/txn/storage/mem/log_test.go
- pkg/txn/storage/mem/mvcc_kv.go
- pkg/txn/storage/mem/mvcc_kv_test.go
- proto/txn.proto
issue #
Not Available
Not Available
Not Available
> txn: add mem txn storage for test

- .github/workflows/issue_to_project.yml
issue #
auto add kind/subtask to project
Not Available
Not Available
> auto add kind/subtask to project

- pkg/hakeeper/bootstrap/bootstrap.go
- pkg/hakeeper/bootstrap/bootstrap_test.go
issue #
Not Available
Not Available
Not Available
> Hakeeper: fix issue #3846

- pkg/sql/colexec/join/join.go
- pkg/sql/colexec/left/join.go
issue #
Not Available
Not Available
Not Available
> Fix the bug of join

- pkg/sql/plan/query_builder.go
issue #3262
Not Available
Not Available
Not Available
> [Opt] Fix join order bug

- pkg/sql/plan/mock.go
issue #
Not Available
Not Available
Not Available
> [Plan] Modify parameter for explain test

- pkg/txn/storage/mem/kv_txn_storage.go
- pkg/txn/storage/mem/kv_txn_storage_test.go
issue #
Not Available
Not Available
Not Available
> txn: add mem txn storage event for test

- pkg/vm/engine/tae/logstore/store/vfile.go
issue #
Not Available
Not Available
Not Available
> update sync, add panic info

- docs/en/MatrixOne/Reference/System-tables.md
issue #
Not Available
Not Available
Not Available
> Add system catalog doc

- pkg/txn/client/client_test.go
- pkg/txn/client/operator.go
- pkg/txn/client/operator_test.go
- pkg/txn/client/types.go
- pkg/txn/rpc/sender.go
- pkg/txn/rpc/sender_test.go
- pkg/txn/rpc/server_test.go
- pkg/txn/rpc/types.go
- pkg/txn/service/service.go
- pkg/txn/service/service_cn_handler.go
- pkg/txn/service/service_cn_handler_test.go
- pkg/txn/service/service_dn_handler_test.go
- pkg/txn/service/service_recovery.go
- pkg/txn/service/service_test.go
issue #
Not Available
Not Available
Not Available
> txn: avoid memory allocation for TxnSender result

- pkg/logservice/service_test.go
it is skipped by default, see comments for details
issue #
Re-enabled a test. See added comments for more details. 
Not Available
Not Available
> logservice: re-enabled a test

- pkg/hakeeper/rsm_test.go
- pkg/logservice/hakeeper_checker.go
- pkg/logservice/service_test.go
- pkg/logservice/store.go
- pkg/logservice/store_test.go
issue #
Made static check happy again. 
Not Available
Not Available
> logservice,hakeeper: made sca tools happy again

- pkg/txn/client/client_test.go
- pkg/txn/service/service_cn_handler_test.go
- pkg/txn/storage/mem/kv_txn_storage_test.go
issue #3950 
Not Available
Not Available
Not Available
> fix: static check

- pkg/hakeeper/rsm_test.go
issue #
Minor fix for a flaky test. 
Not Available
Not Available
> hakeeper: minor fix for TestClusterDetailsQuery

- pkg/common/hashmap/hashmap.go
- pkg/common/hashmap/hashmap_test.go
- pkg/common/hashmap/types.go
- pkg/container/types/types.go
issue #3599
Not Available
Not Available
Not Available
> Add hashmap

- pkg/vm/engine/tae/db/tables_test.go
- pkg/vm/engine/tae/tables/block.go
issue #
There is some problem with unit test`TestMergeBlocks2` and it sometimes fails during CI run.
Not Available
Not Available
> (tae): small code refactor and update ut

- pkg/pb/logservice/logservice.go
issue #
Not Available
Not Available
Not Available
> fix LogString mem err

- pkg/common/bitmap/bitmap.go
- pkg/common/bitmap/types.go
- pkg/common/hashmap/hashmap.go
issue #
Not Available
Not Available
Not Available
> remove useless code in bitmap

- pkg/logservice/commands.go
issue #
Fixed the join parameter.
Not Available
Not Available
> logservice: fixed the join parameter

- pkg/pb/logservice/logservice.go
- pkg/pb/logservice/logservice_test.go
fix #4023
issue #
Fixed LogRecord.ResizePayload(). 
Not Available
Not Available
> logservice: fixed LogRecord.ResizePayload()

- pkg/txn/service/service_cn_handler.go
- pkg/txn/service/service_cn_handler_test.go
- pkg/txn/service/service_test.go
issue #
Not Available
Not Available
Not Available
> txn: blocking read if local clock < txn.snapshot

- pkg/sql/plan/query_builder.go
issue #3262
Not Available
Not Available
Not Available
> [Opt] Tune join order

- Makefile
issue #
As per discussion, misspelling check should be disabled in SCA. 
Not Available
Not Available
> ci: removed misspelling check

- pkg/fileservice/s3.go
issue #
Not Available
Not Available
Not Available
> fileservice: add toml tag to s3 config

- go.mod
- go.sum
- pkg/util/toml/types.go
- pkg/util/toml/types_test.go
issue #
Not Available
Not Available
Not Available
> util: add toml types

- pkg/vm/engine/tae/dataio/segmentio/driver_test.go
- pkg/vm/engine/tae/dataio/segmentio/log.go
issue #
Not Available
Not Available
Not Available
> Fix the bug that replay dead loop when the log is not full

- pkg/fileservice/file_service.go
- pkg/fileservice/file_service_test.go
- pkg/fileservice/io_vector.go
- pkg/fileservice/local_fs.go
- pkg/fileservice/memory_fs.go
- pkg/fileservice/s3_fs.go
- pkg/fileservice/s3_fs_minio.go
issue #4065 
Not Available
Not Available
Not Available
> fileservice: allow reading to the end of file in FileService.Read

- go.mod
- pkg/common/hashmap/hashmap.go
- pkg/common/hashmap/hashmap_test.go
- pkg/common/hashmap/iterator.go
- pkg/common/hashmap/types.go
- pkg/container/vector/vector.go
issue #
Not Available
Not Available
Not Available
> Add iterator for strhashmap

- pkg/frontend/codec.go
issue #4081 
Not Available
Not Available
Not Available
> fix: sql codec

- docs/en/MatrixOne/FAQs/sql-faqs.md
issue #
Not Available
Not Available
Not Available
> Update SQL FAQ for 0.5

- pkg/sql/colexec/agg/agg.go
- pkg/sql/colexec/agg/bit_and/bit_and.go
- pkg/sql/colexec/agg/bit_or/bit_or.go
- pkg/sql/colexec/agg/bit_xor/bit_xor.go
- pkg/sql/colexec/agg/count/count.go
- pkg/sql/colexec/agg/distagg.go
- pkg/sql/colexec/agg/types.go
issue #3599
Not Available
Not Available
Not Available
> perfecting the agg interface

- pkg/txn/service/service_cn_handler_test.go
- pkg/txn/service/service_dn_handler_test.go
- pkg/txn/service/service_recovery_test.go
- pkg/txn/service/service_testutil.go
issue #
Not Available
Not Available
Not Available
> txn: export txn service test util functions

- pkg/container/types/types.go
- pkg/container/vector/vector.go
- pkg/sql/colexec2/limit/limit.go
- pkg/sql/colexec2/limit/limit_test.go
- pkg/sql/colexec2/limit/types.go
- pkg/sql/colexec2/merge/merge.go
- pkg/sql/colexec2/merge/merge_test.go
- pkg/sql/colexec2/merge/types.go
- pkg/sql/colexec2/mergelimit/limit.go
- pkg/sql/colexec2/mergelimit/limit_test.go
- pkg/sql/colexec2/mergelimit/types.go
- pkg/sql/colexec2/mergeoffset/offset.go
- pkg/sql/colexec2/mergeoffset/offset_test.go
- pkg/sql/colexec2/mergeoffset/types.go
- pkg/sql/colexec2/offset/offset.go
- pkg/sql/colexec2/offset/offset_test.go
- pkg/sql/colexec2/offset/types.go
- pkg/sql/colexec2/restrict/restrict.go
- pkg/sql/colexec2/restrict/types.go
- pkg/vm/process/process.go
issue #3921
Not Available
Not Available
Not Available
> Add colexec2 for rewrite operator

- pkg/pb/logservice/logservice.pb.go
- pkg/pb/metadata/metadata.pb.go
- pkg/pb/metric/metric.pb.go
- pkg/pb/plan/plan.pb.go
- pkg/pb/timestamp/timestamp.pb.go
- pkg/pb/txn/txn.pb.go
- proto/plan.proto
issue #3921
Not Available
Not Available
Not Available
> Add Analyze information for plan

- pkg/sql/colexec/agg/agg.go
- pkg/sql/colexec/agg/bit_and/bit_and.go
- pkg/sql/colexec/agg/bit_and/bit_and_test.go
- pkg/sql/colexec/agg/bit_or/bit_or.go
- pkg/sql/colexec/agg/bit_or/bit_or_test.go
- pkg/sql/colexec/agg/bit_xor/bit_xor.go
- pkg/sql/colexec/agg/bit_xor/bit_xor_test.go
- pkg/sql/colexec/agg/count/count.go
- pkg/sql/colexec/agg/count/count_test.go
- pkg/sql/colexec/agg/distagg.go
- pkg/sql/colexec/agg/types.go
issue #3599
Not Available
Not Available
Not Available
> Improve the agg interface

- pkg/vm/engine/tae/tables/updates/delchain.go
- pkg/vm/engine/tae/tables/updates/mvcc.go
- pkg/vm/engine/tae/tables/updates/updatechain.go
- pkg/vm/engine/tae/tables/updates/updateview.go
issue #4104 
Not Available
Not Available
Not Available
> (tae): fix mvcc bug

- pkg/container/vector/types.go
- pkg/container/vector/vector.go
- pkg/sql/colexec/agg/agg.go
- pkg/sql/colexec/agg/distagg.go
- pkg/sql/colexec/agg/types.go
- pkg/sql/colexec/complement/types.go
- pkg/sql/colexec/connector/types.go
- pkg/sql/colexec/expr_eval.go
- pkg/sql/colexec/left/types.go
- pkg/sql/colexec/limit/limit.go
- pkg/sql/colexec/semi/types.go
- pkg/sql/colexec2/limit/limit.go
- pkg/sql/compile/scope.go
- pkg/vm/engine/memEngine/types.go
- pkg/vm/process/types.go
issue #4104
Not Available
Not Available
Not Available
> Fix the static check problems of comment

- pkg/txn/client/client.go
- pkg/txn/storage/mem/mvcc_kv.go
issue #
Not Available
Not Available
Not Available
> fix: txn static check

- pkg/dnservice/factory.go
- pkg/txn/service/service_dn_handler.go
- pkg/txn/service/service_testutil.go
- pkg/txn/storage/mem/kv_txn_storage.go
- pkg/txn/storage/mem/kv_txn_storage_test.go
- pkg/txn/storage/types.go
issue #
Not Available
Not Available
Not Available
> txn: alloc prepare ts in TxnStorage

- pkg/dnservice/cfg.go
- pkg/dnservice/cfg_test.go
- pkg/dnservice/store.go
issue #
Not Available
Not Available
Not Available
> dnservice: add max connection idle duration config

- pkg/common/morpc/client.go
- pkg/pb/txn/txn.go
issue #
Not Available
Not Available
Not Available
> fix: more sca check

- Makefile
issue #
`make clean` should clean *.o *.a files generated in `cgo/`.
Not Available
Not Available
> make clean cgo *.o, *.a files

- docs/en/MatrixOne/FAQs/sql-faqs.md
- docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/with-cte.md
issue #
Not Available
Not Available
Not Available
> Add constraint for CTE, update sql faq

- pkg/frontend/routine_manager.go
issue #
Not Available
Not Available
Not Available
> fix data race in frontend module

- test/cases/expression/cte.sql
- test/cases/subquery/subquery-with-any.sql
- test/cases/subquery/subquery-with-exists.sql
- test/cases/subquery/subquery-with-in.sql
issue #3304
Not Available
Not Available
Not Available
> Retag some #3304 cases

- pkg/sql/colexec/agg/agg.go
- pkg/sql/colexec/agg/distagg.go
Signed-off-by: Wu Qinxuan <wuqinxuan33@gmail.com>
issue #
Fix agg and disagg string type init issue
Not Available
Not Available
> Fix agg and disagg string type init issue

- pkg/container/ring/avg/decimal.go
- pkg/container/ring/sum/decimal64.go
- pkg/container/types/decimal.go
- pkg/container/types/decimal_test.go
- pkg/frontend/load.go
- pkg/frontend/mysql_cmd_executor.go
- pkg/sql/plan/function/builtin/binary/typecast.go
- pkg/sql/plan/function/operator/and.go
- pkg/sql/plan/function/operator/cast.go
- pkg/sql/plan/function/operator/minus.go
- pkg/sql/plan/function/operator/not.go
- pkg/sql/plan/function/operator/or.go
- pkg/sql/plan/function/operator/xor.go
- pkg/testutil/util_make.go
- pkg/testutil/util_new.go
Use value as receiver is safer.
Many random small sca fixes.
issue #
Not Available
Not Available
Not Available
> Move decimal64/128 receiver to value.

- pkg/pb/metadata/metadata.go
- pkg/pb/timestamp/timestamp.go
- pkg/pb/txn/txn.go
- pkg/txn/client/operator.go
- pkg/txn/service/service.go
- pkg/txn/service/service_cn_handler.go
- pkg/txn/service/service_dn_handler.go
- pkg/txn/service/service_recovery.go
- pkg/txn/util/log.go
issue #
Not Available
Not Available
Not Available
> txn: format txn log

- pkg/common/hashmap/strhashmap.go
- pkg/sql/colexec/agg/bit_and/bit_and.go
- pkg/sql/colexec/agg/bit_and/bit_and_test.go
- pkg/sql/colexec/agg/bit_and/types.go
- pkg/sql/colexec/agg/bit_or/bit_or.go
- pkg/sql/colexec/agg/bit_or/bit_or_test.go
- pkg/sql/colexec/agg/bit_or/types.go
- pkg/sql/colexec/agg/bit_xor/bit_xor.go
- pkg/sql/colexec/agg/bit_xor/bit_xor_test.go
- pkg/sql/colexec/agg/bit_xor/types.go
- pkg/sql/colexec/agg/count/count.go
- pkg/sql/colexec/agg/count/count_test.go
- pkg/sql/colexec/agg/stddevpop/stddevpop.go
- pkg/sql/colexec/agg/stddevpop/stddevpop_test.go
- pkg/sql/colexec/agg/stddevpop/types.go
- pkg/sql/colexec/agg/variance/types.go
- pkg/sql/colexec/agg/variance/variance.go
- pkg/sql/colexec/agg/variance/variance_test.go
issue #3599
strengthen generic semantics of bit_or,bit_and,bit_xor,count,stddevpop,variance
Not Available
Not Available
> strengthen generic semantics of bit_or,bit_and,bit_xor,count,stddevpop,variance

- .github/workflows/robot.yml
- pkg/common/bitmap/cbitmap.go
issue #
Not Available
Not Available
Not Available
> Modify the compile options in yum

- cmd/generate-config/config_template.go
- pkg/config/test/config_template.go
- pkg/fileservice/memory_fs.go
- pkg/sql/parsers/goyacc/goyacc.go
- pkg/sql/plan/build_test.go
- pkg/vm/engine/tae/db/base_test.go
- pkg/vm/engine/tae/db/replay.go
issue #4180 
Not Available
Not Available
Not Available
> remove usages of ioutil package

- Makefile
- pkg/sql/plan/visit_query.go
- pkg/vm/engine/tae/logstore/store/file.go
issue #
report all errors identified by static-check
minor fixes for various static check errors escaped from previous runs
Not Available
Not Available
> Makefile: report all errors identified by static-check

- pkg/common/stopper/stopper.go
issue #
Not Available
Not Available
Not Available
> Remove recover from stopper

- cmd/mo-service/cfg.go
- cmd/mo-service/cfg_test.go
- etc/dn-minimal-test.toml
issue #
Not Available
Not Available
Not Available
> config: add minmal dn test config

- pkg/dnservice/cfg.go
issue #
Not Available
Not Available
Not Available
> dnservice: fix config toml tag error

- pkg/txn/storage/mem/kv_txn_storage.go
- pkg/txn/storage/mem/kv_txn_storage_test.go
issue #
Not Available
Not Available
Not Available
> txn: fix prepare conflict check

- pkg/fileservice/config.go
- pkg/fileservice/s3.go
issue #
Not Available
Not Available
Not Available
> fileservice: add create fileservice from config

- pkg/fileservice/vfs_fs.go
- pkg/fileservice/vfs_fs_test.go
updates issue #2716 
Not Available
Not Available
Not Available
> fileservice: add VfsFS for testing uses

- pkg/dnservice/cfg.go
- pkg/dnservice/factory.go
- pkg/txn/storage/tae/storage.go
updates issue #3516 
Not Available
Not Available
Not Available
> sketch TAE storage

- pkg/fileservice/config.go
- pkg/fileservice/s3.go
issue #
Not Available
Not Available
Not Available
> fileservice: add new file service from config

- pkg/logservice/errors.go
- pkg/logservice/errors_test.go
issue #
fixed dragonboat.ErrInvalidDeadline handling
Not Available
Not Available
> logservice: fixed dragonboat.ErrInvalidDeadline handling

- pkg/logservice/store_metadata.go
- pkg/logservice/store_metadata_test.go
issue #
fixed duplicated shard metadata record
Not Available
Not Available
> logservice: fixed duplicated shard metadata record

- cmd/mo-service/cfg.go
- cmd/mo-service/cfg_test.go
- cmd/mo-service/main.go
- pkg/dnservice/cfg.go
- pkg/dnservice/factory.go
- pkg/dnservice/factory_test.go
- pkg/dnservice/store.go
- pkg/dnservice/store_metadata.go
- pkg/dnservice/store_metadata_test.go
- pkg/dnservice/store_test.go
- pkg/fileservice/config.go
issue #
Not Available
Not Available
Not Available
> mo-service: create fileservice in main

- cmd/mo-service/cfg_test.go
- etc/dn-minimal-test.toml
issue #
Not Available
Not Available
Not Available
> update minimal dn config file

- pkg/vm/engine/txn/database.go
- pkg/vm/engine/txn/engine.go
- pkg/vm/engine/txn/error.go
- pkg/vm/engine/txn/hakeeper.go
- pkg/vm/engine/txn/operations.go
- pkg/vm/engine/txn/relation.go
- pkg/vm/engine/txn/shard.go
- pkg/vm/engine/txn/table.go
- pkg/vm/engine/txn/table_reader.go
- pkg/vm/engine/txn/txn.go
updates issue #4250 
Not Available
Not Available
Not Available
> add txn engine

- pkg/dnservice/cfg.go
- pkg/dnservice/cfg_test.go
- pkg/dnservice/store_test.go
issue #
Not Available
Not Available
Not Available
> dnservice: remove datadir config

- pkg/common/morpc/backend.go
- pkg/common/morpc/backend_test.go
issue #
Not Available
Not Available
Not Available
> morpc: limit backend reconnect

- cmd/mo-service/main.go
- etc/dn-minimal-s3-test.toml
- etc/dn-minimal-test.toml
issue #
Not Available
Not Available
Not Available
> mo-service: remove uuid from cmd line

- pkg/logservice/service_wrap.go
- pkg/tests/service/address.go
- pkg/tests/service/address_test.go
- pkg/tests/service/dnservice.go
- pkg/tests/service/doc.go
- pkg/tests/service/errors.go
- pkg/tests/service/fileservice.go
- pkg/tests/service/fileservice_test.go
- pkg/tests/service/logservice.go
- pkg/tests/service/options.go
- pkg/tests/service/options_test.go
- pkg/tests/service/service.go
- pkg/tests/service/service_test.go
issue #4002
Not Available
Not Available
Not Available
> Implements integration test framework for `dn` and `log` services;

- pkg/logservice/client.go
- pkg/logservice/commands.go
issue #
minor tweaks on connection timeout
Not Available
Not Available
> logservice: minor tweaks on connection timeout

- go.mod
- go.sum
- pkg/txn/storage/txn/alias.go
- pkg/txn/storage/txn/catalog.go
- pkg/txn/storage/txn/handler.go
- pkg/txn/storage/txn/mem_handler.go
- pkg/txn/storage/txn/mem_handler_test.go
- pkg/txn/storage/txn/mvcc.go
- pkg/txn/storage/txn/mvcc_test.go
- pkg/txn/storage/txn/read.go
- pkg/txn/storage/txn/read_result.go
- pkg/txn/storage/txn/storage.go
- pkg/txn/storage/txn/storage_test.go
- pkg/txn/storage/txn/table.go
- pkg/txn/storage/txn/table_iter.go
- pkg/txn/storage/txn/table_test.go
- pkg/txn/storage/txn/transaction.go
- pkg/txn/storage/txn/types.go
- pkg/txn/storage/txn/write.go
- pkg/vm/engine/txn/operations.go
updates issue #4250 
Not Available
Not Available
Not Available
> add txnstorage package

- pkg/common/morpc/server.go
issue #
Not Available
Not Available
Not Available
> morpc: fix close data race

- go.mod
- go.sum
issue #
Not Available
Not Available
Not Available
> morpc: upgrade goetty

- pkg/common/morpc/examples/message/message.go
issue #
Not Available
Not Available
Not Available
> fix ineffictiveassign static check

- pkg/common/bitmap/bitmap.go
issue #4306 
Not Available
Not Available
Not Available
> bitmap: implement encoding.BinaryMarshaler/Unmarshaler for Bitmap

- pkg/sql/colexec/loopsingle/join.go
- pkg/sql/colexec/loopsingle/join_test.go
- pkg/sql/colexec/loopsingle/types.go
- pkg/sql/colexec/single/join.go
- pkg/sql/colexec/single/join_test.go
- pkg/sql/colexec/single/types.go
- pkg/sql/compile/compile.go
- pkg/sql/compile/operator.go
- pkg/sql/plan/explain/explain_node.go
- pkg/sql/plan/flatten_subquery.go
- pkg/sql/plan/query_builder.go
- pkg/vm/overload.go
- test/cases/expression/cte.sql
- test/cases/function/func_string_concat_ws.test
- test/cases/subquery/subquery-with-in.sql
- test/result/expression/cte.result
- test/result/subquery/subquery-with-in.result
issues #3303 #4151
Not Available
Not Available
Not Available
> Implement SINGLE join

- pkg/dnservice/factory.go
- pkg/txn/storage/tae/storage.go
updates issue #3516 
Not Available
Not Available
Not Available
> dnservice: pass clock to taestorage.New

- cgo/Makefile
issue #
Not Available
Not Available
Not Available
> cgo: fix Makefile to avoid recompilation in every build

- cmd/db-server/main.go
- pkg/frontend/internal_executor.go
- pkg/frontend/internal_executor_test.go
- pkg/util/internalExecutor/internal_executor.go
- pkg/util/metric/metric_collector_test.go
issue #
Internal Executor can query now
This implementation is a prototype, at most 100 rows will be hold in the result, more rows will be dropped.
Not Available
> feat: add query to internalExecutor

- .github/mergify.yml
issue #
Not Available
Not Available
Not Available
> Mergify: add mergify message for PR

- Makefile
issue #
This will make it easier to debug binary
Not Available
Not Available
> chore: disable optimization and inlining when build debug binary

- pkg/hakeeper/bootstrap/bootstrap.go
- pkg/hakeeper/bootstrap/bootstrap_test.go
- pkg/pb/logservice/logservice.go
- pkg/pb/logservice/logservice_test.go
issue #
Not Available
Not Available
Not Available
> fix bootstrap dn bug & commands' log output

- .github/mergify.yml
issue #
modify files to make mergify commit message include PR number
Not Available
Not Available
> Mergify: mergify add PR number

- .github/mergify.yml
issue #
ignore darwin check and set queue check timeout to 30 minutes
Not Available
Not Available
> Mergify ignore darwin

- .github/PULL_REQUEST_TEMPLATE.md
- .github/mergify.yml
issue #
Not Available
Not Available
Not Available
> Mergify: add more information for PR merge commit message

- .github/mergify.yml
issue #
add check label do-not-merge/wip
> Mergify: add check label do-not-merge/wip

- pkg/sql/compile/compile.go
- pkg/sql/compile/scope.go
- test/cases/dml/insert/insert.test
- test/cases/dtype/bigint.test
- test/cases/dtype/decimal.test
- test/cases/dtype/double.test
- test/cases/dtype/float.test
- test/cases/dtype/int.test
- test/cases/dtype/smallint.test
- test/cases/dtype/tinyint.test
- test/cases/function/func_aggr_max.test
- test/cases/function/func_aggr_sum.test
- test/cases/function/func_if.test
- test/result/dml/insert/insert.result
- test/result/dtype/double.result
- test/result/dtype/tinyint.result
- test/result/function/func_aggr_sum.result
- test/result/function/func_if.result
> remove insert issue tag and add some test cases=

- pkg/compress/compress.go
- pkg/compress/compress_test.go
- pkg/vm/engine/memEngine/relation.go
- pkg/vm/engine/tae/dataio/segmentio/driver.go
issue #4361
Update lz4 version
> Update lz4 version

- pkg/sql/plan/function/builtin/binary/typecast.go
- pkg/sql/plan/function/operator/cast.go
- test/cases/dtype/bigint.test
> fix cast uint as char

- pkg/frontend/test/engine_mock.go
- pkg/frontend/test/txn_mock.go
- pkg/sql/compile/compile.go
- pkg/txn/storage/txn/atomic.go
- pkg/txn/storage/txn/mem_handler.go
- pkg/txn/storage/txn/mvcc.go
- pkg/txn/storage/txn/mvcc_test.go
- pkg/txn/storage/txn/transaction.go
- pkg/vm/engine/memEngine/engine.go
- pkg/vm/engine/tae/moengine/engine.go
- pkg/vm/engine/txn/database.go
- pkg/vm/engine/txn/engine.go
- pkg/vm/engine/txn/hakeeper.go
- pkg/vm/engine/txn/table.go
- pkg/vm/engine/txn/table_reader.go
- pkg/vm/engine/txn/test/engine_test.go
- pkg/vm/engine/txn/test/txn_sender.go
- pkg/vm/engine/txn/txn.go
- pkg/vm/engine/types.go
updates issue #4250 
txnstorage: implement MemHandler.HandleCommit,HandleCommitting,HandleDestroy,HandlePrepare,HandleRollback,HandleStartRecovery
txnstorage: make Transaction.State an atomic value
txnengine: refine doTxnRequest
txnengine: separate hakeeper related codes from Engine
engine: add error return value to Engine.Nodes
> txnstorage, txnengine: refinements

- pkg/fileservice/file_service.go
- pkg/fileservice/lru.go
- pkg/fileservice/pin.go
- pkg/fileservice/pin_test.go
updates issue #2716 
fileservice: add value pinning in LRU
> fileservice: add value pinning in LRU

- pkg/fileservice/caching_file_service.go
- pkg/fileservice/caching_file_service_test.go
- pkg/fileservice/config.go
- pkg/fileservice/local_fs.go
- pkg/fileservice/local_fs_test.go
- pkg/fileservice/lru.go
- pkg/fileservice/mem_cache.go
- pkg/fileservice/s3_fs.go
- pkg/fileservice/s3_fs_test.go
update issue #2716 
fileservice: add CachingFileService; implement CachingFileService for S3FS
fileservice: add MemCache
fileservice: add testCachingFileService
fileservice: implement CachingFileService for LocalFS
> fileservice: cache refinements

- pkg/fileservice/file_service.go
- pkg/fileservice/lru.go
- pkg/fileservice/rc.go
- pkg/fileservice/rc_test.go
issue #2716 
fileservice: replace Pinned with RC
> fileservice: replace Pinned with RC

- pkg/sql/colexec/mergeorder/order.go
issue #4427
Fix the bug of ssb
> Fix the bug of ssb

- pkg/hakeeper/checkers/syshealth/check.go
- pkg/hakeeper/checkers/syshealth/check_test.go
issue #4430
- Evaluate health of a log shard via its running replicas, not via its expired replica.
> Fix issue #4430

- pkg/container/types/decimal.go
- pkg/sql/parsers/dialect/mysql/mysql_sql.go
- pkg/sql/parsers/dialect/mysql/mysql_sql.y
- pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
- pkg/sql/plan/build_util.go
- pkg/sql/plan/function/builtin/binary/typecast.go
- pkg/sql/plan/function/operator/cast.go
- pkg/vectorize/floor/floor.go
- test/cases/dtype/date.test
- test/cases/dtype/decimal.test
- test/cases/function/func_cast.test
- test/result/dtype/date.result
- test/result/dtype/decimal.result
> fix some cast error about decimal

- .github/ut_pr.yml
issue #4202 
add file `ut_pr.yml` to support pull request additional unit test coverage
> CI: add pull request additional unit test coverage

- go.mod
- go.sum
> Upgrade goetty to support TLS

- pkg/txn/service/service_testutil.go
- pkg/txn/storage/mem/kv_txn_storage.go
- pkg/txn/storage/mem/kv_txn_storage_test.go
- pkg/txn/storage/mem/log.go
- pkg/txn/storage/mem/log_test.go
Inconsistent behaviour of the memory-based implementation of Log and LogService, resulting in the test DNService not working properly
issue #4334
> txn: make mem log lsn start with 1

- pkg/vm/engine/tae/db/db_test.go
- pkg/vm/engine/tae/tables/jobs/mergeblocks.go
issue #4469 
Fix mergeblocks. Record deleteMask for those with primary key.
> fix mergeblocks

- pkg/dnservice/replica.go
- pkg/dnservice/replica_test.go
- pkg/dnservice/store.go
issue #
Closing un started dn shard will be blocked
> dnservice: close unstarted shard will be blocked

- .github/workflows/labeler.yml
> Labeler: Update labeler.yml to fix bug

- pkg/txn/storage/txn/mem_handler.go
- pkg/txn/storage/txn/mvcc.go
- pkg/vm/engine/txn/database.go
- pkg/vm/engine/txn/engine.go
- pkg/vm/engine/txn/hack.go
- pkg/vm/engine/txn/operations_test.go
- pkg/vm/engine/txn/shard.go
- pkg/vm/engine/txn/table.go
- pkg/vm/engine/txn/table_reader.go
- pkg/vm/engine/txn/test/engine_test.go
- pkg/vm/engine/txn/test/env.go
- pkg/vm/engine/txn/test/execution.go
- pkg/vm/engine/txn/test/node.go
- pkg/vm/engine/txn/test/shard.go
- pkg/vm/engine/txn/test/tx.go
- pkg/vm/engine/txn/test/txn_sender.go
- pkg/vm/engine/txn/txn.go
issue #4250 
add testtxnengine package
refactor sharding in txnengine
> add testtxnengine package

- pkg/fileservice/block_mapper.go
- pkg/fileservice/block_mapper_test.go
- pkg/fileservice/utils.go
issue #2716 
fileservice: add BlockMapper
> fileservice: add BlockMapper

- pkg/fileservice/block_mapper.go
- pkg/fileservice/block_mapper_test.go
- pkg/fileservice/local_fs.go
issue #2716 
fileservice: add BlockMappable interafce
fileservice: optimize LocalFS.Read
> fileservice: add BlockMappable interafce

- pkg/sql/plan/function/builtins.go
- test/cases/function/func_string_char_length.test
- test/cases/function/func_string_substring.test
> fix char_length with param of varchar

- pkg/container/batch/batch.go
- pkg/container/batch/types.go
- pkg/container/vector/vector.go
issue #
vector: fix Vector.Read; 
batch: add EncodeBatch.Attrs
> vector: fix Vector.Read; batch: add EncodeBatch.Attrs

- pkg/sql/plan/query_builder.go
> [Opt] Enable pushdown of non-equi SEMI/ANTI joins

- pkg/sql/colexec/agg/agg.go
- pkg/sql/colexec/agg/avg/avg.go
- pkg/sql/colexec/group/group.go
- pkg/sql/compile/compile.go
> Fix the bug of union

- .dockerignore
Signed-off-by: wanglei4687 <wanglei4687@gmail.com>
issue #
> feat: add dockerignore

- pkg/sql/colexec/agg/avg/avg.go
> Fix the bug of avg

- go.mod
- go.sum
- pkg/sql/colexec/external/external.go
issue #4550 
solve memory leak in batch alloc
> use mheap to alloc batch in external scan

- pkg/txn/client/client.go
issue #
Adjust default clock maxoffset
> txn: adjust default clock maxoffset

- pkg/logservice/client.go
- pkg/logservice/service.go
- pkg/txn/rpc/sender.go
- pkg/txn/rpc/sender_test.go
- pkg/txn/rpc/server.go
issue #
active checksum in cn, dn and logservice
> morpc: active checksum in cn, dn and logservice

- pkg/fileservice/local_etl_fs.go
- pkg/fileservice/local_etl_fs_test.go
issue #2716
fileservice: implement MutableFileService for LocalETLFS
> fileservice: implement MutableFileService for LocalETLFS

- pkg/dnservice/factory.go
- pkg/dnservice/store.go
- pkg/dnservice/store_metadata.go
- pkg/dnservice/store_metadata_test.go
- pkg/dnservice/store_test.go
- pkg/fileservice/config.go
- pkg/fileservice/file_service.go
- pkg/fileservice/file_service_test.go
- pkg/fileservice/file_services.go
- pkg/fileservice/file_services_test.go
- pkg/fileservice/get.go
- pkg/fileservice/local_etl_fs.go
- pkg/fileservice/local_fs.go
- pkg/fileservice/local_fs_test.go
- pkg/fileservice/memory_fs.go
- pkg/fileservice/path.go
- pkg/fileservice/s3_fs.go
- pkg/fileservice/s3_fs_test.go
- pkg/sql/colexec/external/external.go
- pkg/tests/service/fileservice.go
- pkg/txn/storage/tae/storage.go
issue #2716
fileservice: add FileService.Name
fileservice: add FileServices; add Get
fileservice: support named path
dnservice: replace store.localFS,s3FS with store.fs,metadataFS
> fileservice: various changes

- etc/cn-minimal-test.toml
- pkg/cnservice/server.go
- pkg/cnservice/types.go
issue #
cnservice: initialize hakeeper client, txn sender, txn client lazily
> cnservice: initialize hakeeper client, txn sender, txn client lazily

- pkg/frontend/mysql_cmd_executor_test.go
- pkg/frontend/session.go
- pkg/frontend/session_test.go
- pkg/frontend/test/txn_mock.go
- pkg/txn/client/client.go
- pkg/txn/client/client_test.go
- pkg/txn/client/operator_test.go
- pkg/txn/client/types.go
- pkg/vm/engine/tae/moengine/txn_wrapper.go
- pkg/vm/engine/txn/test/env.go
- pkg/vm/engine/txn/test/session.go
- pkg/vm/engine/txn/test/tx.go
issue #
txn: add error return to TxnClient.New
> txn: add error return to TxnClient.New

- pkg/cnservice/server.go
- pkg/sql/compile/server.go
- pkg/sql/compile/types.go
> Move pipeline server from cn server to pipeline

- pkg/dnservice/factory.go
- pkg/dnservice/store.go
issue #
Retry start DNShard if failed
> dnservice: retry start dnshard

- pkg/dnservice/factory.go
- pkg/txn/storage/txn/isolation.go
- pkg/txn/storage/txn/mem_handler.go
- pkg/txn/storage/txn/mvcc.go
- pkg/txn/storage/txn/mvcc_test.go
- pkg/txn/storage/txn/table_test.go
- pkg/txn/storage/txn/transaction.go
- pkg/vm/engine/txn/test/node.go
issue #
txnstorage: add IsolationPolicy; refactor conflict error types
> txnstorage: add IsolationPolicy; refactor conflict error types

- pkg/vm/engine/tae/catalog/base.go
- pkg/vm/engine/tae/catalog/catalog.go
- pkg/vm/engine/tae/catalog/database.go
- pkg/vm/engine/tae/db/db_test.go
issue #4661 
read when ts is equal
> fix get node to read

- pkg/sql/compile/compile.go
- pkg/sql/compile/scope.go
> Refactor compile

- test/cases/dtype/text_1.sql
- test/result/dtype/text_1.result
> add text type test

- .github/workflows/ci.yml
- .github/workflows/labeler.yml
- .github/workflows/ut_pr.yml
issue #
In this pr, I optimized ut_pr and add auto cancel outdate workflows. For the function of automatic cancellation, please refer to this link: https://docs.github.com/en/actions/using-jobs/using-concurrency
> CI: optimize ut_pr and auto cancel outdate workflows

- pkg/frontend/load_test.go
- pkg/frontend/mysql_cmd_executor_test.go
- pkg/frontend/session.go
- pkg/frontend/session_test.go
- pkg/frontend/test/engine_mock.go
- pkg/vm/engine/disttae/engine.go
- pkg/vm/engine/memEngine/engine.go
- pkg/vm/engine/tae/moengine/engine.go
- pkg/vm/engine/txn/engine.go
- pkg/vm/engine/types.go
issue #3515 
vm/engine: add Engine.Hints
> vm/engine: add Engine.Hints

- CODEOWNERS
issue #
I also need to maintain the entrence of the frontend.
So, I apply for the another code owner of pkg/cnservice
> apply for the another code owner of pkg/cnservice

- pkg/fileservice/file_services.go
- pkg/fileservice/local_etl_fs.go
- pkg/fileservice/local_fs.go
- pkg/fileservice/memory_fs.go
- pkg/fileservice/path.go
- pkg/fileservice/s3_fs.go
issue #2716
fileservice: add Path, ParsePath, ParsePathAtService
> fileservice: add Path, ParsePath, ParsePathAtService

- test/cases/function/func_coalesce_1.sql
- test/result/function/func_coalesce_1.result
> add func coalesce test

- docs/cn/MatrixOne/Tutorial/SSB-test-with-matrixone.md
- docs/cn/README.md
> ALTER ERROR PATH

- test/cases/function/func_date_format_1.sql
- test/result/function/func_date_format_1.result
> add func date_format test

- pkg/dnservice/store.go
issue #
Add more log for schedule command
> dnservice: add more debug for schedule command

- .github/workflows/ut_pr.yml
issue #
fix bug: add awk file path
> CI: Update ut_pr.yml

- pkg/hakeeper/checkers/dnservice/check.go
- pkg/hakeeper/checkers/dnservice/parse.go
issue #
- Add log for `pkg/hakeeper/checkers/dnservice`
> Add log for pkg/hakeeper/checkers/dnservice;

- pkg/frontend/mysql_cmd_executor.go
- pkg/sql/plan/build_show.go
- test/cases/dml/show/show.test
- test/result/dml/show/show.result
> fix select 'create table' and log err for sql fail

- pkg/dnservice/store_metadata.go
- pkg/pb/metadata/metadata.go
issue #
Add log for loaded local metadata in dnservice
> dnservice: add start log for local metadata

- test/cases/distinct/distinct.sql
- test/result/distinct/distinct.result
> add distinct test

- pkg/fileservice/errors.go
- pkg/fileservice/file_service.go
- pkg/fileservice/file_service_test.go
- pkg/fileservice/file_services_test.go
- pkg/fileservice/get.go
- pkg/fileservice/local_etl_fs_test.go
- pkg/fileservice/local_fs_test.go
- pkg/fileservice/memory_fs.go
- pkg/fileservice/memory_fs_test.go
- pkg/fileservice/path.go
- pkg/fileservice/s3_fs.go
- pkg/fileservice/s3_fs_test.go
issue #
fileservice: implement ETLFileService for MemoryFS
fileservice: add FileService.Name tests
> fileservice fixes

- pkg/fileservice/errors.go
- pkg/fileservice/s3_fs.go
- pkg/fileservice/s3_fs_test.go
issue #
fileservice: try loading s3 test config
> fileservice: try loading s3 test config

- pkg/txn/storage/txn/catalog_handler.go
- pkg/txn/storage/txn/catalog_handler_test.go
- pkg/txn/storage/txn/mem_handler.go
issue #4250 
txnstorage: simplify CatalogHandler
> txnstorage: simplify CatalogHandler 

- pkg/sql/colexec/agg/stddevpop/stddevpop.go
- pkg/sql/colexec/agg/stddevpop/stddevpop_test.go
- pkg/sql/colexec/agg/stddevpop/types.go
- pkg/sql/colexec/agg/variance/types.go
- pkg/sql/colexec/agg/variance/variance.go
- pkg/sql/colexec/agg/variance/variance_test.go
- pkg/sql/colexec/aggregate/aggregate.go
- pkg/sql/plan/base_binder.go
- pkg/sql/plan/function/aggregate.go
- test/cases/function/func_aggr_count.test
- test/cases/function/func_aggr_variance.test
- test/result/function/func_aggr_variance.result
> refactor func of variance and std for decimal

- pkg/fileservice/file_service.go
- pkg/fileservice/local_etl_fs.go
- pkg/fileservice/local_fs.go
- pkg/fileservice/mutable_file_service.go
- pkg/fileservice/mutable_file_service_test.go
> fileservice: add Mutator.Append

- pkg/txn/storage/txn/any.go
- pkg/txn/storage/txn/batch.go
- pkg/txn/storage/txn/frontend_test.go
- pkg/txn/storage/txn/mem_handler.go
issue #4250 
txnstorage: add AnyRow.String
txnstorage: fix MemHandler.rangeBatchPhysicalRows
txnstorage: update TestFrontend
txnstorage: fix BatchIter
> txnstorage: various fixes

- pkg/logutil/dragonboat.go
- pkg/logutil/dragonboat_test.go
- pkg/logutil/internal.go
- pkg/logutil/internal_test.go
- pkg/logutil/logutil2/api_test.go
- pkg/logutil/report.go
- pkg/logutil/report_test.go
issue #
make `PR Unit Test Coverage` pass on `pkg/logutil`, `pkg/logutil/logutil2`
> UT on pkg/logutil, pkg/logutil/logutil2

- pkg/pb/task/task.pb.go
- pkg/taskservice/types.go
- proto/task.proto
issue #
New TaskStorage interface to make testing easier, while allowing TaskService functionality not coupled with task metadata storage
> taskservice: modify the task-related abstract

- pkg/common/morpc/server.go
issue #
Add WithServerDisableAutoCancelContext options for morpc.  Used in scenarios where the handler handles messages asynchronously, causing the Context to be Cancelled early
> morpc: add disable auto cancel option

- pkg/vm/engine/disttae/db.go
- pkg/vm/engine/disttae/engine_test.go
- pkg/vm/engine/disttae/types.go
> Add cache interface for cn

- pkg/frontend/mysql_cmd_executor.go
- pkg/sql/colexec/auto_incr.go
- pkg/sql/colexec/external/external_test.go
- pkg/sql/compile/cnserviceDriver.go
- pkg/testutil/util_new.go
- pkg/vectorize/momath/math_test.go
- pkg/vm/engine/tae/common/mempool_test.go
- pkg/vm/process/process.go
- pkg/vm/process/types.go
issue #
add Process.TxnClient and use it in auto increment codes
> add Process.TxnClient and use it in auto increment codes

- pkg/vm/engine/tae/iface/txnif/types.go
- pkg/vm/engine/tae/txn/txnbase/impl.go
- pkg/vm/engine/tae/txn/txnbase/store.go
- pkg/vm/engine/tae/txn/txnbase/txn.go
- pkg/vm/engine/tae/txn/txnbase/txnctx.go
- pkg/vm/engine/tae/txn/txnbase/txnmgr.go
- pkg/vm/engine/tae/txn/txnimpl/store.go
- pkg/vm/engine/tae/txn/txnimpl/table.go
- pkg/vm/engine/tae/txn/txnimpl/txndb.go
issue #
1. Remove or merge some txn APIs
2. Code refactor for better readability
3. Sort out the 1pc|2pc process call chain
> dn txn related code refactor

- docs/cn/MatrixOne/Tutorial/develop-java-connect-mo.md
[Doc]: Fix some code error
issue #4976
> [Doc]: Fix some code error

- pkg/config/configuration.go
- pkg/frontend/mysql_cmd_executor.go
- pkg/frontend/util.go
issue #
Log the result status of the statements.
> log statement status

- pkg/sql/colexec/mergetop/top.go
- pkg/sql/colexec/top/top.go
> Fix the oom bug of top

- .github/workflows/robot.yml
> add check bvt issue ci

- pkg/util/metric/metric_test.go
issue #
skip specific metrics check because it can be failed to fetch once
> fix: skip specific metric check

- pkg/vm/process/analyze.go
> Modify the time unit of explain

- pkg/frontend/mysql_cmd_executor.go
- pkg/sql/parsers/tree/constant.go
- pkg/sql/parsers/tree/format.go
issue #3706
format string paramter in FmtCtx with `"`
> FmtCtx with quote string

- pkg/hakeeper/checkers/dnservice/parse.go
issue #
Lower the log level for frequent output.
> hakeeper: lower the log level for frequent output

- etc/cn-standalone-dist-tae-test.toml
- etc/cn-standalone-mem-engine-test.toml
- etc/cn-standalone-non-dist-memory-test.toml
- pkg/cnservice/memory_engine.go
- pkg/cnservice/server.go
- pkg/cnservice/types.go
issue #
cnservice: add non-distributed memory CN engine type
> cnservice: add non-distributed memory CN engine type

- pkg/sql/compile/ddl.go
issue #4865 
throw no database select error msg
> throw no database select error msg

- pkg/sql/plan/query_builder.go
- test/cases/union/union.result
- test/cases/union/union.sql
issue #4948 
fix bug: limit is incorrect in plan for union clause
sorry for that low level bug.
> fix bug: limit is incorrect in plan for union clause

- pkg/txn/storage/txn/any.go
- pkg/txn/storage/txn/batch.go
- pkg/txn/storage/txn/catalog.go
- pkg/txn/storage/txn/catalog_handler.go
- pkg/txn/storage/txn/mem_handler.go
- pkg/txn/storage/txn/nullable.go
- pkg/txn/storage/txn/table.go
- pkg/txn/storage/txn/types.go
issue #
txnstorage: rename namedAttrGetter to NamedRow
txnstorage: add NamedAnyRow
txnstorage: add Nullable
> txnstorage: various improvements

- pkg/vm/engine/tae/moengine/txn_wrapper.go
- pkg/vm/engine/tae/moengine/txn_wrapper_test.go
> moengine: implement wrappedTx.Snapshot; fix wrappedEngine.NewWithSnapshot

- test/cases/dml/select/union_and_union_all.sql
- test/result/dml/select/union_and_union_all.result
> add union and union all test

- pkg/sql/plan/explain/explain_node.go
- pkg/sql/plan/flatten_subquery.go
- pkg/sql/plan/join_order.go
- pkg/sql/plan/mock.go
- pkg/sql/plan/query_builder.go
- pkg/sql/plan/tpch/ddl.sql
- test/result/explain/explain.result
> [Opt] Improve join order by considering primary keys

- pkg/dnservice/store_metadata_test.go
- pkg/fileservice/cache.go
- pkg/fileservice/caching_file_service_test.go
- pkg/fileservice/config.go
- pkg/fileservice/file_service.go
- pkg/fileservice/file_service_bench_test.go
- pkg/fileservice/file_service_test.go
- pkg/fileservice/io.go
- pkg/fileservice/io_entry.go
- pkg/fileservice/local_etl_fs.go
- pkg/fileservice/local_fs.go
- pkg/fileservice/lru.go
- pkg/fileservice/mem_cache.go
- pkg/fileservice/memory_fs.go
- pkg/fileservice/s3_fs.go
- pkg/objectio/buffer.go
- pkg/objectio/column.go
- pkg/objectio/reader.go
- pkg/sql/plan/function/builtin/unary/load_file_test.go
- pkg/util/export/fs_writer.go
- pkg/util/file/file.go
> fileservice: use int64 extensively

- pkg/txn/storage/txn/account.go
- pkg/txn/storage/txn/catalog.go
- pkg/txn/storage/txn/catalog_handler.go
- pkg/txn/storage/txn/data.go
- pkg/txn/storage/txn/mem_handler.go
- pkg/txn/storage/txn/table.go
- pkg/txn/storage/txn/table_iter.go
- pkg/txn/storage/txn/table_test.go
- pkg/txn/storage/txn/tuple.go
issue #
txnstorage: rename AnyKey to Tuple, AnyRow to DataRow
txnstorage: rename Row.PrimaryKey to Key
txnstorage: add DataKey
txnstorage: replace MemHandler.tables with data
txnstorage: add TableIter.Seek
> txnstorage: various changes

- pkg/common/hashmap/inthashmap.go
- pkg/common/hashmap/strhashmap.go
- pkg/container/vector/vector.go
> Reduce unnecessary memory overhead

- pkg/frontend/mysql_cmd_executor.go
issue #4081， #4083
If the explain sql execution plan is not supported, an error is reported.
> modify explain insert value panic error

- pkg/frontend/mysql_protocol.go
issue #
remove unused code which for old logic.    and that code will make parseExecuteParameter incorrect
> fix bug: Execute parameter parser incorrect

- pkg/sql/plan/function/operator/logical.go
issue #5062
Modify the logic or operation bug, that is, when the 'constant null OR true', the result calculation is incorrect, and this pr is used to correct the bug
> Modify the logic bug Issue#5062

- pkg/vm/engine/tae/catalog/segment.go
- pkg/vm/engine/tae/catalog/table.go
- pkg/vm/engine/tae/db/db_test.go
- pkg/vm/engine/tae/tables/handle.go
issue #
https://github.com/matrixorigin/MO-Cloud/issues/33
> fix lastappendableblock

- pkg/cnservice/memory_engine.go
- pkg/txn/storage/txn/bvt/bvt.go
- pkg/txn/storage/txn/frontend_test.go
- pkg/vm/engine/txn/shard.go
- pkg/vm/engine/txn/shard_fallback.go
- pkg/vm/engine/txn/shard_hash.go
- pkg/vm/engine/txn/table.go
issue #
txnstorage: clean batch after HandleRead
txnengine: rename ShardToSingleStatic to NoShard
txnengine: add NewDefaultShardPolicy, FallbackShard, HashShard
> txnengine: shard policy changes

- pkg/vm/engine/tae/catalog/segment.go
- pkg/vm/engine/tae/db/db_test.go
- pkg/vm/engine/tae/tables/handle.go
issue # https://github.com/matrixorigin/MO-Cloud/issues/37
> fix getappendableblk

- pkg/vm/engine/txn/hakeeper.go
issue #
txnengine: do retry in GetClusterDetailsFromHAKeeper
> txnengine: do retry in GetClusterDetailsFromHAKeeper

- go.sum
- pkg/container/nulls/nulls.go
> Fix nulls.Filter function

- optools/images/Dockerfile
issue #
When we deploy MO in the Kubernetes cluster with mo-operator, we need to check the availability of the Pod DNS domains first before starting the processes, so we need the DNS utilities. And the curl maybe useful during debugging.
> install some utilities used for debugging or by startup script

- cmd/mo-service/config.go
- cmd/mo-service/config_test.go
- cmd/mo-service/launch.go
- cmd/mo-service/main.go
- etc/launch/cn1.toml
- etc/launch/dn1.toml
- etc/launch/launch.toml
- etc/launch/log1.toml
- etc/launch/log2.toml
- etc/launch/log3.toml
- go.sum
issue #
Start a multi-replica mo cluster with main. It's used in dev mode.
usage:
./mo-service -launch ./etc/launch/launch.toml 
by default it will launch 1 log service with 3 replicas, 1 dn and 1 cn.
> misc: start a multi-replica mo cluster with main

- pkg/sql/plan/build_insert.go
- pkg/sql/plan/build_update.go
- pkg/sql/plan/build_util.go
- test/cases/auto_increment/auto_increment_columns.result
- test/cases/auto_increment/auto_increment_columns.sql
> fix conflict between dafault and auto increment

- pkg/taskservice/task_service_cron_test.go
> taskservice: fix unstable tests

- cmd/mo-service/config_test.go
issue #
Fix tests: fix TestGossipSeedAddressesAreResolved
> tests: fix TestGossipSeedAddressesAreResolved

- pkg/txn/storage/txn/account.go
- pkg/txn/storage/txn/batch.go
- pkg/txn/storage/txn/catalog.go
- pkg/txn/storage/txn/catalog_handler.go
- pkg/txn/storage/txn/data.go
- pkg/txn/storage/txn/log_tail.go
- pkg/txn/storage/txn/log_tail_test.go
- pkg/txn/storage/txn/mem_handler.go
- pkg/txn/storage/txn/mem_storage.go
- pkg/txn/storage/txn/memtable/bench_test.go
- pkg/txn/storage/txn/memtable/physical_row.go
- pkg/txn/storage/txn/memtable/physical_row_test.go
- pkg/txn/storage/txn/memtable/table.go
- pkg/txn/storage/txn/memtable/table_iter.go
- pkg/txn/storage/txn/memtable/table_test.go
- pkg/txn/storage/txn/storage_test.go
- pkg/txn/storage/txn/types.go
issue #
txnstorage: do not return empty log tail entry
txnstorage: log tail for system table
> txnstorage: log tail changes

- pkg/frontend/util.go
- pkg/util/trace/report_statement.go
> bugfix: disableTrace has panic problem

- pkg/logservice/client.go
- pkg/logservice/client_test.go
- pkg/logservice/config.go
- pkg/logservice/errors.go
- pkg/logservice/hakeeper_client.go
- pkg/logservice/rsm.go
- pkg/logservice/service.go
- pkg/logservice/service_bootstrap.go
- pkg/logservice/service_commands.go
- pkg/logservice/service_test.go
- pkg/logservice/shardinfo.go
- pkg/logservice/store.go
- pkg/logservice/store_hakeeper_check.go
- pkg/logservice/store_hakeeper_check_test.go
- pkg/logservice/store_metadata.go
- pkg/logservice/store_test.go
- pkg/taskservice/task_service_cron.go
> replace plog with logger

- test/cases/operator/between_and_operator.sql
- test/result/operator/between_and_operator.result
> Test cases for comparison operator BETWEEN

- pkg/sql/plan/base_binder.go
- pkg/sql/plan/explain/column_prune_test.go
- test/result/explain/explain.result
> [Plan] Don't assign particular column to starcount in binder

- pkg/sql/plan/build_show.go
issue #5196 
add error msg when show table without select db
> add error msg when show table without select db

- pkg/sql/plan/deepcopy.go
issue #
fix bug: forget to set length before copy
> fix deepcopy bug

- pkg/vm/engine/txn/database.go
- pkg/vm/engine/txn/engine.go
- pkg/vm/engine/txn/log_tail.go
- pkg/vm/engine/txn/operations.go
- pkg/vm/engine/txn/request.go
- pkg/vm/engine/txn/shard.go
- pkg/vm/engine/txn/shard_fallback.go
- pkg/vm/engine/txn/shard_hash.go
- pkg/vm/engine/txn/table.go
- pkg/vm/engine/txn/table_reader.go
issue #
txnengine: refactor shard policy
> txnengine: refactor shard policy

- pkg/frontend/codec.go
issue #5060 
Fix panic when decode mysql protocol
> frontend: fix decode mysql codec protocol

- pkg/vm/engine/txn/shard.go
issue #
txnengine: fix allShards, anyShard, NoShard.setShard
> txnengine: fix allShards, anyShard, NoShard.setShard

- pkg/sql/colexec/external/external.go
issue #5046 
fix bug with timestamp type in load process
> fix bug with timestamp type in load process

- pkg/txn/storage/txn/log_tail.go
- pkg/txn/storage/txn/mem_handler.go
- pkg/txn/storage/txn/memtable/bench_test.go
- pkg/txn/storage/txn/memtable/physical_iter.go
- pkg/txn/storage/txn/memtable/physical_row.go
- pkg/txn/storage/txn/memtable/physical_row_test.go
- pkg/txn/storage/txn/memtable/table.go
- pkg/txn/storage/txn/memtable/table_iter.go
- pkg/txn/storage/txn/read_result.go
- pkg/vm/engine/txn/shard_hash.go
> txnstorage: refactor memtable.Table

- pkg/tests/service/cnservice.go
> allocate unused port for Frontend

- pkg/txn/storage/txn/catalog_handler.go
- pkg/txn/storage/txn/mem_handler.go
- pkg/txn/storage/txn/memtable/physical_row.go
- pkg/txn/storage/txn/memtable/physical_row_test.go
- pkg/txn/storage/txn/memtable/table.go
- pkg/txn/storage/txn/memtable/table_test.go
- pkg/txn/storage/txn/memtable/transaction.go
> txnstorage: memtable fixes

- pkg/txn/service/service.go
- pkg/txn/service/service_cn_handler.go
- pkg/txn/service/service_cn_handler_test.go
- pkg/txn/service/service_test.go
- pkg/txn/service/service_testutil.go
> txn: clean zombie txn

- pkg/testutil/testengine/testengine_test.go
- pkg/txn/storage/memorystorage/handler.go
- pkg/txn/storage/memorystorage/storage_txn_client.go
- pkg/txn/storage/memorystorage/write.go
- pkg/vm/engine/memoryengine/database.go
- pkg/vm/engine/memoryengine/engine.go
- pkg/vm/engine/memoryengine/gob.go
- pkg/vm/engine/memoryengine/log_tail.go
- pkg/vm/engine/memoryengine/operation_handler.go
- pkg/vm/engine/memoryengine/operations.go
- pkg/vm/engine/memoryengine/request.go
- pkg/vm/engine/memoryengine/table.go
- pkg/vm/engine/memoryengine/table_reader.go
issue #
memoryengine: remove unnecessary param from DoTxnRequest
testutil: add testengine benchmark
memoryengine: refactor DoTxnRequest
memoryengine: add OperationHandler; allow handle engine methods without payload marshal/unmarshal
> memoryengine: optimize for non-distributed usage

- pkg/fileservice/s3_fs.go
> fileservice: do not make unnecessary mo err in S3FS.Write

- pkg/vm/pipeline/pipeline.go
> Remove debug log

- test/cases/operator/bit_operator.sql
- test/result/operator/bit_operator.result
> Test for Bit Operator

- pkg/txn/storage/memorystorage/memtable/physical_row.go
- pkg/vm/engine/memoryengine/shard_hash.go
issue #
memorystorage: do not update PhysicalRow.LastUpdate in clone
memoryengine: fix getBytesFromPrimaryVectorForHash
> mem engine bug fixes

- pkg/txn/storage/memorystorage/catalog_handler.go
- pkg/txn/storage/memorystorage/mem_handler.go
issue #
memorystorage: replace some moerr.NewNoSuchTable to moerr.NewInternalError
> memorystorage: replace some moerr.NewNoSuchTable to moerr.NewInternalError

- proto/api.proto
issue #
system table changes are sent as same as user tables.
> proto: fix docs of SyncLogTailResp

- pkg/vm/engine/tae/logstore/driver/batchstoredriver/vfile.go
- pkg/vm/engine/tae/logstore/driver/logservicedriver/info.go
- pkg/vm/engine/tae/txn/txnbase/mvccnode.go
issue #
Update panic info, print err in panic info.
> update panic info

- pkg/sql/plan/build_test.go
- pkg/sql/plan/limit_binder.go
- pkg/sql/plan/query_builder.go
issue #5295 
fix limitBinder bug
> fix limitBinder bug

- pkg/container/types/txnts.go
- pkg/txn/storage/memorystorage/batch.go
- pkg/txn/storage/memorystorage/log_tail.go
- pkg/txn/storage/memorystorage/memtable/nullable.go
- pkg/vm/engine/disttae/db.go
- pkg/vm/engine/disttae/hack.go
- pkg/vm/engine/disttae/partition.go
- pkg/vm/engine/disttae/partition_reader.go
- pkg/vm/engine/disttae/table.go
- pkg/vm/engine/disttae/txn.go
- pkg/vm/engine/disttae/types.go
issue #
disttae: implement MVCC for Partition
> disttae: implement MVCC for Partition

- pkg/frontend/session.go
- pkg/sql/plan/build_insert.go
> fix load composite primary key panic bug

- pkg/vm/engine/tae/catalog/model.go
- pkg/vm/engine/tae/containers/batch.go
- pkg/vm/engine/tae/db/db_test.go
- pkg/vm/engine/tae/db/logtail.go
- pkg/vm/engine/tae/moengine/engine.go
- pkg/vm/engine/tae/moengine/types.go
- pkg/vm/engine/tae/rpc/handle.go
issue #4678 
- add logtail handler to tae rpc handle file
- adjust columns of logtail response to keep consistent with memengine
> add tae logtail handler and adjust columns

- pkg/vm/engine/tae/catalog/mock.go
- pkg/vm/engine/tae/catalog/schema.go
- pkg/vm/engine/tae/iface/handle/relation.go
- pkg/vm/engine/tae/iface/txnif/types.go
- pkg/vm/engine/tae/model/codec.go
- pkg/vm/engine/tae/moengine/helper.go
- pkg/vm/engine/tae/moengine/txn_relation.go
- pkg/vm/engine/tae/tables/block.go
- pkg/vm/engine/tae/txn/txnbase/handle.go
- pkg/vm/engine/tae/txn/txnbase/store.go
- pkg/vm/engine/tae/txn/txnimpl/localseg.go
- pkg/vm/engine/tae/txn/txnimpl/relation.go
- pkg/vm/engine/tae/txn/txnimpl/store.go
- pkg/vm/engine/tae/txn/txnimpl/table.go
- pkg/vm/engine/tae/txn/txnimpl/txndb.go
> Code Refactoring

- pkg/sql/plan/function/builtin/unary/time_of_day.go
issue #
fix `unnecessary type arguments infertype args` warning
> fix `unnecessary type arguments infertype args` warning

- pkg/vm/engine/tae/dataio/blockio/block.go
- pkg/vm/engine/tae/db/gc_test.go
- pkg/vm/engine/tae/iface/file/block.go
- pkg/vm/engine/tae/tables/jobs/flushablk.go
- pkg/vm/engine/tae/tables/jobs/flushblk.go
issue #
The writer needs to be released after flushing the block
> Add free writer

- pkg/txn/storage/memorystorage/account.go
- pkg/txn/storage/memorystorage/catalog.go
- pkg/txn/storage/memorystorage/catalog_handler.go
- pkg/txn/storage/memorystorage/log_tail.go
- pkg/txn/storage/memorystorage/mem_handler.go
- pkg/txn/storage/memorystorage/memtable/types.go
issue #
memorystorage: use []byte to store string types
> memorystorage: use []byte to store string types

- pkg/vm/engine/tae/db/gc_test.go
> Fix TestGCTable

- pkg/txn/storage/memorystorage/catalog_handler.go
- pkg/txn/storage/memorystorage/catalog_handler_test.go
- pkg/txn/storage/memorystorage/handler.go
- pkg/txn/storage/memorystorage/log_tail.go
- pkg/txn/storage/memorystorage/mem_handler.go
- pkg/txn/storage/memorystorage/precommit.go
- pkg/txn/storage/memorystorage/read.go
- pkg/txn/storage/memorystorage/storage.go
- pkg/txn/storage/memorystorage/write.go
- pkg/vm/engine/memoryengine/operation_handler.go
- pkg/vm/engine/memoryengine/request.go
issue #
memorystorage: add context param to handler methods
> memorystorage: add context param to handler methods

- CODEOWNERS
> Add catalog owner

- pkg/catalog/types.go
- pkg/cnservice/memory_engine.go
- pkg/dnservice/factory.go
- pkg/dnservice/store_test.go
- pkg/logservice/hakeeper_client.go
- pkg/testutil/testengine/testengine.go
- pkg/txn/storage/memorystorage/account.go
- pkg/txn/storage/memorystorage/catalog_handler.go
- pkg/txn/storage/memorystorage/catalog_handler_test.go
- pkg/txn/storage/memorystorage/frontend_test.go
- pkg/txn/storage/memorystorage/log_tail.go
- pkg/txn/storage/memorystorage/log_tail_test.go
- pkg/txn/storage/memorystorage/mem_handler.go
- pkg/txn/storage/memorystorage/mem_storage.go
- pkg/txn/storage/memorystorage/memtable/physical_row.go
- pkg/txn/storage/memorystorage/memtable/table.go
- pkg/txn/storage/memorystorage/memtable/table_test.go
- pkg/txn/storage/memorystorage/memtable/types.go
- pkg/txn/storage/memorystorage/precommit.go
- pkg/vm/engine/memoryengine/database.go
- pkg/vm/engine/memoryengine/id.go
- pkg/vm/engine/memoryengine/id_test.go
- pkg/vm/engine/memoryengine/operations.go
issue #5417 
memoryengine: add IDGenerator, RandomIDGenerator, HakeeperIDGenerator
memorystorage, memoryengine: add ID param to CreateDatabaseReq, CreateRelationReq
memoryengine: do not send Database.Relations to all shards
memoryengine: add context param to handler methods
> memoryengine, memorystorage: various fixes 

- pkg/common/morpc/codec.go
- pkg/common/morpc/codec_test.go
issue #
morpc missing grow the write buffer,  write big payload will panic.
> morpc: fix codec panic

- pkg/frontend/mysql_cmd_executor.go
> let cmd field list returns empty

- docs/cn/MatrixOne/Contribution-Guide/How-to-Contribute/preparation.md
- docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/case.md
- docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/load-data.md
- docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/operators.md
- docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/operators/flow-control-functions/flow-control-functions-overview.md
- docs/cn/MatrixOne/Release-Notes/v0.5.1.md
- docs/cn/MatrixOne/Tutorial/TPCH-test-with-matrixone.md
- docs/cn/MatrixOne/Tutorial/develop-java-crud-demo.md
- docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/case.md
- docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/load-data.md
- docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/operators.md
- docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/operators/flow-control-functions/flow-control-functions-overview.md
- docs/en/MatrixOne/Release-Notes/v0.5.1.md
> fix the broken links by mkdocs serve

- pkg/catalog/types.go
- pkg/container/batch/batch.go
- pkg/vm/engine/disttae/engine.go
- pkg/vm/engine/disttae/table.go
- pkg/vm/engine/disttae/tools.go
- pkg/vm/engine/disttae/txn.go
- pkg/vm/engine/disttae/types.go
> Add delete logic

- pkg/frontend/mysql_cmd_executor.go
issue #
add prepare/execute log
> add prepare/execute log

- pkg/vm/engine/tae/tables/updates/delchain.go
- pkg/vm/engine/tae/tables/updates/delete.go
issue # https://github.com/matrixorigin/MO-Cloud/issues/74
> add delete view

- pkg/vm/engine/disttae/partition.go
- pkg/vm/engine/disttae/txn.go
> Add default rowid

- pkg/container/hashtable/int64_hash_map.go
- pkg/container/hashtable/string_hash_map.go
> Manage hashtable's memory with mpool

- pkg/catalog/catalog.go
- pkg/catalog/types.go
- pkg/vm/engine/disttae/database.go
- pkg/vm/engine/disttae/engine.go
- pkg/vm/engine/disttae/table.go
- pkg/vm/engine/disttae/txn.go
- pkg/vm/engine/disttae/types.go
> Adding the processing of block list of table

- pkg/cnservice/memory_engine.go
- pkg/testutil/testengine/testengine.go
- pkg/txn/storage/memorystorage/mem_handler.go
- pkg/txn/storage/memorystorage/storage_txn_client.go
- pkg/txn/storage/memorystorage/storage_txn_client_test.go
- pkg/vm/engine/memoryengine/database.go
- pkg/vm/engine/memoryengine/engine.go
- pkg/vm/engine/memoryengine/id.go
- pkg/vm/engine/memoryengine/operation_handler.go
- pkg/vm/engine/memoryengine/request.go
- pkg/vm/engine/memoryengine/table_reader.go
issue #
memoryengine: for system table, create iter in single shard in reader
memorystorage: support multiple storages in StorageTxnClient
memorystorage: add another DN to TestStorageTxnClient
memorystorage: fix TestStorageTxnClient
memorystorage: check table existence in MemoryHandler.HandleDelete
memorystorage: generate database and table id in CN
memorystorage: add testStorageTxnClient
> memoryengine bug fixes

- pkg/vm/engine/tae/tables/block.go
- pkg/vm/engine/tae/tables/node.go
> fix a small bug

- pkg/catalog/types.go
- pkg/container/batch/batch.go
- pkg/sql/plan/build_show.go
- pkg/sql/plan/mock.go
- pkg/txn/storage/memorystorage/catalog.go
- pkg/vm/engine/disttae/database.go
- pkg/vm/engine/disttae/db.go
- pkg/vm/engine/disttae/table.go
- pkg/vm/engine/disttae/tools.go
issue #3931
memengine: Fix the bug of memorystorage(return the true defaultexpr)
disttae: Adapting the logic of tae
> Fix the bug of memorystorage(return the true defaultexpr)

- pkg/sql/colexec/deletion/deletion.go
- pkg/sql/colexec/insert/insert.go
- pkg/sql/colexec/update/update.go
- pkg/vm/engine/disttae/table.go
> Fix the bug of insert/delete/update

- README.md
- docs/cn/MatrixOne/FAQs/deployment-faqs.md
- docs/en/MatrixOne/FAQs/deployment-faqs.md
- docs/en/MatrixOne/Get-Started/install-standalone-matrixone.md
- docs/en/MatrixOne/Tutorial/develop-java-crud-demo.md
> fix content format bug

- pkg/vm/engine/tae/compute/compute.go
- pkg/vm/engine/tae/compute/compute_test.go
- pkg/vm/engine/tae/tables/txnentries/mergeblocks.go
> refactor mergeblocks

- pkg/vm/engine/tae/logstore/driver/entry/entry.go
- pkg/vm/engine/tae/logstore/driver/logservicedriver/append.go
- pkg/vm/engine/tae/logstore/driver/logservicedriver/clientpool.go
- pkg/vm/engine/tae/logstore/driver/logservicedriver/driver.go
- pkg/vm/engine/tae/logstore/driver/logservicedriver/entry.go
- pkg/vm/engine/tae/logstore/driver/logservicedriver/info.go
- pkg/vm/engine/tae/logstore/driver/logservicedriver/replay.go
- pkg/vm/engine/tae/logstore/driver/logservicedriver/truncate.go
- pkg/vm/engine/tae/logstore/store/checkpoint.go
issue #
1. Fix logstore replay
2. Free entries after replay
> fix logservicedriver replay

- test/cases/function/left_function.sql
- test/result/function/left_function.result
> test for left function

- go.mod
- go.sum
issue #
Replace lni/dragonboat with matrixorigin/dragonboat.
> replace lni/dragonboat with matrixorigin/dragonboat.

- pkg/catalog/catalog.go
- pkg/catalog/catalog_test.go
- pkg/catalog/types.go
- pkg/vm/engine/tae/logtail/handle.go
- pkg/vm/engine/tae/logtail/types.go
issue #
add block meta schema to catalog package
> add blk meta schema

- .github/mergify.yml
- .github/workflows/ci.yml
> Ci upgrade

- .github/mergify.yml
- .github/workflows/ci.yml
2. change x86 runner from github host to self-host
issue #
1. remove unnecessary upload data
2. change x86 runner from github host to self-host
> 1. remove unnecessary upload data

- .github/workflows/ci.yml
> set locale before bvt start in bvt-linux-x86

- pkg/frontend/routine_manager.go
- pkg/sql/plan/function/builtin/multi/external_test.go
> Fix a race.

- etc/launch-tae-logservice/cn1.toml
- etc/launch-tae-logservice/dn1.toml
- etc/launch-tae-logservice/log1.toml
- etc/launch-tae-logservice/log2.toml
- etc/launch-tae-logservice/log3.toml
issue #
BVT takes a long time after using log-service, which has 3 replicas. So change to single replica to reduce the test time.
> BVT uses single logservice to reduce test time.

- pkg/vm/engine/disttae/tools.go
- pkg/vm/engine/disttae/types.go
> Reorder schema with column number

- pkg/vm/engine/tae/containers/batch.go
- pkg/vm/engine/tae/containers/types.go
- pkg/vm/engine/tae/containers/vecbase.go
- pkg/vm/engine/tae/containers/vector.go
- pkg/vm/engine/tae/containers/vecview.go
- pkg/vm/engine/tae/containers/vecwindow.go
issue #
Implement String and PPString for tae batch
> implement String for batch

- pkg/catalog/catalog.go
- pkg/catalog/types.go
- pkg/vm/engine/tae/db/db_test.go
- pkg/vm/engine/tae/logtail/handle.go
issue #
change block meta schema and send only block meta with metaloc
> fix block meta schema

- pkg/container/types/date.go
- pkg/container/types/datetime.go
> Support YYYY/MM/DD format for date/datetime/timestamp

- pkg/sql/colexec/group/group.go
- test/cases/function/func_aggr_bitwise.test
- test/result/function/func_aggr_bitwise.result
issue #5638 
fix bug: free mpool incorrect
> fix bug: free mpool incorrect

- pkg/sql/colexec/external/external.go
- test/cases/load_data/load_data.result
- test/cases/load_data/load_data.sql
- test/cases/load_data/load_data_jsonline.result
- test/cases/load_data/load_data_jsonline.test
- test/resources/load_data/uuid.csv
issue #5434 
support uuid type in load data
> support uuid type in load data

- pkg/txn/storage/memorystorage/memtable/index_iter.go
- pkg/txn/storage/memorystorage/memtable/table.go
- pkg/vm/engine/disttae/db.go
- pkg/vm/engine/disttae/logtail.go
- pkg/vm/engine/disttae/partition.go
- pkg/vm/engine/disttae/types.go
issue #
disttae: check primary index in Partition.Insert
memtable: add IndexIter
disttae: add Partition.IterRowIDsByBlockID
>  disttae: add primary key and block id index 

- pkg/vm/engine/disttae/database.go
- pkg/vm/engine/disttae/tools.go
- pkg/vm/engine/disttae/txn.go
- pkg/vm/engine/disttae/types.go
- pkg/vm/engine/disttae/util.go
issue #3931
fix some bug of disttae
> fix some bug of disttae

- pkg/txn/storage/memorystorage/memtable/index_iter.go
- pkg/txn/storage/memorystorage/memtable/ordered.go
- pkg/txn/storage/memorystorage/memtable/table.go
- pkg/txn/storage/memorystorage/memtable/tuple.go
- pkg/txn/storage/memorystorage/memtable/tuple_test.go
- pkg/vm/engine/disttae/partition.go
- pkg/vm/engine/disttae/partition_reader.go
issue #
memtable: add Min, Max
memtable: add min, max params to IndexIter
memtable: add Table.Upsert
> disttae: add Partition.IterDeletedRowIDs

- pkg/vm/engine/tae/rpc/handle.go
issue #
Get datatabase first and then drop
> fix bug in handle

- etc/launch-tae-CN-tae-DN/dn.toml
- pkg/vm/engine/tae/moengine/database.go
- pkg/vm/engine/tae/moengine/helper.go
- pkg/vm/engine/tae/rpc/rpc_test.go
issue #
- new defsToSchema
- cn/dn without flushing
> New defs to schema

- pkg/txn/storage/memorystorage/catalog.go
- pkg/txn/storage/memorystorage/data.go
- pkg/txn/storage/memorystorage/log_tail.go
- pkg/txn/storage/memorystorage/mem_handler.go
- pkg/txn/storage/memorystorage/memtable/index_iter.go
- pkg/txn/storage/memorystorage/memtable/table.go
- pkg/txn/storage/memorystorage/memtable/table_test.go
- pkg/txn/storage/memorystorage/memtable/transaction.go
- pkg/txn/storage/memorystorage/storage_test.go
- pkg/vm/engine/disttae/partition.go
issue #
memtable: add Table.FilterVersions; add error return to AbortTx
memtable: add ReverseIndexEntry; delete indexes in Table.FilterVersion
memtable: remove IndexEntry.Value
memtable: add unique index
memtable: check unique indexes in Table.Insert,Update,Upsert
memtable: check unique indexes in Table.CommitTx
memtable: add TestUniqueIndex
> various memtable fixes

- pkg/vm/engine/disttae/db.go
- pkg/vm/engine/disttae/engine.go
- pkg/vm/engine/disttae/logtail.go
- pkg/vm/engine/disttae/partition.go
- pkg/vm/engine/disttae/table.go
- pkg/vm/engine/disttae/types.go
> Add option for primary key constraint detection

- pkg/vm/engine/disttae/util.go
- pkg/vm/engine/disttae/util_test.go
issue #3931
add getNonIntPkValueByExpr function
> add some util function for disttae

- pkg/sql/colexec/agg/agg.go
- pkg/sql/colexec/agg/distagg.go
issue #
fix a bug while grows the Agg structure.
> fix an Agg' Grows method bug

- pkg/vm/engine/tae/rpc/handle.go
> fix accessinfo in precommit

- pkg/vm/engine/tae/moengine/helper.go
> record comment in schema

- pkg/vm/engine/tae/db/db_test.go
- pkg/vm/engine/tae/logtail/reader.go
> do not send sys tables logtail when launching

- pkg/vm/engine/tae/common/mpool.go
> fix batchstore restart

- pkg/vm/engine/disttae/database.go
- pkg/vm/engine/disttae/engine.go
- pkg/vm/engine/disttae/txn.go
> disttae: add Transaction.allocateID

- pkg/frontend/session.go
> Fix "Execution of sql error, all subsequent sql execution fails"

- pkg/common/morpc/server.go
issue #
fix data race with TxnResponse
> txn: fix data race with TxnResponse

- pkg/config/configuration.go
- pkg/frontend/routine.go
issue #
Add session timeout. The default value is 10minutes.
> add session timeout 

- pkg/sql/plan/flatten_subquery.go
- pkg/sql/plan/utils.go
> Make tuple comparison logic reusable

- pkg/util/trace/schema.go
- test/cases/log/column_error.sql
- test/cases/log/column_log.sql
- test/cases/log/column_metric.sql
- test/cases/log/column_span.sql
- test/cases/log/column_stmt.sql
- test/result/log/column_error.result
- test/result/log/column_log.result
- test/result/log/column_metric.result
- test/result/log/column_span.result
- test/result/log/column_stmt.result
issue #
add bvt case, help to check column name in metric and log tables.
> add bvt check metric/log table column name

- test/distributed/cases/dml/delete/delete.test
- test/distributed/cases/dml/insert/insert.test
- test/distributed/cases/dml/update/update.test
- test/distributed/cases/table/drop_table.test
> disable unique key related bvt in cn-dn

- pkg/vm/engine/disttae/engine.go
- [] Code Refactoring
issue #5856
> When dropping the database, drop all tables are deleted along with it

- pkg/container/vector/tools.go
- pkg/sql/colexec/insert/insert.go
issue #5834 #5772
fix bug: make sure vector.data is not null when insert rows
> fix bug: make sure vector.data is not null when insert rows

- test/distributed/cases/dml/select/minus.result
- test/distributed/cases/dtype/char.test
- test/distributed/result/dtype/char.result
- test/distributed/result/function/func_cast.result
issue #5874 #5875 #5877
update distributed test case
> update distributed test case

- pkg/catalog/catalog.go
- pkg/catalog/types.go
- pkg/vm/engine/tae/logtail/handle.go
> add sorted in blk meta

- test/distributed/result/database/system_table.result
> fix type diff

- pkg/common/bitmap/bitmap.go
issue #5901
fix bitmap contains fun bug
> fix bitmap contains fun bug

- etc/launch-flush-tae-CN-tae-DN/cn.toml
- etc/launch-flush-tae-CN-tae-DN/dn.toml
- etc/launch-flush-tae-CN-tae-DN/log.toml
- etc/launch-mem-CN-mem-DN/cn.toml
- etc/launch-mem-CN-mem-DN/cn2.toml
- etc/launch-mem-CN-mem-DN/dn.toml
- etc/launch-mem-CN-mem-DN/log.toml
- etc/launch-tae-CN-mem-DN/cn.toml
- etc/launch-tae-CN-mem-DN/dn.toml
- etc/launch-tae-CN-mem-DN/log.toml
- etc/launch-tae-CN-tae-DN/cn.toml
- etc/launch-tae-CN-tae-DN/dn.toml
- etc/launch-tae-CN-tae-DN/log.toml
- etc/launch-tae-logservice/cn1.toml
- etc/launch-tae-logservice/dn1.toml
- etc/launch-tae-logservice/log1.toml
- etc/launch-tae-logservice/log2.toml
- etc/launch-tae-logservice/log3.toml
- etc/launch/cn1.toml
- etc/launch/dn1.toml
- etc/launch/log1.toml
- etc/launch/log2.toml
- etc/launch/log3.toml
issue #
对齐 luanch 配置中的 ETL 的数据目录 => `mo-data/local/etl`
> modify etc/launch*/* ETL's data-dir = mo-data/local/etl

- pkg/txn/storage/memorystorage/memtable/index_iter.go
- pkg/txn/storage/memorystorage/memtable/table.go
- pkg/vm/engine/disttae/partition.go
> disttae: replace index_BlockID and index_Time_OP with index_BlockID_Time_OP

- pkg/txn/storage/memorystorage/memtable/types.go
- pkg/vm/engine/disttae/partition.go
> disttae: remove Op type, use uint8 instead

- pkg/vm/engine/tae/mergesort/varchar/func.go
issue #
construct a sorted vector and copy to the original vector to get better sort performance
> fix vec sort

- pkg/frontend/session.go
- pkg/vm/engine/disttae/db.go
- pkg/vm/engine/disttae/partition.go
- pkg/vm/engine/disttae/tools.go
- pkg/vm/engine/disttae/txn.go
- pkg/vm/engine/disttae/types.go
> Add hash index for memtable

- pkg/frontend/session.go
- pkg/vm/engine/disttae/db.go
- pkg/vm/engine/disttae/partition.go
- pkg/vm/engine/disttae/tools.go
- pkg/vm/engine/disttae/txn.go
- pkg/vm/engine/disttae/types.go
This reverts commit f739455f65c78d0beef20c747ba5f14be7b4a240.
issue #
> Revert "Add hash index for memtable (#5962)"

- test/distributed/result/database/create_database.result
- test/distributed/result/database/drop_database.result
- test/distributed/result/database/new_database.result
> sync cn-dn bvt result

- .github/workflows/ci.yml
- .github/workflows/e2e.yml
- etc/launch-tae-CN-tae-DN/cn.toml
- optools/run_bvt.sh
issue #
update e2e ci wo wait mo system init task completed
> ci: update e2e config

- go.mod
- go.sum
issue #
fix debug log write with error log
> log: fix error log

- pkg/vm/engine/tae/dataio/blockio/read.go
> fix rowid converting in BlockRead

- pkg/fileservice/file_service_test.go
- pkg/fileservice/local_fs.go
> fileservice: fix file sizes in LocalFS.List

- pkg/taskservice/mysql_task_storage.go
- pkg/tests/service/task_test.go
issue #
Currently, `select exists(select * from %s.sys_async_task where task_metadata_id=?)` is invalid.
So replace it with `select count(task_metadata_id) from %s.sys_async_task where task_metadata_id=?`.
Add an integrated test for cron task.
> fix cron sql syntax error & add integrated test for cron task

- optools/run_ut.sh
- pkg/tests/service/service_test.go
- pkg/tests/service/task_test.go
- pkg/tests/txn/cluster_basic_test.go
issue #
skip all cluster testing in short mode.
> tests: skip all cluster test in short mode

- etc/launch-flush-tae-CN-tae-DN/dn.toml
> add log-backend to flush

- pkg/sql/colexec/auto_incr.go
- pkg/vm/engine/disttae/logtail.go
- pkg/vm/engine/disttae/partition.go
- pkg/vm/engine/disttae/reader.go
- pkg/vm/engine/disttae/tools.go
> Fix some bug of cn

- pkg/vm/engine/tae/tables/block.go
- pkg/vm/engine/tae/txn/txnbase/mvccchain.go
issue #
There is a small probability that a compact panic will occur during TestDelete3.
> fix small probability ut panic problem

- pkg/vm/engine/disttae/tools.go
> Fix the wrong blockid setting caused by a pen error

- pkg/util/metric/m_sql.go
issue #
correct metric type name of update and delete
> correct type of update and delete

- .gitignore
- Makefile
add mo-dump to gitignore
issue #
> move dump out of default build

- pkg/util/export/merge.go
- pkg/util/export/merge_test.go
- pkg/util/export/table.go
- pkg/util/export/table_test.go
- pkg/util/export/type.go
issue #
improve merge.go ut recover up to 80%
> Ut cover merge 80%

- pkg/fileservice/file_service_test.go
- pkg/fileservice/path.go
- pkg/fileservice/s3_fs.go
> fileservice: trim leading / in ParsePath; fix S3FS.List

- .github/workflows/robot.yml
> add projects milestone

- .gitignore
> git ignore tester-log.

- pkg/cnservice/server.go
- pkg/cnservice/server_heartbeat.go
- pkg/cnservice/server_task.go
- pkg/logutil/action.go
- pkg/taskservice/task_service_holder.go
- pkg/tests/service/service.go
issue #
Add some close log to help debug
> log: add some close log

- pkg/cnservice/server_task.go
issue #
fix deadlock in task executor
> cnservice: fix deadlock in task executor

- .dockerignore
Signed-off-by: wanglei <wanglei4687@gmail.com>
issue #
Ignore bvt generate files. I checked with @tianyahui-python.
> fix: docker build ignore bvt generate files

- pkg/container/nulls/nulls.go
- pkg/sql/colexec/mergeorder/order.go
- pkg/sql/compile/compile.go
> refactor mergeOrder operator

- README.md
- README_CN.md
- docs/cn/MatrixOne/Develop/export-data/backup-restore-matrixone-with_modump.md
- docs/cn/MatrixOne/Develop/import-data/0.6-bulk-load/load-s3.md
- docs/cn/MatrixOne/Get-Started/connect-to-matrixone-server.md
- docs/cn/MatrixOne/Reference/Limitations/mo-partition-support.md
- docs/cn/MatrixOne/Tutorial/connect_mo_with_orm.md
- docs/cn/MatrixOne/Tutorial/springboot-mybatis-crud-demo.md
- docs/en/MatrixOne/Develop/0.6-read-data/subquery.md
- docs/en/MatrixOne/Develop/export-data/backup-restore-matrixone-with_modump.md
- docs/en/MatrixOne/Develop/import-data/0.6-bulk-load/load-jsonline.md
- docs/en/MatrixOne/Develop/import-data/0.6-bulk-load/load-s3.md
- docs/en/MatrixOne/Get-Started/connect-to-matrixone-server.md
- docs/en/MatrixOne/Reference/Limitations/mo-partition-support.md
- docs/en/MatrixOne/Tutorial/connect_mo_with_orm.md
【New docs】
- Develop/export-data/backup-restore-matrixone-with_modump.md
- Develop/import-data/0.6-bulk-load/load-s3.md
- Reference/Limitations/mo-partition-support.md
- Tutorial/connect_mo_with_orm.md
issue #
> add load data docs and tutorial docs

- pkg/container/types/bool.go
- pkg/sql/plan/function/operator/cast.go
- test/cases/dtype/text_1.sql
- test/distributed/cases/dtype/text_1.sql
- test/distributed/result/dtype/text_1.result
- test/distributed/result/operator/is_not_operator.result
- test/result/dtype/text_1.result
- test/result/operator/is_not_operator.result
issue #4636
fix a bug when string type cast to bool type
> [Bug]: text type cast bool type, Not up to expectations. #4636

- pkg/sql/colexec/auto_incr.go
> Add a loop for auto incr value.

- pkg/common/morpc/codec.go
- pkg/txn/rpc/cfg.go
- pkg/txn/rpc/sender.go
- pkg/txn/rpc/server.go
issue #
Modify default max message size to 100MB
> rpc: modify  deafult max message size to 100MB

- pkg/fileservice/s3_fs.go
> fileservice: set a background context if passed argument is nil

- .github/workflows/e2e.yml
issue #
get rid of debug binary to expedite e
2e ci
> Sukki37 patch 10

- pkg/sql/colexec/external/external.go
- pkg/sql/colexec/external/types.go
> set load batch size

- pkg/sql/colexec/join/join.go
- pkg/sql/colexec/semi/join.go
> add more a nil check to avoid panic when clean up the pipeline

- pkg/pb/logservice/logservice.go
- pkg/tests/service/service_test.go
- pkg/tests/service/task_test.go
- pkg/tests/txn/cluster_basic_test.go
issue #6295 
Enable leak test in integrated tests.
Fix LogString nil pointer error.(#6295)
> Fix log string

- etc/launch-tae-multi-CN-tae-DN/cn1.toml
- etc/launch-tae-multi-CN-tae-DN/cn2.toml
- etc/launch-tae-multi-CN-tae-DN/dn.toml
- etc/launch-tae-multi-CN-tae-DN/launch.toml
- etc/launch-tae-multi-CN-tae-DN/log.toml
issue #
Add a multi-CN launch file. It will launch 2cn+1dn+1log's mo cluster.
> cfg: add multi cn launch config

- pkg/logservice/store_metadata.go
- pkg/logservice/truncation.go
issue #
Fix a data in logservice.
> fix a data race in logservice.

- pkg/sql/plan/explain/explain_expr.go
- pkg/sql/plan/explain/explain_test.go
issue ##6389
explain supports system variables and user variables
> Explain bug

- pkg/hakeeper/checkers/coordinator.go
- pkg/hakeeper/checkers/dnservice/parse.go
issue #
modify log level in hakeeper.
> modify log level in hakeeper

- pkg/frontend/variables.go
> add variable performance_schema to support mybatis

- pkg/frontend/util.go
- test/cases/set/set_operator.test
- test/distributed/cases/set/set_operator.test
- test/distributed/result/set/set_operator.result
- test/result/set/set_operator.result
> add date type for variable

- pkg/frontend/variables.go
- pkg/sql/compile/cnserviceDriver.go
- pkg/sql/compile/scope.go
- pkg/sql/compile/scope_test.go
- pkg/sql/compile/types.go
issue #6330 #6329
Since the metadata is lost in the remote run, an identifier is needed to indicate that it is a remote run. add this identifier to ensure correctness.
> Add the missing remote flg

- pkg/frontend/util.go
- pkg/frontend/variables.go
- pkg/hakeeper/checkers/coordinator.go
- pkg/hakeeper/checkers/dnservice/parse.go
- pkg/sql/compile/cnserviceDriver.go
- pkg/sql/compile/scope.go
- pkg/sql/compile/scope_test.go
- pkg/sql/compile/types.go
- pkg/vm/engine/tae/catalog/catalog.go
- pkg/vm/engine/tae/catalog/schema.go
- pkg/vm/engine/tae/db/db_test.go
- pkg/vm/engine/tae/db/replay_test.go
- pkg/vm/engine/tae/logstore/driver/logservicedriver/replay.go
- pkg/vm/engine/tae/tables/block.go
- pkg/vm/engine/tae/txn/txnimpl/sysblock.go
- test/cases/set/set_operator.test
- test/distributed/cases/set/set_operator.test
- test/distributed/result/set/set_operator.result
- test/result/set/set_operator.result
issue #6366 
1. fix replay in logservicedriver
2. fix marshal table expr
3. fix replay catalog id
4. fix load delta deletes
5. fix data race when replay index, not replay index in compacted
6. fix replay checkpoint, update dirty tree when replay
> fix checkpoint and replay bugs and add ut

- pkg/taskservice/task_service_holder_test.go
- pkg/txn/rpc/sender_test.go
issue #6404 
Fix some goroutine leak in some tests
> fix goroutine leak in tests

- optools/bvt_ut/entrypoint.sh
Signed-off-by: wanglei <wanglei4687@gmail.com>
issue #
`make ci` should exit when error occurred
use `test/distributed/cases` as default test cases
> fix: make ci

- pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
- pkg/sql/parsers/tree/show.go
> fix format show variable like

- pkg/fileservice/local_etl_fs.go
- pkg/fileservice/local_etl_fs_test.go
- pkg/fileservice/local_fs.go
issue #
fileservice: fix error reporting of LocalETLFS.Read, LocalFS.read
> fileservice: add symlink to dir test

- pkg/cnservice/server.go
- pkg/sql/compile/compile.go
- pkg/sql/compile/scope.go
- pkg/sql/compile/types.go
issue #6324
Added address determination to prevent going remote run on the same machine as well.
> Avoid local remote run

- pkg/sql/compile/compile.go
- pkg/vm/engine/disttae/table.go
> Fix the wrong step calculation code

- pkg/vm/engine/disttae/table.go
> fix compute step bug

- pkg/config/configuration.go
- pkg/frontend/mysql_cmd_executor.go
- pkg/frontend/mysql_protocol.go
> [Feature Request]: make MO version configurable #6479

- pkg/vm/engine/tae/db/base_test.go
- pkg/vm/engine/tae/db/db_test.go
> update ut, skip delete3

- pkg/vm/engine/tae/logstore/driver/logservicedriver/options.go
> change default timeout of append/read op of logservice client

- pkg/vm/engine/tae/logtail/handle.go
issue #
use the last mvcc node as the newest one, otherwise, logtail might give memory data of compacted block
> fix wrong use of latest block node

- pkg/cnservice/server.go
- pkg/frontend/mysql_cmd_executor.go
- pkg/sql/compile/compile.go
- pkg/sql/compile/compile_test.go
- pkg/sql/compile/scope.go
- pkg/sql/compile/scope_test.go
- pkg/sql/compile/types.go
> Removes dependencies on global variables

- pkg/common/morpc/codec.go
- pkg/common/morpc/codec_header.go
issue #6437 #6438 #6488 
Incorrect data encoding of PayloadMessage, leads to various decoding errors. Taking this opportunity, the codec code implementation was refactored
> morpc: incorrect data encoding of PayloadMessage

- pkg/vm/engine/tae/db/db_test.go
- pkg/vm/engine/tae/iface/data/table.go
- pkg/vm/engine/tae/iface/txnif/types.go
- pkg/vm/engine/tae/model/transfer.go
- pkg/vm/engine/tae/tables/block.go
- pkg/vm/engine/tae/tables/handle.go
- pkg/vm/engine/tae/tables/indexwrapper/mutindex.go
- pkg/vm/engine/tae/tables/updates/delchain.go
- pkg/vm/engine/tae/tables/updates/mvcc.go
- pkg/vm/engine/tae/testutils/config/options.go
- pkg/vm/engine/tae/txn/txnbase/mvccnode.go
- pkg/vm/engine/tae/txn/txnbase/mvccslice.go
- pkg/vm/engine/tae/txn/txnimpl/table.go
issue #
1. add some predefined internal error to avoid being traced
2. add some ut 
3. fix bugs in GetActiveRow, which is used by `DN` only
> change some error and add ut

- pkg/common/hashmap/joinmap.go
- pkg/common/hashmap/types.go
> Fix memory leak of joinmap

- pkg/dnservice/cfg.go
issue #
Update default log backend to logservice
> dnservice: update default logbackend to logservice

- pkg/vm/engine/tae/logstore/driver/logservicedriver/appender.go
issue #
1. Use resized record in append.
> fix append, use resized record

- pkg/vm/engine/tae/db/db_test.go
> skip Delete3 and Update

- test/cases/expression/set_variable.result
- test/cases/expression/set_variable.sql
- test/distributed/cases/expression/set_variable.result
- test/distributed/cases/expression/set_variable.sql
> remove some tag

- pkg/config/configuration.go
- pkg/dnservice/store_heartbeat.go
- pkg/hakeeper/operator/controller.go
- pkg/logservice/service_commands.go
- pkg/pb/logservice/logservice.go
- pkg/tests/service/service.go
- pkg/tests/service/task_test.go
issue #
Fix data race in Config.
Implement Log/DN store shutdown.
Check if schedule command is nil.
> fix schedule command is nil & data race in config

- pkg/util/sysview/sysview.go
- test/distributed/result/database/system_table.result
- test/distributed/result/database/system_variables.result
- test/result/database/system_table.result
- test/result/database/system_variables.result
issue #6570
Modify the definition of schemata view，delete NULL type field and adopt empty string
> modify view definition of schemata

- pkg/sql/plan/function/builtin/unary/load_file.go
> fix : blob load invalid path reported panic(#6304)

- pkg/vm/engine/disttae/logtail.go
issue #
Add context argument in `getLogTail`.
Fix tiny bug for error check.
> add ctx argument in getLogTail

- pkg/container/vector/vector.go
- pkg/container/vector/vector_test.go
- pkg/sql/colexec/left/join.go
- pkg/sql/compile/scope.go
> fix vector.UnionOne bug which didn't consider scalarVector.

- pkg/vm/engine/tae/common/print.go
- pkg/vm/engine/tae/db/db_test.go
- pkg/vm/engine/tae/logtail/handle.go
- pkg/vm/engine/tae/logtail/tools.go
- pkg/vm/engine/tae/moengine/helper.go
- pkg/vm/engine/tae/rpc/handle.go
issue #
For better debug experience:
- record precommit operation digest
- record first 3 rows data in logtail and precommit at debug level
> add human readable log for logtail and precommit

- .github/workflows/ci.yml
- .github/workflows/e2e.yml
- .github/workflows/issue_to_project.yml
- .github/workflows/ut_pr.yml
issue #
change ADD_TO_PROJECT_PAT to TOKEN_ACTION in issue_to_project.yaml
> CI: change ADD_TO_PROJECT_PAT to TOKEN_ACTION

- pkg/util/export/type_test.go
issue #
bugfix ut with data race problem
> bugfix ut with data race problem

- pkg/vm/engine/tae/dataio/blockio/read.go
> Prepare Rowid data using disttae's mpool

- pkg/vm/engine/tae/dataio/blockio/read.go
issue #
close vector when failed
> fix close in blockread

- etc/quickstart/launch.toml
issue #6690 
Add quickstart config
> config: add quickstart launch

- pkg/fileservice/s3_fs.go
> fileservice: set S3 client log mode

- pkg/tests/service/service_test.go
- pkg/tests/service/task_test.go
- pkg/tests/txn/cluster_basic_test.go
> Tests: defers closes before starts

- pkg/common/mpool/freelist.go
- pkg/common/mpool/mpool_test.go
- pkg/vm/engine/tae/dataio/blockio/read.go
> Refactoring freelist of mpool

- pkg/sql/parsers/dialect/mysql/mysql_sql.go
- pkg/sql/parsers/dialect/mysql/mysql_sql.y
- test/cases/dtype/text.test
- test/distributed/result/database/system_table.result
- test/distributed/result/database/system_variables.result
- test/result/database/system_table.result
- test/result/database/system_variables.result
- test/result/dtype/text.result
> treat tiny_text,medinum_text,long_text as text

- etc/dn-minimal-s3-test.toml
- etc/launch-tae-compose/config/cn-0.toml
- etc/launch-tae-compose/config/cn-1.toml
- etc/launch-tae-compose/config/dn.toml
- etc/launch-tae-compose/config/log.toml
- pkg/fileservice/cache.go
- pkg/fileservice/config.go
> fileservice: add CacheConfig

- pkg/common/mpool/freelist.go
> Remove dead code of mpool's freelist

- pkg/frontend/mysql_cmd_executor.go
- pkg/sql/parsers/dialect/mysql/mysql_lexer.go
- test/cases/dml/select/select.test
- test/distributed/cases/dml/select/select.test
- test/distributed/result/dml/select/select.result
- test/result/dml/select/select.result
> fix empty query

- pkg/sql/plan/query_builder.go
- pkg/sql/plan/utils.go
> [Bug]: a simple query : mo be suspended by local Machine, and killed by local System 2 min later #6694

- pkg/pb/txn/txn.go
- pkg/txn/util/log.go
issue #6700 
Fix data race in log.
> txn: fix data race

- .github/workflows/e2e-compose.yml
Signed-off-by: wanglei4687 <wanglei4687@gmail.com>
issue #
> feat: add compose test for release branch

- etc/dn-minimal-s3-test.toml
- etc/launch-tae-compose/config/cn-0.toml
- etc/launch-tae-compose/config/cn-1.toml
- etc/launch-tae-compose/config/dn.toml
- etc/launch-tae-compose/config/log.toml
- pkg/fileservice/cache.go
- pkg/fileservice/config.go
This reverts commit 479c3c05f78a70f8269621c4f898e38fad2958d5.
issue #
> Revert "fileservice: add CacheConfig (#6696)"

- pkg/vm/engine/tae/logstore/driver/logservicedriver/driver.go
- pkg/vm/engine/tae/logstore/driver/logservicedriver/info.go
- pkg/vm/engine/tae/logstore/driver/logservicedriver/read.go
issue #
not drops uc records in replay, clean records after replay
> fix read uc in replay

- pkg/vm/engine/tae/dataio/blockio/reader.go
- pkg/vm/engine/tae/db/checkpoint/entry.go
- pkg/vm/engine/tae/db/checkpoint/replay.go
- pkg/vm/engine/tae/logtail/handle.go
- pkg/vm/engine/tae/logtail/utils.go
> read checkpoint entries concurrently

- pkg/vm/engine/tae/dataio/blockio/read.go
> fix read close 

- pkg/common/moerr/error.go
- pkg/hakeeper/task/task_scheduler.go
- pkg/logservice/service_wrap.go
- pkg/taskservice/mysql_task_storage.go
- pkg/taskservice/task_service_holder.go
- pkg/tests/service/service.go
issue #
Fix some typos.
Create initial tasks repeatedly when error occurs in integration test.
> create init tasks repeatedly when error occurs

- pkg/objectio/reader.go
- pkg/objectio/writer_test.go
issue #
This will save unmarshal or decompress costs.
> objectio: cache unmarshaled *Block or decompressed bytes instead of []byte

- pkg/vm/engine/tae/tables/jobs/compactblk.go
> fix delete transfer mapping for 0.6

- etc/dn-minimal-s3-test.toml
- etc/launch-tae-compose/config/cn-0.toml
- etc/launch-tae-compose/config/cn-1.toml
- etc/launch-tae-compose/config/dn.toml
- etc/launch-tae-compose/config/log.toml
- pkg/fileservice/cache.go
- pkg/fileservice/config.go
- pkg/objectio/column.go
- pkg/objectio/reader.go
- pkg/objectio/writer_test.go
- pkg/vm/engine/tae/dataio/blockio/read.go
- pkg/vm/engine/tae/dataio/blockio/reader.go
- pkg/vm/engine/tae/db/checkpoint/replay.go
- pkg/vm/engine/tae/tables/evictable/coldata.go
- pkg/vm/engine/tae/tables/evictable/deltadata.go
> Use copy to read objectio's Object0.6

- pkg/hakeeper/checkers/coordinator.go
- pkg/hakeeper/checkers/dnservice/check.go
- pkg/logservice/option.go
- pkg/taskservice/mysql_task_storage.go
- pkg/tests/service/options.go
- pkg/tests/service/service.go
> modify log level in integration tests

- pkg/sql/compile/compile.go
- pkg/sql/compile/types.go
> Adjust the parallelism of the pipeline according to the cost

- pkg/hakeeper/task/task_scheduler.go
- pkg/logservice/store_hakeeper_check.go
- pkg/logservice/store_hakeeper_check_test.go
- pkg/taskservice/mysql_task_storage.go
issue #
Refactor task scheduler in hakeeper.
> hakeeper: refactor task scheduler in hakeeper

- pkg/frontend/mysql_cmd_executor.go
- pkg/frontend/variables.go
- pkg/sql/colexec/expr_eval.go
- test/cases/database/system_variables.sql
- test/distributed/cases/database/system_variables.sql
- test/distributed/result/database/system_variables.result
- test/result/database/system_variables.result
issue #6743 
Fix 6743: set system variables default return error
> Fix 6743: set system variables return error

- pkg/fileservice/lru.go
- pkg/fileservice/mem_cache.go
> Fix fileservice lru memory leak bug

- pkg/fileservice/file_service.go
- pkg/fileservice/local_fs.go
- pkg/fileservice/mem_cache.go
- pkg/fileservice/mem_cache_test.go
- pkg/fileservice/s3_fs.go
> fileservice: do not set already cached object in MemCache

- pkg/sql/compile/cnserviceDriver.go
- pkg/sql/compile/compile.go
- pkg/sql/compile/operator.go
- pkg/sql/compile/scope.go
- pkg/sql/compile/types.go
- pkg/sql/plan/deepcopy.go
- pkg/sql/plan/types.go
issue https://github.com/matrixorigin/MO-Cloud/issues/214
Improve copy scope performance
thanks @nnsgmsone @m-schen
> Improve copy scope performance for 0.6

- pkg/frontend/mysql_cmd_executor.go
- pkg/sql/parsers/dialect/mysql/mysql_lexer.go
- test/cases/dml/select/select.test
- test/distributed/cases/dml/select/select.test
- test/distributed/result/dml/select/select.result
- test/result/dml/select/select.result
Approved by: @daviszhen, @aressu1985
issue #6686
> fix empty query 

- pkg/hakeeper/checkers/coordinator.go
- pkg/hakeeper/checkers/dnservice/check.go
- pkg/logservice/option.go
- pkg/taskservice/mysql_task_storage.go
- pkg/tests/service/options.go
- pkg/tests/service/service.go
Approved by: @zhangxu19830126
issue #
> modify log level in integration tests (#6770) to 0.6.0

- pkg/vm/engine/tae/db/db_test.go
- pkg/vm/engine/tae/logtail/handle.go
- pkg/vm/engine/tae/rpc/handle.go
- pkg/vm/engine/tae/tables/node.go
issue #6753
- logtail do not read from s3, back to sending meta
- if logtail size is large, force flush table and try again
> Fix flush logtail

- pkg/vm/engine/tae/dataio/blockio/read.go
- pkg/vm/engine/tae/db/db_test.go
- pkg/vm/engine/tae/rpc/handle.go
issue #
- filter appendable block data using ts
> add blockread filter

- pkg/container/vector/tools.go
> fix a disttae filter bug

- pkg/vectorize/momath/math.go
- test/cases/function/func_math_sinh.test
- test/distributed/cases/function/func_math_sinh.test
- test/distributed/result/function/func_math_sinh.result
- test/result/function/func_math_sinh.result
issue #3266
Refer to MySQL processing habits. When the calculation result of the sigh function is infinite, an error is reported: Out of range
> modify sinh bug

- pkg/container/vector/tools.go
> 0.6: fix a disttae filterbug

- pkg/vm/engine/tae/db/db_test.go
- pkg/vm/engine/tae/logtail/handle.go
- pkg/vm/engine/tae/rpc/handle.go
> Flush logtail main

- pkg/common/morpc/backend.go
issue #
Add morpc backend id to logger for easy debugging of issues
> morpc: add backend-id to logger

- pkg/container/vector/tools.go
> [Bug]: fix a filter bug for = operation #6835

- pkg/frontend/mysql_cmd_executor.go
- pkg/frontend/routine.go
- pkg/frontend/routine_manager.go
> support interrupt in load flow

- cmd/mo-service/debug.go
- pkg/txn/storage/memorystorage/memtable/table.go
- pkg/txn/storage/memorystorage/memtable/table_test.go
- pkg/vm/engine/disttae/partition.go
issue #6793 
memtable: make FilterVersions apply on all keys
mo-service: add /debug/heap/ page
> disttae: re-implement Partition.GC

- pkg/taskservice/mysql_task_storage.go
> add rows.Err() check after query for 0.6.0

- pkg/vm/engine/disttae/engine.go
- pkg/vm/engine/disttae/types.go
issue #6232
Temporary solution, until the memtable is refactored and no longer needs to display the call to gc
> Active call to gc to free memory

- pkg/sql/colexec/connector/connector.go
- pkg/sql/colexec/dispatch/dispatch.go
> 0.6: fix operator bug may cause data race when pipeline failed

- pkg/vm/engine/tae/tables/ablk.go
- pkg/vm/engine/tae/tables/appender.go
- pkg/vm/engine/tae/tables/base.go
- pkg/vm/engine/tae/tables/blk.go
- pkg/vm/engine/tae/tables/block_test.go
> avoid creating small pinned object  

- pkg/util/sysview/sysview.go
- test/cases/database/system_table.sql
- test/cases/database/system_variables.sql
- test/cases/table/truncate_table_2.result
- test/distributed/cases/database/system_table.sql
- test/distributed/cases/database/system_variables.sql
- test/distributed/cases/table/truncate_table_2.result
- test/distributed/result/database/system_table.result
- test/distributed/result/database/system_variables.result
- test/distributed/result/table/system_table_cases.result
- test/result/database/system_table.result
- test/result/database/system_variables.result
- test/result/table/system_table_cases.result
> fix pandas to_sql error

- pkg/vm/engine/disttae/table.go
- pkg/vm/engine/disttae/txn.go
- pkg/vm/engine/disttae/types.go
issue #6855 #6875
Fix the data race of cn
> Fix the data race of txn

- pkg/frontend/routine_manager.go
issue #263
Fix using ni pointer before checking it.
> fix nil pointer

- pkg/logservice/client_test.go
- pkg/logservice/hakeeper_client_test.go
- pkg/logservice/shardinfo_test.go
> fix test case where GetShardInfo() is called.

- test/distributed/cases/transaction/isolation_2.result
- test/distributed/cases/transaction/isolation_2.sql
issue #5950 
cherry-pick from main branch
> tests: update issue#5950 bvt

- pkg/vm/engine/tae/dataio/blockio/read.go
issue #
when read s3 error happens, batch will be nil, which can't be closed
> fix err handle

- .github/workflows/e2e_with_race.yml
- .github/workflows/release.yml
- optools/sign/gon.json
> Update release ci

- pkg/vm/engine/disttae/db.go
- pkg/vm/engine/disttae/engine.go
> Fix concurrent access to map for cn

- pkg/sql/colexec/external/external.go
issue #6553 
issue #6552 
issue #6748
> alloc enough memory size for vector Nsp

- test/cases/accesscontrol/drop_account.result
- test/cases/accesscontrol/drop_account.sql
- test/cases/accesscontrol/drop_role.result
- test/cases/accesscontrol/drop_role.sql
- test/cases/accesscontrol/drop_user.result
- test/cases/accesscontrol/drop_user.sql
- test/cases/accesscontrol/inner_object.result
- test/cases/accesscontrol/inner_object.sql
- test/distributed/cases/table/external_table.sql
- test/distributed/cases/table/truncate_table_2.sql
- test/distributed/cases/transaction/atomicity_1.result
- test/distributed/cases/transaction/atomicity_1.sql
- test/distributed/cases/zz_accesscontrol/create_account.sql
- test/distributed/cases/zz_accesscontrol/drop_account.result
- test/distributed/cases/zz_accesscontrol/drop_account.sql
- test/distributed/cases/zz_accesscontrol/drop_role.result
- test/distributed/cases/zz_accesscontrol/drop_role.sql
- test/distributed/cases/zz_accesscontrol/drop_user.result
- test/distributed/cases/zz_accesscontrol/drop_user.sql
- test/distributed/cases/zz_accesscontrol/inner_object.result
- test/distributed/cases/zz_accesscontrol/inner_object.sql
> remove bvt tag

- pkg/testutil/util_new.go
- pkg/vm/engine/disttae/cache/catalog.go
- pkg/vm/engine/disttae/cache/catalog_test.go
- pkg/vm/engine/disttae/cache/types.go
> First proposal of cn cache: catalog cache

- pkg/txn/storage/memorystorage/memorytable/atomic.go
- pkg/txn/storage/memorystorage/memorytable/batch.go
- pkg/txn/storage/memorystorage/memorytable/batch_utils.go
- pkg/txn/storage/memorystorage/memorytable/bench_test.go
- pkg/txn/storage/memorystorage/memorytable/history.go
- pkg/txn/storage/memorystorage/memorytable/index.go
- pkg/txn/storage/memorystorage/memorytable/index_iter.go
- pkg/txn/storage/memorystorage/memorytable/iter.go
- pkg/txn/storage/memorystorage/memorytable/kv_pair.go
- pkg/txn/storage/memorystorage/memorytable/nullable.go
- pkg/txn/storage/memorystorage/memorytable/ordered.go
- pkg/txn/storage/memorystorage/memorytable/table.go
- pkg/txn/storage/memorystorage/memorytable/table_iter.go
- pkg/txn/storage/memorystorage/memorytable/table_state.go
- pkg/txn/storage/memorystorage/memorytable/time.go
- pkg/txn/storage/memorystorage/memorytable/transaction.go
- pkg/txn/storage/memorystorage/memorytable/tuple.go
- pkg/txn/storage/memorystorage/memorytable/types.go
- pkg/txn/storage/memorystorage/memorytable/vector_utils.go
> memorytable: add Batch

- .github/mergify.yml
issue #
modify the regular expression in mergify.taml
> Modify the configure file of Mergify

- pkg/sql/colexec/join/join.go
- pkg/sql/colexec/loopanti/join.go
- pkg/sql/colexec/loopjoin/join.go
- pkg/sql/colexec/loopleft/join.go
- pkg/sql/colexec/loopsemi/join.go
- pkg/sql/colexec/loopsingle/join.go
- pkg/sql/colexec/mark/join.go
- pkg/sql/colexec/semi/join.go
- pkg/sql/colexec/single/join.go
issue #
minor improve : free memory when encountering errors
> minor improve : free memory when encountering errors

- .github/workflows/robot.yml
- cmd/mo-service/main.go
issue #
we need to change the default configure to launch way.
> update default startup configuration

- pkg/vm/engine/tae/tables/ablk.go
- pkg/vm/engine/tae/tables/appender.go
- pkg/vm/engine/tae/tables/base.go
- pkg/vm/engine/tae/tables/blk.go
- pkg/vm/engine/tae/tables/block_test.go
- pkg/vm/engine/tae/tables/mnode.go
- pkg/vm/engine/tae/tables/pnode.go
- pkg/vm/engine/tae/tables/types.go
issue #
Code refactor to use an atomic pointer instead of sync.Locker
> tables block node small code refactor

- go.mod
- go.sum
- pkg/logservice/service_test.go
- pkg/logservice/store.go
1. Update memberlist lib version to fix goroutine leak.
2. Fix some problems in this test case.
3. Increase timeout of add replica operation.
issue #4992
> fix goroutine leak in test TestGossipInSimulatedCluster.

- pkg/vm/engine/tae/containers/batch.go
- pkg/vm/engine/tae/containers/batch_test.go
- pkg/vm/engine/tae/containers/factory.go
- pkg/vm/engine/tae/containers/utils.go
- pkg/vm/engine/tae/containers/vector.go
- pkg/vm/engine/tae/containers/vector_test.go
- pkg/vm/engine/tae/mergesort/varchar/func.go
- pkg/vm/engine/tae/model/preparer.go
- pkg/vm/engine/tae/stl/containers/stdvec.go
- pkg/vm/engine/tae/stl/containers/strvec.go
- pkg/vm/engine/tae/stl/containers/vector.go
- pkg/vm/engine/tae/stl/containers/vector_test.go
- pkg/vm/engine/tae/tables/mnode.go
- pkg/vm/engine/tae/txn/txnimpl/node.go
> small code refactor

- pkg/frontend/mysql_cmd_executor.go
- pkg/frontend/variables.go
- pkg/sql/colexec/expr_eval.go
issue #7022 #6743 
set var = default
> set var = default  for 0.6 branch

- pkg/txn/storage/memorystorage/memorytable/transaction.go
- pkg/txn/storage/memorystorage/memorytable/transaction_test.go
> memorytable: fix multi-table transaction rollback

- .github/workflows/robot.yml
- cmd/mo-service/main.go
> Adjust startup config

- pkg/vm/engine/tae/catalog/catalog_test.go
- pkg/vm/engine/tae/catalog/schema.go
- pkg/vm/engine/tae/common/id.go
- pkg/vm/engine/tae/db/replay_test.go
- pkg/vm/engine/tae/db/scannerop.go
- pkg/vm/engine/tae/db/util_test.go
- pkg/vm/engine/tae/index/zonemap.go
- pkg/vm/engine/tae/logtail/collector.go
- pkg/vm/engine/tae/logtail/handle.go
- pkg/vm/engine/tae/logtail/table.go
- pkg/vm/engine/tae/logtail/utils.go
- pkg/vm/engine/tae/moengine/engine_test.go
- pkg/vm/engine/tae/moengine/helper.go
- pkg/vm/engine/tae/tables/indexwrapper/zmnode_test.go
- pkg/vm/engine/tae/tables/indexwrapper/zonemapnode.go
- pkg/vm/engine/tae/tables/jobs/mergeblocks.go
- pkg/vm/engine/tae/txn/txnimpl/localseg.go
- pkg/vm/engine/tae/txn/txnimpl/sysblock.go
issue #6996
- store sort key in schema and consider it when compacting and merging blocks
- store Default OnUpdate as []byte to simplify converting
- better merge log and other fix
> refactor schema and sortkey

- pkg/container/types/txnts.go
- pkg/vm/engine/tae/logtail/logtail_test.go
- pkg/vm/engine/tae/logtail/reader.go
- pkg/vm/engine/tae/logtail/table.go
- pkg/vm/engine/tae/options/types.go
> optimize logtail has catalog changes check

- pkg/frontend/session.go
- pkg/sql/compile/ddl.go
- pkg/txn/storage/memorystorage/catalog.go
- pkg/txn/storage/memorystorage/mem_handler.go
- pkg/vm/engine/gob.go
- pkg/vm/engine/tae/db/operations.go
- pkg/vm/engine/tae/moengine/helper.go
- pkg/vm/engine/types.go
issue #6846 
bvt already has some test
> use constraint instead of index in table def

- pkg/sql/plan/utils.go
issue #7082
can not deal with dynamic parameter in preparing stage.
remove filters with paramref
> [Enhancement]: refactoring stats #7082

- pkg/vm/engine/tae/tables/base.go
issue [#302](https://github.com/matrixorigin/MO-Cloud/issues/302)
> fix mnode unref

- .github/workflows/ci.yml
issue #
fix sca install linter fail
> Update ci.yml to fix sca install linter fail

- pkg/catalog/types.go
> fix create_sql too large in tabledef

- pkg/vm/engine/tae/db/scheduler.go
- pkg/vm/engine/tae/tables/jobs/mergeblocks.go
issue #
- use round-robin shader for io task
- close old merge batch early
> fix concurrent io

- .github/mergify.yml
> Remove lint-docs check in mergify

- pkg/vm/engine/disttae/hack.go
- pkg/vm/engine/disttae/tools.go
issue #251
use a map to search blocklist, instead of exhausitive search
> [User Bug]: 跟ck的单机复杂查询性能相差从10倍-3000倍 #251

- .github/workflows/robot.yml
- CODEOWNERS
> add codeowner

- .github/workflows/ci.yml
- .github/workflows/e2e-compose.yml
- .github/workflows/e2e.yml
- .github/workflows/ut_pr.yml
issue #
CI will not run when pr is draft
> Optimize CI

- pkg/vm/engine/disttae/table.go
- pkg/vm/engine/disttae/tools.go
- pkg/vm/engine/disttae/txn.go
- pkg/vm/engine/disttae/util.go
- pkg/vm/engine/disttae/util_test.go
issue #7206
move some operations outside the for loop
> [Enhancement]: optimize the filtering using zonemap #7206

- pkg/sql/plan/function/builtin/unary/current_date.go
- pkg/sql/plan/function/builtin/unary/current_date_test.go
- pkg/sql/plan/function/builtins.go
- pkg/sql/plan/function/function_id.go
- test/distributed/cases/function/func_datetime_curdate.result
- test/distributed/cases/function/func_datetime_curdate.test
> Add curdate function

- pkg/frontend/mysql_cmd_executor.go
- pkg/frontend/mysql_protocol.go
- test/distributed/cases/dtype/text_blob.result
issue #7203 
fix blob type error
> fix blob type error

- pkg/sql/plan/base_binder.go
issue #7197 
if column not exists in current table, MO will log error message now. even if column can be found in parent table.
this PR will stop throw out error when column will be found in parent table.
and throw out error if have no parent in the context.(just like now)
> do not log error message when column was found in parent table

- pkg/vm/engine/tae/common/refs.go
- pkg/vm/engine/tae/dataio/blockio/read.go
- pkg/vm/engine/tae/tables/base.go
- pkg/vm/engine/tae/tables/jobs/compactblk.go
issue #
- fix data race in releasing mnode
- better log
> tae small fix

- pkg/sql/plan/function/operator/compare.go
issue #6870
simplify the code of CompareValenaInline
> [Bug]: mo's scan with predicate is slower than clickhouse #6870

- pkg/vm/engine/disttae/partition.go
- test/distributed/cases/dml/update/flush.result
- test/distributed/cases/dml/update/flush.test
- test/distributed/cases/zz_accesscontrol/alter_account.result
- test/distributed/cases/zz_accesscontrol/alter_account.sql
issue #7007
skip appendable block when collecting modified block
> fix blocklist in cn

- pkg/fileservice/file_service.go
- pkg/fileservice/s3_fs.go
> fileservice: add IOVector.ExpireAt

- pkg/container/vector/vector.go
- pkg/sql/colexec/agg/avg.go
> Fix vector method bug and Aggregate AVG bug.

- pkg/common/hashmap/strhashmap.go
https://github.com/matrixorigin/MO-Cloud/issues/334
> Fix mo-cloud #334

- pkg/common/bitmap/bitmap.go
- pkg/common/bitmap/types.go
> [Bug]: optimze bitmap isEmpty #7307

- test/distributed/cases/dml/update/flush.test
> remove flush.test bvt tag

- pkg/sql/plan/build.go
- pkg/sql/plan/build_partition_test.go
- pkg/sql/plan/build_test.go
- pkg/sql/plan/mock.go
- pkg/sql/plan/query_builder.go
> add more ut in plan

- go.mod
- go.sum
issue #5891
Allow hostname changed when move data directory to another host.
> Allow hostname changed in dragonboat.

- pkg/sql/plan/utils.go
- pkg/vm/engine/disttae/table.go
- pkg/vm/engine/disttae/tools.go
- pkg/vm/engine/disttae/util.go
- pkg/vm/engine/disttae/util_test.go
> [Enhancement]: optimize filter expr for zonemap #7328

- pkg/vm/engine/tae/txn/txnimpl/database.go
issue #7389
inherit access info from the original table
> fix account id in truncating

- pkg/vm/engine/disttae/database.go
- pkg/vm/engine/disttae/engine.go
- pkg/vm/engine/disttae/table.go
- pkg/vm/engine/disttae/types.go
> Add marker to make logtail sync only once

- test/distributed/cases/function/function_sleep.result
- test/distributed/cases/function/function_sleep.sql
> function_sleep cases

- pkg/sql/plan/explain/explain_query.go
- pkg/sql/plan/explain/marshal_model.go
- pkg/sql/plan/explain/marshal_query.go
issue #6596
Explain Fill in the statistical data of the total system resources used for SQL query execution, including time, memory, IO, network, data, etc
> query explain add golbal stats

- pkg/sql/colexec/expr_eval.go
- pkg/sql/plan/function/function.go
> removed a duplicate function structure

- pkg/lockservice/deadlock.go
- pkg/lockservice/deadlock_test.go
> lockservice: add deadlock detector

- pkg/fileservice/file_service.go
- pkg/fileservice/file_service_test.go
- pkg/fileservice/io_entry.go
- pkg/fileservice/local_etl_fs.go
- pkg/fileservice/local_fs.go
issue #
Allow size unknown ReaderForWrite
> fileservice: fix ReaderForWrite

- pkg/container/vector/functionTools.go
- pkg/sql/plan/function/operator/cast2.go
> improve the GetValue performance of FunctionParameterWrapper

- test/distributed/cases/function/func_string_format.result
- test/distributed/cases/function/func_string_format.test
> function_format cases

- pkg/util/export/merge.go
- pkg/util/export/merge_test.go
issue #
fix bug discoverd in CI https://github.com/matrixorigin/matrixone/actions/runs/3847965388/jobs/6563396585
etl merge task run panic with trying to close open, if failed to open file.
> bugfix: ut discover bug while failed to open file.

- pkg/frontend/mysql_cmd_executor.go
- pkg/sql/colexec/table_function/meta_scan.go
- pkg/sql/compile/compile.go
- pkg/vm/process/types.go
> disable query result when no config

- pkg/frontend/authenticate_test.go
- pkg/frontend/internal_executor.go
- pkg/frontend/load.go
- pkg/frontend/mysql_cmd_executor.go
- pkg/frontend/query_result.go
- pkg/frontend/query_result_test.go
- pkg/frontend/routine_manager.go
- pkg/frontend/server.go
- pkg/frontend/session.go
- pkg/frontend/variables.go
- pkg/sql/colexec/table_function/meta_scan.go
- pkg/sql/compile/compile.go
- pkg/sql/plan/function/builtin/unary/infomation_function.go
- pkg/sql/plan/function/builtins.go
- pkg/sql/plan/function/function_id.go
- pkg/vm/process/types.go
> complete func of last_query_id and init var by config

- pkg/catalog/types.go
- pkg/frontend/authenticate.go
- pkg/sql/plan/build_show.go
- pkg/sql/plan/query_builder.go
- pkg/sql/util/util.go
- test/distributed/cases/zz_accesscontrol/create_account.result
- test/distributed/cases/zz_accesscontrol/create_account.sql
This reverts commit 38d9138b244224d6db0ef26d19f6021de95944ab.
issue #
7495 brought some bugs, need to revert
> Revert "fix user account can show all the databases (#7495)"

- pkg/sql/plan/deepcopy.go
> fix table function expr deep-copy err

- pkg/objectio/buffer.go
- pkg/objectio/type.go
- pkg/objectio/writer.go
- pkg/objectio/writer_test.go
> Objectio add write options

- pkg/sql/compile/compile.go
#7124
Set affected rows for create/drop database
> Set affected rows for create/drop database

- pkg/sql/colexec/agg/distagg.go
> Fix the merge bug of dist agg

- pkg/catalog/types.go
- pkg/frontend/mysql_cmd_executor.go
- pkg/frontend/query_result.go
- pkg/frontend/server.go
- pkg/frontend/session.go
- pkg/frontend/variables.go
- pkg/sql/plan/meta_scan.go
- test/distributed/cases/query_result/query_result.result
- test/distributed/cases/query_result/query_result.sql
> add field of tables in meta scan and support size limit

- pkg/frontend/mysql_cmd_executor.go
- pkg/frontend/routine_manager.go
- pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
issue #6668 
show accounts can be put into the begin...commit.
show accounts design docs: https://github.com/matrixorigin/docs/blob/main/tech-notes/sql/design/show_account.md
> update show accounts

- pkg/vm/engine/tae/db/operations.go
- pkg/vm/engine/tae/rpc/handle.go
issue #7158 
1.Fix for context passed by txn framework being canceled.
> fix for context being canceled

- etc/dn-minimal-s3-test.toml
- etc/launch-tae-CN-tae-DN/cn.toml
- etc/launch-tae-CN-tae-DN/dn.toml
- etc/launch-tae-CN-tae-DN/log.toml
- etc/launch-tae-compose/config/cn-0.toml
- etc/launch-tae-compose/config/cn-1.toml
- etc/launch-tae-compose/config/dn.toml
- etc/launch-tae-compose/config/log.toml
- etc/launch-tae-multi-CN-tae-DN/cn1.toml
- etc/launch-tae-multi-CN-tae-DN/cn2.toml
- etc/launch-tae-multi-CN-tae-DN/dn.toml
- etc/launch-tae-multi-CN-tae-DN/log.toml
- pkg/fileservice/local_fs_test.go
> etc: add file service disk cache path config

- pkg/sql/compile/scope.go
- pkg/vm/engine/disttae/database.go
- pkg/vm/engine/disttae/engine.go
- pkg/vm/engine/disttae/reader.go
- pkg/vm/engine/disttae/types.go
> Fix some memory leak of cn

- pkg/frontend/mysql_cmd_executor.go
- pkg/frontend/session.go
- test/distributed/cases/transaction/ww_conflict.result
- test/distributed/cases/transaction/ww_conflict.sql
issue #6024 
Change the error info of `start transaction` or `begin` that encouters the w-w conflict.
> fix error info

- pkg/vm/engine/tae/logtail/service/server.go
issue #6894
issue #6823
If logtail collection interval was configured too short, 5ms for example, it's possible that logtail collector would be quicker than logtail publisher. This PR fix a concurrent bug exposed by a quicker logtail producer.
> FIX: make logtail collection and publishement serialized in `logtail push model`

- pkg/vectorize/like/like.go
- test/distributed/cases/function/func_like.result
- test/distributed/cases/function/func_like.test
> [Bug]: like op got false result, if target string has ( #7656

- pkg/cnservice/cnclient/client.go
- pkg/cnservice/server.go
- pkg/common/morpc/backend.go
- pkg/common/morpc/backend_test.go
- pkg/common/morpc/client.go
- pkg/common/morpc/codec.go
- pkg/common/morpc/codec_test.go
- pkg/common/morpc/internal.go
- pkg/common/morpc/server.go
- pkg/common/morpc/server_test.go
- pkg/common/morpc/types.go
- pkg/logservice/service.go
- pkg/txn/rpc/server.go
- pkg/vm/engine/tae/logtail/service/server.go
issue #7683
Add ping/pong support via morpc.
> morpc: support ping

- pkg/sql/plan/build_show.go
- pkg/sql/plan/build_test.go
- test/distributed/cases/dml/show/show.result
- test/distributed/cases/dml/show/show.test
> fix show tables with quote

- pkg/frontend/mysql_protocol.go
- pkg/frontend/mysql_protocol_test.go
- pkg/frontend/protocol.go
- pkg/frontend/test/system_vars_config.toml
- pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
issue #370
Release the buffer maked from go system actively instead of gc by the go system to relieve the memory consumption.
> release the buffer maked after the connection is closed

- pkg/txn/storage/memorystorage/memorytable/batch.go
- pkg/txn/storage/memorystorage/memorytable/table.go
- pkg/txn/storage/memorystorage/memorytable/transaction.go
- pkg/vm/engine/disttae/engine.go
- pkg/vm/engine/disttae/txn.go
- pkg/vm/engine/disttae/types.go
memorytable: add Table.DisableHistory
issue #
> disttae: use new memory table implementation in workspace

- pkg/vm/engine/disttae/bench_test.go
- pkg/vm/engine/disttae/partition.go
- pkg/vm/engine/disttae/table.go
- pkg/vm/engine/disttae/util.go
> disttae: optimize Partition.Insert

- pkg/vm/engine/disttae/index.go
- pkg/vm/engine/disttae/partition.go
> disttae: remove index_Time

- pkg/frontend/authenticate.go
- pkg/frontend/session.go
- pkg/sql/plan/base_binder.go
- pkg/sql/plan/mock.go
- pkg/sql/plan/types.go
- pkg/vm/engine/memoryengine/compiler_context.go
- test/distributed/cases/function/udf.result
- test/distributed/cases/function/udf.sql
> revert udf execution pr

- pkg/vm/engine/tae/rpc/handle.go
- test/distributed/cases/table/create_table.result
- test/distributed/cases/table/create_table.test
issue #7713
1. improve debug info of write batch, null can be printed now
2. add temp flag to skip insert null in cluster-by table, sort null task is tracked in #7565
> fix bvt case
