matrixorigin/matrixone

- pkg/vm/engine/tae/db/checkpoint/runner.go
- pkg/vm/engine/tae/db/scannerop.go
fix ut fail in https://github.com/matrixorigin/matrixone/actions/runs/4052624188/jobs/6972266792
> fix ckp ut

- pkg/frontend/types.go
- test/distributed/cases/transaction/isolation_2.result
- test/distributed/cases/transaction/isolation_2.sql
issue #7757
And shrink the cache size to 3000.
> Change bvt for auto_incr cache.

- pkg/vm/engine/disttae/table.go
- pkg/vm/engine/disttae/util.go
issue #
get metadata if needed before calc stats
> get metadata if needed before calc stats

- pkg/vm/engine/tae/db/db_test.go
- pkg/vm/engine/tae/db/open.go
> disable gc catalog

- pkg/sql/plan/utils.go
- pkg/sql/util/composite_clusterby_util.go
> adjust stats

- pkg/sql/plan/explain/explain_expr.go
> Output precision and scale for Decimal in explain to help debugging

- pkg/sql/compile/cnserviceDriver.go
Signed-off-by: Wu Qinxuan <wuqinxuan33@gmail.com>
issue #7853
fix the issue that getting stuck when requireCnt = 0
> fix the issue 7853

- pkg/taskservice/task_runner.go
issue #
If ctx of a task is canceled, the task should return directly.
> fix task return when error task run failed

- test/distributed/cases/dml/show/database_statistics.result
- test/distributed/cases/dml/show/database_statistics.sql
> remove bvt  tag

- pkg/frontend/mysql_protocol.go
- pkg/frontend/session.go
issue #
1、rand.Read&rand.Seed was deprecated in go 1.20 (will show warning in my VsCode )。  so do some refactor follow the official advice
see https://pkg.go.dev/math/rand#Seed
2、comment some code not used. (maybe used in debug?)
> minor refacor in frontend

- pkg/sql/colexec/external/external.go
- pkg/sql/compile/compile.go
- pkg/vm/pipeline/pipeline.go
> Forced release of pipeline's resources

- pkg/vm/engine/disttae/db.go
- pkg/vm/engine/disttae/engine.go
- pkg/vm/engine/disttae/partition.go
- pkg/vm/engine/disttae/types.go
> disttae: refactor partition locking

- pkg/vm/engine/disttae/database.go
- pkg/vm/engine/disttae/util.go
> Fix the bug of prefetch

- pkg/fileservice/file_service_test.go
- pkg/fileservice/s3_fs.go
> fileservice: add random offset and size read tests for ReadCloserForRead; add credentials cache

- pkg/vm/engine/tae/logtail/service/response.go
- pkg/vm/engine/tae/logtail/service/service_test.go
issue #7998
Enlarge reserved size for morpc internal header in order to make chunks pass.
> Update segmentation logic according to PR #7931

- pkg/fileservice/s3_fs.go
- pkg/fileservice/s3_fs_test.go
> fileservice: try to detect bucket region if not provided

- pkg/vm/engine/disttae/partition_reader.go
> change err info

- pkg/sql/colexec/dispatch/dispatch.go
- pkg/sql/colexec/dispatch/sendfunc.go
- pkg/sql/compile/compile.go
- pkg/sql/compile/operator.go
roll back broadcast join to old
> roll back broadcast join

- .github/workflows/coverage_pr.yml
- .github/workflows/docu_check.yaml
> Fix coverage bug

- .github/workflows/coverage_pr.yml
issue #
optimize pr coverage test
> Coverage struct redesign

- cmd/mo-service/main.go
- pkg/cnservice/cnclient/client.go
- pkg/cnservice/server.go
issue #
fix rpc config not work for cn pipeline client and server
> cn: fix rpc config not work for cn

- pkg/sql/plan/join_order.go
> Disable the problematic code which affects join order

- pkg/fileservice/file_with_checksum.go
- pkg/fileservice/pool.go
- pkg/fileservice/pool_test.go
> fileservice: optimize FileWithChecksum.readBlock

- pkg/fileservice/pool.go
- pkg/fileservice/pool_test.go
fileservice: optimize pool
issue #
> fileservice: add parallel pool benchmark

- pkg/sql/parsers/dialect/mysql/mysql_sql.go
- pkg/sql/parsers/dialect/mysql/mysql_sql.y
> remove inuse pkg

- pkg/sql/compile/scope.go
issue #
fix copy scope panic issue
> fix copy scope panic issue

- test/distributed/cases/dtype/double.test
> remove bvt case tag for #3366

- pkg/fileservice/profile.go
- pkg/fileservice/profile_test.go
> fileservice: optimize profile

- pkg/fileservice/disk_cache.go
- pkg/fileservice/example_test.go
- pkg/fileservice/lru.go
- pkg/fileservice/mem_cache.go
- pkg/fileservice/releasable.go
- pkg/fileservice/releasable_test.go
issue #
fileservice: remove not required noline tags
fileservice: add cache RC example
>  fileservice: add Releasable; clean-ups 

- pkg/sql/colexec/merge_util.go
- pkg/sql/colexec/s3util.go
> fix sort bug

- .github/workflows/robot.yml
issue #
Carry out UT test in advance to prevent port conflicts
> Change the order between UT and BVT

- pkg/frontend/query_result.go
- pkg/frontend/session.go
- pkg/sql/colexec/external/external.go
- pkg/sql/colexec/table_function/meta_scan.go
> unify error that query result not found

- cmd/mo-service/debug.go
- pkg/fileservice/disk_cache.go
- pkg/fileservice/local_fs.go
- pkg/fileservice/mem_cache.go
- pkg/fileservice/profile.go
- pkg/fileservice/profile_test.go
- pkg/fileservice/s3_fs.go
> fileservice: add ProfileHandler

- pkg/frontend/session.go
- pkg/sql/plan/base_binder.go
- pkg/sql/plan/mock.go
- pkg/sql/plan/types.go
- pkg/sql/plan/types_mock.go
- pkg/vm/engine/memoryengine/compiler_context.go
- test/distributed/cases/function/udf.result
- test/distributed/cases/function/udf.sql
> udf_execution refined

- pkg/container/types/rowid.go
- pkg/vm/engine/disttae/bench_test.go
- pkg/vm/engine/disttae/db.go
- pkg/vm/engine/disttae/logtail.go
- pkg/vm/engine/disttae/logtailPullModel.go
- pkg/vm/engine/disttae/logtailPushModel.go
- pkg/vm/engine/disttae/partition.go
- pkg/vm/engine/disttae/partition_state.go
- pkg/vm/engine/disttae/types.go
issue #7792 
disttae: update BenchmarkPartitionInsert
disttae: sketch new partition cache
disttae: add PartitionCache.HandleRowsDelete
disttae: add PartitionCache.HandleLogtailEntry
disttae: fix PartitionCache.HandleRowsInsert/HandleRowsDelete
disttae: add PartitionCache.HandleMetadataInsert/HandleMetadataDelete
disttae: fix PartitionCache.HandleMetadataDelete
disttae: handle entry state in PartitionCache.HandleMetadataInsert
> disttae: new partition cache implementation.  phase 1

- pkg/lockservice/lock_table_allocator_test.go
issue #8194 
Fix TestKeepaliveBind failed
> lockservice: fix TestKeepaliveBind failed

- test/distributed/cases/dml/select/sp_table.result
- test/distributed/cases/dml/select/sp_table.sql
issue #8185
fix bvt test error
> fix bvt test error

- pkg/vm/engine/disttae/db.go
- pkg/vm/engine/disttae/engine.go
- pkg/vm/engine/disttae/logtail.go
- pkg/vm/engine/disttae/logtailPullModel.go
- pkg/vm/engine/disttae/logtailPushModel.go
- pkg/vm/engine/disttae/tools.go
- pkg/vm/engine/disttae/txn.go
- pkg/vm/engine/disttae/txn_database.go
- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/disttae/types.go
- pkg/vm/engine/disttae/util.go
issue #
disttae: various fixes
disttae: rename database to txnDatabase
disttae: rename table to txnTable
disttae: merge DB to Engine
disttae: remove txnDatabase.fs
disttae: remove txnDatabase.engine
disttae: remove Transaction.catalog
> disttae: code clean-ups

- pkg/container/vector/vector.go
- pkg/container/vector/vector_test.go
> Add GetUnionOneFunction for better copying of vector's data

- go.mod
- go.sum
> logservice: update dragonboat version.

- pkg/frontend/session.go
- test/distributed/cases/sql_inject/sql_inject.result
- test/distributed/cases/sql_inject/sql_inject.test
issue #5476
fix bug: SQL injection
you can see the comment in this issue https://github.com/matrixorigin/matrixone/issues/5476.
comment will tell you what happen & why use this solution to fix it.
> fix bug: SQL injection

- pkg/container/vector/vector.go
- pkg/vm/engine/disttae/bench_test.go
- pkg/vm/engine/disttae/db.go
- pkg/vm/engine/disttae/logtail.go
- pkg/vm/engine/disttae/logtailPullModel.go
- pkg/vm/engine/disttae/logtailPushModel.go
- pkg/vm/engine/disttae/partition.go
- pkg/vm/engine/disttae/partition_reader.go
- pkg/vm/engine/disttae/partition_state.go
- pkg/vm/engine/disttae/partition_state_iterators.go
- pkg/vm/engine/disttae/partition_state_iterators_test.go
- pkg/vm/engine/disttae/types.go
issue #7792 
disttae: add PartitionState.PrimaryIndex
disttae: new reader
disttae: remove PartitionReader.tx
disttae: remove PartitionReader.readTime, change proc to procMPool
disttae: add Partition.MutateState
> disttae: various refactors

- pkg/vm/engine/disttae/bench_test.go
- pkg/vm/engine/disttae/db.go
- pkg/vm/engine/disttae/engine.go
- pkg/vm/engine/disttae/logtail.go
- pkg/vm/engine/disttae/logtailPullModel.go
- pkg/vm/engine/disttae/logtailPushModel.go
- pkg/vm/engine/disttae/partition.go
- pkg/vm/engine/disttae/partition_state.go
- pkg/vm/engine/disttae/partition_state_iterators_test.go
- pkg/vm/engine/disttae/tools.go
- pkg/vm/engine/disttae/txn.go
- pkg/vm/engine/disttae/txn_database.go
- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/disttae/txn_table_meta.go
- pkg/vm/engine/disttae/types.go
issue #
This reverts commit 06f52a314d203b000027bcfd2930dbfb728f6e0c.
> Revert "disttae: various refactors (#8245)"

- .github/workflows/e2e_with_race.yml
> rename e2e(race) job name

- pkg/sql/colexec/dispatch/dispatch.go
- pkg/sql/colexec/dispatch/sendfunc.go
- pkg/sql/colexec/dispatch/types.go
- pkg/sql/compile/compile.go
- pkg/sql/compile/operator.go
- pkg/sql/compile/scope.go
issue #
fix the hung issue when the pipeline read an empty table
> fix pipeline hung bug

- .github/workflows/coverage_pr.yml
issue #
Do not let Step `Stop MO` and `upload artifact` run if all files are skipped
> fix error in coverage_pr

- pkg/sql/colexec/mergeblock/mergeblock.go
- pkg/sql/colexec/mergeblock/mergeblock_test.go
- pkg/sql/colexec/mergeblock/types.go
- pkg/sql/colexec/s3util.go
- pkg/vm/engine/disttae/engine.go
- pkg/vm/engine/disttae/txn.go
- pkg/vm/engine/disttae/types.go
- test/distributed/cases/transaction/conflict_transation.result
> revert transfer little batch

- pkg/container/types/tuple.go
- pkg/container/types/tuple_test.go
- pkg/fileservice/example_test.go
- pkg/fileservice/pool.go
- pkg/fileservice/pool_test.go
- pkg/fileservice/profile.go
- pkg/vm/engine/disttae/db.go
- pkg/vm/engine/disttae/encode.go
- pkg/vm/engine/disttae/encode_test.go
- pkg/vm/engine/disttae/engine.go
- pkg/vm/engine/disttae/logtail.go
- pkg/vm/engine/disttae/partition_state.go
- pkg/vm/engine/disttae/partition_state_iterators_test.go
- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/disttae/types.go
> disttae: add packer pool

- pkg/sql/plan/explain/explain_query.go
- pkg/sql/plan/explain/marshal_query.go
issue #
change time-spent statics's unit to ns
> change time-spent statics unit to ns

- pkg/sql/colexec/constraint_util.go
- pkg/sql/colexec/insert/insert.go
- test/distributed/cases/ddl/create_index.result
- test/distributed/cases/ddl/create_index.sql
issue #8284
clean up insertion code
> clean up insertion code

- pkg/vm/engine/disttae/db.go
- pkg/vm/engine/disttae/logtailPushModel.go
- pkg/vm/engine/disttae/partition_state.go
- pkg/vm/engine/disttae/types.go
- test/distributed/cases/dml/update/checkpoint.result
- test/distributed/cases/dml/update/checkpoint.test
> disttae: fix checkpoint replay in push mode

- pkg/sql/plan/join_order.go
> for tpch q13, do not use right outer join. will fix it in the future

- pkg/fileservice/counter.go
- pkg/fileservice/disk_cache.go
- pkg/fileservice/mem_cache.go
- pkg/fileservice/s3_fs.go
- pkg/fileservice/s3_fs_test.go
issue #
fileservice: add mem and disk cache counter
> fileservice: add Counter, WithCounter

- pkg/vm/engine/tae/db/open.go
- pkg/vm/engine/tae/logtail/logtailer.go
- pkg/vm/engine/tae/logtail/mgr.go
- pkg/vm/engine/tae/logtail/service/server.go
- pkg/vm/engine/tae/logtail/service/service_test.go
- pkg/vm/engine/tae/logtail/service/session.go
- pkg/vm/engine/tae/logtail/service/waterline.go
- pkg/vm/engine/tae/logtail/service/waterline_test.go
- pkg/vm/engine/tae/logtail/table.go
- pkg/vm/engine/tae/logtail/table_test.go
- pkg/vm/engine/tae/txn/txnbase/mvccnode.go
- pkg/vm/engine/tae/txn/txnbase/txnmgr.go
> fix prepare and txn mgr

- etc/launch-tae-CN-tae-DN/cn.toml
- etc/launch-tae-compose/config/cn-0.toml
- etc/launch-tae-compose/config/cn-1.toml
- etc/launch-tae-multi-CN-tae-DN/cn1.toml
- etc/launch-tae-multi-CN-tae-DN/cn2.toml
> Update cn's morpc configuration

- pkg/common/moerr/error.go
- pkg/frontend/query_result.go
- pkg/frontend/session.go
- pkg/sql/colexec/external/external.go
- pkg/sql/colexec/table_function/meta_scan.go
> modify err msg for query result

- pkg/sql/plan/join_order.go
- pkg/sql/plan/query_builder.go
> Fix planner logic of non-equi join conditions

- pkg/dnservice/cfg.go
- pkg/dnservice/store.go
- pkg/dnservice/store_heartbeat.go
- pkg/lockservice/lock_table_allocator.go
- pkg/txn/service/service.go
- pkg/txn/service/service_cn_handler.go
- pkg/txn/service/service_cn_handler_test.go
- pkg/txn/service/service_testutil.go
issue #7066 
dn transaction server integration lockservice
> txn: dn service integration lock service

- cmd/mo-service/config.go
- cmd/mo-service/config_test.go
- cmd/mo-service/debug.go
- cmd/mo-service/launch.go
- cmd/mo-service/main.go
- pkg/cnservice/distributed_tae.go
- pkg/fileservice/caching_file_service_test.go
- pkg/fileservice/config.go
- pkg/fileservice/disk_cache.go
- pkg/fileservice/local_fs.go
- pkg/fileservice/mem_cache.go
- pkg/fileservice/s3_fs.go
- pkg/fileservice/s3_fs_test.go
- pkg/perfcounter/context.go
- pkg/perfcounter/counter.go
- pkg/perfcounter/counter_set.go
- pkg/perfcounter/http.go
- pkg/perfcounter/http_test.go
- pkg/perfcounter/update.go
- pkg/perfcounter/update_test.go
- pkg/sql/compile/compile.go
- pkg/sql/compile/scopeRemoteRun.go
- pkg/sql/compile/scopeRemoteRunTypes.go
- pkg/sql/compile/types.go
- pkg/vm/engine/disttae/partition_state.go
- pkg/vm/pipeline/pipeline.go
issue #
perfcounter: do not show zero values in ServeHTTP
perfcounter: add Counter.FileServices
> perfcounter: optimizations

- pkg/lockservice/lock.go
- pkg/lockservice/lock_table_local.go
- pkg/lockservice/log.go
- pkg/lockservice/service_test.go
- pkg/lockservice/waiter.go
issue #7066 
Add lock with batch rows or ranges support
> lockservice: add lock with batch rows or ranges support

- pkg/fileservice/config.go
- pkg/fileservice/file_service.go
- pkg/fileservice/file_service_test.go
- pkg/fileservice/path.go
- pkg/fileservice/path_test.go
- pkg/fileservice/s3_fs.go
- pkg/fileservice/s3_fs_test.go
- pkg/fileservice/sub_path.go
- pkg/fileservice/sub_path_test.go
> fileservice: add SubPath

- pkg/util/batchpipe/batch_pipe_test.go
> fix some time-related fragile ut

- pkg/vm/engine/tae/tables/jobs/flushblk.go
issue #
SortKey may not be the primary key,cannot use SortKey to set primary key
> SortKey may not be the primary key.

- pkg/vm/engine/tae/containers/vecimpl.go
- pkg/vm/engine/tae/containers/vector_test.go
issue #
ForeachShallow should happen in nullable vector
> fix foreach

- pkg/sql/colexec/s3util.go
> fix buffer

- cmd/mo-service/main.go
- pkg/cnservice/server.go
- pkg/cnservice/server_task.go
- pkg/cnservice/types.go
- pkg/util/export/etl/csv.go
- pkg/util/export/etl/csv_test.go
- pkg/util/export/etl/tae.go
- pkg/util/export/etl/tae_test.go
- pkg/util/export/example/main.go
- pkg/util/export/merge.go
- pkg/util/export/merge_test.go
> util/export: remove refers to defines.ETLFileServiceName

- pkg/taskservice/task_runner.go
issue #
Add task status check when cn fetches tasks' info.
> fix cn runs completed tasks when it restarts

- pkg/frontend/query_result.go
> Fix dump query_result panic

- pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
- pkg/sql/parsers/dialect/mysql/scanner.go
> add dollar quote string

- pkg/sql/plan/function/function.go
> fix decimal bug

- pkg/sql/parsers/tree/cstr.go
- pkg/sql/parsers/tree/cstr_test.go
> fix set config bug

- pkg/sql/colexec/expr_eval.go
> fix inconsistency of decimal scale for particular queries

- pkg/container/vector/vector.go
> Fix a bug in Vector.CloneWindow

- pkg/frontend/variables.go
- test/distributed/cases/dtype/datetime.result
- test/distributed/cases/dtype/datetime.test
> Detect illegal value for time_zone

- pkg/frontend/variables.go
- test/distributed/cases/database/system_variables.result
- test/distributed/cases/database/system_variables.sql
> Init system_time_zone properly

- pkg/sql/colexec/insert/insert.go
- pkg/sql/colexec/mergeblock/mergeblock.go
- pkg/sql/colexec/mergeblock/mergeblock_test.go
- pkg/sql/colexec/mergeblock/types.go
- pkg/sql/colexec/s3util.go
- pkg/vm/engine/disttae/engine.go
- pkg/vm/engine/disttae/txn.go
- pkg/vm/engine/disttae/types.go
- test/distributed/cases/ddl/unique_secondary_index.result
- test/distributed/cases/load_data/load_data.result
- test/distributed/cases/transaction/conflict_transation.result
> transfer little batch

- pkg/fileservice/file_with_checksum.go
- pkg/fileservice/file_with_checksum_test.go
- pkg/fileservice/local_etl_fs.go
- pkg/fileservice/local_fs.go
- pkg/fileservice/mutable_file_service.go
- pkg/fileservice/mutable_file_service_test.go
- pkg/perfcounter/counter_set.go
> fileservice: add FileWithChecksum perf counters

- pkg/container/nulls/nulls.go
- pkg/container/vector/vector.go
> Fix vector bugs

- pkg/vm/engine/tae/dataio/blockio/read.go
issue #
The rowid in BlockRead was previously generated using the vector of dn, but now it is generated using the vector of cn
> Rowid uses cn's vector to generate

- pkg/vm/engine/tae/containers/utils.go
- pkg/vm/engine/tae/containers/vector_test.go
- pkg/vm/engine/tae/dataio/blockio/read.go
> Workaround for fix # 8684

- pkg/vm/engine/tae/logtail/txn_handle.go
issue #
There are some weak memory-leak building logtail responses.
> fix to close batch 

- pkg/frontend/variables.go
> Don't panic for illegal timezone value

- cmd/mo-service/config.go
- pkg/fileservice/caching_file_service_test.go
- pkg/fileservice/disk_cache.go
- pkg/fileservice/disk_cache_test.go
- pkg/fileservice/file_with_checksum.go
- pkg/fileservice/mem_cache.go
- pkg/fileservice/s3_fs.go
- pkg/fileservice/s3_fs_test.go
- pkg/perfcounter/counter_logexporter.go
- pkg/perfcounter/counter_set.go
- pkg/perfcounter/http_test.go
- pkg/sql/compile/compile.go
- pkg/sql/compile/scopeRemoteRun.go
> perfcounter: refactor CounterSet

- pkg/vm/engine/disttae/partition.go
- pkg/vm/engine/disttae/partition_state.go
- pkg/vm/engine/disttae/partition_state_iterators_test.go
- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/disttae/txn_table_test.go
issue #
add PartitionState.noData
disttae: do not copy localState in txnTable.updateLocalState
disttae: use lower btree degree to reduce copy costs
> disttae: various optimizations 

- pkg/fileservice/file_service_bench_test.go
- pkg/fileservice/file_with_checksum.go
- pkg/fileservice/local_fs.go
issue #
fileservice: optimize benchmarkFileService
fileservice: add NewFileWithChecksumOSFile
> fileservice: various optimizations

- pkg/vm/engine/tae/logtail/handle.go
- pkg/vm/engine/tae/tables/txnentries/compactblk.go
issue #8788 #8775
fix deleting existing files of the same block
> fix not found file

- pkg/vm/engine/disttae/txn_table.go
issue #8698
fix bug:tpcc regression test reported panic error
> fix bug:tpcc regression test reported panic error

- pkg/sql/parsers/tree/expr.go
- pkg/sql/util/util.go
issue #8830 
fix mo_columns filter
> fix mo_columns filter

- pkg/util/sysview/sysview.go
- test/distributed/cases/database/system_table.result
- test/distributed/cases/database/system_table.sql
issue #8834
Solve the problem of 'tables' view query error reporting in information schema
> Fix information schema bug

- pkg/lockservice/waiter.go
issue #8817 
Add more logger for panic
> lockservice: add more log for panic

- pkg/sql/plan/stats.go
affected queries: tpch q17 and ssb q3.4
issue #
> adjust stats to get a better join order.

- pkg/taskservice/mysql_task_storage.go
issue #
use prepare in task update.
> use prepare in task update

- .github/workflows/docker_ci.yml
issue #8872 
fix docker image version bug
> fix docker image version bug

- pkg/container/vector/vector.go
- pkg/container/vector/vector_test.go
> implement vector.Window

- pkg/vm/engine/tae/catalog/schema.go
- pkg/vm/engine/tae/db/db_test.go
> fix marsh schema, persist partioned in log

- pkg/vm/engine/tae/txn/txnimpl/localseg.go
- pkg/vm/engine/tae/txn/txnimpl/store.go
- pkg/vm/engine/tae/txn/txnimpl/table.go
- pkg/vm/engine/tae/txn/txnimpl/txndb.go
> fix force checkpoint timeout, unref ablk when applycommit/rollback

- pkg/sql/compile/compile.go
- pkg/sql/compile/scope_test.go
- pkg/sql/compile/types.go
> support compile multi step

- pkg/sql/plan/join_order.go
affected query: tpch q20
issue #
> use stats to judge if pushdownSemiAntiJoins should be done

- cmd/mo-service/debug.go
- cmd/mo-service/main.go
> Add command-line option "--heap-profile"

- pkg/sql/plan/base_binder.go
- pkg/sql/plan/query_builder.go
> ConstFold for unary operator and limit/offset validation in QueryBuilder

- pkg/vm/engine/tae/catalog/segment.go
- pkg/vm/engine/tae/db/db_test.go
- pkg/vm/engine/tae/db/scannerop.go
- pkg/vm/engine/tae/options/types.go
- pkg/vm/engine/tae/tables/handle.go
- pkg/vm/engine/tae/tables/jobs/compactblk.go
issue #8871
- create new appendable segments during appending, avoid index overflowing in a segment
> fix full segment

- pkg/sql/compile/scopeRemoteRunTypes.go
> fix a new sender error will not return.

- pkg/vm/engine/tae/index/zm.go
- pkg/vm/engine/tae/index/zm_test.go
> fix null zm

- pkg/cnservice/cnclient/client.go
- pkg/vm/engine/disttae/logtailPushModel.go
issue #
Some rpc client not set logger
> fix some rpc client logger not set

- pkg/vm/engine/tae/containers/types.go
- pkg/vm/engine/tae/containers/utils.go
- pkg/vm/engine/tae/containers/vector.go
- pkg/vm/engine/tae/containers/vector_test.go
- pkg/vm/engine/tae/db/db_test.go
- pkg/vm/engine/tae/mergesort/func.go
- pkg/vm/engine/tae/mergesort/mergesort_test.go
- pkg/vm/engine/tae/model/colview.go
- pkg/vm/engine/tae/moengine/engine_test.go
issue # https://github.com/matrixorigin/matrixone/issues/8648
Removing types.Null from DN vector for performance improvement
> [Refactor] Remove types.Null | Update()

- pkg/vm/engine/disttae/tools.go
- pkg/vm/engine/disttae/txn_database.go
- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/disttae/types.go
- test/distributed/cases/dml/update/flush.result
- test/distributed/cases/dml/update/flush.test
> disttae: init txnTable partitions once

- pkg/common/morpc/server.go
- pkg/lockservice/log.go
issue #8953 
fix dead lock after close server session
> morpc: fix dead lock after close server session

- pkg/vm/engine/tae/blockio/read.go
- pkg/vm/engine/tae/blockio/writer_test.go
- test/distributed/cases/dml/update/flush.result
- test/distributed/cases/dml/update/flush.test
issue #
merge deletes rather than overwriting
> fix merge deletes

- cmd/mo-service/config.go
- cmd/mo-service/main.go
> [bug] proxy: Add some condition for proxy service startup when use -cfg.

- pkg/sql/colexec/rightanti/join.go
- pkg/sql/colexec/rightsemi/join.go
> [Exec] Avoid sending empty batches during right SEMI/ANTI join probe

- pkg/objectio/writer.go
- pkg/objectio/writer_test.go
issue #
The data of the same column of multiple blocks are written together
> Change col data layout

- pkg/objectio/reader.go
> fix reader

- pkg/sql/plan/function/operator/cast2.go
> fix time convert bug

- pkg/container/vector/functionTools.go
This can improve performance of TPCH q1 for 1/3
issue #
> Preallocate result vector for CAST expression

- pkg/sql/compile/compile.go
issue #9013
force right join to execute on single cn due to right join issue
> force right join to execute on single cn

- pkg/sql/plan/stats.go
issue # mocloud 524
calc stats for values scan node
> calc stats for values scan node

- pkg/sql/colexec/merge/merge.go
- pkg/sql/colexec/merge/types.go
- pkg/sql/colexec/mergegroup/group.go
- pkg/sql/colexec/mergegroup/types.go
- pkg/sql/colexec/mergelimit/limit.go
- pkg/sql/colexec/mergelimit/types.go
- pkg/sql/colexec/mergeoffset/offset.go
- pkg/sql/colexec/mergeoffset/types.go
- pkg/sql/colexec/mergeorder/order.go
- pkg/sql/colexec/mergeorder/types.go
- pkg/sql/colexec/mergetop/top.go
- pkg/sql/colexec/mergetop/types.go
- pkg/vm/pipeline/types.go
…by limit or other operator
issue #8769 #8561
> fix a pipeline free bug may cause hung if next pipeline closed early

- pkg/objectio/codecs.go
- pkg/objectio/constructors.go
- pkg/objectio/funcs.go
- pkg/objectio/meta.go
- pkg/objectio/reader.go
- pkg/objectio/versions.go
- pkg/objectio/writer.go
- pkg/objectio/writer_test.go
> add codecs for objectio

- pkg/sql/colexec/table_function/table_function.go
- pkg/sql/colexec/table_function/unnest.go
> fix unnest bug in rawlog table

- pkg/sql/plan/function/operator/cast2.go
> Change scale when cast time to decimal

- pkg/sql/colexec/insert/insert.go
- pkg/sql/colexec/s3util.go
> [#8993]Fix 8993

- pkg/objectio/writer.go
> improve objectio's writer memory usage

- pkg/sql/plan/base_binder.go
> fix udf exec bug on constant fold

- go.mod
- go.sum
- pkg/frontend/test/txn_mock.go
- pkg/txn/client/client.go
- pkg/txn/client/operator.go
- pkg/txn/client/operator_test.go
- pkg/txn/client/types.go
- pkg/txn/storage/memorystorage/storage_txn_client.go
- pkg/vm/engine/disttae/engine.go
- pkg/vm/engine/disttae/types.go
- pkg/vm/engine/tae/moengine/txn_wrapper.go
> Add minimum active transaction timestamp

- pkg/catalog/catalog.go
- pkg/catalog/types.go
- pkg/objectio/location.go
- pkg/vm/engine/disttae/partition_state.go
- pkg/vm/engine/disttae/util.go
- pkg/vm/engine/disttae/util_test.go
- pkg/vm/engine/tae/blockio/read.go
- pkg/vm/engine/tae/db/db_test.go
issue #
Quickly modify the BlockInfo structure to a fixed length for improving serialization blockInfo
> Change BlockInfo

- pkg/vm/engine/tae/db/db_test.go
- pkg/vm/engine/tae/txn/txnimpl/basenode.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/622
> fix add blks with metaloc

- pkg/sql/colexec/auto_incr.go
- test/distributed/cases/auto_increment/auto_increment_columns.result
- test/distributed/cases/load_data/load_data_set_null.result
issue # https://github.com/matrixorigin/MO-Cloud/issues/622
> fix truncate table operation on auto_col

- pkg/vm/engine/tae/containers/batch.go
- pkg/vm/engine/tae/containers/types.go
- pkg/vm/engine/tae/containers/utils.go
- pkg/vm/engine/tae/containers/vector.go
- pkg/vm/engine/tae/containers/vector_test.go
- pkg/vm/engine/tae/logtail/tools.go
- pkg/vm/engine/tae/mergesort/func.go
- pkg/vm/engine/tae/model/pages.go
- pkg/vm/engine/tae/model/preparer.go
- pkg/vm/engine/tae/rpc/handle.go
- pkg/vm/engine/tae/tables/ablk.go
- pkg/vm/engine/tae/tables/functions.go
- pkg/vm/engine/tae/tables/functions_test.go
- pkg/vm/engine/tae/txn/txnbase/txn.go
- pkg/vm/engine/tae/txn/txnimpl/index.go
issue #
1. Remove unused API
2. Replace some old API implementations with new ones
3. Fix some bug
> changes to dn vector

- pkg/vm/engine/disttae/txn_database.go
- pkg/vm/engine/disttae/txn_table.go
> disttae: add txnTable.reset

- pkg/vm/engine/disttae/engine.go
- pkg/vm/engine/disttae/partition_reader.go
- pkg/vm/engine/disttae/txn.go
- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/disttae/types.go
issue #
fix concurrent map read and map write
> fix concurrent map read and map write

- pkg/vm/engine/disttae/txn.go
- pkg/vm/engine/disttae/txn_database.go
- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/disttae/txn_table_meta.go
- pkg/vm/engine/disttae/types.go
issue #
disttae: remove tableMeta.tableName; move tableMeta.modifedBlocks to txnTable.modifiedBlocks
disttae: remove tableMeta.defs
> disttae: remove tableMeta type

- pkg/proxy/client_conn.go
- pkg/proxy/event_test.go
- pkg/proxy/handler.go
- pkg/proxy/handler_test.go
- pkg/proxy/rebalancer_test.go
- pkg/proxy/router_test.go
- pkg/proxy/server_conn_test.go
- pkg/proxy/server_test.go
> proxy: replace tcp with unix socket in unit test.

- .github/workflows/e2e.yml
- .github/workflows/e2e_with_proxy.yml
- .github/workflows/e2e_with_push_model.yml
- .github/workflows/e2e_with_race.yml
- optools/run_bvt.sh
issue #
Add goroutines stacks if bvt failed
> tests: add goroutine stacks if bvt failed

- pkg/objectio/column.go
- pkg/objectio/writer.go
- pkg/vm/engine/tae/blockio/write_index.go
- pkg/vm/engine/tae/blockio/writer.go
> Set Block's Col Ndv&NullCnt

- pkg/vm/engine/disttae/txn.go
- pkg/vm/engine/disttae/txn_database.go
- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/disttae/types.go
> disttae: use getParts in Transaction.getBlockMetas

- pkg/vm/engine/disttae/stats.go
- test/distributed/cases/dml/insert/insert_duplicate.sql
- test/distributed/cases/dml/insert/on_duplicate_key.sql
- test/distributed/cases/foreign_key/fk_base.sql
- test/distributed/cases/foreign_key/foreign_key.sql
> [Bug]: execPlan serialize failed caused by NaN value

- pkg/common/cache/cache.go
- pkg/common/cache/cache_test.go
- pkg/common/cache/types.go
- pkg/frontend/mysql_cmd_executor.go
- pkg/frontend/mysql_cmd_executor_test.go
- pkg/frontend/session.go
- pkg/frontend/show_subsriptions.go
- pkg/sql/parsers/dialect/mysql/mysql_lexer.go
- pkg/sql/parsers/dialect/mysql/scanner.go
> Add parser cache for session

- pkg/pb/pipeline/pipeline.go
- pkg/sql/compile/compile.go
> fix load hung bug in multi-CN

- pkg/sql/colexec/external/external.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/628
> fix MO_CLOUD 628

- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/disttae/types.go
> disttae: also update logtail in getParts

- pkg/vm/engine/disttae/txn.go
- pkg/vm/engine/disttae/txn_table.go
issue #8016
Re-apply updates for commit `2d41f6`
> Reapply updates for commit 2d41f6

- pkg/vm/engine/disttae/stats.go
issue #8016
mo-service would panic with empty zonemap.
> Fix panic in order to run tpcc

- CODEOWNERS
issue #
Let @jianwan0214  and @qingxinhome  join the frontend maintainanence
> grant wangjian and xiliang to maintain the frontend

- pkg/objectio/meta.go
- pkg/objectio/meta_test.go
- pkg/objectio/writer.go
> BuildMetaData added for Test

- pkg/vm/engine/tae/compute/compute.go
- pkg/vm/engine/tae/index/zm.go
- pkg/vm/engine/tae/index/zm_test.go
issue #
Update zonemap to support ">", "<",">=","<=","="."and","or","+","-","*". It will be used by eval filter expression pushdown
> update zm to support some op and add related ut

- pkg/container/types/decimal.go
> Add comparison between two decimals with scales

- pkg/sql/plan/build_show.go
- test/distributed/cases/tenant/pub_sub.result
issue #9085 
show tables stmt and show table numbers stmt not display view for subscription database.
> fix subscription view error

- pkg/fileservice/disk_cache.go
- pkg/fileservice/disk_cache_test.go
- pkg/perfcounter/counter_set.go
> fileservice: fix DiskCache.Update

- pkg/frontend/authenticate.go
- pkg/frontend/authenticate_test.go
- test/distributed/cases/tenant/init_pub.result
- test/distributed/cases/tenant/init_pub.sql
issue #9076 
add a fliter for publishing database
> fix publishing other tenant's database error

- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/disttae/types.go
> [disttae]: remove some useless and time-consuming code

- pkg/sql/plan/stats.go
- pkg/vm/engine/disttae/stats.go
issue #7082
calc stats ndv using object metadata, remove useless code
now ndv is more accurate than before, and can get better join order for tpch q8 and q21
> [Enhancement]: refactoring stats

- pkg/vm/engine/disttae/txn_table.go
> Fix CN delete s3 bug 

- CODEOWNERS
- pkg/vm/engine/disttae/db.go
- pkg/vm/engine/disttae/engine.go
- pkg/vm/engine/disttae/logtail.go
- pkg/vm/engine/disttae/logtailPullModel.go
- pkg/vm/engine/disttae/logtailPushModel.go
- pkg/vm/engine/disttae/logtailreplay/encode.go
- pkg/vm/engine/disttae/logtailreplay/encode_test.go
- pkg/vm/engine/disttae/logtailreplay/partition.go
- pkg/vm/engine/disttae/logtailreplay/partition_state.go
- pkg/vm/engine/disttae/logtailreplay/partition_state_iterators.go
- pkg/vm/engine/disttae/logtailreplay/partition_state_iterators_test.go
- pkg/vm/engine/disttae/logtailreplay/partition_state_test.go
- pkg/vm/engine/disttae/logtailreplay/utils.go
- pkg/vm/engine/disttae/partition_reader.go
- pkg/vm/engine/disttae/tools.go
- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/disttae/types.go
- pkg/vm/engine/disttae/util.go
> disttae: separate logtail replay codes to logtailreplay package

- pkg/vm/engine/disttae/txn_table.go
issue #
The tests for delete s3 bug is right here : https://github.com/w-zr/matrixone/pulls, but I give the wrong pr for main.
> fix appendIds

- pkg/container/vector/tools.go
- pkg/container/vector/vector.go
- pkg/sql/colexec/constraint_util.go
- pkg/sql/colexec/projection/projection.go
- pkg/vm/engine/tae/blockio/read.go
> Reduce heap allocation in vector.ToConst

- pkg/fileservice/disk_cache.go
- pkg/fileservice/disk_cache_test.go
> fileservice: fix TestDiskCacheWriteAgain

- pkg/fileservice/cache.go
- pkg/fileservice/mem_cache.go
- pkg/fileservice/mem_cache_test.go
- pkg/fileservice/objcache/clockobjcache/clock.go
- pkg/fileservice/objcache/lruobjcache/lru.go
- pkg/perfcounter/counter_set.go
- pkg/util/metric/stats/counter.go
- pkg/vm/engine/tae/model/index.go
> fileservice: add FileServiceCounterSet.Memory.Available

- pkg/sql/colexec/connector/connector.go
- pkg/sql/colexec/deletion/deletion.go
- pkg/sql/colexec/dispatch/dispatch.go
- pkg/sql/colexec/hashbuild/build.go
- pkg/sql/colexec/intersect/intersect.go
- pkg/sql/colexec/intersectall/intersectall.go
- pkg/sql/colexec/lockop/lock_op.go
- pkg/sql/colexec/mergeblock/mergeblock.go
- pkg/sql/colexec/mergedelete/mergedelete.go
- pkg/sql/colexec/minus/minus.go
- pkg/sql/colexec/onduplicatekey/on_duplicate_key.go
- pkg/sql/colexec/product/product.go
- pkg/sql/colexec/restrict/restrict.go
- pkg/sql/colexec/right/join.go
- pkg/sql/colexec/top/top.go
- pkg/sql/colexec/update/update.go
> fix colexec operator bug will cause memory leak

- test/distributed/cases/statement_query_type/statement_query_type.result
- test/distributed/cases/statement_query_type/statement_query_type.sql
> Remove bvt tag 7772

- pkg/common/morpc/server.go
> morpc: fix ping not work

- pkg/sql/plan/function/operators.go
> add json not_equal

- pkg/sql/plan/stats.go
- pkg/vm/engine/disttae/stats.go
issue #
read zm on block using seqnum
> fix zm reading in calc stats

- pkg/sql/colexec/external/external.go
> improve load performance

- pkg/sql/plan/stats.go
issue #
something got wrong in stats, tpch join order remain unchanged, 
while degree of parallelism is not correct. fix stats selectivity calculation
> fix stats selectivity

- pkg/cnservice/cnclient/client.go
> cnclient: fix data race

- pkg/sql/plan/flatten_subquery.go
- pkg/sql/plan/utils.go
- test/distributed/cases/subquery/subquery-with-in.result
> Don't allow a quantified subquery's left operand to be a subquery

- pkg/fileservice/file_with_checksum.go
- pkg/fileservice/io_entry.go
- pkg/fileservice/pool.go
- pkg/fileservice/pool_test.go
- pkg/fileservice/profile.go
- pkg/vm/engine/disttae/db.go
- pkg/vm/engine/disttae/logtail.go
- pkg/vm/engine/disttae/txn_table.go
> fileservice: let caller of Pool.Get allocates

- pkg/objectio/funcs.go
- pkg/vm/engine/tae/blockio/funcs.go
- pkg/vm/engine/tae/blockio/read.go
issue #
Add blockio.LoadColumns without NewObjectReader.
Reduce the generation of small objects
> Add blockio.LoadColumns without NewObjectReader

- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/tae/rpc/handle.go
- pkg/vm/engine/tae/tables/base.go
- pkg/vm/engine/tae/tables/utils.go
- pkg/vm/engine/tae/txn/txnimpl/table.go
issue #
Remove MO unnecessary NewObjetcReader
Reduce the generation of small objects
> Remove MO unnecessary NewObjetcReader

- test/distributed/cases/function/mo_log_date.result
- test/distributed/cases/function/mo_log_date.sql
issue #
https://github.com/matrixorigin/matrixone/pull/7860
https://github.com/matrixorigin/matrixone/issues/7539
> mo_log_date

- pkg/vm/engine/tae/compute/compute.go
- pkg/vm/engine/tae/containers/batch.go
- pkg/vm/engine/tae/containers/factory.go
- pkg/vm/engine/tae/containers/types.go
- pkg/vm/engine/tae/containers/utils.go
- pkg/vm/engine/tae/containers/vector.go
- pkg/vm/engine/tae/containers/vector_test.go
- pkg/vm/engine/tae/model/preparer.go
- pkg/vm/engine/tae/tables/functions.go
- pkg/vm/engine/tae/tables/functions_test.go
- pkg/vm/engine/tae/txn/txnimpl/index.go
- pkg/vm/engine/tae/txn/txnimpl/relation.go
issue #
make dn vector be a pure wrapper of the cn vector
> some code update to dn vector

- optools/images/Dockerfile
issue #https://github.com/matrixorigin/matrixone/issues/9409
correct docker image startup args format
> correct docker image default startup args

- pkg/vm/engine/tae/db/base_test.go
- pkg/vm/engine/tae/db/db_test.go
- pkg/vm/engine/tae/logtail/utils.go
- pkg/vm/engine/tae/tables/jobs/compactblk.go
- pkg/vm/engine/tae/tables/jobs/mergeblocks.go
- pkg/vm/engine/tae/tables/txnentries/mergeblocks.go
- pkg/vm/engine/tae/txn/txnbase/handle.go
- pkg/vm/engine/tae/txn/txnimpl/block.go
- pkg/vm/engine/tae/txn/txnimpl/localseg.go
- pkg/vm/engine/tae/txn/txnimpl/relation.go
- pkg/vm/engine/tae/txn/txnimpl/segment.go
- pkg/vm/engine/tae/txn/txnimpl/table.go
issue #8841 
Use sync.Pool to reduce creating small objects
> reduce creating small objects

- pkg/pb/txn/txn.go
issue #9255 
Disable resuse tcp read buffer memory. Copy into TxnRequest.
> Fix dn panic

- pkg/vm/engine/tae/db/db_test.go
- pkg/vm/engine/tae/iface/data/block.go
- pkg/vm/engine/tae/index/zm.go
- pkg/vm/engine/tae/tables/ablk.go
- pkg/vm/engine/tae/tables/base.go
- pkg/vm/engine/tae/tables/blk.go
- pkg/vm/engine/tae/tables/indexwrapper/immutindex.go
- pkg/vm/engine/tae/tables/indexwrapper/mutindex.go
- pkg/vm/engine/tae/tables/indexwrapper/types.go
- pkg/vm/engine/tae/tables/indexwrapper/zonemapnode.go
- pkg/vm/engine/tae/tables/mnode.go
- pkg/vm/engine/tae/tables/pnode.go
- pkg/vm/engine/tae/tables/types.go
- pkg/vm/engine/tae/txn/txnimpl/anode.go
- pkg/vm/engine/tae/txn/txnimpl/localseg.go
- pkg/vm/engine/tae/txn/txnimpl/node.go
- pkg/vm/engine/tae/txn/txnimpl/store.go
- pkg/vm/engine/tae/txn/txnimpl/table.go
issue #8841 #9309 
Calculate ZM for the input data once
> optimize dn dedup

- pkg/fileservice/file_with_checksum.go
- pkg/fileservice/local_fs.go
- pkg/fileservice/pool.go
- pkg/fileservice/pool_test.go
- pkg/fileservice/profile.go
- pkg/vm/engine/disttae/db.go
- pkg/vm/engine/disttae/logtail.go
- pkg/vm/engine/disttae/txn_table.go
issue #
Rewrite pool code, without append and closure.    Easier to follow and (probably) more efficient.
Fixed a leak.
> Rewrite pool, to be a little bit simpler.

- pkg/vm/engine/disttae/txn_table.go
issue #
Remove one dependency of blockInfos
> remove one dependency of blockInfos

- pkg/sql/colexec/group/group.go
- pkg/sql/colexec/group/group_test.go
- pkg/sql/colexec/mergegroup/group.go
- pkg/sql/compile/compile.go
> Use Int64HashMap in group operator as much as possible

- pkg/sql/plan/stats.go
- pkg/sql/plan/utils.go
issue #
make stats more accurate, and get a better predicate order
> refactoring stats

- pkg/container/types/rowid.go
- pkg/container/types/rowid_test.go
- pkg/objectio/id_test.go
- pkg/sql/colexec/deletion/types.go
- pkg/vm/engine/disttae/logtailreplay/partition_state.go
- pkg/vm/engine/disttae/txn.go
- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/tae/catalog/catalog.go
- pkg/vm/engine/tae/db/gc/table.go
- pkg/vm/engine/tae/model/codec.go
issue #9008 
Update api design in order to reduce unnecessary heap allocation.
> Update api design in order to reduce unnecessary heap allocation;

- pkg/defines/type.go
- pkg/frontend/authenticate.go
- pkg/frontend/compiler_context.go
- pkg/frontend/mysql_cmd_executor.go
- pkg/frontend/plsql_interpreter.go
- pkg/sql/parsers/tree/branch.go
- pkg/sql/parsers/tree/compound.go
- pkg/sql/parsers/tree/procedure.go
- pkg/sql/plan/base_binder.go
- test/distributed/cases/procedure/procedure.result
- test/distributed/cases/procedure/procedure.sql
- test/distributed/cases/statement_query_type/statement_query_type.result
issue #
Currently, this implementation supports following features of stored procedure:
1. variable declaration and usage in any normal sql statements like 'select * from table where id = v1'.
2. dynamic and nested scoping
3. while / repeat / loop structure
4. if-elseif-else / case structure
5. Pass external parameters (system, global, session, user defined) into stored procedure with read or write privileges.
What this implementation does not support:
1. when two loops are nested, it currently cannot jump directly out of the outer loop using label. This will be fixed soon.
> sp_exec impl

- pkg/sql/compile/scopeRemoteRun.go
> fix a bug cause cn memory leak in the case of multi cn nodes.

- optools/bvt_ut/Dockerfile
> Update Dockerfile to support 1.20

- pkg/sql/colexec/evalExpression.go
- pkg/vm/engine/disttae/logtailPushModel.go
for hung issue #9343 #9368 #9378 
may help issue #9428 
fix a push model bug that will use stream in parallel.
fix a function framework bug that may cause memory leak.
modify some timeout log level of push model. and return error if subscribe table timeout.
> modify push model subscription/unsubscription to be serial

- pkg/sql/plan/deepcopy.go
- test/distributed/cases/statement_query_type/prepare.sql
- test/distributed/cases/statement_query_type/statement_query_type.result
Reverts matrixorigin/matrixone#9550
> Revert "copy PubAccountId in DeepCopyObjectRef"

- pkg/sql/plan/function/list_operator.go
- pkg/sql/plan/stats.go
- pkg/sql/plan/utils.go
> Re-enable IN filter on zonemaps after expr refactor

- pkg/sql/compile/scope.go
Reverts matrixorigin/matrixone#9620
> Revert "fix tcp unclosed error"

- pkg/vm/engine/tae/blockio/read.go
issue #
blockread is called at high freq, lower the log level
> change read log lvl

- test/distributed/cases/tenant/pub_sub.result
- test/distributed/cases/tenant/pub_sub.sql
issue #9588 
add bvt test for pub_sub
> add bvt test for pub_sub

- pkg/fileservice/retry.go
- pkg/fileservice/s3_fs.go
https://github.com/matrixorigin/MO-Cloud/issues/483#issuecomment-1556764537
s3 requests may throw errors when reading, just retry.
> fileservice: add retry function to retry s3 reading requests

- pkg/perfcounter/context.go
- pkg/perfcounter/context_test.go
issue #
Allow copy perf counters from another context
> perfcounter: add WithCounterSetFrom

- pkg/container/hashtable/hash.go
- pkg/sql/colexec/dispatch/sendfunc.go
- pkg/sql/colexec/dispatch/types.go
- pkg/sql/colexec/hashbuild/build.go
- pkg/sql/compile/compile.go
- pkg/sql/plan/shuffle.go
issue #
for integer,use mod to get shuffle result, which is not random enough.
call wyhash64 function before mod, to make the result random enough.
> improve the performance of shuffle

- pkg/container/hashtable/hash.go
- pkg/sql/colexec/dispatch/sendfunc.go
- pkg/sql/colexec/dispatch/types.go
- pkg/sql/compile/compile.go
- pkg/sql/plan/shuffle.go
Reverts matrixorigin/matrixone#9676
> Revert "improve the performance of shuffle"

- .github/workflows/chatgpt_review.yaml
- .github/workflows/mo_checkin_regression.yaml
- optools/mo_checkin_regression/mo_checkin_regression.yaml
issue #
1. mo checkin is triggered only when the .go, .c, .h  file is modified
2. add comparision with previous run
3. collect the log which echo to stdout
4. add chatgpt to help review code in pr
5. collect etl log in s3 only when run failed
> CI: Optimize mo checkin

- pkg/hakeeper/checkers/cnservice/check.go
issue https://github.com/matrixorigin/MO-Cloud/issues/669
> [improvement] hakeeper: add some logs to help find bug.

- pkg/container/hashtable/hash.go
- pkg/lockservice/service_remote_test.go
- pkg/sql/colexec/dispatch/sendfunc.go
- pkg/sql/colexec/dispatch/types.go
- pkg/sql/compile/compile.go
- pkg/sql/plan/shuffle.go
issue #
last time, the hash function use rand number as seed, which leads to different results in multi cn.
now we use fixed number as seed in hash function.
> resubmit "improve the performance of shuffle"

- pkg/vm/engine/disttae/db.go
- pkg/vm/engine/disttae/engine.go
- pkg/vm/engine/disttae/logtailPushModel.go
- pkg/vm/engine/disttae/logtailreplay/partition.go
- pkg/vm/engine/disttae/stats.go
- pkg/vm/engine/disttae/txn.go
- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/disttae/types.go
issue #
1.  There is only 1 dn now and in the near future
2.  The current multi-dn code is messy and not tested. Just remove them all. 
3.  We need to reimplement related logic when supporting multi-dn in the future.
TODO:
Change the output of engine.Relation.Ranges.
> remove some untested and messy multi-dn related code

- pkg/vm/engine/disttae/logtailPushModel.go
- pkg/vm/engine/disttae/logtailPushModel_test.go
> fix a push model bug that may cause parallel writing

- pkg/common/moerr/error.go
issue #9528 
promote the error message of the backend close more readable
> change backend close's error message

- pkg/common/morpc/backend.go
- pkg/common/morpc/backend_test.go
- pkg/common/morpc/server_test.go
issue #6997
fix stream write and read blocking each other
> fix stream write and read blocking each other

- pkg/vm/engine/tae/logtail/service/client.go
issue #
Add more log for logtail client to facilitate debug.
> Add more log to facilitate debug

- .github/workflows/chatgpt_review.yaml
issue #
use other action to provide review helper and  this workflow is triggered only when the PR is opened
> CI: use other action to provide review helper

- pkg/vm/engine/tae/catalog/catalog.go
- pkg/vm/engine/tae/logtail/types.go
- pkg/vm/engine/tae/logtail/utils.go
issue #
SortHint is used in DedupSnapByPK now, it is required to add it to checkpoint
> add seg node in ckp

- pkg/vm/engine/disttae/logtailPushModel.go
> Fix a possible go-routine leak when push model reconnect

- pkg/container/batch/batch.go
- pkg/sql/colexec/insert/insert.go
- pkg/sql/colexec/mergeblock/types.go
issue #
Fix bug where attributes are missing when writing to S3
thanks @nnsgmsone & @matrix-meow
> Fix bug where attributes are missing when writing to S3

- pkg/vm/engine/disttae/logtailPushModel.go
> fix a bug cause reconnect hung. and return err for query while reconnecting.

- pkg/lockservice/service.go
issue #
Concurrent locking can cause multiple creation of active objects for the same transaction, resulting in missed lock releases
> fix lock txn create more times

- pkg/sql/compile/compile.go
- pkg/sql/plan/base_binder.go
- pkg/sql/plan/explain/explain_expr.go
- pkg/sql/plan/join_order.go
- pkg/sql/plan/opt_misc.go
- pkg/sql/plan/partition_test.go
- pkg/sql/plan/query_builder.go
- pkg/sql/plan/shuffle.go
- pkg/sql/plan/stats.go
- pkg/sql/plan/utils.go
issue #9747
For shuffle group, it will be possible to do filter before merge, which should be better than merge then filter.
> Put HAVING clause into AGG node

- pkg/txn/rpc/server.go
issue #9447
Add warn logger to help debug.
> add some logger for debug

- pkg/sql/compile/compile.go
issue #7066 
In rc mode, if need to retry, then  need to clean up the effect of the last statement so that  can ensure correctness
> Clean up the effect of failed statement on retry

- pkg/cnservice/types.go
- pkg/sql/compile/compile.go
- pkg/txn/client/operator.go
- pkg/txn/client/operator_test.go
- pkg/vm/engine/disttae/types.go
issue #
Fix conflict txn retry not work in rc mode.
> fix retry conflict txn in rc mode

- pkg/common/morpc/server.go
issue #
It is possible to deadlock when close and write are called concurrently in morpc server
> fix hung when close session and write concurrently

- pkg/vm/engine/disttae/logtailPushModel.go
- pkg/vm/engine/tae/logtail/service/client.go
- pkg/vm/engine/tae/logtail/service/server_test.go
> change timeout check code position of push model, add more logs in log tail client.

- pkg/common/bitmap/bitmap.go
- pkg/container/nulls/nulls.go
- pkg/container/nulls/nulls_test.go
- pkg/vm/engine/tae/blockio/read.go
issue #9309 
Using nulls.Bitmap in block reader
> using delete mask in block read

- pkg/bootstrap/bootstrap.go
- pkg/bootstrap/bootstrap_test.go
- pkg/bootstrap/log.go
- pkg/cnservice/server.go
issue #
Add more log for bootstrap.
> add more log for bootstrap

- pkg/sql/compile/scope.go
- pkg/vm/engine/disttae/reader.go
- pkg/vm/engine/tae/blockio/read.go
- pkg/vm/engine/tae/blockio/writer_test.go
- pkg/vm/engine/tae/db/db_test.go
issue #9309 
1. Change block read API to support filter
2. Optimize for the disttae blockReader to use the filter
3. This PR can improve sysbench point select
> change block read to support filter and optimize sysbench point select

- go.mod
- go.sum
- pkg/fileservice/s3_fs.go
fileservice: more comments for s3 fs
issue #
For loading Aliyun credentials with aliyun SDK
> fileservice: add aliyun credential provider for s3 fs

- pkg/vm/engine/disttae/logtailreplay/rows_iter.go
- pkg/vm/engine/disttae/logtailreplay/rows_iter_test.go
- pkg/vm/engine/disttae/txn_table.go
> logtailreplay: add exact, prefix, min-max primary key iter

- pkg/common/morpc/backend.go
- pkg/common/morpc/backend_test.go
- pkg/common/morpc/future.go
- pkg/common/morpc/future_test.go
- pkg/common/morpc/server.go
- pkg/sql/compile/compile.go
This reverts commit 8b3bb776a13d0a13625c77005959b60c2ee612bc.
issue #
> Revert "Add ping timeout (#9845)"

- pkg/vm/engine/tae/options/options.go
- pkg/vm/engine/tae/txn/txnimpl/table.go
issue #9348 
fix r-w conflict bug
> fix r-w conflict

- go.mod
- go.sum
- pkg/fileservice/s3_fs.go
- pkg/fileservice/s3_fs_credentials.go
> fileservice: add credentials provider for Tencent Cloud

- pkg/vm/engine/disttae/logtailPushModel.go
> fix a log tail client bug may cause response lost

- pkg/sql/compile/compile.go
- pkg/sql/compile/scopeRemoteRun.go
- pkg/sql/compile/types.go
> Disable runtime filter on multi CN

- pkg/fileservice/retry.go
- pkg/fileservice/s3_fs.go
> fileservice: more logging for retry

- pkg/lockservice/btree_storage.go
- pkg/lockservice/lock_table_local.go
- pkg/lockservice/lock_table_local_test.go
- pkg/lockservice/lock_table_remote.go
- pkg/lockservice/log.go
- pkg/lockservice/storage_test.go
- pkg/lockservice/txn.go
- pkg/lockservice/txn_test.go
- pkg/lockservice/types.go
issue #9856 
fix merge range lock errors.
> lockservice: fix lock range merge bugs

- pkg/container/vector/vector.go
- pkg/sql/compile/scope.go
- pkg/sql/compile/scopeRemoteRun.go
> Fix data inconsistency bug

- pkg/sql/colexec/evalExpression.go
- pkg/sql/colexec/window/window.go
- test/distributed/cases/window/window.result
- test/distributed/cases/window/window.sql
> fix shuffle in window func

- pkg/logservice/store.go
- pkg/logservice/store_hakeeper_check.go
- pkg/logservice/store_hakeeper_check_test.go
- pkg/logservice/store_test.go
Reverts matrixorigin/matrixone#9775
> Revert "fix #8599: move task schedule to a separate goroutine"

- pkg/vm/engine/tae/rpc/handle.go
issue #
When an error is returned during the HandleCommit process, the txn's context will not be released. However, w-w conflicts will occur in 90% of the cases running tpcc, so fix this bug
> Fix the bug in HandleCommit where error does not release txn's context

- pkg/incrservice/service.go
- pkg/incrservice/service_test.go
- pkg/incrservice/store_mem.go
- pkg/incrservice/store_sql.go
- pkg/incrservice/types.go
- pkg/sql/compile/sql_executor.go
- pkg/util/executor/options.go
- pkg/util/executor/types.go
> fix bvt w-w conflict

- .github/workflows/mo_checkin_regression.yaml
> CI: modify the sequence of process

- .github/workflows/mo_checkin_regression.yaml
> CI: Pauses performance comparison error log output

- pkg/fileservice/s3_fs.go
issue #
Aliyun and Tencent Cloud credential providers may not be compatible with the aws credential cache, don't use it.
> fileservice: do not cache 3rd-party credential providers

- pkg/fileservice/s3_fs.go
- pkg/fileservice/s3_fs_credentials.go
https://github.com/matrixorigin/MO-Cloud/issues/897
> fileservice: disable 3rd-party s3 credentials

- pkg/fileservice/retry.go
- pkg/fileservice/s3_fs.go
issue #
fix the s3 retryer according to https://github.com/aws/aws-sdk-go-v2/issues/543
> fileservice: fix s3 retryer

- pkg/frontend/mysql_protocol.go
> [bug] fix bug that connectAttrs map is nil.

- pkg/sql/colexec/right/join.go
- pkg/sql/plan/stats.go
issue # https://github.com/matrixorigin/MO-Cloud/issues/444  https://github.com/matrixorigin/MO-Cloud/issues/456
fix stats for left join and right join, to get right join order and improve performance
> fix stats for left join and right join

- pkg/sql/colexec/hashbuild/build.go
- pkg/sql/plan/query_builder.go
- pkg/sql/plan/runtime_filter.go
> Enable runtime filter on composite primary key

- pkg/vm/engine/disttae/logtailPushModel.go
> fix a push bug may set client ready when log tail time is still 0

- pkg/sql/plan/build_dml_util.go
- pkg/sql/plan/runtime_filter.go
> Use runtime filter to handle primary key constraint

- pkg/vm/engine/tae/mergesort/func.go
- pkg/vm/engine/tae/mergesort/mergesort.go
- pkg/vm/engine/tae/mergesort/types.go
- pkg/vm/engine/tae/tables/base.go
- pkg/vm/engine/tae/tables/jobs/compactblk.go
- pkg/vm/engine/tae/tables/jobs/mergeblocks.go
- pkg/vm/engine/tae/tables/txnentries/compactblk.go
issue #9143 
Reduce some memory allocations during the merge sort
> reduce some memory allocations 

- pkg/sql/plan/function/baseTemplate.go
- pkg/sql/plan/function/func_binary.go
- pkg/sql/plan/function/func_builtin.go
- pkg/sql/plan/function/func_builtin_regexp.go
- pkg/sql/plan/function/function.go
- pkg/sql/plan/function/list_builtIn.go
> optimize some function and remove unused code.

- pkg/vm/engine/tae/tables/ablk.go
- pkg/vm/engine/tae/tables/block_test.go
- pkg/vm/engine/tae/tables/mnode.go
- pkg/vm/engine/tae/tables/pnode.go
- pkg/vm/engine/tae/tables/types.go
issue #
Refactor block-related code for the further optimization
> refactor block related code

- pkg/sql/plan/agg_pushdown_pullup.go
- pkg/sql/plan/runtime_filter.go
- pkg/sql/plan/stats.go
issue #
optimize some api function for stats
> minor refactor of stats

- pkg/incrservice/allocator.go
issue #10046
check ctx timeout in async goroutine, to avoid async callback deadlock if ctx timeout
> check ctx timeout in async goroutine

- pkg/vm/engine/tae/rpc/handle.go
- pkg/vm/engine/tae/rpc/handle_test.go
issue #9971
DN will keep the cached request forever if CN fails to commit|rollback (crash, network error, etc).
> Clean rpc handle txn cache for invlid

- pkg/fileservice/error.go
- pkg/fileservice/s3_fs.go
> fileservice: retry on dns lookup error

- pkg/incrservice/allocator.go
Reverts matrixorigin/matrixone#10066
> Revert "check ctx timeout in async goroutine"

- pkg/vm/engine/tae/catalog/block.go
- pkg/vm/engine/tae/db/db_test.go
- pkg/vm/engine/tae/iface/data/block.go
- pkg/vm/engine/tae/iface/txnif/types.go
- pkg/vm/engine/tae/tables/ablk.go
- pkg/vm/engine/tae/tables/base.go
- pkg/vm/engine/tae/tables/txnentries/compactblk.go
- pkg/vm/engine/tae/tables/txnentries/mergeblocks.go
- pkg/vm/engine/tae/tables/updates/cmd.go
- pkg/vm/engine/tae/tables/updates/command_test.go
- pkg/vm/engine/tae/tables/updates/delchain.go
- pkg/vm/engine/tae/tables/updates/delete.go
- pkg/vm/engine/tae/tables/updates/mvcc.go
- pkg/vm/engine/tae/txn/txnbase/store.go
- pkg/vm/engine/tae/txn/txnbase/txn.go
- pkg/vm/engine/tae/txn/txnimpl/store.go
This reverts commit 799f557f192ef663b9f858a7ffa44abbeb34d95d.
issue #
There are some unexpected duplicate errors during the merge run TPCC test. Need further debugging offline
> Revert "release delete nodes when compact (#10073)"

- pkg/vm/engine/disttae/txn_table.go
Reverts matrixorigin/matrixone#10085
> Revert "fix datarace of pkey in tableDef"

- pkg/container/types/rowid.go
- pkg/vm/engine/tae/tables/txnentries/compactblk.go
issue #
- if compact conflict, delete appanedable block file and newly created block file
> better file check

- pkg/vm/engine/tae/tables/txnentries/compactblk.go
issue #
Not GC nablk deletes when compact, because nablk doesn't flush deletes.
> fix ApplyCommit of compaction

- .github/workflows/mo_checkin_regression.yaml
- optools/mo_checkin_regression/mo_checkin_regression.yaml
issue #
1. remove some useless code
2. only run tpch tests if loading tpch data succeeds
3.only run tpcc tests if loading tpcc data succeeds
> CI: optimize mo checkin regression

- .github/workflows/mo_checkin_regression.yaml
> mo checkin regression bug fix

- .github/workflows/mo_checkin_regression.yaml
> Bug fix in mo checkin

- .github/workflows/mo_checkin_regression.yaml
> fix sometime cp file fail

- test/distributed/cases/ddl/alter_table_AddDrop_column.result
- test/distributed/cases/ddl/alter_table_AddDrop_column.sql
> add bvt tag for rename

- pkg/vm/engine/tae/tables/base.go
issue #8841 
1. Avoid using AppendAny
2. Using VectorPool
> small code update for collect deletes

- pkg/vm/engine/tae/db/checkpoint/entry.go
- pkg/vm/engine/tae/db/checkpoint/runner.go
- pkg/vm/engine/tae/db/task.go
issue #9982
Add more information to debug
- print errors in background compacting jobs
- print dirty tree if do incremental checkpoint slowly
> add dirty tree and task error log

- pkg/sql/plan/deepcopy.go
issue #5004
Fix select for update miss copy field in deep copy in build plan
> fix miss copy field in deep copy

- pkg/vm/engine/tae/db/db_test.go
- pkg/vm/engine/tae/txn/txnimpl/table.go
issue #9348 #10128 
1. Add R-W-related UT
2. Fix a bug that may introduce unexpected errors
> fix r-w related error

- pkg/sql/plan/deepcopy.go
> revert 10130

- pkg/vm/engine/tae/db/gc/delete.go
- pkg/vm/engine/tae/rpc/inspect.go
issue https://github.com/matrixorigin/MO-Cloud/issues/916
export all catalog info can be too large for MySQL client, it is better to inspect a specific table. And print GCed files
> dn inspect cmd support table level

- .github/workflows/mo_checkin_regression.yaml
> change the method for get cn pod name

- go.mod
issue #
based on the meeting offline, we use matrixorigin/goetty.
> change goetty repo

- pkg/vm/engine/tae/tables/base.go
issue #8841 
Make the block compaction TTL calculation more reasonable.
> reduce compaction frequency

- pkg/vm/engine/tae/catalog/catalog.go
- pkg/vm/engine/tae/tables/mnode.go
- pkg/vm/engine/tae/txn/txnbase/mvccnode.go
issue #
it is a valid fix only when snapshot read is supported. for now, it has no effect.
1. It always uses "mode" for "ablk" after replaying from the checkpoint, which is not right.
2. lazy create mnode.data
> fix replay from checkpoint 

- cmd/mo-service/launch.go
- go.sum
- pkg/vm/engine/tae/catalog/catalog.go
- pkg/vm/engine/tae/tables/mnode.go
- pkg/vm/engine/tae/txn/txnbase/mvccnode.go
> Fengttt revert

- .github/workflows/mo_checkin_regression.yaml
> CI: enable clean env when cancel

- pkg/vm/engine/disttae/txn_table.go
issue #9665 
1. fix tiny bug for `rangesOnePart ` function
> fix tiny bug for rangesOnePart

- pkg/common/hashmap/inthashmap.go
- pkg/vectorize/sum/sum.go
issue #926
* Fix the bug of out-of-bound write
* remove cgo dependencies, cgo and recover do not work together, I will subsequently remove all cgo's from make
> Fix the bug of out-of-bound write

- cmd/mo-service/launch.go
- go.sum
This reverts commit c244ab836bdeb31b1e49610dccb0663dded26ab8.
issue #
this policy cause performance regression and fluctuation problem.
> Revert "Resubmit calling FreeOSMemory every minute. (#10196)"

- go.sum
issue #
imported by https://github.com/matrixorigin/matrixone/pull/10259
> fix go.sum by go mod tidy

- pkg/vm/engine/disttae/logtailPushModel.go
> fix push model routine leak.

- pkg/vm/engine/disttae/db.go
- pkg/vm/engine/disttae/engine.go
- pkg/vm/engine/disttae/logtail.go
- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/disttae/txn_table_test.go
- pkg/vm/engine/disttae/types.go
issue #
expose the packer pool for pipeline
> disttae: expose Engine.PackerPool

- pkg/frontend/test/engine_mock.go
- pkg/frontend/test/txn_mock.go
- pkg/vm/engine/disttae/db.go
- pkg/vm/engine/disttae/engine.go
- pkg/vm/engine/disttae/logtail.go
- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/disttae/txn_table_test.go
- pkg/vm/engine/disttae/types.go
- pkg/vm/engine/memoryengine/table.go
- pkg/vm/engine/types.go
> engine: add Relation.PrimaryKeysMayBeModified

- go.mod
- go.sum
> update goetty version in go.mod to support timeout when Connect.

- pkg/vm/engine/tae/catalog/catalog.go
- pkg/vm/engine/tae/tables/mnode.go
- pkg/vm/engine/tae/txn/txnbase/mvccnode.go
issue #
it is a valid fix only when snapshot read is supported. for now, it has no effect.
1. It always uses "mode" for "ablk" after replaying from the checkpoint, which is not right.
2. create mnode.data lazily
> resubmit 10187

- pkg/vm/engine/disttae/logtailPushModel.go
- pkg/vm/engine/disttae/logtailPushModel_test.go
issue #10294 
help #10138 
1.  fix a reconnect deadlock bug which cause 10294 hung.
2. add debug log for issue #10138
> fix a possible deadlock if lost connection with DN while unsubscribing tables.

- pkg/frontend/mysql_cmd_executor.go
- pkg/util/trace/impl/motrace/buffer_pipe_test.go
- pkg/util/trace/impl/motrace/report_statement.go
- pkg/util/trace/impl/motrace/statistic/stats_array.go
- pkg/util/trace/impl/motrace/statistic/stats_array_test.go
- test/distributed/cases/log/query_stats.result
- test/distributed/cases/log/query_stats.sql
issue #10319
Add `StatsArray` to help format stats array.
> Serialize stats as json-array

- pkg/container/vector/vector.go
> use three dword instruction to speed up function BuildVarlena

- pkg/sql/plan/function/baseTemplate.go
> remove an unnecessary type conversion at function template.

- cmd/mo-service/launch.go
> [bug] fix a non-stop for loop caused by context deadline error.

- pkg/vm/engine/disttae/reader.go
issue #
Fix a potential bug handling filtering:
For example:
PK Columns: [2,3,4]
Filter Expr Columns: [2,3]
The output pk columns should be [2,3], but now it is [2,3,4]
> fix a potential bug handing filtering

- .github/workflows/ci.yml
- .github/workflows/robot.yml
issue #
refactor workflow structure
> refactor workflow structure

- .github/mergify.yml
issue #
Do not declare required checks in the configuration file, use branch protection rules for management
> CI: modify the setting of mergify

- pkg/vm/engine/tae/containers/pool.go
- pkg/vm/engine/tae/db/dbutils/mem.go
- pkg/vm/engine/tae/db/dbutils/runtime.go
issue #
Add new stats in the vector pool to monitor pool usage.
> update vector pool stats

- pkg/frontend/computation_wrapper.go
- pkg/frontend/types.go
issue #
fix bug: when retry in lock error. the prepare batch was cleaned
> fix bug: when retry in lock error. the prepare batch was cleaned

- pkg/vm/engine/tae/tables/base.go
This reverts commit 57e14ebc1ad01e83d6d9d4c662223d4d753bfe9a.
issue #
Prepared insert performance degradation
> Revert "Resubmit opt compact (#10207)"

- pkg/sql/colexec/insert/insert.go
- pkg/sql/colexec/s3util.go
- pkg/vm/engine/disttae/txn.go
* add more comments about S3writers
* will refactor initialization logic for S3Writer later
https://github.com/matrixorigin/MO-Cloud/issues/949
> continue fix (#10074)

- pkg/sql/colexec/lockop/lock_op.go
issue #10298 
skip empty cached batches for blocking lock
> skip empty cached batches for blocking lock

- pkg/fileservice/disk_cache.go
> fileservice: add by-path read/write locks to disk cache

- cmd/mo-service/debug.go
- pkg/fileservice/profile.go
- pkg/fileservice/profile_test.go
> fileservice: refactor ProfileHandler

- pkg/sql/plan/query_builder.go
issue #10318 #10312 #10297
fix bug: pk idx is incorrect in select for update
> fix bug: pk idx is incorrect in select for update

- pkg/vm/engine/disttae/txn_table.go
issue #10394
Blocks will have different col info because of ddl
Add a check before getting meta info
> fix the metadata scan panic issue after ddl

- .github/workflows/release.yml
> change runner to ubuntu-20.04 to make glibc version to 2.31

- pkg/sql/compile/compile.go
- pkg/vm/process/types.go
issue #
fix bug: valueScanBatch was cleaned when retry
> fix bug: valueScanBatch was cleaned when retry

- .github/workflows/release.yml
> debug: pull repo from corresponding branch

- cmd/mo-service/main.go
- etc/launch-tae-CN-tae-DN/dn.toml
- etc/launch-tae-compose/config/dn.toml
- etc/launch-tae-multi-CN-tae-DN/dn.toml
- etc/launch-with-proxy/dn.toml
- etc/launch/dn1.toml
- pkg/cnservice/types.go
- pkg/dnservice/cfg.go
- pkg/dnservice/cfg_test.go
- pkg/dnservice/factory.go
- pkg/dnservice/store.go
- pkg/dnservice/store_test.go
- pkg/frontend/session.go
- pkg/tests/service/dnservice.go
- pkg/tests/service/service.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/960
1、add cfg to set max prepare stmt count
2、base CN.Txn.Mode to set the default value of CN.txn.isolation 
set SI when mode is optimistic,  set  RC when mode is pessimistic
> add cfg to set max prepare stmt count

- pkg/sql/plan/build_dml_util.go
issue #10438
Solve the problem of wrong offset of partition expression in batch
> fix insert partition table offset error

- etc/launch-tae-compose/config/cn-0.toml
- etc/launch-tae-compose/config/cn-1.toml
- etc/launch-tae-compose/config/dn.toml
issue #
Fix docker compose config
> fix docker-compose config

- pkg/bootstrap/bootstrap.go
- pkg/hakeeper/checker.go
- pkg/hakeeper/task/task_scheduler.go
- pkg/hakeeper/task/task_scheduler_test.go
- pkg/logservice/service_bootstrap.go
- pkg/logservice/service_wrap.go
- pkg/sql/plan/base_binder.go
- pkg/tests/service/logservice.go
- pkg/tests/service/service.go
issue #
Create system init task in `pkg/bootstrap` instead of hakeeper.
> create systeminit task in bootstrap pkg

- pkg/fileservice/cache.go
- pkg/fileservice/example_test.go
- pkg/fileservice/local_fs.go
- pkg/fileservice/local_fs_test.go
- pkg/fileservice/s3_fs.go
- pkg/fileservice/s3_fs_test.go
- pkg/util/export/etl/csv_test.go
> fileservice: refactor CacheConfig

- pkg/hakeeper/task/task_scheduler.go
issue #10310
prolong task timeout limit
> prolong task timeout limit

- pkg/sql/plan/utils.go
issue # https://github.com/matrixorigin/MO-Cloud/issues/948
fix a bug in stats which cause panic
> [User Bug]:insert导入dmt_001数据集报错

- pkg/fileservice/s3_fs.go
> fileservice: fix 3rd-party credentials provider

- pkg/vm/engine/tae/logtail/service/session.go
issue #
fix TestSession introduced by #10493
> fix TestSession

- etc/launch-tae-multi-CN-tae-DN/cn1.toml
- etc/launch-tae-multi-CN-tae-DN/cn2.toml
- etc/launch-tae-multi-CN-tae-DN/dn.toml
- pkg/cnservice/types.go
- pkg/dnservice/cfg.go
> Just set pessimistic to run pessimistic.    Config is still by default, optimistic.

- pkg/util/trace/impl/motrace/buffer_pipe.go
> fix a bug that can stop the stmt recording

- .github/workflows/robot.yml
> Fix the problem of incorrect coverage statistics

- pkg/fileservice/disk_cache.go
- pkg/fileservice/local_fs.go
- pkg/fileservice/mem_cache.go
- pkg/fileservice/profile.go
- pkg/fileservice/profile_test.go
- pkg/fileservice/s3_fs.go
- pkg/vm/engine/disttae/logtailreplay/partition_state.go
issue #10452 
refine the profiler
> fileservice: refactor profile handler

- pkg/frontend/authenticate.go
issue #10538 
fix wrong system variables tuple number in mo_compatibility_mode
> fix wrong system variables tuple number

- pkg/frontend/mysql_cmd_executor.go
issue #10192
dump goroutine info when sql run timeout
> dump goutine info when sql run timeout

- pkg/sql/plan/build_dml_util.go
issue #
extract the appendLockNode function
本来是根据田博士建议，计划该函数后，对于无pk的表，不再增加lock节点。
不过跟张旭确认，这类情况也要加lock节点。
那就单纯作为小重构吧。
> refactor:   extract the appendLockNode function

- pkg/util/trace/config.go
- pkg/util/trace/impl/motrace/mo_trace.go
- pkg/util/trace/impl/motrace/mo_trace_test.go
- pkg/util/trace/impl/motrace/report_statement.go
- pkg/util/trace/trace.go
- pkg/util/trace/type.go
issue #
fix span NeedProfile and add doc.
> fix span NeedProfile and add doc.

- pkg/sql/plan/build_dml_util.go
This reverts commit 37f565d8c397675ba9d790379b6ee6fd0c1533c6.
issue #
合并后，main分支在悲观事务下会无法启动。找了半天没找到原因。
> Revert "refactor:   extract the appendLockNode function (#10544)"

- pkg/fileservice/s3_fs.go
- pkg/fileservice/s3_fs_credentials.go
[issue #](https://github.com/matrixorigin/MO-Cloud/issues/706)
> fileservice: handle role arn in aliyun and qcloud credentials providers

- pkg/sql/compile/compile.go
- test/distributed/cases/dml/update/update.result
- test/distributed/cases/dml/update/update.test
issue #10502 
fix bug: lost project node in select for update
> fix bug: lost project node in select for update

- pkg/sql/plan/function/func_builtin.go
> fix hash_value function bug will cause result unstable in one machine.

- pkg/fileservice/s3_fs.go
- pkg/fileservice/s3_fs_credentials.go
> fileservice: s3 credential provider clean-ups

- pkg/dnservice/cfg.go
- pkg/dnservice/factory.go
- pkg/frontend/txn.go
- pkg/frontend/util.go
- pkg/sql/compile/scope.go
- pkg/tests/service/dnservice.go
- pkg/txn/storage/tae/storage.go
issue #
The dnservice will not use other log drivers, so set it to logservice in the code
> Remove the extra configuration items of dnservice

- pkg/sql/compile/compile.go
- pkg/vm/process/types.go
issue #10562
fix the AnalyzeInfo wrong issue which is due to no reset
> fix the AnalyzeInfo wrong issue which is due to no reset

- test/distributed/cases/database/config_1.result
- test/distributed/cases/database/config_1.sql
issue #10567 
add bvt test for priv check
> add bvt test for priv check

- pkg/lockservice/lock_table_local.go
- pkg/lockservice/lock_table_local_test.go
- pkg/lockservice/lock_table_remote.go
- pkg/lockservice/waiter.go
- pkg/lockservice/waiter_test.go
issue #
Fix waiter reference count incorrectly, cause mem allocate
> fix waiter reference count incorrectly

- pkg/fileservice/s3_fs.go
- pkg/fileservice/s3_fs_credentials.go
fileservice: verify s3 credential provider
issue #
> fileservice: add rrsa credential to aliyun

- cmd/mo-service/main.go
- pkg/common/morpc/examples/pingpong/main.go
- pkg/common/morpc/examples/stream/main.go
- pkg/testutil/testengine/testdata.go
issue #
fix sca check, remove log pkg usage by using logutil.
> remove log pkg usage

- pkg/sql/colexec/evalExpression.go
- pkg/vm/process/types.go
issue #
fix bug: not deal with null for execute stmt
> fix bug: not deal with null for execute stmt

- pkg/frontend/mysql_protocol.go
- test/distributed/cases/dml/select/select.result
- test/distributed/cases/dml/select/select.test
issue #10507 
fix bug: send bool result incorrect
> fix bug: send bool result incorrect

- etc/launch-tae-CN-tae-DN/cn.toml
- etc/launch-tae-CN-tae-DN/dn.toml
- etc/launch-tae-compose/config/cn-0.toml
- etc/launch-tae-compose/config/cn-1.toml
- etc/launch-tae-compose/config/dn.toml
- etc/launch-with-proxy/dn.toml
- etc/launch/cn1.toml
- etc/launch/dn1.toml
- pkg/cnservice/server.go
- pkg/cnservice/types.go
- pkg/sql/colexec/s3util.go
Reduce config matrix and test complexity.
issue #
> Auto set transaction related configs.

- pkg/vm/engine/disttae/types.go
issue #
* fix statement out-of-bounds within workspace
> Fix statement out-of-bounds within workspace

- .github/workflows/merge-trigger.yaml
> not notice when pr closed

- pkg/fileservice/s3_fs_credentials.go
[issue #](https://github.com/matrixorigin/matrixone/issues/10666)
> fileservice: disable aliyun and qcloud credentials

- cmd/mo-service/config.go
- etc/bootstrap-example2/dn-node-1.toml
- etc/bootstrap-example2/dn-node-2.toml
- etc/cn-minimal-test.toml
- etc/cn-non-dist-memory.toml
- etc/cn-standalone-dist-tae-test.toml
- etc/cn-standalone-dist-tae.toml
- etc/cn-standalone-test.toml
- etc/dn-minimal-s3-test.toml
- etc/dn-minimal-test.toml
- etc/launch/cn1.toml
- etc/launch/dn1.toml
- etc/launch/log1.toml
- etc/launch/log2.toml
- etc/launch/log3.toml
- etc/log-minimal-test.toml
[issue #](https://github.com/matrixorigin/matrixone/issues/10621)
>  fileservice: clean-up config files; add default disk cache path 

- pkg/sql/plan/build_insert.go
issue #10703 
fix bug: check pk dup with uuid panic
> fix bug: check pk dup with uuid panic

- cmd/mo-service/config.go
issue #
handle rename before create default file services
> mo-service: fix file service creation

- go.mod
- go.sum
- pkg/fileservice/profile.go
- pkg/fileservice/profile_info.go
- pkg/fileservice/profile_span.go
- pkg/fileservice/profile_span_test.go
- pkg/fileservice/profile_statement.go
> fileservice: add span profiler

- pkg/sql/plan/stats.go
issue #10707
it multi columns contains all primary keys, that must be high ndv columns.
> add primary key in join order

- pkg/cnservice/types.go
- pkg/frontend/session.go
> change cfg : max prepare statement to 10w

- pkg/sql/plan/build_dml_util.go
- test/distributed/cases/dml/update/update.result
- test/distributed/cases/dml/update/update.test
issue #10720 
fix bug: incorrect schema name was used
> fix bug: incorrect schema name was used

- .github/workflows/merge-trigger.yaml
> CI: change timeout settings

- pkg/fileservice/file_service.go
- pkg/fileservice/file_service_test.go
- pkg/fileservice/local_etl_fs.go
- pkg/fileservice/local_fs.go
- pkg/fileservice/memory_fs.go
- pkg/fileservice/s3_fs.go
> fileservice: add IOVector.Hash

- pkg/sql/compile/sql_executor.go
issue #10750
Log error in internal executor.
> log err in internal executor

- pkg/fileservice/local_fs.go
- pkg/fileservice/profile_span.go
- pkg/fileservice/profile_statement.go
- pkg/fileservice/s3_fs.go
…tatementProfiler
issue #10452
> fileservice: span related chagnes

- pkg/sql/colexec/shuffle/shuffle.go
- pkg/sql/colexec/shuffle/types.go
> optimize shuffle by sending multi batches when running

- pkg/vm/engine/disttae/txn_database.go
- pkg/vm/engine/disttae/txn_table.go
Reverts matrixorigin/matrixone#10454
> Revert "fix data race for the proc of txnTable"

- pkg/sql/plan/build_load.go
> fix bug: LoadTag was commented

- pkg/txn/client/operator.go
- pkg/vm/engine/disttae/txn.go
- pkg/vm/engine/disttae/types.go
issue #10712 
missing unlock if txn workspace commit failed.
> fix missing unlock

- pkg/vm/engine/disttae/logtailreplay/partition_state.go
- pkg/vm/engine/disttae/logtailreplay/primary_key_utils.go
- pkg/vm/engine/disttae/logtailreplay/rows_iter.go
- pkg/vm/engine/disttae/logtailreplay/rows_iter_test.go
logtailreplay: add PrimaryIndexEntry.Time
issue #
> logtailreplay: refactor PrimaryKeyMayBeModified

- cmd/mo-service/config.go
- etc/launch-tae-CN-tae-DN/log.toml
- etc/launch-tae-compose/config/log.toml
- etc/launch-tae-multi-CN-tae-DN/log.toml
- etc/launch-with-proxy/log.toml
- pkg/logservice/config.go
- pkg/logservice/config_test.go
- pkg/logservice/hakeeper_client_test.go
- pkg/logservice/service_commands_test.go
- pkg/logservice/service_test.go
- pkg/logservice/store_hakeeper_check_test.go
- pkg/logservice/store_metadata_test.go
- pkg/logservice/store_test.go
- pkg/logservice/testclient.go
> [refactor] logservice: set default config values.

- pkg/sql/compile/scope.go
- pkg/sql/compile/scopeRemoteRun.go
> allow the last operator can be both connector and dispatch

- pkg/fileservice/mem_cache.go
…te with multi goruotines
issue #10659
too large queue may causes memory spike.
>  fileservice: remove async update from memory cache 

- pkg/vm/engine/disttae/txn_database.go
- pkg/vm/engine/disttae/txn_table.go
> Lock fix data race pass tpcc

- pkg/util/trace/impl/motrace/mo_trace.go
> motrace: handle per statement profiler in span begin and end

- pkg/frontend/mysql_cmd_executor.go
> frontend: add per statement profiler

- pkg/sql/colexec/evalExpression.go
> fix an expression bug will cause race when vector is const null.

- pkg/sql/plan/bind_context.go
- pkg/sql/plan/order_binder.go
- pkg/sql/plan/query_builder.go
- pkg/sql/plan/types.go
- pkg/sql/plan/utils.go
- test/distributed/cases/distinct/distinct.result
- test/distributed/cases/expression/case_when.result
- test/distributed/cases/expression/case_when.sql
- test/distributed/cases/expression/temporal_interval.result
- test/distributed/cases/function/func_aggr_avg.result
- test/distributed/cases/function/func_aggr_bitwise.result
- test/distributed/cases/function/func_aggr_count.result
- test/distributed/cases/function/func_aggr_max.result
- test/distributed/cases/function/func_aggr_min.result
- test/distributed/cases/function/func_aggr_std.result
- test/distributed/cases/function/func_aggr_variance.result
- test/distributed/cases/function/func_cast.result
- test/distributed/cases/function/func_math_round.result
- test/distributed/cases/function/func_string_concat_ws.result
- test/distributed/cases/function/func_string_findinset.result
- test/distributed/cases/function/func_string_length.result
> [Plan] Support using alias in GROUP BY/HAVING clause

- pkg/sql/colexec/table_function/processlist.go
> [bug] fix bug that where condition not work for processlist function.

- pkg/sql/compile/scope.go
- pkg/sql/compile/scopeRemoteRun.go
Reverts matrixorigin/matrixone#10669
> Revert "allow the last operator can be both connector and dispatch"

- pkg/lockservice/deadlock.go
- pkg/lockservice/lock_table_allocator.go
- pkg/lockservice/lock_table_keeper_test.go
- pkg/lockservice/lock_table_remote_test.go
- pkg/lockservice/rpc.go
- pkg/lockservice/rpc_test.go
- pkg/lockservice/service.go
- pkg/lockservice/service_remote.go
- pkg/lockservice/types.go
issue #10731 
Fetch txn's waiting list maybe block remote lock. Make handle fetch waiting list asynchronous
> fix fetch txn waiting list will block lockservice

- test/distributed/cases/statement_query_type/statement_query_type.sql
- [ X] Test and CI
issue #10793 
add bvt issue tag for error case related issue #10793
> add bvt tag for issue 10793

- pkg/txn/client/operator.go
issue #
make default ignore rc unexpected errors.
> fix check rc errors

- pkg/sql/compile/compile.go
issue #9747
improve shuffle join performance by add channel buffer size
> [Performance]: Implement shuffle group/join

- pkg/vm/engine/disttae/logtailreplay/partition_state.go
- pkg/vm/engine/disttae/logtailreplay/primary_key_utils.go
- pkg/vm/engine/disttae/logtailreplay/rows_iter.go
- pkg/vm/engine/disttae/logtailreplay/rows_iter_test.go
- pkg/vm/engine/disttae/txn_table.go
> disttae: various logtail fixes

- pkg/sql/plan/build_delete.go
- pkg/sql/plan/build_insert.go
- pkg/sql/plan/build_update.go
- pkg/sql/plan/stats.go
issue #10841
recalculate query stats for IUD query
> [Bug]: Overestimation of cost in tpcc

- pkg/sql/colexec/deletion/types.go
- pkg/vm/engine/disttae/engine.go
- pkg/vm/engine/disttae/txn_database.go
- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/disttae/types.go
issue #
* Fixed time range when replacing rowid
* Remove some of the weird logic from writing s3
> Fix some bugs of workspace

- pkg/sql/compile/ddl.go
issue #10867 
Fix ddl locking. Ignore retry errors until all tables are locked to avoid multiple retries.
> fix ddl locking

- pkg/sql/compile/compile.go
- pkg/vm/engine/disttae/txn_table.go
issue #
* mark writes3 flag to abort transaction with retry
> Mark writes3 to abort transaction in rc

- pkg/lockservice/service.go
> fix lockservice panic

- pkg/vm/engine/disttae/db.go
- pkg/vm/engine/disttae/engine.go
issue #10386
please check the issue page
> fix race in catalog cache

- test/distributed/cases/view/view-subquery-with-in.sql
issue #
https://github.com/matrixorigin/matrixone/issues/10712
> removeTags

- pkg/vm/engine/disttae/logtailreplay/blocks_iter.go
- pkg/vm/engine/disttae/logtailreplay/partition_state.go
- pkg/vm/engine/disttae/txn_table.go
> logtailreplay: code clean-ups

- test/distributed/cases/pessimistic_transaction/isolation_2.sql
issue #
https://github.com/matrixorigin/matrixone/issues/10742
> remove tag 10742

- pkg/vm/engine/disttae/logtailreplay/partition_state.go
- pkg/vm/engine/disttae/logtailreplay/primary_key_utils.go
- pkg/vm/engine/disttae/logtailreplay/rows_iter_test.go
> logtailreplay: fix missing primary key info in rows delete

- pkg/vm/engine/tae/containers/batch.go
- pkg/vm/engine/tae/containers/batch_test.go
- pkg/vm/engine/tae/containers/pool.go
issue #
Add a NewBatchWithPool to create batch with a vector pool
> add new batch with pool 

- pkg/fileservice/local_fs.go
- pkg/fileservice/s3_fs.go
- pkg/fileservice/s3_fs_credentials.go
- pkg/fileservice/s3_fs_test.go
> fileservice: add session token param to s3 credential

- pkg/sql/compile/scope.go
issue #10656 
Add more log in order to record detailed information for cn panic.
> add log for 10656

- pkg/fileservice/disk_cache.go
- pkg/fileservice/file_service.go
- pkg/fileservice/mem_cache.go
> fileservice: add IOEntry.fromCache to reduce unnecessary cache update

- pkg/fileservice/objcache/lruobjcache/lru.go
- pkg/fileservice/objcache/lruobjcache/lru_test.go
This reverts commit 1c70e2f03c6577ce75bfe2119b09be7180f55ab5.
issue #
> Revert "lruobjcache: improve performance of LRU.Get (#10952)"

- pkg/sql/colexec/merge/merge.go
- pkg/sql/colexec/mergecte/mergecte.go
- pkg/sql/colexec/mergerecursive/mergerecursive.go
> fix send recursive bat order

- etc/launch-tae-compose/compose.yaml
issue #10887
bond logservice's 42345:12345 while docker-compose do startup, that helps to pprof
> bond logservice's 42345:12345 while docker-compose do startup

- pkg/common/morpc/cfg.go
- pkg/txn/client/timestamp_waiter.go
issue #
rpc server handle requests chan size not set
> missing set queue default size

- pkg/vm/engine/tae/containers/batch.go
- pkg/vm/engine/tae/containers/batch_test.go
- pkg/vm/engine/tae/containers/types.go
issue #
Add a batch splitter to split a batch into several batches with the same size.
> add a batch splitter

- pkg/sql/colexec/window/window.go
- test/distributed/cases/window/window.result
- test/distributed/cases/window/window.sql
> fix window partition order

- pkg/sql/colexec/hashbuild/build.go
issue #
reduce memory allocation of sels
> optimize hashmap memory allocation 

- pkg/sql/compile/scopeRemoteRun.go
issue #
fix the issue which might lost error when the remote run end with dispatch
> fix the issue which mignt lost error 

- pkg/sql/colexec/onduplicatekey/on_duplicate_key.go
Reverts matrixorigin/matrixone#11012
> Revert "handle on duplicate key issue"

- pkg/proxy/client_conn.go
- pkg/proxy/client_conn_test.go
- pkg/proxy/event.go
- pkg/proxy/event_test.go
- pkg/proxy/handler_test.go
- pkg/proxy/server_conn_test.go
> [feature] proxy: replay prepared stmt on connection migration.

- pkg/container/vector/vector.go
> optimize varlena function by reducing copy cost

- test/distributed/cases/dml/insert/insert_duplicate.sql
issue #10848
add skip label for ‘on duplicate key’ bvt test case
> add skip label for bvt test case

- pkg/vm/engine/tae/rpc/handle.go
- pkg/vm/engine/tae/tables/jobs/mergeblocks.go
fix issue #10981
log issue #11020
> fix merge empty blocks and log duplicate batch

- pkg/cnservice/server.go
issue #
fix max active txn config not work
> fix limit max active txn config not work

- pkg/vm/engine/tae/db/test/compatibility/cases.go
- pkg/vm/engine/tae/db/test/compatibility/registry.go
issue #
update for compatibility ut
> update for compatibility ut

- .github/workflows/merge-trigger.yaml
This reverts commit 55c6296be82dd4139e12192bfe221e541da91c13.
issue #
> Revert "CI: add custom test to merge run (#11096)"

- pkg/vm/engine/tae/containers/types.go
- pkg/vm/engine/tae/containers/vector.go
- pkg/vm/engine/tae/containers/vector_test.go
issue #
DN vector wrapper supports const vector
> dn vector wrapper supports const vector

- pkg/txn/client/client.go
- pkg/txn/client/client_test.go
- pkg/txn/client/operator.go
issue #11036
Only user transactions need to be controlled for the maximum number of active transactions.
> add user txn flag

- pkg/fileservice/bytes.go
- pkg/fileservice/cache.go
- pkg/fileservice/caching_file_service_test.go
- pkg/fileservice/example_test.go
- pkg/fileservice/file_service.go
- pkg/fileservice/file_service_test.go
- pkg/fileservice/io_entry.go
- pkg/fileservice/local_etl_fs.go
- pkg/fileservice/local_fs.go
- pkg/fileservice/lrucache/lru.go
- pkg/fileservice/mem_cache.go
- pkg/fileservice/mem_cache_test.go
- pkg/fileservice/rc_bytes.go
- pkg/objectio/constructors.go
- pkg/objectio/funcs.go
- pkg/objectio/writer_test.go
- pkg/vm/engine/tae/blockio/funcs.go
- pkg/vm/engine/tae/blockio/reader.go
> fileservice: add CacheData, CacheDataAllocator; use Bytes as default cache data type

- pkg/txn/service/service_cn_handler.go
issue #11085
add commit slow log.
> add commit slow log

- .github/workflows/e2e-compose.yml
- optools/compose_bvt/entrypoint.sh
> CI: modify the healthcheck for compose mo cluster

- pkg/frontend/session.go
- pkg/frontend/variables.go
issue #11168 
fix unexpected errors in log
> fix unexpected errors in log

- pkg/incrservice/column_cache.go
issue #10204
fix incrservice auto_increment overflow error msg
> fix incrservice auto_increment overflow error msg

- pkg/vm/engine/disttae/txn_database.go
issue #
print id to distinguish tables with the same name
> print account id and db id of not found table

- pkg/sql/plan/shuffle.go
> fix a bug that cause wrong shuffle method

- pkg/sql/colexec/agg/new.go
[issue matrixone/MO-Cloud/#1145](https://github.com/matrixorigin/MO-Cloud/issues/1145)
> remove batchfill in agg

- pkg/vm/engine/tae/blockio/pipeline.go
- pkg/vm/engine/tae/blockio/pipeline_test.go
- pkg/vm/engine/tae/logstore/sm/safeq.go
- pkg/vm/engine/tae/logstore/sm/sm_test.go
- pkg/vm/engine/tae/logstore/sm/types.go
issue #
the prefetch queue is supposed to be non-blocking.
> set prefetch queue to unblocking

- pkg/container/hashtable/common.go
- pkg/container/hashtable/int64_hash_map.go
- pkg/container/hashtable/string_hash_map.go
> Determine hashtable load factor by size

- pkg/container/hashtable/common.go
- pkg/container/hashtable/int64_hash_map.go
- pkg/container/hashtable/string_hash_map.go
> Use 256MB blocks instead of 1GB in hash table

- .github/workflows/merge-trigger.yaml
issue #
get the results of tpcc and sysbench
> add result summary for merge run

- pkg/sql/colexec/table_function/metadata_scan.go
> better location output in metadata scan

- pkg/vm/engine/disttae/reader.go
- pkg/vm/engine/tae/rpc/handle.go
issue #
Quickly fix the panic bug of prefetch
> Quickly fix the panic bug of prefetch

- pkg/sql/colexec/limit/limit.go
- pkg/sql/colexec/top/top.go
- pkg/sql/compile/scope.go
- pkg/sql/plan/build_dml_util.go
- pkg/sql/plan/explain/explain_query.go
- test/distributed/cases/dml/insert/insert_duplicate.sql
issue #10848 
fix bug: reset dmlPlanCtx incorrect
thanks @qingxinhome @nnsgmsone @sukki37 @m-schen
> fix bug: reset dmlPlanCtx incorrect

- pkg/frontend/variables.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/1199
add system variable sql_log_bin and gtid_purged
> add system variable sql_log_bin and gtid_purged

- test/distributed/cases/ddl/alter_table_change_column.result
- test/distributed/cases/ddl/alter_table_change_column.sql
- test/distributed/cases/pessimistic_transaction/atomicity.result
- test/distributed/cases/pessimistic_transaction/atomicity.sql
- test/distributed/cases/pessimistic_transaction/transaction_enhance.result
- test/distributed/cases/pessimistic_transaction/transaction_enhance.sql
issue #
https://github.com/matrixorigin/matrixone/issues/10380
> alter table change column case

- pkg/util/trace/impl/motrace/mo_trace_test.go
issue # https://github.com/matrixorigin/matrixone/issues/11287
fix ut - TestContextDeadlineAndCancel
- it is base test case: deadline or canceled.
- the original deadline time is too short in UT run env to verify to result.
> fix ut - time sensitive case

- pkg/vm/engine/tae/containers/batch.go
- pkg/vm/engine/tae/tables/base.go
> fix dn panic when collecting deletes

- pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
- pkg/sql/parsers/dialect/mysql/scanner.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/1200
support more hint content
> support more hint content

- pkg/vm/engine/tae/blockio/read.go
- pkg/vm/engine/tae/rpc/handle.go
- pkg/vm/engine/tae/tables/updates/mvcc.go
> fix prefetchDeleteRowID

- pkg/sql/colexec/agg/distagg.go
issue #
https://github.com/matrixorigin/MO-Cloud/issues/1157
> fix disagg bug

- pkg/vm/engine/tae/rpc/handle.go
issue #10677 
https://github.com/matrixorigin/MO-Cloud/issues/1180
> fix bug for creating table with large number of attributes

- pkg/cnservice/types.go
Reverts matrixorigin/matrixone#11313
> Revert "set default max active user transactions"

- pkg/sql/plan/explain/explain_node.go
> add more information about shuffle plan in explain

- pkg/vm/engine/disttae/logtailPushModel.go
may help https://github.com/matrixorigin/MO-Cloud/issues/947
> add context check in push model to avoid routine leak

- .github/workflows/ci.yml
- .github/workflows/e2e-compose.yml
- .github/workflows/e2e-standalone.yml
- .github/workflows/e2e_upgrade.yml
- .github/workflows/merge-trigger.yaml
> modify regex to cover 1.0.0-rc on branch `1.0.0-rc`

- .github/workflows/ci.yml
- .github/workflows/e2e-compose.yml
- .github/workflows/e2e-standalone.yml
- .github/workflows/e2e_upgrade.yml
- .github/workflows/merge-trigger.yaml
- .github/workflows/robot.yml
> CI: regex bug fix and set LC_ALL in wework yaml

- test/distributed/cases/dtype/enum.result
- test/distributed/cases/dtype/enum.sql
issue #
https://github.com/matrixorigin/matrixone/issues/6613
> add enum case

- .github/workflows/merge-trigger.yaml
> CI: show more info for mo cluster

- pkg/fileservice/disk_cache.go
- pkg/fileservice/disk_cache_test.go
- pkg/fileservice/file_service.go
- pkg/fileservice/file_service_bench_test.go
- pkg/fileservice/file_services.go
- pkg/fileservice/io_entry.go
- pkg/fileservice/local_etl_fs.go
- pkg/fileservice/local_fs.go
- pkg/fileservice/memory_fs.go
- pkg/fileservice/s3_fs.go
- pkg/fileservice/sub_path.go
This reverts commit 41cad4b1f2a8ff5e09e03f1f21ca6b78a26d7899.
issue #
> Revert "fileservice: add FileService.ReadCache (#11357)"

- pkg/vm/engine/tae/db/dbutils/runtime.go
- pkg/vm/engine/tae/db/open.go
- pkg/vm/engine/tae/txn/txnimpl/table.go
- pkg/vm/engine/tae/txn/txnimpl/txn_test.go
- pkg/vm/engine/tae/txn/txnimpl/txndb.go
part fix for issue #11020 
use ts from the clock to check transfer deletes
> get transfer check ts from clock

- cmd/mo-service/main.go
- pkg/fileservice/s3_fs.go
- pkg/objectio/cache.go
- pkg/perfcounter/context.go
- pkg/perfcounter/context_test.go
- pkg/util/metric/mometric/metric.go
- pkg/util/metric/mometric/stats_log_writer.go
- pkg/util/metric/mometric/stats_log_writer_test.go
- pkg/vm/engine/disttae/reader.go
- pkg/vm/engine/disttae/reader_test.go
- pkg/vm/engine/tae/blockio/pipeline.go
issue #11235 
adding stats for block read, so we can analyze the mem cache hit info.
> adding codes to collect mem and disk cache info when read blocks

- test/distributed/cases/ddl/alter_table_add_drop_primary_key.sql
- test/distributed/cases/ddl/alter_table_change_column.sql
- test/distributed/cases/ddl/alter_table_modify_column.sql
- test/distributed/cases/ddl/alter_table_rename_column.sql
issue #
https://github.com/matrixorigin/matrixone/issues/11406
> add bvt tag 11406

- pkg/frontend/authenticate.go
- pkg/frontend/authenticate_test.go
- pkg/frontend/mysql_cmd_executor.go
Revert commit https://github.com/matrixorigin/matrixone/pull/11353.
> Revert "skip set ep for select into with stage"

- pkg/vm/engine/tae/db/checkpoint/runner.go
- pkg/vm/engine/tae/db/test/db_test.go
- pkg/vm/engine/tae/tables/updates/delchain.go
- pkg/vm/engine/tae/tables/updates/mvcc.go
issue #
found this bug when debugging #10527
It is dangerous to release the lock during LoopChain, which may lead to skipping some visible delete nodes
> fix loop chain by retry

- pkg/sql/plan/build_dml_util.go
- pkg/sql/plan/query_builder.go
> fix dml cte and col alias

- .github/workflows/ci.yml
- .github/workflows/e2e-compose.yml
- .github/workflows/e2e-standalone.yml
- .github/workflows/e2e_upgrade.yml
- .github/workflows/robot.yml
- pkg/cnservice/types.go
- pkg/dnservice/cfg.go
- pkg/dnservice/cfg_test.go
issue #11417 
change default transaction mode from Optimistic  to Pessimistic
> build on ouyuanning:change-def-tx-mode

- .github/workflows/merge-trigger.yaml
- .github/workflows/release.yml
- .github/workflows/robot.yml
- optools/compose_bvt/entrypoint.sh
> Ci env migration

- pkg/sql/plan/build_dml_util.go
- pkg/vm/engine/disttae/cache/catalog.go
- pkg/vm/engine/disttae/cache/table_guard.go
- pkg/vm/engine/disttae/cache/table_guard_test.go
- pkg/vm/engine/disttae/cache/types.go
- pkg/vm/engine/disttae/engine.go
- pkg/vm/engine/disttae/txn.go
- test/distributed/cases/pessimistic_transaction/isolation.result
- test/distributed/cases/pessimistic_transaction/isolation.sql
- test/distributed/cases/pessimistic_transaction/transaction_enhance.result
- test/distributed/cases/pessimistic_transaction/transaction_enhance.sql
Reverts matrixorigin/matrixone#11418
> Revert "fix bug: get latest schema when retry to run SQL"

- pkg/vm/engine/disttae/txn_table.go
> fix bug for ranges

- pkg/frontend/authenticate.go
- pkg/frontend/authenticate_test.go
- pkg/frontend/mysql_cmd_executor.go
- pkg/proxy/client_conn.go
- pkg/proxy/handshake.go
- pkg/proxy/label_info.go
- pkg/proxy/label_info_test.go
- pkg/proxy/util.go
- pkg/proxy/util_test.go
issue #11413 
Change the delimiter from ":" to "=", the labels info is not correct.
Do some refactors to fix it.
> [bug] frontend: fix the show backend servers error.

- pkg/lockservice/lock_table_local.go
- pkg/lockservice/lock_table_local_test.go
- pkg/lockservice/txn.go
- pkg/lockservice/waiter.go
This reverts commit e283530113dce17195f180910c2559a4f772a7f6.
issue #
Revert
> Revert "fix missing deadlock check (#11507)"

- pkg/sql/compile/scopeRemoteRunTypes.go
issue #
need to fix this in the future. for now, increase it to make tpch1T can run on 3 CN
> increase HandleNotifyTimeout from 120s to 300s

- pkg/vm/engine/tae/catalog/block.go
- pkg/vm/engine/tae/db/test/db_test.go
- pkg/vm/engine/tae/tables/updates/delchain.go
- pkg/vm/engine/tae/tables/updates/mvcc.go
- pkg/vm/engine/tae/txn/txnimpl/block.go
issue #11404 
- Fix persisted timestamp getter
- Get persisted timestamp from the chain if it is empty
> fix missing deletes after restarting

- pkg/container/types/decimal.go
- pkg/sql/plan/function/func_cast.go
> optimize Decimal operation by adding some in-place function

- pkg/vm/engine/tae/db/checkpoint/testutils.go
- pkg/vm/engine/tae/db/test/db_test.go
- pkg/vm/engine/tae/db/test/replay_test.go
- pkg/vm/engine/tae/db/testutil/engine.go
issue #11549 #11335
Change timeout from 1s to 2s, flushInterval from 400ms to 10ms
> fix UT, update force flush

- pkg/sql/plan/associative_law.go
- pkg/sql/plan/query_builder.go
> [Enhancement]: support associative rule in join order

- test/distributed/cases/foreign_key/foreign_key.result
- test/distributed/cases/foreign_key/foreign_key.sql
- test/distributed/cases/pessimistic_transaction/atomicity.result
- test/distributed/cases/pessimistic_transaction/atomicity.sql
- test/distributed/cases/pessimistic_transaction/transaction_enhance.sql
- test/distributed/cases/recursive_cte/recursive_cte1.result
- test/distributed/cases/recursive_cte/recursive_cte1.sql
> add fk cases and remove issue tag

- pkg/vm/engine/tae/catalog/block.go
- pkg/vm/engine/tae/catalog/catalog.go
- pkg/vm/engine/tae/catalog/database.go
- pkg/vm/engine/tae/db/test/db_test.go
- pkg/vm/engine/tae/db/test/hidden_test.go
- pkg/vm/engine/tae/db/testutil/engine.go
- pkg/vm/engine/tae/iface/data/block.go
- pkg/vm/engine/tae/iface/handle/relation.go
- pkg/vm/engine/tae/tables/base.go
- pkg/vm/engine/tae/tables/mnode.go
- pkg/vm/engine/tae/tables/pnode.go
- pkg/vm/engine/tae/tables/updates/mvcc.go
- pkg/vm/engine/tae/txn/txnimpl/relation.go
issue #
fix in memory collect deletes https://github.com/matrixorigin/matrixone/pull/11542
fix AddColumnCnt https://github.com/matrixorigin/matrixone/pull/11486
fix data race in get persisted TS https://github.com/matrixorigin/matrixone/pull/11571
> fix in memory collect deletes

- pkg/sql/compile/scope.go
- pkg/txn/client/client.go
- pkg/txn/client/types.go
- pkg/vm/engine/disttae/db.go
- pkg/vm/engine/disttae/logtailPushModel.go
- pkg/vm/engine/disttae/logtailreplay/partition.go
- pkg/vm/pipeline/pipeline.go
- pkg/vm/pipeline/types.go
issue #
source pr #11558 #11580
> pick stability fixed commit from main to 1.0rc

- pkg/vm/engine/tae/catalog/block.go
- pkg/vm/engine/tae/db/test/db_test.go
- pkg/vm/engine/tae/tables/updates/delchain.go
- pkg/vm/engine/tae/txn/txnimpl/block.go
- Fix persisted timestamp getter
- Get persisted timestamp from the chain if it is empty
issue #
> pick fix missing deletes after restarting (#11541) for 1.0

- test/distributed/cases/window/window.result
- test/distributed/cases/window/window.sql
issue #
https://github.com/matrixorigin/mo-nightly-regression/issues/99
> add window case

- pkg/sql/plan/stats.go
> adjust join order for tpch q10

- .github/workflows/merge-trigger.yaml
> CI: fix sysbench bug

- test/distributed/cases/window/window.result
- test/distributed/cases/window/window.sql
> modify some case and result

- pkg/container/types/decimal.go
- pkg/sql/plan/function/arithmetic.go
- pkg/sql/plan/function/func_cast.go
> [Enhancement]: optimize decimal arith by processing batch

- .github/workflows/merge-trigger.yaml
- .github/workflows/release.yml
- .github/workflows/robot.yml
> CI: change runner for some actions in `1.0.0-rc1` branch

- pkg/sql/colexec/dispatch/types.go
- pkg/sql/colexec/server.go
- pkg/sql/colexec/types.go
> fix a uuid map bug will cause hung if query ends early

- pkg/sql/compile/scope.go
> fix a remote run bug may return error for succeed query.

- pkg/sql/colexec/join/join.go
- pkg/sql/colexec/join/types.go
> split large batch in inner join

- pkg/sql/colexec/join/join.go
- pkg/sql/colexec/join/types.go
This reverts commit 74bda48af43399cfc3390e6dda8edc6170828dea.
issue #
> Revert "split large batch in inner join (#11673)"

- .github/workflows/merge-trigger.yaml
> CI: debug path error

- .github/workflows/merge-trigger.yaml
> CI: add darwin arm64 bvt test to 1.0.0-rc1

- .github/workflows/merge-trigger.yaml
> CI: collect trace before clean env

- .github/workflows/merge-trigger.yaml
> CI: get pprof after test

- pkg/vm/engine/tae/catalog/catalog.go
- pkg/vm/engine/tae/catalog/database.go
- pkg/vm/engine/tae/db/test/db_test.go
- pkg/vm/engine/tae/db/test/hidden_test.go
- pkg/vm/engine/tae/iface/handle/relation.go
- pkg/vm/engine/tae/txn/txnimpl/relation.go
> fix AddColumnCnt (#11486)

- pkg/container/vector/search.go
issue matrixorigin/MO-Cloud#1289
> Fix a boundary check bug for binary search

- .github/workflows/merge-trigger.yaml
> update merge run in 1.0-dev branch

- .github/workflows/merge-trigger.yaml
> update merge run in 1.0.0-rc1 branch 

- test/distributed/cases/pessimistic_transaction/transaction_enhance.sql
> alter wrong cases

- pkg/common/morpc/backend_test.go
- pkg/common/morpc/future.go
issue #11838 
If future notified twice before Get, rpc will hung.
> fix future will hung if notified twice before Get

- test/distributed/cases/pessimistic_transaction/transaction_enhance.sql
issue #
modify some wrong cases that have used lock wait tag
> modify lock wait tag for some wrong cases

- go.mod
- go.sum
- pkg/objectio/versions.go
issue #11703 
The root cause of "not found" is that xorfilter has a bug, which causes the built bloom filter data to be abnormal, so updating the xorfilter version can solve the bug.
> Update xorfilter version

- pkg/incrservice/store_sql.go
issue #11851 
Add some logs to help found incr service cannot allocate new value.
> add bug fatal log in incrservice

- go.mod
- go.sum
- pkg/common/morpc/client.go
- pkg/frontend/mysql_cmd_executor_test.go
- pkg/frontend/routine_test.go
- pkg/frontend/test/txn_mock.go
- pkg/frontend/test/types_mock.go
- pkg/incrservice/store_sql.go
- pkg/objectio/versions.go
- pkg/sql/colexec/lockop/lock_op.go
- pkg/sql/plan/shuffle.go
- pkg/txn/client/client.go
- pkg/txn/client/operator.go
- pkg/txn/client/types.go
- pkg/txn/storage/memorystorage/storage_txn_client.go
- pkg/vm/engine/entire_engine_test.go
- test/distributed/cases/pessimistic_transaction/transaction_enhance.sql
excluding:20831a8ed278ad6be9aa795292da0427d981e2f3
> Cherrypick dcfb3e4 156b90c

- pkg/lockservice/rpc.go
issue #11860
TN received a not support RPC, return error instead of fatal
> return error if received a invalid  request

- .github/workflows/merge-trigger.yaml
> CI: exclude optimized case in merge run

- .github/workflows/merge-trigger.yaml
> CI: change bvt sockes timeout to 300000 in merge run

- pkg/vm/engine/tae/db/test/db_test.go
- pkg/vm/engine/tae/tables/base.go
- pkg/vm/engine/tae/tables/updates/mvcc.go
> fix collect deletes

- pkg/common/morpc/backend_test.go
- pkg/common/morpc/message.go
issue #11964 #11957
Fix context deadline not set  when send heartbeat message
> fix heartbeat context deadline not set

- pkg/lockservice/lock_table_local_test.go
- pkg/lockservice/service.go
- pkg/lockservice/service_forward.go
- pkg/lockservice/service_forward_test.go
- pkg/lockservice/service_remote_test.go
- pkg/lockservice/txn.go
issue #11957
Fix some lockserivce fatal and panic.
> fix some lockservice panic

- pkg/txn/client/client.go
issue #11954
Fix deadlock in IterTxns
> fix txn deadlock in IterTxns

- pkg/sql/compile/compile.go
- test/distributed/cases/pessimistic_transaction/transaction_enhance.result
- test/distributed/cases/pessimistic_transaction/transaction_enhance.sql
- test/distributed/cases/pessimistic_transaction/ww_conflict.result
- test/distributed/cases/pessimistic_transaction/ww_conflict.sql
> fix : do not let other errors override the retry error

- pkg/vm/pipeline/pipeline.go
issue #11957 
return error if ctx is done in pipeline.Run
> pipeline return error if ctx is done

- pkg/vm/engine/disttae/util.go
> Type check failure.

- pkg/cnservice/server.go
- pkg/common/morpc/backend.go
- pkg/incrservice/store_sql.go
issue #11957 
Add some debug log.
> add some debug log

- pkg/vm/engine/tae/catalog/base.go
- pkg/vm/engine/tae/catalog/block.go
- pkg/vm/engine/tae/catalog/catalog.go
- pkg/vm/engine/tae/catalog/database.go
- pkg/vm/engine/tae/catalog/segment.go
- pkg/vm/engine/tae/catalog/table.go
- pkg/vm/engine/tae/db/test/db_test.go
- pkg/vm/engine/tae/logtail/handle.go
- pkg/vm/engine/tae/tables/blk.go
- pkg/vm/engine/tae/txn/txnimpl/txn_test.go
> fix data race in tableEntry.GetCreateTS()

- pkg/vm/engine/tae/db/checkpoint/runner.go
- pkg/vm/engine/tae/db/test/db_test.go
> fix global checkpoint

- pkg/vm/engine/tae/db/checkpoint/replay.go
- pkg/vm/engine/tae/db/checkpoint/testutils.go
- pkg/vm/engine/tae/db/db.go
- pkg/vm/engine/tae/db/test/catalog_test.go
- pkg/vm/engine/tae/db/test/compatibility/cases.go
- pkg/vm/engine/tae/db/test/compatibility/registry.go
- pkg/vm/engine/tae/db/test/db_test.go
- pkg/vm/engine/tae/db/test/replay_test.go
- pkg/vm/engine/tae/db/testutil/engine.go
- pkg/vm/engine/tae/logtail/utils.go
issue #12024 
Set CKP LSN and truncate LSN in `DB.ForceCheckpoint`
> fix checkpoint meta

- pkg/objectio/writer.go
issue #
Remove unnecessary warning logs
> Remove unnecessary warning logs

- pkg/frontend/authenticate.go
> [bug] fix nil pointer bug

- pkg/sql/compile/compile.go
- pkg/sql/compile/compile_test.go
> fix a bug will lost context deadline exceeded error

- pkg/txn/client/operator.go
- pkg/txn/util/log.go
- pkg/vm/engine/disttae/tools.go
- pkg/vm/engine/disttae/txn.go
- pkg/vm/engine/disttae/types.go
> Add some logs to locate why a table was not created.

- test/distributed/cases/pessimistic_transaction/isolation_1.sql
> remove #10701 bvt tag

- pkg/fileservice/aliyun_sdk.go
- pkg/fileservice/disk_cache.go
- pkg/fileservice/object_storage_arguments.go
issue https://github.com/matrixorigin/MO-Cloud/issues/706
> fileservice: add oidc_role_arn credential to AliyunSDK

- pkg/lockservice/cfg.go
- pkg/lockservice/lock_table_local.go
- pkg/lockservice/lock_table_local_test.go
- pkg/lockservice/service_test.go
- pkg/lockservice/test_helper.go
- pkg/lockservice/waiter.go
- pkg/lockservice/waiter_queue.go
- pkg/lockservice/waiter_queue_test.go
- pkg/lockservice/waiter_test.go
This reverts commit 95e2b3ffd828ff64c01f2116de79fe08d1f3b22a.
issue #
TPCC performance is speed down
> Revert "optimize deadlock check (#12056)"

- pkg/sql/compile/compile.go
https://github.com/matrixorigin/MO-Cloud/issues/1451
> fix count(const) from table

- .github/workflows/ci.yml
- .github/workflows/e2e-compose.yml
- .github/workflows/e2e-standalone.yml
- .github/workflows/e2e_upgrade.yml
- .github/workflows/merge-trigger.yaml
- .github/workflows/robot.yml
- pkg/fileservice/aliyun_sdk.go
- pkg/fileservice/disk_cache.go
- pkg/fileservice/object_storage_arguments.go
- test/distributed/cases/pessimistic_transaction/isolation_1.sql
excluding:
56562ae5ec1f9638d353c35d5c48438fc9e68add
95e2b3ffd828ff64c01f2116de79fe08d1f3b22a
> 7dabf36 0070abe

- pkg/lockservice/lock_table_local.go
- pkg/lockservice/service_test.go
- pkg/lockservice/txn.go
issue #11827
fix data race in lockservice/waiter
> fix waiter data race

- pkg/vm/engine/tae/logtail/handle.go
> add debug log

- go.mod
- pkg/cnservice/upgrader/newAddTable.go
- pkg/cnservice/upgrader/upgrader.go
- pkg/cnservice/upgrader/upgrader_test.go
- pkg/cnservice/upgrader/upgrader_util.go
- pkg/common/moerr/error.go
- pkg/util/export/table/table.go
- pkg/util/export/table/table_test.go
- pkg/util/sysview/sysview.go
- pkg/util/trace/impl/motrace/schema.go
- test/distributed/cases/database/system_table.result
- test/distributed/cases/database/system_variables.result
- test/distributed/cases/dml/show/database_statistics.result
- test/distributed/cases/dml/show/database_statistics.sql
- test/distributed/cases/log/query_sql_statement_hotspot.result
- test/distributed/cases/log/query_sql_statement_hotspot.sql
issue #11502, #11406 , #11655
1. Fix version compatibility bugs, submit upgrade code
2. Get hotspot SQL in system_metrics
> Cherry pick upgrate

- pkg/frontend/mysql_cmd_executor.go
> Port #11971 from main: A sequence of minor rewrite to executeStmt.

- pkg/util/trace/impl/motrace/mo_trace_test.go
issue #11864
changes:
1. skip cpu/trace case in UT TestMOSpan_doProfile, if cpu < 4
> try fix TestMOSpan_doProfile in low cpu dev

- pkg/vm/engine/tae/catalog/segment.go
- pkg/vm/engine/tae/db/merge/executor.go
- pkg/vm/engine/tae/db/merge/mod.go
- pkg/vm/engine/tae/db/merge/policyBasic.go
- pkg/vm/engine/tae/db/merge/policyOverlap.go
- pkg/vm/engine/tae/db/merge/utils.go
- pkg/vm/engine/tae/db/scannerop.go
- pkg/vm/engine/tae/tables/jobs/flushTableTail.go
- pkg/vm/engine/tae/tables/jobs/mergeblocks.go
issue #11891
reorganize codes related to block merging
> merge refactor phase 1

- pkg/frontend/compiler_context.go
issue #11978 
fix bug:unhandled exception in some case in stats function
> fix bug:unhandled exception in some case in stats function

- pkg/frontend/authenticate.go
- test/distributed/cases/database/system_variables.result
- test/distributed/cases/database/system_variables.sql
- test/distributed/cases/dml/select/sp_table.result
- test/distributed/cases/dml/select/sp_table.sql
- test/distributed/cases/tenant/tenant.result
- test/distributed/cases/tenant/tenant.test
issue #12043 
add unique index for mo_account table
> add unique index for mo_account table

- pkg/vm/engine/tae/tables/jobs/flushTableTail.go
issue #
This case is normal for now. Optimize it later
> remove unnecessary panic check

- pkg/cnservice/cnclient/client.go
> Add timeout for pipeline stream

- .github/workflows/merge-trigger-tke.yaml
> CI: Add trigger condition for tke

- pkg/sql/compile/compile.go
> Add missing recover

- pkg/fileservice/file_service.go
- pkg/fileservice/io.go
- pkg/fileservice/local_etl_fs.go
- pkg/fileservice/local_fs.go
- pkg/fileservice/s3_fs.go
issue #
fileservice: refine countingReader
fileservice: minor fixes
fileservice: remove IOVector.EntriesSize
fileservice: add bytes read counter to LocalFS
fileservice: add bytes read counter to S3FS
> fileservice: refactor read/write bytes counting

- .github/workflows/merge-trigger-tke.yaml
- .github/workflows/robot.yml
> CI: debug tke mergerun action

- pkg/sql/compile/ddl.go
- pkg/txn/util/log.go
- pkg/vm/engine/disttae/txn_database.go
> Add log to locate why table was not created

- pkg/lockservice/lock.go
- pkg/lockservice/lock_table_local.go
- pkg/lockservice/service_test.go
- pkg/lockservice/test_helper.go
- pkg/lockservice/waiter_events.go
- pkg/lockservice/waiter_queue.go
issue #12015
cherry pick fix to 1.0-dev
> Fix 12015 1.0 dev

- pkg/sql/colexec/server.go
- pkg/sql/compile/alter.go
- pkg/sql/compile/compile.go
- pkg/sql/compile/scopeRemoteRunTypes.go
- pkg/sql/plan/build_alter_table.go
- pkg/util/export/etl/db/db_holder.go
- pkg/util/export/etl/db/db_holder_test.go
- pkg/util/export/etl/sql_test.go
excluding:
854f07a3abb05d76ba45a2ac8a5416b0d7b1fd20
e4924fbb65ce780ee5890e6d104409dd4e32924f
> 854f07a 54d6827

- pkg/sql/compile/ddl.go
- pkg/vm/engine/disttae/txn_database.go
- pkg/vm/engine/tae/rpc/handle.go
issue #11917
* Specialize the debug log to reduce the amount of logging, although this can lead to table not found problems in other cases that may be difficult to locate, although common sysbench cases can be located.
> Prune the log of debug for 11917

- pkg/vm/engine/tae/rpc/handle.go
> Prune log for tae's rpc handle

- pkg/vm/engine/disttae/txn_database.go
> improve the preformace of log for debug

- pkg/sql/compile/ddl.go
- test/distributed/cases/sequence/alter_sequence.result
- test/distributed/cases/sequence/alter_sequence_1.result
- test/distributed/cases/sequence/alter_sequence_1.sql
- test/distributed/cases/sequence/create_sequence.result
Reverts matrixorigin/matrixone#12156
> Revert "fix alter sequence"

- pkg/sql/parsers/dialect/mysql/mysql_sql.go
- pkg/sql/parsers/dialect/mysql/mysql_sql.y
- test/distributed/cases/stage/stage.result
issue #12155 
fix create stage with comment
> fix create stage with comment

- pkg/vm/engine/disttae/txn_database.go
> Remove log for debug 11917

- pkg/hakeeper/task/task_scheduler.go
- pkg/taskservice/task_runner.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/1487
Add some log to 1.0-dev
> add some log

- pkg/frontend/mysql_cmd_executor.go
- pkg/frontend/session.go
- pkg/frontend/txn.go
Reverts matrixorigin/matrixone#12197
> Revert "update mo_sessions view"

- pkg/frontend/authenticate.go
- test/distributed/cases/database/system_variables.result
- test/distributed/cases/database/system_variables.sql
- test/distributed/cases/dml/select/sp_table.result
- test/distributed/cases/dml/select/sp_table.sql
- test/distributed/cases/tenant/tenant.result
- test/distributed/cases/tenant/tenant.test
add unique index for mo_account table
Approved by: @heni02, @qingxinhome
issue #
> add unique index for mo_account table (#12089)

- pkg/cnservice/server_heartbeat.go
- pkg/util/metric/v2/hakeeper_metric.go
- pkg/util/metric/v2/metrics.go
part of #12219 
This PR introduce CN heartbeat histogram and CN heartbeat failure total metric to monitor CN heartbeat.
> feat: add CN heartbeat metric

- pkg/cnservice/server_heartbeat.go
- pkg/util/metric/v2/hakeeper_metric.go
- pkg/util/metric/v2/metrics.go
> cherry-pick: feat: add CN heartbeat metric

- pkg/vm/engine/tae/catalog/segment.go
- pkg/vm/engine/tae/catalog/table.go
- pkg/vm/engine/tae/db/merge/executor.go
- pkg/vm/engine/tae/db/merge/utils.go
- pkg/vm/engine/tae/index/zm.go
issue #12232
- pretty zm string
- set lower bound of available memory zero
> fix slice out of range when considering available mem

- pkg/util/export/batch_processor.go
issue #https://github.com/matrixorigin/matrixone/issues/12275
changes:
- adapt mo collector, which handle export log/trace/metric data in mo, do log support disacardable.
> Cover log discardable, pick from #12286

- test/distributed/cases/pessimistic_transaction/unique_secondary_index.sql
issue #
https://github.com/matrixorigin/matrixone/issues/12305
> addTag12305

- CODEOWNERS
- pkg/txn/rpc/sender.go
- pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
> fix some metrics and update code owners

- pkg/vm/engine/disttae/txn.go
> Remove a verbose log line.

- pkg/util/metric/v2/dashboard/grafana_dashboard_logtail.go
- pkg/util/metric/v2/logtail.go
- pkg/util/metric/v2/metrics.go
- pkg/vm/engine/tae/logtail/handle.go
issue #
add some logtail checkpoint metrics cherry pick
> add some logtail checkpoint metrics

- pkg/util/metric/v2/dashboard/grafana_dashboard.go
- pkg/util/metric/v2/dashboard/grafana_dashboard_fs.go
- pkg/util/metric/v2/dashboard/grafana_dashboard_logtail.go
- pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
- pkg/util/metric/v2/txn.go
issue #
update metrics dashboard.
> update metrics dashboard

- pkg/vm/engine/tae/db/test/db_test.go
- pkg/vm/engine/tae/txn/txnimpl/table.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/1398
> fix TryDeleteByDeltaloc, cherry pick #12278

- pkg/sql/compile/ddl.go
- test/distributed/cases/sequence/alter_sequence.result
- test/distributed/cases/sequence/alter_sequence_1.result
- test/distributed/cases/sequence/alter_sequence_1.sql
- test/distributed/cases/sequence/create_sequence.result
issue #12088 
fix alter sequence
> fix alter sequence (cherry-pick 1.0-dev)

- pkg/frontend/compiler_context.go
- pkg/sql/compile/types.go
- pkg/vm/engine/disttae/tabledef_util.go
- pkg/vm/engine/disttae/txn.go
issue #12235
cherry-pick from main： Fix the issue of missing cluster by information when obtaining table definitions
> Handle sortcluster by column (#12312)

- pkg/proxy/client_conn.go
- pkg/proxy/error.go
- pkg/proxy/handler.go
- pkg/proxy/tunnel.go
issue #12258
Clean proxy logs which are not needed in prod env.
> [refactor] proxy: clean proxy logs.

- pkg/hakeeper/checkers/logservice/check.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/1487
Add some error log for hakeeper
> add error log for hakeeper

- pkg/util/metric/v2/dashboard/grafana_dashboard.go
- pkg/util/metric/v2/dashboard/grafana_dashboard_logtail.go
- pkg/util/metric/v2/dashboard/grafana_dashboard_task.go
- pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
- pkg/util/metric/v2/logtail.go
- pkg/util/metric/v2/metrics.go
- pkg/util/metric/v2/tn_task.go
- pkg/util/metric/v2/txn.go
- pkg/vm/engine/tae/catalog/segment.go
- pkg/vm/engine/tae/catalog/table.go
- pkg/vm/engine/tae/db/checkpoint/entry.go
- pkg/vm/engine/tae/db/checkpoint/runner.go
- pkg/vm/engine/tae/logtail/service/server.go
- pkg/vm/engine/tae/logtail/txn_handle.go
- pkg/vm/engine/tae/tables/jobs/flushTableTail.go
- pkg/vm/engine/tae/txn/txnimpl/store.go
issue #12223 #10337 #12260
adding some metrics:
1. log tail collecting duration histogram
2. log tail subscription request counter
3. ckp pending duration histogram
4. flush table duration histogram
5. txn prepare duration histogram
change the log level of tableEntry.RemoveEntry and segmentEntry.RemoveEntry to debug
> add some metrics for tn

- pkg/backup/backup_test.go
> Fix TestBackupData

- test/distributed/cases/stage/stage.result
- test/distributed/cases/stage/stage.sql
> remove issue tag

- .github/workflows/merge-trigger.yaml
> CI: change runner to tke

- pkg/hakeeper/checkers/logservice/check.go
issue #https://github.com/matrixorigin/MO-Cloud/issues/1487
Do not return directly when creating operators returns error.
> do not return directly when creating operators returns error

- pkg/frontend/compiler_context.go
- pkg/sql/colexec/s3util.go
- pkg/sql/compile/debugTools.go
- pkg/sql/compile/types.go
- pkg/vm/engine/disttae/tabledef_util.go
- pkg/vm/engine/disttae/txn.go
> cherry pick clusterby fix to 1.0-dev

- pkg/frontend/compiler_context.go
- pkg/sql/util/util.go
issue # https://github.com/matrixorigin/MO-Cloud/issues/1562
need to set accountID in context to access metadata for system.statement_info
> fix a bug that cause wrong stats for normal account

- pkg/fileservice/s3_fs.go
> fileservice: do not cache IOEntry to disk

- pkg/util/metric/v2/dashboard/grafana_dashboard_task.go
- pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
- pkg/util/metric/v2/metrics.go
- pkg/util/metric/v2/task.go
- pkg/util/metric/v2/txn.go
- pkg/vm/engine/disttae/txn_table.go
- pkg/vm/engine/tae/db/merge/executor.go
- pkg/vm/engine/tae/rpc/handle.go
- pkg/vm/engine/tae/txn/txnbase/txnmgr.go
- pkg/vm/engine/tae/txn/txnimpl/store.go
issue #
add some metrics:
1. txn OnPrepareWal duration Histogram
2. txn Dequeue Preparing Duration Histogram
3. txn Dequeue Prepared Duration Histogram
4. txn Handle Commit But Before Txn.Commit Duration Histogram
5. task Merge Scheduled times Counter
6. task Merged Block count Each Schedule Counter
7. task Merged Size Each Scheduler Counter
8. txn fast loading object meta counter in oneRangePart
> add more metrics for tn

- pkg/sql/colexec/s3util.go
issue #
changes:
- fix CN do batch write default size as 10MiB
> fix CN do batch write default size as 10MiB

- pkg/sql/colexec/s3util.go
> 1.0dev-pick: clean some unnecessary info logs (#12295)

- pkg/sql/colexec/s3util.go
Reverts matrixorigin/matrixone#12388
> Revert "fix CN do batch write default size as 10MiB"

- pkg/proxy/label_info_test.go
- pkg/proxy/rebalancer_test.go
Approved by: @volgariver6
close #12347
> test: fix data race in rebalancer test (#12363)

- pkg/txn/client/timestamp_waiter_test.go
- pkg/util/address/address.go
- pkg/util/address/address_test.go
- pkg/vm/engine/disttae/logtailPushModel.go
> [bug] logtail: too many connection error messages after restart.

- pkg/frontend/mysql_cmd_executor.go
- pkg/frontend/routine.go
- pkg/frontend/session.go
fix kill query stmt status
issue #
> fix kill query stmt status(1.0-dev)

- pkg/sql/plan/query_builder.go
- pkg/sql/plan/utils.go
- test/distributed/cases/function/func_datetime_now.result
- test/distributed/cases/function/func_datetime_now.test
fix constant fold
Approved by: @heni02, @aunjgr
issue #
> fix time related function plan cache (1.0-dev)

- pkg/sql/colexec/deletion/types.go
> fix-issue-11856

- pkg/util/export/etl/db/db_holder.go
> For Dev1.0: Remove unnecessary retry

- etc/launch-tae-compose/compose.yaml
> CI: change healthcheck and release

- pkg/fileservice/caching_file_service_test.go
- pkg/fileservice/disk_cache.go
- pkg/fileservice/disk_cache_test.go
- pkg/fileservice/file_cache.go
- pkg/fileservice/s3_fs.go
- pkg/perfcounter/counter_set.go
> Pick file service changes

- pkg/sql/plan/build_constraint_util.go
- pkg/sql/plan/build_insert.go
This reverts commit aa74ee52a031792f57b38dc6b8e9933e81f68cd9.
issue #
> Revert "imporve: use in expr to check PK dup (#12447)"

- pkg/common/moerr/error.go
- pkg/proxy/rebalancer.go
- pkg/proxy/tunnel.go
issue #
Too many error logs which are not error level, so do not log these logs.
> [enhancement] proxy: reduce some log messages.

- .github/workflows/ci.yml
- .github/workflows/merge-trigger-tke.yml
- .github/workflows/utils.yaml
> CI: Remove eks mergerun in 1.0 dev

- pkg/fileservice/aliyun_sdk.go
> fileservice: get upstream credentials in provider function

- pkg/sql/plan/opt_misc.go
- pkg/sql/plan/query_builder.go
- pkg/sql/plan/stats.go
- pkg/sql/plan/utils.go
- test/distributed/cases/join/leftjoin.result
- test/distributed/cases/join/leftjoin.test
- test/distributed/cases/optimizer/pushdown.result
issue #
fix a bug for optimize rule of left join
> resubmit optimize rule: remove effectless left joins

- pkg/sql/colexec/table_function/metadata_scan.go
- pkg/vm/engine/disttae/txn_table.go
> add log for metadata scan
